TModLoader: Terraria.Main.DrawInventory
DrawInventory()
void Terraria.Main.DrawInventory () inline protected
Definition at line 52756 of file Main.cs.
    {
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0300: Unknown result type (might be due to invalid IL or missing references)
        //IL_0306: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_0395: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_040e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0413: Unknown result type (might be due to invalid IL or missing references)
        //IL_06da: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_060d: Unknown result type (might be due to invalid IL or missing references)
        //IL_061f: Unknown result type (might be due to invalid IL or missing references)
        //IL_062b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0631: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f11: Unknown result type (might be due to invalid IL or missing references)
        //IL_1257: Unknown result type (might be due to invalid IL or missing references)
        //IL_1259: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f94: Unknown result type (might be due to invalid IL or missing references)
        //IL_1497: Unknown result type (might be due to invalid IL or missing references)
        //IL_1499: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f86: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fa4: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fab: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fe2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2fe9: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ffb: Unknown result type (might be due to invalid IL or missing references)
        //IL_3014: Unknown result type (might be due to invalid IL or missing references)
        //IL_3020: Unknown result type (might be due to invalid IL or missing references)
        //IL_3026: Unknown result type (might be due to invalid IL or missing references)
        //IL_2068: Unknown result type (might be due to invalid IL or missing references)
        //IL_207b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1030: Unknown result type (might be due to invalid IL or missing references)
        //IL_16d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_16db: Unknown result type (might be due to invalid IL or missing references)
        //IL_16e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_16e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_16e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_16ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bbc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aba: Unknown result type (might be due to invalid IL or missing references)
        //IL_2142: Unknown result type (might be due to invalid IL or missing references)
        //IL_2149: Unknown result type (might be due to invalid IL or missing references)
        //IL_214f: Unknown result type (might be due to invalid IL or missing references)
        //IL_134b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1786: Unknown result type (might be due to invalid IL or missing references)
        //IL_1788: Unknown result type (might be due to invalid IL or missing references)
        //IL_170b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1730: Unknown result type (might be due to invalid IL or missing references)
        //IL_1759: Unknown result type (might be due to invalid IL or missing references)
        //IL_1766: Unknown result type (might be due to invalid IL or missing references)
        //IL_176d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1777: Unknown result type (might be due to invalid IL or missing references)
        //IL_177c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be6: Unknown result type (might be due to invalid IL or missing references)
        //IL_307e: Unknown result type (might be due to invalid IL or missing references)
        //IL_31ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_31bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_31d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_31dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_31df: Unknown result type (might be due to invalid IL or missing references)
        //IL_31e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_3216: Unknown result type (might be due to invalid IL or missing references)
        //IL_321d: Unknown result type (might be due to invalid IL or missing references)
        //IL_322f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3248: Unknown result type (might be due to invalid IL or missing references)
        //IL_3254: Unknown result type (might be due to invalid IL or missing references)
        //IL_325a: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_21f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_21fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_2204: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c26: Unknown result type (might be due to invalid IL or missing references)
        //IL_3189: Unknown result type (might be due to invalid IL or missing references)
        //IL_3190: Unknown result type (might be due to invalid IL or missing references)
        //IL_3196: Unknown result type (might be due to invalid IL or missing references)
        //IL_1efe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f17: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f21: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f26: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f35: Unknown result type (might be due to invalid IL or missing references)
        //IL_120c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1211: Unknown result type (might be due to invalid IL or missing references)
        //IL_121b: Unknown result type (might be due to invalid IL or missing references)
        //IL_32b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1fee: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ff5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ffb: Unknown result type (might be due to invalid IL or missing references)
        //IL_158c: Unknown result type (might be due to invalid IL or missing references)
        //IL_33bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_33c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_33ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b76: Unknown result type (might be due to invalid IL or missing references)
        //IL_2b94: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ba0: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ba6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1474: Unknown result type (might be due to invalid IL or missing references)
        //IL_147b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1481: Unknown result type (might be due to invalid IL or missing references)
        //IL_144e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1450: Unknown result type (might be due to invalid IL or missing references)
        //IL_2c93: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cae: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ccc: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cd8: Unknown result type (might be due to invalid IL or missing references)
        //IL_2cde: Unknown result type (might be due to invalid IL or missing references)
        //IL_3444: Unknown result type (might be due to invalid IL or missing references)
        //IL_3455: Unknown result type (might be due to invalid IL or missing references)
        //IL_345a: Unknown result type (might be due to invalid IL or missing references)
        //IL_345f: Unknown result type (might be due to invalid IL or missing references)
        //IL_16b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_16be: Unknown result type (might be due to invalid IL or missing references)
        //IL_16c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1691: Unknown result type (might be due to invalid IL or missing references)
        //IL_1693: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2d3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2663: Unknown result type (might be due to invalid IL or missing references)
        //IL_2668: Unknown result type (might be due to invalid IL or missing references)
        //IL_266a: Unknown result type (might be due to invalid IL or missing references)
        //IL_266f: Unknown result type (might be due to invalid IL or missing references)
        //IL_2918: Unknown result type (might be due to invalid IL or missing references)
        //IL_2927: Unknown result type (might be due to invalid IL or missing references)
        //IL_293e: Unknown result type (might be due to invalid IL or missing references)
        //IL_2948: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1aed: Unknown result type (might be due to invalid IL or missing references)
        //IL_1af2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2edb: Unknown result type (might be due to invalid IL or missing references)
        //IL_2eec: Unknown result type (might be due to invalid IL or missing references)
        //IL_2ef1: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f16: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f23: Unknown result type (might be due to invalid IL or missing references)
        //IL_2f2a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b50: Unknown result type (might be due to invalid IL or missing references)
        //IL_1b55: Unknown result type (might be due to invalid IL or missing references)
        //IL_3795: Unknown result type (might be due to invalid IL or missing references)
        //IL_353f: Unknown result type (might be due to invalid IL or missing references)
        //IL_24b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c48: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c57: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1c6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bb3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1bb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_3934: Unknown result type (might be due to invalid IL or missing references)
        //IL_363d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3644: Unknown result type (might be due to invalid IL or missing references)
        //IL_364a: Unknown result type (might be due to invalid IL or missing references)
        //IL_27f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_2803: Unknown result type (might be due to invalid IL or missing references)
        //IL_2808: Unknown result type (might be due to invalid IL or missing references)
        //IL_283b: Unknown result type (might be due to invalid IL or missing references)
        //IL_2842: Unknown result type (might be due to invalid IL or missing references)
        //IL_2848: Unknown result type (might be due to invalid IL or missing references)
        //IL_284f: Unknown result type (might be due to invalid IL or missing references)
        //IL_386f: Unknown result type (might be due to invalid IL or missing references)
        //IL_3890: Unknown result type (might be due to invalid IL or missing references)
        //IL_389a: Unknown result type (might be due to invalid IL or missing references)
        //IL_38a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_38ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ce6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1cf5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d01: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d32: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d41: Unknown result type (might be due to invalid IL or missing references)
        //IL_39f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a01: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_3a13: Unknown result type (might be due to invalid IL or missing references)
        //IL_2585: Unknown result type (might be due to invalid IL or missing references)
        //IL_2596: Unknown result type (might be due to invalid IL or missing references)
        //IL_259b: Unknown result type (might be due to invalid IL or missing references)
        //IL_25c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_25c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_25cc: Unknown result type (might be due to invalid IL or missing references)
        Recipe.GetThroughDelayedFindRecipes();
        if (ShouldPVPDraw)
        {
            DrawPVPIcons();
        }
        int num = 0;
        int num30 = 0;
        int num41 = screenWidth;
        int num51 = 0;
        int num61 = screenWidth;
        int num71 = 0;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)num, (float)num30);
        new Vector2((float)num41, (float)num51);
        new Vector2((float)num61, (float)num71);
        DrawBestiaryIcon(num, num30);
        DrawEmoteBubblesButton(num, num30);
        DrawTrashItemSlot(num, num30);
        spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[4].Value, new Vector2(40f, 0f) + vector, new Color((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        inventoryScale = 0.85f;
        if (mouseX > 20 && mouseX < (int)(20f + 560f * inventoryScale) && mouseY > 20 && mouseY < (int)(20f + 280f * inventoryScale) && !PlayerInput.IgnoreMouseInterface)
        {
            player[myPlayer].mouseInterface = true;
        }
        for (int i = 0; i < 10; i++)
        {
            for (int j = 0; j < 5; j++)
            {
                int num81 = (int)(20f + (float)(i * 56) * inventoryScale) + num;
                int num92 = (int)(20f + (float)(j * 56) * inventoryScale) + num30;
                int num103 = i + j * 10;
                new Color(100, 100, 100, 100);
                if (mouseX >= num81 && (float)mouseX <= (float)num81 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num92 && (float)mouseY <= (float)num92 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    ItemSlot.OverrideHover(player[myPlayer].inventory, 0, num103);
                    if (player[myPlayer].inventoryChestStack[num103] && (player[myPlayer].inventory[num103].type == 0 || player[myPlayer].inventory[num103].stack == 0))
                    {
                        player[myPlayer].inventoryChestStack[num103] = false;
                    }
                    if (!player[myPlayer].inventoryChestStack[num103])
                    {
                        ItemSlot.LeftClick(player[myPlayer].inventory, 0, num103);
                        ItemSlot.RightClick(player[myPlayer].inventory, 0, num103);
                        if (mouseLeftRelease && mouseLeft)
{
                            Recipe.FindRecipes();
                        }
                    }
                    ItemSlot.MouseHover(player[myPlayer].inventory, 0, num103);
                }
                ItemSlot.Draw(spriteBatch, player[myPlayer].inventory, 0, num103, new Vector2((float)num81, (float)num92));
            }
        }
        int activeToggles = BuilderToggleLoader.ActiveBuilderToggles();
        bool pushSideToolsUp = activeToggles / 12 != BuilderToggleLoader.BuilderTogglePage || activeToggles % 12 >= 10;
        if (!PlayerInput.UsingGamepad)
        {
            DrawHotbarLockIcon(num, num30, pushSideToolsUp);
        }
        ItemSlot.DrawRadialDpad(spriteBatch, new Vector2(20f) + new Vector2(56f * inventoryScale * 10f, 56f * inventoryScale * 5f) + new Vector2(26f, 70f) + vector);
        if (_achievementAdvisor.CanDrawAboveCoins)
        {
            int num2 = (int)(20f + 560f * inventoryScale) + num;
            int num13 = (int)(20f + 0f * inventoryScale) + num30;
            _achievementAdvisor.DrawOneAchievement(spriteBatch, new Vector2((float)num2, (float)num13) + new Vector2(5f), large: true);
        }
        if (mapEnabled)
        {
            bool flag = false;
            int num22 = num41 - 440;
            int num23 = 40 + num51;
            if (screenWidth < 940)
            {
                flag = true;
            }
            if (flag)
            {
                num22 = num61 - 40;
                num23 = num71 - 200;
            }
            int num24 = 0;
            for (int k = 0; k < 4; k++)
            {
                int num25 = 255;
                int num26 = num22 + k * 32 - num24;
                int num27 = num23;
                if (flag)
                {
                    num26 = num22;
                    num27 = num23 + k * 32 - num24;
                }
                int num28 = k;
                num25 = 120;
                if (k > 0 && mapStyle == k - 1)
                {
                    num25 = 200;
                }
                if (mouseX >= num26 && mouseX <= num26 + 32 && mouseY >= num27 && mouseY <= num27 + 30 && !PlayerInput.IgnoreMouseInterface)
                {
                    num25 = 255;
                    num28 += 4;
                    player[myPlayer].mouseInterface = true;
                    if (mouseLeft && mouseLeftRelease)
                    {
                        if (k == 0)
{
                            playerInventory = false;
                            player[myPlayer].SetTalkNPC(-1);
                            npcChatCornerItem = 0;
                            SoundEngine.PlaySound(10);
                            mapFullscreenScale = 2.5f;
                            mapFullscreen = true;
                            resetMapFull = true;
                        }
                        if (k == 1)
{
                            mapStyle = 0;
                            SoundEngine.PlaySound(12);
                        }
                        if (k == 2)
{
                            mapStyle = 1;
                            SoundEngine.PlaySound(12);
                        }
                        if (k == 3)
{
                            mapStyle = 2;
                            SoundEngine.PlaySound(12);
                        }
                    }
                }
                spriteBatch.Draw(TextureAssets.MapIcon[num28].Value, new Vector2((float)num26, (float)num27), (Rectangle?)new Rectangle(0, 0, TextureAssets.MapIcon[num28].Width(), TextureAssets.MapIcon[num28].Height()), new Color(num25, num25, num25, num25), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
        }
        if (armorHide)
        {
            armorAlpha -= 0.1f;
            if (armorAlpha < 0f)
            {
                armorAlpha = 0f;
            }
        }
        else
        {
            armorAlpha += 0.025f;
            if (armorAlpha > 1f)
            {
                armorAlpha = 1f;
            }
        }
        new Color((int)(byte)((float)(int)mouseTextColor * armorAlpha), (int)(byte)((float)(int)mouseTextColor * armorAlpha), (int)(byte)((float)(int)mouseTextColor * armorAlpha), (int)(byte)((float)(int)mouseTextColor * armorAlpha));
        armorHide = false;
        int num29 = 8 + player[myPlayer].GetAmountOfExtraAccessorySlotsToShow();
        int num31 = 174 + mH;
        int num32 = 950;
        _cannotDrawAccessoriesHorizontally = false;
        if (screenHeight < num32 && num29 >= 10)
        {
            num31 -= (int)(56f * inventoryScale * (float)(num29 - 9));
            _cannotDrawAccessoriesHorizontally = true;
        }
        int num33 = DrawPageIcons(num31 - 32);
        if (num33 > -1)
        {
            HoverItem = new Item();
            switch (num33)
            {
            case 1:
                hoverItemName = Lang.inter[80].Value;
                break;
            case 2:
                hoverItemName = Lang.inter[79].Value;
                break;
            case 3:
                hoverItemName = (CaptureModeDisabled ? Lang.inter[115].Value : Lang.inter[81].Value);
                break;
            }
        }
        if (EquipPage == 2)
        {
            Point value = default(Point);
            ((Point)(ref value))._002Ector(mouseX, mouseY);
            Rectangle r = default(Rectangle);
            ((Rectangle)(ref r))._002Ector(0, 0, (int)((float)TextureAssets.InventoryBack.Width() * inventoryScale), (int)((float)TextureAssets.InventoryBack.Height() * inventoryScale));
            Item[] inv = player[myPlayer].miscEquips;
            int num34 = screenWidth - 92;
            int num35 = mH + 174;
            Rectangle r2 = default(Rectangle);
            for (int l = 0; l < 2; l++)
            {
                switch (l)
                {
                case 0:
                    inv = player[myPlayer].miscEquips;
                    break;
                case 1:
                    inv = player[myPlayer].miscDyes;
                    break;
                }
                r.X = num34 + l * -47;
                for (int m = 0; m < 5; m++)
                {
                    int context = 0;
                    int num36 = -1;
                    bool flag5 = false;
                    switch (m)
                    {
                    case 0:
                        context = 19;
                        num36 = 0;
                        break;
                    case 1:
                        context = 20;
                        num36 = 1;
                        break;
                    case 2:
                        context = 18;
                        flag5 = player[myPlayer].unlockedSuperCart;
                        break;
                    case 3:
                        context = 17;
                        break;
                    case 4:
                        context = 16;
                        break;
                    }
                    if (l == 1)
                    {
                        context = 33;
                        num36 = -1;
                        flag5 = false;
                    }
                    r.Y = num35 + m * 47;
                    bool flag6 = false;
                    Texture2D value2 = TextureAssets.InventoryTickOn.Value;
                    ((Rectangle)(ref r2))._002Ector(((Rectangle)(ref r)).Left + 34, ((Rectangle)(ref r)).Top - 2, value2.Width, value2.Height);
                    int num37 = 0;
                    if (num36 != -1)
                    {
                        if (player[myPlayer].hideMisc[num36])
{
                            value2 = TextureAssets.InventoryTickOff.Value;
                        }
                        if (((Rectangle)(ref r2)).Contains(value) && !PlayerInput.IgnoreMouseInterface)
{
                            player[myPlayer].mouseInterface = true;
                            flag6 = true;
                            if (mouseLeft && mouseLeftRelease)
{
                                if (num36 == 0)
{
                                    player[myPlayer].TogglePet();
                                }
                                if (num36 == 1)
{
                                    player[myPlayer].ToggleLight();
                                }
                                mouseLeftRelease = false;
                                SoundEngine.PlaySound(12);
                                if (netMode == 1)
{
                                    NetMessage.SendData(4, -1, -1, null, myPlayer);
                                }
                            }
                            num37 = ((!player[myPlayer].hideMisc[num36]) ? 1 : 2);
                        }
                    }
                    if (flag5)
                    {
                        value2 = TextureAssets.Extra[255].Value;
                        if (!player[myPlayer].enabledSuperCart)
{
                            value2 = TextureAssets.Extra[256].Value;
                        }
                        ((Rectangle)(ref r2))._002Ector(r2.X + r2.Width / 2, r2.Y + r2.Height / 2, r2.Width, r2.Height);
                        ((Rectangle)(ref r2)).Offset(-r2.Width / 2, -r2.Height / 2);
                        if (((Rectangle)(ref r2)).Contains(value) && !PlayerInput.IgnoreMouseInterface)
{
                            player[myPlayer].mouseInterface = true;
                            flag6 = true;
                            if (mouseLeft && mouseLeftRelease)
{
                                player[myPlayer].enabledSuperCart = !player[myPlayer].enabledSuperCart;
                                mouseLeftRelease = false;
                                SoundEngine.PlaySound(12);
                                if (netMode == 1)
{
                                    NetMessage.SendData(4, -1, -1, null, myPlayer);
                                }
                            }
                            num37 = ((!player[myPlayer].enabledSuperCart) ? 1 : 2);
                        }
                    }
                    if (((Rectangle)(ref r)).Contains(value) && !flag6 && !PlayerInput.IgnoreMouseInterface)
                    {
                        player[myPlayer].mouseInterface = true;
                        armorHide = true;
                        ItemSlot.Handle(inv, context, m);
                    }
                    ItemSlot.Draw(spriteBatch, inv, context, m, r.TopLeft());
                    if (num36 != -1)
                    {
                        spriteBatch.Draw(value2, r2.TopLeft(), Color.White * 0.7f);
                        if (num37 > 0)
{
                            HoverItem = new Item();
                            hoverItemName = Lang.inter[58 + num37].Value;
                        }
                    }
                    if (flag5)
                    {
                        spriteBatch.Draw(value2, r2.TopLeft(), Color.White);
                        if (num37 > 0)
{
                            HoverItem = new Item();
                            hoverItemName = Language.GetTextValue((num37 == 1) ? "GameUI.SuperCartDisabled" : "GameUI.SuperCartEnabled");
                        }
                    }
                }
            }
            num35 += 247;
            num34 += 8;
            int num38 = -1;
            int num39 = 0;
            int num40 = 3;
            int num42 = 260;
            if (screenHeight > 630 + num42 * (mapStyle == 1).ToInt())
            {
                num40++;
            }
            if (screenHeight > 680 + num42 * (mapStyle == 1).ToInt())
            {
                num40++;
            }
            if (screenHeight > 730 + num42 * (mapStyle == 1).ToInt())
            {
                num40++;
            }
            int num43 = 46;
            Point point = default(Point);
            for (int n = 0; n < Player.maxBuffs; n++)
            {
                if (player[myPlayer].buffType[n] != 0)
                {
                    int num44 = num39 / num40;
                    int num45 = num39 % num40;
                    ((Point)(ref point))._002Ector(num34 + num44 * -num43, num35 + num45 * num43);
                    num38 = DrawBuffIcon(num38, n, point.X, point.Y);
                    UILinkPointNavigator.SetPosition(9000 + num39, new Vector2((float)(point.X + 30), (float)(point.Y + 30)));
                    num39++;
                    if (buffAlpha[n] < 0.65f)
                    {
                        buffAlpha[n] = 0.65f;
                    }
                }
            }
            UILinkPointNavigator.Shortcuts.BUFFS_DRAWN = num39;
            UILinkPointNavigator.Shortcuts.BUFFS_PER_COLUMN = num40;
            if (num38 >= 0)
            {
                int num46 = player[myPlayer].buffType[num38];
                if (num46 > 0)
                {
                    string buffName = Lang.GetBuffName(num46);
                    string buffTooltip = GetBuffTooltip(player[myPlayer], num46);
                    if (num46 == 147)
                    {
                        bannerMouseOver = true;
                    }
                    int rare = 0;
                    if (meleeBuff[num46])
                    {
                        rare = -10;
                    }
                    BuffLoader.ModifyBuffText(num46, ref buffName, ref buffTooltip, ref rare);
                    MouseTextHackZoom(buffName, rare, 0, buffTooltip);
                }
            }
        }
        else if (EquipPage == 1)
        {
            DrawNPCHousesInUI();
        }
        else if (EquipPage == 0)
        {
            int num47 = 4;
            if (mouseX > screenWidth - 64 - 28 && mouseX < (int)((float)(screenWidth - 64 - 28) + 56f * inventoryScale) && mouseY > num31 && mouseY < (int)((float)num31 + 448f * inventoryScale) && !PlayerInput.IgnoreMouseInterface)
            {
                player[myPlayer].mouseInterface = true;
            }
            float num48 = inventoryScale;
            bool flag7 = false;
            int num49 = num29 - 1;
            bool flag8 = LocalPlayer.CanDemonHeartAccessoryBeShown();
            bool flag9 = LocalPlayer.CanMasterModeAccessoryBeShown();
            if (_settingsButtonIsPushedToSide)
            {
                num49--;
            }
            Color color = inventoryBack;
            Color color2 = default(Color);
            ((Color)(ref color2))._002Ector(80, 80, 80, 80);
            DrawLoadoutButtons(num31, flag8, flag9);
            int num50 = -1;
            Rectangle rectangle = default(Rectangle);
            for (int num52 = 0; num52 < 3; num52++)
            {
                if ((num52 == 8 && !flag8) || (num52 == 9 && !flag9))
                {
                    continue;
                }
                num50++;
                bool flag10 = LocalPlayer.IsItemSlotUnlockedAndUsable(num52);
                if (!flag10)
                {
                    flag7 = true;
                }
                int num53 = screenWidth - 64 - 28;
                int num54 = (int)((float)num31 + (float)(num50 * 56) * inventoryScale);
                new Color(100, 100, 100, 100);
                int num55 = screenWidth - 58;
                int num56 = (int)((float)(num31 - 2) + (float)(num50 * 56) * inventoryScale);
                int context2 = 8;
                if (num52 > 2)
                {
                    num54 += num47;
                    num56 += num47;
                    context2 = 10;
                }
                Texture2D value3 = TextureAssets.InventoryTickOn.Value;
                if (player[myPlayer].hideVisibleAccessory[num52])
                {
                    value3 = TextureAssets.InventoryTickOff.Value;
                }
                ((Rectangle)(ref rectangle))._002Ector(num55, num56, value3.Width, value3.Height);
                int num57 = 0;
                if (num52 > 2 && ((Rectangle)(ref rectangle)).Contains(new Point(mouseX, mouseY)) && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    if (mouseLeft && mouseLeftRelease)
                    {
                        player[myPlayer].hideVisibleAccessory[num52] = !player[myPlayer].hideVisibleAccessory[num52];
                        SoundEngine.PlaySound(12);
                        if (netMode == 1)
{
                            NetMessage.SendData(4, -1, -1, null, myPlayer);
                        }
                    }
                    num57 = ((!player[myPlayer].hideVisibleAccessory[num52]) ? 1 : 2);
                }
                else if (mouseX >= num53 && (float)mouseX <= (float)num53 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num54 && (float)mouseY <= (float)num54 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    armorHide = true;
                    player[myPlayer].mouseInterface = true;
                    ItemSlot.OverrideHover(player[myPlayer].armor, context2, num52);
                    if (flag10 || mouseItem.IsAir)
                    {
                        ItemSlot.LeftClick(player[myPlayer].armor, context2, num52);
                    }
                    ItemSlot.MouseHover(player[myPlayer].armor, context2, num52);
                }
                if (flag7)
                {
                    inventoryBack = color2;
                }
                ItemSlot.Draw(spriteBatch, player[myPlayer].armor, context2, num52, new Vector2((float)num53, (float)num54));
                if (num52 > 2)
                {
                    spriteBatch.Draw(value3, new Vector2((float)num55, (float)num56), Color.White * 0.7f);
                    if (num57 > 0)
                    {
                        HoverItem = new Item();
                        hoverItemName = Lang.inter[58 + num57].Value;
                    }
                }
            }
            inventoryBack = color;
            if (mouseX > screenWidth - 64 - 28 - 47 && mouseX < (int)((float)(screenWidth - 64 - 20 - 47) + 56f * inventoryScale) && mouseY > num31 && mouseY < (int)((float)num31 + 168f * inventoryScale) && !PlayerInput.IgnoreMouseInterface)
            {
                player[myPlayer].mouseInterface = true;
            }
            num50 = -1;
            for (int num58 = 10; num58 < 13; num58++)
            {
                if ((num58 == 18 && !flag8) || (num58 == 19 && !flag9))
                {
                    continue;
                }
                num50++;
                bool num114 = LocalPlayer.IsItemSlotUnlockedAndUsable(num58);
                flag7 = !num114;
                bool flag11 = !num114 && !mouseItem.IsAir;
                int num59 = screenWidth - 64 - 28 - 47;
                int num60 = (int)((float)num31 + (float)(num50 * 56) * inventoryScale);
                new Color(100, 100, 100, 100);
                if (num58 > 12)
                {
                    num60 += num47;
                }
                int context3 = 9;
                if (num58 > 12)
                {
                    context3 = 11;
                }
                if (mouseX >= num59 && (float)mouseX <= (float)num59 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num60 && (float)mouseY <= (float)num60 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    armorHide = true;
                    ItemSlot.OverrideHover(player[myPlayer].armor, context3, num58);
                    if (!flag11)
                    {
                        ItemSlot.LeftClick(player[myPlayer].armor, context3, num58);
                        ItemSlot.RightClick(player[myPlayer].armor, context3, num58);
                    }
                    ItemSlot.MouseHover(player[myPlayer].armor, context3, num58);
                }
                if (flag7)
                {
                    inventoryBack = color2;
                }
                ItemSlot.Draw(spriteBatch, player[myPlayer].armor, context3, num58, new Vector2((float)num59, (float)num60));
            }
            inventoryBack = color;
            if (mouseX > screenWidth - 64 - 28 - 47 && mouseX < (int)((float)(screenWidth - 64 - 20 - 47) + 56f * inventoryScale) && mouseY > num31 && mouseY < (int)((float)num31 + 168f * inventoryScale) && !PlayerInput.IgnoreMouseInterface)
            {
                player[myPlayer].mouseInterface = true;
            }
            num50 = -1;
            for (int num62 = 0; num62 < 3; num62++)
            {
                if ((num62 == 8 && !flag8) || (num62 == 9 && !flag9))
                {
                    continue;
                }
                num50++;
                bool num115 = LocalPlayer.IsItemSlotUnlockedAndUsable(num62);
                flag7 = !num115;
                bool flag12 = !num115 && !mouseItem.IsAir;
                int num63 = screenWidth - 64 - 28 - 47 - 47;
                int num64 = (int)((float)num31 + (float)(num50 * 56) * inventoryScale);
                new Color(100, 100, 100, 100);
                if (num62 > 2)
                {
                    num64 += num47;
                }
                if (mouseX >= num63 && (float)mouseX <= (float)num63 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num64 && (float)mouseY <= (float)num64 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    armorHide = true;
                    ItemSlot.OverrideHover(player[myPlayer].dye, 12, num62);
                    if (!flag12)
                    {
                        if (mouseRightRelease && mouseRight)
{
                            ItemSlot.RightClick(player[myPlayer].dye, 12, num62);
                        }
                        ItemSlot.LeftClick(player[myPlayer].dye, 12, num62);
                    }
                    ItemSlot.MouseHover(player[myPlayer].dye, 12, num62);
                }
                if (flag7)
                {
                    inventoryBack = color2;
                }
                ItemSlot.Draw(spriteBatch, player[myPlayer].dye, 12, num62, new Vector2((float)num63, (float)num64));
            }
            inventoryBack = color;
            Vector2 defPos = AccessorySlotLoader.DefenseIconPosition;
            DrawDefenseCounter((int)defPos.X, (int)defPos.Y);
            if (!_achievementAdvisor.CanDrawAboveCoins)
            {
                Vector2 achievePos = default(Vector2);
                ((Vector2)(ref achievePos))._002Ector(defPos.X - 10f - 47f - 47f - 14f - 14f, defPos.Y - 56f * inventoryScale * 0.5f);
                _achievementAdvisor.DrawOneAchievement(spriteBatch, achievePos, large: false);
                UILinkPointNavigator.SetPosition(1570, achievePos + new Vector2(20f) * inventoryScale);
            }
            inventoryBack = color;
            inventoryScale = num48;
        }
        LoaderManager.Get<AccessorySlotLoader>().DrawAccSlots(num31);
        int num65 = (screenHeight - 600) / 2;
        int num66 = (int)((float)screenHeight / 600f * 250f);
        if (screenHeight < 700)
        {
            num65 = (screenHeight - 508) / 2;
            num66 = (int)((float)screenHeight / 600f * 200f);
        }
        else if (screenHeight < 850)
        {
            num66 = (int)((float)screenHeight / 600f * 225f);
        }
        if (craftingHide)
        {
            craftingAlpha -= 0.1f;
            if (craftingAlpha < 0f)
            {
                craftingAlpha = 0f;
            }
        }
        else
        {
            craftingAlpha += 0.025f;
            if (craftingAlpha > 1f)
            {
                craftingAlpha = 1f;
            }
        }
        Color color3 = default(Color);
        ((Color)(ref color3))._002Ector((int)(byte)((float)(int)mouseTextColor * craftingAlpha), (int)(byte)((float)(int)mouseTextColor * craftingAlpha), (int)(byte)((float)(int)mouseTextColor * craftingAlpha), (int)(byte)((float)(int)mouseTextColor * craftingAlpha));
        craftingHide = false;
        if (InReforgeMenu)
        {
            if (mouseReforge)
            {
                if (reforgeScale < 1f)
                {
                    reforgeScale += 0.02f;
                }
            }
            else if (reforgeScale > 1f)
            {
                reforgeScale -= 0.02f;
            }
            if (player[myPlayer].chest != -1 || npcShop != 0 || player[myPlayer].talkNPC == -1 || InGuideCraftMenu)
            {
                InReforgeMenu = false;
                player[myPlayer].dropItemCheck();
                Recipe.FindRecipes();
            }
            else
            {
                int num67 = 50;
                int num68 = 270;
                string text = Lang.inter[46].Value + ": ";
                if (reforgeItem.type > 0)
                {
                    int num69 = reforgeItem.value;
                    num69 *= reforgeItem.stack;
                    bool canApplyDiscount = true;
                    if (ItemLoader.ReforgePrice(reforgeItem, ref num69, ref canApplyDiscount))
                    {
                        if (canApplyDiscount && LocalPlayer.discountAvailable)
{
                            num69 = (int)((double)num69 * 0.8);
                        }
                        num69 = (int)((double)num69 * player[myPlayer].currentShoppingSettings.PriceAdjustment);
                        num69 /= 3;
                    }
                    string text2 = "";
                    int num70 = 0;
                    int num72 = 0;
                    int num73 = 0;
                    int num74 = 0;
                    int num75 = num69;
                    if (num75 < 1)
                    {
                        num75 = 1;
                    }
                    if (num75 >= 1000000)
                    {
                        num70 = num75 / 1000000;
                        num75 -= num70 * 1000000;
                    }
                    if (num75 >= 10000)
                    {
                        num72 = num75 / 10000;
                        num75 -= num72 * 10000;
                    }
                    if (num75 >= 100)
                    {
                        num73 = num75 / 100;
                        num75 -= num73 * 100;
                    }
                    if (num75 >= 1)
                    {
                        num74 = num75;
                    }
                    if (num70 > 0)
                    {
                        text2 = text2 + "[c/" + Colors.AlphaDarken(Colors.CoinPlatinum).Hex3() + ":" + num70 + " " + Lang.inter[15].Value + "] ";
                    }
                    if (num72 > 0)
                    {
                        text2 = text2 + "[c/" + Colors.AlphaDarken(Colors.CoinGold).Hex3() + ":" + num72 + " " + Lang.inter[16].Value + "] ";
                    }
                    if (num73 > 0)
                    {
                        text2 = text2 + "[c/" + Colors.AlphaDarken(Colors.CoinSilver).Hex3() + ":" + num73 + " " + Lang.inter[17].Value + "] ";
                    }
                    if (num74 > 0)
                    {
                        text2 = text2 + "[c/" + Colors.AlphaDarken(Colors.CoinCopper).Hex3() + ":" + num74 + " " + Lang.inter[18].Value + "] ";
                    }
                    ItemSlot.DrawSavings(spriteBatch, num67 + 130, invBottom, horizontal: true);
                    ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text2, new Vector2((float)(num67 + 50) + FontAssets.MouseText.Value.MeasureString(text).X, (float)num68), Color.White, 0f, Vector2.Zero, Vector2.One);
                    int num76 = num67 + 70;
                    int num77 = num68 + 40;
                    bool num116 = mouseX > num76 - 15 && mouseX < num76 + 15 && mouseY > num77 - 15 && mouseY < num77 + 15 && !PlayerInput.IgnoreMouseInterface;
                    Texture2D value4 = TextureAssets.Reforge[0].Value;
                    if (num116)
                    {
                        value4 = TextureAssets.Reforge[1].Value;
                    }
                    spriteBatch.Draw(value4, new Vector2((float)num76, (float)num77), (Rectangle?)null, Color.White, 0f, value4.Size() / 2f, reforgeScale, (SpriteEffects)0, 0f);
                    UILinkPointNavigator.SetPosition(304, new Vector2((float)num76, (float)num77) + value4.Size() / 4f);
                    if (num116)
                    {
                        hoverItemName = Lang.inter[19].Value;
                        if (!mouseReforge)
{
                            SoundEngine.PlaySound(12);
                        }
                        mouseReforge = true;
                        player[myPlayer].mouseInterface = true;
                        if (mouseLeftRelease && mouseLeft && player[myPlayer].CanAfford(num69) && ItemLoader.CanReforge(reforgeItem))
{
                            player[myPlayer].BuyItem(num69);
                            ItemLoader.PreReforge(reforgeItem);
                            reforgeItem.ResetPrefix();
                            reforgeItem.Prefix(-2);
                            reforgeItem.position.X = player[myPlayer].position.X + (float)(player[myPlayer].width / 2) - (float)(reforgeItem.width / 2);
                            reforgeItem.position.Y = player[myPlayer].position.Y + (float)(player[myPlayer].height / 2) - (float)(reforgeItem.height / 2);
                            ItemLoader.PostReforge(reforgeItem);
                            PopupText.NewText(PopupTextContext.ItemReforge, reforgeItem, reforgeItem.stack, noStack: true);
                            SoundEngine.PlaySound(in SoundID.Item37);
                        }
                    }
                    else
                    {
                        mouseReforge = false;
                    }
                }
                else
                {
                    text = Lang.inter[20].Value;
                }
                ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, new Vector2((float)(num67 + 50), (float)num68), new Color((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor), 0f, Vector2.Zero, Vector2.One);
                if (mouseX >= num67 && (float)mouseX <= (float)num67 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num68 && (float)mouseY <= (float)num68 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    craftingHide = true;
                    ItemSlot.LeftClick(ref reforgeItem, 5);
                    if (mouseLeftRelease && mouseLeft)
                    {
                        Recipe.FindRecipes();
                    }
                    ItemSlot.RightClick(ref reforgeItem, 5);
                    ItemSlot.MouseHover(ref reforgeItem, 5);
                }
                ItemSlot.Draw(spriteBatch, ref reforgeItem, 5, new Vector2((float)num67, (float)num68));
            }
        }
        else if (InGuideCraftMenu)
        {
            if (player[myPlayer].chest != -1 || npcShop != 0 || player[myPlayer].talkNPC == -1 || InReforgeMenu)
            {
                InGuideCraftMenu = false;
                player[myPlayer].dropItemCheck();
                Recipe.FindRecipes();
            }
            else
            {
                DrawGuideCraftText(num65, color3, out var inventoryX, out var inventoryY);
                new Color(100, 100, 100, 100);
                if (mouseX >= inventoryX && (float)mouseX <= (float)inventoryX + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= inventoryY && (float)mouseY <= (float)inventoryY + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    craftingHide = true;
                    ItemSlot.OverrideHover(ref guideItem, 7);
                    ItemSlot.LeftClick(ref guideItem, 7);
                    if (mouseLeftRelease && mouseLeft)
                    {
                        Recipe.FindRecipes();
                    }
                    ItemSlot.RightClick(ref guideItem, 7);
                    ItemSlot.MouseHover(ref guideItem, 7);
                }
                ItemSlot.Draw(spriteBatch, ref guideItem, 7, new Vector2((float)inventoryX, (float)inventoryY));
            }
        }
        CreativeMenu.Draw(spriteBatch);
        bool flag2 = CreativeMenu.Enabled && !CreativeMenu.Blocked;
        flag2 |= hidePlayerCraftingMenu;
        if (!InReforgeMenu && !LocalPlayer.tileEntityAnchor.InUse && !flag2)
        {
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = -1;
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
            if (numAvailableRecipes > 0)
            {
                spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[25].Value, new Vector2(76f, (float)(414 + num65)), color3, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            Color lightColor = default(Color);
            for (int num78 = 0; num78 < Recipe.maxRecipes; num78++)
            {
                inventoryScale = 100f / (Math.Abs(availableRecipeY[num78]) + 100f);
                if ((double)inventoryScale < 0.75)
                {
                    inventoryScale = 0.75f;
                }
                if (recFastScroll)
                {
                    inventoryScale = 0.75f;
                }
                if (availableRecipeY[num78] < (float)((num78 - focusRecipe) * 65))
                {
                    if (availableRecipeY[num78] == 0f && !recFastScroll)
                    {
                        SoundEngine.PlaySound(12);
                    }
                    availableRecipeY[num78] += 6.5f;
                    if (recFastScroll)
                    {
                        availableRecipeY[num78] += 130000f;
                    }
                    if (availableRecipeY[num78] > (float)((num78 - focusRecipe) * 65))
                    {
                        availableRecipeY[num78] = (num78 - focusRecipe) * 65;
                    }
                }
                else if (availableRecipeY[num78] > (float)((num78 - focusRecipe) * 65))
                {
                    if (availableRecipeY[num78] == 0f && !recFastScroll)
                    {
                        SoundEngine.PlaySound(12);
                    }
                    availableRecipeY[num78] -= 6.5f;
                    if (recFastScroll)
                    {
                        availableRecipeY[num78] -= 130000f;
                    }
                    if (availableRecipeY[num78] < (float)((num78 - focusRecipe) * 65))
                    {
                        availableRecipeY[num78] = (num78 - focusRecipe) * 65;
                    }
                }
                else
                {
                    recFastScroll = false;
                }
                if (num78 >= numAvailableRecipes || Math.Abs(availableRecipeY[num78]) > (float)num66)
                {
                    continue;
                }
                int num79 = (int)(46f - 26f * inventoryScale);
                int num80 = (int)(410f + availableRecipeY[num78] * inventoryScale - 30f * inventoryScale + (float)num65);
                double num82 = ((Color)(ref inventoryBack)).A + 50;
                double num83 = 255.0;
                if (Math.Abs(availableRecipeY[num78]) > (float)num66 - 100f)
                {
                    num82 = (double)(150f * (100f - (Math.Abs(availableRecipeY[num78]) - ((float)num66 - 100f)))) * 0.01;
                    num83 = (double)(255f * (100f - (Math.Abs(availableRecipeY[num78]) - ((float)num66 - 100f)))) * 0.01;
                }
                new Color((int)(byte)num82, (int)(byte)num82, (int)(byte)num82, (int)(byte)num82);
                ((Color)(ref lightColor))._002Ector((int)(byte)num83, (int)(byte)num83, (int)(byte)num83, (int)(byte)num83);
                if (!LocalPlayer.creativeInterface && mouseX >= num79 && (float)mouseX <= (float)num79 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num80 && (float)mouseY <= (float)num80 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    HoverOverCraftingItemButton(num78);
                }
                if (numAvailableRecipes <= 0)
                {
                    continue;
                }
                num82 -= 50.0;
                if (num82 < 0.0)
                {
                    num82 = 0.0;
                }
                if (num78 == focusRecipe)
                {
                    UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = 0;
                    if (PlayerInput.SettingsForUI.HighlightThingsForMouse)
                    {
                        ItemSlot.DrawGoldBGForCraftingMaterial = true;
                    }
                }
                else
                {
                    UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
                }
                Color val = inventoryBack;
                inventoryBack = new Color((int)(byte)num82, (int)(byte)num82, (int)(byte)num82, (int)(byte)num82);
                ItemSlot.Draw(spriteBatch, ref recipe[availableRecipe[num78]].createItem, 22, new Vector2((float)num79, (float)num80), lightColor);
                inventoryBack = val;
            }
            if (numAvailableRecipes > 0)
            {
                UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = -1;
                UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
                for (int num84 = 0; num84 < recipe[availableRecipe[focusRecipe]].requiredItem.Count; num84++)
                {
                    if (recipe[availableRecipe[focusRecipe]].requiredItem[num84].type == 0)
                    {
                        UILinkPointNavigator.Shortcuts.CRAFT_CurrentIngredientsCount = num84 + 1;
                        break;
                    }
                    int num85 = 80 + num84 * 40;
                    int num86 = 380 + num65;
                    double num87 = ((Color)(ref inventoryBack)).A + 50;
                    double num88 = 255.0;
                    Color white = Color.White;
                    Color white2 = Color.White;
                    num87 = (float)(((Color)(ref inventoryBack)).A + 50) - Math.Abs(availableRecipeY[focusRecipe]) * 2f;
                    num88 = 255f - Math.Abs(availableRecipeY[focusRecipe]) * 2f;
                    if (num87 < 0.0)
                    {
                        num87 = 0.0;
                    }
                    if (num88 < 0.0)
                    {
                        num88 = 0.0;
                    }
                    ((Color)(ref white)).R = (byte)num87;
                    ((Color)(ref white)).G = (byte)num87;
                    ((Color)(ref white)).B = (byte)num87;
                    ((Color)(ref white)).A = (byte)num87;
                    ((Color)(ref white2)).R = (byte)num88;
                    ((Color)(ref white2)).G = (byte)num88;
                    ((Color)(ref white2)).B = (byte)num88;
                    ((Color)(ref white2)).A = (byte)num88;
                    inventoryScale = 0.6f;
                    if (num87 == 0.0)
                    {
                        break;
                    }
                    if (mouseX >= num85 && (float)mouseX <= (float)num85 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num86 && (float)mouseY <= (float)num86 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                    {
                        craftingHide = true;
                        player[myPlayer].mouseInterface = true;
                        SetRecipeMaterialDisplayName(num84);
                    }
                    num87 -= 50.0;
                    if (num87 < 0.0)
                    {
                        num87 = 0.0;
                    }
                    UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = 1 + num84;
                    Color val2 = inventoryBack;
                    inventoryBack = new Color((int)(byte)num87, (int)(byte)num87, (int)(byte)num87, (int)(byte)num87);
                    Item tempItem = recipe[availableRecipe[focusRecipe]].requiredItem[num84];
                    ItemSlot.Draw(spriteBatch, ref tempItem, 22, new Vector2((float)num85, (float)num86));
                    inventoryBack = val2;
                }
            }
            if (numAvailableRecipes == 0)
            {
                recBigList = false;
            }
            else
            {
                int num89 = 94;
                int num90 = 450 + num65;
                if (InGuideCraftMenu)
                {
                    num90 -= 150;
                }
                bool flag3 = mouseX > num89 - 15 && mouseX < num89 + 15 && mouseY > num90 - 15 && mouseY < num90 + 15 && !PlayerInput.IgnoreMouseInterface;
                int num91 = recBigList.ToInt() * 2 + flag3.ToInt();
                spriteBatch.Draw(TextureAssets.CraftToggle[num91].Value, new Vector2((float)num89, (float)num90), (Rectangle?)null, Color.White, 0f, TextureAssets.CraftToggle[num91].Value.Size() / 2f, 1f, (SpriteEffects)0, 0f);
                if (flag3)
                {
                    MouseText(Language.GetTextValue("GameUI.CraftingWindow"), 0, 0);
                    player[myPlayer].mouseInterface = true;
                    if (mouseLeft && mouseLeftRelease)
                    {
                        if (!recBigList)
{
                            recBigList = true;
                            SoundEngine.PlaySound(12);
                        }
                        else
{
                            recBigList = false;
                            SoundEngine.PlaySound(12);
                        }
                    }
                }
            }
        }
        hidePlayerCraftingMenu = false;
        if (recBigList && !flag2)
        {
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = -1;
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
            int num93 = 42;
            if ((double)inventoryScale < 0.75)
            {
                inventoryScale = 0.75f;
            }
            int num94 = 340;
            int num95 = 310;
            int num96 = (screenWidth - num95 - 280) / num93;
            int num97 = (screenHeight - num94 - 20) / num93;
            UILinkPointNavigator.Shortcuts.CRAFT_IconsPerRow = num96;
            UILinkPointNavigator.Shortcuts.CRAFT_IconsPerColumn = num97;
            int num98 = 0;
            int num99 = 0;
            int num100 = num95;
            int num101 = num94;
            int num102 = num95 - 20;
            int num104 = num94 + 2;
            if (recStart > numAvailableRecipes - num96 * num97)
            {
                recStart = numAvailableRecipes - num96 * num97;
                if (recStart < 0)
                {
                    recStart = 0;
                }
            }
            if (recStart > 0)
            {
                if (mouseX >= num102 && mouseX <= num102 + TextureAssets.CraftUpButton.Width() && mouseY >= num104 && mouseY <= num104 + TextureAssets.CraftUpButton.Height() && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    if (mouseLeftRelease && mouseLeft)
                    {
                        recStart -= num96;
                        if (recStart < 0)
{
                            recStart = 0;
                        }
                        SoundEngine.PlaySound(12);
                        mouseLeftRelease = false;
                    }
                }
                spriteBatch.Draw(TextureAssets.CraftUpButton.Value, new Vector2((float)num102, (float)num104), (Rectangle?)new Rectangle(0, 0, TextureAssets.CraftUpButton.Width(), TextureAssets.CraftUpButton.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (recStart < numAvailableRecipes - num96 * num97)
            {
                num104 += 20;
                if (mouseX >= num102 && mouseX <= num102 + TextureAssets.CraftUpButton.Width() && mouseY >= num104 && mouseY <= num104 + TextureAssets.CraftUpButton.Height() && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    if (mouseLeftRelease && mouseLeft)
                    {
                        recStart += num96;
                        SoundEngine.PlaySound(12);
                        if (recStart > numAvailableRecipes - num96)
{
                            recStart = numAvailableRecipes - num96;
                        }
                        mouseLeftRelease = false;
                    }
                }
                spriteBatch.Draw(TextureAssets.CraftDownButton.Value, new Vector2((float)num102, (float)num104), (Rectangle?)new Rectangle(0, 0, TextureAssets.CraftUpButton.Width(), TextureAssets.CraftUpButton.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            for (int num105 = recStart; num105 < Recipe.maxRecipes && num105 < numAvailableRecipes; num105++)
            {
                int num106 = num100;
                int num107 = num101;
                double num108 = ((Color)(ref inventoryBack)).A + 50;
                double num109 = 255.0;
                new Color((int)(byte)num108, (int)(byte)num108, (int)(byte)num108, (int)(byte)num108);
                new Color((int)(byte)num109, (int)(byte)num109, (int)(byte)num109, (int)(byte)num109);
                if (mouseX >= num106 && (float)mouseX <= (float)num106 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num107 && (float)mouseY <= (float)num107 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                {
                    player[myPlayer].mouseInterface = true;
                    if (mouseLeftRelease && mouseLeft)
                    {
                        focusRecipe = num105;
                        recFastScroll = true;
                        recBigList = false;
                        SoundEngine.PlaySound(12);
                        mouseLeftRelease = false;
                        if (PlayerInput.UsingGamepadUI)
{
                            UILinkPointNavigator.ChangePage(9);
                            LockCraftingForThisCraftClickDuration();
                        }
                    }
                    craftingHide = true;
                    HoverItem = recipe[availableRecipe[num105]].createItem.Clone();
                    ItemSlot.MouseHover(22);
                    hoverItemName = recipe[availableRecipe[num105]].createItem.Name;
                    if (recipe[availableRecipe[num105]].createItem.stack > 1)
                    {
                        hoverItemName = hoverItemName + " (" + recipe[availableRecipe[num105]].createItem.stack + ")";
                    }
                }
                if (numAvailableRecipes > 0)
                {
                    num108 -= 50.0;
                    if (num108 < 0.0)
                    {
                        num108 = 0.0;
                    }
                    UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = num105 - recStart;
                    Color val3 = inventoryBack;
                    inventoryBack = new Color((int)(byte)num108, (int)(byte)num108, (int)(byte)num108, (int)(byte)num108);
                    ItemSlot.Draw(spriteBatch, ref recipe[availableRecipe[num105]].createItem, 22, new Vector2((float)num106, (float)num107));
                    inventoryBack = val3;
                }
                num100 += num93;
                num98++;
                if (num98 >= num96)
                {
                    num100 = num95;
                    num101 += num93;
                    num98 = 0;
                    num99++;
                    if (num99 >= num97)
                    {
                        break;
                    }
                }
            }
        }
        Vector2 vector2 = FontAssets.MouseText.Value.MeasureString("Coins");
        Vector2 vector3 = FontAssets.MouseText.Value.MeasureString(Lang.inter[26].Value);
        float num110 = vector2.X / vector3.X;
        spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[26].Value, new Vector2(496f, 84f + (vector2.Y - vector2.Y * num110) / 2f), new Color((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor), 0f, default(Vector2), 0.75f * num110, (SpriteEffects)0, 0f);
        inventoryScale = 0.6f;
        for (int num111 = 0; num111 < 4; num111++)
        {
            int num112 = 497;
            int num113 = (int)(85f + (float)(num111 * 56) * inventoryScale + 20f);
            int slot = num111 + 50;
            new Color(100, 100, 100, 100);
            if (mouseX >= num112 && (float)mouseX <= (float)num112 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num113 && (float)mouseY <= (float)num113 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
            {
                player[myPlayer].mouseInterface = true;
                ItemSlot.OverrideHover(player[myPlayer].inventory, 1, slot);
                ItemSlot.LeftClick(player[myPlayer].inventory, 1, slot);
                ItemSlot.RightClick(player[myPlayer].inventory, 1, slot);
                if (mouseLeftRelease && mouseLeft)
                {
                    Recipe.FindRecipes();
                }
                ItemSlot.MouseHover(player[myPlayer].inventory, 1, slot);
            }
            ItemSlot.Draw(spriteBatch, player[myPlayer].inventory, 1, slot, new Vector2((float)num112, (float)num113));
        }
        Vector2 vector4 = FontAssets.MouseText.Value.MeasureString("Ammo");
        Vector2 vector5 = FontAssets.MouseText.Value.MeasureString(Lang.inter[27].Value);
        float num3 = vector4.X / vector5.X;
        spriteBatch.DrawString(FontAssets.MouseText.Value, Lang.inter[27].Value, new Vector2(532f, 84f + (vector4.Y - vector4.Y * num3) / 2f), new Color((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor), 0f, default(Vector2), 0.75f * num3, (SpriteEffects)0, 0f);
        inventoryScale = 0.6f;
        for (int num4 = 0; num4 < 4; num4++)
        {
            int num5 = 534;
            int num6 = (int)(85f + (float)(num4 * 56) * inventoryScale + 20f);
            int slot2 = 54 + num4;
            new Color(100, 100, 100, 100);
            if (mouseX >= num5 && (float)mouseX <= (float)num5 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num6 && (float)mouseY <= (float)num6 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
            {
                player[myPlayer].mouseInterface = true;
                ItemSlot.OverrideHover(player[myPlayer].inventory, 2, slot2);
                ItemSlot.LeftClick(player[myPlayer].inventory, 2, slot2);
                ItemSlot.RightClick(player[myPlayer].inventory, 2, slot2);
                if (mouseLeftRelease && mouseLeft)
                {
                    Recipe.FindRecipes();
                }
                ItemSlot.MouseHover(player[myPlayer].inventory, 2, slot2);
            }
            ItemSlot.Draw(spriteBatch, player[myPlayer].inventory, 2, slot2, new Vector2((float)num5, (float)num6));
        }
        if (npcShop > 0 && (!playerInventory || player[myPlayer].talkNPC == -1))
        {
            SetNPCShopIndex(0);
        }
        if (npcShop > 0 && !recBigList)
        {
            Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, Lang.inter[28].Value, 504f, invBottom, Color.White * ((float)(int)mouseTextColor / 255f), Color.Black, Vector2.Zero);
            ItemSlot.DrawSavings(spriteBatch, 504f, invBottom);
            inventoryScale = 0.755f;
            if (mouseX > 73 && mouseX < (int)(73f + 560f * inventoryScale) && mouseY > invBottom && mouseY < (int)((float)invBottom + 224f * inventoryScale) && !PlayerInput.IgnoreMouseInterface)
            {
                player[myPlayer].mouseInterface = true;
            }
            for (int num7 = 0; num7 < 10; num7++)
            {
                for (int num8 = 0; num8 < 4; num8++)
                {
                    int num9 = (int)(73f + (float)(num7 * 56) * inventoryScale);
                    int num10 = (int)((float)invBottom + (float)(num8 * 56) * inventoryScale);
                    int slot3 = num7 + num8 * 10;
                    new Color(100, 100, 100, 100);
                    if (mouseX >= num9 && (float)mouseX <= (float)num9 + (float)TextureAssets.InventoryBack.Width() * inventoryScale && mouseY >= num10 && (float)mouseY <= (float)num10 + (float)TextureAssets.InventoryBack.Height() * inventoryScale && !PlayerInput.IgnoreMouseInterface)
                    {
                        ItemSlot.OverrideHover(shop[npcShop].item, 15, slot3);
                        player[myPlayer].mouseInterface = true;
                        ItemSlot.LeftClick(shop[npcShop].item, 15, slot3);
                        ItemSlot.RightClick(shop[npcShop].item, 15, slot3);
                        ItemSlot.MouseHover(shop[npcShop].item, 15, slot3);
                    }
                    ItemSlot.Draw(spriteBatch, shop[npcShop].item, 15, slot3, new Vector2((float)num9, (float)num10));
                }
            }
        }
        if (player[myPlayer].chest > -1 && !tileContainer[tile[player[myPlayer].chestX, player[myPlayer].chestY].type])
        {
            player[myPlayer].chest = -1;
            Recipe.FindRecipes();
        }
        int offsetDown = 0;
        UIVirtualKeyboard.ShouldHideText = !PlayerInput.SettingsForUI.ShowGamepadHints;
        if (!PlayerInput.UsingGamepad)
        {
            offsetDown = 9999;
        }
        UIVirtualKeyboard.OffsetDown = offsetDown;
        ChestUI.Draw(spriteBatch);
        LocalPlayer.tileEntityAnchor.GetTileEntity()?.OnInventoryDraw(LocalPlayer, spriteBatch);
        if (player[myPlayer].chest == -1 && npcShop == 0)
        {
            int num11 = 0;
            int num12 = 498;
            int num14 = 244;
            int num15 = TextureAssets.ChestStack[num11].Width();
            int num16 = TextureAssets.ChestStack[num11].Height();
            UILinkPointNavigator.SetPosition(301, new Vector2((float)num12 + (float)num15 * 0.75f, (float)num14 + (float)num16 * 0.75f));
            if (mouseX >= num12 && mouseX <= num12 + num15 && mouseY >= num14 && mouseY <= num14 + num16 && !PlayerInput.IgnoreMouseInterface)
            {
                num11 = 1;
                if (!allChestStackHover)
                {
                    SoundEngine.PlaySound(12);
                    allChestStackHover = true;
                }
                if (mouseLeft && mouseLeftRelease)
                {
                    mouseLeftRelease = false;
                    player[myPlayer].QuickStackAllChests();
                    Recipe.FindRecipes();
                }
                player[myPlayer].mouseInterface = true;
            }
            else if (allChestStackHover)
            {
                SoundEngine.PlaySound(12);
                allChestStackHover = false;
            }
            spriteBatch.Draw(TextureAssets.ChestStack[num11].Value, new Vector2((float)num12, (float)num14), (Rectangle?)new Rectangle(0, 0, TextureAssets.ChestStack[num11].Width(), TextureAssets.ChestStack[num11].Height()), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            if (!mouseText && num11 == 1)
            {
                MouseText(Language.GetTextValue("GameUI.QuickStackToNearby"), 0, 0);
            }
        }
        if (player[myPlayer].chest != -1 || npcShop != 0)
        {
            return;
        }
        int num17 = 0;
        int num18 = 534;
        int num19 = 244;
        int num20 = 30;
        int num21 = 30;
        UILinkPointNavigator.SetPosition(302, new Vector2((float)num18 + (float)num20 * 0.75f, (float)num19 + (float)num21 * 0.75f));
        bool flag4 = false;
        if (mouseX >= num18 && mouseX <= num18 + num20 && mouseY >= num19 && mouseY <= num19 + num21 && !PlayerInput.IgnoreMouseInterface)
        {
            num17 = 1;
            flag4 = true;
            player[myPlayer].mouseInterface = true;
            if (mouseLeft && mouseLeftRelease)
            {
                mouseLeftRelease = false;
                ItemSorting.SortInventory();
                Recipe.FindRecipes();
            }
        }
        if (flag4 != inventorySortMouseOver)
        {
            SoundEngine.PlaySound(12);
            inventorySortMouseOver = flag4;
        }
        Texture2D value5 = TextureAssets.InventorySort[inventorySortMouseOver ? 1 : 0].Value;
        spriteBatch.Draw(value5, new Vector2((float)num18, (float)num19), (Rectangle?)null, Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        if (!mouseText && num17 == 1)
        {
            MouseText(Language.GetTextValue("GameUI.SortInventory"), 0, 0);
        }
    }
References Terraria.Main._achievementAdvisor, Terraria.Main._cannotDrawAccessoriesHorizontally, Terraria.Main._settingsButtonIsPushedToSide, Terraria.ModLoader.BuilderToggleLoader.ActiveBuilderToggles(), Terraria.Main.allChestStackHover, Terraria.ID.Colors.AlphaDarken(), Terraria.Main.armorAlpha, Terraria.Main.armorHide, Terraria.Main.availableRecipe, Terraria.Main.availableRecipeY, Terraria.Main.bannerMouseOver, Terraria.GameContent.Creative.CreativeUI.Blocked, Terraria.Main.buffAlpha, Terraria.Player.buffType, Terraria.Player.BuyItem(), Terraria.Player.CanDemonHeartAccessoryBeShown(), Terraria.UI.AchievementAdvisor.CanDrawAboveCoins, Terraria.Player.CanMasterModeAccessoryBeShown(), Terraria.ModLoader.ItemLoader.CanReforge(), Terraria.Main.CaptureModeDisabled, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePage(), Terraria.Main.chest, Terraria.Player.chest, Terraria.GameContent.TextureAssets.ChestStack, Terraria.Item.Clone(), Terraria.ID.Colors.CoinCopper, Terraria.ID.Colors.CoinGold, Terraria.ID.Colors.CoinPlatinum, Terraria.ID.Colors.CoinSilver, Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.CraftDownButton, Terraria.Main.craftingAlpha, Terraria.Main.craftingHide, Terraria.GameContent.TextureAssets.CraftToggle, Terraria.GameContent.TextureAssets.CraftUpButton, Terraria.Recipe.createItem, Terraria.Player.creativeInterface, Terraria.Main.CreativeMenu, Terraria.Player.currentShoppingSettings, Terraria.ModLoader.AccessorySlotLoader.DefenseIconPosition, Terraria.Player.discountAvailable, Terraria.GameContent.Creative.CreativeUI.Draw(), Terraria.UI.ChestUI.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Main.DrawBestiaryIcon(), Terraria.Utils.DrawBorderStringFourWay(), Terraria.Main.DrawBuffIcon(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.DrawDefenseCounter(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.Main.DrawGuideCraftText(), Terraria.Main.DrawHotbarLockIcon(), Terraria.Main.DrawLoadoutButtons(), Terraria.Main.DrawNPCHousesInUI(), Terraria.UI.AchievementAdvisor.DrawOneAchievement(), Terraria.Main.DrawPageIcons(), Terraria.Main.DrawPVPIcons(), Terraria.UI.ItemSlot.DrawRadialDpad(), Terraria.UI.ItemSlot.DrawSavings(), Terraria.Main.DrawTrashItemSlot(), Terraria.Player.dropItemCheck(), Terraria.Player.enabledSuperCart, Terraria.Main.EquipPage, Terraria.GameContent.TextureAssets.Extra, Terraria.Recipe.FindRecipes(), Terraria.Main.focusRecipe, Terraria.Player.GetAmountOfExtraAccessorySlotsToShow(), Terraria.Lang.GetBuffName(), Terraria.Main.GetBuffTooltip(), Terraria.Localization.Language.GetTextValue(), Terraria.Recipe.GetThroughDelayedFindRecipes(), Terraria.DataStructures.PlayerInteractionAnchor.GetTileEntity(), Terraria.Main.guideItem, Terraria.UI.ItemSlot.Handle(), Terraria.Entity.height, Terraria.Player.hideMisc, Terraria.Main.hidePlayerCraftingMenu, Terraria.Player.hideVisibleAccessory, Terraria.GameInput.PlayerInput.SettingsForUI.HighlightThingsForMouse, Terraria.Main.HoverItem, Terraria.Main.hoverItemName, Terraria.Main.HoverOverCraftingItemButton(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.InGuideCraftMenu, Terraria.Main.InReforgeMenu, Terraria.Lang.inter, Terraria.DataStructures.PlayerInteractionAnchor.InUse, Terraria.Main.invBottom, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryBack, Terraria.Player.inventoryChestStack, Terraria.Main.inventoryScale, Terraria.GameContent.TextureAssets.InventorySort, Terraria.Main.inventorySortMouseOver, Terraria.GameContent.TextureAssets.InventoryTickOff, Terraria.GameContent.TextureAssets.InventoryTickOn, Terraria.Item.IsAir, Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.Main.item, Terraria.ID.SoundID.Item37, Terraria.UI.ItemSlot.LeftClick(), Terraria.Main.LocalPlayer, Terraria.Main.LockCraftingForThisCraftClickDuration(), Terraria.Main.mapEnabled, Terraria.Main.mapFullscreen, Terraria.Main.mapFullscreenScale, Terraria.GameContent.TextureAssets.MapIcon, Terraria.Main.mapStyle, Terraria.Player.maxBuffs, Terraria.Recipe.maxRecipes, Terraria.Main.meleeBuff, Terraria.Main.mH, Terraria.Player.miscDyes, Terraria.Player.miscEquips, Terraria.ModLoader.BuffLoader.ModifyBuffText(), Terraria.UI.ItemSlot.MouseHover(), Terraria.Player.mouseInterface, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseReforge, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseText, Terraria.Main.MouseText(), Terraria.Main.mouseTextColor, Terraria.Main.MouseTextHackZoom(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Item.Name, Terraria.Main.netMode, Terraria.PopupText.NewText(), Terraria.Main.npcChatCornerItem, Terraria.Main.npcShop, Terraria.Main.numAvailableRecipes, Terraria.DataStructures.TileEntity.OnInventoryDraw(), Terraria.UI.ItemSlot.OverrideHover(), Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.ModLoader.ItemLoader.PostReforge(), Terraria.Item.Prefix(), Terraria.ModLoader.ItemLoader.PreReforge(), Terraria.ShoppingSettings.PriceAdjustment, Terraria.Player.QuickStackAllChests(), Terraria.Main.rare, Terraria.Main.recBigList, Terraria.Main.recFastScroll, Terraria.Main.recipe, Terraria.Main.recStart, Terraria.GameContent.TextureAssets.Reforge, Terraria.Main.reforgeItem, Terraria.ModLoader.ItemLoader.ReforgePrice(), Terraria.Main.reforgeScale, Terraria.Recipe.requiredItem, Terraria.Main.resetMapFull, Terraria.Item.ResetPrefix(), Terraria.UI.ItemSlot.RightClick(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.NetMessage.SendData(), Terraria.Main.SetNPCShopIndex(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.SetRecipeMaterialDisplayName(), Terraria.Player.SetTalkNPC(), Terraria.Main.shop, Terraria.Main.ShouldPVPDraw, Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadHints, Terraria.UI.ItemSorting.SortInventory(), Terraria.Main.spriteBatch, Terraria.Item.stack, Terraria.Main.tile, Terraria.Main.tileContainer, Terraria.Player.tileEntityAnchor, Terraria.Player.ToggleLight(), Terraria.Player.TogglePet(), Terraria.Item.type, Terraria.Player.unlockedSuperCart, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.GameInput.PlayerInput.UsingGamepadUI, Terraria.Localization.LocalizedText.Value, Terraria.Item.value, and Terraria.Entity.width.
Referenced by Terraria.Main.DrawInterface_27_Inventory().