TModLoader: Terraria.Main.EraseWorld
EraseWorld()
static void Terraria.Main.EraseWorld (int i) inline static private
    {
        try
        {
            if (!WorldList[i].IsCloudSave)
            {
                Platform.Get<IPathService>().MoveToRecycleBin(WorldList[i].Path);
                Platform.Get<IPathService>().MoveToRecycleBin(WorldList[i].Path + ".bak");
                for (int j = 2; j <= 9; j++)
                {
                    Platform.Get<IPathService>().MoveToRecycleBin(WorldList[i].Path + ".bak" + j);
                }
            }
            else if (SocialAPI.Cloud != null)
            {
                SocialAPI.Cloud.Delete(WorldList[i].Path);
            }
            WorldIO.EraseWorld(WorldList[i].Path, WorldList[i].IsCloudSave);
            LoadWorlds();
        }
        catch
        {
        }
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.ModLoader.IO.WorldIO.EraseWorld(), Terraria.Main.LoadWorlds(), Terraria.Enums.Platform, and Terraria.Main.WorldList.
Referenced by Terraria.Main.DedServ_PostModLoad(), and Terraria.Main.DrawMenu().