TModLoader: Terraria.Main.UpdateTime_StartNight
UpdateTime_StartNight()
static void Terraria.Main.UpdateTime_StartNight (ref bool stopEvents) inline static
    {
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0386: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        if (fastForwardTimeToDusk)
        {
            fastForwardTimeToDusk = false;
            UpdateTimeRate();
        }
        if (moondialCooldown > 0)
        {
            moondialCooldown--;
        }
        NPC.ResetBadgerHatTime();
        NPC.freeCake = false;
        Star.NightSetup();
        NPC.setFireFlyChance();
        BirthdayParty.CheckNight();
        LanternNight.CheckNight();
        WorldGen.mysticLogsEvent.StartNight();
        WorldGen.prioritizedTownNPCType = 0;
        checkForSpawns = 0;
        if (rand.Next(50) == 0 && netMode != 1 && NPC.downedBoss2)
        {
            WorldGen.spawnMeteor = true;
        }
        if (LanternNight.LanternsUp)
        {
            stopEvents = true;
        }
        if (eclipse && netMode != 1)
        {
            AchievementsHelper.NotifyProgressionEvent(3);
        }
        eclipse = false;
        if (netMode != 1)
        {
            AchievementsHelper.NotifyProgressionEvent(0);
        }
        if (!IsFastForwardingTime() && !stopEvents)
        {
            if (!NPC.downedBoss1 && netMode != 1)
            {
                bool flag = false;
                for (int i = 0; i < 255; i++)
                {
                    if (player[i].active && player[i].ConsumedLifeCrystals >= 5 && (int)player[i].statDefense > 10)
                    {
                        flag = true;
                        break;
                    }
                }
                if (flag && rand.Next(3) == 0)
                {
                    int num = 0;
                    for (int j = 0; j < 200; j++)
                    {
                        if (npc[j].active && npc[j].townNPC)
{
                            num++;
                        }
                    }
                    if (num >= 4)
                    {
                        WorldGen.spawnEye = true;
                        if (netMode == 0)
{
                            NewText(Lang.misc[9].Value, 50, byte.MaxValue, 130);
                        }
                        else if (netMode == 2)
{
                            ChatHelper.BroadcastChatMessage(Lang.misc[9].ToNetworkText(), new Color(50, 255, 130));
                        }
                    }
                }
            }
            if (netMode != 1 && !pumpkinMoon && !DD2Event.Ongoing && !snowMoon && WorldGen.altarCount > 0 && hardMode && !WorldGen.spawnEye && rand.Next(10) == 0)
            {
                bool flag2 = false;
                for (int k = 0; k < 200; k++)
                {
                    if (npc[k].active && npc[k].boss)
                    {
                        flag2 = true;
                    }
                }
                if (!flag2 && (!NPC.downedMechBoss1 || !NPC.downedMechBoss2 || !NPC.downedMechBoss3))
                {
                    if (remixWorld && getGoodWorld)
                    {
                        if (rand.Next(2) == 0)
{
                            WorldGen.spawnHardBoss = rand.Next(3) + 1;
                            if (netMode == 0)
{
                                NewText(Lang.misc[108].Value, 50, byte.MaxValue, 130);
                            }
                            else if (netMode == 2)
{
                                ChatHelper.BroadcastChatMessage(Lang.misc[108].ToNetworkText(), new Color(50, 255, 130));
                            }
                        }
                    }
                    else
                    {
                        for (int l = 0; l < 1000; l++)
{
                            int num2 = rand.Next(3) + 1;
                            if (num2 == 1 && !NPC.downedMechBoss1)
{
                                WorldGen.spawnHardBoss = num2;
                                if (netMode == 0)
{
                                    NewText(Lang.misc[28].Value, 50, byte.MaxValue, 130);
                                }
                                else if (netMode == 2)
{
                                    ChatHelper.BroadcastChatMessage(Lang.misc[28].ToNetworkText(), new Color(50, 255, 130));
                                }
                                break;
                            }
                            if (num2 == 2 && !NPC.downedMechBoss2)
{
                                WorldGen.spawnHardBoss = num2;
                                if (netMode == 0)
{
                                    NewText(Lang.misc[29].Value, 50, byte.MaxValue, 130);
                                }
                                else if (netMode == 2)
{
                                    ChatHelper.BroadcastChatMessage(Lang.misc[29].ToNetworkText(), new Color(50, 255, 130));
                                }
                                break;
                            }
                            if (num2 == 3 && !NPC.downedMechBoss3)
{
                                WorldGen.spawnHardBoss = num2;
                                if (netMode == 0)
{
                                    NewText(Lang.misc[30].Value, 50, byte.MaxValue, 130);
                                }
                                else if (netMode == 2)
{
                                    ChatHelper.BroadcastChatMessage(Lang.misc[30].ToNetworkText(), new Color(50, 255, 130));
                                }
                                break;
                            }
                        }
                    }
                }
            }
            int maxValue = 9;
            if (tenthAnniversaryWorld)
            {
                maxValue = 6;
            }
            if (!WorldGen.spawnEye && moonPhase != 4 && rand.Next(maxValue) == 0 && netMode != 1)
            {
                for (int m = 0; m < 255; m++)
                {
                    if (player[m].active && player[m].ConsumedLifeCrystals > 1)
                    {
                        bloodMoon = true;
                        break;
                    }
                }
                if (bloodMoon)
                {
                    sundialCooldown = 0;
                    moondialCooldown = 0;
                    AchievementsHelper.NotifyProgressionEvent(4);
                    if (netMode == 0)
                    {
                        NewText(Lang.misc[8].Value, 50, byte.MaxValue, 130);
                    }
                    else if (netMode == 2)
                    {
                        ChatHelper.BroadcastChatMessage(Lang.misc[8].ToNetworkText(), new Color(50, 255, 130));
                    }
                }
            }
        }
        time = 0.0;
        dayTime = false;
        if (netMode == 2)
        {
            NetMessage.SendData(7);
        }
    }
References Terraria.WorldGen.altarCount, Terraria.Main.bloodMoon, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Main.checkForSpawns, Terraria.GameContent.Events.BirthdayParty.CheckNight(), Terraria.GameContent.Events.LanternNight.CheckNight(), Terraria.Main.dayTime, Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.Main.eclipse, Terraria.Main.fastForwardTimeToDusk, Terraria.Main.getGoodWorld, Terraria.Main.hardMode, Terraria.Main.IsFastForwardingTime(), Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Lang.misc, Terraria.Main.moondialCooldown, Terraria.Main.moonPhase, Terraria.WorldGen.mysticLogsEvent, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Star.NightSetup(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.npc, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Main.player, Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NPC.ResetBadgerHatTime(), Terraria.NetMessage.SendData(), Terraria.NPC.setFireFlyChance(), Terraria.Main.snowMoon, Terraria.WorldGen.spawnEye, Terraria.Main.sundialCooldown, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.time, and Terraria.Main.UpdateTimeRate().
Referenced by Terraria.Main.SkipToTime(), and Terraria.Main.UpdateTime().