TModLoader: Terraria.Main.TryFreeingElderSlime
TryFreeingElderSlime()
static bool Terraria.Main.TryFreeingElderSlime (int npcIndex) inline static private
Definition at line 55687 of file Main.cs.
    {
        Player player = Main.player[myPlayer];
        short type = 327;
        bool inVoidBag = false;
        int num = player.FindItemInInventoryOrOpenVoidBag(type, out inVoidBag);
        if (num == -1)
        {
            return false;
        }
        Item item = null;
        item = ((!inVoidBag) ? player.inventory[num] : player.bank4.item[num]);
        if (--item.stack <= 0)
        {
            item.TurnToAir();
        }
        Recipe.FindRecipes();
        return true;
    }
References Terraria.Player.bank4, Terraria.Player.FindItemInInventoryOrOpenVoidBag(), Terraria.Recipe.FindRecipes(), Terraria.Player.inventory, Terraria.Chest.item, Terraria.Main.item, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Item.stack, and Terraria.Item.TurnToAir().
Referenced by Terraria.Main.HoverOverNPCs().