TModLoader: Terraria.Main.DrawMultisegmentPet
DrawMultisegmentPet()
void Terraria.Main.DrawMultisegmentPet (Projectile proj) inline private
    {
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0268: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0282: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_023c: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        Texture2D texture2D = null;
        if (proj.type == 887)
        {
            texture2D = TextureAssets.GlowMask[275].Value;
        }
        int num = 5;
        int num2 = 16;
        switch (proj.type)
        {
        case 883:
            num = 5;
            num2 = 16;
            break;
        case 887:
            num = 6;
            num2 = 16;
            break;
        case 893:
            num = 8;
            num2 = 20;
            break;
        }
        SpriteEffects effects = (SpriteEffects)(proj.spriteDirection != 1);
        Rectangle rectangle = value.Frame(1, projFrames[proj.type]);
        Vector2 origin = rectangle.Size() / 2f;
        Vector2 position = proj.Center - screenPosition;
        Color alpha = proj.GetAlpha(Lighting.GetColor(proj.Center.ToTileCoordinates()));
        Color color = Color.White * ((float)(int)mouseTextColor / 255f);
        Vector2 vector = proj.Center;
        int num3 = 1;
        int num4 = projFrames[proj.type] - 1;
        for (int i = 1; i < num; i++)
        {
            int frameY = num3;
            if (i == num - 1)
            {
                frameY = num4;
            }
            else if (proj.type == 893 && i != 2 && i != 5)
            {
                frameY = 2;
            }
            Rectangle value2 = value.Frame(1, projFrames[proj.type], 0, frameY);
            Vector2 vector2 = proj.oldPos[i * 10] + proj.Size / 2f;
            float num5 = (vector - vector2).ToRotation();
            vector2 = vector - Utils.RotatedBy(new Vector2((float)num2, 0f), num5, Vector2.Zero);
            num5 = (vector - vector2).ToRotation() + (float)Math.PI / 2f;
            Vector2 position2 = vector2 - screenPosition;
            SpriteEffects effects2 = (SpriteEffects)(!(vector2.X < vector.X));
            vector = vector2;
            EntitySpriteDraw(value, position2, value2, proj.GetAlpha(Lighting.GetColor(vector2.ToTileCoordinates())), num5, origin, proj.scale, effects2);
            if (texture2D != null)
            {
                EntitySpriteDraw(texture2D, position2, value2, proj.GetAlpha(color), num5, origin, proj.scale, effects2);
            }
        }
        EntitySpriteDraw(value, position, rectangle, alpha, proj.rotation, origin, proj.scale, effects);
        if (texture2D != null)
        {
            EntitySpriteDraw(texture2D, position, rectangle, color, proj.rotation, origin, proj.scale, effects);
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.EntitySpriteDraw(), Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.Main.mouseTextColor, Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.projFrames, Terraria.Utils.RotatedBy(), and Terraria.Main.screenPosition.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().