TModLoader: Terraria.Main.DrawSurfaceBG
DrawSurfaceBG()
void Terraria.Main.DrawSurfaceBG () inline protected
    {
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0392: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_0341: Unknown result type (might be due to invalid IL or missing references)
        //IL_1296: Unknown result type (might be due to invalid IL or missing references)
        //IL_129f: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a48: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_163f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1646: Unknown result type (might be due to invalid IL or missing references)
        //IL_1650: Unknown result type (might be due to invalid IL or missing references)
        //IL_1655: Unknown result type (might be due to invalid IL or missing references)
        //IL_1697: Unknown result type (might be due to invalid IL or missing references)
        //IL_169c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a67: Unknown result type (might be due to invalid IL or missing references)
        //IL_067d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0680: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_1090: Unknown result type (might be due to invalid IL or missing references)
        //IL_1095: Unknown result type (might be due to invalid IL or missing references)
        //IL_109a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ecf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee8: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_10af: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0beb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c05: Unknown result type (might be due to invalid IL or missing references)
        //IL_06da: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0705: Unknown result type (might be due to invalid IL or missing references)
        //IL_070c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0718: Unknown result type (might be due to invalid IL or missing references)
        //IL_071e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0760: Unknown result type (might be due to invalid IL or missing references)
        //IL_0763: Unknown result type (might be due to invalid IL or missing references)
        //IL_0768: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11da: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_1238: Unknown result type (might be due to invalid IL or missing references)
        //IL_1252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0940: Unknown result type (might be due to invalid IL or missing references)
        //IL_0961: Unknown result type (might be due to invalid IL or missing references)
        //IL_096b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0972: Unknown result type (might be due to invalid IL or missing references)
        //IL_097e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0984: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        if ((!remixWorld || (gameMenu && !WorldGen.remixWorldGen)) && (!WorldGen.remixWorldGen || !WorldGen.drunkWorldGen))
        {
            flag = true;
        }
        if (mapFullscreen)
        {
            flag = false;
        }
        Color colorOfSurfaceBackgroundsBase = ColorOfSurfaceBackgroundsBase;
        int num = 30;
        if (gameMenu)
        {
            num = 0;
        }
        if (WorldGen.drunkWorldGen)
        {
            num = -180;
        }
        float num12 = (float)worldSurface;
        if (num12 == 0f)
        {
            num12 = 1f;
        }
        _ = screenPosition;
        float num17 = screenPosition.Y + (float)(screenHeight / 2) - 600f;
        double num18 = (num17 - screenOff / 2f) / (num12 * 16f);
        num18 = 0f - MathHelper.Lerp((float)num18, 1f, 0f);
        num18 = (0f - num17 + screenOff / 2f) / (num12 * 16f);
        float num19 = 2f;
        int num20 = 0;
        float num21 = SkyManager.Instance.ProcessCloudAlpha() * atmo;
        if (flag && (double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int i = 0; i < 200; i++)
            {
                if (cloud[i].active && cloud[i].scale < 1f)
                {
                    Color color = cloud[i].cloudColor(ColorOfTheSkies);
                    float num22 = cloud[i].scale * 0.8f;
                    float num23 = (cloud[i].scale + 1f) / 2f * 0.9f;
                    ((Color)(ref color)).R = (byte)((float)(int)((Color)(ref color)).R * num22);
                    ((Color)(ref color)).G = (byte)((float)(int)((Color)(ref color)).G * num23);
                    float num2 = cloud[i].position.Y * ((float)screenHeight / 600f);
                    num2 = cloud[i].position.Y + (float)(int)(num18 * 750.0 + 830.0) + (float)(int)scAdj + (float)num20;
                    spriteBatch.Draw(TextureAssets.Cloud[cloud[i].type].Value, new Vector2(cloud[i].position.X + (float)TextureAssets.Cloud[cloud[i].type].Width() * 0.5f, num2 + (float)TextureAssets.Cloud[cloud[i].type].Height() * 0.5f), (Rectangle?)new Rectangle(0, 0, TextureAssets.Cloud[cloud[i].type].Width(), TextureAssets.Cloud[cloud[i].type].Height()), color * num21, cloud[i].rotation, new Vector2((float)TextureAssets.Cloud[cloud[i].type].Width() * 0.5f, (float)TextureAssets.Cloud[cloud[i].type].Height() * 0.5f), cloud[i].scale, cloud[i].spriteDir, 0f);
                }
            }
        }
        if (invasionType == 4 && !SkyManager.Instance["Martian"].IsActive())
        {
            SkyManager.Instance.Activate("Martian", default(Vector2));
        }
        else if (invasionType != 4 && SkyManager.Instance["Martian"].IsActive())
        {
            SkyManager.Instance.Deactivate("Martian");
        }
        SkyManager.Instance.ResetDepthTracker();
        bgParallax = 0.15;
        int num3 = -180;
        bool flag2 = true;
        int num4 = 0;
        if (gameMenu)
        {
            num4 -= num3;
        }
        num20 = num4;
        num20 += num;
        if (!WorldGen.drunkWorldGen && flag && (double)(screenPosition.Y / 16f) <= worldSurface + 10.0)
        {
            if (BackgroundEnabled)
            {
                if (cloudBGActive > 0f)
                {
                    cloudBGAlpha += 0.0005f * (float)desiredWorldEventsUpdateRate;
                    if (cloudBGAlpha > 1f)
                    {
                        cloudBGAlpha = 1f;
                    }
                }
                else
                {
                    cloudBGAlpha -= 0.0005f * (float)desiredWorldEventsUpdateRate;
                    if (cloudBGAlpha < 0f)
                    {
                        cloudBGAlpha = 0f;
                    }
                }
                if (cloudBGAlpha > 0f)
                {
                    LoadBackground(cloudBG[0]);
                    LoadBackground(cloudBG[1]);
                    float num5 = cloudBGAlpha;
                    if (num5 > 1f)
                    {
                        num5 = 1f;
                    }
                    bgScale = 1.65f;
                    bgParallax = 0.09000000357627869;
                    if (((Game)this).IsActive && !gamePaused)
                    {
                        cloudBGX[0] += windSpeedCurrent * (float)bgParallax * 9f * (float)desiredWorldEventsUpdateRate;
                    }
                    if (cloudBGX[0] > (float)backgroundWidth[cloudBG[0]] * bgScale)
                    {
                        cloudBGX[0] -= (float)backgroundWidth[cloudBG[0]] * bgScale;
                    }
                    if (cloudBGX[0] < (float)(-backgroundWidth[cloudBG[0]]) * bgScale)
                    {
                        cloudBGX[0] += (float)backgroundWidth[cloudBG[0]] * bgScale;
                    }
                    float num6 = (float)backgroundWidth[cloudBG[0]] * bgScale;
                    bgTopY = (int)(num18 * 900.0 + 600.0) + (int)scAdj + num20;
                    if (gameMenu)
                    {
                        bgTopY = -150 + num20;
                    }
                    bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, num6) - (double)(num6 / 2f) - (double)num6);
                    bgStartX += (int)cloudBGX[0];
                    bgLoops = screenWidth / (int)num6 + 2 + 2;
                    ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * num5;
                    SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
                    for (int j = 0; j < bgLoops; j++)
                    {
                        spriteBatch.Draw(TextureAssets.Background[cloudBG[0]].Value, new Vector2((float)bgStartX + num6 * (float)j, (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[cloudBG[0]], backgroundHeight[cloudBG[0]]), ColorOfSurfaceBackgroundsModified * num21, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
                    }
                    num5 = cloudBGAlpha * 1.5f;
                    if (num5 > 1f)
                    {
                        num5 = 1f;
                    }
                    ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * num5;
                    bgScale = 1.85f;
                    bgParallax = 0.12;
                    if (((Game)this).IsActive && !gamePaused)
                    {
                        cloudBGX[1] += windSpeedCurrent * (float)bgParallax * 9f * (float)desiredWorldEventsUpdateRate;
                    }
                    if (cloudBGX[1] > (float)backgroundWidth[cloudBG[1]] * bgScale)
                    {
                        cloudBGX[1] -= (float)backgroundWidth[cloudBG[1]] * bgScale;
                    }
                    if (cloudBGX[1] < (float)(-backgroundWidth[cloudBG[1]]) * bgScale)
                    {
                        cloudBGX[1] += (float)backgroundWidth[cloudBG[1]] * bgScale;
                    }
                    num6 = (float)backgroundWidth[cloudBG[1]] * bgScale;
                    bgTopY = (int)(num18 * 1100.0 + 750.0) + (int)scAdj + num20;
                    if (gameMenu)
                    {
                        bgTopY = -50 + num20;
                    }
                    bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, num6) - (double)(num6 / 2f) - (double)num6);
                    bgStartX += (int)cloudBGX[1];
                    bgLoops = screenWidth / (int)num6 + 2 + 2;
                    SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
                    for (int k = 0; k < bgLoops; k++)
                    {
                        spriteBatch.Draw(TextureAssets.Background[cloudBG[1]].Value, new Vector2((float)bgStartX + num6 * (float)k, (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[cloudBG[1]], backgroundHeight[cloudBG[1]]), ColorOfSurfaceBackgroundsModified * num21, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
                    }
                }
                DrawSurfaceBG_BackMountainsStep1(num18, num19, num20);
            }
            cTop = bgTopY - 50;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                for (int l = 0; l < 200; l++)
                {
                    if (cloud[l].active && (double)cloud[l].scale < 1.15 && cloud[l].scale >= 1f)
                    {
                        Color color2 = cloud[l].cloudColor(ColorOfTheSkies);
                        if (atmo < 1f)
{
                            color2 *= atmo;
                        }
                        float num7 = cloud[l].position.Y * ((float)screenHeight / 600f);
                        float num8 = (float)((double)(screenPosition.Y / 16f - 24f) / worldSurface);
                        if (num8 < 0f)
{
                            num8 = 0f;
                        }
                        if (num8 > 1f)
{
                            num8 = 1f;
                        }
                        if (gameMenu)
{
                            num8 = 1f;
                        }
                        spriteBatch.Draw(TextureAssets.Cloud[cloud[l].type].Value, new Vector2(cloud[l].position.X + (float)TextureAssets.Cloud[cloud[l].type].Width() * 0.5f, num7 + (float)TextureAssets.Cloud[cloud[l].type].Height() * 0.5f + cTop + 200f), (Rectangle?)new Rectangle(0, 0, TextureAssets.Cloud[cloud[l].type].Width(), TextureAssets.Cloud[cloud[l].type].Height()), color2 * num21, cloud[l].rotation, new Vector2((float)TextureAssets.Cloud[cloud[l].type].Width() * 0.5f, (float)TextureAssets.Cloud[cloud[l].type].Height() * 0.5f), cloud[l].scale, cloud[l].spriteDir, 0f);
                    }
                }
            }
            if (SceneMetrics.HolyTileCount > 0 && BackgroundEnabled)
            {
                bgParallax = 0.17;
                bgScale = 1.1f;
                bgTopY = (int)(num18 * 1400.0 + 900.0) + (int)scAdj + num20;
                SetBackgroundOffsets(18, num18, num20);
                bgScale *= num19;
                bgWidthScaled = (int)((double)(2100f * bgScale) * 1.05);
                bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
                bgLoops = screenWidth / bgWidthScaled + 2;
                if (gameMenu)
                {
                    bgTopY = 230 + num20;
                    bgStartX -= 500;
                }
                SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
                Color color3 = colorOfSurfaceBackgroundsBase;
                float num9 = (float)(SceneMetrics.HolyTileCount - SceneMetrics.HallowTileThreshold) / (float)(SceneMetrics.HallowTileMax - SceneMetrics.HallowTileThreshold);
                if (num9 > 0.5f)
                {
                    num9 = 0.5f;
                }
                else if (num9 < 0f)
                {
                    num9 = 0f;
                }
                ((Color)(ref color3)).R = (byte)((float)(int)((Color)(ref color3)).R * num9);
                ((Color)(ref color3)).G = (byte)((float)(int)((Color)(ref color3)).G * num9);
                ((Color)(ref color3)).B = (byte)((float)(int)((Color)(ref color3)).B * num9);
                ((Color)(ref color3)).A = (byte)((float)(int)((Color)(ref color3)).A * num9 * 0.8f);
                if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
                {
                    LoadBackground(18);
                    LoadBackground(19);
                    for (int m = 0; m < bgLoops; m++)
                    {
                        spriteBatch.Draw(TextureAssets.Background[18].Value, new Vector2((float)(bgStartX + bgWidthScaled * m), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[18], backgroundHeight[18]), color3, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
                        spriteBatch.Draw(TextureAssets.Background[19].Value, new Vector2((float)(bgStartX + bgWidthScaled * m + 1900), (float)(bgTopY + 100)), (Rectangle?)new Rectangle(0, 0, backgroundWidth[19], backgroundHeight[19]), color3, 0f, default(Vector2), bgScale * 0.9f, (SpriteEffects)0, 0f);
                    }
                }
            }
            if (treeMntBGSet1[1] > -1)
            {
                LoadBackground(treeMntBGSet1[1]);
                bgParallax = 0.2;
                bgScale = 1.15f;
                bgScale *= num19;
                int num10 = backgroundWidth[treeMntBGSet1[1]];
                if (num10 == 0)
                {
                    num10 = 1;
                }
                bgWidthScaled = (int)((float)num10 * bgScale);
                bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
                bgLoops = screenWidth / bgWidthScaled + 2;
                if (treeMntBGSet1[1] == 172)
                {
                    bgLoops++;
                }
                bgTopY = (int)(num18 * 1400.0 + 1260.0) + (int)scAdj + num20;
            }
            if (BackgroundEnabled)
            {
                DrawSurfaceBG_BackMountainsStep2(num20);
            }
            cTop = (float)bgTopY * 1.01f - 150f;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                for (int n = 0; n < 200; n++)
                {
                    if (cloud[n].active && cloud[n].scale >= 1.15f)
                    {
                        Color color4 = cloud[n].cloudColor(ColorOfTheSkies);
                        if (atmo < 1f)
{
                            color4 *= atmo;
                        }
                        float num11 = cloud[n].position.Y * ((float)screenHeight / 600f) - 100f;
                        float num13 = (float)((double)(screenPosition.Y / 16f - 24f) / worldSurface);
                        if (num13 < 0f)
{
                            num13 = 0f;
                        }
                        if (num13 > 1f)
{
                            num13 = 1f;
                        }
                        if (gameMenu)
{
                            num13 = 1f;
                        }
                        spriteBatch.Draw(TextureAssets.Cloud[cloud[n].type].Value, new Vector2(cloud[n].position.X + (float)TextureAssets.Cloud[cloud[n].type].Width() * 0.5f, num11 + (float)TextureAssets.Cloud[cloud[n].type].Height() * 0.5f + cTop), (Rectangle?)new Rectangle(0, 0, TextureAssets.Cloud[cloud[n].type].Width(), TextureAssets.Cloud[cloud[n].type].Height()), color4 * num21, cloud[n].rotation, new Vector2((float)TextureAssets.Cloud[cloud[n].type].Width() * 0.5f, (float)TextureAssets.Cloud[cloud[n].type].Height() * 0.5f), cloud[n].scale, cloud[n].spriteDir, 0f);
                    }
                }
            }
        }
        if (flag2)
        {
            num20 += num3;
        }
        if (flag)
        {
            for (int num14 = 0; num14 < bgAlphaFrontLayer.Length; num14++)
            {
                if (BackgroundEnabled)
                {
                    ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFrontLayer[num14];
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 0)
                    {
                        DrawSurfaceBG_Forest(num18, num19, num20, treeBGSet1);
                        DrawSurfaceBG_DrawChangeOverlay(0);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 10)
                    {
                        DrawSurfaceBG_Forest(num18, num19, num20, treeBGSet2);
                        DrawSurfaceBG_DrawChangeOverlay(1);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 11)
                    {
                        DrawSurfaceBG_Forest(num18, num19, num20, treeBGSet3);
                        DrawSurfaceBG_DrawChangeOverlay(2);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 12)
                    {
                        DrawSurfaceBG_Forest(num18, num19, num20, treeBGSet4);
                        DrawSurfaceBG_DrawChangeOverlay(3);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 1)
                    {
                        int[] bgTexIndexes = corruptBG;
                        DrawSurfaceBG_Corrupt(num18, num19, num20, bgTexIndexes);
                        DrawSurfaceBG_DrawChangeOverlay(4);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 2)
                    {
                        int[] bgTexIndexes2 = desertBG;
                        DrawSurfaceBG_Desert(num18, num19, num20, bgTexIndexes2);
                        DrawSurfaceBG_DrawChangeOverlay(9);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 3)
                    {
                        int[] bgTexIndexes3 = jungleBG;
                        DrawSurfaceBG_Jungle(num18, num19, num20, bgTexIndexes3);
                        DrawSurfaceBG_DrawChangeOverlay(5);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 4)
                    {
                        DrawSurfaceBG_DrawChangeOverlay(10);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 5)
                    {
                        DrawSurfaceBG_GoodEvilDesert(num18, num19, num20);
                        DrawSurfaceBG_DrawChangeOverlay(9);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 6)
                    {
                        int[] bgTexIndexes4 = hallowBG;
                        DrawSurfaceBG_Hallow(num18, num19, num20, bgTexIndexes4);
                        DrawSurfaceBG_DrawChangeOverlay(7);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 7)
                    {
                        int[] bgTexIndexes5 = snowBG;
                        DrawSurfaceBG_Snow(num18, num19, num20, bgTexIndexes5);
                        DrawSurfaceBG_DrawChangeOverlay(6);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 8)
                    {
                        int[] bgTexIndexes6 = crimsonBG;
                        DrawSurfaceBG_Crimson(num18, num19, num20, bgTexIndexes6);
                        DrawSurfaceBG_DrawChangeOverlay(8);
                    }
                    if (bgAlphaFrontLayer[num14] > 0f && num14 == 9)
                    {
                        int[] bgTexIndexes7 = mushroomBG;
                        DrawSurfaceBG_Mushroom(num18, num19, num20, bgTexIndexes7);
                        DrawSurfaceBG_DrawChangeOverlay(11);
                    }
                    if (num14 >= 14)
                    {
                        LoaderManager.Get<SurfaceBackgroundStylesLoader>().DrawCloseBackground(num14);
                    }
                }
            }
        }
        if (flag2)
        {
            num20 -= num3;
        }
        float num15 = DrawSurfaceBG_GetFogPower();
        if (flag && num15 > 0f && !gameMenu && (double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            bgParallax = 0.1;
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, backgroundWidth[background]) - (double)(backgroundWidth[background] / 2));
            bgLoops = screenWidth / backgroundWidth[background] + 2;
            bgStartY = 0;
            bgLoopsY = 0;
            bgTopY = (int)((double)(0f - screenPosition.Y) / (worldSurface * 16.0 - 600.0) * 200.0);
            Texture2D value = TextureAssets.Background[49].Value;
            for (int num16 = 0; num16 < bgLoops; num16++)
            {
                bgStartX = 0;
                Color color5 = ColorOfTheSkies * num15 * atmo;
                int height = Math.Max(screenHeight + 210, value.Height);
                spriteBatch.Draw(value, new Rectangle(bgStartX + value.Width * num16, bgTopY, value.Width, height), color5);
            }
        }
        if (!mapFullscreen)
        {
            SkyManager.Instance.DrawRemainingDepth(spriteBatch);
        }
    }
References Terraria.Main.atmo, Terraria.GameContent.TextureAssets.Background, Terraria.Main.background, Terraria.Main.BackgroundEnabled, Terraria.Main.backgroundHeight, Terraria.Main.backgroundWidth, Terraria.Main.bgAlphaFrontLayer, Terraria.Main.bgLoops, Terraria.Main.bgLoopsY, Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgStartY, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.GameContent.TextureAssets.Cloud, Terraria.Main.cloud, Terraria.Main.cloudBG, Terraria.Main.cloudBGActive, Terraria.Main.cloudBGAlpha, Terraria.Main.cloudBGX, Terraria.Graphics.Light.Color, Terraria.Main.ColorOfSurfaceBackgroundsBase, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Main.ColorOfTheSkies, Terraria.Main.corruptBG, Terraria.Main.crimsonBG, Terraria.Main.cTop, Terraria.Main.desertBG, Terraria.Main.desiredWorldEventsUpdateRate, Terraria.Main.DrawSurfaceBG_BackMountainsStep1(), Terraria.Main.DrawSurfaceBG_BackMountainsStep2(), Terraria.Main.DrawSurfaceBG_Corrupt(), Terraria.Main.DrawSurfaceBG_Crimson(), Terraria.Main.DrawSurfaceBG_Desert(), Terraria.Main.DrawSurfaceBG_DrawChangeOverlay(), Terraria.Main.DrawSurfaceBG_Forest(), Terraria.Main.DrawSurfaceBG_GetFogPower(), Terraria.Main.DrawSurfaceBG_GoodEvilDesert(), Terraria.Main.DrawSurfaceBG_Hallow(), Terraria.Main.DrawSurfaceBG_Jungle(), Terraria.Main.DrawSurfaceBG_Mushroom(), Terraria.Main.DrawSurfaceBG_Snow(), Terraria.WorldGen.drunkWorldGen, Terraria.Main.gameMenu, Terraria.Main.gamePaused, Terraria.Main.hallowBG, Terraria.SceneMetrics.HallowTileMax, Terraria.SceneMetrics.HallowTileThreshold, Terraria.SceneMetrics.HolyTileCount, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.invasionType, Terraria.Main.jungleBG, Terraria.Main.LoadBackground(), Terraria.Main.mapFullscreen, Terraria.Main.mushroomBG, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.Main.scAdj, Terraria.Main.screenHeight, Terraria.Main.screenOff, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.SetBackgroundOffsets(), Terraria.Main.snowBG, Terraria.Main.spriteBatch, Terraria.Main.treeBGSet1, Terraria.Main.treeBGSet2, Terraria.Main.treeBGSet3, Terraria.Main.treeBGSet4, Terraria.Main.treeMntBGSet1, Terraria.Main.windSpeedCurrent, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawBG(), and Terraria.Main.DrawCapture().