TModLoader: Terraria.Main.DrawWaters
DrawWaters()
void Terraria.Main.DrawWaters (bool isBackground = false) inline private
Definition at line 73121 of file Main.cs.
    {
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0146: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        drewLava = false;
        if (!isBackground)
        {
            waterStyle = CalculateWaterStyle();
            for (int i = 0; i < 15; i++)
            {
                if (IsLiquidStyleWater(waterStyle))
                {
                    if (waterStyle != i)
                    {
                        liquidAlpha[i] = Math.Max(liquidAlpha[i] - 0.2f, 0f);
                    }
                    else
                    {
                        liquidAlpha[i] = Math.Min(liquidAlpha[i] + 0.2f, 1f);
                    }
                }
            }
            LoaderManager.Get<WaterStylesLoader>().UpdateLiquidAlphas();
        }
        if (!drawToScreen && !isBackground)
        {
            Vector2 vector = (Vector2)(drawToScreen ? Vector2.Zero : new Vector2((float)offScreenRange, (float)offScreenRange));
            int val = (int)((Camera.ScaledPosition.X - vector.X) / 16f - 1f);
            int val2 = (int)((Camera.ScaledPosition.X + Camera.ScaledSize.X + vector.X) / 16f) + 2;
            int val3 = (int)((Camera.ScaledPosition.Y - vector.Y) / 16f - 1f);
            int val4 = (int)((Camera.ScaledPosition.Y + Camera.ScaledSize.Y + vector.Y) / 16f) + 5;
            val = Math.Max(val, 5) - 2;
            val3 = Math.Max(val3, 5);
            val2 = Math.Min(val2, maxTilesX - 5) + 2;
            val4 = Math.Min(val4, maxTilesY - 5) + 4;
            Rectangle drawArea = default(Rectangle);
            ((Rectangle)(ref drawArea))._002Ector(val, val3, val2 - val, val4 - val3);
            LiquidRenderer.Instance.PrepareDraw(drawArea);
        }
        bool flag = false;
        for (int j = 0; j < LoaderManager.Get<WaterStylesLoader>().TotalCount; j++)
        {
            if (IsLiquidStyleWater(j) && liquidAlpha[j] > 0f && j != waterStyle)
            {
                DrawLiquid(isBackground, j, isBackground ? 1f : liquidAlpha[j], drawSinglePassLiquids: false);
                flag = true;
            }
        }
        DrawLiquid(isBackground, waterStyle, flag ? liquidAlpha[waterStyle] : 1f);
    }
References Terraria.Main.CalculateWaterStyle(), Terraria.Main.DrawLiquid(), Terraria.Main.drawToScreen, Terraria.Main.drewLava, Terraria.GameContent.Liquid.LiquidRenderer.Instance, Terraria.Main.IsLiquidStyleWater(), Terraria.Main.liquidAlpha, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.offScreenRange, Terraria.GameContent.Liquid.LiquidRenderer.PrepareDraw(), Terraria.Graphics.Camera.ScaledPosition, Terraria.Graphics.Camera.ScaledSize, and Terraria.Main.waterStyle.
Referenced by Terraria.Main.DoDraw(), Terraria.Main.RenderBackground(), and Terraria.Main.RenderWater().