TModLoader: Terraria.Main.QueueMainThreadAction
QueueMainThreadAction()
static void Terraria.Main.QueueMainThreadAction (Action action) inline static
    {
        _mainThreadActions.Enqueue(action);
    }
References Terraria.Main._mainThreadActions.
Referenced by Terraria.GameContent.NetModules.NetAmbienceModule.Deserialize(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.DownloadModsAndReturnToBrowser(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DownloadWithDeps(), Terraria.Main.NotifyOfEvent(), Terraria.ModLoader.UI.UIModPacks.OnActivate(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), Terraria.WorldGen.playWorldCallBack(), Terraria.ModLoader.UI.UIModSourceItem.PublishMod(), Terraria.Main.RunOnMainThread(), Terraria.Main.RunOnMainThread< T >(), Terraria.ModLoader.UI.UIInfoMessage.Show(), Terraria.ModLoader.UI.UIErrorMessage.Show(), and Terraria.ModLoader.TileLoader.Unload().