TModLoader: Terraria.Main.DrawSplash
DrawSplash()
void Terraria.Main.DrawSplash (GameTime gameTime) inline protected
Definition at line 66844 of file Main.cs.
    {
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0272: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0334: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_036f: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0386: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_0395: Unknown result type (might be due to invalid IL or missing references)
        int num = 10000;
        ((Game)this).GraphicsDevice.Clear(Color.Black);
        ((Game)this).Draw(gameTime);
        TickLoadProcess();
        long num2 = splashTimer.ElapsedMilliseconds;
        if (musicVolume == 0f)
        {
            quickSplash = true;
            num2 = 999999L;
            num = 0;
        }
        if (Assets.PendingAssets == 0 && _musicLoaded && _artLoaded && Program.LoadedEverything)
        {
            _isAsyncLoadComplete = true;
        }
        spriteBatch.Begin();
        splashCounter++;
        Color white = Color.White;
        byte b = 0;
        if (quickSplash)
        {
            if (splashCounter <= 75)
            {
                b = (byte)((float)splashCounter / 75f * 255f);
            }
            else if (splashCounter <= 125)
            {
                b = byte.MaxValue;
            }
            else if (splashCounter <= 200)
            {
                if (!_isAsyncLoadComplete)
                {
                    splashCounter = 125;
                }
                b = (byte)((float)(75 - (splashCounter - 125)) / 75f * 255f);
            }
            else
            {
                Initialize_AlmostEverything();
                PostContentLoadInitialize();
                showSplash = false;
                fadeCounter = 75;
                splashTimer.Stop();
            }
        }
        else
        {
            int num3 = 90;
            int num4 = 410;
            int num5 = 620;
            int num6 = 60;
            if (splashCounter >= num3)
            {
                if (splashCounter <= num4)
                {
                    float num7 = (float)(splashCounter - num3) / (float)(num4 - num3);
                    num7 *= num7 * num7 * num7;
                    num7 *= 255f;
                    b = (byte)num7;
                }
                else if (splashCounter <= num5)
                {
                    b = byte.MaxValue;
                    if (splashCounter >= num5 - num6)
                    {
                        b = (byte)((float)(num6 - (splashCounter - (num5 - num6))) / (float)num6 * 255f);
                    }
                }
                else if (!_isAsyncLoadComplete)
                {
                    b = 0;
                    num = 1;
                }
                else
                {
                    Initialize_AlmostEverything();
                    PostContentLoadInitialize();
                    showSplash = false;
                    fadeCounter = 120;
                    splashTimer.Stop();
                }
            }
        }
        ((Color)(ref white))._002Ector((int)b, (int)b, (int)b, (int)b);
        Asset<Texture2D> splashTextureLegoBack = TextureAssets.SplashTextureLegoBack;
        if (splashTextureLegoBack.Width() > 0 && splashTextureLegoBack.Height() > 0)
        {
            Vector2 val = new Vector2((float)screenWidth / (float)splashTextureLegoBack.Width(), (float)screenHeight / (float)splashTextureLegoBack.Height());
            _ = splashTextureLegoBack.Size() / 2f;
            Vector2 position = new Vector2((float)screenWidth, (float)screenHeight) / 2f;
            Vector2 scale = val;
            if (scale.X > scale.Y)
            {
                scale.X = scale.Y;
            }
            else
            {
                scale.Y = scale.X;
            }
            Vector2 scale2 = val;
            if (scale2.X < scale2.Y)
            {
                scale2.X = scale2.Y;
            }
            else
            {
                scale2.Y = scale2.X;
            }
            spriteBatch.Draw(splashTextureLegoBack.Value, position, (Rectangle?)null, white, 0f, splashTextureLegoBack.Size() / 2f, scale2, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.SplashTextureLegoTree.Value, ScreenSize.ToVector2(), (Rectangle?)null, white, 0f, TextureAssets.SplashTextureLegoTree.Size(), scale, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.SplashTextureLegoFront.Value, position, (Rectangle?)null, white, 0f, TextureAssets.SplashTextureLegoFront.Size() / 2f, scale, (SpriteEffects)0, 0f);
        }
        int num8 = 70;
        if (num == 1)
        {
            DrawSplash_LoadingFlower(Color.White);
        }
        else if (num2 > num)
        {
            DrawSplash_LoadingFlower(white);
        }
        _splashFrameCount += 1f;
        if (_splashFrameCount >= (float)num8)
        {
            _splashFrameCount = 0f;
        }
        spriteBatch.End();
    }
References Terraria.Main._artLoaded, Terraria.Main._isAsyncLoadComplete, Terraria.Main._musicLoaded, Terraria.Main._splashFrameCount, Terraria.Main.Assets, Terraria.Graphics.Light.Color, Terraria.Main.DrawSplash_LoadingFlower(), Terraria.Main.fadeCounter, Terraria.Main.Initialize_AlmostEverything(), Terraria.Program.LoadedEverything, Terraria.Main.musicVolume, Terraria.Main.PostContentLoadInitialize(), Terraria.Main.quickSplash, Terraria.Main.screenHeight, Terraria.Main.ScreenSize, Terraria.Main.screenWidth, Terraria.Main.showSplash, Terraria.Main.splashCounter, Terraria.GameContent.TextureAssets.SplashTextureLegoBack, Terraria.GameContent.TextureAssets.SplashTextureLegoFront, Terraria.GameContent.TextureAssets.SplashTextureLegoTree, Terraria.Main.splashTimer, Terraria.Main.spriteBatch, and Terraria.Main.TickLoadProcess().
Referenced by Terraria.Main.DoDraw().