TModLoader: Terraria.Main.MouseText
MouseText() [1/2]
void Terraria.Main.MouseText (string cursorText, int rare = 0, byte diff = 0, int hackedMouseX = -1, int hackedMouseY = -1, int hackedScreenWidth = -1, int hackedScreenHeight = -1, int pushWidthX = 0) inline
Definition at line 19466 of file Main.cs.
    {
        MouseText(cursorText, null, rare, diff, hackedMouseX, hackedMouseY, hackedScreenWidth, hackedScreenHeight, pushWidthX);
    }
References Terraria.Main.MouseText(), and Terraria.Main.rare.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.DisplayMouseTextIfHovered(), Terraria.GameContent.UI.IssueReportsIndicator.Draw(), Terraria.ModLoader.UI.UIButton< T >.Draw(), Terraria.Main.DrawBestiaryIcon(), Terraria.Graphics.Capture.CaptureInterface.DrawButtons(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.Main.DrawHotbarLockIcon(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInterface_33_MouseText(), Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawInterface_InstrumentMouseText(), Terraria.Main.DrawInventory(), Terraria.Main.DrawLoadoutButtons(), Terraria.Main.DrawMap(), Terraria.UI.AchievementAdvisor.DrawMouseHover(), Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.DrawMouseOver(), Terraria.Main.DrawNPCHousesInUI(), Terraria.Main.DrawNPCHousesInWorld(), Terraria.ModLoader.UI.UIBestiaryBar.DrawSelf(), Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.DrawSelf(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.DataStructures.TitleLinkButton.DrawTooltip(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices(), Terraria.Main.GUIChatDrawInner(), Terraria.IngameOptions.MouseOver(), Terraria.Main.MouseText(), Terraria.Main.MouseTextHackZoom(), Terraria.Main.MouseTextNoOverride(), Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.OnHover(), Terraria.ModLoader.Config.UI.UIModConfigList.PopulateConfigs(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.research_OnUpdate(), Terraria.GameContent.Bestiary.FilterProviderInfoElement.ShowButtonName(), Terraria.GameContent.Bestiary.ModBestiaryInfoElement.ShowButtonName(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.ShowButtonName(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.ShowButtonName(), Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ShowDescription(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Attack(), Terraria.GameContent.UI.States.UIBestiaryTest.ShowStats_Completion(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Defense(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Knockback(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Life(), and Terraria.ModLoader.UI.UICommon.TooltipMouseText().