TModLoader: Terraria.Main.DrawSurfaceBG_Forest
DrawSurfaceBG_Forest()
void Terraria.Main.DrawSurfaceBG_Forest (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
Definition at line 77636 of file Main.cs.
    {
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_0545: Unknown result type (might be due to invalid IL or missing references)
        //IL_0551: Unknown result type (might be due to invalid IL or missing references)
        //IL_0557: Unknown result type (might be due to invalid IL or missing references)
        //IL_0769: Unknown result type (might be due to invalid IL or missing references)
        //IL_0778: Unknown result type (might be due to invalid IL or missing references)
        //IL_0784: Unknown result type (might be due to invalid IL or missing references)
        //IL_078a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0357: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_0378: Unknown result type (might be due to invalid IL or missing references)
        bgScale = 1.25f;
        bgParallax = 0.4;
        bgTopY = (int)(backgroundTopMagicNumber * 1800.0 + 1500.0) + (int)scAdj + pushBGTopHack;
        if (bgTexIndexes[0] == 91)
        {
            bgParallax = 0.27000001072883606;
            bgScale = 1.2f;
        }
        if (bgTexIndexes[0] == 173)
        {
            bgParallax = 0.25;
            bgScale = 1.3f;
        }
        if (bgTexIndexes[0] == 178)
        {
            bgParallax = 0.30000001192092896;
            bgScale = 1.2f;
        }
        if (bgTexIndexes[0] == 184)
        {
            bgParallax = 0.25;
            bgScale = 1.2f;
        }
        if (bgTexIndexes[0] == 282)
        {
            bgScale = 1.4f;
        }
        SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
        bgScale *= bgGlobalScaleMultiplier;
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        if (bgTexIndexes[0] >= 0)
        {
            SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
            LoadBackground(bgTexIndexes[0]);
            bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[0]] * bgScale);
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
            if (bgTexIndexes[0] == 91)
            {
                bgTopY = (int)(backgroundTopMagicNumber * 1600.0 + 1400.0) + (int)scAdj + pushBGTopHack;
            }
            if (bgTexIndexes[0] == 173)
            {
                bgTopY = (int)(backgroundTopMagicNumber * 1600.0 + 1400.0) + (int)scAdj + pushBGTopHack;
            }
            if (bgTexIndexes[0] == 184)
            {
                bgTopY = (int)(backgroundTopMagicNumber * 1600.0 + 1400.0) + (int)scAdj + pushBGTopHack;
            }
            if (gameMenu)
            {
                bgTopY = 320 + pushBGTopHack;
            }
            if (bgTexIndexes[0] == 50)
            {
                bgTopY -= 50;
            }
            if (bgTexIndexes[0] == 53)
            {
                bgTopY -= 100;
            }
            if (bgTexIndexes[0] == 91)
            {
                bgTopY += 200;
            }
            if (bgTexIndexes[0] == 173)
            {
                bgTopY += 200;
            }
            if (bgTexIndexes[0] == 178)
            {
                bgTopY += 75;
            }
            bgLoops = screenWidth / bgWidthScaled + 2;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                for (int i = 0; i < bgLoops; i++)
                {
                    if (bgTexIndexes[0] != -1)
                    {
                        Asset<Texture2D> asset = TextureAssets.Background[bgTexIndexes[0]];
                        if (bgTexIndexes[0] == 173)
{
                            int num2 = (int)(GetBackgroundCounter() / 10);
                            num2 %= 4;
                            int num3 = 251 + num2;
                            LoadBackground(num3);
                            asset = TextureAssets.Background[num3];
                        }
                        if (asset.Value != null)
{
                            spriteBatch.Draw(asset.Value, new Vector2((float)(bgStartX + bgWidthScaled * i), (float)bgTopY), GetBackgroundRect(bgTexIndexes[0]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
                        }
                    }
                }
            }
        }
        if (bgTexIndexes[1] >= 0)
        {
            LoadBackground(bgTexIndexes[1]);
            bgScale = 1.31f;
            bgScale *= bgGlobalScaleMultiplier;
            bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[1]] * bgScale);
            if (bgWidthScaled == 0)
            {
                bgWidthScaled = 1;
            }
            bgParallax = 0.43;
            SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
            SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
            bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
            bgTopY = (int)(backgroundTopMagicNumber * 1950.0 + 1750.0) + (int)scAdj + pushBGTopHack;
            if (gameMenu)
            {
                bgTopY = 400 + pushBGTopHack;
                bgStartX -= 80;
            }
            if (bgTexIndexes[1] == 51)
            {
                bgTopY -= 50;
            }
            if (bgTexIndexes[1] == 54)
            {
                bgTopY -= 100;
            }
            bgLoops = screenWidth / bgWidthScaled + 2;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                for (int j = 0; j < bgLoops; j++)
                {
                    spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2((float)(bgStartX + bgWidthScaled * j), (float)bgTopY), GetBackgroundRect(bgTexIndexes[1]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)1, 0f);
                }
            }
        }
        if (bgTexIndexes[2] < 0)
        {
            return;
        }
        LoadBackground(bgTexIndexes[2]);
        bgScale = 1.34f;
        bgScale *= bgGlobalScaleMultiplier;
        bgParallax = 0.49;
        SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        if (bgTexIndexes[0] == 91)
        {
            bgScale = 1.3f;
            bgScale *= bgGlobalScaleMultiplier;
            bgParallax = 0.42;
        }
        if (bgTexIndexes[2] < 0 && WorldGen.drunkWorldGen)
        {
            return;
        }
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[2]] * bgScale);
        if (bgWidthScaled == 0)
        {
            bgWidthScaled = 1;
        }
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 2100.0 + 2000.0) + (int)scAdj + pushBGTopHack;
        if (gameMenu)
        {
            bgTopY = 480 + pushBGTopHack;
            bgStartX -= 120;
        }
        if (bgTexIndexes[2] == 52)
        {
            bgTopY -= 50;
        }
        if (bgTexIndexes[2] == 55)
        {
            bgTopY -= 100;
        }
        if (bgTexIndexes[2] == 92)
        {
            bgTopY += 150;
        }
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int k = 0; k < bgLoops; k++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(bgStartX + bgWidthScaled * k), (float)bgTopY), GetBackgroundRect(bgTexIndexes[2]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
    }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundWidth, Terraria.Main.bgLoops, Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.WorldGen.drunkWorldGen, Terraria.Main.gameMenu, Terraria.Main.GetBackgroundCounter(), Terraria.Main.GetBackgroundRect(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.LoadBackground(), Terraria.Main.scAdj, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.SetBackgroundOffsets(), Terraria.Main.spriteBatch, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawSurfaceBG().