TModLoader: Terraria.Main.UpdateSlimeRainWarning
UpdateSlimeRainWarning()
static void Terraria.Main.UpdateSlimeRainWarning () inline static private
    {
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        if (slimeWarningTime <= 0)
        {
            return;
        }
        slimeWarningTime--;
        if (slimeWarningTime > 0)
        {
            return;
        }
        if (netMode == 0)
        {
            if (slimeRainTime > 0.0)
            {
                NewText(Lang.gen[74].Value, 50, byte.MaxValue, 130);
            }
            else
            {
                NewText(Lang.gen[75].Value, 50, byte.MaxValue, 130);
            }
        }
        else if (slimeRainTime > 0.0)
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.gen[74].Key), new Color(50, 255, 130));
        }
        else
        {
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.gen[75].Key), new Color(50, 255, 130));
        }
    }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Graphics.Light.Color, Terraria.Localization.NetworkText.FromKey(), Terraria.Lang.gen, Terraria.Localization.LocalizedText.Key, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Main.slimeRainTime, Terraria.Main.slimeWarningTime, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.UpdateTime().