TModLoader: Terraria.Main.DrawProj_DrawYoyoString
DrawProj_DrawYoyoString()
void Terraria.Main.DrawProj_DrawYoyoString (Projectile proj, Vector2 mountedCenter) inline private
    {
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_038a: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03df: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        //IL_044c: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_047e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0483: Unknown result type (might be due to invalid IL or missing references)
        //IL_0497: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ba: Unknown result type (might be due to invalid IL or missing references)
        if (proj.aiStyle != 99)
        {
            return;
        }
        Vector2 vector = mountedCenter;
        vector.Y += player[proj.owner].gfxOffY;
        float num = proj.Center.X - vector.X;
        float num4 = proj.Center.Y - vector.Y;
        Math.Sqrt(num * num + num4 * num4);
        float num5 = (float)Math.Atan2(num4, num) - 1.57f;
        if (!proj.counterweight)
        {
            int num6 = -1;
            if (proj.position.X + (float)(proj.width / 2) < player[proj.owner].position.X + (float)(player[proj.owner].width / 2))
            {
                num6 = 1;
            }
            num6 *= -1;
            player[proj.owner].itemRotation = (float)Math.Atan2(num4 * (float)num6, num * (float)num6);
        }
        bool flag = true;
        bool flag2 = true;
        if (num == 0f && num4 == 0f)
        {
            flag = false;
        }
        else
        {
            float num7 = (float)Math.Sqrt(num * num + num4 * num4);
            num7 = 12f / num7;
            num *= num7;
            num4 *= num7;
            vector.X -= num * 0.1f;
            vector.Y -= num4 * 0.1f;
            num = proj.position.X + (float)proj.width * 0.5f - vector.X;
            num4 = proj.position.Y + (float)proj.height * 0.5f - vector.Y;
        }
        Color color = default(Color);
        while (flag)
        {
            float num8 = 12f;
            float num9 = (float)Math.Sqrt(num * num + num4 * num4);
            float num10 = num9;
            if (float.IsNaN(num9) || float.IsNaN(num10))
            {
                flag = false;
                continue;
            }
            if (num9 < 20f)
            {
                num8 = num9 - 8f;
                flag = false;
            }
            num9 = 12f / num9;
            num *= num9;
            num4 *= num9;
            if (flag2)
            {
                flag2 = false;
            }
            else
            {
                vector.X += num;
                vector.Y += num4;
            }
            num = proj.position.X + (float)proj.width * 0.5f - vector.X;
            num4 = proj.position.Y + (float)proj.height * 0.1f - vector.Y;
            if (num10 > 12f)
            {
                float num11 = 0.3f;
                float num2 = Math.Abs(proj.velocity.X) + Math.Abs(proj.velocity.Y);
                if (num2 > 16f)
                {
                    num2 = 16f;
                }
                num2 = 1f - num2 / 16f;
                num11 *= num2;
                num2 = num10 / 80f;
                if (num2 > 1f)
                {
                    num2 = 1f;
                }
                num11 *= num2;
                if (num11 < 0f)
                {
                    num11 = 0f;
                }
                num11 *= num2;
                num11 *= 0.5f;
                if (num4 > 0f)
                {
                    num4 *= 1f + num11;
                    num *= 1f - num11;
                }
                else
                {
                    num2 = Math.Abs(proj.velocity.X) / 3f;
                    if (num2 > 1f)
                    {
                        num2 = 1f;
                    }
                    num2 -= 0.5f;
                    num11 *= num2;
                    if (num11 > 0f)
                    {
                        num11 *= 2f;
                    }
                    num4 *= 1f + num11;
                    num *= 1f - num11;
                }
            }
            num5 = (float)Math.Atan2(num4, num) - 1.57f;
            Color white = Color.White;
            ((Color)(ref white)).A = (byte)((float)(int)((Color)(ref white)).A * 0.4f);
            white = TryApplyingPlayerStringColor(player[proj.owner].stringColor, white);
            float num3 = 0.5f;
            white = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f), white);
            ((Color)(ref color))._002Ector((int)(byte)((float)(int)((Color)(ref white)).R * num3), (int)(byte)((float)(int)((Color)(ref white)).G * num3), (int)(byte)((float)(int)((Color)(ref white)).B * num3), (int)(byte)((float)(int)((Color)(ref white)).A * num3));
            EntitySpriteDraw(TextureAssets.FishingLine.Value, new Vector2(vector.X - screenPosition.X + (float)TextureAssets.FishingLine.Width() * 0.5f, vector.Y - screenPosition.Y + (float)TextureAssets.FishingLine.Height() * 0.5f) - new Vector2(6f, 0f), (Rectangle?)new Rectangle(0, 0, TextureAssets.FishingLine.Width(), (int)num8), color, num5, new Vector2((float)TextureAssets.FishingLine.Width() * 0.5f, 0f), 1f, (SpriteEffects)0, 0f);
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.FishingLine, Terraria.Lighting.GetColor(), Terraria.Player.gfxOffY, Terraria.Player.itemRotation, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.screenPosition, Terraria.Player.stringColor, Terraria.Main.TryApplyingPlayerStringColor(), and Terraria.Entity.width.
Referenced by Terraria.Main.DrawProj_Inner().