TModLoader: Terraria.Main.DrawProj_TerraBlade2Shot
DrawProj_TerraBlade2Shot()
void Terraria.Main.DrawProj_TerraBlade2Shot (Projectile proj) inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0123: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0180: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0236: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_0319: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0334: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_0369: Unknown result type (might be due to invalid IL or missing references)
        //IL_036f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0373: Unknown result type (might be due to invalid IL or missing references)
        //IL_037a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_0423: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_044e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_0470: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0484: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0502: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0543: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        //IL_055e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0565: Unknown result type (might be due to invalid IL or missing references)
        //IL_056a: Unknown result type (might be due to invalid IL or missing references)
        //IL_056f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0587: Unknown result type (might be due to invalid IL or missing references)
        //IL_0599: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_07da: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0800: Unknown result type (might be due to invalid IL or missing references)
        //IL_0805: Unknown result type (might be due to invalid IL or missing references)
        //IL_080a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0813: Unknown result type (might be due to invalid IL or missing references)
        //IL_0825: Unknown result type (might be due to invalid IL or missing references)
        //IL_082c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_083b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0874: Unknown result type (might be due to invalid IL or missing references)
        //IL_087b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0880: Unknown result type (might be due to invalid IL or missing references)
        //IL_0887: Unknown result type (might be due to invalid IL or missing references)
        //IL_0891: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0908: Unknown result type (might be due to invalid IL or missing references)
        //IL_090f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0914: Unknown result type (might be due to invalid IL or missing references)
        //IL_091b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0925: Unknown result type (might be due to invalid IL or missing references)
        //IL_0632: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0663: Unknown result type (might be due to invalid IL or missing references)
        //IL_066a: Unknown result type (might be due to invalid IL or missing references)
        //IL_066f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0674: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0701: Unknown result type (might be due to invalid IL or missing references)
        //IL_0708: Unknown result type (might be due to invalid IL or missing references)
        //IL_070f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0714: Unknown result type (might be due to invalid IL or missing references)
        //IL_071b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0722: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_0745: Unknown result type (might be due to invalid IL or missing references)
        //IL_074c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0756: Unknown result type (might be due to invalid IL or missing references)
        //IL_075b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0799: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ba: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = proj.Center - screenPosition;
        Asset<Texture2D> asset = TextureAssets.Projectile[proj.type];
        Rectangle rectangle = asset.Frame(1, 4);
        Vector2 origin = rectangle.Size() / 2f;
        float scale = proj.scale;
        SpriteEffects spriteEffects = (SpriteEffects)((!(proj.ai[0] >= 0f)) ? 2 : 0);
        SpriteEffects effects = (SpriteEffects)(spriteEffects ^ 2);
        float num = Utils.Remap(proj.localAI[0], 0f, proj.ai[1] + 30f, 0f, 1f);
        float opacity = proj.Opacity;
        float num5 = 0.975f;
        Color color6 = Lighting.GetColor(proj.Center.ToTileCoordinates());
        Vector3 val = ((Color)(ref color6)).ToVector3();
        float num6 = ((Vector3)(ref val)).Length() / (float)Math.Sqrt(3.0);
        num6 = 0.5f + num6 * 0.5f;
        num6 = Utils.Remap(num6, 0.2f, 1f, 0f, 1f);
        Color color = default(Color);
        ((Color)(ref color))._002Ector(45, 124, 205);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color * num6 * opacity, proj.rotation + proj.ai[0] * ((float)Math.PI / 4f) * 0.5f * -1f * (1f - num), origin, scale * 0.95f, spriteEffects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color * num6 * opacity, proj.rotation + proj.ai[0] * ((float)Math.PI / 4f) * 0.5f * 1f * (1f - num), origin, scale * 0.95f, effects, 0f);
        Color color2 = default(Color);
        ((Color)(ref color2))._002Ector(181, 230, 29);
        Color color3 = default(Color);
        ((Color)(ref color3))._002Ector(34, 177, 76);
        Color color4 = Color.White * opacity * 0.5f;
        ((Color)(ref color4)).A = (byte)((float)(int)((Color)(ref color4)).A * (1f - num6));
        Color color5 = color4 * num6 * 0.5f;
        ((Color)(ref color5)).G = (byte)((float)(int)((Color)(ref color5)).G * num6);
        ((Color)(ref color5)).B = (byte)((float)(int)((Color)(ref color5)).R * (0.25f + num6 * 0.75f));
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color5 * 0.15f, proj.rotation + proj.ai[0] * 0.01f, origin, scale, spriteEffects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color5 * 0.15f, proj.rotation + proj.ai[0] * -0.01f, origin, scale, effects, 0f);
        float num7 = 1f - num;
        float num8 = 0.25f;
        float num9 = 0.15f;
        float num10 = 0.05f;
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color3 * num6 * opacity * 0.3f, proj.rotation + proj.ai[0] * num8 * num7, origin, scale, spriteEffects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color3 * num6 * opacity * 0.3f, proj.rotation + (0f - proj.ai[0]) * num8 * num7, origin, scale, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color2 * num6 * opacity * 0.5f, proj.rotation + proj.ai[0] * num9 * num7, origin, scale * num5, spriteEffects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.6f * opacity, proj.rotation + proj.ai[0] * num10 * num7, origin, scale, spriteEffects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.5f * opacity, proj.rotation + proj.ai[0] * -0.05f, origin, scale * 0.8f, spriteEffects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.4f * opacity, proj.rotation + proj.ai[0] * -0.1f, origin, scale * 0.6f, spriteEffects, 0f);
        for (float num11 = -9f; num11 < 9f; num11 += 1f)
        {
            float num12 = proj.rotation + proj.ai[0] * num11 * ((float)Math.PI * -2f) * 0.025f;
            Vector2 drawpos = vector + num12.ToRotationVector2() * ((float)asset.Width() * 0.5f - 6f) * scale;
            float num2 = Math.Abs(num11) / 9f;
            DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos, new Color(255, 255, 255, 0) * opacity * num2, color3, num, 0f, 0.5f, 0.5f, 1f, num12, new Vector2(0f, Utils.Remap(num, 0f, 1f, 3f, 0f)) * scale, Vector2.One * scale);
        }
        for (float num3 = -1f; num3 <= 1f; num3 += 0.5f)
        {
            if (num3 != 0f)
            {
                Vector2 drawpos2 = vector + (proj.rotation + num3 * (float)Math.PI * 0.75f * num).ToRotationVector2() * ((float)asset.Width() * 0.5f - 4f) * scale;
                float num4 = Utils.Remap(Math.Abs(num3), 0f, 1f, 1f, 0.5f);
                DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos2, new Color(255, 255, 255, 0) * opacity * 0.5f, color3, num, 0f, 0.5f, 0.5f, 0.75f, (float)Math.PI / 4f, new Vector2(Utils.Remap(num, 0f, 1f, 4f, 1f)) * scale * num4, Vector2.One * scale * num4);
                DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos2, new Color(255, 255, 255, 0) * opacity * 0.5f, color3, num, 0f, 0.5f, 0.5f, 0.75f, 0f, new Vector2(2f, Utils.Remap(num, 0f, 1f, 4f, 1f)) * scale * num4, Vector2.One * scale * num4);
            }
        }
        Vector2 drawpos3 = vector + proj.rotation.ToRotationVector2() * ((float)asset.Width() * 0.5f - 4f) * scale;
        DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos3, new Color(255, 255, 255, 0) * opacity * 0.5f, color3, num, 0f, 0.5f, 0.5f, 1f, (float)Math.PI / 4f, new Vector2(Utils.Remap(num, 0f, 1f, 4f, 1f)) * scale, Vector2.One * scale * 1.5f);
        DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos3, new Color(255, 255, 255, 0) * opacity * 0.5f, color3, num, 0f, 0.5f, 0.5f, 1f, 0f, new Vector2(2f, Utils.Remap(num, 0f, 1f, 4f, 1f)) * scale, Vector2.One * scale * 1.5f);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DrawPrettyStarSparkle(), Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().