TModLoader: Terraria.Main.GetPlayerArmPosition
GetPlayerArmPosition()
static Vector2 Terraria.Main.GetPlayerArmPosition (Projectile proj) inline static
Definition at line 48263 of file Main.cs.
    {
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[proj.owner];
        Vector2 vector = OffsetsPlayerOnhand[player.bodyFrame.Y / 56] * 2f;
        if (player.direction != 1)
        {
            vector.X = (float)player.bodyFrame.Width - vector.X;
        }
        if (player.gravDir != 1f)
        {
            vector.Y = (float)player.bodyFrame.Height - vector.Y;
        }
        vector -= new Vector2((float)(player.bodyFrame.Width - player.width), (float)(player.bodyFrame.Height - 42)) / 2f;
        Vector2 pos = player.MountedCenter - new Vector2(20f, 42f) / 2f + vector + Vector2.UnitY * player.gfxOffY;
        if (player.mount.Active && player.mount.Type == 52)
        {
            pos.Y -= player.mount.PlayerOffsetHitbox;
            pos += new Vector2((float)(12 * player.direction), -12f);
        }
        return player.RotatedRelativePoint(pos);
    }
References Terraria.Mount.Active, Terraria.Player.bodyFrame, Terraria.Entity.direction, Terraria.Player.gfxOffY, Terraria.Player.gravDir, Terraria.Player.mount, Terraria.Main.OffsetsPlayerOnhand, Terraria.Main.player, Terraria.Mount.PlayerOffsetHitbox, Terraria.Player.RotatedRelativePoint(), Terraria.Mount.Type, and Terraria.Entity.width.
Referenced by Terraria.Projectile.AI_165_Whip(), Terraria.Main.DrawKite(), Terraria.Main.DrawProj_FlailChains(), and Terraria.Projectile.FillWhipControlPoints().