TModLoader: Terraria.Main.DrawWires
DrawWires()
void Terraria.Main.DrawWires () inline protected
Definition at line 74315 of file Main.cs.
    {
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_1101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_1156: Unknown result type (might be due to invalid IL or missing references)
        //IL_115b: Unknown result type (might be due to invalid IL or missing references)
        //IL_115d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1162: Unknown result type (might be due to invalid IL or missing references)
        //IL_1181: Unknown result type (might be due to invalid IL or missing references)
        //IL_1186: Unknown result type (might be due to invalid IL or missing references)
        //IL_1188: Unknown result type (might be due to invalid IL or missing references)
        //IL_118d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1194: Unknown result type (might be due to invalid IL or missing references)
        //IL_1196: Unknown result type (might be due to invalid IL or missing references)
        //IL_1198: Unknown result type (might be due to invalid IL or missing references)
        //IL_119d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fff: Unknown result type (might be due to invalid IL or missing references)
        //IL_104d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1052: Unknown result type (might be due to invalid IL or missing references)
        //IL_1054: Unknown result type (might be due to invalid IL or missing references)
        //IL_106f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1079: Unknown result type (might be due to invalid IL or missing references)
        //IL_107c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1088: Unknown result type (might be due to invalid IL or missing references)
        //IL_108e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1003: Unknown result type (might be due to invalid IL or missing references)
        //IL_100a: Unknown result type (might be due to invalid IL or missing references)
        //IL_100f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1013: Unknown result type (might be due to invalid IL or missing references)
        //IL_1018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0355: Unknown result type (might be due to invalid IL or missing references)
        //IL_033c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_050a: Unknown result type (might be due to invalid IL or missing references)
        //IL_050c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0503: Unknown result type (might be due to invalid IL or missing references)
        //IL_0508: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_055a: Unknown result type (might be due to invalid IL or missing references)
        //IL_055f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0561: Unknown result type (might be due to invalid IL or missing references)
        //IL_0566: Unknown result type (might be due to invalid IL or missing references)
        //IL_056c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0576: Unknown result type (might be due to invalid IL or missing references)
        //IL_0580: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cd9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cee: Unknown result type (might be due to invalid IL or missing references)
        //IL_094d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0952: Unknown result type (might be due to invalid IL or missing references)
        //IL_0954: Unknown result type (might be due to invalid IL or missing references)
        //IL_0959: Unknown result type (might be due to invalid IL or missing references)
        //IL_095f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0969: Unknown result type (might be due to invalid IL or missing references)
        //IL_0973: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d40: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d45: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d66: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05de: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09da: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0654: Unknown result type (might be due to invalid IL or missing references)
        //IL_0659: Unknown result type (might be due to invalid IL or missing references)
        //IL_065b: Unknown result type (might be due to invalid IL or missing references)
        //IL_066a: Unknown result type (might be due to invalid IL or missing references)
        //IL_066f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0676: Unknown result type (might be due to invalid IL or missing references)
        //IL_0682: Unknown result type (might be due to invalid IL or missing references)
        //IL_068c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0693: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dd7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a86: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0705: Unknown result type (might be due to invalid IL or missing references)
        //IL_070a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0711: Unknown result type (might be due to invalid IL or missing references)
        //IL_071a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0724: Unknown result type (might be due to invalid IL or missing references)
        //IL_072b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e50: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e55: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_077e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0783: Unknown result type (might be due to invalid IL or missing references)
        //IL_0785: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0798: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eeb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b95: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8f: Unknown result type (might be due to invalid IL or missing references)
        Rectangle value = default(Rectangle);
        ((Rectangle)(ref value))._002Ector(0, 0, 16, 16);
        Vector2 zero = Vector2.Zero;
        DrawWiresSpecialTiles.Clear();
        bool flag = !WiresUI.Settings.HideWires;
        float num = 1f;
        if (WiresUI.Settings.HideWires)
        {
            num = 0.5f;
        }
        int num9 = 1;
        int num10 = 1;
        int num11 = 1;
        int num12 = 1;
        int num13 = 1;
        if (player[myPlayer].InfoAccMechShowWires)
        {
            int[] builderAccStatus = player[myPlayer].builderAccStatus;
            num9 = builderAccStatus[4];
            num10 = builderAccStatus[5];
            num11 = builderAccStatus[6];
            num12 = builderAccStatus[7];
            num13 = builderAccStatus[9];
        }
        _ = gfxQuality;
        _ = gfxQuality;
        Vector2 zero2 = Vector2.Zero;
        if (drawToScreen)
        {
            zero2 = Vector2.Zero;
        }
        int num14 = (int)((screenPosition.X - zero2.X) / 16f - 1f);
        int num15 = (int)((screenPosition.X + (float)screenWidth + zero2.X) / 16f) + 2;
        int num16 = (int)((screenPosition.Y - zero2.Y) / 16f - 1f);
        int num2 = (int)((screenPosition.Y + (float)screenHeight + zero2.Y) / 16f) + 5;
        if (num14 < 0)
        {
            num14 = 0;
        }
        if (num15 > maxTilesX)
        {
            num15 = maxTilesX;
        }
        if (num16 < 0)
        {
            num16 = 0;
        }
        if (num2 > maxTilesY)
        {
            num2 = maxTilesY;
        }
        Point screenOverdrawOffset = GetScreenOverdrawOffset();
        for (int i = num16 + screenOverdrawOffset.Y; i < num2 - screenOverdrawOffset.Y; i++)
        {
            for (int j = num14 + screenOverdrawOffset.X; j < num15 - screenOverdrawOffset.X; j++)
            {
                bool flag3 = false;
                bool flag4 = false;
                bool flag5 = false;
                bool flag6 = false;
                bool flag7 = false;
                bool flag8 = false;
                bool flag9 = false;
                bool flag10 = false;
                bool flag2 = false;
                float num3 = 0f;
                Tile tile = Main.tile[j, i];
                if (flag && player[myPlayer].CanDoWireStuffHere(j, i))
                {
                    int num4 = 0;
                    if (tile.active())
                    {
                        if (tile.type == 424)
{
                            switch (tile.frameX / 18)
{
                            case 0:
                                num4 += 72;
                                break;
                            case 1:
                                num4 += 144;
                                break;
                            case 2:
                                num4 += 216;
                                break;
                            }
                        }
                        else if (tile.type == 445)
{
                            num4 += 72;
                        }
                    }
                    if (tile.wire())
                    {
                        num3 += 1f;
                        int num5 = 0;
                        if (Main.tile[j, i - 1].wire())
{
                            num5 += 18;
                            flag5 = true;
                        }
                        if (Main.tile[j + 1, i].wire())
{
                            num5 += 36;
                            flag4 = true;
                        }
                        if (Main.tile[j, i + 1].wire())
{
                            num5 += 72;
                            flag6 = true;
                        }
                        if (Main.tile[j - 1, i].wire())
{
                            num5 += 144;
                            flag3 = true;
                        }
                        value.Y = num4;
                        value.X = num5;
                        Color color = Lighting.GetColor(j, i);
                        switch (num9)
{
                        case 0:
                            color = Color.White;
                            break;
                        case 2:
                            color *= 0.5f;
                            break;
                        case 3:
                            color = Color.Transparent;
                            break;
                        }
                        if (color == Color.Transparent)
{
                            num3 -= 1f;
                        }
                        else
{
                            spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)value, color, 0f, zero, 1f, (SpriteEffects)0, 0f);
                        }
                    }
                    if (tile.wire2())
                    {
                        flag7 = (flag8 = (flag9 = (flag10 = (flag2 = false))));
                        num3 += 1f;
                        int num6 = 0;
                        if (Main.tile[j, i - 1].wire2())
{
                            num6 += 18;
                            flag9 = true;
                            if (flag5)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j + 1, i].wire2())
{
                            num6 += 36;
                            flag8 = true;
                            if (flag4)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j, i + 1].wire2())
{
                            num6 += 72;
                            flag10 = true;
                            if (flag6)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j - 1, i].wire2())
{
                            num6 += 144;
                            flag7 = true;
                            if (flag3)
{
                                flag2 = true;
                            }
                        }
                        if (num3 > 1f)
{
                            flag2 = true;
                        }
                        value.Y = num4 + 18;
                        value.X = num6;
                        Color color2 = Lighting.GetColor(j, i);
                        switch (num10)
{
                        case 0:
                            color2 = Color.White;
                            break;
                        case 2:
                            color2 *= 0.5f;
                            break;
                        case 3:
                            color2 = Color.Transparent;
                            break;
                        }
                        if (color2 == Color.Transparent)
{
                            num3 -= 1f;
                        }
                        else
{
                            spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)value, color2 * (1f / num3), 0f, zero, 1f, (SpriteEffects)0, 0f);
                            if (flag9)
{
                                if (flag2 && !flag5)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)new Rectangle(18, value.Y, 16, 6), color2, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag5 = true;
                            }
                            if (flag10)
{
                                if (flag2 && !flag6)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2 + new Vector2(0f, 10f), (Rectangle?)new Rectangle(72, value.Y + 10, 16, 6), color2, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag6 = true;
                            }
                            if (flag8)
{
                                if (flag2 && !flag4)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2 + new Vector2(10f, 0f), (Rectangle?)new Rectangle(46, value.Y, 6, 16), color2, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag4 = true;
                            }
                            if (flag7)
{
                                if (flag2 && !flag3)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)new Rectangle(144, value.Y, 6, 16), color2, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag3 = true;
                            }
                        }
                    }
                    if (tile.wire3())
                    {
                        flag7 = (flag8 = (flag9 = (flag10 = (flag2 = false))));
                        num3 += 1f;
                        int num7 = 0;
                        if (Main.tile[j, i - 1].wire3())
{
                            num7 += 18;
                            flag9 = true;
                            if (flag5)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j + 1, i].wire3())
{
                            num7 += 36;
                            flag8 = true;
                            if (flag4)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j, i + 1].wire3())
{
                            num7 += 72;
                            flag10 = true;
                            if (flag6)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j - 1, i].wire3())
{
                            num7 += 144;
                            flag7 = true;
                            if (flag3)
{
                                flag2 = true;
                            }
                        }
                        if (num3 > 1f)
{
                            flag2 = true;
                        }
                        value.Y = num4 + 36;
                        value.X = num7;
                        Color color3 = Lighting.GetColor(j, i);
                        switch (num11)
{
                        case 0:
                            color3 = Color.White;
                            break;
                        case 2:
                            color3 *= 0.5f;
                            break;
                        case 3:
                            color3 = Color.Transparent;
                            break;
                        }
                        if (color3 == Color.Transparent)
{
                            num3 -= 1f;
                        }
                        else
{
                            spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)value, color3 * (1f / num3), 0f, zero, 1f, (SpriteEffects)0, 0f);
                            if (flag9)
{
                                if (flag2 && !flag5)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)new Rectangle(18, value.Y, 16, 6), color3, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag5 = true;
                            }
                            if (flag10)
{
                                if (flag2 && !flag6)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2 + new Vector2(0f, 10f), (Rectangle?)new Rectangle(72, value.Y + 10, 16, 6), color3, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag6 = true;
                            }
                            if (flag8)
{
                                if (flag2 && !flag4)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2 + new Vector2(10f, 0f), (Rectangle?)new Rectangle(46, value.Y, 6, 16), color3, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag4 = true;
                            }
                            if (flag7)
{
                                if (flag2 && !flag3)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)new Rectangle(144, value.Y, 6, 16), color3, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag3 = true;
                            }
                        }
                    }
                    if (tile.wire4())
                    {
                        flag7 = (flag8 = (flag9 = (flag10 = (flag2 = false))));
                        num3 += 1f;
                        int num8 = 0;
                        if (Main.tile[j, i - 1].wire4())
{
                            num8 += 18;
                            flag9 = true;
                            if (flag5)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j + 1, i].wire4())
{
                            num8 += 36;
                            flag8 = true;
                            if (flag4)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j, i + 1].wire4())
{
                            num8 += 72;
                            flag10 = true;
                            if (flag6)
{
                                flag2 = true;
                            }
                        }
                        if (Main.tile[j - 1, i].wire4())
{
                            num8 += 144;
                            flag7 = true;
                            if (flag3)
{
                                flag2 = true;
                            }
                        }
                        if (num3 > 1f)
{
                            flag2 = true;
                        }
                        value.Y = num4 + 54;
                        value.X = num8;
                        Color color4 = Lighting.GetColor(j, i);
                        switch (num12)
{
                        case 0:
                            color4 = Color.White;
                            break;
                        case 2:
                            color4 *= 0.5f;
                            break;
                        case 3:
                            color4 = Color.Transparent;
                            break;
                        }
                        if (color4 == Color.Transparent)
{
                            num3 -= 1f;
                        }
                        else
{
                            spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)value, color4 * (1f / num3), 0f, zero, 1f, (SpriteEffects)0, 0f);
                            if (flag9)
{
                                if (flag2 && !flag5)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)new Rectangle(18, value.Y, 16, 6), color4, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag5 = true;
                            }
                            if (flag10)
{
                                if (flag2 && !flag6)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2 + new Vector2(0f, 10f), (Rectangle?)new Rectangle(72, value.Y + 10, 16, 6), color4, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag6 = true;
                            }
                            if (flag8)
{
                                if (flag2 && !flag4)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2 + new Vector2(10f, 0f), (Rectangle?)new Rectangle(46, value.Y, 6, 16), color4, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag4 = true;
                            }
                            if (flag7)
{
                                if (flag2 && !flag3)
{
                                    spriteBatch.Draw(TextureAssets.WireNew.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)new Rectangle(144, value.Y, 6, 16), color4, 0f, zero, 1f, (SpriteEffects)0, 0f);
                                }
                                flag3 = true;
                            }
                        }
                    }
                }
                if (Main.tile[j, i].actuator() && (Lighting.Brightness(j, i) > 0f || num13 == 0))
                {
                    Color color5 = Lighting.GetColor(j, i);
                    switch (num13)
                    {
                    case 0:
                        color5 = Color.White;
                        break;
                    case 2:
                        color5 *= 0.5f;
                        break;
                    case 3:
                        color5 = Color.Transparent;
                        break;
                    }
                    spriteBatch.Draw(TextureAssets.Actuator.Value, new Vector2((float)(j * 16 - (int)screenPosition.X), (float)(i * 16 - (int)screenPosition.Y)) + zero2, (Rectangle?)new Rectangle(0, 0, TextureAssets.Actuator.Width(), TextureAssets.Actuator.Height()), color5 * num, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                }
                if (tile.active() && tile.type == 423 && tile.frameY == 36)
                {
                    DrawWiresSpecialTiles.Add(Tuple.Create(j, i, tile.type));
                }
            }
        }
        for (int k = 0; k < DrawWiresSpecialTiles.Count; k++)
        {
            Tuple<int, int, ushort> tuple = DrawWiresSpecialTiles[k];
            if (tuple.Item3 == 423)
            {
                Vector2 start = new Vector2((float)(tuple.Item1 * 16 - 32 - 1), (float)(tuple.Item2 * 16 - 160 - 1)) + zero2;
                Vector2 end = new Vector2((float)(tuple.Item1 * 16 + 48 + 1), (float)(tuple.Item2 * 16 + 1)) + zero2;
                Utils.DrawRectangle(spriteBatch, start, end, Color.LightSeaGreen, Color.LightSeaGreen, 2f);
            }
        }
        TimeLogger.DetailedDrawTime(34);
    }
References Terraria.GameContent.TextureAssets.Actuator, Terraria.Lighting.Brightness(), Terraria.Player.builderAccStatus, Terraria.Graphics.Light.Color, Terraria.TimeLogger.DetailedDrawTime(), Terraria.Utils.DrawRectangle(), Terraria.Main.drawToScreen, Terraria.Main.DrawWiresSpecialTiles, Terraria.Lighting.GetColor(), Terraria.Main.GetScreenOverdrawOffset(), Terraria.Main.gfxQuality, Terraria.GameContent.UI.WiresUI.Settings.HideWires, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.Main.tile, and Terraria.GameContent.TextureAssets.WireNew.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().