TModLoader: Terraria.Main.DrawNPCDirect_HallowBoss
DrawNPCDirect_HallowBoss()
static void Terraria.Main.DrawNPCDirect_HallowBoss (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
Definition at line 30699 of file Main.cs.
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0724: Unknown result type (might be due to invalid IL or missing references)
        //IL_0728: Unknown result type (might be due to invalid IL or missing references)
        //IL_072d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0732: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_073a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0742: Unknown result type (might be due to invalid IL or missing references)
        //IL_0744: Unknown result type (might be due to invalid IL or missing references)
        //IL_074e: Unknown result type (might be due to invalid IL or missing references)
        //IL_075f: Unknown result type (might be due to invalid IL or missing references)
        //IL_079e: Unknown result type (might be due to invalid IL or missing references)
        //IL_079f: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0790: Unknown result type (might be due to invalid IL or missing references)
        //IL_088c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0891: Unknown result type (might be due to invalid IL or missing references)
        //IL_089b: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0839: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02de: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_090f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0914: Unknown result type (might be due to invalid IL or missing references)
        //IL_0919: Unknown result type (might be due to invalid IL or missing references)
        //IL_091a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0921: Unknown result type (might be due to invalid IL or missing references)
        //IL_092b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0936: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_0354: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_0387: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_040a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_041b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0432: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_0455: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0951: Unknown result type (might be due to invalid IL or missing references)
        //IL_0967: Unknown result type (might be due to invalid IL or missing references)
        //IL_096d: Unknown result type (might be due to invalid IL or missing references)
        //IL_096f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0985: Unknown result type (might be due to invalid IL or missing references)
        //IL_098a: Unknown result type (might be due to invalid IL or missing references)
        //IL_098f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0990: Unknown result type (might be due to invalid IL or missing references)
        //IL_0992: Unknown result type (might be due to invalid IL or missing references)
        //IL_0997: Unknown result type (might be due to invalid IL or missing references)
        //IL_099e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a44: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a93: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05af: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0609: Unknown result type (might be due to invalid IL or missing references)
        //IL_04db: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0500: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0678: Unknown result type (might be due to invalid IL or missing references)
        //IL_067b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_068f: Unknown result type (might be due to invalid IL or missing references)
        //IL_069a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0642: Unknown result type (might be due to invalid IL or missing references)
        //IL_0647: Unknown result type (might be due to invalid IL or missing references)
        //IL_064c: Unknown result type (might be due to invalid IL or missing references)
        //IL_064e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0655: Unknown result type (might be due to invalid IL or missing references)
        //IL_065f: Unknown result type (might be due to invalid IL or missing references)
        //IL_066a: Unknown result type (might be due to invalid IL or missing references)
        //IL_055d: Unknown result type (might be due to invalid IL or missing references)
        //IL_055f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0569: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_057e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_0588: Unknown result type (might be due to invalid IL or missing references)
        //IL_058a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_0599: Unknown result type (might be due to invalid IL or missing references)
        //IL_0502: Unknown result type (might be due to invalid IL or missing references)
        //IL_050c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0513: Unknown result type (might be due to invalid IL or missing references)
        //IL_051a: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b08: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fb: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Npc[typeCache].Value;
        Vector2 vector = rCurrentNPC.Center - screenPos;
        bool flag = rCurrentNPC.AI_120_HallowBoss_IsInPhase2();
        int num = (int)rCurrentNPC.ai[0];
        Texture2D value4 = TextureAssets.Extra[159].Value;
        Rectangle rectangle = value4.Frame(1, 11, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 11);
        Color color = rCurrentNPC.GetAlpha(npcColor);
        Texture2D value5 = TextureAssets.Extra[158].Value;
        Texture2D value6 = TextureAssets.Extra[160].Value;
        Texture2D value7 = TextureAssets.Extra[157].Value;
        DrawNPCDirect_GetHallowBossArmFrame(rCurrentNPC, out var armFrame_Count, out var armFrameToUseLeft, out var armFrameToUseRight);
        Rectangle rectangle2 = value5.Frame(1, armFrame_Count, 0, armFrameToUseLeft);
        Rectangle rectangle3 = value6.Frame(1, armFrame_Count, 0, armFrameToUseRight);
        Vector2 origin = rectangle2.Size() / 2f;
        Vector2 origin2 = rectangle3.Size() / 2f;
        int num9 = 0;
        int num10 = 0;
        if (armFrameToUseLeft == 5)
        {
            num9 = 1;
        }
        if (armFrameToUseRight == 5)
        {
            num10 = 1;
        }
        float num11 = 1f;
        int num12 = 0;
        int num13 = 0;
        float num14 = 0f;
        float num15 = 0f;
        float num16 = 0f;
        if (num == 8 || num == 9)
        {
            num14 = Utils.GetLerpValue(0f, 30f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(90f, 30f, rCurrentNPC.ai[1], clamped: true);
            num15 = Utils.GetLerpValue(0f, 30f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(90f, 70f, rCurrentNPC.ai[1], clamped: true);
            num16 = Utils.GetLerpValue(0f, 15f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(45f, 30f, rCurrentNPC.ai[1], clamped: true);
            color = Color.Lerp(color, Color.White, num14);
            num11 *= 1f - num16;
            num12 = 4;
            num13 = 3;
        }
        if (num == 10)
        {
            num14 = Utils.GetLerpValue(30f, 90f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(165f, 90f, rCurrentNPC.ai[1], clamped: true);
            num15 = Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(180f, 120f, rCurrentNPC.ai[1], clamped: true);
            num16 = Utils.GetLerpValue(0f, 60f, rCurrentNPC.ai[1], clamped: true) * Utils.GetLerpValue(180f, 120f, rCurrentNPC.ai[1], clamped: true);
            color = Color.Lerp(color, Color.White, num14);
            num11 *= 1f - num16;
            num13 = 4;
        }
        if (num13 + num12 > 0)
        {
            for (int i = -num13; i <= num13 + num12; i++)
            {
                if (i == 0)
                {
                    continue;
                }
                Color color2 = Color.White;
                Vector2 position = vector;
                if (num == 8 || num == 9)
                {
                    float hue = ((float)i + 5f) / 10f;
                    float num2 = 200f;
                    float num3 = (float)timeForVisualEffects / 60f;
                    Matrix val = Matrix.CreateRotationX((num3 - 0.3f + (float)i * 0.1f) * 0.7f * ((float)Math.PI * 2f)) * Matrix.CreateRotationY((num3 - 0.8f + (float)i * 0.3f) * 0.7f * ((float)Math.PI * 2f)) * Matrix.CreateRotationZ((num3 + (float)i * 0.5f) * 0.1f * ((float)Math.PI * 2f));
                    Vector3 vector2 = Vector3.Transform(Vector3.Forward, val);
                    num2 += Utils.GetLerpValue(-1f, 1f, vector2.Z, clamped: true) * 150f;
                    Vector2 spinningpoint = new Vector2(vector2.X, vector2.Y) * num2 * num14;
                    float lerpValue = Utils.GetLerpValue(90f, 0f, rCurrentNPC.ai[1], clamped: true);
                    color2 = hslToRgb(hue, 1f, MathHelper.Lerp(0.5f, 1f, lerpValue)) * 0.8f * num15;
                    ((Color)(ref color2)).A = (byte)(((Color)(ref color2)).A / 3);
                    position += spinningpoint.RotatedBy(rCurrentNPC.ai[1] / 180f * ((float)Math.PI * 2f));
                }
                if (num == 10)
                {
                    if (rCurrentNPC.ai[1] >= 90f)
                    {
                        float num4 = (float)timeForVisualEffects / 90f;
                        int num5 = i;
                        if (num5 < 0)
{
                            num5++;
                        }
                        Vector2 vector3 = (((float)num5 + 0.5f) * ((float)Math.PI / 4f) + (float)Math.PI * 2f * num4).ToRotationVector2();
                        position += vector3 * new Vector2(600f * num14, 150f * num14);
                    }
                    else
                    {
                        position += 200f * new Vector2((float)i, 0f) * num14;
                    }
                    color2 = Color.White * 0.8f * num15 * num11;
                    ((Color)(ref color2)).A = (byte)(((Color)(ref color2)).A / 3);
                }
                if (i > num13)
                {
                    float lerpValue2 = Utils.GetLerpValue(30f, 70f, rCurrentNPC.ai[1], clamped: true);
                    if (lerpValue2 == 0f)
                    {
                        continue;
                    }
                    position = vector + rCurrentNPC.velocity * -3f * ((float)i - 4f) * lerpValue2;
                    color2 *= 1f - num16;
                }
                mySpriteBatch.Draw(value4, position, (Rectangle?)rectangle, color2, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
                mySpriteBatch.Draw(value7, position, (Rectangle?)rectangle, color2, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
                if (flag)
                {
                    Texture2D value8 = TextureAssets.Extra[187].Value;
                    Rectangle value9 = value8.Frame(1, 8, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 8);
                    mySpriteBatch.Draw(value8, position, (Rectangle?)value9, color2, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                }
                mySpriteBatch.Draw(value, position, (Rectangle?)rCurrentNPC.frame, color2, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
                for (int j = 0; j < 2; j++)
                {
                    if (j == num9)
                    {
                        mySpriteBatch.Draw(value5, position, (Rectangle?)rectangle2, color2, rCurrentNPC.rotation, origin, rCurrentNPC.scale, npcSpriteEffect, 0f);
                    }
                    if (j == num10)
                    {
                        mySpriteBatch.Draw(value6, position, (Rectangle?)rectangle3, color2, rCurrentNPC.rotation, origin2, rCurrentNPC.scale, npcSpriteEffect, 0f);
                    }
                }
            }
        }
        color *= num11;
        mySpriteBatch.Draw(value4, vector, (Rectangle?)rectangle, color, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect, 0f);
        if (!rCurrentNPC.IsABestiaryIconDummy)
        {
            mySpriteBatch.End();
            mySpriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.Default, RasterizerState.CullNone, (Effect)null, Transform);
        }
        DrawData value10 = new DrawData(value7, vector, rectangle, color, rCurrentNPC.rotation, rectangle.Size() / 2f, rCurrentNPC.scale * 2f, npcSpriteEffect);
        GameShaders.Misc["HallowBoss"].Apply(value10);
        value10.Draw(mySpriteBatch);
        pixelShader.CurrentTechnique.Passes[0].Apply();
        if (!rCurrentNPC.IsABestiaryIconDummy)
        {
            mySpriteBatch.End();
            mySpriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        }
        float num6 = (float)Math.Sin(GlobalTimeWrappedHourly * ((float)Math.PI * 2f) * 0.5f) * 0.5f + 0.5f;
        Color color3 = hslToRgb((num6 * 0.08f + 0.6f) % 1f, 1f, 0.5f);
        ((Color)(ref color3)).A = 0;
        color3 *= 0.6f;
        if (NPC.ShouldEmpressBeEnraged())
        {
            color3 = OurFavoriteColor;
            ((Color)(ref color3)).A = 0;
            color3 *= 0.3f;
        }
        color3 *= num11 * rCurrentNPC.Opacity;
        if (flag)
        {
            Texture2D value11 = TextureAssets.Extra[187].Value;
            Rectangle value2 = value11.Frame(1, 8, 0, (int)(rCurrentNPC.localAI[0] / 4f) % 8);
            mySpriteBatch.Draw(value11, vector, (Rectangle?)value2, color, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
            for (float num7 = 0f; num7 < 1f; num7 += 0.25f)
            {
                Vector2 vector4 = rCurrentNPC.rotation.ToRotationVector2().RotatedBy(num7 * ((float)Math.PI * 2f) + (float)Math.PI / 4f) * MathHelper.Lerp(2f, 8f, num6);
                mySpriteBatch.Draw(value11, vector + vector4, (Rectangle?)value2, color3, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
            }
        }
        mySpriteBatch.Draw(value, vector, (Rectangle?)rCurrentNPC.frame, color, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
        if (flag)
        {
            Texture2D value3 = TextureAssets.Extra[188].Value;
            for (float num8 = 0f; num8 < 1f; num8 += 0.25f)
            {
                Vector2 vector5 = rCurrentNPC.rotation.ToRotationVector2().RotatedBy(num8 * ((float)Math.PI * 2f) + (float)Math.PI / 4f) * MathHelper.Lerp(2f, 8f, num6);
                mySpriteBatch.Draw(value3, vector + vector5, (Rectangle?)null, color3, rCurrentNPC.rotation, halfSize, rCurrentNPC.scale, npcSpriteEffect, 0f);
            }
        }
        for (int k = 0; k < 2; k++)
        {
            if (k == num9)
            {
                mySpriteBatch.Draw(value5, vector, (Rectangle?)rectangle2, color, rCurrentNPC.rotation, origin, rCurrentNPC.scale, npcSpriteEffect, 0f);
            }
            if (k == num10)
            {
                mySpriteBatch.Draw(value6, vector, (Rectangle?)rectangle3, color, rCurrentNPC.rotation, origin2, rCurrentNPC.scale, npcSpriteEffect, 0f);
            }
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DefaultSamplerState, Terraria.Main.DrawNPCDirect_GetHallowBossArmFrame(), Terraria.GameContent.TextureAssets.Extra, Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.hslToRgb(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.GameContent.TextureAssets.Npc, Terraria.Main.OurFavoriteColor, Terraria.Main.pixelShader, Terraria.Main.Rasterizer, Terraria.NPC.ShouldEmpressBeEnraged(), Terraria.Main.timeForVisualEffects, and Terraria.Main.Transform.
Referenced by Terraria.Main.DrawNPCDirect_Inner().