TModLoader: Terraria.Main.UpdateUIStates
UpdateUIStates()
static void Terraria.Main.UpdateUIStates (GameTime gameTime) inline static private
    {
        if (MenuUI != null)
        {
            MenuUI.Update(gameTime);
        }
        if (InGameUI != null)
        {
            InGameUI.Update(gameTime);
        }
        CreativeMenu.Update(gameTime);
        SystemLoader.UpdateUI(gameTime);
        PlayerInput.ScrollWheelDeltaForUI = 0;
        BossBarLoader.HandleStyle();
        if (!gameMenu)
        {
            BigBossProgressBar.Update();
        }
    }
References Terraria.Main.BigBossProgressBar, Terraria.Main.CreativeMenu, Terraria.Main.gameMenu, Terraria.ModLoader.BossBarLoader.HandleStyle(), Terraria.Main.InGameUI, Terraria.Main.MenuUI, Terraria.GameContent.UI.BigProgressBar.BigProgressBarSystem.Update(), Terraria.GameContent.Creative.CreativeUI.Update(), Terraria.UI.UserInterface.Update(), and Terraria.ModLoader.SystemLoader.UpdateUI().
Referenced by Terraria.Main.DoUpdate().