TModLoader: Terraria.Main.oldDrawWater
oldDrawWater()
void Terraria.Main.oldDrawWater (bool bg = false, int Style = 0, float Alpha = 1f) inline
    {
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_039c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0686: Unknown result type (might be due to invalid IL or missing references)
        //IL_068d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0836: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0806: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f65: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0916: Unknown result type (might be due to invalid IL or missing references)
        //IL_0920: Unknown result type (might be due to invalid IL or missing references)
        //IL_0925: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fbb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ffd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1002: Unknown result type (might be due to invalid IL or missing references)
        //IL_1004: Unknown result type (might be due to invalid IL or missing references)
        //IL_1009: Unknown result type (might be due to invalid IL or missing references)
        //IL_1018: Unknown result type (might be due to invalid IL or missing references)
        //IL_1024: Unknown result type (might be due to invalid IL or missing references)
        //IL_102a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ecc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1060: Unknown result type (might be due to invalid IL or missing references)
        //IL_1065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f48: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_10fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1104: Unknown result type (might be due to invalid IL or missing references)
        //IL_1106: Unknown result type (might be due to invalid IL or missing references)
        //IL_1110: Unknown result type (might be due to invalid IL or missing references)
        //IL_111a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1123: Unknown result type (might be due to invalid IL or missing references)
        //IL_1129: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a11: Unknown result type (might be due to invalid IL or missing references)
        //IL_1151: Unknown result type (might be due to invalid IL or missing references)
        //IL_1153: Unknown result type (might be due to invalid IL or missing references)
        //IL_1158: Unknown result type (might be due to invalid IL or missing references)
        //IL_115d: Unknown result type (might be due to invalid IL or missing references)
        //IL_115f: Unknown result type (might be due to invalid IL or missing references)
        //IL_116a: Unknown result type (might be due to invalid IL or missing references)
        //IL_117c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1188: Unknown result type (might be due to invalid IL or missing references)
        //IL_118e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a9d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c48: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c72: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1223: Unknown result type (might be due to invalid IL or missing references)
        //IL_1225: Unknown result type (might be due to invalid IL or missing references)
        //IL_122a: Unknown result type (might be due to invalid IL or missing references)
        //IL_122f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1231: Unknown result type (might be due to invalid IL or missing references)
        //IL_123d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1247: Unknown result type (might be due to invalid IL or missing references)
        //IL_124b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1257: Unknown result type (might be due to invalid IL or missing references)
        //IL_125d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dbf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ddc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0def: Unknown result type (might be due to invalid IL or missing references)
        //IL_0df5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d85: Unknown result type (might be due to invalid IL or missing references)
        //IL_1285: Unknown result type (might be due to invalid IL or missing references)
        //IL_1287: Unknown result type (might be due to invalid IL or missing references)
        //IL_128c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1291: Unknown result type (might be due to invalid IL or missing references)
        //IL_1293: Unknown result type (might be due to invalid IL or missing references)
        //IL_129f: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_12b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e32: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e37: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e82: Unknown result type (might be due to invalid IL or missing references)
        float num = 0f;
        float num12 = 99999f;
        float num23 = 99999f;
        int num27 = -1;
        int num28 = -1;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)offScreenRange, (float)offScreenRange);
        if (drawToScreen)
        {
            vector = Vector2.Zero;
        }
        _ = new Color[4];
        int num29 = (int)(255f * (1f - gfxQuality) + 40f * gfxQuality);
        _ = gfxQuality;
        _ = gfxQuality;
        int num30 = (int)((screenPosition.X - vector.X) / 16f - 1f);
        int num31 = (int)((screenPosition.X + (float)screenWidth + vector.X) / 16f) + 2;
        int num32 = (int)((screenPosition.Y - vector.Y) / 16f - 1f);
        int num2 = (int)((screenPosition.Y + (float)screenHeight + vector.Y) / 16f) + 5;
        if (num30 < 5)
        {
            num30 = 5;
        }
        if (num31 > maxTilesX - 5)
        {
            num31 = maxTilesX - 5;
        }
        if (num32 < 5)
        {
            num32 = 5;
        }
        if (num2 > maxTilesY - 5)
        {
            num2 = maxTilesY - 5;
        }
        Vector2 vector2 = default(Vector2);
        Rectangle value = default(Rectangle);
        Color newColor = default(Color);
        for (int i = num32; i < num2 + 4; i++)
        {
            for (int j = num30 - 2; j < num31 + 2; j++)
            {
                if (tile[j, i] == null)
                {
                    tile[j, i] = default(Tile);
                }
                if (tile[j, i].liquid <= 0 || (tile[j, i].nactive() && tileSolid[tile[j, i].type] && !tileSolidTop[tile[j, i].type]) || !(Lighting.Brightness(j, i) > 0f || bg))
                {
                    continue;
                }
                Color color = Lighting.GetColor(j, i);
                float num3 = 256 - tile[j, i].liquid;
                num3 /= 32f;
                bool flag = false;
                int num4 = 0;
                if (tile[j, i].lava())
                {
                    if (drewLava)
                    {
                        continue;
                    }
                    float num5 = Math.Abs((float)(j * 16 + 8) - (screenPosition.X + (float)(screenWidth / 2)));
                    float num6 = Math.Abs((float)(i * 16 + 8) - (screenPosition.Y + (float)(screenHeight / 2)));
                    if (num5 < (float)(screenWidth * 2) && num6 < (float)(screenHeight * 2))
                    {
                        float num7 = (float)Math.Sqrt(num5 * num5 + num6 * num6);
                        float num8 = 1f - num7 / ((float)screenWidth * 0.75f);
                        if (num8 > 0f)
{
                            num += num8;
                        }
                    }
                    if (num5 < num12)
                    {
                        num12 = num5;
                        num27 = j * 16 + 8;
                    }
                    if (num6 < num23)
                    {
                        num23 = num5;
                        num28 = i * 16 + 8;
                    }
                    num4 = 1;
                }
                else if (tile[j, i].honey())
                {
                    num4 = 11;
                }
                else if (tile[j, i].shimmer())
                {
                    num4 = 14;
                    flag = true;
                }
                if (num4 == 0)
                {
                    num4 = Style;
                }
                if ((num4 == 1 || num4 == 11) && drewLava)
                {
                    continue;
                }
                float num9 = 0.5f;
                if (bg)
                {
                    num9 = 1f;
                }
                if (num4 != 1 && num4 != 11)
                {
                    num9 *= Alpha;
                }
                DrawTileInWater(-screenPosition + vector, j, i);
                ((Vector2)(ref vector2))._002Ector((float)(j * 16), (float)(i * 16 + (int)num3 * 2));
                ((Rectangle)(ref value))._002Ector(0, 0, 16, 16 - (int)num3 * 2);
                bool flag2 = true;
                if (tile[j, i + 1].liquid < 245 && (!tile[j, i + 1].nactive() || !tileSolid[tile[j, i + 1].type] || tileSolidTop[tile[j, i + 1].type]))
                {
                    float num10 = 256 - tile[j, i + 1].liquid;
                    num10 /= 32f;
                    num9 = 0.5f * (8f - num3) / 4f;
                    if ((double)num9 > 0.55)
                    {
                        num9 = 0.55f;
                    }
                    if ((double)num9 < 0.35)
                    {
                        num9 = 0.35f;
                    }
                    float num11 = num3 / 2f;
                    if (tile[j, i + 1].liquid < 200)
                    {
                        if (bg)
{
                            continue;
                        }
                        if (tile[j, i - 1].liquid > 0 && tile[j, i - 1].liquid > 0)
{
                            ((Rectangle)(ref value))._002Ector(0, 4, 16, 16);
                            num9 = 0.5f;
                        }
                        else if (tile[j, i - 1].liquid > 0)
{
                            ((Vector2)(ref vector2))._002Ector((float)(j * 16), (float)(i * 16 + 4));
                            ((Rectangle)(ref value))._002Ector(0, 4, 16, 12);
                            num9 = 0.5f;
                        }
                        else if (tile[j, i + 1].liquid > 0)
{
                            ((Vector2)(ref vector2))._002Ector((float)(j * 16), (float)(i * 16 + (int)num3 * 2 + (int)num10 * 2));
                            ((Rectangle)(ref value))._002Ector(0, 4, 16, 16 - (int)num3 * 2);
                        }
                        else
{
                            ((Vector2)(ref vector2))._002Ector((float)(j * 16 + (int)num11), (float)(i * 16 + (int)num11 * 2 + (int)num10 * 2));
                            ((Rectangle)(ref value))._002Ector(0, 4, 16 - (int)num11 * 2, 16 - (int)num11 * 2);
                        }
                    }
                    else
                    {
                        num9 = 0.5f;
                        ((Rectangle)(ref value))._002Ector(0, 4, 16, 16 - (int)num3 * 2 + (int)num10 * 2);
                    }
                }
                else if (tile[j, i - 1].liquid > 32)
                {
                    ((Rectangle)(ref value))._002Ector(0, 4, value.Width, value.Height);
                }
                else if (num3 < 1f && tile[j, i - 1].nactive() && tileSolid[tile[j, i - 1].type] && !tileSolidTop[tile[j, i - 1].type])
                {
                    ((Vector2)(ref vector2))._002Ector((float)(j * 16), (float)(i * 16));
                    ((Rectangle)(ref value))._002Ector(0, 4, 16, 16);
                }
                else
                {
                    for (int k = i + 1; k < i + 6 && (!tile[j, k].nactive() || !tileSolid[tile[j, k].type] || tileSolidTop[tile[j, k].type]); k++)
                    {
                        if (tile[j, k].liquid < 200)
{
                            flag2 = false;
                            break;
                        }
                    }
                    if (!flag2)
                    {
                        num9 = 0.5f;
                        ((Rectangle)(ref value))._002Ector(0, 4, 16, 16);
                    }
                    else if (tile[j, i - 1].liquid > 0)
                    {
                        ((Rectangle)(ref value))._002Ector(0, 2, value.Width, value.Height);
                    }
                }
                if ((((Color)(ref color)).R > 20 || ((Color)(ref color)).B > 20 || ((Color)(ref color)).G > 20) && value.Y < 4)
                {
                    int num13 = ((Color)(ref color)).R;
                    if (((Color)(ref color)).G > num13)
                    {
                        num13 = ((Color)(ref color)).G;
                    }
                    if (((Color)(ref color)).B > num13)
                    {
                        num13 = ((Color)(ref color)).B;
                    }
                    num13 /= 30;
                    if (rand.Next(20000) < num13)
                    {
                        ((Color)(ref newColor))._002Ector(255, 255, 255);
                        if (tile[j, i].honey())
{
                            ((Color)(ref newColor))._002Ector(255, 255, 50);
                        }
                        int num14 = Dust.NewDust(new Vector2((float)(j * 16), vector2.Y - 2f), 16, 8, 43, 0f, 0f, 254, newColor, 0.75f);
                        Dust obj = dust[num14];
                        obj.velocity *= 0f;
                    }
                }
                if (tile[j, i].honey())
                {
                    num9 *= 1.6f;
                    if (num9 > 1f)
                    {
                        num9 = 1f;
                    }
                }
                if (tile[j, i].lava())
                {
                    num9 *= 1.8f;
                    if (num9 > 1f)
                    {
                        num9 = 1f;
                    }
                    if (((Game)this).IsActive && !gamePaused && Dust.lavaBubbles < 200)
                    {
                        if (tile[j, i].liquid > 200 && rand.Next(700) == 0)
{
                            Dust.NewDust(new Vector2((float)(j * 16), (float)(i * 16)), 16, 16, 35);
                        }
                        if (value.Y == 0 && rand.Next(350) == 0)
{
                            int num15 = Dust.NewDust(new Vector2((float)(j * 16), (float)(i * 16) + num3 * 2f - 8f), 16, 8, 35, 0f, 0f, 50, default(Color), 1.5f);
                            Dust obj2 = dust[num15];
                            obj2.velocity *= 0.8f;
                            dust[num15].velocity.X *= 2f;
                            dust[num15].velocity.Y -= (float)rand.Next(1, 7) * 0.1f;
                            if (rand.Next(10) == 0)
{
                                dust[num15].velocity.Y *= rand.Next(2, 5);
                            }
                            dust[num15].noGravity = true;
                        }
                    }
                }
                float num16 = (float)(int)((Color)(ref color)).R * num9;
                float num17 = (float)(int)((Color)(ref color)).G * num9;
                float num18 = (float)(int)((Color)(ref color)).B * num9;
                float num19 = (float)(int)((Color)(ref color)).A * num9;
                ((Color)(ref color))._002Ector((int)(byte)num16, (int)(byte)num17, (int)(byte)num18, (int)(byte)num19);
                if (flag)
                {
                    ((Color)(ref color))._002Ector(((Color)(ref color)).ToVector4() * LiquidRenderer.GetShimmerBaseColor(j, i));
                }
                if (Lighting.NotRetro && !bg)
                {
                    Color color2 = color;
                    if (num4 != 1 && ((double)(int)((Color)(ref color2)).R > (double)num29 * 0.6 || (double)(int)((Color)(ref color2)).G > (double)num29 * 0.65 || (double)(int)((Color)(ref color2)).B > (double)num29 * 0.7))
                    {
                        for (int l = 0; l < 4; l++)
{
                            int num20 = 0;
                            int num21 = 0;
                            int width = 8;
                            int height = 8;
                            Color color3 = color2;
                            Color color4 = Lighting.GetColor(j, i);
                            if (l == 0)
{
                                color4 = Lighting.GetColor(j - 1, i - 1);
                                if (value.Height < 8)
{
                                    height = value.Height;
                                }
                            }
                            if (l == 1)
{
                                color4 = Lighting.GetColor(j + 1, i - 1);
                                num20 = 8;
                                if (value.Height < 8)
{
                                    height = value.Height;
                                }
                            }
                            if (l == 2)
{
                                color4 = Lighting.GetColor(j - 1, i + 1);
                                num21 = 8;
                                height = 8 - (16 - value.Height);
                            }
                            if (l == 3)
{
                                color4 = Lighting.GetColor(j + 1, i + 1);
                                num20 = 8;
                                num21 = 8;
                                height = 8 - (16 - value.Height);
                            }
                            num16 = (float)(int)((Color)(ref color4)).R * num9;
                            num17 = (float)(int)((Color)(ref color4)).G * num9;
                            num18 = (float)(int)((Color)(ref color4)).B * num9;
                            num19 = (float)(int)((Color)(ref color4)).A * num9;
                            ((Color)(ref color4))._002Ector((int)(byte)num16, (int)(byte)num17, (int)(byte)num18, (int)(byte)num19);
                            ((Color)(ref color3)).R = (byte)((((Color)(ref color2)).R * 3 + ((Color)(ref color4)).R * 2) / 5);
                            ((Color)(ref color3)).G = (byte)((((Color)(ref color2)).G * 3 + ((Color)(ref color4)).G * 2) / 5);
                            ((Color)(ref color3)).B = (byte)((((Color)(ref color2)).B * 3 + ((Color)(ref color4)).B * 2) / 5);
                            ((Color)(ref color3)).A = (byte)((((Color)(ref color2)).A * 3 + ((Color)(ref color4)).A * 2) / 5);
                            if (flag)
{
                                ((Color)(ref color3))._002Ector(((Color)(ref color3)).ToVector4() * LiquidRenderer.GetShimmerBaseColor(j, i));
                            }
                            spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + new Vector2((float)num20, (float)num21) + vector, (Rectangle?)new Rectangle(value.X + num20, value.Y + num21, width, height), color3, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                            if (flag)
{
                                spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + new Vector2((float)num20, (float)num21) + vector, (Rectangle?)new Rectangle(value.X + num20, value.Y + num21 + 36, width, height), LiquidRenderer.GetShimmerGlitterColor(flag2, j, i), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                            }
                        }
                    }
                    else
                    {
                        spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + vector, (Rectangle?)value, color, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                        if (flag)
{
                            value.Y += 36;
                            spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + vector, (Rectangle?)value, LiquidRenderer.GetShimmerGlitterColor(flag2, j, i), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                        }
                    }
                }
                else
                {
                    if (value.Y < 4)
                    {
                        value.X += (int)(wFrame * 18f);
                    }
                    spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + vector, (Rectangle?)value, color, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                    if (flag)
                    {
                        value.Y += 36;
                        spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + vector, (Rectangle?)value, LiquidRenderer.GetShimmerGlitterColor(flag2, j, i), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                    }
                }
                if (!tile[j, i + 1].halfBrick())
                {
                    continue;
                }
                color = Lighting.GetColor(j, i + 1);
                num16 = (float)(int)((Color)(ref color)).R * num9;
                num17 = (float)(int)((Color)(ref color)).G * num9;
                num18 = (float)(int)((Color)(ref color)).B * num9;
                num19 = (float)(int)((Color)(ref color)).A * num9;
                ((Color)(ref color))._002Ector((int)(byte)num16, (int)(byte)num17, (int)(byte)num18, (int)(byte)num19);
                if (flag)
                {
                    ((Color)(ref color))._002Ector(((Color)(ref color)).ToVector4() * LiquidRenderer.GetShimmerBaseColor(j, i));
                }
                ((Vector2)(ref vector2))._002Ector((float)(j * 16), (float)(i * 16 + 16));
                spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + vector, (Rectangle?)new Rectangle(0, 4, 16, 8), color, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                if (flag)
                {
                    spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + vector, (Rectangle?)new Rectangle(0, 40, 16, 8), LiquidRenderer.GetShimmerGlitterColor(flag2, j, i), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                }
                float num22 = 6f;
                float num24 = 0.75f;
                if (num4 == 1 || num4 == 11)
                {
                    num22 = 4f;
                    num24 = 0.5f;
                }
                for (int m = 0; (float)m < num22; m++)
                {
                    int num25 = i + 2 + m;
                    if (WorldGen.SolidTile(j, num25))
                    {
                        break;
                    }
                    float num26 = 1f - (float)m / num22;
                    num26 *= num24;
                    ((Vector2)(ref vector2))._002Ector((float)(j * 16), (float)(num25 * 16 - 2));
                    spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + vector, (Rectangle?)new Rectangle(0, 18, 16, 16), color * num26, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                    if (flag)
                    {
                        spriteBatch.Draw(TextureAssets.Liquid[num4].Value, vector2 - screenPosition + vector, (Rectangle?)new Rectangle(0, 54, 16, 16), LiquidRenderer.GetShimmerGlitterColor(flag2, j, i) * num26, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                    }
                }
            }
        }
        if (!drewLava)
        {
            ambientLavaX = num27;
            ambientLavaY = num28;
            ambientLavaStrength = num;
        }
        drewLava = true;
    }
References Terraria.Main.ambientLavaStrength, Terraria.Main.ambientLavaX, Terraria.Main.ambientLavaY, Terraria.Lighting.Brightness(), Terraria.Graphics.Light.Color, Terraria.Main.DrawTileInWater(), Terraria.Main.drawToScreen, Terraria.Main.drewLava, Terraria.Main.dust, Terraria.Main.gamePaused, Terraria.Lighting.GetColor(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerBaseColor(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterColor(), Terraria.Main.gfxQuality, Terraria.Dust.lavaBubbles, Terraria.GameContent.TextureAssets.Liquid, Terraria.Main.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Dust.NewDust(), Terraria.Lighting.NotRetro, Terraria.Main.offScreenRange, Terraria.Main.rand, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.WorldGen.SolidTile(), Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Main.wFrame.
Referenced by Terraria.Main.DrawLiquid().