TModLoader: Terraria.Main.DrawClothesWindow
DrawClothesWindow()
void Terraria.Main.DrawClothesWindow () inline protected
Definition at line 57151 of file Main.cs.
    {
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018f: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0314: Unknown result type (might be due to invalid IL or missing references)
        //IL_0324: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_040b: Unknown result type (might be due to invalid IL or missing references)
        //IL_041b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_042e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0433: Unknown result type (might be due to invalid IL or missing references)
        //IL_035e: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_046f: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05de: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0603: Unknown result type (might be due to invalid IL or missing references)
        //IL_0608: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0624: Unknown result type (might be due to invalid IL or missing references)
        //IL_0640: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0552: Unknown result type (might be due to invalid IL or missing references)
        //IL_0554: Unknown result type (might be due to invalid IL or missing references)
        //IL_055b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0560: Unknown result type (might be due to invalid IL or missing references)
        //IL_0576: Unknown result type (might be due to invalid IL or missing references)
        //IL_0581: Unknown result type (might be due to invalid IL or missing references)
        //IL_0589: Unknown result type (might be due to invalid IL or missing references)
        //IL_058e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0595: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_053d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_053f: Unknown result type (might be due to invalid IL or missing references)
        //IL_083c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0841: Unknown result type (might be due to invalid IL or missing references)
        //IL_070d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0712: Unknown result type (might be due to invalid IL or missing references)
        //IL_0714: Unknown result type (might be due to invalid IL or missing references)
        //IL_071b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_0736: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_0749: Unknown result type (might be due to invalid IL or missing references)
        //IL_074e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0755: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_090b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0910: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ace: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c80: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cf8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cfd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e49: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e6c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e71: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eaa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0edf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f19: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1e: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1306: Unknown result type (might be due to invalid IL or missing references)
        //IL_130b: Unknown result type (might be due to invalid IL or missing references)
        //IL_133a: Unknown result type (might be due to invalid IL or missing references)
        //IL_133f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1354: Unknown result type (might be due to invalid IL or missing references)
        //IL_1359: Unknown result type (might be due to invalid IL or missing references)
        //IL_136e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1373: Unknown result type (might be due to invalid IL or missing references)
        //IL_1388: Unknown result type (might be due to invalid IL or missing references)
        //IL_138d: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_13f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1401: Unknown result type (might be due to invalid IL or missing references)
        //IL_1406: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe3: Unknown result type (might be due to invalid IL or missing references)
        //IL_1001: Unknown result type (might be due to invalid IL or missing references)
        //IL_100d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f9f: Unknown result type (might be due to invalid IL or missing references)
        //IL_146d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1472: Unknown result type (might be due to invalid IL or missing references)
        //IL_1481: Unknown result type (might be due to invalid IL or missing references)
        //IL_1483: Unknown result type (might be due to invalid IL or missing references)
        //IL_149f: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1412: Unknown result type (might be due to invalid IL or missing references)
        //IL_141c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1426: Unknown result type (might be due to invalid IL or missing references)
        //IL_142b: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1107: Unknown result type (might be due to invalid IL or missing references)
        //IL_110c: Unknown result type (might be due to invalid IL or missing references)
        //IL_111e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1123: Unknown result type (might be due to invalid IL or missing references)
        //IL_1135: Unknown result type (might be due to invalid IL or missing references)
        //IL_113a: Unknown result type (might be due to invalid IL or missing references)
        //IL_114c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1151: Unknown result type (might be due to invalid IL or missing references)
        //IL_1163: Unknown result type (might be due to invalid IL or missing references)
        //IL_1168: Unknown result type (might be due to invalid IL or missing references)
        //IL_1197: Unknown result type (might be due to invalid IL or missing references)
        //IL_11b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_11cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_117a: Unknown result type (might be due to invalid IL or missing references)
        //IL_117f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1250: Unknown result type (might be due to invalid IL or missing references)
        //IL_1262: Unknown result type (might be due to invalid IL or missing references)
        //IL_126c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1271: Unknown result type (might be due to invalid IL or missing references)
        //IL_1209: Unknown result type (might be due to invalid IL or missing references)
        //IL_1216: Unknown result type (might be due to invalid IL or missing references)
        //IL_1220: Unknown result type (might be due to invalid IL or missing references)
        //IL_122c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1232: Unknown result type (might be due to invalid IL or missing references)
        if (npcChatText != "" || playerInventory || player[myPlayer].chest != -1 || npcShop != 0 || player[myPlayer].talkNPC != -1 || InGuideCraftMenu)
        {
            CancelClothesWindow();
            return;
        }
        if (!LocalPlayer.IsInInteractionRangeToMultiTileHitbox(interactedDresserTopLeftX, interactedDresserTopLeftY) || !tile[interactedDresserTopLeftX, interactedDresserTopLeftY].active())
        {
            CancelClothesWindow();
            return;
        }
        int num = 477;
        int num12 = num / 2;
        num12 = 180;
        num = 511;
        num -= num / 2 - num12 - 26;
        int num17 = screenHeight / 2 + 60;
        int num18 = screenWidth / 2 - num / 2;
        int num19 = num17 + 32;
        int num20 = num18 + 22;
        num19 -= 16;
        int num21 = num18 + num - num12;
        int num22 = num17 + 18;
        if (selClothes == 0)
        {
            selColor = player[myPlayer].shirtColor;
        }
        if (selClothes == 1)
        {
            selColor = player[myPlayer].underShirtColor;
        }
        if (selClothes == 2)
        {
            selColor = player[myPlayer].pantsColor;
        }
        if (selClothes == 3)
        {
            selColor = player[myPlayer].shoeColor;
        }
        if (selClothes == 4)
        {
            selColor = player[myPlayer].eyeColor;
        }
        if (selClothes == 5)
        {
            selColor = player[myPlayer].skinColor;
        }
        Utils.DrawInvBG(spriteBatch, new Rectangle(num18, num17, num, 133));
        if (!PlayerInput.IgnoreMouseInterface && mouseX > num18 && mouseX < num18 + TextureAssets.ClothesStyleBack.Width() && mouseY > num17 && mouseY < num17 + TextureAssets.ClothesStyleBack.Height())
        {
            player[myPlayer].mouseInterface = true;
        }
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(num18 + num / 2 - 16 - 28), (float)(num17 + 66 + dresserInterfaceDummy.height / 2 - 20));
        vector.Y += 18f;
        vector.X += 58f;
        Rectangle r = default(Rectangle);
        ((Rectangle)(ref r))._002Ector((int)vector.X - dresserInterfaceDummy.width / 2 - 15, (int)vector.Y - dresserInterfaceDummy.height - 33, dresserInterfaceDummy.width + 30, dresserInterfaceDummy.height + 66);
        bool flag = ((Rectangle)(ref r)).Contains(MouseScreen.ToPoint());
        int num23 = selClothes;
        int num2 = (mouseTextColor * 2 + 255) / 3;
        Color color = default(Color);
        ((Color)(ref color))._002Ector(num2, (int)((double)num2 / 1.1), num2 / 2, num2);
        float num3 = 0.9f;
        string textValue = Language.GetTextValue("GameUI.Change");
        int num4 = num18 + num - num12 + 22;
        num4 = num18 + 22;
        int num5 = num17 + 94;
        bool flag2 = false;
        if (oldClothesColor[0] != player[myPlayer].shirtColor || oldClothesColor[1] != player[myPlayer].underShirtColor || oldClothesColor[2] != player[myPlayer].pantsColor || oldClothesColor[3] != player[myPlayer].shoeColor || oldClothesColor[4] != player[myPlayer].eyeColor || oldClothesColor[5] != player[myPlayer].skinColor || oldClothesStyle != player[myPlayer].skinVariant)
        {
            flag2 = true;
        }
        Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(textValue);
        bool flag3 = false;
        UILinkPointNavigator.SetPosition(2803, new Vector2((float)num4, (float)num5) + vector2 * num3 * 0.5f);
        if (flag2 && mouseX > num4 && (float)mouseX < (float)num4 + vector2.X && mouseY > num5 && (float)mouseY < (float)num5 + vector2.Y)
        {
            flag3 = true;
            num3 = 1.1f;
            if (!npcChatFocus1)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus1 = true;
            player[myPlayer].releaseUseItem = false;
        }
        else
        {
            if (npcChatFocus1)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus1 = false;
        }
        for (int i = 0; i < 5; i++)
        {
            int num6 = num4;
            int num7 = num5;
            Color color2 = Color.Black;
            if (flag3)
            {
                color2 = Color.Brown;
            }
            if (i == 0)
            {
                num6 -= 2;
            }
            if (i == 1)
            {
                num6 += 2;
            }
            if (i == 2)
            {
                num7 -= 2;
            }
            if (i == 3)
            {
                num7 += 2;
            }
            if (i == 4)
            {
                color2 = (Color)(flag2 ? color : new Color(100, 100, 100));
            }
            Vector2 origin = FontAssets.MouseText.Value.MeasureString(textValue);
            origin *= 0.5f;
            spriteBatch.DrawString(FontAssets.MouseText.Value, textValue, new Vector2((float)num6 + origin.X, (float)num7 + origin.Y), color2, 0f, origin, num3, (SpriteEffects)0, 0f);
        }
        num3 = 0.9f;
        string textValue2 = Language.GetTextValue("GameUI.Cancel");
        num4 += 130;
        bool flag4 = false;
        vector2 = FontAssets.MouseText.Value.MeasureString(textValue2);
        UILinkPointNavigator.SetPosition(2804, new Vector2((float)num4, (float)num5) + vector2 * num3 * 0.5f);
        if (mouseX > num4 && (float)mouseX < (float)num4 + vector2.X && mouseY > num5 && (float)mouseY < (float)num5 + vector2.Y)
        {
            flag4 = true;
            num3 = 1.1f;
            if (!npcChatFocus2)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus2 = true;
            player[myPlayer].releaseUseItem = false;
        }
        else
        {
            if (npcChatFocus2)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus2 = false;
        }
        for (int j = 0; j < 5; j++)
        {
            int num8 = num4;
            int num9 = num5;
            Color color3 = Color.Black;
            if (flag4)
            {
                color3 = Color.Brown;
            }
            if (j == 0)
            {
                num8 -= 2;
            }
            if (j == 1)
            {
                num8 += 2;
            }
            if (j == 2)
            {
                num9 -= 2;
            }
            if (j == 3)
            {
                num9 += 2;
            }
            if (j == 4)
            {
                color3 = color;
            }
            Vector2 origin2 = FontAssets.MouseText.Value.MeasureString(textValue2);
            origin2 *= 0.5f;
            spriteBatch.DrawString(FontAssets.MouseText.Value, textValue2, new Vector2((float)num8 + origin2.X, (float)num9 + origin2.Y), color3, 0f, origin2, num3, (SpriteEffects)0, 0f);
        }
        if (mouseLeft && mouseLeftRelease)
        {
            if (npcChatFocus1)
            {
                SaveClothesWindow();
                return;
            }
            if (npcChatFocus2)
            {
                CancelClothesWindow();
                return;
            }
        }
        if (!mouseLeft)
        {
            grabColorSlider = 0;
            blockMouse = false;
        }
        int num10 = 167;
        Vector3 val = rgbToHsl(selColor);
        float num11 = val.X;
        float num13 = val.Y;
        float z = val.Z;
        if (hBar == -1f || sBar == -1f || lBar == -1f)
        {
            hBar = num11;
            sBar = num13;
            lBar = z;
        }
        else
        {
            num11 = hBar;
            num13 = sBar;
            z = lBar;
        }
        spriteBatch.Draw(TextureAssets.Hue.Value, new Vector2((float)num20, (float)num19), Color.White);
        if ((mouseX > num20 - 4 && mouseX < num20 + TextureAssets.Hue.Width() + 4 && mouseY > num19 - 4 && mouseY < num19 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 1)
        {
            spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num20, (float)num19), OurFavoriteColor);
        }
        spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num20 + (float)(TextureAssets.Hue.Width() - 2) * hBar - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num19 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
        if (((mouseX > num20 - 4 && mouseX < num20 + TextureAssets.Hue.Width() + 4 && mouseY > num19 - 4 && mouseY < num19 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 1) && mouseLeft && !blockMouse)
        {
            grabColorSlider = 1;
            num11 = mouseX - num20;
            num11 /= (float)TextureAssets.Hue.Width();
            if (num11 < 0f)
            {
                num11 = 0f;
            }
            if (num11 > 1f)
            {
                num11 = 1f;
            }
            hBar = num11;
        }
        UILinkPointNavigator.SetPosition(2800, new Vector2((float)num20, (float)num19) + TextureAssets.Hue.Value.Size() / 2f);
        num19 += 26;
        spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2((float)num20, (float)num19), Color.White);
        for (int k = 0; k <= num10; k++)
        {
            float saturation = (float)k / (float)num10;
            Color color4 = hslToRgb(num11, saturation, z);
            spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2((float)(num20 + k + 5), (float)(num19 + 4)), color4);
        }
        if ((mouseX > num20 - 4 && mouseX < num20 + TextureAssets.Hue.Width() + 4 && mouseY > num19 - 4 && mouseY < num19 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 2)
        {
            spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num20, (float)num19), OurFavoriteColor);
        }
        spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num20 + (float)(TextureAssets.Hue.Width() - 2) * sBar - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num19 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
        if (((mouseX > num20 - 4 && mouseX < num20 + TextureAssets.Hue.Width() + 4 && mouseY > num19 - 4 && mouseY < num19 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 2) && mouseLeft && !blockMouse)
        {
            grabColorSlider = 2;
            num13 = mouseX - num20;
            num13 /= (float)TextureAssets.Hue.Width();
            if (num13 < 0f)
            {
                num13 = 0f;
            }
            if (num13 > 1f)
            {
                num13 = 1f;
            }
            sBar = num13;
        }
        UILinkPointNavigator.SetPosition(2801, new Vector2((float)num20, (float)num19) + TextureAssets.Hue.Value.Size() / 2f);
        num19 += 26;
        spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2((float)num20, (float)num19), Color.White);
        float num14 = 0.15f;
        for (int l = 0; l <= num10; l++)
        {
            float luminosity = (float)l / (float)num10;
            Color color5 = hslToRgb(num11, num13, luminosity);
            spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2((float)(num20 + l + 5), (float)(num19 + 4)), color5);
        }
        if ((mouseX > num20 - 4 && mouseX < num20 + TextureAssets.Hue.Width() + 4 && mouseY > num19 - 4 && mouseY < num19 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 3)
        {
            spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num20, (float)num19), OurFavoriteColor);
        }
        spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num20 + (float)(TextureAssets.Hue.Width() - 2) * ((lBar - num14) / (1f - num14)) - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num19 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
        if (((mouseX > num20 - 4 && mouseX < num20 + TextureAssets.Hue.Width() + 4 && mouseY > num19 - 4 && mouseY < num19 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 3) && mouseLeft && !blockMouse)
        {
            grabColorSlider = 3;
            z = mouseX - num20;
            z /= (float)TextureAssets.Hue.Width();
            if (z < 0f)
            {
                z = 0f;
            }
            if (z > 1f)
            {
                z = 1f;
            }
            z = z * (1f - num14) + num14;
            lBar = z;
        }
        UILinkPointNavigator.SetPosition(2802, new Vector2((float)num20, (float)num19) + TextureAssets.Hue.Value.Size() / 2f);
        selColor = hslToRgb(hBar, sBar, lBar);
        if (selClothes == 0)
        {
            player[myPlayer].shirtColor = selColor;
        }
        if (selClothes == 1)
        {
            player[myPlayer].underShirtColor = selColor;
        }
        if (selClothes == 2)
        {
            player[myPlayer].pantsColor = selColor;
        }
        if (selClothes == 3)
        {
            player[myPlayer].shoeColor = selColor;
        }
        if (selClothes == 4)
        {
            player[myPlayer].eyeColor = selColor;
        }
        if (selClothes == 5)
        {
            player[myPlayer].skinColor = selColor;
        }
        int num15 = num21;
        int num16 = num22;
        num16 -= 8;
        for (int m = 0; m < 6; m++)
        {
            if (num23 == m)
            {
                spriteBatch.Draw(TextureAssets.InventoryBack14.Value, new Vector2((float)num15, (float)num16), (Rectangle?)new Rectangle(0, 0, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            else
            {
                spriteBatch.Draw(TextureAssets.InventoryBack8.Value, new Vector2((float)num15, (float)num16), (Rectangle?)new Rectangle(0, 0, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (mouseX > num15 && mouseX < num15 + TextureAssets.InventoryBack.Width() && mouseY > num16 && mouseY < num16 + TextureAssets.InventoryBack.Height() && mouseLeft && mouseLeftRelease)
            {
                mouseLeftRelease = false;
                selClothes = m;
                SoundEngine.PlaySound(12);
                hBar = -1f;
                lBar = -1f;
                sBar = -1f;
            }
            float x = num15 + TextureAssets.InventoryBack.Width() / 2 - TextureAssets.Clothes[m].Width() / 2;
            float y = num16 + TextureAssets.InventoryBack.Height() / 2 - TextureAssets.Clothes[m].Height() / 2;
            Color color6 = Color.White;
            if (m == 0)
            {
                color6 = player[myPlayer].shirtColor;
            }
            if (m == 1)
            {
                color6 = player[myPlayer].underShirtColor;
            }
            if (m == 2)
            {
                color6 = player[myPlayer].pantsColor;
            }
            if (m == 3)
            {
                color6 = player[myPlayer].shoeColor;
            }
            if (m == 4)
            {
                color6 = player[myPlayer].eyeColor;
            }
            if (m == 5)
            {
                color6 = player[myPlayer].skinColor;
            }
            spriteBatch.Draw(TextureAssets.Clothes[m].Value, new Vector2(x, y), (Rectangle?)new Rectangle(0, 0, TextureAssets.Clothes[m].Width(), TextureAssets.Clothes[m].Height()), color6, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            if (m == 4)
            {
                Texture2D value = Assets.Request<Texture2D>("Images/UI/CharCreation/ColorEyeBack").Value;
                spriteBatch.Draw(value, new Vector2(x, y), (Rectangle?)value.Frame(), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            UILinkPointNavigator.SetPosition(2806 + m, new Vector2(x, y) + TextureAssets.Clothes[m].Value.Size() * 0.75f);
            num15 += 56;
            if (m == 1)
            {
                num15 -= 112;
                num16 += 56;
            }
            if (m == 3)
            {
                num16 -= 56;
            }
            if (m == 4)
            {
                num16 += 56;
                num15 -= 56;
            }
        }
        dresserInterfaceDummy.skinVariant = player[myPlayer].skinVariant;
        dresserInterfaceDummy.eyeColor = player[myPlayer].eyeColor;
        dresserInterfaceDummy.hairColor = player[myPlayer].hairColor;
        dresserInterfaceDummy.hair = player[myPlayer].hair;
        dresserInterfaceDummy.skinColor = player[myPlayer].skinColor;
        dresserInterfaceDummy.shirtColor = player[myPlayer].shirtColor;
        dresserInterfaceDummy.underShirtColor = player[myPlayer].underShirtColor;
        dresserInterfaceDummy.shoeColor = player[myPlayer].shoeColor;
        dresserInterfaceDummy.pantsColor = player[myPlayer].pantsColor;
        dresserInterfaceDummy.Bottom = screenPosition + vector;
        dresserInterfaceDummy.direction = -1;
        dresserInterfaceDummy.gravDir = 1f;
        dresserInterfaceDummy.PlayerFrame();
        dresserInterfaceDummy.socialIgnoreLight = true;
        Color c = new Color(46, 106, 98) * 0.6f;
        if (flag)
        {
            c = new Color(46, 106, 98) * 2f * 0.6f;
            if (mouseLeft && mouseLeftRelease)
            {
                mouseLeftRelease = false;
                SoundEngine.PlaySound(12);
                CycleClothingStyle(player[myPlayer]);
            }
        }
        UILinkPointNavigator.SetPosition(2805, ((Rectangle)(ref r)).Center.ToVector2());
        Utils.DrawInvBG(spriteBatch, r, c);
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)1, (BlendState)null, (SamplerState)null, (DepthStencilState)null, (RasterizerState)null, (Effect)null, UIScaleMatrix);
        PlayerRenderer.DrawPlayer(Camera, dresserInterfaceDummy, dresserInterfaceDummy.position, dresserInterfaceDummy.fullRotation, dresserInterfaceDummy.fullRotationOrigin);
    }
References Terraria.Main.Assets, Terraria.Main.blockMouse, Terraria.Main.CancelClothesWindow(), Terraria.Main.chest, Terraria.GameContent.TextureAssets.Clothes, Terraria.GameContent.TextureAssets.ClothesStyleBack, Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.ColorBar, Terraria.GameContent.TextureAssets.ColorBlip, Terraria.GameContent.TextureAssets.ColorHighlight, Terraria.GameContent.TextureAssets.ColorSlider, Terraria.Main.CycleClothingStyle(), Terraria.Utils.DrawInvBG(), Terraria.Graphics.Renderers.IPlayerRenderer.DrawPlayer(), Terraria.Main.dresserInterfaceDummy, Terraria.Player.eyeColor, Terraria.Player.fullRotation, Terraria.Player.fullRotationOrigin, Terraria.Localization.Language.GetTextValue(), Terraria.Main.grabColorSlider, Terraria.Player.hair, Terraria.Player.hairColor, Terraria.Main.hBar, Terraria.Entity.height, Terraria.Main.hslToRgb(), Terraria.GameContent.TextureAssets.Hue, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.InGuideCraftMenu, Terraria.Main.interactedDresserTopLeftX, Terraria.Main.interactedDresserTopLeftY, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.GameContent.TextureAssets.InventoryBack14, Terraria.GameContent.TextureAssets.InventoryBack8, Terraria.Player.IsInInteractionRangeToMultiTileHitbox(), Terraria.Main.lBar, Terraria.Main.LocalPlayer, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npcChatFocus1, Terraria.Main.npcChatFocus2, Terraria.Main.npcChatText, Terraria.Main.npcShop, Terraria.Main.oldClothesColor, Terraria.Main.oldClothesStyle, Terraria.Main.OurFavoriteColor, Terraria.Player.pantsColor, Terraria.Main.player, Terraria.Player.PlayerFrame(), Terraria.Main.playerInventory, Terraria.Main.PlayerRenderer, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Player.releaseUseItem, Terraria.Main.rgbToHsl(), Terraria.Main.SaveClothesWindow(), Terraria.Main.sBar, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.selClothes, Terraria.Main.selColor, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, Terraria.Player.skinVariant, Terraria.Main.spriteBatch, Terraria.Main.tile, Terraria.Main.UIScaleMatrix, Terraria.Player.underShirtColor, and Terraria.Entity.width.
Referenced by Terraria.Main.DrawInterface_22_DresserWindow().