TModLoader: Terraria.Main.DrawNPCDirect_Faeling
DrawNPCDirect_Faeling()
static void Terraria.Main.DrawNPCDirect_Faeling (SpriteBatch mySpriteBatch, NPC rCurrentNPC, ref Vector2 screenPos, int typeCache, ref Color npcColor, ref Vector2 halfSize, SpriteEffects npcSpriteEffect) inline static private
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0223: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_022d: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_025d: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_027a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_0318: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_032e: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_033a: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_0428: Unknown result type (might be due to invalid IL or missing references)
        //IL_0432: Unknown result type (might be due to invalid IL or missing references)
        //IL_0439: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0443: Unknown result type (might be due to invalid IL or missing references)
        //IL_044a: Unknown result type (might be due to invalid IL or missing references)
        //IL_044e: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Npc[typeCache].Value;
        Vector2 vector = rCurrentNPC.Center - screenPos;
        int num = 5;
        int horizontalFrames = 4;
        float num10 = ((float)rCurrentNPC.whoAmI * 0.11f + (float)timeForVisualEffects / 360f) % 1f;
        Color color = hslToRgb(num10, 1f, 0.65f);
        ((Color)(ref color)).A = (byte)(((Color)(ref color)).A / 2);
        float rotation = rCurrentNPC.rotation;
        Rectangle rectangle = value.Frame(horizontalFrames, num, 0, rCurrentNPC.frame.Y);
        Vector2 origin = rectangle.Size() / 2f;
        float scale = rCurrentNPC.scale;
        Rectangle value2 = value.Frame(horizontalFrames, num, 2);
        Color color2 = new Color(255, 255, 255, 0) * 1f;
        int num11 = rCurrentNPC.oldPos.Length;
        int num12 = num11 - 1 - 5;
        int num13 = 5;
        int num14 = 3;
        float num15 = 32f;
        float num16 = 16f;
        Vector2 center = new Vector2(num15, num16);
        float fromMax = ((Vector2)(ref center)).Length();
        float num17 = Utils.Remap(Vector2.Distance(rCurrentNPC.oldPos[num12], rCurrentNPC.position), 0f, fromMax, 0f, 100f);
        num17 = (int)num17 / 5;
        num17 *= 5f;
        num17 /= 100f;
        num16 *= num17;
        num15 *= num17;
        float num2 = 9f;
        float num3 = 0.5f;
        float num4 = (float)Math.PI;
        for (int num5 = num12; num5 >= num13; num5 -= num14)
        {
            Vector2 vector2 = rCurrentNPC.oldPos[num5] - rCurrentNPC.position;
            float num6 = Utils.Remap(num5, 0f, num11, 1f, 0f);
            float num7 = 1f - num6;
            Vector2 spinningpoint = new Vector2((float)Math.Sin((double)((float)rCurrentNPC.whoAmI / 17f) + timeForVisualEffects / (double)num2 + (double)(num6 * 2f * ((float)Math.PI * 2f))) * num16, 0f - num15) * num7;
            Vector2 val = vector2;
            double radians = num4;
            center = default(Vector2);
            vector2 = val + spinningpoint.RotatedBy(radians, center);
            Color color3 = hslToRgb((num10 + num7 * num3) % 1f, 1f, 0.5f);
            ((Color)(ref color3)).A = 0;
            mySpriteBatch.Draw(value, vector + vector2, (Rectangle?)value2, color3 * num6 * 0.16f, rotation, origin, scale * Utils.Remap(num6 * num6, 0f, 1f, 0f, 2.5f), npcSpriteEffect, 0f);
        }
        mySpriteBatch.Draw(value, vector, (Rectangle?)value2, color2, rotation, origin, scale, npcSpriteEffect, 0f);
        Rectangle value3 = value.Frame(horizontalFrames, num, 1, rCurrentNPC.frame.Y);
        Color white = Color.White;
        ((Color)(ref white)).A = (byte)(((Color)(ref white)).A / 2);
        mySpriteBatch.Draw(value, vector, (Rectangle?)value3, white, rotation, origin, scale, npcSpriteEffect, 0f);
        mySpriteBatch.Draw(value, vector, (Rectangle?)rectangle, color, rotation, origin, scale, npcSpriteEffect, 0f);
        float num8 = MathHelper.Clamp((float)Math.Sin(timeForVisualEffects / 60.0) * 0.3f + 0.3f, 0f, 1f);
        float num9 = 0.8f + (float)Math.Sin(timeForVisualEffects / 15.0 * 6.2831854820251465) * 0.3f;
        Rectangle value4 = value.Frame(horizontalFrames, num, 3, rCurrentNPC.whoAmI % num);
        Color color4 = Color.Lerp(color, new Color(255, 255, 255, 0), 0.5f) * num8;
        mySpriteBatch.Draw(value, vector, (Rectangle?)value4, color4, rotation, origin, scale * num9, (SpriteEffects)0, 0f);
        Rectangle value5 = value.Frame(horizontalFrames, num, 3, 1);
        Color color5 = Color.Lerp(color, new Color(255, 255, 255, 0), 0.5f) * num8;
        mySpriteBatch.Draw(value, vector, (Rectangle?)value5, color5, rotation, origin, scale * num9, (SpriteEffects)0, 0f);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.hslToRgb(), Terraria.GameContent.TextureAssets.Npc, Terraria.Utils.Remap(), and Terraria.Main.timeForVisualEffects.
Referenced by Terraria.Main.DrawNPCDirect_Inner().