TModLoader: Terraria.Main.DrawDust
DrawDust()
void Terraria.Main.DrawDust () inline protected
    {
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_0399: Unknown result type (might be due to invalid IL or missing references)
        //IL_039e: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_040d: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0420: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0436: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0902: Unknown result type (might be due to invalid IL or missing references)
        //IL_0907: Unknown result type (might be due to invalid IL or missing references)
        //IL_0934: Unknown result type (might be due to invalid IL or missing references)
        //IL_0939: Unknown result type (might be due to invalid IL or missing references)
        //IL_093d: Unknown result type (might be due to invalid IL or missing references)
        //IL_093f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0944: Unknown result type (might be due to invalid IL or missing references)
        //IL_0635: Unknown result type (might be due to invalid IL or missing references)
        //IL_063a: Unknown result type (might be due to invalid IL or missing references)
        //IL_063e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0643: Unknown result type (might be due to invalid IL or missing references)
        //IL_0648: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0652: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0708: Unknown result type (might be due to invalid IL or missing references)
        //IL_070a: Unknown result type (might be due to invalid IL or missing references)
        //IL_070f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_0722: Unknown result type (might be due to invalid IL or missing references)
        //IL_0727: Unknown result type (might be due to invalid IL or missing references)
        //IL_072e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0738: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0501: Unknown result type (might be due to invalid IL or missing references)
        //IL_0506: Unknown result type (might be due to invalid IL or missing references)
        //IL_0557: Unknown result type (might be due to invalid IL or missing references)
        //IL_055c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0560: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_0578: Unknown result type (might be due to invalid IL or missing references)
        //IL_057a: Unknown result type (might be due to invalid IL or missing references)
        //IL_057f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0586: Unknown result type (might be due to invalid IL or missing references)
        //IL_0590: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0803: Unknown result type (might be due to invalid IL or missing references)
        //IL_0808: Unknown result type (might be due to invalid IL or missing references)
        //IL_080d: Unknown result type (might be due to invalid IL or missing references)
        //IL_085e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0863: Unknown result type (might be due to invalid IL or missing references)
        //IL_0867: Unknown result type (might be due to invalid IL or missing references)
        //IL_0869: Unknown result type (might be due to invalid IL or missing references)
        //IL_086e: Unknown result type (might be due to invalid IL or missing references)
        //IL_087f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0881: Unknown result type (might be due to invalid IL or missing references)
        //IL_0886: Unknown result type (might be due to invalid IL or missing references)
        //IL_088d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0897: Unknown result type (might be due to invalid IL or missing references)
        //IL_08aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09be: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0985: Unknown result type (might be due to invalid IL or missing references)
        //IL_0987: Unknown result type (might be due to invalid IL or missing references)
        //IL_097c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a55: Unknown result type (might be due to invalid IL or missing references)
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector((int)screenPosition.X - 500, (int)screenPosition.Y - 50, screenWidth + 1000, screenHeight + 100);
        ((Rectangle)(ref rectangle))._002Ector((int)screenPosition.X - 1000, (int)screenPosition.Y - 1050, screenWidth + 2000, screenHeight + 2100);
        Rectangle rectangle2 = rectangle;
        ArmorShaderData armorShaderData = null;
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullNone, (Effect)null, Transform);
        Vector2 origin = default(Vector2);
        for (int i = 0; i < maxDustToDraw; i++)
        {
            Dust dust = Main.dust[i];
            if (!dust.active)
            {
                continue;
            }
            if ((dust.type >= 130 && dust.type <= 134) || (dust.type >= 219 && dust.type <= 223) || dust.type == 226 || dust.type == 278)
            {
                rectangle = rectangle2;
            }
            Rectangle val = new Rectangle((int)dust.position.X, (int)dust.position.Y, 4, 4);
            if (((Rectangle)(ref val)).Intersects(rectangle))
            {
                float scale = dust.GetVisualScale();
                if (dust.shader != armorShaderData)
                {
                    spriteBatch.End();
                    armorShaderData = dust.shader;
                    if (armorShaderData == null)
                    {
                        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullNone, (Effect)null, Transform);
                    }
                    else
                    {
                        spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, SamplerState.PointClamp, DepthStencilState.None, RasterizerState.CullNone, (Effect)null, Transform);
                        dust.shader.Apply(null);
                    }
                }
                if (dust.type >= 130 && dust.type <= 134)
                {
                    float num = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                    num *= 0.3f;
                    num *= 10f;
                    if (num > 10f)
                    {
                        num = 10f;
                    }
                    for (int j = 0; (float)j < num; j++)
                    {
                        Vector2 velocity = dust.velocity;
                        Vector2 vector = dust.position - velocity * (float)j;
                        float scale2 = dust.scale * (1f - (float)j / 10f);
                        Color color = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                        color = dust.GetAlpha(color);
                        spriteBatch.Draw(TextureAssets.Dust.Value, vector - screenPosition, (Rectangle?)dust.frame, color, dust.rotation, new Vector2(4f, 4f), scale2, (SpriteEffects)0, 0f);
                    }
                }
                else if (dust.type == 278)
                {
                    float num2 = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                    num2 *= 0.3f;
                    num2 *= 10f;
                    if (num2 > 10f)
                    {
                        num2 = 10f;
                    }
                    ((Vector2)(ref origin))._002Ector(4f, 4f);
                    for (int k = 0; (float)k < num2; k++)
                    {
                        Vector2 velocity2 = dust.velocity;
                        Vector2 vector2 = dust.position - velocity2 * (float)k;
                        float scale3 = dust.scale * (1f - (float)k / 10f);
                        Color color2 = Lighting.GetColor((int)(dust.position.X + 4f) / 16, (int)(dust.position.Y + 4f) / 16);
                        color2 = dust.GetAlpha(color2);
                        spriteBatch.Draw(TextureAssets.Dust.Value, vector2 - screenPosition, (Rectangle?)dust.frame, color2, dust.rotation, origin, scale3, (SpriteEffects)0, 0f);
                    }
                }
                else if (dust.type >= 219 && dust.type <= 223 && dust.fadeIn == 0f)
                {
                    float num3 = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                    num3 *= 0.3f;
                    num3 *= 10f;
                    if (num3 > 10f)
                    {
                        num3 = 10f;
                    }
                    for (int l = 0; (float)l < num3; l++)
                    {
                        Vector2 velocity3 = dust.velocity;
                        Vector2 vector3 = dust.position - velocity3 * (float)l;
                        float scale4 = dust.scale * (1f - (float)l / 10f);
                        Color color3 = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                        color3 = dust.GetAlpha(color3);
                        spriteBatch.Draw(TextureAssets.Dust.Value, vector3 - screenPosition, (Rectangle?)dust.frame, color3, dust.rotation, new Vector2(4f, 4f), scale4, (SpriteEffects)0, 0f);
                    }
                }
                else if (dust.type == 264 && dust.fadeIn == 0f)
                {
                    float num4 = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                    num4 *= 10f;
                    if (num4 > 10f)
                    {
                        num4 = 10f;
                    }
                    for (int m = 0; (float)m < num4; m++)
                    {
                        Vector2 velocity4 = dust.velocity;
                        Vector2 vector4 = dust.position - velocity4 * (float)m;
                        float scale5 = dust.scale * (1f - (float)m / 10f);
                        Color color4 = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                        color4 = dust.GetAlpha(color4) * 0.3f;
                        spriteBatch.Draw(TextureAssets.Dust.Value, vector4 - screenPosition, (Rectangle?)dust.frame, color4, dust.rotation, new Vector2(5f), scale5, (SpriteEffects)0, 0f);
                        color4 = dust.GetColor(color4);
                        spriteBatch.Draw(TextureAssets.Dust.Value, vector4 - screenPosition, (Rectangle?)dust.frame, color4, dust.rotation, new Vector2(5f), scale5, (SpriteEffects)0, 0f);
                    }
                }
                else if ((dust.type == 226 || dust.type == 272) && dust.fadeIn == 0f)
                {
                    float num5 = Math.Abs(dust.velocity.X) + Math.Abs(dust.velocity.Y);
                    num5 *= 0.3f;
                    num5 *= 10f;
                    if (num5 > 10f)
                    {
                        num5 = 10f;
                    }
                    for (int n = 0; (float)n < num5; n++)
                    {
                        Vector2 velocity5 = dust.velocity;
                        Vector2 vector5 = dust.position - velocity5 * (float)n;
                        float scale6 = dust.scale * (1f - (float)n / 10f);
                        Color color5 = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                        color5 = dust.GetAlpha(color5);
                        spriteBatch.Draw(TextureAssets.Dust.Value, vector5 - screenPosition, (Rectangle?)dust.frame, color5, dust.rotation, new Vector2(4f, 4f), scale6, (SpriteEffects)0, 0f);
                    }
                }
                Color newColor = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                if (dust.type == 6 || dust.type == 15 || (dust.type >= 59 && dust.type <= 64))
                {
                    newColor = Color.White;
                }
                newColor = dust.GetAlpha(newColor);
                if (dust.type == 213)
                {
                    scale = 1f;
                }
                ModDust modDust = DustLoader.GetDust(dust.type);
                if (modDust != null)
                {
                    if (modDust.PreDraw(dust))
                    {
                        modDust.Draw(dust, newColor, scale);
                    }
                    if (newColor == Color.Black)
                    {
                        dust.active = false;
                    }
                    continue;
                }
                spriteBatch.Draw(TextureAssets.Dust.Value, dust.position - screenPosition, (Rectangle?)dust.frame, newColor, dust.GetVisualRotation(), new Vector2(4f, 4f), scale, (SpriteEffects)0, 0f);
                if (((Color)(ref dust.color)).PackedValue != 0)
                {
                    Color color6 = dust.GetColor(newColor);
                    if (((Color)(ref color6)).PackedValue != 0)
                    {
                        spriteBatch.Draw(TextureAssets.Dust.Value, dust.position - screenPosition, (Rectangle?)dust.frame, color6, dust.GetVisualRotation(), new Vector2(4f, 4f), scale, (SpriteEffects)0, 0f);
                    }
                }
                if (newColor == Color.Black)
                {
                    dust.active = false;
                }
            }
            else
            {
                dust.active = false;
            }
        }
        spriteBatch.End();
        pixelShader.CurrentTechnique.Passes[0].Apply();
        TimeLogger.DetailedDrawTime(25);
    }
References Terraria.TimeLogger.DetailedDrawTime(), Terraria.GameContent.TextureAssets.Dust, Terraria.Main.dust, Terraria.Lighting.GetColor(), Terraria.ModLoader.DustLoader.GetDust(), Terraria.Main.maxDustToDraw, Terraria.Main.pixelShader, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, and Terraria.Main.Transform.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().