TModLoader: Terraria.Main.DrawProj
DrawProj()
void Terraria.Main.DrawProj (int i) inline
    {
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_005f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        int num = ProjectileID.Sets.DrawScreenCheckFluff[projectile[i].type];
        Rectangle val = new Rectangle((int)Camera.ScaledPosition.X - num, (int)Camera.ScaledPosition.Y - num, (int)Camera.ScaledSize.X + num * 2, (int)Camera.ScaledSize.Y + num * 2);
        if (((Rectangle)(ref val)).Intersects(projectile[i].Hitbox))
        {
            Projectile proj = projectile[i];
            DrawProjDirect(proj);
        }
    }
References Terraria.Main.DrawProjDirect(), Terraria.ID.ProjectileID.Sets.DrawScreenCheckFluff, Terraria.Main.projectile, Terraria.Graphics.Camera.ScaledPosition, Terraria.Graphics.Camera.ScaledSize, and Terraria.Projectile.type.
Referenced by Terraria.Main.DrawCachedProjs(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerInternal(), Terraria.Main.DrawProj_DrawNormalProjs(), Terraria.Main.DrawProjectiles(), and Terraria.Main.DrawWallOfStars().