TModLoader: Terraria.Main.DrawLiquid
DrawLiquid()
void Terraria.Main.DrawLiquid (bool bg = false, int waterStyle = 0, float Alpha = 1f, bool drawSinglePassLiquids = true) inline package
Definition at line 73184 of file Main.cs.
    {
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        if (!Lighting.NotRetro)
        {
            oldDrawWater(bg, waterStyle, Alpha);
            return;
        }
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        Vector2 drawOffset = (Vector2)(drawToScreen ? Vector2.Zero : new Vector2((float)offScreenRange, (float)offScreenRange)) - screenPosition;
        if (bg)
        {
            TilesRenderer.DrawLiquidBehindTiles(waterStyle);
        }
        LiquidRenderer.Instance.DrawNormalLiquids(spriteBatch, drawOffset, waterStyle, Alpha, bg);
        if (drawSinglePassLiquids)
        {
            LiquidRenderer.Instance.DrawShimmer(spriteBatch, drawOffset, bg);
        }
        if (!bg)
        {
            TimeLogger.DrawTime(4, stopwatch.Elapsed.TotalMilliseconds);
        }
    }
References Terraria.GameContent.Drawing.TileDrawing.DrawLiquidBehindTiles(), Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids(), Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer(), Terraria.TimeLogger.DrawTime(), Terraria.Main.drawToScreen, Terraria.GameContent.Liquid.LiquidRenderer.Instance, Terraria.Lighting.NotRetro, Terraria.Main.offScreenRange, Terraria.Main.oldDrawWater(), Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Main.TilesRenderer, and Terraria.Main.waterStyle.
Referenced by Terraria.Main.DrawCapture(), and Terraria.Main.DrawWaters().