TModLoader: Terraria.Main.GUIChatDrawInner
GUIChatDrawInner()
void Terraria.Main.GUIChatDrawInner () inline protected
    {
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_034f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0359: Unknown result type (might be due to invalid IL or missing references)
        //IL_0361: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0504: Unknown result type (might be due to invalid IL or missing references)
        //IL_0530: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        //IL_054d: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_056b: Unknown result type (might be due to invalid IL or missing references)
        //IL_055b: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_057f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0588: Unknown result type (might be due to invalid IL or missing references)
        //IL_058d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0597: Unknown result type (might be due to invalid IL or missing references)
        //IL_0599: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0602: Unknown result type (might be due to invalid IL or missing references)
        //IL_060f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0617: Unknown result type (might be due to invalid IL or missing references)
        //IL_0624: Unknown result type (might be due to invalid IL or missing references)
        //IL_0630: Unknown result type (might be due to invalid IL or missing references)
        //IL_063c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        //IL_064f: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_068c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1507: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1551: Unknown result type (might be due to invalid IL or missing references)
        //IL_155b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1609: Unknown result type (might be due to invalid IL or missing references)
        if (player[myPlayer].talkNPC < 0 && player[myPlayer].sign == -1)
        {
            npcChatText = "";
            return;
        }
        Color color = default(Color);
        ((Color)(ref color))._002Ector(200, 200, 200, 200);
        int num = (mouseTextColor * 2 + 255) / 3;
        Color color2 = default(Color);
        ((Color)(ref color2))._002Ector(num, num, num, num);
        bool flag = InGameUI.CurrentState is UIVirtualKeyboard && PlayerInput.UsingGamepad;
        string textValue = npcChatText;
        bool num27 = player[myPlayer].talkNPC != -1 && CanDryadPlayStardewAnimation(LocalPlayer, npc[player[myPlayer].talkNPC]);
        if (player[myPlayer].talkNPC != -1 && npc[player[myPlayer].talkNPC].ai[0] == 24f && NPC.RerollDryadText == 2)
        {
            NPC.RerollDryadText = 1;
        }
        if (num27 && NPC.RerollDryadText == 1 && npc[player[myPlayer].talkNPC].ai[0] != 24f && player[myPlayer].talkNPC != -1 && npc[player[myPlayer].talkNPC].active && npc[player[myPlayer].talkNPC].type == 20)
        {
            NPC.RerollDryadText = 0;
            npcChatText = npc[player[myPlayer].talkNPC].GetChat();
            NPC.PreventJojaColaDialog = true;
        }
        if (num27 && !NPC.PreventJojaColaDialog)
        {
            textValue = Language.GetTextValue("StardewTalk.PlayerHasColaAndIsHoldingIt");
        }
        _ = player[myPlayer].talkNPC;
        _textDisplayCache.PrepareCache(textValue, color2);
        List<List<TextSnippet>> textLines = _textDisplayCache.TextLines;
        int amountOfLines = _textDisplayCache.AmountOfLines;
        bool flag2 = false;
        if (editSign)
        {
            textBlinkerCount++;
            if (textBlinkerCount >= 20)
            {
                if (textBlinkerState == 0)
                {
                    textBlinkerState = 1;
                }
                else
                {
                    textBlinkerState = 0;
                }
                textBlinkerCount = 0;
            }
            if (textBlinkerState == 1)
            {
                flag2 = true;
                textLines[amountOfLines - 1].Add(new TextSnippet("|", Color.White));
            }
            instance.DrawWindowsIMEPanel(new Vector2((float)(screenWidth / 2), 90f), 0.5f);
        }
        spriteBatch.Draw(TextureAssets.ChatBack.Value, new Vector2((float)(screenWidth / 2 - TextureAssets.ChatBack.Width() / 2), 100f), (Rectangle?)new Rectangle(0, 0, TextureAssets.ChatBack.Width(), (amountOfLines + 1) * 30), color, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        spriteBatch.Draw(TextureAssets.ChatBack.Value, new Vector2((float)(screenWidth / 2 - TextureAssets.ChatBack.Width() / 2), (float)(100 + (amountOfLines + 1) * 30)), (Rectangle?)new Rectangle(0, TextureAssets.ChatBack.Height() - 30, TextureAssets.ChatBack.Width(), 30), color, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        TextSnippet hoveredSnippet = null;
        for (int i = 0; i < amountOfLines; i++)
        {
            List<TextSnippet> text = textLines[i];
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text.ToArray(), new Vector2((float)(170 + (screenWidth - 800) / 2), (float)(120 + i * 30)), 0f, color2, Color.Black, Vector2.Zero, Vector2.One, out var hoveredSnippetNum);
            if (hoveredSnippetNum > -1)
            {
                hoveredSnippet = text[hoveredSnippetNum];
            }
        }
        if (flag2)
        {
            textLines[amountOfLines - 1].RemoveAt(textLines[amountOfLines - 1].Count - 1);
        }
        if (hoveredSnippet != null)
        {
            hoveredSnippet.OnHover();
            if (mouseLeft && mouseLeftRelease)
            {
                hoveredSnippet.OnClick();
            }
        }
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(screenWidth / 2 - TextureAssets.ChatBack.Width() / 2, 100, TextureAssets.ChatBack.Width(), (amountOfLines + 2) * 30);
        int num20 = 120 + amountOfLines * 30 + 30;
        num20 -= 235;
        UIVirtualKeyboard.ShouldHideText = !PlayerInput.SettingsForUI.ShowGamepadHints;
        if (!PlayerInput.UsingGamepad)
        {
            num20 = 9999;
        }
        UIVirtualKeyboard.OffsetDown = num20;
        if (npcChatCornerItem != 0)
        {
            Vector2 position = default(Vector2);
            ((Vector2)(ref position))._002Ector((float)(screenWidth / 2 + TextureAssets.ChatBack.Width() / 2), (float)(100 + (amountOfLines + 1) * 30 + 30));
            position -= Vector2.One * 8f;
            Item item = new Item();
            item.netDefaults(npcChatCornerItem);
            float num21 = 1f;
            GetItemDrawFrame(item.type, out var itemTexture, out var rectangle2);
            if (rectangle2.Width > 32 || rectangle2.Height > 32)
            {
                num21 = ((rectangle2.Width <= rectangle2.Height) ? (32f / (float)rectangle2.Height) : (32f / (float)rectangle2.Width));
            }
            spriteBatch.Draw(itemTexture, position, (Rectangle?)rectangle2, item.GetAlpha(Color.White), 0f, rectangle2.Size(), num21, (SpriteEffects)0, 0f);
            if (item.color != default(Color))
            {
                spriteBatch.Draw(itemTexture, position, (Rectangle?)rectangle2, item.GetColor(item.color), 0f, rectangle2.Size(), num21, (SpriteEffects)0, 0f);
            }
            Rectangle val = new Rectangle((int)position.X - (int)((float)rectangle2.Width * num21), (int)position.Y - (int)((float)rectangle2.Height * num21), (int)((float)rectangle2.Width * num21), (int)((float)rectangle2.Height * num21));
            if (((Rectangle)(ref val)).Contains(new Point(mouseX, mouseY)))
            {
                cursorOverride = 2;
                if (mouseLeftRelease && mouseLeft)
                {
                    if (!drawingPlayerChat)
                    {
                        OpenPlayerChat();
                    }
                    if (ChatManager.AddChatText(FontAssets.MouseText.Value, ItemTagHandler.GenerateTag(item), Vector2.One))
                    {
                        SoundEngine.PlaySound(12);
                    }
                }
                MouseText(item.Name, -11, 0);
            }
        }
        num = mouseTextColor;
        ((Color)(ref color2))._002Ector(num, (int)((double)num / 1.1), num / 2, num);
        string focusText = "";
        string focusText2 = "";
        int num22 = player[myPlayer].statLifeMax2 - player[myPlayer].statLife;
        for (int j = 0; j < Player.maxBuffs; j++)
        {
            int num23 = player[myPlayer].buffType[j];
            if (debuff[num23] && player[myPlayer].buffTime[j] > 60 && (num23 < 0 || !BuffID.Sets.NurseCannotRemoveDebuff[num23]))
            {
                num22 += 100;
            }
        }
        int health = LocalPlayer.statLifeMax2 - LocalPlayer.statLife;
        bool removeDebuffs = true;
        string reason = "";
        bool canHeal = true;
        if (NPC.downedGolemBoss)
        {
            num22 *= 200;
        }
        else if (NPC.downedPlantBoss)
        {
            num22 *= 150;
        }
        else if (NPC.downedMechBossAny)
        {
            num22 *= 100;
        }
        else if (hardMode)
        {
            num22 *= 60;
        }
        else if (NPC.downedBoss3 || NPC.downedQueenBee)
        {
            num22 *= 25;
        }
        else if (NPC.downedBoss2)
        {
            num22 *= 10;
        }
        else if (NPC.downedBoss1)
        {
            num22 *= 3;
        }
        if (expertMode)
        {
            num22 *= 2;
        }
        num22 = (int)((double)num22 * player[myPlayer].currentShoppingSettings.PriceAdjustment);
        string text2 = null;
        string text3 = null;
        if (player[myPlayer].sign > -1)
        {
            focusText = ((!editSign) ? Lang.inter[48].Value : Lang.inter[47].Value);
        }
        else if (npc[player[myPlayer].talkNPC].type == 20)
        {
            focusText = Lang.inter[28].Value;
            focusText2 = Lang.inter[49].Value;
            if (CanDryadPlayStardewAnimation(LocalPlayer, npc[player[myPlayer].talkNPC]))
            {
                focusText2 = Language.GetTextValue("StardewTalk.GiveColaButtonText");
            }
        }
        else if (NPCID.Sets.IsTownPet[npc[player[myPlayer].talkNPC].type])
        {
            focusText = Language.GetTextValue("UI.PetTheAnimal");
        }
        else if (npc[player[myPlayer].talkNPC].type == 207)
        {
            focusText = Lang.inter[28].Value;
            if (hardMode)
            {
                focusText2 = Lang.inter[107].Value;
            }
        }
        else if (npc[player[myPlayer].talkNPC].type == 453)
        {
            focusText = Lang.inter[28].Value;
        }
        else if (npc[player[myPlayer].talkNPC].type == 550)
        {
            focusText = Lang.inter[28].Value;
            focusText2 = Language.GetTextValue("UI.BartenderHelp");
        }
        else if (npc[player[myPlayer].talkNPC].type == 588)
        {
            focusText = Lang.inter[28].Value;
        }
        else if (npc[player[myPlayer].talkNPC].type == 633)
        {
            focusText = Lang.inter[28].Value;
        }
        else if (npc[player[myPlayer].talkNPC].type == 663)
        {
            focusText = Lang.inter[28].Value;
        }
        else if (npc[player[myPlayer].talkNPC].type == 353)
        {
            focusText = Lang.inter[28].Value;
            focusText2 = Language.GetTextValue("GameUI.HairStyle");
        }
        else if (npc[player[myPlayer].talkNPC].type == 368)
        {
            focusText = Lang.inter[28].Value;
        }
        else if (npc[player[myPlayer].talkNPC].type == 369)
        {
            focusText = Lang.inter[64].Value;
        }
        else if (npc[player[myPlayer].talkNPC].type == 208)
        {
            focusText = Lang.inter[28].Value;
            if (TOWMusicUnlocked)
            {
                focusText2 = Language.GetTextValue("GameUI.Music");
            }
        }
        else if (npc[player[myPlayer].talkNPC].type == 227)
        {
            focusText = Lang.inter[28].Value;
            focusText2 = Language.GetTextValue("GameUI.PainterDecor");
        }
        else if (npc[player[myPlayer].talkNPC].type == 17 || npc[player[myPlayer].talkNPC].type == 19 || npc[player[myPlayer].talkNPC].type == 38 || npc[player[myPlayer].talkNPC].type == 54 || npc[player[myPlayer].talkNPC].type == 107 || npc[player[myPlayer].talkNPC].type == 108 || npc[player[myPlayer].talkNPC].type == 124 || npc[player[myPlayer].talkNPC].type == 142 || npc[player[myPlayer].talkNPC].type == 160 || npc[player[myPlayer].talkNPC].type == 178 || npc[player[myPlayer].talkNPC].type == 207 || npc[player[myPlayer].talkNPC].type == 209 || npc[player[myPlayer].talkNPC].type == 228 || npc[player[myPlayer].talkNPC].type == 229)
        {
            focusText = Lang.inter[28].Value;
            if (npc[player[myPlayer].talkNPC].type == 107)
            {
                focusText2 = Lang.inter[19].Value;
            }
        }
        else if (npc[player[myPlayer].talkNPC].type == 37)
        {
            if (!IsItDay())
            {
                focusText = Lang.inter[50].Value;
            }
        }
        else if (npc[player[myPlayer].talkNPC].type == 22)
        {
            focusText = Lang.inter[51].Value;
            focusText2 = Lang.inter[25].Value;
        }
        else if (npc[player[myPlayer].talkNPC].type == 441)
        {
            if (player[myPlayer].taxMoney <= 0)
            {
                focusText = Lang.inter[89].Value;
            }
            else
            {
                string text4 = "";
                int num24 = 0;
                int num25 = 0;
                int num26 = 0;
                int num2 = 0;
                int taxMoney = player[myPlayer].taxMoney;
                taxMoney = (int)((double)taxMoney / player[myPlayer].currentShoppingSettings.PriceAdjustment);
                if (taxMoney < 0)
                {
                    taxMoney = 0;
                }
                num22 = taxMoney;
                if (taxMoney >= 1000000)
                {
                    num24 = taxMoney / 1000000;
                    taxMoney -= num24 * 1000000;
                }
                if (taxMoney >= 10000)
                {
                    num25 = taxMoney / 10000;
                    taxMoney -= num25 * 10000;
                }
                if (taxMoney >= 100)
                {
                    num26 = taxMoney / 100;
                    taxMoney -= num26 * 100;
                }
                if (taxMoney >= 1)
                {
                    num2 = taxMoney;
                }
                if (num24 > 0)
                {
                    text4 = text4 + num24 + " " + Lang.inter[15].Value + " ";
                }
                if (num25 > 0)
                {
                    text4 = text4 + num25 + " " + Lang.inter[16].Value + " ";
                }
                if (num26 > 0)
                {
                    text4 = text4 + num26 + " " + Lang.inter[17].Value + " ";
                }
                if (num2 > 0)
                {
                    text4 = text4 + num2 + " " + Lang.inter[18].Value + " ";
                }
                float num3 = (float)(int)mouseTextColor / 255f;
                if (num24 > 0)
                {
                    ((Color)(ref color2))._002Ector((int)(byte)(220f * num3), (int)(byte)(220f * num3), (int)(byte)(198f * num3), (int)mouseTextColor);
                }
                else if (num25 > 0)
                {
                    ((Color)(ref color2))._002Ector((int)(byte)(224f * num3), (int)(byte)(201f * num3), (int)(byte)(92f * num3), (int)mouseTextColor);
                }
                else if (num26 > 0)
                {
                    ((Color)(ref color2))._002Ector((int)(byte)(181f * num3), (int)(byte)(192f * num3), (int)(byte)(193f * num3), (int)mouseTextColor);
                }
                else if (num2 > 0)
                {
                    ((Color)(ref color2))._002Ector((int)(byte)(246f * num3), (int)(byte)(138f * num3), (int)(byte)(96f * num3), (int)mouseTextColor);
                }
                if (text4 == "")
                {
                    focusText = Lang.inter[89].Value;
                }
                else
                {
                    text4 = text4.Substring(0, text4.Length - 1);
                    focusText = Lang.inter[89].Value + " (" + text4 + ")";
                }
                focusText = Lang.inter[89].Value;
                text3 = focusText;
                text2 = "";
                for (int k = 0; k < focusText.Length; k++)
                {
                    text2 += " ";
                }
                focusText = focusText + text2 + "        ";
            }
        }
        else if (npc[player[myPlayer].talkNPC].type == 18)
        {
            string text5 = "";
            int num4 = 0;
            int num5 = 0;
            int num6 = 0;
            int num7 = 0;
            int num8 = num22;
            if (num8 > 0 && num8 < 1)
            {
                num8 = 1;
            }
            reason = Language.GetTextValue("tModLoader.DefaultNurseCantHealChat");
            canHeal = PlayerLoader.ModifyNurseHeal(player[myPlayer], LocalPlayer.TalkNPC, ref health, ref removeDebuffs, ref reason);
            PlayerLoader.ModifyNursePrice(player[myPlayer], LocalPlayer.TalkNPC, health, removeDebuffs, ref num8);
            if (num8 < 0)
            {
                num8 = 0;
            }
            num22 = num8;
            if (num8 >= 1000000)
            {
                num4 = num8 / 1000000;
                num8 -= num4 * 1000000;
            }
            if (num8 >= 10000)
            {
                num5 = num8 / 10000;
                num8 -= num5 * 10000;
            }
            if (num8 >= 100)
            {
                num6 = num8 / 100;
                num8 -= num6 * 100;
            }
            if (num8 >= 1)
            {
                num7 = num8;
            }
            if (num4 > 0)
            {
                text5 = text5 + num4 + " " + Lang.inter[15].Value + " ";
            }
            if (num5 > 0)
            {
                text5 = text5 + num5 + " " + Lang.inter[16].Value + " ";
            }
            if (num6 > 0)
            {
                text5 = text5 + num6 + " " + Lang.inter[17].Value + " ";
            }
            if (num7 > 0)
            {
                text5 = text5 + num7 + " " + Lang.inter[18].Value + " ";
            }
            float num9 = (float)(int)mouseTextColor / 255f;
            if (num4 > 0)
            {
                ((Color)(ref color2))._002Ector((int)(byte)(220f * num9), (int)(byte)(220f * num9), (int)(byte)(198f * num9), (int)mouseTextColor);
            }
            else if (num5 > 0)
            {
                ((Color)(ref color2))._002Ector((int)(byte)(224f * num9), (int)(byte)(201f * num9), (int)(byte)(92f * num9), (int)mouseTextColor);
            }
            else if (num6 > 0)
            {
                ((Color)(ref color2))._002Ector((int)(byte)(181f * num9), (int)(byte)(192f * num9), (int)(byte)(193f * num9), (int)mouseTextColor);
            }
            else if (num7 > 0)
            {
                ((Color)(ref color2))._002Ector((int)(byte)(246f * num9), (int)(byte)(138f * num9), (int)(byte)(96f * num9), (int)mouseTextColor);
            }
            if (text5 == "")
            {
                focusText = Lang.inter[54].Value;
            }
            else
            {
                text5 = text5.Substring(0, text5.Length - 1);
                focusText = Lang.inter[54].Value + " (" + text5 + ")";
            }
        }
        NPCLoader.SetChatButtons(ref focusText, ref focusText2);
        if (!flag)
        {
            DrawNPCChatButtons(num, color2, amountOfLines, focusText, focusText2);
            if (text2 != null)
            {
                float num10 = 130 + amountOfLines * 30;
                float num11 = 180 + (screenWidth - 800) / 2;
                num11 += ChatManager.GetStringSize(FontAssets.MouseText.Value, text3, new Vector2(0.9f)).X - 20f;
                int taxMoney2 = player[myPlayer].taxMoney;
                taxMoney2 = (int)((double)taxMoney2 / player[myPlayer].currentShoppingSettings.PriceAdjustment);
                ItemSlot.DrawMoney(spriteBatch, "", num11, num10 - 40f, Utils.CoinsSplit(taxMoney2), horizontal: true);
            }
        }
        if (PlayerInput.IgnoreMouseInterface)
        {
            return;
        }
        if (((Rectangle)(ref rectangle)).Contains(new Point(mouseX, mouseY)))
        {
            player[myPlayer].mouseInterface = true;
        }
        if (!mouseLeft || !mouseLeftRelease || !((Rectangle)(ref rectangle)).Contains(new Point(mouseX, mouseY)))
        {
            return;
        }
        mouseLeftRelease = false;
        player[myPlayer].releaseUseItem = false;
        player[myPlayer].mouseInterface = true;
        if (npcChatFocus1)
        {
            CloseNPCChatOrSign();
        }
        else if (npcChatFocus2)
        {
            if (player[myPlayer].sign != -1)
            {
                if (editSign)
                {
                    SubmitSignText();
                }
                else
                {
                    IngameFancyUI.OpenVirtualKeyboard(1);
                }
            }
            else if (NPCID.Sets.IsTownPet[npc[player[myPlayer].talkNPC].type])
            {
                player[myPlayer].PetAnimal(player[myPlayer].talkNPC);
            }
            else
            {
                if (!NPCLoader.PreChatButtonClicked(firstButton: true))
                {
                    return;
                }
                NPCLoader.OnChatButtonClicked(firstButton: true);
                if (npc[player[myPlayer].talkNPC].type == 369)
                {
                    npcChatCornerItem = 0;
                    SoundEngine.PlaySound(12);
                    bool flag3 = false;
                    if (!anglerQuestFinished && !anglerWhoFinishedToday.Contains(player[myPlayer].name))
                    {
                        int num12 = player[myPlayer].FindItem(anglerQuestItemNetIDs[anglerQuest]);
                        if (num12 != -1)
{
                            player[myPlayer].inventory[num12].stack--;
                            if (player[myPlayer].inventory[num12].stack <= 0)
{
                                player[myPlayer].inventory[num12] = new Item();
                            }
                            flag3 = true;
                            SoundEngine.PlaySound(24);
                            player[myPlayer].anglerQuestsFinished++;
                            player[myPlayer].GetAnglerReward(npc[player[myPlayer].talkNPC], anglerQuestItemNetIDs[anglerQuest]);
                        }
                    }
                    npcChatText = Lang.AnglerQuestChat(flag3);
                    if (flag3)
                    {
                        anglerQuestFinished = true;
                        if (netMode == 1)
{
                            NetMessage.SendData(75);
                        }
                        else
{
                            anglerWhoFinishedToday.Add(player[myPlayer].name);
                        }
                        AchievementsHelper.HandleAnglerService();
                    }
                }
                else if (npc[player[myPlayer].talkNPC].type == 17)
                {
                    OpenShop(1);
                }
                else if (npc[player[myPlayer].talkNPC].type == 19)
                {
                    OpenShop(2);
                }
                else if (npc[player[myPlayer].talkNPC].type == 124)
                {
                    OpenShop(8);
                }
                else if (npc[player[myPlayer].talkNPC].type == 142)
                {
                    OpenShop(9);
                }
                else if (npc[player[myPlayer].talkNPC].type == 37)
                {
                    if (netMode == 0)
                    {
                        NPC.SpawnSkeletron(myPlayer);
                    }
                    else
                    {
                        NetMessage.SendData(51, -1, -1, null, myPlayer, 1f);
                    }
                    npcChatText = "";
                }
                else if (npc[player[myPlayer].talkNPC].type == 20)
                {
                    OpenShop(3);
                }
                else if (npc[player[myPlayer].talkNPC].type == 38)
                {
                    OpenShop(4);
                }
                else if (npc[player[myPlayer].talkNPC].type == 54)
                {
                    OpenShop(5);
                }
                else if (npc[player[myPlayer].talkNPC].type == 107)
                {
                    OpenShop(6);
                }
                else if (npc[player[myPlayer].talkNPC].type == 108)
                {
                    OpenShop(7);
                }
                else if (npc[player[myPlayer].talkNPC].type == 160)
                {
                    OpenShop(10);
                }
                else if (npc[player[myPlayer].talkNPC].type == 178)
                {
                    OpenShop(11);
                }
                else if (npc[player[myPlayer].talkNPC].type == 207)
                {
                    OpenShop(12);
                }
                else if (npc[player[myPlayer].talkNPC].type == 208)
                {
                    OpenShop(13);
                }
                else if (npc[player[myPlayer].talkNPC].type == 209)
                {
                    OpenShop(14);
                }
                else if (npc[player[myPlayer].talkNPC].type == 227)
                {
                    OpenShop(15);
                }
                else if (npc[player[myPlayer].talkNPC].type == 228)
                {
                    OpenShop(16);
                }
                else if (npc[player[myPlayer].talkNPC].type == 229)
                {
                    OpenShop(17);
                }
                else if (npc[player[myPlayer].talkNPC].type == 353)
                {
                    OpenShop(18);
                }
                else if (npc[player[myPlayer].talkNPC].type == 368)
                {
                    OpenShop(19);
                }
                else if (npc[player[myPlayer].talkNPC].type == 453)
                {
                    OpenShop(20);
                }
                else if (npc[player[myPlayer].talkNPC].type == 550)
                {
                    OpenShop(21);
                }
                else if (npc[player[myPlayer].talkNPC].type == 588)
                {
                    OpenShop(22);
                }
                else if (npc[player[myPlayer].talkNPC].type == 633)
                {
                    OpenShop(23);
                }
                else if (npc[player[myPlayer].talkNPC].type == 663)
                {
                    OpenShop(24);
                }
                else if (npc[player[myPlayer].talkNPC].type == 22)
                {
                    SoundEngine.PlaySound(12);
                    HelpText();
                }
                else if (npc[player[myPlayer].talkNPC].type == 441)
                {
                    if (player[myPlayer].taxMoney > 0)
                    {
                        int taxMoney3 = player[myPlayer].taxMoney;
                        taxMoney3 = (int)((double)taxMoney3 / player[myPlayer].currentShoppingSettings.PriceAdjustment);
                        while (taxMoney3 > 0)
{
                            EntitySource_Gift source = new EntitySource_Gift(npc[player[myPlayer].talkNPC]);
                            if (taxMoney3 > 1000000)
{
                                int num13 = taxMoney3 / 1000000;
                                taxMoney3 -= 1000000 * num13;
                                int number = Item.NewItem(source, (int)player[myPlayer].position.X, (int)player[myPlayer].position.Y, player[myPlayer].width, player[myPlayer].height, 74, num13);
                                if (netMode == 1)
{
                                    NetMessage.SendData(21, -1, -1, null, number, 1f);
                                }
                                continue;
                            }
                            if (taxMoney3 > 10000)
{
                                int num14 = taxMoney3 / 10000;
                                taxMoney3 -= 10000 * num14;
                                int number2 = Item.NewItem(source, (int)player[myPlayer].position.X, (int)player[myPlayer].position.Y, player[myPlayer].width, player[myPlayer].height, 73, num14);
                                if (netMode == 1)
{
                                    NetMessage.SendData(21, -1, -1, null, number2, 1f);
                                }
                                continue;
                            }
                            if (taxMoney3 > 100)
{
                                int num15 = taxMoney3 / 100;
                                taxMoney3 -= 100 * num15;
                                int number3 = Item.NewItem(source, (int)player[myPlayer].position.X, (int)player[myPlayer].position.Y, player[myPlayer].width, player[myPlayer].height, 72, num15);
                                if (netMode == 1)
{
                                    NetMessage.SendData(21, -1, -1, null, number3, 1f);
                                }
                                continue;
                            }
                            int num16 = taxMoney3;
                            if (num16 < 1)
{
                                num16 = 1;
                            }
                            taxMoney3 -= num16;
                            int number4 = Item.NewItem(source, (int)player[myPlayer].position.X, (int)player[myPlayer].position.Y, player[myPlayer].width, player[myPlayer].height, 71, num16);
                            if (netMode == 1)
{
                                NetMessage.SendData(21, -1, -1, null, number4, 1f);
                            }
                        }
                        npcChatText = Lang.dialog(rand.Next(380, 382));
                        player[myPlayer].taxMoney = 0;
                    }
                    else
                    {
                        npcChatText = Lang.dialog(rand.Next(390, 401));
                    }
                }
                else
                {
                    if (npc[player[myPlayer].talkNPC].type != 18)
                    {
                        return;
                    }
                    SoundEngine.PlaySound(12);
                    if (num22 > 0)
                    {
                        if (!canHeal)
{
                            npcChatText = reason;
                        }
                        else if (player[myPlayer].BuyItem(num22))
{
                            AchievementsHelper.HandleNurseService(num22);
                            SoundEngine.PlaySound(in SoundID.Item4);
                            player[myPlayer].HealEffect(health);
                            if ((double)player[myPlayer].statLife < (double)player[myPlayer].statLifeMax2 * 0.25)
{
                                npcChatText = Lang.dialog(227);
                            }
                            else if ((double)player[myPlayer].statLife < (double)player[myPlayer].statLifeMax2 * 0.5)
{
                                npcChatText = Lang.dialog(228);
                            }
                            else if ((double)player[myPlayer].statLife < (double)player[myPlayer].statLifeMax2 * 0.75)
{
                                npcChatText = Lang.dialog(229);
                            }
                            else
{
                                npcChatText = Lang.dialog(230);
                            }
                            player[myPlayer].statLife += health;
                            if (removeDebuffs)
{
                                for (int l = 0; l < Player.maxBuffs; l++)
{
                                    int num17 = player[myPlayer].buffType[l];
                                    if (debuff[num17] && player[myPlayer].buffTime[l] > 0 && (num17 < 0 || !BuffID.Sets.NurseCannotRemoveDebuff[num17]))
{
                                        player[myPlayer].DelBuff(l);
                                        l = -1;
                                    }
                                }
                            }
                            PlayerLoader.PostNurseHeal(LocalPlayer, LocalPlayer.TalkNPC, health, removeDebuffs, num22);
                        }
                        else
{
                            int num28 = rand.Next(3);
                            if (num28 == 0)
{
                                npcChatText = Lang.dialog(52);
                            }
                            if (num28 == 1)
{
                                npcChatText = Lang.dialog(53);
                            }
                            if (num28 == 2)
{
                                npcChatText = Lang.dialog(54);
                            }
                        }
                    }
                    else
                    {
                        int num18 = rand.Next(3);
                        if (!ChildSafety.Disabled)
{
                            num18 = rand.Next(1, 3);
                        }
                        switch (num18)
{
                        case 0:
                            npcChatText = Lang.dialog(55);
                            break;
                        case 1:
                            npcChatText = Lang.dialog(56);
                            break;
                        case 2:
                            npcChatText = Lang.dialog(57);
                            break;
                        }
                    }
                }
            }
        }
        else if (npcChatFocus4)
        {
            npcChatCornerItem = 0;
            SoundEngine.PlaySound(12);
            npcChatText = player[myPlayer].currentShoppingSettings.HappinessReport;
        }
        else
        {
            if (!npcChatFocus3 || player[myPlayer].talkNPC < 0 || !NPCLoader.PreChatButtonClicked(firstButton: false))
            {
                return;
            }
            NPCLoader.OnChatButtonClicked(firstButton: false);
            if (npc[player[myPlayer].talkNPC].type == 20)
            {
                SoundEngine.PlaySound(12);
                npcChatText = Lang.GetDryadWorldStatusDialog(out var worldIsEntirelyPure);
                if (CanDryadPlayStardewAnimation(LocalPlayer, npc[player[myPlayer].talkNPC]))
                {
                    NPC.PreventJojaColaDialog = true;
                    NPC.RerollDryadText = 2;
                    LocalPlayer.ConsumeItem(5275, reverseOrder: true);
                    if (netMode == 1)
                    {
                        NetMessage.SendData(144);
                    }
                    else
                    {
                        NPC.HaveDryadDoStardewAnimation();
                    }
                    npcChatText = Language.GetTextValue("StardewTalk.PlayerGivesCola");
                }
                else if (worldIsEntirelyPure)
                {
                    AchievementsHelper.HandleSpecialEvent(player[myPlayer], 27);
                }
            }
            if (npc[player[myPlayer].talkNPC].type == 208)
            {
                SoundEngine.PlaySound(12);
                npcChatText = Language.GetTextValue("PartyGirlSpecialText.Music" + rand.Next(1, 4));
                swapMusic = !swapMusic;
            }
            else if (npc[player[myPlayer].talkNPC].type == 22)
            {
                playerInventory = true;
                npcChatText = "";
                SoundEngine.PlaySound(12);
                InGuideCraftMenu = true;
                UILinkPointNavigator.GoToDefaultPage();
            }
            else if (npc[player[myPlayer].talkNPC].type == 107)
            {
                playerInventory = true;
                npcChatText = "";
                SoundEngine.PlaySound(12);
                InReforgeMenu = true;
                UILinkPointNavigator.GoToDefaultPage();
            }
            else if (npc[player[myPlayer].talkNPC].type == 353)
            {
                OpenHairWindow();
            }
            else if (npc[player[myPlayer].talkNPC].type == 207)
            {
                npcChatCornerItem = 0;
                SoundEngine.PlaySound(12);
                bool gotDye = false;
                int num19 = player[myPlayer].FindItem(ItemID.Sets.ExoticPlantsForDyeTrade);
                if (num19 != -1)
                {
                    player[myPlayer].inventory[num19].stack--;
                    if (player[myPlayer].inventory[num19].stack <= 0)
                    {
                        player[myPlayer].inventory[num19] = new Item();
                    }
                    gotDye = true;
                    SoundEngine.PlaySound(24);
                    player[myPlayer].GetDyeTraderReward(npc[player[myPlayer].talkNPC]);
                }
                npcChatText = Lang.DyeTraderQuestChat(gotDye);
            }
            else if (npc[player[myPlayer].talkNPC].type == 550)
            {
                SoundEngine.PlaySound(12);
                HelpText();
                npcChatText = Lang.BartenderHelpText(npc[player[myPlayer].talkNPC]);
            }
            else if (npc[player[myPlayer].talkNPC].type == 227)
            {
                OpenShop(25);
            }
        }
    }
References Terraria.Main._textDisplayCache, Terraria.Entity.active, Terraria.UI.Chat.ChatManager.AddChatText(), Terraria.NPC.ai, Terraria.Main.TextDisplayCache.AmountOfLines, Terraria.Main.anglerQuest, Terraria.Lang.AnglerQuestChat(), Terraria.Main.anglerQuestFinished, Terraria.Main.anglerQuestItemNetIDs, Terraria.Player.anglerQuestsFinished, Terraria.Main.anglerWhoFinishedToday, Terraria.Lang.BartenderHelpText(), Terraria.Player.buffType, Terraria.Main.CanDryadPlayStardewAnimation(), Terraria.GameContent.TextureAssets.ChatBack, Terraria.Main.CloseNPCChatOrSign(), Terraria.Utils.CoinsSplit(), Terraria.Graphics.Light.Color, Terraria.Item.color, Terraria.Player.ConsumeItem(), Terraria.Count, Terraria.Player.currentShoppingSettings, Terraria.Main.cursorOverride, Terraria.Main.debuff, Terraria.Player.DelBuff(), Terraria.Lang.dialog(), Terraria.GameContent.ChildSafety.Disabled, Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedMechBossAny, Terraria.NPC.downedPlantBoss, Terraria.NPC.downedQueenBee, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.drawingPlayerChat, Terraria.UI.ItemSlot.DrawMoney(), Terraria.Main.DrawNPCChatButtons(), Terraria.Main.DrawWindowsIMEPanel(), Terraria.Lang.DyeTraderQuestChat(), Terraria.Main.editSign, Terraria.ID.ItemID.Sets.ExoticPlantsForDyeTrade, Terraria.Main.expertMode, Terraria.Player.FindItem(), Terraria.GameContent.UI.Chat.ItemTagHandler.GenerateTag(), Terraria.Item.GetAlpha(), Terraria.Player.GetAnglerReward(), Terraria.NPC.GetChat(), Terraria.Item.GetColor(), Terraria.Lang.GetDryadWorldStatusDialog(), Terraria.Player.GetDyeTraderReward(), Terraria.Main.GetItemDrawFrame(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage(), Terraria.GameContent.Achievements.AchievementsHelper.HandleAnglerService(), Terraria.GameContent.Achievements.AchievementsHelper.HandleNurseService(), Terraria.GameContent.Achievements.AchievementsHelper.HandleSpecialEvent(), Terraria.ShoppingSettings.HappinessReport, Terraria.Main.hardMode, Terraria.NPC.HaveDryadDoStardewAnimation(), Terraria.Player.HealEffect(), Terraria.Entity.height, Terraria.Main.HelpText(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.InGuideCraftMenu, Terraria.Main.InReforgeMenu, Terraria.Main.instance, Terraria.Lang.inter, Terraria.Player.inventory, Terraria.Main.IsItDay(), Terraria.ID.NPCID.Sets.IsTownPet, Terraria.Main.item, Terraria.ID.SoundID.Item4, Terraria.Main.LocalPlayer, Terraria.Player.maxBuffs, Terraria.ModLoader.PlayerLoader.ModifyNurseHeal(), Terraria.ModLoader.PlayerLoader.ModifyNursePrice(), Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.MouseText(), Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Item.Name, Terraria.Player.name, Terraria.Item.netDefaults(), Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.npcChatCornerItem, Terraria.Main.npcChatFocus1, Terraria.Main.npcChatFocus2, Terraria.Main.npcChatFocus3, Terraria.Main.npcChatFocus4, Terraria.Main.npcChatText, Terraria.ID.BuffID.Sets.NurseCannotRemoveDebuff, Terraria.ModLoader.NPCLoader.OnChatButtonClicked(), Terraria.Main.OpenHairWindow(), Terraria.Main.OpenPlayerChat(), Terraria.Main.OpenShop(), Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), Terraria.Player.PetAnimal(), Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.ModLoader.PlayerLoader.PostNurseHeal(), Terraria.ModLoader.NPCLoader.PreChatButtonClicked(), Terraria.Main.TextDisplayCache.PrepareCache(), Terraria.NPC.PreventJojaColaDialog, Terraria.ShoppingSettings.PriceAdjustment, Terraria.Main.rand, Terraria.Player.releaseUseItem, Terraria.NPC.RerollDryadText, Terraria.Main.screenWidth, Terraria.NetMessage.SendData(), Terraria.ModLoader.NPCLoader.SetChatButtons(), Terraria.GameInput.PlayerInput.SettingsForUI.ShowGamepadHints, Terraria.Main.sign, Terraria.NPC.SpawnSkeletron(), Terraria.Main.spriteBatch, Terraria.Item.stack, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Main.SubmitSignText(), Terraria.Main.swapMusic, Terraria.Player.talkNPC, Terraria.Player.TalkNPC, Terraria.Player.taxMoney, Terraria.Main.textBlinkerCount, Terraria.Main.textBlinkerState, Terraria.Main.TextDisplayCache.TextLines, Terraria.Main.TOWMusicUnlocked, Terraria.Item.type, Terraria.NPC.type, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.Localization.LocalizedText.Value, and Terraria.Entity.width.
Referenced by Terraria.Main.GUIChatDraw().