TModLoader: Terraria.Main.DrawProj_LightsBane
DrawProj_LightsBane()
void Terraria.Main.DrawProj_LightsBane (Projectile proj) inline private
Definition at line 32088 of file Main.cs.
    {
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0190: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0213: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0257: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0283: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02de: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_031c: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Expected O, but got Unknown
        spriteBatch.End();
        if (_multiplyBlendState == null)
        {
            _ = BlendState.AlphaBlend;
            _ = BlendState.Additive;
            _multiplyBlendState = new BlendState
            {
                ColorBlendFunction = (BlendFunction)2,
                ColorDestinationBlend = (Blend)0,
                ColorSourceBlend = (Blend)4,
                AlphaBlendFunction = (BlendFunction)2,
                AlphaDestinationBlend = (Blend)0,
                AlphaSourceBlend = (Blend)4
            };
        }
        BlendState multiplyBlendState = _multiplyBlendState;
        spriteBatch.Begin((SpriteSortMode)0, multiplyBlendState, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        Vector2 position = proj.Center - screenPosition;
        LoadProjectile(proj.type);
        Asset<Texture2D> asset = TextureAssets.Projectile[proj.type];
        Rectangle rectangle = asset.Frame(1, 13, 0, proj.frame);
        Vector2 vector = rectangle.Size() / 2f;
        Vector2 vector2 = new Vector2(0.7f, 0.7f) * proj.scale;
        float num = Utils.Remap(proj.frame, 0f, 3f, 0f, 1f) * Utils.Remap(proj.frame, 4f, 12f, 1f, 0f);
        Rectangle value = asset.Frame(1, 13, 0, 12);
        Vector2 origin = vector + new Vector2(0f, 0f);
        spriteBatch.Draw(asset.Value, position, (Rectangle?)value, Color.White * 0.3f * num, proj.rotation, origin, new Vector2(1f, 6f) * vector2, (SpriteEffects)0, 0f);
        spriteBatch.Draw(asset.Value, position, (Rectangle?)value, Color.White * 0.3f * num, proj.rotation, origin, new Vector2(2f, 2f) * vector2, (SpriteEffects)0, 0f);
        spriteBatch.Draw(asset.Value, position, (Rectangle?)rectangle, Color.White, proj.rotation, vector, vector2, (SpriteEffects)0, 0f);
        spriteBatch.Draw(asset.Value, position, (Rectangle?)rectangle, Color.White, proj.rotation, vector, vector2, (SpriteEffects)0, 0f);
        spriteBatch.Draw(asset.Value, position, (Rectangle?)rectangle, Color.White, proj.rotation, vector, vector2, (SpriteEffects)0, 0f);
        spriteBatch.Draw(asset.Value, position, (Rectangle?)rectangle, Color.White, proj.rotation, vector, vector2, (SpriteEffects)0, 0f);
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, BlendState.Additive, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        spriteBatch.Draw(asset.Value, position, (Rectangle?)rectangle, Color.Magenta, proj.rotation, vector, vector2, (SpriteEffects)0, 0f);
        spriteBatch.Draw(asset.Value, position, (Rectangle?)rectangle, Color.Magenta, proj.rotation, vector, vector2, (SpriteEffects)0, 0f);
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
    }
References Terraria.Main._multiplyBlendState, Terraria.Main.DefaultSamplerState, Terraria.Main.LoadProjectile(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.Rasterizer, Terraria.Utils.Remap(), Terraria.Main.screenPosition, Terraria.Main.spriteBatch, and Terraria.Main.Transform.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().