TModLoader: Terraria.Main.Update
Update()
override void Terraria.Main.Update (GameTime gameTime) inline protected
Definition at line 16251 of file Main.cs.
    {
        if (!IsEnginePreloaded)
        {
            IsEnginePreloaded = true;
            if (Main.OnEnginePreload != null)
            {
                Main.OnEnginePreload();
            }
        }
        if (!_isDrawingOrUpdating)
        {
            _isDrawingOrUpdating = true;
            try
            {
                DoUpdate(ref gameTime);
            }
            catch (Exception e)
            {
                Logging.Terraria.Error((object)e);
            }
            CinematicManager.Instance.Update(gameTime);
            if (netMode == 2)
            {
                for (int i = 0; i < 256; i++)
                {
                    if (Netplay.Clients[i].Socket != null)
                    {
                        Netplay.Clients[i].Socket.SendQueuedPackets();
                    }
                }
            }
            else if (netMode == 1)
            {
                Netplay.Connection.Socket.SendQueuedPackets();
            }
            _isDrawingOrUpdating = false;
        }
        ((Game)this).Update(gameTime);
        ConsumeAllMainThreadActions();
        if (GameAskedToQuit)
        {
            QuitGame();
        }
    }
References Terraria.Main._isDrawingOrUpdating, Terraria.Netplay.Clients, Terraria.Netplay.Connection, Terraria.Main.ConsumeAllMainThreadActions(), Terraria.Main.DoUpdate(), Terraria.UI.Game, Terraria.Main.GameAskedToQuit, Terraria.Cinematics.CinematicManager.Instance, Terraria.Main.IsEnginePreloaded, Terraria.Main.netMode, Terraria.Main.OnEnginePreload, Terraria.Main.QuitGame(), and Terraria.ModLoader.Logging.Terraria.