TModLoader: Terraria.Main.DrawInterface_38_MouseCarriedObject
DrawInterface_38_MouseCarriedObject()
void Terraria.Main.DrawInterface_38_MouseCarriedObject () inline private
Definition at line 58309 of file Main.cs.
    {
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_0163: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        if (mouseItem.type > 0 && mouseItem.stack > 0)
        {
            SetMouseNPC(-1, -1);
            player[myPlayer].cursorItemIconEnabled = false;
            player[myPlayer].cursorItemIconID = 0;
            mouseText = true;
            float num5 = inventoryScale;
            inventoryScale = cursorScale;
            ItemSlot.Draw(spriteBatch, ref mouseItem, 21, new Vector2((float)mouseX, (float)mouseY));
            inventoryScale = num5;
        }
        else
        {
            if (mouseNPCType <= -1)
            {
                return;
            }
            float num2 = 1f;
            num2 *= cursorScale;
            if (mouseNPCIndex >= 0)
            {
                NPC nPC = npc[mouseNPCIndex];
                if (!nPC.active || nPC.type != mouseNPCType)
                {
                    SetMouseNPC_ToHousingQuery();
                }
            }
            int type = mouseNPCType;
            int num3 = ((mouseNPCIndex >= 0) ? TownNPCProfiles.GetHeadIndexSafe(npc[mouseNPCIndex]) : NPC.TypeToDefaultHeadIndex(type));
            Texture2D value = TextureAssets.NpcHead[num3].Value;
            spriteBatch.Draw(value, new Vector2((float)mouseX + 26f * num2 - (float)value.Width * 0.5f * num2, (float)mouseY + 26f * num2 - (float)value.Height * 0.5f * num2), (Rectangle?)null, Color.White, 0f, default(Vector2), num2, (SpriteEffects)0, 0f);
            if (PlayerInput.IgnoreMouseInterface)
            {
                return;
            }
            player[myPlayer].mouseInterface = true;
            mouseText = false;
            if (mouseRight && mouseRightRelease)
            {
                SoundEngine.PlaySound(12);
                SetMouseNPC(-1, -1);
            }
            if (!mouseLeft || !mouseLeftRelease)
            {
                return;
            }
            if (mouseNPCType == 0)
            {
                PlayerInput.SetZoom_Unscaled();
                PlayerInput.SetZoom_MouseInWorld();
                int x3 = (int)(((float)mouseX + screenPosition.X) / 16f);
                int y = (int)(((float)mouseY + screenPosition.Y) / 16f);
                if (player[myPlayer].gravDir == -1f)
                {
                    y = (int)((screenPosition.Y + (float)screenHeight - (float)mouseY) / 16f);
                }
                PlayerInput.SetZoom_Unscaled();
                int i = -1;
                if (WorldGen.MoveTownNPC(x3, y, i))
                {
                    NewText(Lang.inter[39].Value, byte.MaxValue, 240, 20);
                }
                return;
            }
            int num4 = mouseNPCIndex;
            if (num4 >= 0)
            {
                PlayerInput.SetZoom_Unscaled();
                PlayerInput.SetZoom_MouseInWorld();
                int x2 = (int)(((float)mouseX + screenPosition.X) / 16f);
                int y2 = (int)(((float)mouseY + screenPosition.Y) / 16f);
                PlayerInput.SetZoom_Unscaled();
                if (WorldGen.MoveTownNPC(x2, y2, num4))
                {
                    SetMouseNPC(-1, -1);
                    WorldGen.moveRoom(x2, y2, num4);
                    SoundEngine.PlaySound(12);
                }
            }
        }
    }
References Terraria.Main.cursorScale, Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.TownNPCProfiles.GetHeadIndexSafe(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Lang.inter, Terraria.Main.inventoryScale, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseNPCIndex, Terraria.Main.mouseNPCType, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.mouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.WorldGen.moveRoom(), Terraria.WorldGen.MoveTownNPC(), Terraria.Main.myPlayer, Terraria.Main.NewText(), Terraria.Main.npc, Terraria.GameContent.TextureAssets.NpcHead, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.SetMouseNPC(), Terraria.Main.SetMouseNPC_ToHousingQuery(), Terraria.GameInput.PlayerInput.SetZoom_MouseInWorld(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.Main.spriteBatch, and Terraria.NPC.TypeToDefaultHeadIndex().
Referenced by Terraria.Main.SetupDrawInterfaceLayers().