TModLoader: Terraria.Main.MouseText_DrawBuffTooltip
MouseText_DrawBuffTooltip()
void Terraria.Main.MouseText_DrawBuffTooltip (string buffString, ref int X, ref int Y, int buffNameHeight) inline private
    {
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0168: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0195: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0345: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03da: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        Point p = default(Point);
        ((Point)(ref p))._002Ector(X, Y);
        int num = 220;
        int num8 = 72;
        int num9 = -1;
        float num10 = 1f;
        List<Vector2> list = new List<Vector2>();
        Vector2 vector = ChatManager.GetStringSize(FontAssets.MouseText.Value, buffString, Vector2.One);
        list.Add(vector);
        int num11 = (int)((float)(screenHeight - Y - 24 - num8) * num10) / 20;
        if (num11 < 1)
        {
            num11 = 1;
        }
        if (bannerMouseOver)
        {
            int num12 = 0;
            for (int i = 0; i < NPCLoader.NPCCount; i++)
            {
                if (Item.BannerToNPC(i) != 0 && player[myPlayer].HasNPCBannerBuff(i))
                {
                    num12++;
                    string nPCNameValue = Lang.GetNPCNameValue(Item.BannerToNPC(i));
                    Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(nPCNameValue);
                    int num13 = X;
                    int num14 = Y + (int)vector2.Y + num12 * 20 + 10;
                    int num15 = 0;
                    int num2 = num12 / num11;
                    for (int j = 0; j < num2; j++)
                    {
                        num15++;
                        num13 += num;
                        num14 -= num11 * 20;
                    }
                    if ((float)(num13 - 24 - num) > (float)screenWidth * num10)
                    {
                        num9 = num12;
                        break;
                    }
                    list.Add(new Vector2((float)num13, (float)num14) + vector2 - p.ToVector2());
                }
            }
        }
        BuffLoader.CustomBuffTipSize(buffString, list);
        Vector2 zero = Vector2.Zero;
        foreach (Vector2 item in list)
        {
            if (zero.X < item.X)
            {
                zero.X = item.X;
            }
            if (zero.Y < item.Y)
            {
                zero.Y = item.Y;
            }
        }
        if ((float)X + zero.X + 24f > (float)screenWidth * num10)
        {
            X = (int)((float)screenWidth * num10 - zero.X - 24f);
        }
        if ((float)Y + zero.Y + 4f > (float)screenHeight * num10)
        {
            Y = (int)((float)screenHeight * num10 - zero.Y - 4f);
        }
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, 255);
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, buffString, new Vector2((float)X, (float)(Y + buffNameHeight)), color, 0f, Vector2.Zero, Vector2.One);
        if (!bannerMouseOver)
        {
            return;
        }
        int num3 = 0;
        for (int k = 0; k < NPCLoader.NPCCount; k++)
        {
            if (Item.BannerToNPC(k) == 0 || !player[myPlayer].HasNPCBannerBuff(k))
            {
                continue;
            }
            num3++;
            bool flag = false;
            for (int l = 0; l < 5; l++)
            {
                int num4 = X;
                int num5 = Y + (int)vector.Y + num3 * 20 + 10;
                int num6 = (num3 - 1) / num11;
                num4 += num * num6;
                num5 -= num11 * 20 * num6;
                string text = Lang.GetNPCNameValue(Item.BannerToNPC(k));
                if (num9 == num3)
                {
                    text = Language.GetTextValue("UI.Ellipsis");
                    flag = true;
                }
                Color color2 = Color.Black;
                switch (l)
                {
                case 0:
                    num4 -= 2;
                    break;
                case 1:
                    num4 += 2;
                    break;
                case 2:
                    num5 -= 2;
                    break;
                case 3:
                    num5 += 2;
                    break;
                default:
                {
                    float num7 = (float)(int)mouseTextColor / 255f;
                    ((Color)(ref color2))._002Ector((int)(byte)(80f * num7), (int)(byte)(255f * num7), (int)(byte)(120f * num7), (int)mouseTextColor);
                    break;
                }
                }
                spriteBatch.DrawString(FontAssets.MouseText.Value, text, new Vector2((float)num4, (float)num5), color2, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (flag)
            {
                break;
            }
        }
        BuffLoader.DrawCustomBuffTip(buffString, spriteBatch, X, Y + (int)FontAssets.MouseText.Value.MeasureString(buffString).Y);
    }
References Terraria.Main.bannerMouseOver, Terraria.Item.BannerToNPC(), Terraria.Main.buffString, Terraria.Graphics.Light.Color, Terraria.ModLoader.BuffLoader.CustomBuffTipSize(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.ModLoader.BuffLoader.DrawCustomBuffTip(), Terraria.Lang.GetNPCNameValue(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Localization.Language.GetTextValue(), Terraria.Player.HasNPCBannerBuff(), Terraria.Main.item, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.ModLoader.NPCLoader.NPCCount, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenWidth, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.MouseTextInner().