TModLoader: Terraria.Main.SetBackColor
SetBackColor()
static void Terraria.Main.SetBackColor (InfoToSetBackColor info, out Color sunColor, out Color moonColor) inline static private
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fee: Unknown result type (might be due to invalid IL or missing references)
        double num = time;
        Color bgColorToSet = Color.White;
        sunColor = Color.White;
        moonColor = Color.White;
        float num7 = 0f;
        bool isInGameMenuOrIsServer = info.isInGameMenuOrIsServer;
        if (dayTime)
        {
            if (num < 13500.0)
            {
                num7 = (float)(num / 13500.0);
                ((Color)(ref sunColor)).R = (byte)(num7 * 200f + 55f);
                ((Color)(ref sunColor)).G = (byte)(num7 * 180f + 75f);
                ((Color)(ref sunColor)).B = (byte)(num7 * 250f + 5f);
                ((Color)(ref bgColorToSet)).R = (byte)(num7 * 230f + 25f);
                ((Color)(ref bgColorToSet)).G = (byte)(num7 * 220f + 35f);
                ((Color)(ref bgColorToSet)).B = (byte)(num7 * 220f + 35f);
            }
            if (num > 45900.0)
            {
                num7 = (float)(1.0 - (num / 54000.0 - 0.85) * 6.666666666666667);
                ((Color)(ref sunColor)).R = (byte)(num7 * 120f + 55f);
                ((Color)(ref sunColor)).G = (byte)(num7 * 100f + 25f);
                ((Color)(ref sunColor)).B = (byte)(num7 * 120f + 55f);
                ((Color)(ref bgColorToSet)).R = (byte)(num7 * 200f + 35f);
                ((Color)(ref bgColorToSet)).G = (byte)(num7 * 85f + 35f);
                ((Color)(ref bgColorToSet)).B = (byte)(num7 * 135f + 35f);
            }
            else if (num > 37800.0)
            {
                num7 = (float)(1.0 - (num / 54000.0 - 0.7) * 6.666666666666667);
                ((Color)(ref sunColor)).R = (byte)(num7 * 80f + 175f);
                ((Color)(ref sunColor)).G = (byte)(num7 * 130f + 125f);
                ((Color)(ref sunColor)).B = (byte)(num7 * 100f + 155f);
                ((Color)(ref bgColorToSet)).R = (byte)(num7 * 20f + 235f);
                ((Color)(ref bgColorToSet)).G = (byte)(num7 * 135f + 120f);
                ((Color)(ref bgColorToSet)).B = (byte)(num7 * 85f + 170f);
            }
        }
        if (!dayTime)
        {
            if (info.BloodMoonActive)
            {
                if (num < 16200.0)
                {
                    num7 = (float)(1.0 - num / 16200.0);
                    ((Color)(ref moonColor)).R = (byte)(num7 * 10f + 205f);
                    ((Color)(ref moonColor)).G = (byte)(num7 * 170f + 55f);
                    ((Color)(ref moonColor)).B = (byte)(num7 * 200f + 55f);
                    ((Color)(ref bgColorToSet)).R = (byte)(40f - num7 * 40f + 35f);
                    ((Color)(ref bgColorToSet)).G = (byte)(num7 * 20f + 15f);
                    ((Color)(ref bgColorToSet)).B = (byte)(num7 * 20f + 15f);
                }
                else if (num >= 16200.0)
                {
                    num7 = (float)((num / 32400.0 - 0.5) * 2.0);
                    ((Color)(ref moonColor)).R = (byte)(num7 * 50f + 205f);
                    ((Color)(ref moonColor)).G = (byte)(num7 * 100f + 155f);
                    ((Color)(ref moonColor)).B = (byte)(num7 * 100f + 155f);
                    ((Color)(ref moonColor)).R = (byte)(num7 * 10f + 205f);
                    ((Color)(ref moonColor)).G = (byte)(num7 * 170f + 55f);
                    ((Color)(ref moonColor)).B = (byte)(num7 * 200f + 55f);
                    ((Color)(ref bgColorToSet)).R = (byte)(40f - num7 * 40f + 35f);
                    ((Color)(ref bgColorToSet)).G = (byte)(num7 * 20f + 15f);
                    ((Color)(ref bgColorToSet)).B = (byte)(num7 * 20f + 15f);
                }
            }
            else if (num < 16200.0)
            {
                num7 = (float)(1.0 - num / 16200.0);
                ((Color)(ref moonColor)).R = (byte)(num7 * 10f + 205f);
                ((Color)(ref moonColor)).G = (byte)(num7 * 70f + 155f);
                ((Color)(ref moonColor)).B = (byte)(num7 * 100f + 155f);
                ((Color)(ref bgColorToSet)).R = (byte)(num7 * 30f + 5f);
                ((Color)(ref bgColorToSet)).G = (byte)(num7 * 30f + 5f);
                ((Color)(ref bgColorToSet)).B = (byte)(num7 * 30f + 5f);
            }
            else if (num >= 16200.0)
            {
                num7 = (float)((num / 32400.0 - 0.5) * 2.0);
                ((Color)(ref moonColor)).R = (byte)(num7 * 50f + 205f);
                ((Color)(ref moonColor)).G = (byte)(num7 * 100f + 155f);
                ((Color)(ref moonColor)).B = (byte)(num7 * 100f + 155f);
                ((Color)(ref bgColorToSet)).R = (byte)(num7 * 20f + 5f);
                ((Color)(ref bgColorToSet)).G = (byte)(num7 * 30f + 5f);
                ((Color)(ref bgColorToSet)).B = (byte)(num7 * 30f + 5f);
            }
            if (dontStarveWorld)
            {
                DontStarveSeed.ModifyNightColor(ref bgColorToSet, ref moonColor);
            }
        }
        if (cloudAlpha > 0f && !remixWorld)
        {
            float num8 = 1f - cloudAlpha * 0.9f * atmo;
            ((Color)(ref bgColorToSet)).R = (byte)((float)(int)((Color)(ref bgColorToSet)).R * num8);
            ((Color)(ref bgColorToSet)).G = (byte)((float)(int)((Color)(ref bgColorToSet)).G * num8);
            ((Color)(ref bgColorToSet)).B = (byte)((float)(int)((Color)(ref bgColorToSet)).B * num8);
        }
        if (info.GraveyardInfluence > 0f && !remixWorld)
        {
            float num9 = 1f - info.GraveyardInfluence * 0.6f;
            ((Color)(ref bgColorToSet)).R = (byte)((float)(int)((Color)(ref bgColorToSet)).R * num9);
            ((Color)(ref bgColorToSet)).G = (byte)((float)(int)((Color)(ref bgColorToSet)).G * num9);
            ((Color)(ref bgColorToSet)).B = (byte)((float)(int)((Color)(ref bgColorToSet)).B * num9);
        }
        if (isInGameMenuOrIsServer && !dayTime)
        {
            ((Color)(ref bgColorToSet)).R = 35;
            ((Color)(ref bgColorToSet)).G = 35;
            ((Color)(ref bgColorToSet)).B = 35;
        }
        if (info.CorruptionBiomeInfluence > 0f)
        {
            float num10 = info.CorruptionBiomeInfluence;
            if (num10 > 1f)
            {
                num10 = 1f;
            }
            int r = ((Color)(ref bgColorToSet)).R;
            int g = ((Color)(ref bgColorToSet)).G;
            int b = ((Color)(ref bgColorToSet)).B;
            r -= (int)(90f * num10 * ((float)(int)((Color)(ref bgColorToSet)).R / 255f));
            g -= (int)(140f * num10 * ((float)(int)((Color)(ref bgColorToSet)).G / 255f));
            b -= (int)(70f * num10 * ((float)(int)((Color)(ref bgColorToSet)).B / 255f));
            if (r < 15)
            {
                r = 15;
            }
            if (g < 15)
            {
                g = 15;
            }
            if (b < 15)
            {
                b = 15;
            }
            DontStarveSeed.FixBiomeDarkness(ref bgColorToSet, ref r, ref g, ref b);
            ((Color)(ref bgColorToSet)).R = (byte)r;
            ((Color)(ref bgColorToSet)).G = (byte)g;
            ((Color)(ref bgColorToSet)).B = (byte)b;
            r = ((Color)(ref sunColor)).R;
            g = ((Color)(ref sunColor)).G;
            b = ((Color)(ref sunColor)).B;
            r -= (int)(100f * num10 * ((float)(int)((Color)(ref sunColor)).R / 255f));
            g -= (int)(100f * num10 * ((float)(int)((Color)(ref sunColor)).G / 255f));
            b -= (int)(0f * num10 * ((float)(int)((Color)(ref sunColor)).B / 255f));
            if (r < 15)
            {
                r = 15;
            }
            if (g < 15)
            {
                g = 15;
            }
            if (b < 15)
            {
                b = 15;
            }
            ((Color)(ref sunColor)).R = (byte)r;
            ((Color)(ref sunColor)).G = (byte)g;
            ((Color)(ref sunColor)).B = (byte)b;
        }
        if (info.CrimsonBiomeInfluence > 0f)
        {
            float num11 = info.CrimsonBiomeInfluence;
            if (num11 > 1f)
            {
                num11 = 1f;
            }
            int r2 = ((Color)(ref bgColorToSet)).R;
            int g2 = ((Color)(ref bgColorToSet)).G;
            int b2 = ((Color)(ref bgColorToSet)).B;
            r2 -= (int)(40f * num11 * ((float)(int)((Color)(ref bgColorToSet)).G / 255f));
            g2 -= (int)(110f * num11 * ((float)(int)((Color)(ref bgColorToSet)).G / 255f));
            b2 -= (int)(140f * num11 * ((float)(int)((Color)(ref bgColorToSet)).B / 255f));
            if (r2 < 15)
            {
                r2 = 15;
            }
            if (g2 < 15)
            {
                g2 = 15;
            }
            if (b2 < 15)
            {
                b2 = 15;
            }
            DontStarveSeed.FixBiomeDarkness(ref bgColorToSet, ref r2, ref g2, ref b2);
            ((Color)(ref bgColorToSet)).R = (byte)r2;
            ((Color)(ref bgColorToSet)).G = (byte)g2;
            ((Color)(ref bgColorToSet)).B = (byte)b2;
            r2 = ((Color)(ref sunColor)).R;
            g2 = ((Color)(ref sunColor)).G;
            b2 = ((Color)(ref sunColor)).B;
            g2 -= (int)(90f * num11 * ((float)(int)((Color)(ref sunColor)).G / 255f));
            b2 -= (int)(110f * num11 * ((float)(int)((Color)(ref sunColor)).B / 255f));
            if (r2 < 15)
            {
                r2 = 15;
            }
            if (g2 < 15)
            {
                g2 = 15;
            }
            if (b2 < 15)
            {
                b2 = 15;
            }
            ((Color)(ref sunColor)).R = (byte)r2;
            ((Color)(ref sunColor)).G = (byte)g2;
            ((Color)(ref sunColor)).B = (byte)b2;
        }
        if (info.JungleBiomeInfluence > 0f)
        {
            float num12 = info.JungleBiomeInfluence;
            if (num12 > 1f)
            {
                num12 = 1f;
            }
            int r3 = ((Color)(ref bgColorToSet)).R;
            int G = ((Color)(ref bgColorToSet)).G;
            int b3 = ((Color)(ref bgColorToSet)).B;
            r3 -= (int)(40f * num12 * ((float)(int)((Color)(ref bgColorToSet)).R / 255f));
            b3 -= (int)(70f * num12 * ((float)(int)((Color)(ref bgColorToSet)).B / 255f));
            if (G > 255)
            {
                G = 255;
            }
            if (G < 15)
            {
                G = 15;
            }
            if (r3 > 255)
            {
                r3 = 255;
            }
            if (r3 < 15)
            {
                r3 = 15;
            }
            if (b3 < 15)
            {
                b3 = 15;
            }
            DontStarveSeed.FixBiomeDarkness(ref bgColorToSet, ref r3, ref G, ref b3);
            ((Color)(ref bgColorToSet)).R = (byte)r3;
            ((Color)(ref bgColorToSet)).G = (byte)G;
            ((Color)(ref bgColorToSet)).B = (byte)b3;
            r3 = ((Color)(ref sunColor)).R;
            G = ((Color)(ref sunColor)).G;
            b3 = ((Color)(ref sunColor)).B;
            r3 -= (int)(30f * num12 * ((float)(int)((Color)(ref sunColor)).R / 255f));
            b3 -= (int)(10f * num12 * ((float)(int)((Color)(ref sunColor)).B / 255f));
            if (r3 < 15)
            {
                r3 = 15;
            }
            if (G < 15)
            {
                G = 15;
            }
            if (b3 < 15)
            {
                b3 = 15;
            }
            ((Color)(ref sunColor)).R = (byte)r3;
            ((Color)(ref sunColor)).G = (byte)G;
            ((Color)(ref sunColor)).B = (byte)b3;
        }
        if (info.MushroomBiomeInfluence > 0f)
        {
            float mushroomBiomeInfluence = info.MushroomBiomeInfluence;
            int r4 = ((Color)(ref bgColorToSet)).R;
            int g3 = ((Color)(ref bgColorToSet)).G;
            int b4 = ((Color)(ref bgColorToSet)).B;
            g3 -= (int)(250f * mushroomBiomeInfluence * ((float)(int)((Color)(ref bgColorToSet)).G / 255f));
            r4 -= (int)(250f * mushroomBiomeInfluence * ((float)(int)((Color)(ref bgColorToSet)).R / 255f));
            b4 -= (int)(250f * mushroomBiomeInfluence * ((float)(int)((Color)(ref bgColorToSet)).B / 255f));
            if (g3 < 15)
            {
                g3 = 15;
            }
            if (r4 < 15)
            {
                r4 = 15;
            }
            if (b4 < 15)
            {
                b4 = 15;
            }
            DontStarveSeed.FixBiomeDarkness(ref bgColorToSet, ref r4, ref g3, ref b4);
            ((Color)(ref bgColorToSet)).R = (byte)r4;
            ((Color)(ref bgColorToSet)).G = (byte)g3;
            ((Color)(ref bgColorToSet)).B = (byte)b4;
            r4 = ((Color)(ref sunColor)).R;
            g3 = ((Color)(ref sunColor)).G;
            b4 = ((Color)(ref sunColor)).B;
            g3 -= (int)(10f * mushroomBiomeInfluence * ((float)(int)((Color)(ref sunColor)).G / 255f));
            r4 -= (int)(30f * mushroomBiomeInfluence * ((float)(int)((Color)(ref sunColor)).R / 255f));
            b4 -= (int)(10f * mushroomBiomeInfluence * ((float)(int)((Color)(ref sunColor)).B / 255f));
            if (r4 < 15)
            {
                r4 = 15;
            }
            if (g3 < 15)
            {
                g3 = 15;
            }
            if (b4 < 15)
            {
                b4 = 15;
            }
            ((Color)(ref sunColor)).R = (byte)r4;
            ((Color)(ref sunColor)).G = (byte)g3;
            ((Color)(ref sunColor)).B = (byte)b4;
            r4 = ((Color)(ref moonColor)).R;
            g3 = ((Color)(ref moonColor)).G;
            b4 = ((Color)(ref moonColor)).B;
            g3 -= (int)(140f * mushroomBiomeInfluence * ((float)(int)((Color)(ref moonColor)).R / 255f));
            r4 -= (int)(170f * mushroomBiomeInfluence * ((float)(int)((Color)(ref moonColor)).G / 255f));
            b4 -= (int)(190f * mushroomBiomeInfluence * ((float)(int)((Color)(ref moonColor)).B / 255f));
            if (r4 < 15)
            {
                r4 = 15;
            }
            if (g3 < 15)
            {
                g3 = 15;
            }
            if (b4 < 15)
            {
                b4 = 15;
            }
            ((Color)(ref moonColor)).R = (byte)r4;
            ((Color)(ref moonColor)).G = (byte)g3;
            ((Color)(ref moonColor)).B = (byte)b4;
        }
        byte minimalLight = 15;
        switch (GetMoonPhase())
        {
        case MoonPhase.Empty:
            minimalLight = 11;
            break;
        case MoonPhase.QuarterAtLeft:
        case MoonPhase.QuarterAtRight:
            minimalLight = 13;
            break;
        case MoonPhase.HalfAtLeft:
        case MoonPhase.HalfAtRight:
            minimalLight = 15;
            break;
        case MoonPhase.ThreeQuartersAtLeft:
        case MoonPhase.ThreeQuartersAtRight:
            minimalLight = 17;
            break;
        case MoonPhase.Full:
            minimalLight = 19;
            break;
        }
        if (dontStarveWorld)
        {
            DontStarveSeed.ModifyMinimumLightColorAtNight(ref minimalLight);
        }
        if (((Color)(ref bgColorToSet)).R < minimalLight)
        {
            ((Color)(ref bgColorToSet)).R = minimalLight;
        }
        if (((Color)(ref bgColorToSet)).G < minimalLight)
        {
            ((Color)(ref bgColorToSet)).G = minimalLight;
        }
        if (((Color)(ref bgColorToSet)).B < minimalLight)
        {
            ((Color)(ref bgColorToSet)).B = minimalLight;
        }
        if (info.BloodMoonActive)
        {
            if (((Color)(ref bgColorToSet)).R < 25)
            {
                ((Color)(ref bgColorToSet)).R = 25;
            }
            if (((Color)(ref bgColorToSet)).G < 25)
            {
                ((Color)(ref bgColorToSet)).G = 25;
            }
            if (((Color)(ref bgColorToSet)).B < 25)
            {
                ((Color)(ref bgColorToSet)).B = 25;
            }
        }
        if (eclipse && dayTime)
        {
            float num13 = 1242f;
            eclipseLight = (float)(num / (double)num13);
            if (eclipseLight > 1f)
            {
                eclipseLight = 1f;
            }
        }
        else if (eclipseLight > 0f)
        {
            eclipseLight -= 0.01f;
            if (eclipseLight < 0f)
            {
                eclipseLight = 0f;
            }
        }
        if (eclipseLight > 0f)
        {
            float num14 = 1f - 0.925f * eclipseLight;
            float num2 = 1f - 0.96f * eclipseLight;
            float num3 = 1f - 1f * eclipseLight;
            int num4 = (int)((float)(int)((Color)(ref bgColorToSet)).R * num14);
            int num5 = (int)((float)(int)((Color)(ref bgColorToSet)).G * num2);
            int num6 = (int)((float)(int)((Color)(ref bgColorToSet)).B * num3);
            ((Color)(ref bgColorToSet)).R = (byte)num4;
            ((Color)(ref bgColorToSet)).G = (byte)num5;
            ((Color)(ref bgColorToSet)).B = (byte)num6;
            ((Color)(ref sunColor)).R = byte.MaxValue;
            ((Color)(ref sunColor)).G = 127;
            ((Color)(ref sunColor)).B = 67;
            if (((Color)(ref bgColorToSet)).R < 20)
            {
                ((Color)(ref bgColorToSet)).R = 20;
            }
            if (((Color)(ref bgColorToSet)).G < 10)
            {
                ((Color)(ref bgColorToSet)).G = 10;
            }
            if (!Lighting.NotRetro)
            {
                if (((Color)(ref bgColorToSet)).R < 20)
                {
                    ((Color)(ref bgColorToSet)).R = 20;
                }
                if (((Color)(ref bgColorToSet)).G < 14)
                {
                    ((Color)(ref bgColorToSet)).G = 14;
                }
                if (((Color)(ref bgColorToSet)).B < 6)
                {
                    ((Color)(ref bgColorToSet)).B = 6;
                }
            }
        }
        if ((remixWorld && !gameMenu) || WorldGen.remixWorldGen)
        {
            ((Color)(ref bgColorToSet)).R = 1;
            ((Color)(ref bgColorToSet)).G = 1;
            ((Color)(ref bgColorToSet)).B = 1;
        }
        if (lightning > 0f)
        {
            float value = (float)(int)((Color)(ref bgColorToSet)).R / 255f;
            float value2 = (float)(int)((Color)(ref bgColorToSet)).G / 255f;
            float value3 = (float)(int)((Color)(ref bgColorToSet)).B / 255f;
            value = MathHelper.Lerp(value, 1f, lightning);
            value2 = MathHelper.Lerp(value2, 1f, lightning);
            value3 = MathHelper.Lerp(value3, 1f, lightning);
            ((Color)(ref bgColorToSet)).R = (byte)(value * 255f);
            ((Color)(ref bgColorToSet)).G = (byte)(value2 * 255f);
            ((Color)(ref bgColorToSet)).B = (byte)(value3 * 255f);
        }
        if (!info.BloodMoonActive)
        {
            moonColor = Color.White;
        }
        ColorOfTheSkies = bgColorToSet;
    }
References Terraria.Main.atmo, Terraria.Main.cloudAlpha, Terraria.Graphics.Light.Color, Terraria.Main.ColorOfTheSkies, Terraria.Main.dayTime, Terraria.Main.dontStarveWorld, Terraria.Main.eclipse, Terraria.Main.eclipseLight, Terraria.GameContent.DontStarveSeed.FixBiomeDarkness(), Terraria.Main.gameMenu, Terraria.Main.GetMoonPhase(), Terraria.Main.lightning, Terraria.GameContent.DontStarveSeed.ModifyMinimumLightColorAtNight(), Terraria.GameContent.DontStarveSeed.ModifyNightColor(), Terraria.Lighting.NotRetro, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, and Terraria.Main.time.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().