TModLoader: Terraria.Main.NPCAddHeight
NPCAddHeight()
static float Terraria.Main.NPCAddHeight (NPC theNPC) inline static
    {
        float num = 0f;
        if (theNPC.type == 125)
        {
            num = 30f;
        }
        else if (theNPC.ModNPC != null)
        {
            num = theNPC.ModNPC.DrawOffsetY;
        }
        else if (theNPC.type == 54)
        {
            num = 2f;
        }
        else if (theNPC.type == 205)
        {
            num = 8f;
        }
        else if (theNPC.type == 182)
        {
            num = 24f;
        }
        else if (theNPC.type == 178)
        {
            num = 2f;
        }
        else if (theNPC.type == 126)
        {
            num = 30f;
        }
        else if (theNPC.type == 6 || theNPC.type == 173)
        {
            num = 26f;
        }
        else if (theNPC.type == 94)
        {
            num = 14f;
        }
        else if (theNPC.type == 7 || theNPC.type == 8 || theNPC.type == 9)
        {
            num = 13f;
        }
        else if (theNPC.type == 98 || theNPC.type == 99 || theNPC.type == 100)
        {
            num = 13f;
        }
        else if (theNPC.type == 95 || theNPC.type == 96 || theNPC.type == 97)
        {
            num = 13f;
        }
        else if (theNPC.type == 10 || theNPC.type == 11 || theNPC.type == 12)
        {
            num = 8f;
        }
        else if (theNPC.type == 13 || theNPC.type == 14 || theNPC.type == 15)
        {
            num = 26f;
        }
        else if (theNPC.type == 175)
        {
            num = 4f;
        }
        else if (theNPC.type == 520)
        {
            num = 2f;
        }
        else if (theNPC.type >= 412 && theNPC.type <= 414)
        {
            num = 18f;
        }
        else if (theNPC.type == 48)
        {
            num = 32f;
        }
        else if (theNPC.type == 49 || theNPC.type == 51)
        {
            num = 4f;
        }
        else if (theNPC.type == 60)
        {
            num = 10f;
        }
        else if (theNPC.type == 62 || theNPC.type == 66 || theNPC.type == 156)
        {
            num = 14f;
        }
        else if (theNPC.type == 63 || theNPC.type == 64 || theNPC.type == 103)
        {
            num = 4f;
        }
        else if (theNPC.type == 65)
        {
            num = 5f;
        }
        else if (theNPC.type == 69)
        {
            num = 4f;
        }
        else if (theNPC.type == 70)
        {
            num = -4f;
        }
        else if (theNPC.type == 72)
        {
            num = -2f;
        }
        else if (theNPC.type == 83 || theNPC.type == 84)
        {
            num = 20f;
        }
        else if (theNPC.type == 150 || theNPC.type == 151 || theNPC.type == 158)
        {
            num = 10f;
        }
        else if (theNPC.type == 152)
        {
            num = 6f;
        }
        else if (theNPC.type == 153 || theNPC.type == 154)
        {
            num = 2f;
        }
        else if (theNPC.type == 165 || theNPC.type == 237 || theNPC.type == 238 || theNPC.type == 240 || theNPC.type == 531)
        {
            num = 10f;
        }
        else if (theNPC.type == 39 || theNPC.type == 40 || theNPC.type == 41)
        {
            num = 26f;
        }
        else if (theNPC.type >= 87 && theNPC.type <= 92)
        {
            num = 56f;
        }
        else if (theNPC.type >= 134 && theNPC.type <= 136)
        {
            num = 30f;
        }
        else if (theNPC.type == 169)
        {
            num = 8f;
        }
        else if (theNPC.type == 174)
        {
            num = 6f;
        }
        else if (theNPC.type == 369)
        {
            num = 2f;
        }
        else if (theNPC.type == 376)
        {
            num = 6f;
        }
        else if (theNPC.type == 579)
        {
            num = -2f;
        }
        else if (theNPC.type == 613 || theNPC.type == 612)
        {
            num = 2f;
        }
        switch (theNPC.type)
        {
        case 269:
        case 270:
        case 271:
        case 274:
        case 277:
            num -= 2f;
            break;
        }
        if (theNPC.townNPC && theNPC.ai[0] == 5f)
        {
            num -= 4f;
            if (theNPC.type == 637 || theNPC.type == 656 || NPCID.Sets.IsTownSlime[theNPC.type])
            {
                num -= 10f;
            }
        }
        if (theNPC.type == 671 || theNPC.type == 672 || theNPC.type == 673 || theNPC.type == 674 || theNPC.type == 675)
        {
            num += 10f;
        }
        return num * theNPC.scale;
    }
References Terraria.ID.NPCID.Sets.IsTownSlime.
Referenced by Terraria.ModLoader.NPCLoader.DrawHealthBar(), Terraria.Main.DrawInterface_14_EntityHealthBars(), and Terraria.Main.DrawNPCDirect_Inner().