TModLoader: Terraria.Main.MouseText_DrawItemTooltip
MouseText_DrawItemTooltip()
void Terraria.Main.MouseText_DrawItemTooltip (MouseTextCache info, int rare, byte diff, int X, int Y) inline private
Definition at line 19655 of file Main.cs.
    {
        //IL_055b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0560: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05da: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0662: Unknown result type (might be due to invalid IL or missing references)
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_0676: Unknown result type (might be due to invalid IL or missing references)
        //IL_069c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0706: Unknown result type (might be due to invalid IL or missing references)
        //IL_0716: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_0937: Unknown result type (might be due to invalid IL or missing references)
        //IL_093c: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07be: Unknown result type (might be due to invalid IL or missing references)
        //IL_07d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cb6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d17: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d53: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e23: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e52: Unknown result type (might be due to invalid IL or missing references)
        //IL_089a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0891: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0baa: Unknown result type (might be due to invalid IL or missing references)
        bool settingsEnabled_OpaqueBoxBehindTooltips = SettingsEnabled_OpaqueBoxBehindTooltips;
        Color color = default(Color);
        ((Color)(ref color))._002Ector((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor);
        Item hoverItem = HoverItem;
        int yoyoLogo = -1;
        int researchLine = -1;
        rare = hoverItem.rare;
        float knockBack = hoverItem.knockBack;
        float num = 1f;
        if (hoverItem.melee && player[myPlayer].kbGlove)
        {
            num += 1f;
        }
        if (player[myPlayer].kbBuff)
        {
            num += 0.5f;
        }
        if (num != 1f)
        {
            hoverItem.knockBack *= num;
        }
        if (hoverItem.ranged && player[myPlayer].shroomiteStealth)
        {
            hoverItem.knockBack *= 1f + (1f - player[myPlayer].stealth) * 0.5f;
        }
        int num12 = 30;
        int numLines = 1;
        string[] array = new string[num12];
        bool[] array2 = new bool[num12];
        bool[] array3 = new bool[num12];
        for (int j = 0; j < num12; j++)
        {
            array2[j] = false;
            array3[j] = false;
        }
        string[] tooltipNames = new string[num12];
        MouseText_DrawItemTooltip_GetLinesInfo(hoverItem, ref yoyoLogo, ref researchLine, knockBack, ref numLines, array, array2, array3, tooltipNames, out var prefixlineIndex);
        float num16 = (float)(int)mouseTextColor / 255f;
        float num17 = num16;
        int a = mouseTextColor;
        if (npcShop > 0 && hoverItem.value >= 0 && (hoverItem.type < 71 || hoverItem.type > 74))
        {
            LocalPlayer.GetItemExpectedPrice(hoverItem, out var calcForSelling, out var calcForBuying);
            long num18 = ((hoverItem.isAShopItem || hoverItem.buyOnce) ? calcForBuying : calcForSelling);
            if (hoverItem.shopSpecialCurrency != -1)
            {
                tooltipNames[numLines] = "SpecialPrice";
                CustomCurrencyManager.GetPriceText(hoverItem.shopSpecialCurrency, array, ref numLines, num18);
                ((Color)(ref color))._002Ector((int)(byte)(255f * num17), (int)(byte)(255f * num17), (int)(byte)(255f * num17), a);
            }
            else if (num18 > 0)
            {
                string text = "";
                long num19 = 0L;
                long num20 = 0L;
                long num21 = 0L;
                long num22 = 0L;
                long num2 = num18 * hoverItem.stack;
                if (!hoverItem.buy)
                {
                    num2 = num18 / 5;
                    if (num2 < 1)
                    {
                        num2 = 1L;
                    }
                    long num3 = num2;
                    num2 *= hoverItem.stack;
                    int amount = shopSellbackHelper.GetAmount(hoverItem);
                    if (amount > 0)
                    {
                        num2 += (-num3 + calcForBuying) * Math.Min(amount, hoverItem.stack);
                    }
                }
                if (num2 < 1)
                {
                    num2 = 1L;
                }
                if (num2 >= 1000000)
                {
                    num19 = num2 / 1000000;
                    num2 -= num19 * 1000000;
                }
                if (num2 >= 10000)
                {
                    num20 = num2 / 10000;
                    num2 -= num20 * 10000;
                }
                if (num2 >= 100)
                {
                    num21 = num2 / 100;
                    num2 -= num21 * 100;
                }
                if (num2 >= 1)
                {
                    num22 = num2;
                }
                if (num19 > 0)
                {
                    text = text + num19 + " " + Lang.inter[15].Value + " ";
                }
                if (num20 > 0)
                {
                    text = text + num20 + " " + Lang.inter[16].Value + " ";
                }
                if (num21 > 0)
                {
                    text = text + num21 + " " + Lang.inter[17].Value + " ";
                }
                if (num22 > 0)
                {
                    text = text + num22 + " " + Lang.inter[18].Value + " ";
                }
                if (!hoverItem.buy)
                {
                    array[numLines] = Lang.tip[49].Value + " " + text;
                }
                else
                {
                    array[numLines] = Lang.tip[50].Value + " " + text;
                }
                tooltipNames[numLines] = "Price";
                numLines++;
                if (num19 > 0)
                {
                    ((Color)(ref color))._002Ector((int)(byte)(220f * num17), (int)(byte)(220f * num17), (int)(byte)(198f * num17), a);
                }
                else if (num20 > 0)
                {
                    ((Color)(ref color))._002Ector((int)(byte)(224f * num17), (int)(byte)(201f * num17), (int)(byte)(92f * num17), a);
                }
                else if (num21 > 0)
                {
                    ((Color)(ref color))._002Ector((int)(byte)(181f * num17), (int)(byte)(192f * num17), (int)(byte)(193f * num17), a);
                }
                else if (num22 > 0)
                {
                    ((Color)(ref color))._002Ector((int)(byte)(246f * num17), (int)(byte)(138f * num17), (int)(byte)(96f * num17), a);
                }
            }
            else if (hoverItem.type != 3817)
            {
                array[numLines] = Lang.tip[51].Value;
                tooltipNames[numLines] = "Price";
                numLines++;
                ((Color)(ref color))._002Ector((int)(byte)(120f * num17), (int)(byte)(120f * num17), (int)(byte)(120f * num17), a);
            }
        }
        Vector2 zero = Vector2.Zero;
        Color?[] overrideColor;
        List<TooltipLine> lines = ItemLoader.ModifyTooltips(HoverItem, ref numLines, tooltipNames, ref array, ref array2, ref array3, ref yoyoLogo, out overrideColor, prefixlineIndex);
        List<DrawableTooltipLine> drawableLines = lines.Select((TooltipLine x, int i) => new DrawableTooltipLine(x, i, 0, 0, Color.White)).ToList();
        int num4 = 0;
        for (int k = 0; k < numLines; k++)
        {
            Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, array[k], Vector2.One);
            if (stringSize.X > zero.X)
            {
                zero.X = stringSize.X;
            }
            zero.Y += stringSize.Y + (float)num4;
        }
        if (yoyoLogo != -1)
        {
            zero.Y += 24f;
        }
        X += toolTipDistance;
        Y += toolTipDistance;
        int num5 = 4;
        if (settingsEnabled_OpaqueBoxBehindTooltips)
        {
            X += 8;
            Y += 2;
            num5 = 18;
        }
        int num6 = screenWidth;
        int num7 = screenHeight;
        if ((float)X + zero.X + (float)num5 > (float)num6)
        {
            X = (int)((float)num6 - zero.X - (float)num5);
        }
        if ((float)Y + zero.Y + (float)num5 > (float)num7)
        {
            Y = (int)((float)num7 - zero.Y - (float)num5);
        }
        int num8 = 0;
        num16 = (float)(int)mouseTextColor / 255f;
        if (settingsEnabled_OpaqueBoxBehindTooltips)
        {
            num16 = MathHelper.Lerp(num16, 1f, 1f);
            int num9 = 14;
            int num10 = 9;
            Utils.DrawInvBG(spriteBatch, new Rectangle(X - num9, Y - num10, (int)zero.X + num9 * 2, (int)zero.Y + num10 + num10 / 2), new Color(23, 25, 81, 255) * 0.925f);
        }
        bool globalCanDraw = ItemLoader.PreDrawTooltip(HoverItem, lines.AsReadOnly(), ref X, ref Y);
        for (int l = 0; l < numLines; l++)
        {
            drawableLines[l].OriginalX = X;
            drawableLines[l].OriginalY = Y + num8;
            if (drawableLines[l].Mod == "Terraria" && drawableLines[l].Name == "OneDropLogo")
            {
                float num11 = 1f;
                int num13 = (int)((float)(int)mouseTextColor * num11);
                Color color2 = Color.Black;
                drawableLines[l].Color = new Color(num13, num13, num13, num13);
                if (ItemLoader.PreDrawTooltipLine(HoverItem, drawableLines[l], ref num4) && globalCanDraw)
                {
                    for (int m = 0; m < 5; m++)
                    {
                        int num14 = drawableLines[l].X;
                        int num15 = drawableLines[l].Y;
                        if (m == 4)
{
                            ((Color)(ref color2))._002Ector(num13, num13, num13, num13);
                        }
                        switch (m)
{
                        case 0:
                            num14--;
                            break;
                        case 1:
                            num14++;
                            break;
                        case 2:
                            num15--;
                            break;
                        case 3:
                            num15++;
                            break;
                        }
                        Color drawColor2 = (Color)(((_003F?)drawableLines[l].OverrideColor) ?? drawableLines[l].Color);
                        spriteBatch.Draw(TextureAssets.OneDropLogo.Value, new Vector2((float)num14, (float)num15), (Rectangle?)null, (m != 4) ? color2 : drawColor2, drawableLines[l].Rotation, drawableLines[l].Origin, (drawableLines[l].BaseScale.X + drawableLines[l].BaseScale.Y) / 2f, (SpriteEffects)0, 0f);
                    }
                }
            }
            else
            {
                Color black = Color.Black;
                ((Color)(ref black))._002Ector(num17, num17, num17, num17);
                if (drawableLines[l].Mod == "Terraria" && drawableLines[l].Name == "ItemName")
                {
                    if (rare == -11)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(255f * num17), (int)(byte)(175f * num17), (int)(byte)(0f * num17), a);
                    }
                    if (rare == -1)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(130f * num17), (int)(byte)(130f * num17), (int)(byte)(130f * num17), a);
                    }
                    if (rare == 1)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(150f * num17), (int)(byte)(150f * num17), (int)(byte)(255f * num17), a);
                    }
                    if (rare == 2)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(150f * num17), (int)(byte)(255f * num17), (int)(byte)(150f * num17), a);
                    }
                    if (rare == 3)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(255f * num17), (int)(byte)(200f * num17), (int)(byte)(150f * num17), a);
                    }
                    if (rare == 4)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(255f * num17), (int)(byte)(150f * num17), (int)(byte)(150f * num17), a);
                    }
                    if (rare == 5)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(255f * num17), (int)(byte)(150f * num17), (int)(byte)(255f * num17), a);
                    }
                    if (rare == 6)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(210f * num17), (int)(byte)(160f * num17), (int)(byte)(255f * num17), a);
                    }
                    if (rare == 7)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(150f * num17), (int)(byte)(255f * num17), (int)(byte)(10f * num17), a);
                    }
                    if (rare == 8)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(255f * num17), (int)(byte)(255f * num17), (int)(byte)(10f * num17), a);
                    }
                    if (rare == 9)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(5f * num17), (int)(byte)(200f * num17), (int)(byte)(255f * num17), a);
                    }
                    if (rare == 10)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(255f * num17), (int)(byte)(40f * num17), (int)(byte)(100f * num17), a);
                    }
                    if (rare == 11)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(180f * num17), (int)(byte)(40f * num17), (int)(byte)(255f * num17), a);
                    }
                    if (rare > 11)
                    {
                        black = RarityLoader.GetRarity(rare).RarityColor * num17;
                    }
                    if (diff == 1)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)((float)(int)((Color)(ref mcColor)).R * num17), (int)(byte)((float)(int)((Color)(ref mcColor)).G * num17), (int)(byte)((float)(int)((Color)(ref mcColor)).B * num17), a);
                    }
                    if (diff == 2)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)((float)(int)((Color)(ref hcColor)).R * num17), (int)(byte)((float)(int)((Color)(ref hcColor)).G * num17), (int)(byte)((float)(int)((Color)(ref hcColor)).B * num17), a);
                    }
                    if (hoverItem.expert || rare == -12)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)((float)DiscoR * num17), (int)(byte)((float)DiscoG * num17), (int)(byte)((float)DiscoB * num17), a);
                    }
                    if (hoverItem.master || rare == -13)
                    {
                        ((Color)(ref black))._002Ector((int)(byte)(255f * num17), (int)(byte)(masterColor * 200f * num17), 0, a);
                    }
                }
                else if (array2[l])
                {
                    black = ((!array3[l]) ? new Color((int)(byte)(120f * num17), (int)(byte)(190f * num17), (int)(byte)(120f * num17), a) : new Color((int)(byte)(190f * num17), (int)(byte)(120f * num17), (int)(byte)(120f * num17), a));
                }
                else if (drawableLines[l].Mod == "Terraria" && drawableLines[l].Name == "Price")
                {
                    black = color;
                }
                if (drawableLines[l].Mod == "Terraria" && drawableLines[l].Name == "JourneyResearch")
                {
                    black = Colors.JourneyMode;
                }
                drawableLines[l].Color = black;
                Color realLineColor = black;
                if (overrideColor[l].HasValue)
                {
                    realLineColor = overrideColor[l].Value * num17;
                    drawableLines[l].OverrideColor = realLineColor;
                }
                if (ItemLoader.PreDrawTooltipLine(HoverItem, drawableLines[l], ref num4) && globalCanDraw)
                {
                    ChatManager.DrawColorCodedStringWithShadow(spriteBatch, drawableLines[l].Font, drawableLines[l].Text, new Vector2((float)drawableLines[l].X, (float)drawableLines[l].Y), realLineColor, drawableLines[l].Rotation, drawableLines[l].Origin, drawableLines[l].BaseScale, drawableLines[l].MaxWidth, drawableLines[l].Spread);
                }
            }
            ItemLoader.PostDrawTooltipLine(HoverItem, drawableLines[l]);
            num8 += (int)(FontAssets.MouseText.Value.MeasureString(drawableLines[l].Text).Y + (float)num4);
        }
        ItemLoader.PostDrawTooltip(HoverItem, drawableLines.AsReadOnly());
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Utils.DrawInvBG(), Terraria.GameContent.ItemShopSellbackHelper.GetAmount(), Terraria.Player.GetItemExpectedPrice(), Terraria.GameContent.UI.CustomCurrencyManager.GetPriceText(), Terraria.ModLoader.RarityLoader.GetRarity(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Main.hcColor, Terraria.Main.HoverItem, Terraria.Lang.inter, Terraria.ID.Colors.JourneyMode, Terraria.Player.kbGlove, Terraria.Main.LocalPlayer, Terraria.Main.masterColor, Terraria.Main.mcColor, Terraria.ModLoader.ItemLoader.ModifyTooltips(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), Terraria.Main.mouseTextColor, Terraria.Main.myPlayer, Terraria.Main.npcShop, Terraria.GameContent.TextureAssets.OneDropLogo, Terraria.Main.player, Terraria.ModLoader.ItemLoader.PostDrawTooltip(), Terraria.ModLoader.ItemLoader.PostDrawTooltipLine(), Terraria.ModLoader.ItemLoader.PreDrawTooltip(), Terraria.ModLoader.ItemLoader.PreDrawTooltipLine(), Terraria.Main.rare, Terraria.ModLoader.ModRarity.RarityColor, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.SettingsEnabled_OpaqueBoxBehindTooltips, Terraria.Main.shopSellbackHelper, Terraria.Player.shroomiteStealth, Terraria.Main.spriteBatch, Terraria.Player.stealth, Terraria.Lang.tip, Terraria.Main.toolTipDistance, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.MouseTextInner().