TModLoader: Terraria.Main.DrawProj_EmpressBlade
DrawProj_EmpressBlade()
void Terraria.Main.DrawProj_EmpressBlade (Projectile proj, float hueOverride) inline private
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0013: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0259: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        CurrentDrawnEntityShader = -1;
        PrepareDrawnProjectileDrawing(proj);
        Vector2 vector = proj.Center - screenPosition;
        proj.GetFairyQueenWeaponsColor(0f, 0f, hueOverride);
        Color fairyQueenWeaponsColor = proj.GetFairyQueenWeaponsColor(0.5f, 0f, hueOverride);
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        Vector2 origin = value.Frame().Size() / 2f;
        Color color = Color.White * proj.Opacity;
        ((Color)(ref color)).A = (byte)((float)(int)((Color)(ref color)).A * 0.7f);
        ((Color)(ref fairyQueenWeaponsColor)).A = (byte)(((Color)(ref fairyQueenWeaponsColor)).A / 2);
        float scale = proj.scale;
        float num = proj.rotation - (float)Math.PI / 2f;
        float num2 = proj.Opacity * 0.3f;
        if (num2 > 0f)
        {
            float lerpValue = Utils.GetLerpValue(60f, 50f, proj.ai[0], clamped: true);
            float num3 = Utils.GetLerpValue(70f, 50f, proj.ai[0], clamped: true) * Utils.GetLerpValue(40f, 45f, proj.ai[0], clamped: true);
            for (float num4 = 0f; num4 < 1f; num4 += 1f / 6f)
            {
                Vector2 vector2 = num.ToRotationVector2() * -120f * num4 * lerpValue;
                EntitySpriteDraw(value, vector + vector2, null, fairyQueenWeaponsColor * num2 * (1f - num4) * num3, num, origin, scale * 1.5f, (SpriteEffects)0);
            }
            for (float num5 = 0f; num5 < 1f; num5 += 0.25f)
            {
                Vector2 vector3 = (num5 * ((float)Math.PI * 2f) + num).ToRotationVector2() * 4f * scale;
                EntitySpriteDraw(value, vector + vector3, null, fairyQueenWeaponsColor * num2, num, origin, scale, (SpriteEffects)0);
            }
        }
        EntitySpriteDraw(value, vector, null, color, num, origin, scale, (SpriteEffects)0);
        EntitySpriteDraw(value, vector, null, fairyQueenWeaponsColor * num2 * 0.5f, num, origin, scale, (SpriteEffects)0);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.CurrentDrawnEntityShader, Terraria.Main.EntitySpriteDraw(), Terraria.Utils.GetLerpValue(), Terraria.Main.PrepareDrawnProjectileDrawing(), Terraria.GameContent.TextureAssets.Projectile, and Terraria.Main.screenPosition.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().