TModLoader: Terraria.Main.DrawSurfaceBG_GoodEvilDesert
DrawSurfaceBG_GoodEvilDesert()
void Terraria.Main.DrawSurfaceBG_GoodEvilDesert (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack) inline private
Definition at line 77206 of file Main.cs.
    {
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02df: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        LoadBackground(26);
        bgScale = 1.25f;
        bgScale *= bgGlobalScaleMultiplier;
        bgWidthScaled = (int)((float)backgroundWidth[26] * bgScale);
        bgParallax = 0.37;
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 1800.0 + 1750.0) + (int)scAdj + pushBGTopHack;
        if (gameMenu)
        {
            bgTopY = 320 + pushBGTopHack;
        }
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int i = 0; i < bgLoops; i++)
            {
                spriteBatch.Draw(TextureAssets.Background[26].Value, new Vector2((float)(bgStartX + bgWidthScaled * i), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[26], backgroundHeight[26]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
        bgScale = 1.34f;
        bgScale *= bgGlobalScaleMultiplier;
        LoadBackground(27);
        bgWidthScaled = (int)((float)backgroundWidth[27] * bgScale);
        bgParallax = 0.49;
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 2100.0 + 2150.0) + (int)scAdj + pushBGTopHack;
        if (gameMenu)
        {
            bgTopY = 480 + pushBGTopHack;
            bgStartX -= 120;
        }
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int j = 0; j < bgLoops; j++)
            {
                spriteBatch.Draw(TextureAssets.Background[27].Value, new Vector2((float)(bgStartX + bgWidthScaled * j), (float)bgTopY), (Rectangle?)new Rectangle(0, 0, backgroundWidth[27], backgroundHeight[27]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
    }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundHeight, Terraria.Main.backgroundWidth, Terraria.Main.bgLoops, Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Graphics.Effects.SkyManager.DrawToDepth(), Terraria.Main.gameMenu, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.LoadBackground(), Terraria.Main.scAdj, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawSurfaceBG().