TModLoader: Terraria.Main.DrawCapture
DrawCapture()
void Terraria.Main.DrawCapture (Rectangle area, CaptureSettings settings) inline
Definition at line 72450 of file Main.cs.
    {
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_033c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_03be: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_043e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0440: Unknown result type (might be due to invalid IL or missing references)
        //IL_0445: Unknown result type (might be due to invalid IL or missing references)
        //IL_044a: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0524: Unknown result type (might be due to invalid IL or missing references)
        //IL_0526: Unknown result type (might be due to invalid IL or missing references)
        //IL_052b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_054c: Unknown result type (might be due to invalid IL or missing references)
        //IL_057a: Unknown result type (might be due to invalid IL or missing references)
        //IL_057f: Unknown result type (might be due to invalid IL or missing references)
        //IL_058d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0592: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_0599: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a94: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aec: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_06bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_070c: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0750: Unknown result type (might be due to invalid IL or missing references)
        //IL_085d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0867: Unknown result type (might be due to invalid IL or missing references)
        //IL_0876: Unknown result type (might be due to invalid IL or missing references)
        //IL_0881: Unknown result type (might be due to invalid IL or missing references)
        //IL_0897: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_076e: Unknown result type (might be due to invalid IL or missing references)
        //IL_078f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0965: Unknown result type (might be due to invalid IL or missing references)
        //IL_0967: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0800: Unknown result type (might be due to invalid IL or missing references)
        //IL_0802: Unknown result type (might be due to invalid IL or missing references)
        //IL_0818: Unknown result type (might be due to invalid IL or missing references)
        //IL_081d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0824: Unknown result type (might be due to invalid IL or missing references)
        //IL_0832: Unknown result type (might be due to invalid IL or missing references)
        //IL_0839: Unknown result type (might be due to invalid IL or missing references)
        //IL_084c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0851: Unknown result type (might be due to invalid IL or missing references)
        //IL_09da: Unknown result type (might be due to invalid IL or missing references)
        //IL_09df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a12: Unknown result type (might be due to invalid IL or missing references)
        //IL_1047: Unknown result type (might be due to invalid IL or missing references)
        //IL_1049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f99: Unknown result type (might be due to invalid IL or missing references)
        //IL_1016: Unknown result type (might be due to invalid IL or missing references)
        //IL_101c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fde: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fed: Unknown result type (might be due to invalid IL or missing references)
        float[] array = bgAlphaFrontLayer;
        bgAlphaFrontLayer = new float[array.Length];
        float[] array2 = bgAlphaFarBackLayer;
        bgAlphaFarBackLayer = new float[array2.Length];
        UpdateBGVisibility_BackLayer(settings.Biome.BackgroundIndex, 1f);
        UpdateBGVisibility_FrontLayer(settings.Biome.BackgroundIndex, 1f);
        float[] array3 = liquidAlpha.ToArray();
        int holyTileCount = SceneMetrics.HolyTileCount;
        SceneMetrics.HolyTileCount = ((settings.Biome.BackgroundIndex == 6) ? SceneMetrics.HallowTileMax : 0);
        int num = offScreenRange;
        offScreenRange = 0;
        SpriteViewMatrix gameViewMatrix = GameViewMatrix;
        GameViewMatrix = new SpriteViewMatrix(((Game)this).GraphicsDevice);
        Rasterizer = RasterizerState.CullCounterClockwise;
        bool captureEntities = settings.CaptureEntities;
        bool captureBackground = settings.CaptureBackground;
        CaptureBiome biome = settings.Biome;
        Vector2 vector = screenPosition;
        int num10 = screenWidth;
        int num11 = screenHeight;
        float num12 = cloudAlpha;
        bool captureMech = settings.CaptureMech;
        screenWidth = area.Width << 4;
        screenHeight = area.Height << 4;
        screenPosition = new Vector2((float)(area.X * 16), (float)(area.Y * 16));
        cloudAlpha = 0f;
        for (int i = 0; i <= 10; i++)
        {
            if (i != 1)
            {
                liquidAlpha[i] = ((i == biome.WaterStyle) ? 1f : 0f);
            }
        }
        int x = area.X;
        int y = area.Y;
        int num13 = area.X + screenWidth / 16;
        int num14 = area.Y + screenHeight / 16;
        float num15 = (biome.TileColor == CaptureBiome.TileColorStyle.Mushroom).ToInt();
        InfoToSetBackColor info = default(InfoToSetBackColor);
        info.isInGameMenuOrIsServer = gameMenu || netMode == 2;
        info.CorruptionBiomeInfluence = (biome.TileColor == CaptureBiome.TileColorStyle.Corrupt).ToInt();
        info.CrimsonBiomeInfluence = (biome.TileColor == CaptureBiome.TileColorStyle.Crimson).ToInt();
        info.JungleBiomeInfluence = (biome.TileColor == CaptureBiome.TileColorStyle.Jungle).ToInt();
        info.MushroomBiomeInfluence = num15;
        info.GraveyardInfluence = GraveyardVisualIntensity;
        info.BloodMoonActive = biome.WaterStyle == 9;
        info.LanternNightActive = LanternNight.LanternsUp;
        SetBackColor(info, out var sunColor, out var moonColor);
        ApplyColorOfTheSkiesToTiles();
        ColorOfSurfaceBackgroundsBase = (ColorOfSurfaceBackgroundsModified = ColorOfTheSkies);
        bool flag = mapEnabled;
        mapEnabled = false;
        Lighting.Initialize();
        renderCount = 99;
        for (int j = 0; j < 4; j++)
        {
            Lighting.LightTiles(x, num13, y, num14);
        }
        mapEnabled = flag;
        if (!((float)(settings.Area.X * 16) > vector.X - 16f) || !((float)(settings.Area.Y * 16) > vector.Y - 16f) || !((float)((settings.Area.X + settings.Area.Width) * 16) < vector.X + (float)num10 + 16f) || !((float)((settings.Area.Y + settings.Area.Height) * 16) < vector.Y + (float)num11 + 16f))
        {
            for (int k = 0; k < dust.Length; k++)
            {
                if (dust[k].active && dust[k].type == 76)
                {
                    dust[k].active = false;
                }
            }
        }
        Vector2 vector2 = (Vector2)(drawToScreen ? Vector2.Zero : new Vector2((float)offScreenRange, (float)offScreenRange));
        int val = (int)((screenPosition.X - vector2.X) / 16f - 1f);
        int val2 = (int)((screenPosition.X + (float)screenWidth + vector2.X) / 16f) + 2;
        int val3 = (int)((screenPosition.Y - vector2.Y) / 16f - 1f);
        int val4 = (int)((screenPosition.Y + (float)screenHeight + vector2.Y) / 16f) + 5;
        vector2 -= screenPosition;
        val = Math.Max(val, 5) - 2;
        val3 = Math.Max(val3, 5);
        val2 = Math.Min(val2, maxTilesX - 5) + 2;
        val4 = Math.Min(val4, maxTilesY - 5) + 4;
        Rectangle drawArea = default(Rectangle);
        ((Rectangle)(ref drawArea))._002Ector(val, val3, val2 - val, val4 - val3);
        LiquidRenderer.Instance.PrepareDraw(drawArea);
        WorldGen.SectionTileFrameWithCheck(x, y, num13, num14);
        SceneArea sceneArea = default(SceneArea);
        if (captureBackground)
        {
            Matrix transform = Transform;
            int num16 = screenHeight;
            int num17 = screenWidth;
            Vector2 vector3 = screenPosition;
            bool flag2 = mapFullscreen;
            mapFullscreen = false;
            float num2 = scAdj;
            Vector2 vector4 = default(Vector2);
            ((Vector2)(ref vector4))._002Ector((float)num10, (float)num11);
            Vector2 vector5 = new Vector2((float)(settings.Area.Width * 16), (float)(settings.Area.Height * 16)) / vector4;
            vector5.X = Math.Max(1f, vector5.X);
            vector5.Y = Math.Max(1f, vector5.Y);
            Vector2[] array4 = (Vector2[])(object)new Vector2[numClouds];
            for (int l = 0; l < numClouds; l++)
            {
                array4[l] = cloud[l].position;
                Cloud obj = cloud[l];
                obj.position *= vector5;
            }
            if ((float)(settings.Area.Height * 16) >= 2000f || (float)(settings.Area.Width * 16) >= 2000f)
            {
                scAdj = 0f;
                float num3 = 2048f;
                float num4 = MathHelper.Clamp((float)settings.Area.Height * 16f / num3, 1f, 3f);
                screenWidth = settings.Area.Width * 16;
                screenHeight = Math.Min(2048, settings.Area.Height * 16);
                screenPosition.X = settings.Area.X * 16;
                screenPosition.Y = settings.Area.Y * 16;
                screenPosition.Y += Math.Max(0f, Math.Min(settings.Area.Height, (float)worldSurface) * 16f - num3 * num4);
                transform *= Matrix.CreateScale(num4);
                ((Matrix)(ref transform)).Translation = ((Matrix)(ref transform)).Translation + new Vector3((float)((settings.Area.X - area.X) * 16), (float)((settings.Area.Y - area.Y) * 16), 0f);
                ((Matrix)(ref transform)).Translation = ((Matrix)(ref transform)).Translation + new Vector3(0f, Math.Max(0f, Math.Min(settings.Area.Height, (float)worldSurface) * 16f - num3 * num4) / num4, 0f);
            }
            else if ((float)(settings.Area.X * 16) > vector.X - 16f && (float)(settings.Area.Y * 16) > vector.Y - 16f && (float)((settings.Area.X + settings.Area.Width) * 16) < vector.X + (float)num10 + 16f && (float)((settings.Area.Y + settings.Area.Height) * 16) < vector.Y + (float)num11 + 16f)
            {
                screenPosition = vector;
                screenWidth = num10;
                screenHeight = num11;
                ((Matrix)(ref transform)).Translation = ((Matrix)(ref transform)).Translation + new Vector3(vector.X - (float)area.X * 16f, vector.Y - (float)area.Y * 16f, 0f);
            }
            Vector2 areaPosition = default(Vector2);
            ((Vector2)(ref areaPosition))._002Ector((float)(area.X * 16), (float)(area.Y * 16));
            int areaWidth = area.Width * 16;
            int areaHeight = area.Height * 16;
            tileBatch.Begin();
            DrawSimpleSurfaceBackground(areaPosition, areaWidth, areaHeight);
            tileBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.AnisotropicClamp, DepthStencilState.Default, RasterizerState.CullNone, (Effect)null, transform);
            int num5 = screenWidth;
            int num6 = screenHeight;
            Vector2 zero = Vector2.Zero;
            if (num5 < 800)
            {
                int num7 = 800 - num5;
                zero.X -= (float)num7 * 0.5f;
                num5 = 800;
            }
            if (num6 < 600)
            {
                int num8 = 600 - num6;
                zero.Y -= (float)num8 * 0.5f;
                num6 = 600;
            }
            SceneArea sceneArea2 = default(SceneArea);
            sceneArea2.bgTopY = 0;
            sceneArea2.totalWidth = num5;
            sceneArea2.totalHeight = num6;
            sceneArea2.SceneLocalScreenPositionOffset = zero;
            SceneArea sceneArea3 = sceneArea2;
            sceneArea = sceneArea3;
            if (shimmerAlpha != 1f)
            {
                DrawStarsInBackground(sceneArea3, artificial: false);
            }
            if ((double)(screenPosition.Y / 16f) < worldSurface + 2.0)
            {
                DrawSunAndMoon(sceneArea3, moonColor, sunColor, num15);
            }
            DrawSurfaceBG();
            spriteBatch.End();
            for (int m = 0; m < numClouds; m++)
            {
                cloud[m].position = array4[m];
            }
            scAdj = num2;
            mapFullscreen = flag2;
            screenWidth = num17;
            screenHeight = num16;
            screenPosition = vector3;
        }
        if (captureBackground)
        {
            spriteBatch.Begin();
            DrawUnderworldBackground(flat: true);
            spriteBatch.End();
        }
        if (captureEntities)
        {
            spriteBatch.Begin();
            CacheNPCDraws();
            CacheProjDraws();
            DrawCachedNPCs(DrawCacheNPCsMoonMoon, behindTiles: true);
            spriteBatch.End();
        }
        if (shimmerAlpha > 0f && captureBackground)
        {
            spriteBatch.Begin();
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, Vector2.Zero, (Rectangle?)null, Color.Black * shimmerAlpha, 0f, Vector2.Zero, new Vector2(Camera.UnscaledSize.X + (float)(offScreenRange * 2), Camera.UnscaledSize.Y + (float)(offScreenRange * 2)), (SpriteEffects)0, 0f);
            spriteBatch.End();
        }
        tileBatch.Begin();
        spriteBatch.Begin();
        DrawBlack(force: true);
        tileBatch.End();
        spriteBatch.End();
        tileBatch.Begin();
        spriteBatch.Begin();
        if (biome == null)
        {
            DrawLiquid(bg: true, waterStyle);
        }
        else
        {
            DrawLiquid(bg: true, bloodMoon ? 9 : biome.WaterStyle);
        }
        tileBatch.End();
        spriteBatch.End();
        if (shimmerAlpha > 0f && captureBackground)
        {
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, (DepthStencilState)null, (RasterizerState)null, (Effect)null);
            PlayerInput.SetZoom_Unscaled();
            DrawStarsInBackground(sceneArea, artificial: true);
            spriteBatch.End();
            PlayerInput.SetDesiredZoomContext(ZoomContext.World);
        }
        if (captureBackground)
        {
            tileBatch.Begin();
            spriteBatch.Begin();
            DrawBackground();
            tileBatch.End();
            spriteBatch.End();
        }
        tileBatch.Begin();
        spriteBatch.Begin();
        DrawWalls();
        tileBatch.End();
        spriteBatch.End();
        if (captureEntities)
        {
            spriteBatch.Begin();
            DrawWoF();
            spriteBatch.End();
        }
        if (drawBackGore && captureEntities)
        {
            spriteBatch.Begin();
            DrawGoreBehind();
            spriteBatch.End();
            drawBackGore = true;
        }
        if (captureEntities)
        {
            spriteBatch.Begin();
            MoonlordDeathDrama.DrawPieces(spriteBatch);
            MoonlordDeathDrama.DrawExplosions(spriteBatch);
            spriteBatch.End();
        }
        bool flag3 = false;
        bool intoRenderTargets = false;
        bool intoRenderTargets2 = false;
        TilesRenderer.SpecificHacksForCapture();
        TilesRenderer.PreDrawTiles(solidLayer: false, flag3, intoRenderTargets2);
        tileBatch.Begin();
        spriteBatch.Begin();
        DrawCachedNPCs(DrawCacheNPCsBehindNonSolidTiles, behindTiles: true);
        int waterStyleOverride = (bloodMoon ? 9 : biome.WaterStyle);
        if (biome == null)
        {
            DrawTiles(solidLayer: false, flag3, intoRenderTargets);
        }
        else
        {
            DrawTiles(solidLayer: false, flag3, intoRenderTargets, waterStyleOverride);
        }
        tileBatch.End();
        spriteBatch.End();
        DrawTileEntities(solidLayer: false, flag3, intoRenderTargets);
        if (captureEntities)
        {
            spriteBatch.Begin();
            tileBatch.Begin();
            waterfallManager.FindWaterfalls(forced: true);
            waterfallManager.Draw(spriteBatch);
            tileBatch.End();
            spriteBatch.End();
        }
        if (captureEntities)
        {
            DrawCachedProjs(DrawCacheProjsBehindNPCsAndTiles);
            spriteBatch.Begin();
            DrawNPCs(behindTiles: true);
            spriteBatch.End();
        }
        TilesRenderer.PreDrawTiles(solidLayer: true, flag3, intoRenderTargets2);
        tileBatch.Begin();
        spriteBatch.Begin();
        if (biome == null)
        {
            DrawTiles(solidLayer: true, flag3, intoRenderTargets);
        }
        else
        {
            DrawTiles(solidLayer: true, flag3, intoRenderTargets, waterStyleOverride);
        }
        tileBatch.End();
        spriteBatch.End();
        DrawTileEntities(solidLayer: true, flag3, intoRenderTargets);
        if (captureEntities)
        {
            DrawPlayers_BehindNPCs();
            DrawCachedProjs(DrawCacheProjsBehindNPCs);
            spriteBatch.Begin();
            DrawNPCs();
            spriteBatch.End();
            spriteBatch.Begin();
            DrawCachedNPCs(DrawCacheNPCProjectiles, behindTiles: false);
            spriteBatch.End();
            DrawSuperSpecialProjectiles(DrawCacheFirstFractals);
            DrawCachedProjs(DrawCacheProjsBehindProjectiles);
            DrawProjectiles();
            DrawPlayers_AfterProjectiles();
            DrawCachedProjs(DrawCacheProjsOverPlayers);
            spriteBatch.Begin();
            DrawCachedNPCs(DrawCacheNPCsOverPlayers, behindTiles: false);
            spriteBatch.End();
            spriteBatch.Begin();
            DrawItems();
            spriteBatch.End();
            spriteBatch.Begin();
            DrawRain();
            spriteBatch.End();
            spriteBatch.Begin();
            DrawGore();
            spriteBatch.End();
            DrawDust();
        }
        tileBatch.Begin();
        spriteBatch.Begin();
        if (biome == null)
        {
            DrawLiquid(bg: false, waterStyle);
        }
        else
        {
            DrawLiquid(bg: false, biome.WaterStyle);
        }
        if (captureMech)
        {
            DrawWires();
        }
        tileBatch.End();
        spriteBatch.End();
        DrawCachedProjs(DrawCacheProjsOverWiresUI);
        if (mapEnabled)
        {
            spriteBatch.Begin();
            for (int n = area.X; n < area.X + area.Width; n++)
            {
                for (int num9 = area.Y; num9 < area.Y + area.Height; num9++)
                {
                    if (!Map.IsRevealed(n, num9))
                    {
                        spriteBatch.Draw(TextureAssets.BlackTile.Value, new Vector2((float)n * 16f, (float)num9 * 16f) - screenPosition, Color.Black);
                    }
                }
            }
            spriteBatch.End();
        }
        renderCount = 99;
        screenWidth = num10;
        screenHeight = num11;
        screenPosition = vector;
        liquidAlpha = array3;
        offScreenRange = num;
        cloudAlpha = num12;
        bgAlphaFrontLayer = array;
        bgAlphaFarBackLayer = array2;
        SceneMetrics.HolyTileCount = holyTileCount;
        Lighting.Initialize();
        GameViewMatrix = gameViewMatrix;
    }
References Terraria.Dust.active, Terraria.Main.ApplyColorOfTheSkiesToTiles(), Terraria.Graphics.TileBatch.Begin(), Terraria.Main.bgAlphaFarBackLayer, Terraria.Main.bgAlphaFrontLayer, Terraria.GameContent.TextureAssets.BlackTile, Terraria.Main.bloodMoon, Terraria.Main.CacheNPCDraws(), Terraria.Main.CacheProjDraws(), Terraria.Main.cloud, Terraria.Main.cloudAlpha, Terraria.Graphics.Light.Color, Terraria.Main.ColorOfSurfaceBackgroundsBase, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Main.ColorOfTheSkies, Terraria.Main.DefaultSamplerState, Terraria.WaterfallManager.Draw(), Terraria.Main.drawBackGore, Terraria.Main.DrawBackground(), Terraria.Main.DrawBlack(), Terraria.Main.DrawCachedNPCs(), Terraria.Main.DrawCachedProjs(), Terraria.Main.DrawCacheFirstFractals, Terraria.Main.DrawCacheNPCProjectiles, Terraria.Main.DrawCacheNPCsBehindNonSolidTiles, Terraria.Main.DrawCacheNPCsMoonMoon, Terraria.Main.DrawCacheNPCsOverPlayers, Terraria.Main.DrawCacheProjsBehindNPCs, Terraria.Main.DrawCacheProjsBehindNPCsAndTiles, Terraria.Main.DrawCacheProjsBehindProjectiles, Terraria.Main.DrawCacheProjsOverPlayers, Terraria.Main.DrawCacheProjsOverWiresUI, Terraria.Main.DrawDust(), Terraria.GameContent.Events.MoonlordDeathDrama.DrawExplosions(), Terraria.Main.DrawGore(), Terraria.Main.DrawGoreBehind(), Terraria.Main.DrawItems(), Terraria.Main.DrawLiquid(), Terraria.Main.DrawNPCs(), Terraria.GameContent.Events.MoonlordDeathDrama.DrawPieces(), Terraria.Main.DrawPlayers_AfterProjectiles(), Terraria.Main.DrawPlayers_BehindNPCs(), Terraria.Main.DrawProjectiles(), Terraria.Main.DrawRain(), Terraria.Main.DrawSimpleSurfaceBackground(), Terraria.Main.DrawStarsInBackground(), Terraria.Main.DrawSunAndMoon(), Terraria.Main.DrawSuperSpecialProjectiles(), Terraria.Main.DrawSurfaceBG(), Terraria.Main.DrawTileEntities(), Terraria.Main.DrawTiles(), Terraria.Main.drawToScreen, Terraria.Main.DrawUnderworldBackground(), Terraria.Main.DrawWalls(), Terraria.Main.DrawWires(), Terraria.Main.DrawWoF(), Terraria.Main.dust, Terraria.Graphics.TileBatch.End(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.Main.gameMenu, Terraria.Main.GameViewMatrix, Terraria.Main.GraveyardVisualIntensity, Terraria.SceneMetrics.HallowTileMax, Terraria.SceneMetrics.HolyTileCount, Terraria.Lighting.Initialize(), Terraria.GameContent.Liquid.LiquidRenderer.Instance, Terraria.Map.WorldMap.IsRevealed(), Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Lighting.LightTiles(), Terraria.Main.liquidAlpha, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.Map, Terraria.Main.mapEnabled, Terraria.Main.mapFullscreen, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Main.numClouds, Terraria.Main.offScreenRange, Terraria.Cloud.position, Terraria.GameContent.Drawing.TileDrawing.PreDrawTiles(), Terraria.GameContent.Liquid.LiquidRenderer.PrepareDraw(), Terraria.Main.Rasterizer, Terraria.Main.renderCount, Terraria.Main.scAdj, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.WorldGen.SectionTileFrameWithCheck(), Terraria.Main.SetBackColor(), Terraria.GameInput.PlayerInput.SetDesiredZoomContext(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.Main.shimmerAlpha, Terraria.GameContent.Drawing.TileDrawing.SpecificHacksForCapture(), Terraria.Main.spriteBatch, Terraria.Main.tileBatch, Terraria.Main.TilesRenderer, Terraria.Main.Transform, Terraria.Graphics.Camera.UnscaledSize, Terraria.Main.UpdateBGVisibility_BackLayer(), Terraria.Main.UpdateBGVisibility_FrontLayer(), Terraria.Main.waterfallManager, Terraria.Main.waterStyle, and Terraria.Main.worldSurface.
Referenced by Terraria.Graphics.Capture.CaptureCamera.DrawTick().