TModLoader: Terraria.Main.MouseTextInner
MouseTextInner()
void Terraria.Main.MouseTextInner (MouseTextCache info) inline private
    {
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_045d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0464: Unknown result type (might be due to invalid IL or missing references)
        //IL_0469: Unknown result type (might be due to invalid IL or missing references)
        //IL_056c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0571: Unknown result type (might be due to invalid IL or missing references)
        //IL_0578: Unknown result type (might be due to invalid IL or missing references)
        //IL_057d: Unknown result type (might be due to invalid IL or missing references)
        //IL_058c: Unknown result type (might be due to invalid IL or missing references)
        string cursorText = info.cursorText;
        int num = info.rare;
        byte diff = info.diff;
        int x = info.X;
        int y = info.Y;
        int hackedScreenWidth = info.hackedScreenWidth;
        int hackedScreenHeight = info.hackedScreenHeight;
        if (mouseNPCType > -1 || cursorText == null)
        {
            return;
        }
        int X = mouseX + 14;
        int Y = mouseY + 14;
        if (x != -1 && y != -1)
        {
            X = x + 10;
            Y = y + 10;
        }
        if (ThickMouse)
        {
            X += 6;
            Y += 6;
        }
        if (!mouseItem.IsAir)
        {
            X += 34;
        }
        new Color((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor);
        Vector2 vector = FontAssets.MouseText.Value.MeasureString(cursorText);
        if (HoverItem.type > 0)
        {
            MouseText_DrawItemTooltip(info, num, diff, X, Y);
            return;
        }
        if (info.buffTooltip != null && info.buffTooltip != "")
        {
            MouseText_DrawBuffTooltip(info.buffTooltip, ref X, ref Y, (int)vector.Y);
        }
        if (hackedScreenHeight != -1 && hackedScreenWidth != -1)
        {
            if ((float)X + vector.X + 4f > (float)hackedScreenWidth)
            {
                X = (int)((float)hackedScreenWidth - vector.X - 4f);
            }
            if ((float)Y + vector.Y + 4f > (float)hackedScreenHeight)
            {
                Y = (int)((float)hackedScreenHeight - vector.Y - 4f);
            }
        }
        else
        {
            if ((float)X + vector.X + 4f > (float)screenWidth)
            {
                X = (int)((float)screenWidth - vector.X - 4f);
            }
            if ((float)Y + vector.Y + 4f > (float)screenHeight)
            {
                Y = (int)((float)screenHeight - vector.Y - 4f);
            }
        }
        float num2 = (float)(int)mouseTextColor / 255f;
        Color baseColor = default(Color);
        ((Color)(ref baseColor))._002Ector((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor);
        if (num == -11)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(255f * num2), (int)(byte)(175f * num2), (int)(byte)(0f * num2), (int)mouseTextColor);
        }
        if (num == -10)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(65f * num2), (int)(byte)(255f * num2), (int)(byte)(110f * num2), (int)mouseTextColor);
        }
        if (num == -1)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(130f * num2), (int)(byte)(130f * num2), (int)(byte)(130f * num2), (int)mouseTextColor);
        }
        if (num == 1)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(150f * num2), (int)(byte)(150f * num2), (int)(byte)(255f * num2), (int)mouseTextColor);
        }
        if (num == 2)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(150f * num2), (int)(byte)(255f * num2), (int)(byte)(150f * num2), (int)mouseTextColor);
        }
        if (num == 3)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(255f * num2), (int)(byte)(200f * num2), (int)(byte)(150f * num2), (int)mouseTextColor);
        }
        if (num == 4)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(255f * num2), (int)(byte)(150f * num2), (int)(byte)(150f * num2), (int)mouseTextColor);
        }
        if (num == 5)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(255f * num2), (int)(byte)(150f * num2), (int)(byte)(255f * num2), (int)mouseTextColor);
        }
        if (num == 6)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(210f * num2), (int)(byte)(160f * num2), (int)(byte)(255f * num2), (int)mouseTextColor);
        }
        if (num == 7)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(150f * num2), (int)(byte)(255f * num2), (int)(byte)(10f * num2), (int)mouseTextColor);
        }
        if (num == 8)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(255f * num2), (int)(byte)(255f * num2), (int)(byte)(10f * num2), (int)mouseTextColor);
        }
        if (num == 9)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(5f * num2), (int)(byte)(200f * num2), (int)(byte)(255f * num2), (int)mouseTextColor);
        }
        if (num == 10)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(255f * num2), (int)(byte)(40f * num2), (int)(byte)(100f * num2), (int)mouseTextColor);
        }
        if (num == 11)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(180f * num2), (int)(byte)(40f * num2), (int)(byte)(255f * num2), (int)mouseTextColor);
        }
        if (num > 11)
        {
            baseColor = RarityLoader.GetRarity(num).RarityColor * num2;
        }
        if (HoverItem.expert || num == -12)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)((float)DiscoR * num2), (int)(byte)((float)DiscoG * num2), (int)(byte)((float)DiscoB * num2), (int)mouseTextColor);
        }
        if (HoverItem.master || num == -13)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)(255f * num2), (int)(byte)(masterColor * 200f * num2), 0, (int)mouseTextColor);
        }
        if (diff == 1)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)((float)(int)((Color)(ref mcColor)).R * num2), (int)(byte)((float)(int)((Color)(ref mcColor)).G * num2), (int)(byte)((float)(int)((Color)(ref mcColor)).B * num2), (int)mouseTextColor);
        }
        if (diff == 2)
        {
            ((Color)(ref baseColor))._002Ector((int)(byte)((float)(int)((Color)(ref hcColor)).R * num2), (int)(byte)((float)(int)((Color)(ref hcColor)).G * num2), (int)(byte)((float)(int)((Color)(ref hcColor)).B * num2), (int)mouseTextColor);
        }
        ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, cursorText, new Vector2((float)X, (float)Y), baseColor, 0f, Vector2.Zero, Vector2.One);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.ModLoader.RarityLoader.GetRarity(), Terraria.Main.hcColor, Terraria.Main.HoverItem, Terraria.Main.masterColor, Terraria.Main.mcColor, Terraria.Main.mouseItem, Terraria.Main.mouseNPCType, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.MouseText_DrawBuffTooltip(), Terraria.Main.MouseText_DrawItemTooltip(), Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, and Terraria.Main.ThickMouse.