TModLoader: Terraria.Main.DoDraw
DoDraw()
void Terraria.Main.DoDraw (GameTime gameTime) inline private
    {
        //IL_18ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_1720: Unknown result type (might be due to invalid IL or missing references)
        //IL_1734: Unknown result type (might be due to invalid IL or missing references)
        //IL_1739: Unknown result type (might be due to invalid IL or missing references)
        //IL_173e: Unknown result type (might be due to invalid IL or missing references)
        //IL_178a: Unknown result type (might be due to invalid IL or missing references)
        //IL_179e: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_17a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_17e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_18ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_18f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_18fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_194a: Unknown result type (might be due to invalid IL or missing references)
        //IL_198c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a0d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a3b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1a72: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ea2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ed9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1acc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ad1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ad5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1ae2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1f47: Unknown result type (might be due to invalid IL or missing references)
        //IL_1de7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e17: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e1c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1e2b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d60: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d75: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1d89: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_0973: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b81: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b86: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b87: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d77: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0db4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed4: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_10ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_1108: Unknown result type (might be due to invalid IL or missing references)
        //IL_1119: Unknown result type (might be due to invalid IL or missing references)
        //IL_1123: Unknown result type (might be due to invalid IL or missing references)
        //IL_1128: Unknown result type (might be due to invalid IL or missing references)
        //IL_112d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1137: Unknown result type (might be due to invalid IL or missing references)
        //IL_113c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1141: Unknown result type (might be due to invalid IL or missing references)
        //IL_114b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1150: Unknown result type (might be due to invalid IL or missing references)
        //IL_1154: Unknown result type (might be due to invalid IL or missing references)
        //IL_1163: Unknown result type (might be due to invalid IL or missing references)
        //IL_1061: Unknown result type (might be due to invalid IL or missing references)
        //IL_118b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1190: Unknown result type (might be due to invalid IL or missing references)
        //IL_1195: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11da: Unknown result type (might be due to invalid IL or missing references)
        //IL_1209: Unknown result type (might be due to invalid IL or missing references)
        //IL_124f: Unknown result type (might be due to invalid IL or missing references)
        //IL_129a: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1311: Unknown result type (might be due to invalid IL or missing references)
        //IL_1015: Unknown result type (might be due to invalid IL or missing references)
        //IL_1017: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_146e: Unknown result type (might be due to invalid IL or missing references)
        //IL_147d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1487: Unknown result type (might be due to invalid IL or missing references)
        //IL_1491: Unknown result type (might be due to invalid IL or missing references)
        //IL_149b: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_14c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_1508: Unknown result type (might be due to invalid IL or missing references)
        //IL_150d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1512: Unknown result type (might be due to invalid IL or missing references)
        //IL_1517: Unknown result type (might be due to invalid IL or missing references)
        //IL_139d: Unknown result type (might be due to invalid IL or missing references)
        //IL_13be: Unknown result type (might be due to invalid IL or missing references)
        //IL_15cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_161a: Unknown result type (might be due to invalid IL or missing references)
        //IL_161f: Unknown result type (might be due to invalid IL or missing references)
        Stopwatch stopwatch = new Stopwatch();
        stopwatch.Start();
        if (showSplash)
        {
            DrawSplash(gameTime);
            TimeLogger.SplashDrawTime(stopwatch.Elapsed.TotalMilliseconds);
            TimeLogger.EndDrawFrame();
            return;
        }
        if (_drawCycleCounter == 0L)
        {
            TileFrameSeed = Utils.RandomNextSeed(TileFrameSeed);
        }
        _drawCycleCounter = (_drawCycleCounter + 1) % 5;
        MenuUI.IsVisible = gameMenu && menuMode == 888;
        InGameUI.IsVisible = !gameMenu && InGameUI.CurrentState != null;
        PlayerInput.UpdateMainMouse();
        RefreshPlayerDrawOrder();
        CaptureManager.Instance.DrawTick();
        TimeLogger.NewDrawFrame();
        if (!gameMenu)
        {
            TilesRenderer.PreparePaintForTilesOnScreen();
        }
        for (int i = 0; i < ContentThatNeedsRenderTargets.Count; i++)
        {
            ContentThatNeedsRenderTargets[i].PrepareRenderTarget(((Game)this).GraphicsDevice, spriteBatch);
        }
        TilePaintSystem.PrepareAllRequests();
        TimeLogger.DetailedDrawTime(0);
        if (loadMap)
        {
            refreshMap = false;
            DrawToMap();
            TimeLogger.DetailedDrawTime(1);
        }
        if (Lighting.UpdateEveryFrame)
        {
            drawToScreen = true;
        }
        else
        {
            drawToScreen = false;
        }
        if (drawToScreen && targetSet)
        {
            ReleaseTargets();
        }
        if (!drawToScreen && !targetSet)
        {
            InitTargets();
        }
        fpsCount++;
        if (!((Game)this).IsActive)
        {
            maxQ = true;
        }
        if (!dedServ)
        {
            UpdateDisplaySettings();
            if (Main.OnPreDraw != null)
            {
                Main.OnPreDraw(gameTime);
            }
        }
        drawsCountedForFPS++;
        screenLastPosition = screenPosition;
        if (stackSplit == 0)
        {
            timesTriedToFastStack = 0;
            stackCounter = 0;
            stackDelay = 7;
            superFastStack = 0;
        }
        else
        {
            stackCounter++;
            int num = 30;
            num = ((stackDelay == 7) ? 30 : ((stackDelay == 6) ? 25 : ((stackDelay == 5) ? 20 : ((stackDelay == 4) ? 15 : ((stackDelay != 3) ? 5 : 10)))));
            if (stackCounter >= num)
            {
                stackDelay--;
                if (stackDelay < 2)
                {
                    stackDelay = 2;
                    superFastStack++;
                }
                if (timesTriedToFastStack < 10)
                {
                    superFastStack = 0;
                }
                timesTriedToFastStack++;
                stackCounter = 0;
            }
        }
        if (myPlayer >= 0)
        {
            player[myPlayer].lastMouseInterface = player[myPlayer].mouseInterface;
            player[myPlayer].mouseInterface = false;
        }
        if (mapTime > 0)
        {
            mapTime--;
        }
        if (gameMenu)
        {
            mapTime = mapTimeMax;
        }
        HoverItem = new Item();
        DoDraw_UpdateCameraPosition();
        CheckMonoliths();
        sunCircle += 0.01f;
        if ((double)sunCircle > 6.285)
        {
            sunCircle -= 6.285f;
        }
        TimeLogger.DetailedDrawReset();
        if (!gameMenu)
        {
            waterfallManager.FindWaterfalls();
            TimeLogger.DetailedDrawTime(2);
            if (renderNow)
            {
                screenLastPosition = screenPosition;
                renderNow = false;
                renderCount = 99;
                ((Game)this).Draw(gameTime);
                Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
                Lighting.LightTiles(firstTileX, lastTileX, firstTileY, lastTileY);
                RenderTiles();
                sceneTilePos.X = screenPosition.X - (float)offScreenRange;
                sceneTilePos.Y = screenPosition.Y - (float)offScreenRange;
                RenderBackground();
                sceneBackgroundPos.X = screenPosition.X - (float)offScreenRange;
                sceneBackgroundPos.Y = screenPosition.Y - (float)offScreenRange;
                RenderWalls();
                sceneWallPos.X = screenPosition.X - (float)offScreenRange;
                sceneWallPos.Y = screenPosition.Y - (float)offScreenRange;
                RenderTiles2();
                sceneTile2Pos.X = screenPosition.X - (float)offScreenRange;
                sceneTile2Pos.Y = screenPosition.Y - (float)offScreenRange;
                RenderWater();
                sceneWaterPos.X = screenPosition.X - (float)offScreenRange;
                sceneWaterPos.Y = screenPosition.Y - (float)offScreenRange;
                renderCount = 99;
            }
            else
            {
                if (renderCount == 3)
                {
                    RenderTiles();
                    sceneTilePos.X = screenPosition.X - (float)offScreenRange;
                    sceneTilePos.Y = screenPosition.Y - (float)offScreenRange;
                }
                if (renderCount == ((Lighting.LegacyEngine.Mode == 0) ? 2 : 3))
                {
                    RenderTiles2();
                    sceneTile2Pos.X = screenPosition.X - (float)offScreenRange;
                    sceneTile2Pos.Y = screenPosition.Y - (float)offScreenRange;
                }
                if (renderCount == ((Lighting.LegacyEngine.Mode != 0) ? 3 : 0))
                {
                    RenderWalls();
                    sceneWallPos.X = screenPosition.X - (float)offScreenRange;
                    sceneWallPos.Y = screenPosition.Y - (float)offScreenRange;
                }
                if (renderCount == 2)
                {
                    RenderBackground();
                    sceneBackgroundPos.X = screenPosition.X - (float)offScreenRange;
                    sceneBackgroundPos.Y = screenPosition.Y - (float)offScreenRange;
                }
                if (renderCount == 1)
                {
                    RenderWater();
                    sceneWaterPos.X = screenPosition.X - (float)offScreenRange;
                    sceneWaterPos.Y = screenPosition.Y - (float)offScreenRange;
                }
            }
            if (render && !gameMenu)
            {
                if (Math.Abs(sceneTilePos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneTilePos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                {
                    RenderTiles();
                    sceneTilePos.X = screenPosition.X - (float)offScreenRange;
                    sceneTilePos.Y = screenPosition.Y - (float)offScreenRange;
                }
                if (Math.Abs(sceneTile2Pos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneTile2Pos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                {
                    RenderTiles2();
                    sceneTile2Pos.X = screenPosition.X - (float)offScreenRange;
                    sceneTile2Pos.Y = screenPosition.Y - (float)offScreenRange;
                }
                if (Math.Abs(sceneBackgroundPos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneBackgroundPos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                {
                    RenderBackground();
                    sceneBackgroundPos.X = screenPosition.X - (float)offScreenRange;
                    sceneBackgroundPos.Y = screenPosition.Y - (float)offScreenRange;
                }
                if (Math.Abs(sceneWallPos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneWallPos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                {
                    RenderWalls();
                    sceneWallPos.X = screenPosition.X - (float)offScreenRange;
                    sceneWallPos.Y = screenPosition.Y - (float)offScreenRange;
                }
                if (Math.Abs(sceneWaterPos.X - (screenPosition.X - (float)offScreenRange)) > (float)offScreenRange || Math.Abs(sceneWaterPos.Y - (screenPosition.Y - (float)offScreenRange)) > (float)offScreenRange)
                {
                    RenderWater();
                    sceneWaterPos.X = screenPosition.X - (float)offScreenRange;
                    sceneWaterPos.Y = screenPosition.Y - (float)offScreenRange;
                }
            }
        }
        if (!loadMap)
        {
            if (!gameMenu)
            {
                TimeLogger.DetailedDrawReset();
                Stopwatch stopwatch2 = new Stopwatch();
                stopwatch2.Start();
                int num12 = 0;
                int x;
                int y;
                while (stopwatch2.ElapsedMilliseconds < 5 && sectionManager.GetNextMapDraw(player[myPlayer].position, out x, out y))
                {
                    DrawToMap_Section(x, y);
                    num12++;
                }
                TimeLogger.DetailedDrawTime(3);
            }
            if (updateMap)
            {
                if (((Game)this).IsActive || netMode == 1)
                {
                    if (refreshMap)
                    {
                        refreshMap = false;
                        sectionManager.ClearMapDraw();
                    }
                    DrawToMap();
                    updateMap = false;
                }
                else if (MapHelper.numUpdateTile > 0)
                {
                    DrawToMap();
                }
                TimeLogger.DetailedDrawTime(4);
            }
        }
        bgParallax = 0.1;
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, backgroundWidth[background]) - (double)(backgroundWidth[background] / 2));
        bgLoops = screenWidth / backgroundWidth[background] + 2;
        bgStartY = 0;
        bgLoopsY = 0;
        bgTopY = (int)((double)(0f - screenPosition.Y) / (worldSurface * 16.0 - 600.0) * 200.0);
        if (gameMenu || netMode == 2)
        {
            bgTopY = -200;
        }
        double num13 = desiredWorldEventsUpdateRate;
        float num14 = 0.0005f * (float)num13;
        if (gameMenu)
        {
            num14 *= 20f;
        }
        if (raining)
        {
            if (cloudAlpha > maxRaining)
            {
                cloudAlpha -= num14;
                if (cloudAlpha < maxRaining)
                {
                    cloudAlpha = maxRaining;
                }
            }
            else if (cloudAlpha < maxRaining)
            {
                cloudAlpha += num14;
                if (cloudAlpha > maxRaining)
                {
                    cloudAlpha = maxRaining;
                }
            }
        }
        else
        {
            cloudAlpha -= num14;
            if (cloudAlpha < 0f)
            {
                cloudAlpha = 0f;
            }
        }
        if (gameMenu || netMode == 2)
        {
            bgDelay = 1000;
            SceneMetrics.EvilTileCount = (int)(bgAlphaFrontLayer[1] * (float)SceneMetrics.CorruptionTileMax);
        }
        Color moonColor = Color.White;
        Color sunColor = Color.White;
        float num15 = SceneMetrics.MushroomTileCount / SceneMetrics.MushroomTileMax;
        float num16 = SmoothedMushroomLightInfluence;
        if (num15 > 0f)
        {
            if (num15 > num16)
            {
                num16 += 0.01f;
            }
            if (num15 < num16)
            {
                num16 -= 0.01f;
            }
        }
        else
        {
            num16 -= 0.02f;
        }
        if (num16 < 0f)
        {
            num16 = 0f;
        }
        if (num16 > 1f)
        {
            num16 = 1f;
        }
        SmoothedMushroomLightInfluence = num16;
        InfoToSetBackColor info = default(InfoToSetBackColor);
        info.isInGameMenuOrIsServer = gameMenu || netMode == 2;
        info.CorruptionBiomeInfluence = (float)SceneMetrics.EvilTileCount / (float)SceneMetrics.CorruptionTileMax;
        info.CrimsonBiomeInfluence = (float)SceneMetrics.BloodTileCount / (float)SceneMetrics.CrimsonTileMax;
        info.JungleBiomeInfluence = (float)SceneMetrics.JungleTileCount / (float)SceneMetrics.JungleTileMax;
        info.MushroomBiomeInfluence = SmoothedMushroomLightInfluence;
        info.GraveyardInfluence = GraveyardVisualIntensity;
        info.BloodMoonActive = bloodMoon || SceneMetrics.BloodMoonMonolith;
        info.LanternNightActive = LanternNight.LanternsUp;
        SetBackColor(info, out sunColor, out moonColor);
        if (gameMenu || netMode == 2)
        {
            bgTopY = 0;
        }
        ApplyColorOfTheSkiesToTiles();
        UpdateAtmosphereTransparencyToSkyColor();
        ((Game)this).GraphicsDevice.Clear(Color.Black);
        ((Game)this).Draw(gameTime);
        float val = (float)screenWidth / (Terraria.ModLoader.ModLoader.removeForcedMinimumZoom ? 8192f : MinimumZoomComparerX);
        float val2 = (float)screenHeight / (Terraria.ModLoader.ModLoader.removeForcedMinimumZoom ? 8192f : MinimumZoomComparerY);
        ForcedMinimumZoom = Math.Max(Math.Max(1f, val), val2);
        GameViewMatrix.Effects = (SpriteEffects)((!gameMenu && player[myPlayer].gravDir != 1f) ? 2 : 0);
        BackgroundViewMatrix.Effects = GameViewMatrix.Effects;
        BackgroundViewMatrix.Zoom = new Vector2(ForcedMinimumZoom);
        GameViewMatrix.Zoom = new Vector2(ForcedMinimumZoom * MathHelper.Clamp(GameZoomTarget, 1f, 2f));
        SystemLoader.ModifyTransformMatrix(ref GameViewMatrix);
        if (gameMenu || player[myPlayer].gravDir == 1f)
        {
            Rasterizer = RasterizerState.CullCounterClockwise;
        }
        else
        {
            Rasterizer = RasterizerState.CullClockwise;
        }
        bool flag = gameMenu;
        if (dontStarveWorld && WorldGen.generatingWorld)
        {
            if (!Terraria.Graphics.Effects.Filters.Scene["Sepia"].IsActive())
            {
                Terraria.Graphics.Effects.Filters.Scene.Activate("Sepia", default(Vector2));
            }
            flag = false;
        }
        else if (flag && Terraria.Graphics.Effects.Filters.Scene["Sepia"].IsActive())
        {
            Terraria.Graphics.Effects.Filters.Scene.Deactivate("Sepia");
        }
        if (Terraria.Graphics.Effects.Filters.Scene["Sepia"].IsInUse())
        {
            flag = false;
        }
        bool flag2 = !(drawToScreen || netMode == 2 || flag) && !mapFullscreen && Lighting.NotRetro && Terraria.Graphics.Effects.Filters.Scene.CanCapture();
        if (flag2)
        {
            Terraria.Graphics.Effects.Filters.Scene.BeginCapture(screenTarget, Color.Black);
        }
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, BackgroundViewMatrix.TransformationMatrix);
        TimeLogger.DetailedDrawReset();
        SceneArea sceneArea = default(SceneArea);
        sceneArea.bgTopY = bgTopY;
        sceneArea.totalHeight = screenHeight;
        sceneArea.totalWidth = screenWidth;
        sceneArea.SceneLocalScreenPositionOffset = Vector2.Zero;
        SceneArea sceneArea2 = sceneArea;
        if (!mapFullscreen)
        {
            unityMouseOver = false;
            if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
            {
                Asset<Texture2D> asset = TextureAssets.Background[background];
                Rectangle destinationRectangle = default(Rectangle);
                ((Rectangle)(ref destinationRectangle))._002Ector(bgStartX, bgTopY, asset.Width(), Math.Max(screenHeight, asset.Height()));
                if (((Rectangle)(ref destinationRectangle)).Bottom < asset.Height())
                {
                    int num17 = asset.Height() - ((Rectangle)(ref destinationRectangle)).Bottom;
                    destinationRectangle.Height += num17;
                }
                for (int j = 0; j < bgLoops; j++)
                {
                    destinationRectangle.X = bgStartX + asset.Width() * j;
                    spriteBatch.Draw(asset.Value, destinationRectangle, ColorOfTheSkies);
                }
                TimeLogger.DetailedDrawTime(6);
            }
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, BackgroundViewMatrix.EffectMatrix);
            if (shimmerAlpha != 1f)
            {
                DrawStarsInBackground(sceneArea2, artificial: false);
            }
            if ((double)(screenPosition.Y / 16f) < worldSurface + 2.0)
            {
                DrawSunAndMoon(sceneArea2, moonColor, sunColor, num16);
            }
            TimeLogger.DetailedDrawTime(7);
        }
        Overlays.Scene.Draw(spriteBatch, RenderLayers.Sky);
        spriteBatch.End();
        Vector2 val3 = screenPosition;
        int num19 = screenWidth;
        int num18 = screenHeight;
        screenWidth = (int)((float)screenWidth / BackgroundViewMatrix.Zoom.X);
        screenHeight = (int)((float)screenHeight / BackgroundViewMatrix.Zoom.Y);
        screenPosition += BackgroundViewMatrix.Translation;
        Matrix transformationMatrix = BackgroundViewMatrix.TransformationMatrix;
        Vector3 translation = ((Matrix)(ref transformationMatrix)).Translation;
        Matrix zoomMatrix = BackgroundViewMatrix.ZoomMatrix;
        ((Matrix)(ref transformationMatrix)).Translation = translation - ((Matrix)(ref zoomMatrix)).Translation * new Vector3(1f, ((Enum)BackgroundViewMatrix.Effects).HasFlag((Enum)(object)(SpriteEffects)2) ? (-1f) : 1f, 1f);
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Rasterizer, (Effect)null, transformationMatrix);
        CurrentFrameFlags.Hacks.CurrentBackgroundMatrixForCreditsRoll = transformationMatrix;
        DrawBG();
        screenWidth = num19;
        screenHeight = num18;
        screenPosition = val3;
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Rasterizer, (Effect)null, GameViewMatrix.TransformationMatrix);
        DrawBackgroundBlackFill();
        spriteBatch.End();
        Overlays.Scene.Draw(spriteBatch, RenderLayers.Landscape, beginSpriteBatch: true);
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Rasterizer, (Effect)null, UIScaleMatrix);
        if (gameMenu || netMode == 2)
        {
            spriteBatch.End();
            PreDrawMenu(out var screenSizeCache, out var screenSizeCacheAfterScaling);
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, Rasterizer, (Effect)null, UIScaleMatrix);
            DrawMenu(gameTime);
            PostDrawMenu(screenSizeCache, screenSizeCacheAfterScaling);
            TimeLogger.MenuDrawTime(stopwatch.Elapsed.TotalMilliseconds);
            TimeLogger.EndDrawFrame();
            if (flag2)
            {
                Terraria.Graphics.Effects.Filters.Scene.EndCapture(null, screenTarget, screenTargetSwap, Color.Black);
            }
            return;
        }
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        DoLightTiles();
        TimeLogger.DetailedDrawReset();
        if (mapFullscreen)
        {
            if (player[myPlayer].talkNPC >= 0 || player[myPlayer].sign >= 0 || (playerInventory && !CaptureManager.Instance.Active))
            {
                player[myPlayer].ToggleInv();
            }
            DrawMap(gameTime);
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerStateForCursor, (DepthStencilState)null, (RasterizerState)null, (Effect)null, UIScaleMatrix);
            PlayerInput.SetZoom_UI();
            DrawFPS();
            DrawPlayerChat();
            DrawPendingMouseText();
            DrawCursor(DrawThickCursor());
            PlayerInput.SetZoom_Unscaled();
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, (DepthStencilState)null, (RasterizerState)null, (Effect)null);
            TimeLogger.MapDrawTime(stopwatch.Elapsed.TotalMilliseconds);
            TimeLogger.EndDrawFrame();
            PlayerInput.SetDesiredZoomContext(ZoomContext.Unscaled);
            CaptureManager.Instance.Update();
            if (CaptureManager.Instance.Active)
            {
                CaptureManager.Instance.Draw(spriteBatch);
            }
            spriteBatch.End();
            if (mouseLeft)
            {
                mouseLeftRelease = false;
            }
            else
            {
                mouseLeftRelease = true;
            }
            return;
        }
        if (shimmerAlpha > 0f)
        {
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, Vector2.Zero, (Rectangle?)null, Color.Black * shimmerAlpha, 0f, Vector2.Zero, new Vector2(Camera.UnscaledSize.X + (float)(offScreenRange * 2), Camera.UnscaledSize.Y + (float)(offScreenRange * 2)), (SpriteEffects)0, 0f);
        }
        Overlays.Scene.Draw(spriteBatch, RenderLayers.InWorldUI);
        _ = Color.White;
        if (drawToScreen)
        {
            DrawWaters(isBackground: true);
        }
        else
        {
            spriteBatch.Draw((Texture2D)(object)backWaterTarget, sceneBackgroundPos - screenPosition, Color.White);
            TimeLogger.DetailedDrawTime(11);
        }
        Overlays.Scene.Draw(spriteBatch, RenderLayers.BackgroundWater);
        float x2 = (sceneBackgroundPos.X - screenPosition.X + (float)offScreenRange) * caveParallax - (float)offScreenRange;
        if (shimmerAlpha > 0f)
        {
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, (DepthStencilState)null, (RasterizerState)null, (Effect)null);
            PlayerInput.SetZoom_Unscaled();
            DrawStarsInBackground(sceneArea2, artificial: true);
            spriteBatch.End();
            PlayerInput.SetDesiredZoomContext(ZoomContext.World);
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        }
        if (drawToScreen)
        {
            tileBatch.Begin();
            DrawBackground();
            tileBatch.End();
        }
        else
        {
            spriteBatch.Draw((Texture2D)(object)backgroundTarget, new Vector2(x2, sceneBackgroundPos.Y - screenPosition.Y), Color.White);
            TimeLogger.DetailedDrawTime(12);
        }
        Overlays.Scene.Draw(spriteBatch, RenderLayers.Background);
        ScreenDarkness.DrawBack(spriteBatch);
        magmaBGFrameCounter++;
        if (magmaBGFrameCounter >= 8)
        {
            magmaBGFrameCounter = 0;
            magmaBGFrame++;
            if (magmaBGFrame >= 3)
            {
                magmaBGFrame = 0;
            }
        }
        DoDraw_WallsTilesNPCs();
        Overlays.Scene.Draw(spriteBatch, RenderLayers.TilesAndNPCs);
        if (!mapFullscreen && mapStyle == 2)
        {
            try
            {
                DrawMap(gameTime);
            }
            catch (Exception e)
            {
                if (!ignoreErrors)
                {
                    throw;
                }
                TimeLogger.DrawException(e);
            }
        }
        TimeLogger.DetailedDrawReset();
        spriteBatch.End();
        SystemLoader.PostDrawTiles();
        TimeLogger.DetailedDrawTime(35);
        HasInteractibleObjectThatIsNotATile = false;
        SortDrawCacheWorms();
        DrawSuperSpecialProjectiles(DrawCacheFirstFractals);
        DrawCachedProjs(DrawCacheProjsBehindProjectiles);
        DrawProjectiles();
        spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        ParticleSystem_World_BehindPlayers.Settings.AnchorPosition = -screenPosition;
        ParticleSystem_World_BehindPlayers.Draw(spriteBatch);
        spriteBatch.End();
        DrawPlayers_AfterProjectiles();
        DrawCachedProjs(DrawCacheProjsOverPlayers);
        spriteBatch.Begin((SpriteSortMode)1, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        ParticleSystem_World_OverPlayers.Settings.AnchorPosition = -screenPosition;
        ParticleSystem_World_OverPlayers.Draw(spriteBatch);
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        DrawCachedNPCs(DrawCacheNPCsOverPlayers, behindTiles: false);
        if (!gamePaused)
        {
            essScale += (float)essDir * 0.01f;
            if (essScale > 1f)
            {
                essDir = -1;
                essScale = 1f;
            }
            if ((double)essScale < 0.7)
            {
                essDir = 1;
                essScale = 0.7f;
            }
        }
        DrawItems();
        TimeLogger.DetailedDrawTime(22);
        DrawRain();
        if (ignoreErrors)
        {
            try
            {
                DrawGore();
            }
            catch (Exception e2)
            {
                TimeLogger.DrawException(e2);
            }
        }
        else
        {
            DrawGore();
        }
        spriteBatch.End();
        DrawDust();
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        Overlays.Scene.Draw(spriteBatch, RenderLayers.Entities);
        if (drawToScreen)
        {
            DrawWaters();
            if (WiresUI.Settings.DrawWires)
            {
                DrawWires();
            }
        }
        else
        {
            spriteBatch.Draw((Texture2D)(object)waterTarget, sceneWaterPos - screenPosition, Color.White);
            if (WiresUI.Settings.DrawWires)
            {
                DrawWires();
            }
            TimeLogger.DetailedDrawTime(26);
        }
        if (shimmerAlpha > 0f)
        {
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, (DepthStencilState)null, (RasterizerState)null, (Effect)null, BackgroundViewMatrix.EffectMatrix);
            PlayerInput.SetZoom_Unscaled();
            DrawStarsInForeground(sceneArea2);
            spriteBatch.End();
            PlayerInput.SetDesiredZoomContext(ZoomContext.World);
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        }
        Overlays.Scene.Draw(spriteBatch, RenderLayers.ForegroundWater);
        DrawCachedProjs(DrawCacheProjsOverWiresUI, startSpriteBatch: false);
        DrawInfernoRings();
        ScreenDarkness.DrawFront(spriteBatch);
        MoonlordDeathDrama.DrawWhite(spriteBatch);
        ScreenObstruction.Draw(spriteBatch);
        TimeLogger.DetailedDrawReset();
        spriteBatch.End();
        Overlays.Scene.Draw(spriteBatch, RenderLayers.All, beginSpriteBatch: true);
        if (flag2)
        {
            Terraria.Graphics.Effects.Filters.Scene.EndCapture(null, screenTarget, screenTargetSwap, Color.Black);
        }
        TimeLogger.DetailedDrawTime(36);
        if (!hideUI)
        {
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, (DepthStencilState)null, (RasterizerState)null, (Effect)null, UIScaleMatrix);
            TimeLogger.DetailedDrawReset();
            DrawPlayerChatBubbles();
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, (DepthStencilState)null, (RasterizerState)null, (Effect)null, GameViewMatrix.ZoomMatrix);
            float targetScale = CombatText.TargetScale;
            Vector2 origin = default(Vector2);
            Color color = default(Color);
            for (int k = 0; k < 100; k++)
            {
                if (!combatText[k].active)
                {
                    continue;
                }
                int num2 = 0;
                if (combatText[k].crit)
                {
                    num2 = 1;
                }
                Vector2 vector2 = FontAssets.CombatText[num2].Value.MeasureString(combatText[k].text);
                ((Vector2)(ref origin))._002Ector(vector2.X * 0.5f, vector2.Y * 0.5f);
                float num3 = combatText[k].scale / targetScale;
                float num4 = (int)((Color)(ref combatText[k].color)).R;
                float num5 = (int)((Color)(ref combatText[k].color)).G;
                float num6 = (int)((Color)(ref combatText[k].color)).B;
                float num7 = (int)((Color)(ref combatText[k].color)).A;
                num4 *= num3 * combatText[k].alpha * 0.3f;
                num6 *= num3 * combatText[k].alpha * 0.3f;
                num5 *= num3 * combatText[k].alpha * 0.3f;
                num7 *= num3 * combatText[k].alpha;
                ((Color)(ref color))._002Ector((int)num4, (int)num5, (int)num6, (int)num7);
                for (int l = 0; l < 5; l++)
                {
                    float num8 = 0f;
                    float num9 = 0f;
                    switch (l)
                    {
                    case 0:
                        num8 -= targetScale;
                        break;
                    case 1:
                        num8 += targetScale;
                        break;
                    case 2:
                        num9 -= targetScale;
                        break;
                    case 3:
                        num9 += targetScale;
                        break;
                    default:
                        num4 = (float)(int)((Color)(ref combatText[k].color)).R * num3 * combatText[k].alpha;
                        num6 = (float)(int)((Color)(ref combatText[k].color)).B * num3 * combatText[k].alpha;
                        num5 = (float)(int)((Color)(ref combatText[k].color)).G * num3 * combatText[k].alpha;
                        num7 = (float)(int)((Color)(ref combatText[k].color)).A * num3 * combatText[k].alpha;
                        ((Color)(ref color))._002Ector((int)num4, (int)num5, (int)num6, (int)num7);
                        break;
                    }
                    if (player[myPlayer].gravDir == -1f)
                    {
                        float num10 = combatText[k].position.Y - screenPosition.Y;
                        num10 = (float)screenHeight - num10;
                        spriteBatch.DrawString(FontAssets.CombatText[num2].Value, combatText[k].text, new Vector2(combatText[k].position.X - screenPosition.X + num8 + origin.X, num10 + num9 + origin.Y), color, combatText[k].rotation, origin, combatText[k].scale, (SpriteEffects)0, 0f);
                    }
                    else
                    {
                        spriteBatch.DrawString(FontAssets.CombatText[num2].Value, combatText[k].text, new Vector2(combatText[k].position.X - screenPosition.X + num8 + origin.X, combatText[k].position.Y - screenPosition.Y + num9 + origin.Y), color, combatText[k].rotation, origin, combatText[k].scale, (SpriteEffects)0, 0f);
                    }
                }
            }
            targetScale = PopupText.TargetScale;
            if (targetScale == 0f)
            {
                targetScale = 1f;
            }
            DrawItemTextPopups(targetScale);
            PlayerInput.SetZoom_UI();
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, (DepthStencilState)null, (RasterizerState)null, (Effect)null, UIScaleMatrix);
            DrawNetplayStatusText();
            DrawFPS();
            spriteBatch.End();
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, (DepthStencilState)null, (RasterizerState)null, (Effect)null, GameViewMatrix.ZoomMatrix);
            PlayerInput.SetZoom_World();
            if (BlackFadeIn > 0)
            {
                if (BlackFadeIn < 0)
                {
                    BlackFadeIn = 0;
                }
                int num11 = BlackFadeIn;
                if (num11 > 255)
                {
                    num11 = 255;
                }
                BlackFadeIn -= 25;
                spriteBatch.Draw(TextureAssets.SplashTexture16x9.Value, new Rectangle(0, 0, screenWidth, screenHeight), new Color(0, 0, 0, num11));
            }
            spriteBatch.End();
            if (!mapFullscreen)
            {
                if (ignoreErrors)
                {
                    try
                    {
                        DrawInterface(gameTime);
                    }
                    catch (Exception e3)
                    {
                        TimeLogger.DrawException(e3);
                    }
                }
                else
                {
                    DrawInterface(gameTime);
                }
            }
            TimeLogger.DetailedDrawTime(27);
        }
        else
        {
            maxQ = true;
        }
        TimeLogger.DetailedDrawTime(37);
        if (mouseLeft)
        {
            mouseLeftRelease = false;
        }
        else
        {
            mouseLeftRelease = true;
        }
        if (mouseRight)
        {
            mouseRightRelease = false;
        }
        else
        {
            mouseRightRelease = true;
        }
        if (mouseMiddle)
        {
            mouseMiddleRelease = false;
        }
        else
        {
            mouseMiddleRelease = true;
        }
        if (mouseXButton1)
        {
            mouseXButton1Release = false;
        }
        else
        {
            mouseXButton1Release = true;
        }
        if (mouseXButton2)
        {
            mouseXButton2Release = false;
        }
        else
        {
            mouseXButton2Release = true;
        }
        if (!PlayerInput.Triggers.Current.MouseRight && !PlayerInput.Triggers.Current.MouseLeft && !preventStackSplitReset)
        {
            stackSplit = 0;
        }
        if (stackSplit > 0)
        {
            stackSplit--;
            if (stackSplit == 0)
            {
                preventStackSplitReset = false;
            }
        }
        TimeLogger.RenderTime(renderCount, stopwatch.Elapsed.TotalMilliseconds);
        TimeLogger.EndDrawFrame();
    }
References Terraria.Main._drawCycleCounter, Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.Graphics.Capture.CaptureManager.Active, Terraria.CombatText.alpha, Terraria.Main.ApplyColorOfTheSkiesToTiles(), Terraria.GameContent.TextureAssets.Background, Terraria.Main.background, Terraria.Main.backgroundTarget, Terraria.Main.BackgroundViewMatrix, Terraria.Main.backgroundWidth, Terraria.Main.backWaterTarget, Terraria.Graphics.TileBatch.Begin(), Terraria.Graphics.Effects.FilterManager.BeginCapture(), Terraria.Main.bgAlphaFrontLayer, Terraria.Main.bgDelay, Terraria.Main.bgLoops, Terraria.Main.bgLoopsY, Terraria.Main.bgParallax, Terraria.Main.bgStartX, Terraria.Main.bgStartY, Terraria.Main.bgTopY, Terraria.Main.BlackFadeIn, Terraria.Main.bloodMoon, Terraria.SceneMetrics.BloodMoonMonolith, Terraria.SceneMetrics.BloodTileCount, Terraria.Graphics.Effects.FilterManager.CanCapture(), Terraria.Main.caveParallax, Terraria.Main.CheckMonoliths(), Terraria.WorldSections.ClearMapDraw(), Terraria.Main.cloudAlpha, Terraria.Graphics.Light.Color, Terraria.CombatText.color, Terraria.Main.ColorOfTheSkies, Terraria.GameContent.FontAssets.CombatText, Terraria.Main.combatText, Terraria.Main.ContentThatNeedsRenderTargets, Terraria.SceneMetrics.CorruptionTileMax, Terraria.SceneMetrics.CrimsonTileMax, Terraria.GameInput.TriggersPack.Current, Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Main.dedServ, Terraria.Main.DefaultSamplerState, Terraria.Main.desiredWorldEventsUpdateRate, Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.Main.DoDraw_UpdateCameraPosition(), Terraria.Main.DoDraw_WallsTilesNPCs(), Terraria.Main.DoLightTiles(), Terraria.Main.dontStarveWorld, Terraria.Graphics.Capture.CaptureManager.Draw(), Terraria.GameContent.Events.ScreenObstruction.Draw(), Terraria.Graphics.Renderers.ParticleRenderer.Draw(), Terraria.Graphics.Effects.OverlayManager.Draw(), Terraria.GameContent.Events.ScreenDarkness.DrawBack(), Terraria.Main.DrawBackground(), Terraria.Main.DrawBackgroundBlackFill(), Terraria.Main.DrawBG(), Terraria.Main.DrawCachedNPCs(), Terraria.Main.DrawCachedProjs(), Terraria.Main.DrawCacheFirstFractals, Terraria.Main.DrawCacheNPCsOverPlayers, Terraria.Main.DrawCacheProjsBehindProjectiles, Terraria.Main.DrawCacheProjsOverPlayers, Terraria.Main.DrawCacheProjsOverWiresUI, Terraria.Main.DrawCursor(), Terraria.Main.DrawDust(), Terraria.TimeLogger.DrawException(), Terraria.Main.DrawFPS(), Terraria.GameContent.Events.ScreenDarkness.DrawFront(), Terraria.Main.DrawGore(), Terraria.Main.DrawInfernoRings(), Terraria.Main.DrawInterface(), Terraria.Main.DrawItems(), Terraria.Main.DrawItemTextPopups(), Terraria.Main.DrawMap(), Terraria.Main.DrawMenu(), Terraria.Main.DrawNetplayStatusText(), Terraria.Main.DrawPendingMouseText(), Terraria.Main.DrawPlayerChat(), Terraria.Main.DrawPlayerChatBubbles(), Terraria.Main.DrawPlayers_AfterProjectiles(), Terraria.Main.DrawProjectiles(), Terraria.Main.DrawRain(), Terraria.Main.drawsCountedForFPS, Terraria.Main.DrawSplash(), Terraria.Main.DrawStarsInBackground(), Terraria.Main.DrawStarsInForeground(), Terraria.Main.DrawSunAndMoon(), Terraria.Main.DrawSuperSpecialProjectiles(), Terraria.Main.DrawThickCursor(), Terraria.Graphics.Capture.CaptureManager.DrawTick(), Terraria.Main.DrawToMap(), Terraria.Main.DrawToMap_Section(), Terraria.Main.drawToScreen, Terraria.Main.DrawWaters(), Terraria.GameContent.Events.MoonlordDeathDrama.DrawWhite(), Terraria.GameContent.UI.WiresUI.Settings.DrawWires, Terraria.Main.DrawWires(), Terraria.Graphics.SpriteViewMatrix.EffectMatrix, Terraria.Graphics.SpriteViewMatrix.Effects, Terraria.Graphics.TileBatch.End(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.TimeLogger.EndDrawFrame(), Terraria.Main.essDir, Terraria.Main.essScale, Terraria.SceneMetrics.EvilTileCount, Terraria.WaterfallManager.FindWaterfalls(), Terraria.Main.firstTileX, Terraria.Main.firstTileY, Terraria.Main.ForcedMinimumZoom, Terraria.Main.fpsCount, Terraria.Main.gameMenu, Terraria.Main.gamePaused, Terraria.Main.GameViewMatrix, Terraria.Main.GameZoomTarget, Terraria.WorldGen.generatingWorld, Terraria.WorldSections.GetNextMapDraw(), Terraria.Main.GraveyardVisualIntensity, Terraria.Main.HasInteractibleObjectThatIsNotATile, Terraria.Main.hideUI, Terraria.Main.HoverItem, Terraria.Main.ignoreErrors, Terraria.Main.InitTargets(), Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.SceneMetrics.JungleTileCount, Terraria.SceneMetrics.JungleTileMax, Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Player.lastMouseInterface, Terraria.Main.lastTileX, Terraria.Main.lastTileY, Terraria.Lighting.LegacyEngine, Terraria.Lighting.LightTiles(), Terraria.Main.loadMap, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.magmaBGFrame, Terraria.Main.magmaBGFrameCounter, Terraria.TimeLogger.MapDrawTime(), Terraria.Main.mapFullscreen, Terraria.Main.mapStyle, Terraria.Main.mapTime, Terraria.Main.mapTimeMax, Terraria.Main.maxQ, Terraria.Main.maxRaining, Terraria.TimeLogger.MenuDrawTime(), Terraria.Main.menuMode, Terraria.Main.MinimumZoomComparerX, Terraria.Main.MinimumZoomComparerY, Terraria.ModLoader.SystemLoader.ModifyTransformMatrix(), Terraria.Player.mouseInterface, Terraria.GameInput.TriggersSet.MouseLeft, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseMiddle, Terraria.Main.mouseMiddleRelease, Terraria.GameInput.TriggersSet.MouseRight, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.mouseXButton1, Terraria.Main.mouseXButton1Release, Terraria.Main.mouseXButton2, Terraria.Main.mouseXButton2Release, Terraria.SceneMetrics.MushroomTileMax, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.TimeLogger.NewDrawFrame(), Terraria.Lighting.NotRetro, Terraria.Map.MapHelper.numUpdateTile, Terraria.Main.offScreenRange, Terraria.Main.OnPreDraw, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.CombatText.position, Terraria.Entity.position, Terraria.Main.PostDrawMenu(), Terraria.ModLoader.SystemLoader.PostDrawTiles(), Terraria.Main.PreDrawMenu(), Terraria.GameContent.TilePaintSystemV2.PrepareAllRequests(), Terraria.GameContent.Drawing.TileDrawing.PreparePaintForTilesOnScreen(), Terraria.Main.preventStackSplitReset, Terraria.Main.raining, Terraria.Utils.RandomNextSeed(), Terraria.Main.Rasterizer, Terraria.Main.refreshMap, Terraria.Main.RefreshPlayerDrawOrder(), Terraria.Main.ReleaseTargets(), Terraria.ModLoader.ModLoader.removeForcedMinimumZoom, Terraria.Main.render, Terraria.Main.RenderBackground(), Terraria.Main.renderCount, Terraria.Main.renderNow, Terraria.Main.RenderTiles(), Terraria.Main.RenderTiles2(), Terraria.TimeLogger.RenderTime(), Terraria.Main.RenderWalls(), Terraria.Main.RenderWater(), Terraria.CombatText.rotation, Terraria.Main.SamplerStateForCursor, Terraria.CombatText.scale, Terraria.Graphics.Effects.Filters.Scene, Terraria.Graphics.Effects.Overlays.Scene, Terraria.Main.sceneBackgroundPos, Terraria.Main.sceneTile2Pos, Terraria.Main.sceneTilePos, Terraria.Main.sceneWallPos, Terraria.Main.sceneWaterPos, Terraria.Main.screenHeight, Terraria.Main.screenLastPosition, Terraria.Main.screenPosition, Terraria.Main.screenTarget, Terraria.Main.screenTargetSwap, Terraria.Main.screenWidth, Terraria.Main.sectionManager, Terraria.Main.SetBackColor(), Terraria.GameInput.PlayerInput.SetDesiredZoomContext(), Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.GameInput.PlayerInput.SetZoom_World(), Terraria.Main.shimmerAlpha, Terraria.Main.showSplash, Terraria.Main.sign, Terraria.Main.SmoothedMushroomLightInfluence, Terraria.Main.SortDrawCacheWorms(), Terraria.TimeLogger.SplashDrawTime(), Terraria.GameContent.TextureAssets.SplashTexture16x9, Terraria.Main.spriteBatch, Terraria.Main.stackCounter, Terraria.Main.stackDelay, Terraria.Main.stackSplit, Terraria.Main.sunCircle, Terraria.Main.superFastStack, Terraria.CombatText.TargetScale, Terraria.PopupText.TargetScale, Terraria.Main.targetSet, Terraria.CombatText.text, Terraria.Main.tileBatch, Terraria.Main.TileFrameSeed, Terraria.Main.TilePaintSystem, Terraria.Main.TilesRenderer, Terraria.Main.timesTriedToFastStack, Terraria.Player.ToggleInv(), Terraria.Main.Transform, Terraria.Graphics.SpriteViewMatrix.TransformationMatrix, Terraria.Graphics.SpriteViewMatrix.Translation, Terraria.GameInput.PlayerInput.Triggers, Terraria.Main.UIScaleMatrix, Terraria.Main.unityMouseOver, Terraria.Graphics.Camera.UnscaledSize, Terraria.Graphics.Capture.CaptureManager.Update(), Terraria.Main.UpdateAtmosphereTransparencyToSkyColor(), Terraria.Main.UpdateDisplaySettings(), Terraria.Lighting.UpdateEveryFrame, Terraria.GameInput.PlayerInput.UpdateMainMouse(), Terraria.Main.updateMap, Terraria.Main.waterfallManager, Terraria.Main.waterTarget, Terraria.Main.worldSurface, Terraria.Graphics.SpriteViewMatrix.Zoom, and Terraria.Graphics.SpriteViewMatrix.ZoomMatrix.
Referenced by Terraria.Main.Draw_Inner().