TModLoader: Terraria.Main.DrawProj_Inner_DoDrawProj
DrawProj_Inner_DoDrawProj()
void Terraria.Main.DrawProj_Inner_DoDrawProj (Projectile proj, Vector2 mountedCenter, float polePosX, float polePosY) inline private
    {
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0093: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        Color projectileColor = Lighting.GetColor((int)((double)proj.position.X + (double)proj.width * 0.5) / 16, (int)(((double)proj.position.Y + (double)proj.height * 0.5) / 16.0));
        if (proj.hide && !ProjectileID.Sets.DontAttachHideToAlpha[proj.type])
        {
            projectileColor = Lighting.GetColor((int)mountedCenter.X / 16, (int)(mountedCenter.Y / 16f));
        }
        if (proj.type == 14)
        {
            projectileColor = Color.White;
        }
        if (ProjectileLoader.PreDraw(proj, ref projectileColor))
        {
            bool earlyReturn = true;
            DrawProj_DrawVoidLens(proj, ref earlyReturn);
            if (!earlyReturn)
            {
                earlyReturn = true;
                DrawProj_DrawSpecialProjs(proj, ref earlyReturn);
                if (!earlyReturn)
                {
                    DrawProj_DrawNormalProjs(proj, polePosX, polePosY, mountedCenter, ref projectileColor);
                }
            }
        }
        ProjectileLoader.PostDraw(proj, projectileColor);
    }
References Terraria.ID.ProjectileID.Sets.DontAttachHideToAlpha, Terraria.Main.DrawProj_DrawNormalProjs(), Terraria.Main.DrawProj_DrawSpecialProjs(), Terraria.Main.DrawProj_DrawVoidLens(), Terraria.Lighting.GetColor(), Terraria.ModLoader.ProjectileLoader.PostDraw(), and Terraria.ModLoader.ProjectileLoader.PreDraw().
Referenced by Terraria.Main.DrawProj_Inner().