TModLoader: Terraria.Main.TryInteractingWithMoneyTrough2
TryInteractingWithMoneyTrough2()
static void Terraria.Main.TryInteractingWithMoneyTrough2 (Projectile proj) inline static private
Definition at line 48768 of file Main.cs.
    {
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        if (gamePaused && !gameMenu)
        {
            return;
        }
        Vector2 vector = proj.position - screenPosition;
        if (!((float)mouseX > vector.X) || !((float)mouseX < vector.X + (float)proj.width) || !((float)mouseY > vector.Y) || !((float)mouseY < vector.Y + (float)proj.height))
        {
            return;
        }
        int num = (int)(player[myPlayer].Center.X / 16f);
        int num2 = (int)(player[myPlayer].Center.Y / 16f);
        int num3 = (int)proj.Center.X / 16;
        int num4 = (int)proj.Center.Y / 16;
        int lastTileRangeX = player[myPlayer].lastTileRangeX;
        int lastTileRangeY = player[myPlayer].lastTileRangeY;
        if (num < num3 - lastTileRangeX || num > num3 + lastTileRangeX + 1 || num2 < num4 - lastTileRangeY || num2 > num4 + lastTileRangeY + 1)
        {
            return;
        }
        Player localPlayer = LocalPlayer;
        player[myPlayer].noThrow = 2;
        player[myPlayer].cursorItemIconEnabled = true;
        player[myPlayer].cursorItemIconID = 3213;
        if (PlayerInput.UsingGamepad)
        {
            player[myPlayer].GamepadEnableGrappleCooldown();
        }
        if (mouseRight && mouseRightRelease && Player.BlockInteractionWithProjectiles == 0)
        {
            mouseRightRelease = false;
            localPlayer.tileInteractAttempted = true;
            localPlayer.tileInteractionHappened = true;
            localPlayer.releaseUseTile = false;
            if (player[myPlayer].chest == -2)
            {
                SoundEngine.PlaySound(in SoundID.Item59);
                player[myPlayer].chest = -1;
                Recipe.FindRecipes();
                return;
            }
            player[myPlayer].piggyBankProjTracker.Set(proj);
            player[myPlayer].chest = -2;
            player[myPlayer].chestX = (int)(proj.Center.X / 16f);
            player[myPlayer].chestY = (int)(proj.Center.Y / 16f);
            player[myPlayer].SetTalkNPC(-1);
            SetNPCShopIndex(0);
            playerInventory = true;
            SoundEngine.PlaySound(in SoundID.Item59);
            Recipe.FindRecipes();
        }
    }
References Terraria.Player.BlockInteractionWithProjectiles, Terraria.Main.chest, Terraria.Player.chest, Terraria.Player.chestX, Terraria.Player.chestY, Terraria.Player.cursorItemIconEnabled, Terraria.Player.cursorItemIconID, Terraria.Recipe.FindRecipes(), Terraria.Main.gameMenu, Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Main.gamePaused, Terraria.ID.SoundID.Item59, Terraria.Player.lastTileRangeX, Terraria.Player.lastTileRangeY, Terraria.Main.LocalPlayer, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Player.noThrow, Terraria.Player.piggyBankProjTracker, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.screenPosition, Terraria.DataStructures.TrackedProjectileReference.Set(), Terraria.Main.SetNPCShopIndex(), Terraria.Player.SetTalkNPC(), and Terraria.GameInput.PlayerInput.UsingGamepad.