TModLoader: Terraria.Main.InitTMLContentManager
InitTMLContentManager()
void Terraria.Main.InitTMLContentManager () inline package
Definition at line 83951 of file Main.cs.
    {
        if (dedServ)
        {
            return;
        }
        string vanillaContentFolder;
        if (SocialAPI.Mode == SocialMode.Steam)
        {
            vanillaContentFolder = Path.Combine(Steam.GetSteamTerrariaInstallDir(), "Content");
        }
        else
        {
            vanillaContentFolder = (Platform.IsOSX ? "../Terraria/Terraria.app/Contents/Resources/Content" : "../Terraria/Content");
            if (!Directory.Exists(vanillaContentFolder))
            {
                vanillaContentFolder = (Platform.IsOSX ? "../Terraria.app/Contents/Resources/Content" : "../Content");
            }
            Logging.tML.Info((object)("Content folder of Terraria GOG Install Location assumed to be: " + Path.GetFullPath(vanillaContentFolder)));
        }
        if (!Directory.Exists(vanillaContentFolder))
        {
            ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.ContentFolderNotFound"));
        }
        if (!File.Exists(Path.Combine(vanillaContentFolder, "Images", "Projectile_981.xnb")))
        {
            ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.TerrariaOutOfDateMessage"));
        }
        TMLContentManager localOverrideContentManager = null;
        if (Directory.Exists(Path.Combine("Content", "Images")))
        {
            localOverrideContentManager = new TMLContentManager(((Game)this).Content.ServiceProvider, "Content", null);
        }
        ((Game)this).Content = (ContentManager)(object)new TMLContentManager(((Game)this).Content.ServiceProvider, vanillaContentFolder, localOverrideContentManager);
    }
References Terraria.Main.dedServ, Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.ModLoader.Engine.Steam.GetSteamTerrariaInstallDir(), Terraria.Localization.Language.GetTextValue(), Terraria.Social.SocialAPI.Mode, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.Main.Initialize().