TModLoader: Terraria.Main.DrawSettingButton
DrawSettingButton()
static void Terraria.Main.DrawSettingButton (ref bool mouseOver, ref float scale, int posX, int posY, string text, string textSizeMatcher, Action clickAction) inline static
Definition at line 58655 of file Main.cs.
    {
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0022: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_017e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        Vector2 val = FontAssets.MouseText.Value.MeasureString(textSizeMatcher);
        Vector2 vector2 = FontAssets.MouseText.Value.MeasureString(text);
        Vector2 vector3 = FontAssets.DeathText.Value.MeasureString(text);
        float num = val.X / vector2.X;
        if (mouseOver)
        {
            if ((double)scale < 0.96)
            {
                scale += 0.02f;
            }
        }
        else if ((double)scale > 0.8)
        {
            scale -= 0.02f;
        }
        UILinkPointNavigator.SetPosition(308, new Vector2((float)posX, (float)posY));
        for (int i = 0; i < 5; i++)
        {
            int num2 = 0;
            int num3 = 0;
            Color color = Color.Black;
            if (i == 0)
            {
                num2 = -2;
            }
            if (i == 1)
            {
                num2 = 2;
            }
            if (i == 2)
            {
                num3 = -2;
            }
            if (i == 3)
            {
                num3 = 2;
            }
            if (i == 4)
            {
                color = Color.White;
            }
            spriteBatch.DrawString(FontAssets.DeathText.Value, text, new Vector2((float)(posX + num2), (float)(posY + num3)), color, 0f, new Vector2(vector3.X / 2f, vector3.Y / 2f), (scale - 0.2f) * num, (SpriteEffects)0, 0f);
        }
        if ((float)mouseX > (float)posX - vector3.X / 2f && (float)mouseX < (float)posX + vector3.X / 2f && (float)mouseY > (float)posY - vector3.Y / 2f && (float)mouseY < (float)posY + vector3.Y / 2f - 10f && !LocalPlayer.mouseInterface)
        {
            if (!PlayerInput.IgnoreMouseInterface)
            {
                if (!mouseOver)
                {
                    SoundEngine.PlaySound(12);
                }
                mouseOver = true;
                player[myPlayer].mouseInterface = true;
                if (mouseLeftRelease && mouseLeft)
                {
                    mouseOver = false;
                    scale = 0.8f;
                    clickAction();
                }
            }
        }
        else
        {
            mouseOver = false;
        }
    }
References Terraria.Graphics.Light.Color, Terraria.GameContent.FontAssets.DeathText, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.LocalPlayer, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawInterface_29_SettingsButton().