TModLoader: Terraria.Main.Ambience
Ambience()
static void Terraria.Main.Ambience () inline static
    {
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        ambientCounter++;
        if (ambientCounter >= 15)
        {
            ambientCounter = 0;
            LocalPlayer.Center.ToPoint();
            float usedWaterVolume = MathHelper.Clamp(ambientWaterfallStrength / 50f * (1f - shimmerAlpha), 0f, 1f);
            HandleAmbientSound(in SoundID.Waterfall, ref waterfallSoundSlot, usedWaterVolume, new Vector2(ambientWaterfallX, ambientWaterfallY));
            float num = Math.Abs(ambientLavaX - (screenPosition.X + (float)(screenWidth / 2))) + Math.Abs(ambientLavaY - (screenPosition.Y + (float)(screenHeight / 2)));
            float num5 = Math.Abs(ambientLavafallX - (screenPosition.X + (float)(screenWidth / 2))) + Math.Abs(ambientLavafallY - (screenPosition.Y + (float)(screenHeight / 2)));
            float num2 = ambientLavaX;
            float num3 = ambientLavaY;
            if (num5 < num)
            {
                num2 = ambientLavafallX;
                num3 = ambientLavafallY;
            }
            float num4 = ambientLavafallStrength + ambientLavaStrength;
            float usedLavaVolume = ((ambientLavaStrength > 0f) ? MathHelper.Clamp(num4 / 50f, 0f, 1f) : 0f);
            HandleAmbientSound(in SoundID.Lavafall, ref lavafallSoundSlot, usedLavaVolume, new Vector2(num2, num3));
        }
        static void HandleAmbientSound(in SoundStyle soundStyle, ref SlotId slot, float volume, Vector2 position)
        {
            //IL_0044: Unknown result type (might be due to invalid IL or missing references)
            //IL_001b: Unknown result type (might be due to invalid IL or missing references)
            SoundEngine.TryGetActiveSound(slot, out ActiveSound activeSound);
            if (volume > 0f)
            {
                if (activeSound == null)
                {
                    slot = SoundEngine.PlaySound(in soundStyle, position);
                    if (!SoundEngine.TryGetActiveSound(slot, out activeSound))
                    {
                        return;
                    }
                }
                activeSound.Volume = volume;
                activeSound.Position = position;
            }
            else if (activeSound != null)
            {
                activeSound.Stop();
                slot = SlotId.Invalid;
            }
        }
    }
References Terraria.Main.ambientCounter, Terraria.Main.ambientLavafallStrength, Terraria.Main.ambientLavafallX, Terraria.Main.ambientLavafallY, Terraria.Main.ambientLavaStrength, Terraria.Main.ambientLavaX, Terraria.Main.ambientLavaY, Terraria.Main.ambientWaterfallStrength, Terraria.Main.ambientWaterfallX, Terraria.Main.ambientWaterfallY, Terraria.ID.SoundID.Lavafall, Terraria.Main.lavafallSoundSlot, Terraria.Main.LocalPlayer, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.shimmerAlpha, Terraria.Audio.SoundEngine.TryGetActiveSound(), Terraria.ID.SoundID.Waterfall, and Terraria.Main.waterfallSoundSlot.
Referenced by Terraria.Main.DoUpdate().