TModLoader: Terraria.Main.LoadProjectile
LoadProjectile()
void Terraria.Main.LoadProjectile (int i) inline
    {
        if (TextureAssets.Projectile[i].State == AssetState.NotLoaded)
        {
            Assets.Request<Texture2D>(TextureAssets.Projectile[i].Name);
        }
    }
References Terraria.Main.Assets, and Terraria.GameContent.TextureAssets.Projectile.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup_2(), Terraria.Graphics.Renderers.GasParticle.Draw(), Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.DataStructures.PlayerDrawLayers.DrawMeowcartTrail(), Terraria.Main.DrawNPCDirect_Inner(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_12_SkinComposite_BackArmShirt(), Terraria.Main.DrawProj_DrawNormalProjs(), Terraria.Main.DrawProj_Inner(), Terraria.Main.DrawProj_LightsBane(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.ModLoader.Config.UI.ProjectileDefinitionOptionElement.DrawSelf(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.GameContent.VoidLensHelper.DrawToDrawData(), Terraria.Main.DrawWallOfBoulders(), Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseReqest(), Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_ZoologistAndPetsAnnoyGolfer(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningHit(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlackLightningSmall(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlameWaders(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WallOfFleshGoatMountFlames().