TModLoader: Terraria.Main.DrawInterface_14_EntityHealthBars
DrawInterface_14_EntityHealthBars()
void Terraria.Main.DrawInterface_14_EntityHealthBars () inline private
    {
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ccd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cda: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cdf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ce4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a66: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a70: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c18: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c76: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c8f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0caf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cbe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0acb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b99: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b02: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b07: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0300: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_047c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0486: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_048d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0497: Unknown result type (might be due to invalid IL or missing references)
        //IL_049c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0473: Unknown result type (might be due to invalid IL or missing references)
        //IL_0475: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_040c: Unknown result type (might be due to invalid IL or missing references)
        //IL_054e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0566: Unknown result type (might be due to invalid IL or missing references)
        //IL_042b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0430: Unknown result type (might be due to invalid IL or missing references)
        if (HealthBarDrawSettings == 0)
        {
            return;
        }
        int num = -1;
        if (PlayerInput.UsingGamepad)
        {
            Player localPlayer = LocalPlayer;
            for (int i = 0; i < 200; i++)
            {
                NPC nPC = npc[i];
                if ((nPC.life == nPC.lifeMax || nPC.dontTakeDamage) && !nPC.dontTakeDamage && nPC.nameOver > 0f && (num == -1 || nPC.Distance(localPlayer.Center) < npc[num].Distance(localPlayer.Center)))
                {
                    num = i;
                }
            }
        }
        bool flag = false;
        for (int num3 = 199; num3 >= 0; num3--)
        {
            if (!npc[num3].active || npc[num3].type <= 0 || npc[num3].shimmerTransparency != 0f)
            {
                continue;
            }
            NPC obj = npc[num3];
            obj.position += npc[num3].netOffset;
            if (npc[num3].life != npc[num3].lifeMax && !npc[num3].dontTakeDamage)
            {
                float scale = 1f;
                int type = npc[num3].type;
                if (type == 4)
                {
                    scale = 1.5f;
                }
                if (type == 35)
                {
                    scale = 1.5f;
                }
                if (type == 36)
                {
                    scale = 1.5f;
                }
                if (type == 50)
                {
                    scale = 1.5f;
                }
                if (type == 113)
                {
                    scale = 1.5f;
                }
                if (type == 114)
                {
                    scale = 1.5f;
                }
                if (type == 125)
                {
                    scale = 1.5f;
                }
                if (type == 126)
                {
                    scale = 1.5f;
                }
                if (type == 127)
                {
                    scale = 1.5f;
                }
                if (type == 128)
                {
                    scale = 1.5f;
                }
                if (type == 129)
                {
                    scale = 1.5f;
                }
                if (type == 130)
                {
                    scale = 1.5f;
                }
                if (type == 131)
                {
                    scale = 1.5f;
                }
                if (type == 222)
                {
                    scale = 1.5f;
                }
                if (type >= 245 && type <= 249)
                {
                    scale = 1.5f;
                }
                if (type == 262)
                {
                    scale = 1.5f;
                }
                if (type == 266)
                {
                    scale = 1.5f;
                }
                if (type == 564 || type == 565 || type == 551 || type == 576 || type == 577)
                {
                    scale = 1.5f;
                }
                if (type == 87)
                {
                    scale = 1.5f;
                }
                if (type == 510 || type == 454 || type == 621)
                {
                    scale = 1.5f;
                }
                if (type == 439 || type == 370)
                {
                    scale = 1.5f;
                }
                float num4 = 10f;
                if (HealthBarDrawSettings == 2)
                {
                    num4 -= 34f;
                }
                if (!NPCLoader.DrawHealthBar(npc[num3], ref scale))
                {
                    NPC obj2 = npc[num3];
                    obj2.position -= npc[num3].netOffset;
                    continue;
                }
                if ((!expertMode || type != 266) && ((type != 439 && type != 440) || npc[num3].ai[0] != 5f))
                {
                    if (type >= 134 && type <= 136)
                    {
                        scale = 1.5f;
                        if (!flag)
{
                            flag = true;
                            Vector2 vector = default(Vector2);
                            float num5 = 999999f;
                            for (int j = 0; j < 200; j++)
{
                                if (npc[j].active && npc[j].type >= 134 && npc[j].type <= 136)
{
                                    Vector2 vector2 = player[myPlayer].Center - npc[j].Center;
                                    if (((Vector2)(ref vector2)).Length() < num5 && Collision.CanHit(player[myPlayer].Center, 1, 1, npc[j].Center, 1, 1))
{
                                        num5 = ((Vector2)(ref vector2)).Length();
                                        vector = npc[j].position;
                                    }
                                }
                            }
                            if (num5 < (float)screenWidth)
{
                                if (destroyerHB.X < 100f && destroyerHB.Y < 100f)
{
                                    destroyerHB = vector;
                                }
                                else
{
                                    destroyerHB = (destroyerHB * 49f + vector) / 50f;
                                }
                                vector = destroyerHB;
                                int num6 = num3;
                                if (type != 134 && npc[num3].realLife != -1)
{
                                    num6 = npc[num3].realLife;
                                }
                                float num7 = Lighting.Brightness((int)((npc[num3].position.X + (float)(npc[num3].width / 2)) / 16f), (int)((npc[num3].position.Y + (float)(npc[num3].height / 2) + npc[num3].gfxOffY) / 16f));
                                num7 = (num7 + 1f) / 2f;
                                DrawHealthBar(vector.X + (float)(npc[num3].width / 2), vector.Y + (float)(npc[num3].height / 2), npc[num6].life, npc[num6].lifeMax, num7, scale);
                            }
                            else
{
                                destroyerHB = new Vector2(0f, 0f);
                            }
                        }
                    }
                    else
                    {
                        switch (type)
{
                        case 7:
                            DrawInterface_Healthbar_Worm(npc[num3], 9, scale);
                            break;
                        case 95:
                            DrawInterface_Healthbar_Worm(npc[num3], 97, scale);
                            break;
                        case 10:
                            DrawInterface_Healthbar_Worm(npc[num3], 12, scale);
                            break;
                        case 87:
                            DrawInterface_Healthbar_Worm(npc[num3], 92, scale);
                            break;
                        case 412:
                            DrawInterface_Healthbar_Worm(npc[num3], 414, scale);
                            break;
                        case 39:
                            DrawInterface_Healthbar_Worm(npc[num3], 41, scale);
                            break;
                        case 98:
                            DrawInterface_Healthbar_Worm(npc[num3], 100, scale);
                            break;
                        case 454:
                            DrawInterface_Healthbar_Worm(npc[num3], 459, scale);
                            break;
                        default:
                            switch (type)
{
                            case 510:
                                DrawInterface_Healthbar_Worm(npc[num3], 512, scale);
                                break;
                            case 621:
                                DrawInterface_Healthbar_Worm(npc[num3], 623, scale);
                                break;
                            case 513:
                                DrawInterface_Healthbar_Worm(npc[num3], 515, scale);
                                break;
                            case 117:
                                DrawInterface_Healthbar_Worm(npc[num3], 119, scale);
                                break;
                            default:
                                if (HealthBarDrawSettings == 1)
{
                                    num4 += NPCAddHeight(npc[num3]);
                                    DrawHealthBar(npc[num3].position.X + (float)(npc[num3].width / 2), npc[num3].position.Y + (float)npc[num3].height + num4 + npc[num3].gfxOffY, npc[num3].life, npc[num3].lifeMax, Lighting.Brightness((int)((npc[num3].position.X + (float)(npc[num3].width / 2)) / 16f), (int)((npc[num3].position.Y + (float)(npc[num3].height / 2) + npc[num3].gfxOffY) / 16f)), scale);
                                }
                                else if (HealthBarDrawSettings == 2)
{
                                    num4 -= NPCAddHeight(npc[num3]) / 2f;
                                    DrawHealthBar(npc[num3].position.X + (float)(npc[num3].width / 2), npc[num3].position.Y + num4 + npc[num3].gfxOffY, npc[num3].life, npc[num3].lifeMax, Lighting.Brightness((int)((npc[num3].position.X + (float)(npc[num3].width / 2)) / 16f), (int)((npc[num3].position.Y + (float)(npc[num3].height / 2) + npc[num3].gfxOffY) / 16f)), scale);
                                }
                                break;
                            case 118:
                            case 119:
                            case 511:
                            case 512:
                            case 514:
                            case 515:
                            case 622:
                            case 623:
                                break;
                            }
                            break;
                        case 8:
                        case 9:
                        case 11:
                        case 12:
                        case 40:
                        case 41:
                        case 88:
                        case 89:
                        case 90:
                        case 91:
                        case 92:
                        case 96:
                        case 97:
                        case 99:
                        case 100:
                        case 413:
                        case 414:
                        case 455:
                        case 456:
                        case 457:
                        case 458:
                        case 459:
                            break;
                        }
                    }
                }
            }
            else if (!npc[num3].dontTakeDamage && npc[num3].nameOver > 0f && PlayerInput.UsingGamepad && num3 == num)
            {
                Vector2 stringSize = ChatManager.GetStringSize(FontAssets.MouseText.Value, npc[num3].GivenOrTypeName, Vector2.One);
                Vector2 vector3 = npc[num3].Bottom - screenPosition + new Vector2(0f, 10f);
                if (NPC.GetNPCLocation(num3, seekHead: true, averageDirection: true, out var _, out var pos))
                {
                    vector3 = pos - screenPosition + new Vector2(0f, (float)(10 + npc[num3].height / 2));
                    if (player[myPlayer].gravDir == -1f)
                    {
                        vector3 = ReverseGravitySupport(vector3, (float)(-npc[num3].height - 20));
                    }
                    Vector2 origin = stringSize * new Vector2(0.5f, 0f);
                    ChatManager.DrawColorCodedStringShadow(spriteBatch, FontAssets.MouseText.Value, npc[num3].GivenOrTypeName, vector3, Color.Black * npc[num3].nameOver * 0.5f, 0f, origin, Vector2.One);
                    ChatManager.DrawColorCodedString(spriteBatch, FontAssets.MouseText.Value, npc[num3].GivenOrTypeName, vector3, Color.White * npc[num3].nameOver, 0f, origin, Vector2.One);
                }
            }
            if (npc[num3].type == 548 && !npc[num3].dontTakeDamageFromHostiles && DD2Event.TimeLeftBetweenWaves > 0 && !hideUI)
            {
                Vector2 position = npc[num3].Bottom - screenPosition + new Vector2(0f, -100f);
                int num8 = DD2Event.TimeLeftBetweenWaves / 60;
                string text = $"{num8}";
                DynamicSpriteFont value = FontAssets.MouseText.Value;
                float num9 = 1f;
                Vector2 origin2 = value.MeasureString(text) * num9 * new Vector2(0.5f, 0.5f);
                ChatManager.DrawColorCodedStringWithShadow(spriteBatch, value, text, position, Color.White, 0f, origin2, Vector2.One * num9);
            }
            NPC obj3 = npc[num3];
            obj3.position -= npc[num3].netOffset;
        }
        for (int k = 0; k < 255; k++)
        {
            if (k != myPlayer && player[k].active && !player[k].ghost && !player[k].dead && !player[k].invis && player[k].statLife != player[k].statLifeMax2)
            {
                if (HealthBarDrawSettings == 1)
                {
                    int num10 = 10;
                    DrawHealthBar(player[k].position.X + (float)(player[k].width / 2), player[k].position.Y + (float)player[k].height + (float)num10 + player[k].gfxOffY, player[k].statLife, player[k].statLifeMax2, player[k].stealth * Lighting.Brightness((int)((player[k].position.X + (float)(player[k].width / 2)) / 16f), (int)((player[k].position.Y + (float)(player[k].height / 2) + player[k].gfxOffY) / 16f)));
                }
                else if (HealthBarDrawSettings == 2)
                {
                    int num2 = -20;
                    DrawHealthBar(player[k].position.X + (float)(player[k].width / 2), player[k].position.Y + (float)num2 + player[k].gfxOffY, player[k].statLife, player[k].statLifeMax2, player[k].stealth * Lighting.Brightness((int)((player[k].position.X + (float)(player[k].width / 2)) / 16f), (int)((player[k].position.Y + (float)(player[k].height / 2) + player[k].gfxOffY) / 16f)));
                }
            }
        }
    }
References Terraria.Entity.Bottom, Terraria.Lighting.Brightness(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Graphics.Light.Color, Terraria.Main.destroyerHB, Terraria.Entity.Distance(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.DrawHealthBar(), Terraria.ModLoader.NPCLoader.DrawHealthBar(), Terraria.Main.DrawInterface_Healthbar_Worm(), Terraria.Main.expertMode, Terraria.NPC.GetNPCLocation(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.NPC.gfxOffY, Terraria.Player.gfxOffY, Terraria.NPC.GivenOrTypeName, Terraria.Main.HealthBarDrawSettings, Terraria.Entity.height, Terraria.Main.hideUI, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.LocalPlayer, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.myPlayer, Terraria.NPC.nameOver, Terraria.NPC.netOffset, Terraria.Main.npc, Terraria.Main.NPCAddHeight(), Terraria.Main.player, Terraria.Entity.position, Terraria.NPC.realLife, Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Player.stealth, Terraria.GameContent.Events.DD2Event.TimeLeftBetweenWaves, Terraria.NPC.type, Terraria.GameInput.PlayerInput.UsingGamepad, and Terraria.Entity.width.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().