TModLoader: Terraria.Main.DoDraw_Tiles_NonSolid
DoDraw_Tiles_NonSolid()
void Terraria.Main.DoDraw_Tiles_NonSolid () inline private
Definition at line 80393 of file Main.cs.
    {
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        TilesRenderer.PreDrawTiles(solidLayer: false, !drawToScreen, intoRenderTargets: false);
        if (drawToScreen)
        {
            DrawTiles(solidLayer: false, !drawToScreen, intoRenderTargets: false);
            TimeLogger.DetailedDrawReset();
        }
        else
        {
            spriteBatch.Draw((Texture2D)(object)tile2Target, sceneTile2Pos - screenPosition, Color.White);
            TimeLogger.DetailedDrawTime(15);
        }
        spriteBatch.End();
        try
        {
            DrawTileEntities(solidLayer: false, !drawToScreen, intoRenderTargets: false);
        }
        catch (Exception e)
        {
            TimeLogger.DrawException(e);
        }
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DefaultSamplerState, Terraria.TimeLogger.DetailedDrawReset(), Terraria.TimeLogger.DetailedDrawTime(), Terraria.TimeLogger.DrawException(), Terraria.Main.DrawTileEntities(), Terraria.Main.DrawTiles(), Terraria.Main.drawToScreen, Terraria.GameContent.Drawing.TileDrawing.PreDrawTiles(), Terraria.Main.Rasterizer, Terraria.Main.sceneTile2Pos, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, Terraria.Main.tile2Target, Terraria.Main.TilesRenderer, and Terraria.Main.Transform.
Referenced by Terraria.Main.DoDraw_WallsTilesNPCs().