TModLoader: Terraria.Main.DrawToMap
DrawToMap()
void Terraria.Main.DrawToMap () inline protected
Definition at line 70294 of file Main.cs.
    {
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04de: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0385: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        if (!mapEnabled)
        {
            return;
        }
        int num = maxTilesX / textureMaxWidth;
        int num12 = maxTilesY / textureMaxHeight;
        for (int i = 0; i <= num; i++)
        {
            for (int j = 0; j <= num12; j++)
            {
                if (!checkMap(i, j))
                {
                    return;
                }
            }
        }
        if (clearMap)
        {
            for (int k = 0; k <= num; k++)
            {
                for (int l = 0; l <= num12; l++)
                {
                    ((Game)this).GraphicsDevice.SetRenderTarget(mapTarget[k, l]);
                    ((Game)this).GraphicsDevice.Clear(Color.Transparent);
                    ((Game)this).GraphicsDevice.SetRenderTarget((RenderTarget2D)null);
                }
            }
            clearMap = false;
        }
        int num19 = -1;
        int num20 = -1;
        bool flag = false;
        int num21 = 0;
        int num22 = mapMinY;
        int num23 = mapMinY;
        int num24 = mapMaxY;
        int num25 = mapMaxY;
        int num2 = 1;
        if (mapMinY / textureMaxHeight != mapMaxY / textureMaxHeight)
        {
            num24 = textureMaxHeight;
            num23 = textureMaxHeight;
            num2 = 2;
        }
        for (int m = 0; m < num2; m++)
        {
            switch (m)
            {
            case 0:
                mapMinY = num22;
                mapMaxY = num24;
                break;
            case 1:
                mapMinY = num23;
                mapMaxY = num25;
                break;
            }
            if (mapMinX < 0)
            {
                mapMinX = 0;
            }
            if (mapMinX >= maxTilesX)
            {
                mapMinX = maxTilesX - 1;
            }
            if (mapMinY < 0)
            {
                mapMinY = 0;
            }
            if (mapMinY >= maxTilesY)
            {
                mapMinY = maxTilesY - 1;
            }
            for (int n = mapMinX; n < mapMaxX; n++)
            {
                for (int num3 = mapMinY; num3 < mapMaxY; num3++)
                {
                    MapTile mapTile = Map[n, num3];
                    if (!mapTile.IsChanged || mapTarget[n / textureMaxWidth, num3 / textureMaxHeight].IsContentLost)
                    {
                        continue;
                    }
                    num21++;
                    if (num21 >= maxMapUpdates)
                    {
                        continue;
                    }
                    if (loadMap)
                    {
                        loadMapLastX = n;
                    }
                    Map.ConsumeUpdate(n, num3);
                    int num4 = n / textureMaxWidth;
                    int num5 = num3 / textureMaxHeight;
                    if (num4 != num19 || num5 != num20)
                    {
                        num19 = num4;
                        num20 = num5;
                        if (flag)
{
                            spriteBatch.End();
                            ((Game)this).GraphicsDevice.SetRenderTarget((RenderTarget2D)null);
                        }
                        flag = true;
                        ((Game)this).GraphicsDevice.SetRenderTarget(mapTarget[num4, num5]);
                        spriteBatch.Begin();
                    }
                    int num6 = n - num4 * textureMaxWidth;
                    int num7 = num3 - num5 * textureMaxHeight;
                    Color mapTileXnaColor = MapHelper.GetMapTileXnaColor(ref mapTile);
                    int num8 = 1;
                    int num9 = 1;
                    int num10 = num3 + 1;
                    while (num10 < mapMaxY)
                    {
                        MapTile other2;
                        MapTile mapTile3 = (other2 = Map[n, num10]);
                        if (!mapTile3.IsChanged || !mapTile.Equals(ref other2) || num10 / textureMaxHeight != num5)
{
                            break;
                        }
                        Map.ConsumeUpdate(n, num10);
                        num8++;
                        num10++;
                        num3++;
                    }
                    if (num8 == 1)
                    {
                        for (num10 = n + 1; num10 < mapMaxX; num10++)
{
                            MapTile other;
                            MapTile mapTile2 = (other = Map[num10, num3]);
                            if (!mapTile2.IsChanged || !mapTile.Equals(ref other) || num10 / textureMaxWidth != num4)
{
                                break;
                            }
                            Map.ConsumeUpdate(num10, num3);
                            num9++;
                        }
                    }
                    spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Vector2((float)num6, (float)num7), (Rectangle?)new Rectangle(0, 0, num9, num8), mapTileXnaColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
                }
            }
        }
        for (int num11 = 0; num11 < MapHelper.numUpdateTile; num11++)
        {
            int num13 = MapHelper.updateTileX[num11];
            int num14 = MapHelper.updateTileY[num11];
            MapTile mapTile4 = Map[num13, num14];
            if (!mapTile4.IsChanged)
            {
                continue;
            }
            Map.ConsumeUpdate(num13, num14);
            int num15 = num13 / textureMaxWidth;
            int num16 = num14 / textureMaxHeight;
            if (num15 != num19 || num16 != num20)
            {
                num19 = num15;
                num20 = num16;
                if (flag)
                {
                    spriteBatch.End();
                    ((Game)this).GraphicsDevice.SetRenderTarget((RenderTarget2D)null);
                }
                flag = true;
                ((Game)this).GraphicsDevice.SetRenderTarget(mapTarget[num15, num16]);
                spriteBatch.Begin();
            }
            int num17 = num13 - num15 * textureMaxWidth;
            int num18 = num14 - num16 * textureMaxHeight;
            Color mapTileXnaColor2 = MapHelper.GetMapTileXnaColor(ref mapTile4);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Vector2((float)num17, (float)num18), (Rectangle?)new Rectangle(0, 0, 1, 1), mapTileXnaColor2, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        MapHelper.numUpdateTile = 0;
        if (flag)
        {
            spriteBatch.End();
            ((Game)this).GraphicsDevice.SetRenderTarget((RenderTarget2D)null);
        }
        mapReady = true;
        loadMapLastX = 0;
        loadMap = false;
        loadMapLock = false;
    }
References Terraria.Main.checkMap(), Terraria.Main.clearMap, Terraria.UI.Game, Terraria.Map.MapHelper.GetMapTileXnaColor(), Terraria.Main.loadMap, Terraria.Main.loadMapLastX, Terraria.Main.loadMapLock, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.mapEnabled, Terraria.Main.mapMaxX, Terraria.Main.mapMaxY, Terraria.Main.mapMinX, Terraria.Main.mapMinY, Terraria.Main.mapReady, Terraria.Main.mapTarget, Terraria.Main.maxMapUpdates, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Map.MapHelper.numUpdateTile, Terraria.Main.spriteBatch, Terraria.Main.textureMaxHeight, Terraria.Main.textureMaxWidth, Terraria.Map.MapHelper.updateTileX, and Terraria.Map.MapHelper.updateTileY.
Referenced by Terraria.Main.DoDraw().