TModLoader: Terraria.Main.DrawSunAndMoon
DrawSunAndMoon()
void Terraria.Main.DrawSunAndMoon (SceneArea sceneArea, Color moonColor, Color sunColor, float tempMushroomInfluence) inline private
Definition at line 79659 of file Main.cs.
    {
        //IL_0835: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0500: Unknown result type (might be due to invalid IL or missing references)
        //IL_0505: Unknown result type (might be due to invalid IL or missing references)
        //IL_0513: Unknown result type (might be due to invalid IL or missing references)
        //IL_0519: Unknown result type (might be due to invalid IL or missing references)
        //IL_051e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0523: Unknown result type (might be due to invalid IL or missing references)
        //IL_083a: Unknown result type (might be due to invalid IL or missing references)
        //IL_083f: Unknown result type (might be due to invalid IL or missing references)
        //IL_084b: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_055d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0586: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05da: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0601: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_062e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0655: Unknown result type (might be due to invalid IL or missing references)
        //IL_065f: Unknown result type (might be due to invalid IL or missing references)
        //IL_067c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_045b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0460: Unknown result type (might be due to invalid IL or missing references)
        //IL_046e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0474: Unknown result type (might be due to invalid IL or missing references)
        //IL_0479: Unknown result type (might be due to invalid IL or missing references)
        //IL_047e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0486: Unknown result type (might be due to invalid IL or missing references)
        //IL_0492: Unknown result type (might be due to invalid IL or missing references)
        //IL_0496: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ea: Unknown result type (might be due to invalid IL or missing references)
        Texture2D value = TextureAssets.Sun.Value;
        int num = moonType;
        if (!TextureAssets.Moon.IndexInRange(num))
        {
            num = Utils.Clamp(num, 0, 8);
        }
        Texture2D value2 = TextureAssets.Moon[num].Value;
        int num6 = sceneArea.bgTopY;
        int num7 = (int)(time / 54000.0 * (double)(sceneArea.totalWidth + (float)(value.Width * 2))) - value.Width;
        int num8 = 0;
        float num9 = 1f;
        float rotation = (float)(time / 54000.0) * 2f - 7.3f;
        int num10 = (int)(time / 32400.0 * (double)(sceneArea.totalWidth + (float)(value2.Width * 2))) - value2.Width;
        int num11 = 0;
        float num12 = 1f;
        float num13 = (float)(time / 32400.0) * 2f - 7.3f;
        if (dayTime)
        {
            double num2;
            if (time < 27000.0)
            {
                num2 = Math.Pow(1.0 - time / 54000.0 * 2.0, 2.0);
                num8 = (int)((double)num6 + num2 * 250.0 + 180.0);
            }
            else
            {
                num2 = Math.Pow((time / 54000.0 - 0.5) * 2.0, 2.0);
                num8 = (int)((double)num6 + num2 * 250.0 + 180.0);
            }
            num9 = (float)(1.2 - num2 * 0.4);
        }
        else
        {
            double num3;
            if (time < 16200.0)
            {
                num3 = Math.Pow(1.0 - time / 32400.0 * 2.0, 2.0);
                num11 = (int)((double)num6 + num3 * 250.0 + 180.0);
            }
            else
            {
                num3 = Math.Pow((time / 32400.0 - 0.5) * 2.0, 2.0);
                num11 = (int)((double)num6 + num3 * 250.0 + 180.0);
            }
            num12 = (float)(1.2 - num3 * 0.4);
        }
        num9 *= ForcedMinimumZoom;
        num12 *= ForcedMinimumZoom;
        if (starGame)
        {
            if (WorldGen.generatingWorld)
            {
                alreadyGrabbingSunOrMoon = true;
                if (rand.Next(60) == 0)
                {
                    for (int i = 0; i < numStars; i++)
                    {
                        if (star[i].hidden)
{
                            Star.SpawnStars(i);
                        }
                    }
                }
                if (dayTime)
                {
                    dayTime = false;
                    time = 0.0;
                }
            }
            else
            {
                starGame = false;
            }
        }
        else
        {
            starsHit = 0;
        }
        if (dayTime)
        {
            if ((remixWorld && !gameMenu) || WorldGen.remixWorldGen)
            {
                return;
            }
            num9 *= 1.1f;
            float num4 = 1f - tempMushroomInfluence;
            num4 -= cloudAlpha * 1.5f * atmo;
            if (num4 < 0f)
            {
                num4 = 0f;
            }
            Color color = default(Color);
            ((Color)(ref color))._002Ector((int)(byte)(255f * num4), (int)(byte)((float)(int)((Color)(ref sunColor)).G * num4), (int)(byte)((float)(int)((Color)(ref sunColor)).B * num4), (int)(byte)(255f * num4));
            Color color2 = default(Color);
            ((Color)(ref color2))._002Ector((int)(byte)((float)(int)((Color)(ref sunColor)).R * num4), (int)(byte)((float)(int)((Color)(ref sunColor)).G * num4), (int)(byte)((float)(int)((Color)(ref sunColor)).B * num4), (int)(byte)((float)(int)((Color)(ref sunColor)).B * num4));
            bool flag = false;
            if (eclipse)
            {
                value = TextureAssets.Sun3.Value;
                flag = true;
            }
            else if (!gameMenu && player[myPlayer].head == 12)
            {
                value = TextureAssets.Sun2.Value;
                flag = true;
            }
            if (flag)
            {
                ((Color)(ref color2))._002Ector((int)(byte)((float)(int)((Color)(ref sunColor)).R * num4), (int)(byte)((float)(int)((Color)(ref sunColor)).G * num4), (int)(byte)((float)(int)((Color)(ref sunColor)).B * num4), (int)(byte)((float)(((Color)(ref sunColor)).B - 60) * num4));
            }
            Vector2 origin = value.Size() / 2f;
            Vector2 position = new Vector2((float)num7, (float)(num8 + sunModY)) + sceneArea.SceneLocalScreenPositionOffset;
            spriteBatch.Draw(value, position, (Rectangle?)null, color, rotation, origin, num9, (SpriteEffects)0, 0f);
            spriteBatch.Draw(value, position, (Rectangle?)null, color2, rotation, origin, num9, (SpriteEffects)0, 0f);
        }
        if (!dayTime)
        {
            float num5 = 1f - cloudAlpha * 1.5f * atmo;
            if (num5 < 0f)
            {
                num5 = 0f;
            }
            moonColor *= num5;
            Vector2 position2 = new Vector2((float)num10, (float)(num11 + moonModY)) + sceneArea.SceneLocalScreenPositionOffset;
            if (WorldGen.drunkWorldGen)
            {
                spriteBatch.Draw(TextureAssets.SmileyMoon.Value, position2, (Rectangle?)new Rectangle(0, 0, TextureAssets.SmileyMoon.Width(), TextureAssets.SmileyMoon.Height()), moonColor, num13 / 2f + (float)Math.PI, new Vector2((float)(TextureAssets.SmileyMoon.Width() / 2), (float)(TextureAssets.SmileyMoon.Width() / 2)), num12, (SpriteEffects)0, 0f);
            }
            else if (pumpkinMoon)
            {
                spriteBatch.Draw(TextureAssets.PumpkinMoon.Value, position2, (Rectangle?)new Rectangle(0, TextureAssets.PumpkinMoon.Width() * moonPhase, TextureAssets.PumpkinMoon.Width(), TextureAssets.PumpkinMoon.Width()), moonColor, num13, new Vector2((float)(TextureAssets.PumpkinMoon.Width() / 2), (float)(TextureAssets.PumpkinMoon.Width() / 2)), num12, (SpriteEffects)0, 0f);
            }
            else if (snowMoon)
            {
                spriteBatch.Draw(TextureAssets.SnowMoon.Value, position2, (Rectangle?)new Rectangle(0, TextureAssets.SnowMoon.Width() * moonPhase, TextureAssets.SnowMoon.Width(), TextureAssets.SnowMoon.Width()), moonColor, num13, new Vector2((float)(TextureAssets.SnowMoon.Width() / 2), (float)(TextureAssets.SnowMoon.Width() / 2)), num12, (SpriteEffects)0, 0f);
            }
            else if (value2 != TextureAssets.Moon[num].Value)
            {
                spriteBatch.Draw(value2, position2, (Rectangle?)new Rectangle(0, 0, value2.Width, value2.Width), moonColor, num13, new Vector2((float)(value2.Width / 2)), num12, (SpriteEffects)0, 0f);
            }
            else
            {
                spriteBatch.Draw(TextureAssets.Moon[num].Value, position2, (Rectangle?)new Rectangle(0, TextureAssets.Moon[num].Width() * moonPhase, TextureAssets.Moon[num].Width(), TextureAssets.Moon[num].Width()), moonColor, num13, new Vector2((float)(TextureAssets.Moon[num].Width() / 2), (float)(TextureAssets.Moon[num].Width() / 2)), num12, (SpriteEffects)0, 0f);
            }
        }
        Rectangle value3 = ((!dayTime) ? new Rectangle((int)((double)num10 - (double)TextureAssets.Moon[num].Width() * 0.5 * (double)num12), (int)((double)num11 - (double)TextureAssets.Moon[num].Width() * 0.5 * (double)num12 + (double)moonModY), (int)((float)TextureAssets.Moon[num].Width() * num12), (int)((float)TextureAssets.Moon[num].Width() * num12)) : new Rectangle((int)((double)num7 - (double)TextureAssets.Sun.Width() * 0.5 * (double)num9), (int)((double)num8 - (double)TextureAssets.Sun.Height() * 0.5 * (double)num9 + (double)sunModY), (int)((float)TextureAssets.Sun.Width() * num9), (int)((float)TextureAssets.Sun.Width() * num9)));
        ((Rectangle)(ref value3)).Offset((int)sceneArea.SceneLocalScreenPositionOffset.X, (int)sceneArea.SceneLocalScreenPositionOffset.Y);
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(mouseX, mouseY, 1, 1);
        sunModY = (short)((double)sunModY * 0.999);
        moonModY = (short)((double)moonModY * 0.999);
        if (!gameMenu || netMode == 1)
        {
            return;
        }
        if (((Rectangle)(ref rectangle)).Intersects(value3) || alreadyGrabbingSunOrMoon)
        {
            player[myPlayer].mouseInterface = true;
        }
        if ((mouseLeft || starGame) && hasFocus)
        {
            if (!((Rectangle)(ref rectangle)).Intersects(value3) && !alreadyGrabbingSunOrMoon)
            {
                return;
            }
            if (dayTime)
            {
                time = 54000.0 * (double)((float)(mouseX + TextureAssets.Sun.Width()) / ((float)screenWidth + (float)(TextureAssets.Sun.Width() * 2)));
                sunModY = (short)(mouseY - num8);
                if (time > 53990.0)
                {
                    time = 53990.0;
                }
            }
            else
            {
                time = 32400.0 * (double)((float)(mouseX + TextureAssets.Moon[num].Width()) / ((float)screenWidth + (float)(TextureAssets.Moon[num].Width() * 2)));
                moonModY = (short)(mouseY - num11);
                if (time > 32390.0)
                {
                    time = 32390.0;
                }
            }
            if (time < 10.0)
            {
                time = 10.0;
            }
            alreadyGrabbingSunOrMoon = true;
        }
        else
        {
            alreadyGrabbingSunOrMoon = false;
        }
    }
References Terraria.Main.alreadyGrabbingSunOrMoon, Terraria.Main.atmo, Terraria.Main.cloudAlpha, Terraria.Graphics.Light.Color, Terraria.Main.dayTime, Terraria.WorldGen.drunkWorldGen, Terraria.Main.eclipse, Terraria.Main.ForcedMinimumZoom, Terraria.Main.gameMenu, Terraria.WorldGen.generatingWorld, Terraria.Main.hasFocus, Terraria.GameContent.TextureAssets.Moon, Terraria.Main.moonModY, Terraria.Main.moonPhase, Terraria.Main.moonType, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.numStars, Terraria.Main.player, Terraria.GameContent.TextureAssets.PumpkinMoon, Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.Main.screenWidth, Terraria.GameContent.TextureAssets.SmileyMoon, Terraria.GameContent.TextureAssets.SnowMoon, Terraria.Main.snowMoon, Terraria.Star.SpawnStars(), Terraria.Main.spriteBatch, Terraria.Main.star, Terraria.Main.starGame, Terraria.Main.starsHit, Terraria.GameContent.TextureAssets.Sun, Terraria.GameContent.TextureAssets.Sun2, Terraria.GameContent.TextureAssets.Sun3, Terraria.Main.sunModY, and Terraria.Main.time.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().