TModLoader: Terraria.Main.DrawVersionNumber
DrawVersionNumber()
static void Terraria.Main.DrawVersionNumber (Color menuColor, float upBump) inline static private
Definition at line 66409 of file Main.cs.
    {
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_0336: Unknown result type (might be due to invalid IL or missing references)
        //IL_033b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_0421: Unknown result type (might be due to invalid IL or missing references)
        //IL_0438: Unknown result type (might be due to invalid IL or missing references)
        //IL_044e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_045a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_027d: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_037d: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        //IL_039b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ae: Unknown result type (might be due to invalid IL or missing references)
        string supportMessage = Language.GetTextValue("tModLoader.PatreonSupport");
        string patreonShortURL = "patreon.com/tModLoader";
        bool showPatreon = SocialAPI.Mode != SocialMode.Steam;
        Language.GetTextValue("tModLoader.MenuModsEnabled", Math.Max(0, Terraria.ModLoader.ModLoader.Mods.Length - 1));
        string text = Terraria.ModLoader.ModLoader.versionedName + (showPatreon ? (Environment.NewLine + supportMessage) : "") + ((menuMode == 0) ? Environment.NewLine : "") + Environment.NewLine + "Terraria " + versionNumber;
        Vector2 origin = FontAssets.MouseText.Value.MeasureString(text);
        origin.X *= 0.5f;
        origin.Y *= 0.5f;
        Vector2 pos = default(Vector2);
        Rectangle rect = default(Rectangle);
        for (int i = 0; i < 5; i++)
        {
            Color color = Color.Black;
            if (i == 4)
            {
                color = menuColor;
                ((Color)(ref color)).R = (byte)((255 + ((Color)(ref color)).R) / 2);
                ((Color)(ref color)).G = (byte)((255 + ((Color)(ref color)).R) / 2);
                ((Color)(ref color)).B = (byte)((255 + ((Color)(ref color)).R) / 2);
            }
            ((Color)(ref color)).A = (byte)((float)(int)((Color)(ref color)).A * 0.3f);
            int num = 0;
            int num2 = 0;
            if (i == 0)
            {
                num = -2;
            }
            if (i == 1)
            {
                num = 2;
            }
            if (i == 2)
            {
                num2 = -2;
            }
            if (i == 3)
            {
                num2 = 2;
            }
            spriteBatch.DrawString(FontAssets.MouseText.Value, text, new Vector2(origin.X + (float)num + 10f, (float)screenHeight - origin.Y + (float)num2 - 2f - upBump), color, 0f, origin, 1f, (SpriteEffects)0, 0f);
            if (menuMode == 0)
            {
                string developerModeText = Language.GetTextValue("tModLoader.SwitchVersionInfoButton");
                Vector2 textSize = FontAssets.MouseText.Value.MeasureString(developerModeText);
                ((Vector2)(ref pos))._002Ector((float)screenWidth - 10f + (float)num, (float)screenHeight - 2f + (float)num2);
                Color d_color = color;
                float scale = 1.2f;
                if (i == 4)
                {
                    ((Rectangle)(ref rect))._002Ector((int)(pos.X - textSize.X * scale), (int)(pos.Y - textSize.Y * scale), (int)(textSize.X * scale), (int)(textSize.Y * scale));
                    bool num3 = ((Rectangle)(ref rect)).Contains(mouseX, mouseY);
                    d_color = (num3 ? highVersionColor : d_color);
                    if (num3 && mouseLeftRelease && mouseLeft)
                    {
                        SoundEngine.PlaySound(in SoundID.MenuOpen);
                        Utils.OpenToURL("https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#beta-branches");
                    }
                }
                spriteBatch.DrawString(FontAssets.MouseText.Value, developerModeText, pos, d_color, 0f, textSize, 1.2f, (SpriteEffects)0, 0f);
            }
            if (showPatreon)
            {
                DynamicSpriteFont font2 = FontAssets.MouseText.Value;
                Vector2 patreonOrigin = font2.MeasureString(supportMessage);
                Vector2 urlSize = font2.MeasureString(patreonShortURL);
                spriteBatch.DrawString(font2, patreonShortURL, new Vector2(patreonOrigin.X + (float)num + 10f, (float)screenHeight - patreonOrigin.Y + (float)num2 - 2f - (float)(int)upBump), color, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
                if (i == 4 && mouseLeftRelease && mouseLeft)
                {
                    Rectangle val = new Rectangle((int)patreonOrigin.X + 10, screenHeight - (int)urlSize.Y - 2 - (int)upBump, (int)urlSize.X, (int)patreonOrigin.Y);
                    if (((Rectangle)(ref val)).Contains(new Point(mouseX, mouseY)) && hasFocus)
                    {
                        SoundEngine.PlaySound(in SoundID.MenuOpen);
                        Utils.OpenToURL("https://www.patreon.com/tModLoader");
                    }
                }
            }
            if (ModOrganizer.ModPackActive != null)
            {
                DynamicSpriteFont font = FontAssets.MouseText.Value;
                string modpackText = Language.GetTextValue("tModLoader.CurrentModPack", Path.GetFileNameWithoutExtension(ModOrganizer.ModPackActive));
                Vector2 packOrigin = font.MeasureString(modpackText);
                spriteBatch.DrawString(font, modpackText, new Vector2(packOrigin.X + (float)num + 10f, (float)screenHeight - packOrigin.Y + (float)num2 - 2f - (float)(int)upBump), color, 0f, Vector2.Zero, 1f, (SpriteEffects)0, 0f);
            }
        }
    }
References Terraria.Graphics.Light.Color, Terraria.ModLoader.Environment, Terraria.Localization.Language.GetTextValue(), Terraria.Main.hasFocus, Terraria.Main.highVersionColor, Terraria.Main.menuMode, Terraria.ID.SoundID.MenuOpen, Terraria.ModLoader.Core.ModOrganizer.ModPackActive, Terraria.ModLoader.ModLoader.Mods, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Utils.OpenToURL(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, and Terraria.Main.versionNumber.
Referenced by Terraria.Main.DrawMenu().