TModLoader: Terraria.Main.DrawProj_TrueExcalibur
DrawProj_TrueExcalibur()
void Terraria.Main.DrawProj_TrueExcalibur (Projectile proj) inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0212: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0261: Unknown result type (might be due to invalid IL or missing references)
        //IL_0267: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_030a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0310: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_034a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0364: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0386: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0418: Unknown result type (might be due to invalid IL or missing references)
        //IL_0421: Unknown result type (might be due to invalid IL or missing references)
        //IL_0489: Unknown result type (might be due to invalid IL or missing references)
        //IL_048c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0528: Unknown result type (might be due to invalid IL or missing references)
        //IL_052f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_053b: Unknown result type (might be due to invalid IL or missing references)
        //IL_055b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0588: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0620: Unknown result type (might be due to invalid IL or missing references)
        //IL_0627: Unknown result type (might be due to invalid IL or missing references)
        //IL_062c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0633: Unknown result type (might be due to invalid IL or missing references)
        Vector2 vector = proj.Center - screenPosition;
        Asset<Texture2D> asset = TextureAssets.Projectile[proj.type];
        Rectangle rectangle = asset.Frame(1, 4);
        Vector2 origin = rectangle.Size() / 2f;
        float num = proj.scale * 1.1f;
        SpriteEffects effects = (SpriteEffects)((!(proj.ai[0] >= 0f)) ? 2 : 0);
        float num2 = proj.localAI[0] / proj.ai[1];
        float num3 = Utils.Remap(num2, 0f, 0.6f, 0f, 1f) * Utils.Remap(num2, 0.6f, 1f, 1f, 0f);
        float num4 = 0.975f;
        float amount = num3;
        Color color6 = Lighting.GetColor(proj.Center.ToTileCoordinates());
        Vector3 val = ((Color)(ref color6)).ToVector3();
        float fromValue = ((Vector3)(ref val)).Length() / (float)Math.Sqrt(3.0);
        fromValue = Utils.Remap(fromValue, 0.2f, 1f, 0f, 1f);
        Color color = Color.Lerp(new Color(180, 50, 90), new Color(180, 30, 60), amount);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color * fromValue * num3, proj.rotation + proj.ai[0] * ((float)Math.PI / 4f) * -1f * (1f - num2), origin, num, effects, 0f);
        Color color2 = Color.Lerp(new Color(255, 240, 150), new Color(255, 60, 170), amount);
        Color color3 = Color.Lerp(new Color(255, 255, 80), new Color(255, 60, 190), amount);
        Color color4 = Color.White * num3 * 0.5f;
        ((Color)(ref color4)).A = (byte)((float)(int)((Color)(ref color4)).A * (1f - fromValue));
        Color color5 = color4 * fromValue * 0.5f;
        ((Color)(ref color5)).G = (byte)((float)(int)((Color)(ref color5)).G * fromValue);
        ((Color)(ref color5)).B = (byte)((float)(int)((Color)(ref color5)).R * (0.25f + fromValue * 0.75f));
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color5 * 0.15f, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color3 * fromValue * num3 * 0.3f, proj.rotation, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)rectangle, color2 * fromValue * num3 * 0.5f, proj.rotation, origin, num * num4, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.6f * num3, proj.rotation + proj.ai[0] * 0.01f, origin, num, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.5f * num3, proj.rotation + proj.ai[0] * -0.05f, origin, num * 0.8f, effects, 0f);
        spriteBatch.Draw(asset.Value, vector, (Rectangle?)asset.Frame(1, 4, 0, 3), Color.White * 0.4f * num3, proj.rotation + proj.ai[0] * -0.1f, origin, num * 0.6f, effects, 0f);
        float num5 = num * 0.75f;
        for (float num6 = 0f; num6 < 12f; num6 += 1f)
        {
            float num7 = proj.rotation + proj.ai[0] * num6 * ((float)Math.PI * -2f) * 0.025f + Utils.Remap(num2, 0f, 0.6f, 0f, 0.95504415f) * proj.ai[0];
            Vector2 drawpos = vector + num7.ToRotationVector2() * ((float)asset.Width() * 0.5f - 6f) * num;
            float num8 = num6 / 12f;
            DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos, new Color(255, 255, 255, 0) * num3 * num8, color3, num2, 0f, 0.5f, 0.5f, 1f, num7, new Vector2(0f, Utils.Remap(num2, 0f, 1f, 3f, 0f)) * num5, Vector2.One * num5);
        }
        Vector2 drawpos2 = vector + (proj.rotation + Utils.Remap(num2, 0f, 0.6f, 0f, 0.95504415f) * proj.ai[0]).ToRotationVector2() * ((float)asset.Width() * 0.5f - 4f) * num;
        DrawPrettyStarSparkle(proj.Opacity, (SpriteEffects)0, drawpos2, new Color(255, 255, 255, 0) * num3 * 0.5f, color3, num2, 0f, 0.5f, 0.5f, 1f, 0f, new Vector2(2f, Utils.Remap(num2, 0f, 1f, 4f, 1f)) * num5, Vector2.One * num5);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.DrawPrettyStarSparkle(), Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Utils.Remap(), Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawProj_DrawSpecialProjs().