TModLoader: Terraria.Main.DrawWhip_WhipBland
DrawWhip_WhipBland()
static Vector2 Terraria.Main.DrawWhip_WhipBland (Projectile proj, List< Vector2 > controlPoints) inline static
Definition at line 47376 of file Main.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0067: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_0137: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018c: Unknown result type (might be due to invalid IL or missing references)
        //IL_018e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        SpriteEffects spriteEffects = (SpriteEffects)0;
        if (proj.spriteDirection == 1)
        {
            spriteEffects = (SpriteEffects)(spriteEffects ^ 1);
        }
        Texture2D value = TextureAssets.Projectile[proj.type].Value;
        Rectangle rectangle = value.Frame(1, 5);
        int height = rectangle.Height;
        rectangle.Height -= 2;
        Vector2 vector = rectangle.Size() / 2f;
        Vector2 vector2 = controlPoints[0];
        for (int i = 0; i < controlPoints.Count - 1; i++)
        {
            bool flag = false;
            Vector2 origin = vector;
            float scale = 1f;
            if (i == 0)
            {
                origin.Y -= 4f;
                flag = true;
            }
            else
            {
                flag = true;
                int num = 1;
                if (i > 10)
                {
                    num = 2;
                }
                if (i > 20)
                {
                    num = 3;
                }
                rectangle.Y = height * num;
            }
            if (i == controlPoints.Count - 2)
            {
                flag = true;
                rectangle.Y = height * 4;
                scale = 1.3f;
                Projectile.GetWhipSettings(proj, out var timeToFlyOut, out var _, out var _);
                float t = proj.ai[0] / timeToFlyOut;
                float amount = Utils.GetLerpValue(0.1f, 0.7f, t, clamped: true) * Utils.GetLerpValue(0.9f, 0.7f, t, clamped: true);
                scale = MathHelper.Lerp(0.5f, 1.5f, amount);
            }
            Vector2 vector3 = controlPoints[i];
            Vector2 vector4 = controlPoints[i + 1] - vector3;
            if (flag)
            {
                float rotation = vector4.ToRotation() - (float)Math.PI / 2f;
                Color color = Lighting.GetColor(vector3.ToTileCoordinates());
                spriteBatch.Draw(value, vector2 - screenPosition, (Rectangle?)rectangle, color, rotation, origin, scale, spriteEffects, 0f);
            }
            vector2 += vector4;
        }
        return vector2;
    }
References Terraria.Graphics.Light.Color, Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Terraria.Projectile.GetWhipSettings(), Terraria.GameContent.TextureAssets.Projectile, Terraria.Main.screenPosition, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawWhip().