TModLoader: Terraria.Main.BuilderTogglePageHandler
BuilderTogglePageHandler()
static void Terraria.Main.BuilderTogglePageHandler (int startY, int activeToggles, out bool moveDownForButton, out int startIndex, out int endIndex) inline static
    {
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_023e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0243: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0403: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_040f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0414: Unknown result type (might be due to invalid IL or missing references)
        //IL_0423: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_037c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0381: Unknown result type (might be due to invalid IL or missing references)
        //IL_0390: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a8: Unknown result type (might be due to invalid IL or missing references)
        startIndex = 0;
        endIndex = activeToggles;
        moveDownForButton = false;
        string text = "";
        if (activeToggles <= 12)
        {
            return;
        }
        startIndex = 12 * BuilderToggleLoader.BuilderTogglePage;
        if (activeToggles - startIndex < 12)
        {
            endIndex = activeToggles;
        }
        else if (startIndex == 0)
        {
            endIndex = startIndex + 12;
        }
        else
        {
            endIndex = startIndex + 11;
        }
        Texture2D buttonTexture = UICommon.InfoDisplayPageArrowTexture.Value;
        bool hover = false;
        Vector2 buttonPosition = default(Vector2);
        ((Vector2)(ref buttonPosition))._002Ector(3f, (float)startY - 6f);
        if (BuilderToggleLoader.BuilderTogglePage != 0)
        {
            moveDownForButton = true;
            spriteBatch.Draw(buttonTexture, buttonPosition + new Vector2(0f, 13f), (Rectangle?)new Rectangle(0, 0, buttonTexture.Width, buttonTexture.Height), Color.White, -(float)Math.PI / 2f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            if ((float)mouseX >= buttonPosition.X && (float)mouseY >= buttonPosition.Y && (float)mouseX <= buttonPosition.X + (float)buttonTexture.Width && (float)mouseY <= buttonPosition.Y + (float)buttonTexture.Height && !PlayerInput.IgnoreMouseInterface)
            {
                hover = true;
                player[myPlayer].mouseInterface = true;
                text = "Previous Page";
                mouseText = true;
                if (mouseLeft && mouseLeftRelease)
                {
                    SoundEngine.PlaySound(in SoundID.MenuTick);
                    mouseLeftRelease = false;
                    if (BuilderToggleLoader.BuilderTogglePage > 0)
                    {
                        BuilderToggleLoader.BuilderTogglePage--;
                    }
                }
                spriteBatch.Draw(TextureAssets.InfoIcon[13].Value, buttonPosition + new Vector2(0f, 17f) - Vector2.One * 2f, (Rectangle?)null, OurFavoriteColor, -(float)Math.PI / 2f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
        }
        ((Vector2)(ref buttonPosition))._002Ector(3f, (float)startY + (float)(endIndex - startIndex + (BuilderToggleLoader.BuilderTogglePage != 0).ToInt()) * 24f - 6f);
        if (BuilderToggleLoader.BuilderTogglePage != activeToggles / 12)
        {
            spriteBatch.Draw(buttonTexture, buttonPosition + new Vector2(0f, 12f), (Rectangle?)new Rectangle(0, 0, buttonTexture.Width, buttonTexture.Height), Color.White, (float)Math.PI / 2f, new Vector2((float)buttonTexture.Width, (float)buttonTexture.Height), 1f, (SpriteEffects)0, 0f);
            if ((float)mouseX >= buttonPosition.X && (float)mouseY >= buttonPosition.Y && (float)mouseX <= buttonPosition.X + (float)buttonTexture.Width && (float)mouseY <= buttonPosition.Y + (float)buttonTexture.Height && !PlayerInput.IgnoreMouseInterface)
            {
                hover = true;
                player[myPlayer].mouseInterface = true;
                text = "Next Page";
                mouseText = true;
                if (mouseLeft && mouseLeftRelease)
                {
                    SoundEngine.PlaySound(in SoundID.MenuTick);
                    mouseLeftRelease = false;
                    if (BuilderToggleLoader.BuilderTogglePage < activeToggles / 12)
                    {
                        BuilderToggleLoader.BuilderTogglePage++;
                    }
                }
                spriteBatch.Draw(TextureAssets.InfoIcon[13].Value, buttonPosition + new Vector2(4f, 12f) - Vector2.One * 2f, (Rectangle?)null, OurFavoriteColor, (float)Math.PI / 2f, new Vector2((float)buttonTexture.Width, (float)buttonTexture.Height), 1f, (SpriteEffects)0, 0f);
            }
        }
        if (mouseText && hover)
        {
            float colorByte = (float)(int)mouseTextColor / 255f;
            Color textColor = default(Color);
            ((Color)(ref textColor))._002Ector(colorByte, colorByte, colorByte);
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, new Vector2((float)(mouseX + 14), (float)(mouseY + 14)), textColor, 0f, Vector2.Zero, Vector2.One);
            mouseText = false;
        }
    }
References Terraria.ModLoader.BuilderToggleLoader.BuilderTogglePage, Terraria.Graphics.Light.Color, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.ModLoader.UI.UICommon.InfoDisplayPageArrowTexture, Terraria.GameContent.TextureAssets.InfoIcon, Terraria.ID.SoundID.MenuTick, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawBuilderAccToggles_Inner().