TModLoader: Terraria.Main.DrawSurfaceBG_BackMountainsStep2
DrawSurfaceBG_BackMountainsStep2()
void Terraria.Main.DrawSurfaceBG_BackMountainsStep2 (int pushBGTopHack) inline private
Definition at line 76279 of file Main.cs.
    {
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_013d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_014a: Unknown result type (might be due to invalid IL or missing references)
        //IL_016a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0240: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024e: Unknown result type (might be due to invalid IL or missing references)
        if (gameMenu)
        {
            bgTopY = 230 + pushBGTopHack;
            bgStartX -= 500;
        }
        Color colorOfSurfaceBackgroundsBase = ColorOfSurfaceBackgroundsBase;
        UpdateOceanWaterLineForAmbience();
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        if (!((double)screenPosition.Y < worldSurface * 16.0 + 16.0))
        {
            return;
        }
        if (bgAlphaFarBackLayer[0] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[0];
            if (treeMntBGSet1[1] > -1)
            {
                DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet1[1]);
            }
        }
        if (bgAlphaFarBackLayer[1] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[1];
            if (WorldGen.desertBG != 4)
            {
                DrawSurfaceBG_DrawBackMountainsLayer(22);
            }
        }
        if (bgAlphaFarBackLayer[2] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[2];
            DrawSurfaceBG_DrawBackMountainsLayer(25);
        }
        if (bgAlphaFarBackLayer[3] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[3];
            DrawSurfaceBG_DrawBackMountainsLayer(oceanBG);
        }
        if (bgAlphaFarBackLayer[4] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[4];
            DrawSurfaceBG_DrawBackMountainsLayer(snowMntBG[1]);
        }
        if (bgAlphaFarBackLayer[5] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[5];
            if (WorldGen.crimsonBG != 5)
            {
                DrawSurfaceBG_DrawBackMountainsLayer(42);
            }
        }
        if (bgAlphaFarBackLayer[6] > 0f && WorldGen.hallowBG == 3)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[6];
            DrawSurfaceBG_DrawBackMountainsLayer(247);
        }
        if (bgAlphaFarBackLayer[10] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[10];
            if (treeMntBGSet2[1] > -1)
            {
                DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet2[1]);
            }
        }
        if (bgAlphaFarBackLayer[11] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[11];
            if (treeMntBGSet3[1] > -1)
            {
                DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet3[1]);
            }
        }
        if (bgAlphaFarBackLayer[12] > 0f)
        {
            ColorOfSurfaceBackgroundsModified = colorOfSurfaceBackgroundsBase * bgAlphaFarBackLayer[12];
            if (treeMntBGSet4[1] > -1)
            {
                DrawSurfaceBG_DrawBackMountainsLayer(treeMntBGSet4[1]);
            }
        }
        LoaderManager.Get<SurfaceBackgroundStylesLoader>().DrawMiddleTexture();
    }
References Terraria.Main.bgAlphaFarBackLayer, Terraria.Main.bgParallax, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.ColorOfSurfaceBackgroundsBase, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.WorldGen.crimsonBG, Terraria.WorldGen.desertBG, Terraria.Main.DrawSurfaceBG_DrawBackMountainsLayer(), Terraria.Main.gameMenu, Terraria.WorldGen.hallowBG, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.oceanBG, Terraria.Main.screenPosition, Terraria.Main.snowMntBG, Terraria.Main.spriteBatch, Terraria.Main.treeMntBGSet1, Terraria.Main.treeMntBGSet2, Terraria.Main.treeMntBGSet3, Terraria.Main.treeMntBGSet4, Terraria.Main.UpdateOceanWaterLineForAmbience(), and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawSurfaceBG().