TModLoader: Terraria.Main.DoUpdate_WhilePaused
DoUpdate_WhilePaused()
static void Terraria.Main.DoUpdate_WhilePaused () inline static private
Definition at line 16865 of file Main.cs.
    {
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        if (!drawingPlayerChat && !editSign && !editChest && !blockInput)
        {
            Main.player[myPlayer].controlInv = PlayerInput.Triggers.Current.Inventory;
            Main.player[myPlayer].controlCreativeMenu = PlayerInput.Triggers.Current.OpenCreativePowersMenu;
            Player player = Main.player[myPlayer];
            if (player.controlCreativeMenu)
            {
                if (player.releaseCreativeMenu)
                {
                    player.ToggleCreativeMenu();
                }
                player.releaseCreativeMenu = false;
            }
            else
            {
                player.releaseCreativeMenu = true;
            }
            if (player.controlInv)
            {
                if (player.releaseInventory)
                {
                    player.ToggleInv();
                }
                player.releaseInventory = false;
            }
            else
            {
                player.releaseInventory = true;
            }
        }
        if (playerInventory)
        {
            Main.player[myPlayer].RefreshInfoAccs();
            Recipe.GetThroughDelayedFindRecipes();
            if (PlayerInput.MouseInModdedUI.Count == 0)
            {
                int num = PlayerInput.ScrollWheelDelta / 120;
                bool flag = true;
                if (recBigList)
                {
                    int num2 = 42;
                    int num3 = 340;
                    int num4 = 310;
                    PlayerInput.SetZoom_UI();
                    int num5 = (screenWidth - num4 - 280) / num2;
                    int num6 = (screenHeight - num3 - 20) / num2;
                    Rectangle val = new Rectangle(num4, num3, num5 * num2, num6 * num2);
                    if (((Rectangle)(ref val)).Contains(MouseScreen.ToPoint()))
                    {
                        int num7 = Math.Sign(num);
                        while (num != 0)
{
                            if (num < 0)
{
                                recStart -= num5;
                                if (recStart < 0)
{
                                    recStart = 0;
                                }
                            }
                            else
{
                                recStart += num5;
                                SoundEngine.PlaySound(12);
                                if (recStart > numAvailableRecipes - num5)
{
                                    recStart = numAvailableRecipes - num5;
                                }
                            }
                            num -= num7;
                        }
                    }
                    PlayerInput.SetZoom_World();
                }
                if (flag)
                {
                    focusRecipe += num;
                    if (focusRecipe > numAvailableRecipes - 1)
                    {
                        focusRecipe = numAvailableRecipes - 1;
                    }
                    if (focusRecipe < 0)
                    {
                        focusRecipe = 0;
                    }
                }
            }
            PlayerInput.MouseInModdedUI.Clear();
            Main.player[myPlayer].dropItemCheck();
        }
        Main.player[myPlayer].head = Main.player[myPlayer].armor[0].headSlot;
        Main.player[myPlayer].body = Main.player[myPlayer].armor[1].bodySlot;
        Main.player[myPlayer].legs = Main.player[myPlayer].armor[2].legSlot;
        if (!Main.player[myPlayer].hostile)
        {
            if (Main.player[myPlayer].armor[10].headSlot >= 0)
            {
                Main.player[myPlayer].head = Main.player[myPlayer].armor[10].headSlot;
            }
            if (Main.player[myPlayer].armor[11].bodySlot >= 0)
            {
                Main.player[myPlayer].body = Main.player[myPlayer].armor[11].bodySlot;
            }
            if (Main.player[myPlayer].armor[12].legSlot >= 0)
            {
                Main.player[myPlayer].legs = Main.player[myPlayer].armor[12].legSlot;
            }
        }
        if (editSign)
        {
            if (Main.player[myPlayer].sign == -1)
            {
                editSign = false;
            }
            else
            {
                InputTextSign();
            }
        }
        else if (editChest && Main.player[myPlayer].chest == -1)
        {
            editChest = false;
        }
        Player.tileTargetX = (int)(((float)mouseX + screenPosition.X) / 16f);
        Player.tileTargetY = (int)(((float)mouseY + screenPosition.Y) / 16f);
        Main.player[myPlayer].LookForTileInteractions();
        Main.player[myPlayer].lastChest = Main.player[myPlayer].chest;
        if (playerInventory)
        {
            Main.player[myPlayer].AdjTiles();
        }
    }
References Terraria.Player.AdjTiles(), Terraria.Player.armor, Terraria.Main.blockInput, Terraria.Player.body, Terraria.Item.bodySlot, Terraria.Player.chest, Terraria.Player.controlCreativeMenu, Terraria.Player.controlInv, Terraria.GameInput.TriggersPack.Current, Terraria.Main.drawingPlayerChat, Terraria.Player.dropItemCheck(), Terraria.Main.editChest, Terraria.Main.editSign, Terraria.Main.focusRecipe, Terraria.Recipe.GetThroughDelayedFindRecipes(), Terraria.Player.head, Terraria.Item.headSlot, Terraria.Player.hostile, Terraria.Main.InputTextSign(), Terraria.GameInput.TriggersSet.Inventory, Terraria.Player.lastChest, Terraria.Player.legs, Terraria.Item.legSlot, Terraria.Player.LookForTileInteractions(), Terraria.GameInput.PlayerInput.MouseInModdedUI, Terraria.Main.MouseScreen, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.numAvailableRecipes, Terraria.GameInput.TriggersSet.OpenCreativePowersMenu, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.recBigList, Terraria.Main.recStart, Terraria.Player.RefreshInfoAccs(), Terraria.Player.releaseCreativeMenu, Terraria.Player.releaseInventory, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_World(), Terraria.Player.sign, Terraria.Player.ToggleCreativeMenu(), Terraria.Player.ToggleInv(), and Terraria.GameInput.PlayerInput.Triggers.
Referenced by Terraria.Main.DoUpdate().