TModLoader: Terraria.Main.DrawHotbarLockIcon
DrawHotbarLockIcon()
void Terraria.Main.DrawHotbarLockIcon (int pivotTopLeftX, int pivotTopLeftY, bool pushSideToolsUp) inline private
    {
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_017b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        int num = 21 + pivotTopLeftY;
        _ = player[myPlayer];
        if (pushSideToolsUp)
        {
            num = pivotTopLeftY;
        }
        float num2 = 0.9f;
        Texture2D value = TextureAssets.HbLock[(!player[myPlayer].hbLocked) ? 1u : 0u].Value;
        Rectangle value2 = value.Frame(2);
        bool flag = false;
        if (mouseX > pivotTopLeftX && (float)mouseX < (float)pivotTopLeftX + (float)value2.Width * num2 && mouseY > num && (float)mouseY < (float)num + (float)value2.Height * num2)
        {
            flag = true;
            player[myPlayer].mouseInterface = true;
            if (!player[myPlayer].hbLocked)
            {
                MouseText(Lang.inter[5].Value, 0, 0);
            }
            else
            {
                MouseText(Lang.inter[6].Value, 0, 0);
            }
            mouseText = true;
            if (mouseLeft && mouseLeftRelease)
            {
                SoundEngine.PlaySound(22);
                player[myPlayer].hbLocked = !player[myPlayer].hbLocked;
            }
        }
        spriteBatch.Draw(value, new Vector2((float)pivotTopLeftX, (float)num), (Rectangle?)value2, Color.White, 0f, default(Vector2), num2, (SpriteEffects)0, 0f);
        if (flag)
        {
            spriteBatch.Draw(value, new Vector2((float)pivotTopLeftX, (float)num), (Rectangle?)value.Frame(2, 1, 1), OurFavoriteColor, 0f, default(Vector2), num2, (SpriteEffects)0, 0f);
        }
    }
References Terraria.GameContent.TextureAssets.HbLock, Terraria.Lang.inter, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseText, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawInventory().