TModLoader: Terraria.Main.SubmitSignText
SubmitSignText()
static void Terraria.Main.SubmitSignText () inline static
Definition at line 52384 of file Main.cs.
    {
        SoundEngine.PlaySound(12);
        int num = player[myPlayer].sign;
        Sign.TextSign(num, npcChatText);
        editSign = false;
        if (netMode == 1)
        {
            NetMessage.SendData(47, -1, -1, null, num);
        }
    }
References Terraria.Main.editSign, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.npcChatText, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.Player.sign, and Terraria.Sign.TextSign().
Referenced by Terraria.Main.GUIChatDrawInner().