TModLoader: Terraria.Main.DrawPageIcons
DrawPageIcons()
static int Terraria.Main.DrawPageIcons (int yPos) inline static private
    {
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_019a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_023f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02be: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0277: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_028b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        int num = -1;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)(screenWidth - 162), (float)yPos);
        vector.X += 82f;
        Texture2D value = TextureAssets.EquipPage[(EquipPage == 2) ? 3 : 2].Value;
        if (Collision.CheckAABBvAABBCollision(vector, value.Size(), new Vector2((float)mouseX, (float)mouseY), Vector2.One) && (mouseItem.stack < 1 || mouseItem.dye > 0))
        {
            num = 2;
        }
        if (num == 2)
        {
            spriteBatch.Draw(TextureAssets.EquipPage[6].Value, vector, (Rectangle?)null, OurFavoriteColor, 0f, new Vector2(2f), 0.9f, (SpriteEffects)0, 0f);
        }
        spriteBatch.Draw(value, vector, (Rectangle?)null, Color.White, 0f, Vector2.Zero, 0.9f, (SpriteEffects)0, 0f);
        UILinkPointNavigator.SetPosition(305, vector + value.Size() * 0.75f);
        vector.X -= 48f;
        value = TextureAssets.EquipPage[(EquipPage == 1) ? 5 : 4].Value;
        if (Collision.CheckAABBvAABBCollision(vector, value.Size(), new Vector2((float)mouseX, (float)mouseY), Vector2.One) && mouseItem.stack < 1)
        {
            num = 1;
        }
        if (num == 1)
        {
            spriteBatch.Draw(TextureAssets.EquipPage[7].Value, vector, (Rectangle?)null, OurFavoriteColor, 0f, new Vector2(2f), 0.9f, (SpriteEffects)0, 0f);
        }
        spriteBatch.Draw(value, vector, (Rectangle?)null, Color.White, 0f, Vector2.Zero, 0.9f, (SpriteEffects)0, 0f);
        UILinkPointNavigator.SetPosition(306, vector + value.Size() * 0.75f);
        vector.X -= 48f;
        value = TextureAssets.EquipPage[(EquipPage == 3) ? 10 : 8].Value;
        if (Collision.CheckAABBvAABBCollision(vector, value.Size(), new Vector2((float)mouseX, (float)mouseY), Vector2.One) && mouseItem.stack < 1)
        {
            num = 3;
        }
        if (num == 3 && !CaptureModeDisabled)
        {
            spriteBatch.Draw(TextureAssets.EquipPage[9].Value, vector, (Rectangle?)null, OurFavoriteColor, 0f, Vector2.Zero, 0.9f, (SpriteEffects)0, 0f);
        }
        spriteBatch.Draw(value, vector, (Rectangle?)null, CaptureModeDisabled ? Color.Red : Color.White, 0f, Vector2.Zero, 0.9f, (SpriteEffects)0, 0f);
        UILinkPointNavigator.SetPosition(307, vector + value.Size() * 0.75f);
        if (num != -1)
        {
            player[myPlayer].mouseInterface = true;
            if (mouseLeft && mouseLeftRelease)
            {
                bool flag = true;
                if (num == 3)
                {
                    if (CaptureModeDisabled)
                    {
                        flag = false;
                    }
                    else if (PlayerInput.UsingGamepad)
                    {
                        CaptureInterface.QuickScreenshot();
                    }
                    else
                    {
                        CaptureManager.Instance.Active = true;
                        blockMouse = true;
                    }
                }
                else if (EquipPageSelected != num)
                {
                    EquipPageSelected = num;
                }
                else
                {
                    EquipPageSelected = 0;
                }
                if (flag)
                {
                    SoundEngine.PlaySound(10);
                }
            }
        }
        ItemSlot.SelectEquipPage(mouseItem);
        if (EquipPage == -1)
        {
            EquipPage = EquipPageSelected;
        }
        return num;
    }
References Terraria.Main.blockMouse, Terraria.Main.CaptureModeDisabled, Terraria.Collision.CheckAABBvAABBCollision(), Terraria.Graphics.Light.Color, Terraria.Item.dye, Terraria.GameContent.TextureAssets.EquipPage, Terraria.Main.EquipPage, Terraria.Main.EquipPageSelected, Terraria.Player.mouseInterface, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Graphics.Capture.CaptureInterface.QuickScreenshot(), Terraria.Main.screenWidth, Terraria.UI.ItemSlot.SelectEquipPage(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, Terraria.Item.stack, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.DrawInventory().