TModLoader: Terraria.Main.SetRecipeMaterialDisplayName
SetRecipeMaterialDisplayName()
static void Terraria.Main.SetRecipeMaterialDisplayName (int i) inline static private
Definition at line 54983 of file Main.cs.
    {
        HoverItem = recipe[availableRecipe[focusRecipe]].requiredItem[i].Clone();
        ItemSlot.MouseHover(22);
        hoverItemName = recipe[availableRecipe[focusRecipe]].requiredItem[i].Name;
        if (recipe[availableRecipe[focusRecipe]].ProcessGroupsForText(recipe[availableRecipe[focusRecipe]].requiredItem[i].type, out var theText))
        {
            HoverItem.SetNameOverride(theText);
        }
        if (recipe[availableRecipe[focusRecipe]].anyIronBar && recipe[availableRecipe[focusRecipe]].requiredItem[i].type == 22)
        {
            HoverItem.SetNameOverride(Lang.misc[37].Value + " " + Lang.GetItemNameValue(22));
        }
        else if (recipe[availableRecipe[focusRecipe]].anyWood && recipe[availableRecipe[focusRecipe]].requiredItem[i].type == 9)
        {
            HoverItem.SetNameOverride(Lang.misc[37].Value + " " + Lang.GetItemNameValue(9));
        }
        else if (recipe[availableRecipe[focusRecipe]].anySand && recipe[availableRecipe[focusRecipe]].requiredItem[i].type == 169)
        {
            HoverItem.SetNameOverride(Lang.misc[37].Value + " " + Lang.GetItemNameValue(169));
        }
        else if (recipe[availableRecipe[focusRecipe]].anyFragment && recipe[availableRecipe[focusRecipe]].requiredItem[i].type == 3458)
        {
            HoverItem.SetNameOverride(Lang.misc[37].Value + " " + Lang.misc[51].Value);
        }
        else if (recipe[availableRecipe[focusRecipe]].anyPressurePlate && recipe[availableRecipe[focusRecipe]].requiredItem[i].type == 542)
        {
            HoverItem.SetNameOverride(Lang.misc[37].Value + " " + Lang.misc[38].Value);
        }
        if (recipe[availableRecipe[focusRecipe]].requiredItem[i].stack > 1)
        {
            hoverItemName = hoverItemName + " (" + recipe[availableRecipe[focusRecipe]].requiredItem[i].stack + ")";
        }
    }
References Terraria.Main.availableRecipe, Terraria.Main.focusRecipe, Terraria.Lang.GetItemNameValue(), Terraria.Main.HoverItem, Terraria.Main.hoverItemName, Terraria.Lang.misc, Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.recipe, Terraria.Recipe.requiredItem, Terraria.Item.SetNameOverride(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DrawInventory().