TModLoader: Terraria.Main.DrawInterface_Healthbar_Worm
DrawInterface_Healthbar_Worm()
void Terraria.Main.DrawInterface_Healthbar_Worm (NPC head, int tailID, float scale) inline private
Definition at line 59560 of file Main.cs.
    {
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        NPC nPC = head;
        for (int i = head.whoAmI + 1; i < 200; i++)
        {
            if (npc[i].active && npc[i].type == tailID)
            {
                nPC = npc[i];
                break;
            }
        }
        Vector2 vector = (head.position + nPC.position) / 2f;
        DrawHealthBar(vector.X + (float)(head.width / 2), vector.Y + (float)(head.height / 2), head.life, head.lifeMax, Lighting.Brightness((int)((head.position.X + (float)(head.width / 2)) / 16f), (int)((head.position.Y + (float)(head.height / 2) + head.gfxOffY) / 16f)), scale);
    }
References Terraria.Lighting.Brightness(), Terraria.Main.DrawHealthBar(), Terraria.NPC.gfxOffY, Terraria.Entity.height, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.npc, Terraria.Entity.position, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.Main.DrawInterface_14_EntityHealthBars().