TModLoader: Terraria.Main.DrawProj_DrawVoidLens
DrawProj_DrawVoidLens()
void Terraria.Main.DrawProj_DrawVoidLens (Projectile proj, ref bool earlyReturn) inline private
Definition at line 33443 of file Main.cs.
    {
        if (proj.type == 734)
        {
            VoidLensHelper voidLensHelper = new VoidLensHelper(proj);
            _voidLensData.Clear();
            int selectionMode = TryInteractingWithVoidLens(proj);
            voidLensHelper.DrawToDrawData(_voidLensData, selectionMode);
            {
                foreach (DrawData voidLensDatum in _voidLensData)
                {
                    EntitySpriteDraw(voidLensDatum);
                }
                return;
            }
        }
        earlyReturn = false;
    }
References Terraria.Main._voidLensData, Terraria.Main.EntitySpriteDraw(), and Terraria.Main.TryInteractingWithVoidLens().
Referenced by Terraria.Main.DrawProj_Inner_DoDrawProj().