TModLoader: Terraria.Main.DrawGoreBehind
DrawGoreBehind()
void Terraria.Main.DrawGoreBehind () inline protected
    {
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_019f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_0296: Unknown result type (might be due to invalid IL or missing references)
        //IL_0322: Unknown result type (might be due to invalid IL or missing references)
        //IL_032e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_0372: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < 600; i++)
        {
            if (!gore[i].active || gore[i].type <= 0)
            {
                continue;
            }
            bool flag = false;
            if (GoreID.Sets.DrawBehind[gore[i].type])
            {
                if (gore[i].type < GoreID.Count)
                {
                    byte frame = gore[i].frame;
                    if (frame >= 7 && frame <= 9)
                    {
                        goto IL_006b;
                    }
                }
                flag = true;
            }
            goto IL_006b;
            IL_006b:
            if (flag)
            {
                LoadGore(gore[i].type);
                if (gore[i].Frame.ColumnCount > 1 || gore[i].Frame.RowCount > 1)
                {
                    Rectangle sourceRectangle = gore[i].Frame.GetSourceRectangle(TextureAssets.Gore[gore[i].type].Value);
                    Color alpha = gore[i].GetAlpha(Lighting.GetColor((int)((double)gore[i].position.X + (double)sourceRectangle.Width * 0.5) / 16, (int)(((double)gore[i].position.Y + (double)sourceRectangle.Height * 0.5) / 16.0)));
                    spriteBatch.Draw(TextureAssets.Gore[gore[i].type].Value, new Vector2(gore[i].position.X - screenPosition.X + (float)(sourceRectangle.Width / 2), gore[i].position.Y - screenPosition.Y + (float)(sourceRectangle.Height / 2) - 2f) + gore[i].drawOffset, (Rectangle?)sourceRectangle, alpha, gore[i].rotation, new Vector2((float)(sourceRectangle.Width / 2), (float)(sourceRectangle.Height / 2)), gore[i].scale, (SpriteEffects)0, 0f);
                }
                else
                {
                    Color alpha2 = gore[i].GetAlpha(Lighting.GetColor((int)((double)gore[i].position.X + (double)TextureAssets.Gore[gore[i].type].Width() * 0.5) / 16, (int)(((double)gore[i].position.Y + (double)TextureAssets.Gore[gore[i].type].Height() * 0.5) / 16.0)));
                    spriteBatch.Draw(TextureAssets.Gore[gore[i].type].Value, new Vector2(gore[i].position.X - screenPosition.X + (float)(TextureAssets.Gore[gore[i].type].Width() / 2), gore[i].position.Y - screenPosition.Y + (float)(TextureAssets.Gore[gore[i].type].Height() / 2)) + gore[i].drawOffset, (Rectangle?)new Rectangle(0, 0, TextureAssets.Gore[gore[i].type].Width(), TextureAssets.Gore[gore[i].type].Height()), alpha2, gore[i].rotation, new Vector2((float)(TextureAssets.Gore[gore[i].type].Width() / 2), (float)(TextureAssets.Gore[gore[i].type].Height() / 2)), gore[i].scale, (SpriteEffects)0, 0f);
                }
            }
        }
    }
References Terraria.Graphics.Light.Color, Terraria.ID.GoreID.Count, Terraria.ID.GoreID.Sets.DrawBehind, Terraria.Gore.drawOffset, Terraria.Gore.Frame, Terraria.Gore.frame, Terraria.Gore.GetAlpha(), Terraria.Lighting.GetColor(), Terraria.DataStructures.SpriteFrame.GetSourceRectangle(), Terraria.GameContent.TextureAssets.Gore, Terraria.Main.gore, Terraria.Main.LoadGore(), Terraria.Gore.position, Terraria.Gore.rotation, Terraria.DataStructures.SpriteFrame.RowCount, Terraria.Gore.scale, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, and Terraria.Gore.type.
Referenced by Terraria.Main.DrawBackGore(), and Terraria.Main.DrawCapture().