TModLoader: Terraria.Main.Initialize_TileAndNPCData1
Initialize_TileAndNPCData1()
static void Terraria.Main.Initialize_TileAndNPCData1 () inline static private
    {
        for (int i = 0; i < TileID.Count; i++)
        {
            tileGlowMask[i] = -1;
        }
        for (int j = 0; j < ProjectileID.Count; j++)
        {
            projFrames[j] = 1;
        }
        projFrames[736] = 3;
        projFrames[737] = 3;
        projFrames[738] = 3;
        projFrames[779] = 4;
        projFrames[783] = 4;
        projFrames[862] = 4;
        projFrames[863] = 4;
        projFrames[820] = 4;
        projFrames[916] = 6;
        projFrames[34] = 6;
        projFrames[706] = 8;
        projFrames[712] = 8;
        projFrames[663] = 7;
        projFrames[665] = 9;
        projFrames[667] = 9;
        projFrames[677] = 6;
        projFrames[678] = 6;
        projFrames[679] = 6;
        projFrames[688] = 6;
        projFrames[689] = 6;
        projFrames[690] = 8;
        projFrames[691] = 4;
        projFrames[692] = 4;
        projFrames[693] = 4;
        projFrames[694] = 4;
        projFrames[695] = 4;
        projFrames[696] = 5;
        projFrames[700] = 4;
        projFrames[964] = 1;
        projFrames[965] = 1;
        projFrames[643] = 8;
        projFrames[566] = 4;
        projFrames[565] = 4;
        projFrames[525] = 5;
        projFrames[519] = 4;
        projFrames[509] = 2;
        projFrames[485] = 5;
        projFrames[492] = 8;
        projFrames[500] = 4;
        projFrames[499] = 12;
        projFrames[518] = 4;
        projFrames[585] = 4;
        projFrames[593] = 4;
        projFrames[595] = 28;
        projFrames[735] = 28;
        projFrames[596] = 4;
        projFrames[612] = 5;
        projFrames[978] = 5;
        projFrames[613] = 4;
        projFrames[614] = 4;
        projFrames[615] = 7;
        projFrames[623] = 19;
        projFrames[633] = 5;
        projFrames[645] = 7;
        projFrames[650] = 4;
        projFrames[652] = 6;
        projFrames[659] = 4;
        projFrames[714] = 7;
        projFrames[734] = 8;
        projFrames[755] = 5;
        projFrames[759] = 5;
        projFrames[765] = 10;
        projFrames[951] = 12;
        projFrames[953] = 5;
        projFrames[384] = 6;
        projFrames[385] = 3;
        projFrames[386] = 6;
        projFrames[390] = 11;
        projFrames[391] = 11;
        projFrames[392] = 11;
        projFrames[393] = 15;
        projFrames[394] = 15;
        projFrames[395] = 15;
        projFrames[398] = 10;
        projFrames[407] = 6;
        projFrames[408] = 2;
        projFrames[409] = 3;
        projFrames[387] = 3;
        projFrames[388] = 3;
        projFrames[334] = 11;
        projFrames[324] = 10;
        projFrames[351] = 2;
        projFrames[349] = 5;
        projFrames[423] = 4;
        projFrames[435] = 4;
        projFrames[682] = 4;
        projFrames[436] = 4;
        projFrames[439] = 6;
        projFrames[443] = 4;
        projFrames[447] = 4;
        projFrames[448] = 3;
        projFrames[450] = 5;
        projFrames[454] = 2;
        projFrames[456] = 4;
        projFrames[459] = 3;
        projFrames[462] = 5;
        projFrames[465] = 4;
        projFrames[467] = 4;
        projFrames[468] = 4;
        projFrames[533] = 21;
        projFrames[535] = 12;
        projFrames[539] = 4;
        projFrames[575] = 4;
        projFrames[574] = 2;
        projFrames[634] = 4;
        projFrames[635] = 4;
        projFrames[709] = 3;
        projFrames[353] = 14;
        projFrames[346] = 2;
        projFrames[347] = 2;
        projFrames[335] = 4;
        projFrames[344] = 3;
        projFrames[337] = 5;
        projFrames[317] = 8;
        projFrames[321] = 3;
        projFrames[308] = 10;
        projFrames[316] = 4;
        projFrames[275] = 2;
        projFrames[276] = 2;
        projFrames[254] = 5;
        projFrames[307] = 2;
        projFrames[72] = 4;
        projFrames[86] = 4;
        projFrames[87] = 4;
        projFrames[102] = 2;
        projFrames[111] = 8;
        projFrames[112] = 6;
        projFrames[127] = 16;
        projFrames[175] = 2;
        projFrames[181] = 4;
        projFrames[189] = 4;
        projFrames[191] = 18;
        projFrames[192] = 18;
        projFrames[193] = 18;
        projFrames[194] = 18;
        projFrames[190] = 4;
        projFrames[198] = 4;
        projFrames[199] = 8;
        projFrames[200] = 10;
        projFrames[206] = 5;
        projFrames[208] = 5;
        projFrames[209] = 12;
        projFrames[210] = 12;
        projFrames[211] = 10;
        projFrames[221] = 3;
        projFrames[237] = 4;
        projFrames[238] = 6;
        projFrames[221] = 3;
        projFrames[228] = 5;
        projFrames[229] = 4;
        projFrames[236] = 13;
        projFrames[243] = 4;
        projFrames[244] = 6;
        projFrames[249] = 5;
        projFrames[252] = 4;
        projFrames[266] = 6;
        projFrames[268] = 8;
        projFrames[269] = 7;
        projFrames[270] = 3;
        projFrames[313] = 12;
        projFrames[314] = 13;
        projFrames[319] = 11;
        projFrames[373] = 3;
        projFrames[375] = 8;
        projFrames[377] = 9;
        projFrames[379] = 4;
        projFrames[380] = 4;
        projFrames[601] = 2;
        projFrames[602] = 4;
        projFrames[703] = 8;
        projFrames[701] = 3;
        projFrames[702] = 4;
        projFrames[732] = 4;
        projFrames[731] = 4;
        projFrames[758] = 24;
        projFrames[766] = 4;
        projFrames[767] = 4;
        projFrames[768] = 4;
        projFrames[769] = 4;
        projFrames[770] = 4;
        projFrames[774] = 8;
        projFrames[773] = 4;
        projFrames[815] = 10;
        projFrames[816] = 17;
        projFrames[817] = 18;
        projFrames[821] = 23;
        projFrames[824] = 4;
        projFrames[825] = 26;
        projFrames[826] = 3;
        projFrames[828] = 2;
        projFrames[829] = 2;
        projFrames[831] = 6;
        projFrames[970] = 6;
        projFrames[833] = 10;
        projFrames[834] = 12;
        projFrames[835] = 12;
        projFrames[836] = 4;
        projFrames[837] = 3;
        projFrames[839] = 4;
        projFrames[840] = 4;
        projFrames[851] = 4;
        projFrames[853] = 4;
        projFrames[854] = 19;
        projFrames[855] = 4;
        projFrames[858] = 14;
        projFrames[859] = 24;
        projFrames[860] = 14;
        projFrames[861] = 4;
        projFrames[864] = 2;
        projFrames[866] = 4;
        projFrames[870] = 4;
        projFrames[875] = 11;
        projFrames[881] = 12;
        projFrames[882] = 20;
        projFrames[883] = 3;
        projFrames[884] = 14;
        projFrames[885] = 10;
        projFrames[886] = 8;
        projFrames[887] = 3;
        projFrames[888] = 36;
        projFrames[889] = 11;
        projFrames[890] = 12;
        projFrames[891] = 15;
        projFrames[892] = 6;
        projFrames[893] = 4;
        projFrames[894] = 8;
        projFrames[895] = 6;
        projFrames[896] = 16;
        projFrames[897] = 11;
        projFrames[898] = 16;
        projFrames[899] = 14;
        projFrames[900] = 14;
        projFrames[901] = 12;
        projFrames[908] = 12;
        projFrames[909] = 6;
        projFrames[920] = 3;
        projFrames[934] = 12;
        projFrames[880] = 8;
        projFrames[929] = 8;
        projFrames[956] = 11;
        projFrames[957] = 12;
        projFrames[958] = 17;
        projFrames[959] = 12;
        projFrames[960] = 20;
        projFrames[961] = 1;
        projFrames[962] = 3;
        projFrames[963] = 13;
        projFrames[966] = 3;
        projFrames[967] = 8;
        projFrames[968] = 24;
        projFrames[969] = 8;
        projFrames[994] = 16;
        projFrames[995] = 20;
        projFrames[998] = 10;
        projFrames[1003] = 16;
        projFrames[1004] = 15;
        projFrames[1014] = 11;
        projPet[492] = true;
        projPet[499] = true;
        projPet[653] = true;
        projPet[701] = true;
        projPet[703] = true;
        projPet[702] = true;
        projPet[764] = true;
        projPet[765] = true;
        projPet[319] = true;
        projPet[334] = true;
        projPet[324] = true;
        projPet[266] = true;
        projPet[313] = true;
        projPet[314] = true;
        projPet[317] = true;
        projPet[175] = true;
        projPet[111] = true;
        projPet[112] = true;
        projPet[127] = true;
        projPet[191] = true;
        projPet[192] = true;
        projPet[193] = true;
        projPet[194] = true;
        projPet[197] = true;
        projPet[198] = true;
        projPet[199] = true;
        projPet[200] = true;
        projPet[208] = true;
        projPet[209] = true;
        projPet[210] = true;
        projPet[211] = true;
        projPet[236] = true;
        projPet[268] = true;
        projPet[269] = true;
        projPet[353] = true;
        projPet[373] = true;
        projPet[375] = true;
        projPet[380] = true;
        projPet[387] = true;
        projPet[388] = true;
        projPet[390] = true;
        projPet[391] = true;
        projPet[392] = true;
        projPet[393] = true;
        projPet[394] = true;
        projPet[395] = true;
        projPet[398] = true;
        projPet[407] = true;
        projPet[423] = true;
        projPet[533] = true;
        projPet[613] = true;
        projPet[623] = true;
        projPet[625] = true;
        projPet[626] = true;
        projPet[627] = true;
        projPet[628] = true;
        projPet[755] = true;
        projPet[758] = true;
        projPet[759] = true;
        projPet[774] = true;
        projPet[815] = true;
        projPet[816] = true;
        projPet[817] = true;
        projPet[821] = true;
        projPet[825] = true;
        projPet[831] = true;
        projPet[833] = true;
        projPet[834] = true;
        projPet[835] = true;
        projPet[854] = true;
        projPet[858] = true;
        projPet[859] = true;
        projPet[860] = true;
        projPet[864] = true;
        projPet[875] = true;
        projPet[946] = true;
        projPet[951] = true;
        projPet[963] = true;
        projPet[970] = true;
        projPet[881] = true;
        projPet[882] = true;
        projPet[883] = true;
        projPet[884] = true;
        projPet[885] = true;
        projPet[886] = true;
        projPet[887] = true;
        projPet[888] = true;
        projPet[889] = true;
        projPet[890] = true;
        projPet[891] = true;
        projPet[892] = true;
        projPet[893] = true;
        projPet[894] = true;
        projPet[895] = true;
        projPet[896] = true;
        projPet[897] = true;
        projPet[898] = true;
        projPet[899] = true;
        projPet[900] = true;
        projPet[901] = true;
        projPet[934] = true;
        projPet[956] = true;
        projPet[957] = true;
        projPet[958] = true;
        projPet[959] = true;
        projPet[960] = true;
        projPet[994] = true;
        projPet[998] = true;
        projPet[1003] = true;
        projPet[1004] = true;
        projPet[1018] = true;
        tileLighted[237] = true;
        tileLighted[27] = true;
        tileLighted[381] = true;
        tileLighted[534] = true;
        tileLighted[536] = true;
        tileLighted[539] = true;
        tileLighted[625] = true;
        tileLighted[627] = true;
        tileLighted[184] = true;
        tileLighted[463] = true;
        tileLighted[491] = true;
        slimeRainNPC[1] = true;
        debuff[158] = true;
        debuff[160] = true;
        debuff[20] = true;
        debuff[21] = true;
        debuff[22] = true;
        debuff[23] = true;
        debuff[24] = true;
        debuff[25] = true;
        debuff[28] = true;
        debuff[30] = true;
        debuff[31] = true;
        debuff[32] = true;
        debuff[33] = true;
        debuff[34] = true;
        debuff[35] = true;
        debuff[36] = true;
        debuff[37] = true;
        debuff[38] = true;
        debuff[39] = true;
        debuff[44] = true;
        debuff[46] = true;
        debuff[47] = true;
        debuff[67] = true;
        debuff[68] = true;
        debuff[69] = true;
        debuff[70] = true;
        debuff[80] = true;
        debuff[86] = true;
        debuff[87] = true;
        debuff[88] = true;
        debuff[89] = true;
        debuff[94] = true;
        debuff[103] = true;
        debuff[119] = true;
        debuff[120] = true;
        debuff[137] = true;
        debuff[145] = true;
        debuff[146] = true;
        debuff[147] = true;
        debuff[148] = true;
        debuff[149] = true;
        debuff[156] = true;
        debuff[157] = true;
        debuff[350] = true;
        debuff[163] = true;
        debuff[164] = true;
        debuff[144] = true;
        debuff[194] = true;
        debuff[195] = true;
        debuff[196] = true;
        debuff[197] = true;
        debuff[199] = true;
        debuff[215] = true;
        debuff[320] = true;
        debuff[321] = true;
        debuff[332] = true;
        debuff[333] = true;
        debuff[334] = true;
        debuff[353] = true;
        pvpBuff[20] = true;
        pvpBuff[70] = true;
        pvpBuff[24] = true;
        pvpBuff[323] = true;
        pvpBuff[31] = true;
        pvpBuff[39] = true;
        pvpBuff[44] = true;
        pvpBuff[324] = true;
        pvpBuff[69] = true;
        pvpBuff[103] = true;
        pvpBuff[119] = true;
        pvpBuff[120] = true;
        pvpBuff[137] = true;
        pvpBuff[320] = true;
        meleeBuff[71] = true;
        meleeBuff[73] = true;
        meleeBuff[74] = true;
        meleeBuff[75] = true;
        meleeBuff[76] = true;
        meleeBuff[77] = true;
        meleeBuff[78] = true;
        meleeBuff[79] = true;
        buffNoSave[20] = true;
        buffNoSave[22] = true;
        buffNoSave[23] = true;
        buffNoSave[24] = true;
        buffNoSave[28] = true;
        buffNoSave[30] = true;
        buffNoSave[31] = true;
        buffNoSave[34] = true;
        buffNoSave[35] = true;
        buffNoSave[37] = true;
        buffNoSave[38] = true;
        buffNoSave[39] = true;
        buffNoSave[43] = true;
        buffNoSave[44] = true;
        buffNoSave[46] = true;
        buffNoSave[47] = true;
        buffNoSave[48] = true;
        buffNoSave[58] = true;
        buffNoSave[59] = true;
        buffNoSave[60] = true;
        buffNoSave[62] = true;
        buffNoSave[63] = true;
        buffNoSave[64] = true;
        buffNoSave[67] = true;
        buffNoSave[68] = true;
        buffNoSave[69] = true;
        buffNoSave[70] = true;
        buffNoSave[72] = true;
        buffNoSave[80] = true;
        buffNoSave[87] = true;
        buffNoSave[158] = true;
        buffNoSave[146] = true;
        buffNoSave[147] = true;
        buffNoSave[215] = true;
        buffNoSave[88] = true;
        buffNoSave[89] = true;
        buffNoSave[94] = true;
        buffNoSave[95] = true;
        buffNoSave[96] = true;
        buffNoSave[97] = true;
        buffNoSave[98] = true;
        buffNoSave[99] = true;
        buffNoSave[100] = true;
        buffNoSave[103] = true;
        buffNoSave[118] = true;
        buffNoSave[138] = true;
        buffNoSave[167] = true;
        buffNoSave[166] = true;
        buffNoSave[184] = true;
        buffNoSave[185] = true;
        buffNoSave[211] = true;
        buffNoSave[210] = true;
        buffNoSave[119] = true;
        buffNoSave[120] = true;
        buffNoSave[90] = true;
        buffNoSave[125] = true;
        buffNoSave[126] = true;
        buffNoSave[128] = true;
        buffNoSave[129] = true;
        buffNoSave[130] = true;
        buffNoSave[131] = true;
        buffNoSave[132] = true;
        buffNoSave[133] = true;
        buffNoSave[134] = true;
        buffNoSave[135] = true;
        buffNoSave[139] = true;
        buffNoSave[140] = true;
        buffNoSave[141] = true;
        buffNoSave[142] = true;
        buffNoSave[143] = true;
        buffNoSave[137] = true;
        buffNoSave[144] = true;
        buffNoSave[161] = true;
        buffNoSave[162] = true;
        buffNoSave[163] = true;
        buffNoSave[164] = true;
        buffNoSave[168] = true;
        buffNoSave[170] = true;
        buffNoSave[171] = true;
        buffNoSave[172] = true;
        buffNoSave[182] = true;
        buffNoSave[187] = true;
        buffNoSave[188] = true;
        buffNoSave[193] = true;
        buffNoSave[194] = true;
        buffNoSave[195] = true;
        buffNoSave[196] = true;
        buffNoSave[197] = true;
        buffNoSave[198] = true;
        buffNoSave[199] = true;
        buffNoSave[205] = true;
        buffNoSave[212] = true;
        buffNoSave[213] = true;
        buffNoSave[214] = true;
        buffNoSave[230] = true;
        buffNoSave[263] = true;
        buffNoSave[265] = true;
        buffNoSave[271] = true;
        buffNoSave[322] = true;
        buffNoSave[275] = true;
        buffNoSave[276] = true;
        buffNoSave[277] = true;
        buffNoSave[278] = true;
        buffNoSave[279] = true;
        buffNoSave[280] = true;
        buffNoSave[281] = true;
        buffNoSave[282] = true;
        buffNoSave[283] = true;
        buffNoSave[305] = true;
        buffNoSave[318] = true;
        buffNoSave[342] = true;
        buffNoSave[320] = true;
        buffNoSave[321] = true;
        buffNoSave[325] = true;
        buffNoSave[335] = true;
        buffNoSave[150] = true;
        buffNoSave[93] = true;
        buffNoSave[159] = true;
        buffNoSave[29] = true;
        buffNoSave[348] = true;
        buffNoSave[353] = true;
        for (int k = 173; k <= 181; k++)
        {
            buffNoSave[k] = true;
        }
        buffNoTimeDisplay[19] = true;
        buffNoTimeDisplay[27] = true;
        buffNoTimeDisplay[28] = true;
        buffNoTimeDisplay[34] = true;
        buffNoTimeDisplay[37] = true;
        buffNoTimeDisplay[38] = true;
        buffNoTimeDisplay[40] = true;
        buffNoTimeDisplay[41] = true;
        buffNoTimeDisplay[42] = true;
        buffNoTimeDisplay[43] = true;
        buffNoTimeDisplay[45] = true;
        buffNoTimeDisplay[49] = true;
        buffNoTimeDisplay[60] = true;
        buffNoTimeDisplay[62] = true;
        buffNoTimeDisplay[64] = true;
        buffNoTimeDisplay[68] = true;
        buffNoTimeDisplay[81] = true;
        buffNoTimeDisplay[82] = true;
        buffNoTimeDisplay[83] = true;
        buffNoTimeDisplay[90] = true;
        buffNoTimeDisplay[95] = true;
        buffNoTimeDisplay[96] = true;
        buffNoTimeDisplay[97] = true;
        buffNoTimeDisplay[98] = true;
        buffNoTimeDisplay[99] = true;
        buffNoTimeDisplay[100] = true;
        buffNoTimeDisplay[101] = true;
        buffNoTimeDisplay[102] = true;
        buffNoTimeDisplay[118] = true;
        buffNoTimeDisplay[138] = true;
        buffNoTimeDisplay[167] = true;
        buffNoTimeDisplay[166] = true;
        buffNoTimeDisplay[184] = true;
        buffNoTimeDisplay[185] = true;
        buffNoTimeDisplay[211] = true;
        buffNoTimeDisplay[210] = true;
        buffNoTimeDisplay[125] = true;
        buffNoTimeDisplay[126] = true;
        buffNoTimeDisplay[128] = true;
        buffNoTimeDisplay[129] = true;
        buffNoTimeDisplay[130] = true;
        buffNoTimeDisplay[131] = true;
        buffNoTimeDisplay[132] = true;
        buffNoTimeDisplay[133] = true;
        buffNoTimeDisplay[134] = true;
        buffNoTimeDisplay[135] = true;
        buffNoTimeDisplay[136] = true;
        buffNoTimeDisplay[139] = true;
        buffNoTimeDisplay[140] = true;
        buffNoTimeDisplay[141] = true;
        buffNoTimeDisplay[142] = true;
        buffNoTimeDisplay[143] = true;
        buffNoTimeDisplay[137] = true;
        buffNoTimeDisplay[200] = true;
        buffNoTimeDisplay[202] = true;
        buffNoTimeDisplay[201] = true;
        buffNoTimeDisplay[161] = true;
        buffNoTimeDisplay[162] = true;
        buffNoTimeDisplay[163] = true;
        buffNoTimeDisplay[168] = true;
        buffNoTimeDisplay[170] = true;
        buffNoTimeDisplay[171] = true;
        buffNoTimeDisplay[172] = true;
        buffNoTimeDisplay[182] = true;
        buffNoTimeDisplay[165] = true;
        buffNoTimeDisplay[186] = true;
        buffNoTimeDisplay[187] = true;
        buffNoTimeDisplay[188] = true;
        buffNoTimeDisplay[193] = true;
        buffNoTimeDisplay[199] = true;
        buffNoTimeDisplay[212] = true;
        buffNoTimeDisplay[213] = true;
        buffNoTimeDisplay[214] = true;
        buffNoTimeDisplay[216] = true;
        buffNoTimeDisplay[217] = true;
        buffNoTimeDisplay[219] = true;
        buffNoTimeDisplay[230] = true;
        buffNoTimeDisplay[258] = true;
        buffNoTimeDisplay[259] = true;
        buffNoTimeDisplay[260] = true;
        buffNoTimeDisplay[261] = true;
        buffNoTimeDisplay[262] = true;
        buffNoTimeDisplay[263] = true;
        buffNoTimeDisplay[264] = true;
        buffNoTimeDisplay[265] = true;
        buffNoTimeDisplay[266] = true;
        buffNoTimeDisplay[267] = true;
        buffNoTimeDisplay[268] = true;
        buffNoTimeDisplay[271] = true;
        buffNoTimeDisplay[322] = true;
        buffNoTimeDisplay[274] = true;
        buffNoTimeDisplay[275] = true;
        buffNoTimeDisplay[276] = true;
        buffNoTimeDisplay[277] = true;
        buffNoTimeDisplay[278] = true;
        buffNoTimeDisplay[279] = true;
        buffNoTimeDisplay[280] = true;
        buffNoTimeDisplay[281] = true;
        buffNoTimeDisplay[282] = true;
        buffNoTimeDisplay[283] = true;
        buffNoTimeDisplay[284] = true;
        buffNoTimeDisplay[285] = true;
        buffNoTimeDisplay[286] = true;
        buffNoTimeDisplay[287] = true;
        buffNoTimeDisplay[288] = true;
        buffNoTimeDisplay[289] = true;
        buffNoTimeDisplay[290] = true;
        buffNoTimeDisplay[291] = true;
        buffNoTimeDisplay[292] = true;
        buffNoTimeDisplay[293] = true;
        buffNoTimeDisplay[294] = true;
        buffNoTimeDisplay[295] = true;
        buffNoTimeDisplay[296] = true;
        buffNoTimeDisplay[297] = true;
        buffNoTimeDisplay[298] = true;
        buffNoTimeDisplay[299] = true;
        buffNoTimeDisplay[300] = true;
        buffNoTimeDisplay[301] = true;
        buffNoTimeDisplay[302] = true;
        buffNoTimeDisplay[303] = true;
        buffNoTimeDisplay[304] = true;
        buffNoTimeDisplay[305] = true;
        buffNoTimeDisplay[317] = true;
        buffNoTimeDisplay[318] = true;
        buffNoTimeDisplay[342] = true;
        buffNoTimeDisplay[320] = true;
        buffNoTimeDisplay[325] = true;
        buffNoTimeDisplay[335] = true;
        buffNoTimeDisplay[341] = true;
        buffNoTimeDisplay[327] = true;
        buffNoTimeDisplay[328] = true;
        buffNoTimeDisplay[329] = true;
        buffNoTimeDisplay[330] = true;
        buffNoTimeDisplay[331] = true;
        buffNoTimeDisplay[334] = true;
        buffNoTimeDisplay[345] = true;
        buffNoTimeDisplay[349] = true;
        buffNoTimeDisplay[351] = true;
        buffNoTimeDisplay[352] = true;
        buffNoTimeDisplay[354] = true;
        buffNoTimeDisplay[29] = true;
        buffNoTimeDisplay[159] = true;
        buffNoTimeDisplay[150] = true;
        buffNoTimeDisplay[93] = true;
        buffNoTimeDisplay[348] = true;
        buffNoTimeDisplay[353] = true;
        persistentBuff[71] = true;
        persistentBuff[73] = true;
        persistentBuff[74] = true;
        persistentBuff[75] = true;
        persistentBuff[76] = true;
        persistentBuff[77] = true;
        persistentBuff[78] = true;
        persistentBuff[79] = true;
        Initialize_BuffDataFromMountData();
        Initialize_TileAndNPCData1_Part2();
    }
References Terraria.Main.buffNoSave, Terraria.Main.buffNoTimeDisplay, Terraria.ID.ProjectileID.Count, Terraria.ID.TileID.Count, Terraria.Main.debuff, Terraria.Main.Initialize_BuffDataFromMountData(), Terraria.Main.Initialize_TileAndNPCData1_Part2(), Terraria.Main.meleeBuff, Terraria.Main.persistentBuff, Terraria.Main.projFrames, Terraria.Main.projPet, Terraria.Main.pvpBuff, Terraria.Main.slimeRainNPC, Terraria.Main.tileGlowMask, and Terraria.Main.tileLighted.
Referenced by Terraria.Main.Initialize_AlmostEverything().