TModLoader: Terraria.Main.DrawSurfaceBG_Jungle
DrawSurfaceBG_Jungle()
void Terraria.Main.DrawSurfaceBG_Jungle (double backgroundTopMagicNumber, float bgGlobalScaleMultiplier, int pushBGTopHack, int[] bgTexIndexes) inline private
    {
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0354: Unknown result type (might be due to invalid IL or missing references)
        //IL_0363: Unknown result type (might be due to invalid IL or missing references)
        //IL_036f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        //IL_0525: Unknown result type (might be due to invalid IL or missing references)
        //IL_0534: Unknown result type (might be due to invalid IL or missing references)
        //IL_0540: Unknown result type (might be due to invalid IL or missing references)
        //IL_0546: Unknown result type (might be due to invalid IL or missing references)
        LoadBackground(bgTexIndexes[0]);
        bgScale = 1.25f;
        bgScale *= bgGlobalScaleMultiplier;
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[0]] * bgScale);
        bgParallax = 0.4;
        SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 1800.0 + 1660.0) + (int)scAdj + pushBGTopHack;
        SetBackgroundOffsets(bgTexIndexes[0], backgroundTopMagicNumber, pushBGTopHack);
        if (gameMenu)
        {
            bgTopY = 320 + pushBGTopHack;
        }
        if (bgTexIndexes[0] == 59)
        {
            bgTopY -= 200;
        }
        bgTopY += DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[0]);
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int i = 0; i < bgLoops; i++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[0]].Value, new Vector2((float)(bgStartX + bgWidthScaled * i), (float)bgTopY), GetBackgroundRect(bgTexIndexes[0]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
        LoadBackground(bgTexIndexes[1]);
        bgScale = 1.31f;
        bgScale *= bgGlobalScaleMultiplier;
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[1]] * bgScale);
        bgParallax = 0.43;
        SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 1950.0 + 1840.0) + (int)scAdj + pushBGTopHack;
        SetBackgroundOffsets(bgTexIndexes[1], backgroundTopMagicNumber, pushBGTopHack);
        if (gameMenu)
        {
            bgTopY = 400 + pushBGTopHack;
            bgStartX -= 80;
        }
        if (bgTexIndexes[1] == 60)
        {
            bgTopY -= 175;
        }
        bgTopY += DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[1]);
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int j = 0; j < bgLoops; j++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[1]].Value, new Vector2((float)(bgStartX + bgWidthScaled * j), (float)bgTopY), GetBackgroundRect(bgTexIndexes[1]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)1, 0f);
            }
        }
        bgScale = 1.34f;
        bgScale *= bgGlobalScaleMultiplier;
        LoadBackground(bgTexIndexes[2]);
        bgWidthScaled = (int)((float)backgroundWidth[bgTexIndexes[2]] * bgScale);
        bgParallax = 0.49;
        SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
        SkyManager.Instance.DrawToDepth(spriteBatch, 1f / (float)bgParallax);
        bgStartX = (int)(0.0 - Math.IEEERemainder((double)screenPosition.X * bgParallax, bgWidthScaled) - (double)(bgWidthScaled / 2));
        bgTopY = (int)(backgroundTopMagicNumber * 2100.0 + 2060.0) + (int)scAdj + pushBGTopHack;
        SetBackgroundOffsets(bgTexIndexes[2], backgroundTopMagicNumber, pushBGTopHack);
        if (gameMenu)
        {
            bgTopY = 480 + pushBGTopHack;
            bgStartX -= 120;
        }
        if (bgTexIndexes[2] == 61)
        {
            bgTopY -= 150;
        }
        bgTopY += DrawSurfaceBG_GetLayerYOffset(bgTexIndexes[2]);
        bgLoops = screenWidth / bgWidthScaled + 2;
        if ((double)screenPosition.Y < worldSurface * 16.0 + 16.0)
        {
            for (int k = 0; k < bgLoops; k++)
            {
                spriteBatch.Draw(TextureAssets.Background[bgTexIndexes[2]].Value, new Vector2((float)(bgStartX + bgWidthScaled * k), (float)bgTopY), GetBackgroundRect(bgTexIndexes[2]), ColorOfSurfaceBackgroundsModified, 0f, default(Vector2), bgScale, (SpriteEffects)0, 0f);
            }
        }
    }
References Terraria.GameContent.TextureAssets.Background, Terraria.Main.backgroundWidth, Terraria.Main.bgLoops, Terraria.Main.bgParallax, Terraria.Main.bgScale, Terraria.Main.bgStartX, Terraria.Main.bgTopY, Terraria.Main.bgWidthScaled, Terraria.Main.ColorOfSurfaceBackgroundsModified, Terraria.Main.DrawSurfaceBG_GetLayerYOffset(), Terraria.Main.gameMenu, Terraria.Main.GetBackgroundRect(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.LoadBackground(), Terraria.Main.scAdj, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.SetBackgroundOffsets(), Terraria.Main.spriteBatch, and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DrawSurfaceBG().