TModLoader: Terraria.Main.DrawProj_FishingLine
DrawProj_FishingLine()
static void Terraria.Main.DrawProj_FishingLine (Projectile proj, ref float polePosX, ref float polePosY, Vector2 mountedCenter) inline static private
    {
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_052c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_0538: Unknown result type (might be due to invalid IL or missing references)
        //IL_053f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0549: Unknown result type (might be due to invalid IL or missing references)
        //IL_054e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0553: Unknown result type (might be due to invalid IL or missing references)
        //IL_056e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0591: Unknown result type (might be due to invalid IL or missing references)
        //IL_063d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0660: Unknown result type (might be due to invalid IL or missing references)
        //IL_0709: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0880: Unknown result type (might be due to invalid IL or missing references)
        //IL_088b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0899: Unknown result type (might be due to invalid IL or missing references)
        //IL_089a: Unknown result type (might be due to invalid IL or missing references)
        //IL_089f: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0907: Unknown result type (might be due to invalid IL or missing references)
        //IL_0911: Unknown result type (might be due to invalid IL or missing references)
        //IL_092b: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[proj.owner];
        polePosX = mountedCenter.X;
        polePosY = mountedCenter.Y;
        polePosY += player.gfxOffY;
        if (player.mount.Active && player.mount.Type == 52)
        {
            polePosX -= player.direction * 14;
            polePosY -= -10f;
        }
        int type = player.inventory[player.selectedItem].type;
        Color stringColor = default(Color);
        ((Color)(ref stringColor))._002Ector(200, 200, 200, 100);
        if (type == 2294)
        {
            ((Color)(ref stringColor))._002Ector(100, 180, 230, 100);
        }
        if (type == 2295)
        {
            ((Color)(ref stringColor))._002Ector(250, 90, 70, 100);
        }
        if (type == 2293)
        {
            ((Color)(ref stringColor))._002Ector(203, 190, 210, 100);
        }
        if (type == 2421)
        {
            ((Color)(ref stringColor))._002Ector(183, 77, 112, 100);
        }
        if (type == 2422)
        {
            ((Color)(ref stringColor))._002Ector(255, 226, 116, 100);
        }
        if (type == 4325)
        {
            ((Color)(ref stringColor))._002Ector(200, 100, 100, 100);
        }
        if (type == 4442)
        {
            ((Color)(ref stringColor))._002Ector(100, 100, 200, 100);
        }
        ProjectileLoader.ModifyFishingLine(proj, ref polePosX, ref polePosY, ref stringColor);
        stringColor = TryApplyingPlayerStringColor(Main.player[proj.owner].stringColor, stringColor);
        float gravDir = Main.player[proj.owner].gravDir;
        switch (type)
        {
        case 2289:
            polePosX += 43 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 36f * gravDir;
            break;
        case 2291:
            polePosX += 43 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 34f * gravDir;
            break;
        case 2292:
            polePosX += 46 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 34f * gravDir;
            break;
        case 2293:
            polePosX += 43 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 34f * gravDir;
            break;
        case 2294:
            polePosX += 43 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 30f * gravDir;
            break;
        case 2295:
            polePosX += 43 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 30f * gravDir;
            break;
        case 2296:
            polePosX += 43 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 30f * gravDir;
            break;
        case 2421:
            polePosX += 47 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 36f * gravDir;
            break;
        case 2422:
            polePosX += 47 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 32f * gravDir;
            break;
        case 4325:
            polePosX += 44 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 32f * gravDir;
            break;
        case 4442:
            polePosX += 44 * Main.player[proj.owner].direction;
            if (Main.player[proj.owner].direction < 0)
            {
                polePosX -= 13f;
            }
            polePosY -= 32f * gravDir;
            break;
        }
        if (gravDir == -1f)
        {
            polePosY -= 12f;
        }
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(polePosX, polePosY);
        vector = Main.player[proj.owner].RotatedRelativePoint(vector + new Vector2(8f)) - new Vector2(8f);
        float num = proj.position.X + (float)proj.width * 0.5f - vector.X;
        float num2 = proj.position.Y + (float)proj.height * 0.5f - vector.Y;
        Math.Sqrt(num * num + num2 * num2);
        float num3 = (float)Math.Atan2(num2, num) - 1.57f;
        bool flag = true;
        if (num == 0f && num2 == 0f)
        {
            flag = false;
        }
        else
        {
            float num4 = (float)Math.Sqrt(num * num + num2 * num2);
            num4 = 12f / num4;
            num *= num4;
            num2 *= num4;
            vector.X -= num;
            vector.Y -= num2;
            num = proj.position.X + (float)proj.width * 0.5f - vector.X;
            num2 = proj.position.Y + (float)proj.height * 0.5f - vector.Y;
        }
        while (flag)
        {
            float num5 = 12f;
            float num6 = (float)Math.Sqrt(num * num + num2 * num2);
            float num7 = num6;
            if (float.IsNaN(num6) || float.IsNaN(num7))
            {
                flag = false;
                continue;
            }
            if (num6 < 20f)
            {
                num5 = num6 - 8f;
                flag = false;
            }
            num6 = 12f / num6;
            num *= num6;
            num2 *= num6;
            vector.X += num;
            vector.Y += num2;
            num = proj.position.X + (float)proj.width * 0.5f - vector.X;
            num2 = proj.position.Y + (float)proj.height * 0.1f - vector.Y;
            if (num7 > 12f)
            {
                float num8 = 0.3f;
                float num9 = Math.Abs(proj.velocity.X) + Math.Abs(proj.velocity.Y);
                if (num9 > 16f)
                {
                    num9 = 16f;
                }
                num9 = 1f - num9 / 16f;
                num8 *= num9;
                num9 = num7 / 80f;
                if (num9 > 1f)
                {
                    num9 = 1f;
                }
                num8 *= num9;
                if (num8 < 0f)
                {
                    num8 = 0f;
                }
                num9 = 1f - proj.localAI[0] / 100f;
                num8 *= num9;
                if (num2 > 0f)
                {
                    num2 *= 1f + num8;
                    num *= 1f - num8;
                }
                else
                {
                    num9 = Math.Abs(proj.velocity.X) / 3f;
                    if (num9 > 1f)
                    {
                        num9 = 1f;
                    }
                    num9 -= 0.5f;
                    num8 *= num9;
                    if (num8 > 0f)
                    {
                        num8 *= 2f;
                    }
                    num2 *= 1f + num8;
                    num *= 1f - num8;
                }
            }
            num3 = (float)Math.Atan2(num2, num) - 1.57f;
            Color color = Lighting.GetColor((int)vector.X / 16, (int)(vector.Y / 16f), stringColor);
            EntitySpriteDraw(TextureAssets.FishingLine.Value, new Vector2(vector.X - screenPosition.X + (float)TextureAssets.FishingLine.Width() * 0.5f, vector.Y - screenPosition.Y + (float)TextureAssets.FishingLine.Height() * 0.5f), (Rectangle?)new Rectangle(0, 0, TextureAssets.FishingLine.Width(), (int)num5), color, num3, new Vector2((float)TextureAssets.FishingLine.Width() * 0.5f, 0f), 1f, (SpriteEffects)0, 0f);
        }
    }
References Terraria.Mount.Active, Terraria.Graphics.Light.Color, Terraria.Entity.direction, Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.TextureAssets.FishingLine, Terraria.Lighting.GetColor(), Terraria.Player.gfxOffY, Terraria.Player.gravDir, Terraria.Player.inventory, Terraria.ModLoader.ProjectileLoader.ModifyFishingLine(), Terraria.Player.mount, Terraria.Main.player, Terraria.Player.RotatedRelativePoint(), Terraria.Main.screenPosition, Terraria.Player.selectedItem, Terraria.Player.stringColor, Terraria.Main.TryApplyingPlayerStringColor(), Terraria.Item.type, and Terraria.Mount.Type.
Referenced by Terraria.Main.DrawProj_DrawExtras().