TModLoader: Terraria.Main.DrawNPCExtras
DrawNPCExtras()
void Terraria.Main.DrawNPCExtras (NPC n, bool beforeDraw, float addHeight, float addY, Color npcColor, Vector2 halfSize, SpriteEffects npcSpriteEffect, Vector2 screenPosition) inline protected
    {
        //IL_0688: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0712: Unknown result type (might be due to invalid IL or missing references)
        //IL_072d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0733: Unknown result type (might be due to invalid IL or missing references)
        //IL_073e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0740: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0753: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e8c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e91: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0de8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dea: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dfb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e05: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e15: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e30: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e35: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e52: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_10c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_10cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_10d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_12d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_12db: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_12f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_12fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_1300: Unknown result type (might be due to invalid IL or missing references)
        //IL_1302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fcf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fdb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_131a: Unknown result type (might be due to invalid IL or missing references)
        //IL_131f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1324: Unknown result type (might be due to invalid IL or missing references)
        //IL_132d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1334: Unknown result type (might be due to invalid IL or missing references)
        //IL_133e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1345: Unknown result type (might be due to invalid IL or missing references)
        //IL_134f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1354: Unknown result type (might be due to invalid IL or missing references)
        //IL_135c: Unknown result type (might be due to invalid IL or missing references)
        //IL_135e: Unknown result type (might be due to invalid IL or missing references)
        //IL_136a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1372: Unknown result type (might be due to invalid IL or missing references)
        //IL_1375: Unknown result type (might be due to invalid IL or missing references)
        //IL_111a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1126: Unknown result type (might be due to invalid IL or missing references)
        //IL_1008: Unknown result type (might be due to invalid IL or missing references)
        //IL_100d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1012: Unknown result type (might be due to invalid IL or missing references)
        //IL_101b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1022: Unknown result type (might be due to invalid IL or missing references)
        //IL_102c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1033: Unknown result type (might be due to invalid IL or missing references)
        //IL_103d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1042: Unknown result type (might be due to invalid IL or missing references)
        //IL_104a: Unknown result type (might be due to invalid IL or missing references)
        //IL_104c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1058: Unknown result type (might be due to invalid IL or missing references)
        //IL_1060: Unknown result type (might be due to invalid IL or missing references)
        //IL_1063: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_113f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1145: Unknown result type (might be due to invalid IL or missing references)
        //IL_13da: Unknown result type (might be due to invalid IL or missing references)
        //IL_13df: Unknown result type (might be due to invalid IL or missing references)
        //IL_1185: Unknown result type (might be due to invalid IL or missing references)
        //IL_1199: Unknown result type (might be due to invalid IL or missing references)
        //IL_119e: Unknown result type (might be due to invalid IL or missing references)
        //IL_11a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        //IL_0413: Unknown result type (might be due to invalid IL or missing references)
        //IL_0418: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_0985: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_140b: Unknown result type (might be due to invalid IL or missing references)
        //IL_11be: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_11c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_11cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_11d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_11ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_1216: Unknown result type (might be due to invalid IL or missing references)
        //IL_1220: Unknown result type (might be due to invalid IL or missing references)
        //IL_1225: Unknown result type (might be due to invalid IL or missing references)
        //IL_122a: Unknown result type (might be due to invalid IL or missing references)
        //IL_122c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1233: Unknown result type (might be due to invalid IL or missing references)
        //IL_1238: Unknown result type (might be due to invalid IL or missing references)
        //IL_123d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1245: Unknown result type (might be due to invalid IL or missing references)
        //IL_126b: Unknown result type (might be due to invalid IL or missing references)
        //IL_127b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1285: Unknown result type (might be due to invalid IL or missing references)
        //IL_128a: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a00: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ada: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b3a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b78: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b93: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b98: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ba2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bb5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_14ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_14bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c7d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0caf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0cc9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d31: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d44: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_1495: Unknown result type (might be due to invalid IL or missing references)
        //IL_149a: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0602: Unknown result type (might be due to invalid IL or missing references)
        //IL_060a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0611: Unknown result type (might be due to invalid IL or missing references)
        //IL_0619: Unknown result type (might be due to invalid IL or missing references)
        //IL_061e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_062d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_063e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_14dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_14f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_14f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_1509: Unknown result type (might be due to invalid IL or missing references)
        //IL_150b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1510: Unknown result type (might be due to invalid IL or missing references)
        //IL_1518: Unknown result type (might be due to invalid IL or missing references)
        //IL_151a: Unknown result type (might be due to invalid IL or missing references)
        //IL_1520: Unknown result type (might be due to invalid IL or missing references)
        //IL_1527: Unknown result type (might be due to invalid IL or missing references)
        //IL_152f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1532: Unknown result type (might be due to invalid IL or missing references)
        if (!beforeDraw && n.UsesPartyHat())
        {
            int num = n.frame.Y / n.frame.Height;
            int[] array = NPCID.Sets.TownNPCsFramingGroups[NPCID.Sets.NPCFramingGroup[n.type]];
            if (num >= array.Length)
            {
                num = 0;
            }
            Texture2D value = TextureAssets.Extra[72].Value;
            int num11 = 0;
            switch (n.GetPartyHatColor())
            {
            case PartyHatColor.Pink:
                num11 = 16;
                break;
            case PartyHatColor.Cyan:
                num11 = 17;
                break;
            case PartyHatColor.Purple:
                num11 = 18;
                break;
            case PartyHatColor.White:
                num11 = 19;
                break;
            }
            Rectangle rectangle = value.Frame(20, 1, num11 % 20);
            rectangle.Width -= 2;
            rectangle.Height -= 2;
            int num15 = 0;
            int num16 = 0;
            int num17 = n.spriteDirection;
            if (n.type == 663)
            {
                num15 = 1;
            }
            if (n.type == 637)
            {
                num15 = 6;
                switch (num)
                {
                case 19:
                case 22:
                case 23:
                case 24:
                case 25:
                case 26:
                case 27:
                    num15 -= 2;
                    break;
                case 11:
                case 12:
                case 13:
                case 14:
                case 15:
                    num15 += 2;
                    break;
                }
            }
            if (n.type == 638)
            {
                num15 = 12;
            }
            if (n.type == 656)
            {
                num15 = 6;
                switch (num)
                {
                case 1:
                case 2:
                case 3:
                    num15 -= 2;
                    break;
                case 18:
                case 19:
                case 20:
                case 21:
                case 22:
                case 23:
                case 24:
                case 25:
                    num15 -= 4;
                    break;
                case 8:
                    num15 -= 2;
                    break;
                }
            }
            if (NPCID.Sets.IsTownSlime[n.type])
            {
                num17 *= -1;
                switch (n.type)
                {
                default:
                    num15 = 1;
                    break;
                case 670:
                    num15 = -1;
                    break;
                case 681:
                    num15 = -2;
                    break;
                case 682:
                    num15 = -1;
                    num16 = 2;
                    break;
                case 683:
                    num15 = -1;
                    num16 = -2;
                    break;
                case 684:
                    num15 = -4;
                    break;
                case 679:
                    break;
                }
            }
            if (n.IsShimmerVariant)
            {
                switch (n.type)
                {
                case 38:
                    num15 += 2;
                    num16 = -2;
                    break;
                case 178:
                case 228:
                    num15 = -4;
                    num16 = -4;
                    break;
                case 107:
                    num15 = 2;
                    num16 = -6;
                    break;
                case 54:
                    num16 = -6;
                    break;
                case 160:
                    num16 = -2;
                    break;
                case 108:
                case 124:
                case 208:
                case 209:
                case 227:
                    num16 = -4;
                    break;
                }
            }
            Vector2 vector = n.Top + new Vector2((float)(-2 * num17), n.gfxOffY);
            vector.X += num15 * num17;
            vector.Y += array[num];
            vector.Y += num16;
            vector.Y += NPCID.Sets.HatOffsetY[n.type];
            int num18 = 0;
            if (n.ai[0] == 5f)
            {
                num18 = -4;
                if (n.type == 38)
                {
                    num18 = -8;
                }
                if (n.type == 124)
                {
                    num18 = -2;
                }
                if (n.type == 550)
                {
                    num18 = -4;
                }
                if (n.type == 588)
                {
                    num18 = -4;
                }
                if (n.type == 108 || n.type == 178)
                {
                    num18 = -6;
                }
                if (n.type == 637)
                {
                    num18 = -12;
                }
                if (n.type == 663)
                {
                    num18 = -8;
                }
            }
            vector.Y += num18;
            if (n.type == 229 && n.ai[0] == 12f)
            {
                vector.X -= num17 * 4;
            }
            if (n.type == 550 && n.ai[0] == 5f)
            {
                vector.X += num17 * 7;
            }
            Vector2 origin = rectangle.Size() - new Vector2((float)(rectangle.Width / 2), 12f);
            int num19 = 0;
            switch (n.type)
            {
            case 550:
                num19 = -4;
                break;
            case 588:
                num19 = 0;
                break;
            case 227:
                num19 = -4;
                break;
            case 228:
                num19 = -2;
                break;
            case 17:
            case 18:
            case 19:
            case 20:
            case 22:
            case 124:
            case 229:
            case 353:
            case 633:
            case 637:
            case 638:
            case 656:
            case 670:
            case 678:
            case 679:
            case 680:
            case 681:
            case 682:
            case 683:
            case 684:
                num19 = -1;
                break;
            case 37:
            case 38:
            case 54:
            case 107:
            case 108:
            case 160:
            case 207:
            case 209:
                num19 = -3;
                break;
            case 178:
            case 208:
            case 369:
                num19 = 1;
                break;
            }
            vector.X += num19 * num17;
            vector.X += 4 * num17;
            SpriteEffects spriteEffects = npcSpriteEffect;
            if (NPCID.Sets.IsTownSlime[n.type])
            {
                spriteEffects = (SpriteEffects)(spriteEffects ^ 1);
            }
            float num20 = 1f;
            if (n.shimmerTransparency > 0f)
            {
                num20 *= 1f - n.shimmerTransparency;
            }
            spriteBatch.Draw(value, new Vector2(vector.X - screenPosition.X, vector.Y - screenPosition.Y), (Rectangle?)rectangle, npcColor * n.Opacity * num20, 0f, origin, n.scale, spriteEffects, 0f);
        }
        if (!beforeDraw && n.type == 681)
        {
            spriteBatch.Draw(TextureAssets.Extra[250].Value, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), (Rectangle?)n.frame, n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
        }
        if (NPCID.Sets.AttackType[n.type] == 1 && n.ai[0] == 12f && !beforeDraw)
        {
            if (n.type == 228 || n.type == 229 || n.type == 209)
            {
                return;
            }
            float num21 = n.ai[2];
            Vector2 vector4 = OffsetsNPCOffhand[2];
            if (n.spriteDirection == 1)
            {
                vector4.X *= -1f;
            }
            Vector2 vector5 = n.Bottom - vector4;
            if (n.type == 22 && n.ai[2] > -0.1f)
            {
                vector5.Y += 4f;
            }
            if (n.type == 368 && hardMode && n.ai[2] > -0.1f)
            {
                vector5.Y += 4f;
            }
            if (n.type == 368 && !hardMode && n.ai[2] < -0.1f)
            {
                vector5.Y -= 8f;
            }
            float rotation = num21 * ((float)Math.PI / 2f) * (float)n.spriteDirection;
            float num2 = 1f;
            int itemtype = 0;
            int num3 = 4;
            if (n.type == 19)
            {
                itemtype = (hardMode ? 98 : 95);
                if (hardMode)
                {
                    vector5.X -= 10 * n.direction;
                    vector5.Y += 4f;
                }
            }
            else if (n.type == 22)
            {
                itemtype = 39;
                num3 = 18;
            }
            else if (n.type == 178)
            {
                itemtype = 434;
            }
            else if (n.type == 227)
            {
                itemtype = 3350;
                num3 = 16;
                num2 = 0.85f;
            }
            else if (n.type == 368)
            {
                itemtype = (hardMode ? 2223 : 2269);
                if (hardMode)
                {
                    num3 = 18;
                }
                else
                {
                    if (n.ai[2] < -0.1f)
                    {
                        num3 = 28;
                    }
                    num2 = 0.75f;
                }
            }
            Vector2 val = DrawPlayerItemPos(1f, itemtype);
            GetItemDrawFrame(itemtype, out var itemTexture, out var value2);
            int num4 = (int)val.X - num3;
            NPCLoader.DrawTownAttackGun(n, ref itemTexture, ref value2, ref num2, ref num4);
            Vector2 origin2 = default(Vector2);
            ((Vector2)(ref origin2))._002Ector((float)(-num4), (float)(value2.Height / 2));
            if (n.spriteDirection == -1)
            {
                ((Vector2)(ref origin2))._002Ector((float)(value2.Width + num4), (float)(value2.Height / 2));
            }
            spriteBatch.Draw(itemTexture, new Vector2((float)(int)(vector5.X - screenPosition.X), (float)(int)(vector5.Y - screenPosition.Y)), (Rectangle?)value2, npcColor, rotation, origin2, n.scale * num2, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
            if (n.type == 22 && n.frame.Y / (TextureAssets.Npc[n.type].Height() / npcFrameCount[n.type]) >= 21)
            {
                Texture2D value3 = TextureAssets.Extra[52].Value;
                if (n.IsShimmerVariant)
                {
                    value3 = TextureAssets.Extra[264].Value;
                }
                Rectangle value4 = value3.Frame(1, 5, 0, n.frame.Y / (TextureAssets.Npc[n.type].Height() / npcFrameCount[n.type]) - 21);
                spriteBatch.Draw(value3, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), (Rectangle?)value4, n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
            }
            else if (n.type == 368 && n.frame.Y / (TextureAssets.Npc[n.type].Height() / npcFrameCount[n.type]) >= 21)
            {
                Texture2D value5 = TextureAssets.Extra[53].Value;
                if (n.IsShimmerVariant)
                {
                    value5 = TextureAssets.Extra[265].Value;
                }
                Rectangle value6 = value5.Frame(1, 5, 0, n.frame.Y / (TextureAssets.Npc[n.type].Height() / npcFrameCount[n.type]) - 21);
                spriteBatch.Draw(value5, new Vector2(n.position.X - screenPosition.X + (float)(n.width / 2) - (float)TextureAssets.Npc[n.type].Width() * n.scale / 2f + halfSize.X * n.scale, n.position.Y - screenPosition.Y + (float)n.height - (float)TextureAssets.Npc[n.type].Height() * n.scale / (float)npcFrameCount[n.type] + 4f + halfSize.Y * n.scale + addHeight + addY + n.gfxOffY), (Rectangle?)value6, n.GetAlpha(npcColor), n.rotation, halfSize, n.scale, npcSpriteEffect, 0f);
            }
        }
        if (NPCID.Sets.AttackType[n.type] == 2 && (n.ai[0] == 14f || (n.ai[0] == 24f && n.frameCounter < 240.0)) && !beforeDraw)
        {
            Texture2D value7 = TextureAssets.Extra[51].Value;
            Vector2 vector6 = n.Bottom + new Vector2(0f, n.gfxOffY + 4f);
            Rectangle rectangle2 = value7.Frame(1, 4, 0, (int)n.frameCounter % 48 / 12);
            Vector2 origin3 = rectangle2.Size() * new Vector2(0.5f, 1f);
            spriteBatch.Draw(value7, new Vector2((float)(int)(vector6.X - screenPosition.X), (float)(int)(vector6.Y - screenPosition.Y)), (Rectangle?)rectangle2, n.GetMagicAuraColor(), 0f, origin3, n.scale, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
        }
        if (NPCID.Sets.AttackType[n.type] == 3 && n.ai[0] == 15f)
        {
            int num5 = 32;
            float num6 = 0f;
            Vector2 zero = Vector2.Zero;
            short num7 = 4;
            if (n.type == 207)
            {
                num7 = 3349;
                num6 = 0.15f;
                if (beforeDraw)
                {
                    return;
                }
                if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                {
                    zero.Y = 12f;
                }
            }
            else if (n.type == 353)
            {
                num7 = 3352;
                num6 = 0.15f;
                if (!beforeDraw)
                {
                    return;
                }
                if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                {
                    zero.Y = 12f;
                }
            }
            else if (n.type == 441)
            {
                num7 = 3351;
                num5 = 28;
                num6 = 0.1f;
                if (!beforeDraw)
                {
                    return;
                }
                if (n.ai[1] > (float)NPCID.Sets.AttackTime[n.type] * 0.66f)
                {
                    zero.Y = 12f;
                }
            }
            GetItemDrawFrame(num7, out var itemTexture2, out var rectangle3);
            NPCLoader.DrawTownAttackSwing(n, ref itemTexture2, ref rectangle3, ref num5, ref num6, ref zero);
            Tuple<Vector2, float> swingStats = n.GetSwingStats(NPCID.Sets.AttackTime[n.type] * 2, (int)n.ai[1], n.spriteDirection, num5, num5);
            Vector2 vector7 = swingStats.Item1 + (swingStats.Item1 - n.Center) * num6 + zero;
            Vector2 origin4 = rectangle3.Size() * new Vector2((float)((n.spriteDirection != 1) ? 1 : 0), 1f);
            spriteBatch.Draw(itemTexture2, new Vector2((float)(int)(vector7.X - screenPosition.X), (float)(int)(vector7.Y - screenPosition.Y)), (Rectangle?)rectangle3, n.GetAlpha(npcColor), swingStats.Item2, origin4, n.scale, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
        }
        if (n.type == 550 && n.ai[0] == 18f)
        {
            if (beforeDraw)
            {
                return;
            }
            instance.LoadItem(353);
            Texture2D value8 = TextureAssets.Item[353].Value;
            int num8 = 32;
            float num9 = 0.15f;
            Vector2 zero2 = Vector2.Zero;
            Rectangle rectangle4 = value8.Frame(1, 3, 0, 1);
            int num10 = (int)n.ai[2];
            if (num10 >= 0 && num10 < 255)
            {
                Player player = Main.player[num10];
                bool flag = player.HeldItem.type == 353 && player.direction == Math.Sign(n.Center.X - player.Center.X);
                float num22 = player.Hitbox.Distance(n.Center);
                float num12 = n.localAI[3];
                if (num22 < 46f && flag)
                {
                    n.localAI[3] = 1f;
                    if (n.localAI[3] != num12)
                    {
                        Vector2 vector8 = n.Center + new Vector2((float)(n.spriteDirection * 30), -6f);
                        Vector2 vector9 = default(Vector2);
                        ((Vector2)(ref vector9))._002Ector(10f, 10f);
                        for (int i = 0; i < 30; i++)
{
                            Dust obj = Dust.NewDustDirect(vector8 - vector9 / 2f, (int)vector9.X, (int)vector9.Y, 4, 0f, 0f, 50, new Color(245, 200, 30, 155), 0.7f);
                            obj.noGravity = true;
                            obj.velocity *= 1f;
                            Dust obj2 = Dust.NewDustDirect(vector8 - vector9 / 2f, (int)vector9.X, (int)vector9.Y, 4, 0f, 0f, 50, new Color(245, 200, 30, 155), 0.6f);
                            obj2.velocity *= 2f;
                        }
                    }
                }
                else if (n.localAI[3] == 1f)
                {
                    n.localAI[3] = 2f;
                }
            }
            Tuple<Vector2, float> swingStats2 = n.GetSwingStats(40, 12, n.spriteDirection, num8, num8);
            Vector2 vector10 = swingStats2.Item1 + (swingStats2.Item1 - n.Center) * num9 + zero2;
            Vector2 origin5 = rectangle4.Size() * new Vector2((float)((n.spriteDirection != 1) ? 1 : 0), 1f);
            spriteBatch.Draw(value8, new Vector2((float)(int)(vector10.X - screenPosition.X), (float)(int)(vector10.Y - screenPosition.Y)), (Rectangle?)rectangle4, n.GetAlpha(npcColor), swingStats2.Item2, origin5, n.scale, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
        }
        if (beforeDraw || n.ai[0] != 23f)
        {
            return;
        }
        int num13 = (int)n.ai[2];
        if (num13 <= 0 || num13 > ItemID.Count)
        {
            return;
        }
        GetItemDrawFrame(num13, out var itemTexture3, out var rectangle5);
        int num14 = 0;
        num14 = (((int)n.frameCounter < 6) ? 1 : 2);
        if (n.ai[1] < 6f)
        {
            num14 = 1;
        }
        if (num14 == 0)
        {
            return;
        }
        Vector2 vector2 = Vector2.Zero;
        if (num14 == 1)
        {
            ((Vector2)(ref vector2))._002Ector(10f, 6f);
        }
        if (num14 == 2)
        {
            ((Vector2)(ref vector2))._002Ector(16f, 0f);
        }
        if (!((Enum)npcSpriteEffect).HasFlag((Enum)(object)(SpriteEffects)1))
        {
            vector2.X *= -1f;
        }
        if (n.type == 369)
        {
            vector2.X *= 0.5f;
            vector2.Y += 4f;
        }
        if (n.type == 453)
        {
            vector2.Y += 8f;
        }
        if (n.type == 550)
        {
            if (num13 == 353)
            {
                rectangle5 = itemTexture3.Frame(1, 3, 0, 1);
            }
            vector2.Y += 6f;
        }
        Vector2 vector3 = n.Center + vector2;
        Vector2 origin6 = rectangle5.Size() * new Vector2((float)((n.spriteDirection != 1) ? 1 : 0), 1f);
        Vector2 position = default(Vector2);
        ((Vector2)(ref position))._002Ector((float)(int)(vector3.X - screenPosition.X), (float)(int)(vector3.Y - screenPosition.Y));
        Color alpha = n.GetAlpha(npcColor);
        spriteBatch.Draw(itemTexture3, position, (Rectangle?)rectangle5, alpha, 0f, origin6, n.scale, (SpriteEffects)(npcSpriteEffect ^ 1), 0f);
    }
References Terraria.ID.NPCID.Sets.AttackTime, Terraria.ID.NPCID.Sets.AttackType, Terraria.ID.ItemID.Count, Terraria.Main.DrawPlayerItemPos(), Terraria.ModLoader.NPCLoader.DrawTownAttackGun(), Terraria.ModLoader.NPCLoader.DrawTownAttackSwing(), Terraria.GameContent.TextureAssets.Extra, Terraria.Main.GetItemDrawFrame(), Terraria.Main.hardMode, Terraria.ID.NPCID.Sets.HatOffsetY, Terraria.Main.instance, Terraria.ID.NPCID.Sets.IsTownSlime, Terraria.GameContent.TextureAssets.Item, Terraria.Dust.NewDustDirect(), Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npcFrameCount, Terraria.ID.NPCID.Sets.NPCFramingGroup, Terraria.Main.OffsetsNPCOffhand, Terraria.Main.player, Terraria.Main.screenPosition, Terraria.Main.spriteBatch, and Terraria.ID.NPCID.Sets.TownNPCsFramingGroups.
Referenced by Terraria.Main.DrawNPCDirect_Inner().