TModLoader: Terraria.Main.startPumpkinMoon
startPumpkinMoon()
static void Terraria.Main.startPumpkinMoon () inline static
Definition at line 10516 of file Main.cs.
    {
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        pumpkinMoon = true;
        snowMoon = false;
        bloodMoon = false;
        invasionProgress = -1;
        invasionProgressDisplayLeft = 0;
        invasionProgressAlpha = 0f;
        invasionProgressIcon = 0;
        if (netMode != 1)
        {
            NPC.totalInvasionPoints = 0f;
            NPC.waveKills = 0f;
            NPC.waveNumber = 1;
            NetworkText invasionWaveText = Lang.GetInvasionWaveText(1, 305);
            if (netMode == 0)
            {
                NewText(invasionWaveText.ToString(), 175, 75);
            }
            else if (netMode == 2)
            {
                ChatHelper.BroadcastChatMessage(invasionWaveText, new Color(175, 75, 255));
            }
        }
    }
References Terraria.Main.bloodMoon, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Graphics.Light.Color, Terraria.Lang.GetInvasionWaveText(), Terraria.Main.invasionProgress, Terraria.Main.invasionProgressAlpha, Terraria.Main.invasionProgressDisplayLeft, Terraria.Main.invasionProgressIcon, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Main.pumpkinMoon, and Terraria.Main.snowMoon.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.ItemCheck_UseEventItems().