TModLoader: Terraria.Main.DoDraw_WallsTilesNPCs
DoDraw_WallsTilesNPCs()
void Terraria.Main.DoDraw_WallsTilesNPCs () inline private
    {
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        try
        {
            CacheNPCDraws();
            CacheProjDraws();
            DrawCachedNPCs(DrawCacheNPCsMoonMoon, behindTiles: true);
            DoDraw_WallsAndBlacks();
            DrawWoF();
            DrawBackGore();
            MoonlordDeathDrama.DrawPieces(spriteBatch);
            MoonlordDeathDrama.DrawExplosions(spriteBatch);
            DrawCachedNPCs(DrawCacheNPCsBehindNonSolidTiles, behindTiles: true);
            DoDraw_Tiles_NonSolid();
            tileBatch.Begin(Rasterizer, Transform);
            DoDraw_Waterfalls();
            tileBatch.End();
        }
        catch (Exception e)
        {
            TimeLogger.DrawException(e);
        }
        spriteBatch.End();
        try
        {
            bool detectCreature = player[myPlayer].detectCreature;
            if (!detectCreature)
            {
                DoDraw_DrawNPCsBehindTiles();
            }
            DoDraw_Tiles_Solid();
            if (detectCreature)
            {
                DoDraw_DrawNPCsBehindTiles();
            }
            DrawPlayers_BehindNPCs();
            DoDraw_DrawNPCsOverTiles();
            TimeLogger.DetailedDrawReset();
        }
        catch (Exception e2)
        {
            TimeLogger.DrawException(e2);
        }
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
    }
References Terraria.Main.CacheNPCDraws(), Terraria.Main.CacheProjDraws(), Terraria.Main.DefaultSamplerState, Terraria.TimeLogger.DetailedDrawReset(), Terraria.Main.DoDraw_DrawNPCsBehindTiles(), Terraria.Main.DoDraw_DrawNPCsOverTiles(), Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DoDraw_WallsAndBlacks(), Terraria.Main.DoDraw_Waterfalls(), Terraria.Main.DrawBackGore(), Terraria.Main.DrawCachedNPCs(), Terraria.Main.DrawCacheNPCsBehindNonSolidTiles, Terraria.Main.DrawCacheNPCsMoonMoon, Terraria.TimeLogger.DrawException(), Terraria.GameContent.Events.MoonlordDeathDrama.DrawExplosions(), Terraria.GameContent.Events.MoonlordDeathDrama.DrawPieces(), Terraria.Main.DrawPlayers_BehindNPCs(), Terraria.Main.DrawWoF(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.Rasterizer, Terraria.Main.spriteBatch, Terraria.Main.tileBatch, and Terraria.Main.Transform.
Referenced by Terraria.Main.DoDraw().