TModLoader: Terraria.Main.DrawItem_GetBasics
DrawItem_GetBasics()
void Terraria.Main.DrawItem_GetBasics (Item item, int slot, out Texture2D texture, out Rectangle frame, out Rectangle glowmaskFrame) inline private
Definition at line 49501 of file Main.cs.
    {
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0181: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_011f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        LoadItem(item.type);
        if (ItemID.Sets.AnimatesAsSoul[item.type] || ItemID.Sets.NebulaPickup[item.type])
        {
            DrawItem_AnimateSlot(slot, itemAnimations[item.type].TicksPerFrame, itemAnimations[item.type].FrameCount);
            texture = TextureAssets.Item[item.type].Value;
        }
        else if (ItemID.Sets.IsFood[item.type])
        {
            texture = TextureAssets.Item[item.type].Value;
        }
        else
        {
            switch (item.type)
            {
            case 5358:
            case 5359:
            case 5360:
            case 5361:
                LoadItem(5437);
                texture = TextureAssets.Item[5437].Value;
                break;
            case 71:
            case 72:
            case 73:
            case 74:
            {
                int num = item.type - 71;
                texture = TextureAssets.Coin[num].Value;
                DrawItem_AnimateSlot(slot, 6, 8);
                frame = (glowmaskFrame = _coinOnWorldAnimation.GetFrame(texture, itemFrameCounter[slot]));
                return;
            }
            case 3858:
                texture = TextureAssets.Item[item.type].Value;
                DrawItem_AnimateSlot(slot, 5, 3);
                frame = texture.Frame();
                glowmaskFrame = TextureAssets.GlowMask[233].Value.Frame(1, 3, 0, itemFrameCounter[slot] / 5);
                glowmaskFrame.Height -= 2;
                return;
            case 75:
                texture = TextureAssets.Item[item.type].Value;
                DrawItem_AnimateSlot(slot, itemAnimations[item.type].TicksPerFrame, itemAnimations[item.type].FrameCount * 2 - 1);
                break;
            default:
                texture = TextureAssets.Item[item.type].Value;
                break;
            }
        }
        if (itemAnimations[item.type] != null)
        {
            frame = (glowmaskFrame = itemAnimations[item.type].GetFrame(texture, itemFrameCounter[slot]));
        }
        else
        {
            frame = (glowmaskFrame = texture.Frame());
        }
    }
References Terraria.Main._coinOnWorldAnimation, Terraria.ID.ItemID.Sets.AnimatesAsSoul, Terraria.GameContent.TextureAssets.Coin, Terraria.Main.DrawItem_AnimateSlot(), Terraria.DataStructures.DrawAnimation.FrameCount, Terraria.DataStructures.DrawAnimation.GetFrame(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.ID.ItemID.Sets.IsFood, Terraria.GameContent.TextureAssets.Item, Terraria.Main.item, Terraria.Main.itemAnimations, Terraria.Main.itemFrameCounter, Terraria.Main.LoadItem(), Terraria.ID.ItemID.Sets.NebulaPickup, Terraria.DataStructures.DrawAnimation.TicksPerFrame, and Terraria.Item.type.
Referenced by Terraria.Main.DrawItem().