TModLoader: Terraria.Main.DrawWallOfStars
DrawWallOfStars()
static void Terraria.Main.DrawWallOfStars () inline static
    {
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        bool flag = true;
        if (flag)
        {
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        }
        int num = Projectile.NewProjectile(Projectile.GetNoneSource(), Vector2.Zero, Vector2.UnitX, 12, 0, 0f, myPlayer);
        Projectile projectile = Main.projectile[num];
        Vector2 vector = default(Vector2);
        for (int i = 0; i < 5; i++)
        {
            float num2 = 10f;
            ((Vector2)(ref vector))._002Ector((float)screenWidth / num2 * (GlobalTimeWrappedHourly % num2), -100f);
            vector.X += 14 * i;
            vector.Y += i % 2 * 14;
            while (vector.Y < (float)(screenHeight + 100))
            {
                vector.Y += 26f;
                projectile.position = Vector2.One * 10f;
                projectile.velocity = Vector2.UnitX * 10f;
                projectile.rotation = GlobalTimeWrappedHourly * ((float)Math.PI * 2f);
                projectile.Update(num);
                projectile.position = vector + screenPosition;
                instance.DrawProj(num);
            }
        }
        projectile.position = Vector2.One * 10f;
        projectile.Kill();
        if (flag)
        {
            spriteBatch.End();
        }
    }
References Terraria.Main.DefaultSamplerState, Terraria.Main.DrawProj(), Terraria.Projectile.GetNoneSource(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.instance, Terraria.Projectile.Kill(), Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.projectile, Terraria.Main.Rasterizer, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.Main.Transform, and Terraria.Projectile.Update().