TModLoader: Terraria.Main.DrawInterface_18_DiagnoseVideo
DrawInterface_18_DiagnoseVideo()
static void Terraria.Main.DrawInterface_18_DiagnoseVideo () inline static private
    {
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_025e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0264: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0445: Unknown result type (might be due to invalid IL or missing references)
        //IL_044a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0456: Unknown result type (might be due to invalid IL or missing references)
        //IL_045c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0306: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0317: Unknown result type (might be due to invalid IL or missing references)
        //IL_031d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0595: Unknown result type (might be due to invalid IL or missing references)
        //IL_059a: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0602: Unknown result type (might be due to invalid IL or missing references)
        //IL_060e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0614: Unknown result type (might be due to invalid IL or missing references)
        //IL_0674: Unknown result type (might be due to invalid IL or missing references)
        //IL_0679: Unknown result type (might be due to invalid IL or missing references)
        //IL_0685: Unknown result type (might be due to invalid IL or missing references)
        //IL_068b: Unknown result type (might be due to invalid IL or missing references)
        //IL_06eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0702: Unknown result type (might be due to invalid IL or missing references)
        if (!drawDiag)
        {
            return;
        }
        if (PlayerInput.UsingGamepad)
        {
            for (int i = 0; i < 2; i++)
            {
                string text = "";
                int num = 20;
                int num12 = 160;
                num12 += i * 16;
                if (i == 0)
                {
                    text = "Gamepad Left Thumbstick  : " + string.Format("{0,-10} ,   {1,-10}", PlayerInput.GamepadThumbstickLeft.X.ToString("P2"), PlayerInput.GamepadThumbstickLeft.Y.ToString("P2"));
                }
                if (i == 1)
                {
                    text = "Gamepad Right Thumbstick: " + string.Format("{0,-10} ,   {1,-10}", PlayerInput.GamepadThumbstickRight.X.ToString("P2"), PlayerInput.GamepadThumbstickRight.Y.ToString("P2"));
                }
                spriteBatch.DrawString(FontAssets.MouseText.Value, text, new Vector2((float)num, (float)num12), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
        }
        for (int j = 0; j < 7; j++)
        {
            string text2 = "";
            int num17 = 20;
            int num18 = 220;
            num18 += j * 16;
            if (j == 0)
            {
                text2 = "Solid Tiles:";
            }
            if (j == 1)
            {
                text2 = "Misc. Tiles:";
            }
            if (j == 2)
            {
                text2 = "Walls Tiles:";
            }
            if (j == 3)
            {
                text2 = "Background Tiles:";
            }
            if (j == 4)
            {
                text2 = "Water Tiles:";
            }
            if (j == 5)
            {
                text2 = "Black Tiles:";
            }
            if (j == 6)
            {
                text2 = "Total Render:";
            }
            spriteBatch.DrawString(FontAssets.MouseText.Value, text2, new Vector2((float)num17, (float)num18), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        for (int k = 0; k < 7; k++)
        {
            string text3 = "";
            int num19 = 180;
            int num20 = 220;
            num20 += k * 16;
            float num21 = ((k != 6) ? TimeLogger.GetDrawTime(k) : TimeLogger.GetDrawTotal());
            text3 = $"{num21:F2}ms";
            spriteBatch.DrawString(FontAssets.MouseText.Value, text3, new Vector2((float)num19, (float)num20), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        for (int l = 0; l < 6; l++)
        {
            string text4 = "";
            int num22 = 20;
            int num23 = 346;
            num23 += l * 16;
            if (l == 0)
            {
                text4 = "Lighting Init:";
            }
            if (l == 1)
            {
                text4 = "Lighting Phase #1:";
            }
            if (l == 2)
            {
                text4 = "Lighting Phase #2:";
            }
            if (l == 3)
            {
                text4 = "Lighting Phase #3";
            }
            if (l == 4)
            {
                text4 = "Lighting Phase #4";
            }
            if (l == 5)
            {
                text4 = "Total Lighting:";
            }
            spriteBatch.DrawString(FontAssets.MouseText.Value, text4, new Vector2((float)num22, (float)num23), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        for (int m = 0; m < 6; m++)
        {
            string text5 = "";
            int num2 = 180;
            int num3 = 346;
            num3 += m * 16;
            float num4 = ((m != 5) ? TimeLogger.GetLightingTime(m) : TimeLogger.GetLightingTotal());
            text5 = $"{num4:F2}ms";
            spriteBatch.DrawString(FontAssets.MouseText.Value, text5, new Vector2((float)num2, (float)num3), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        int num5 = 5;
        for (int n = 0; n < num5; n++)
        {
            string text6 = "";
            int num6 = 20;
            int num7 = 456;
            num7 += n * 16;
            text6 = "Render #" + n + ":";
            spriteBatch.DrawString(FontAssets.MouseText.Value, text6, new Vector2((float)num6, (float)num7), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        for (int num8 = 0; num8 < num5; num8++)
        {
            string text7 = "";
            int num9 = 180;
            int num10 = 456;
            num10 += num8 * 16;
            text7 = $"{TimeLogger.GetRenderTime(num8):F2}ms";
            spriteBatch.DrawString(FontAssets.MouseText.Value, text7, new Vector2((float)num9, (float)num10), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        for (int num11 = 0; num11 < num5; num11++)
        {
            string text8 = "";
            int num13 = 230;
            int num14 = 456;
            num14 += num11 * 16;
            num13 += 10;
            text8 = $"{TimeLogger.GetRenderMax(num11):F2}ms";
            spriteBatch.DrawString(FontAssets.MouseText.Value, text8, new Vector2((float)num13, (float)num14), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        string text9 = "";
        int num15 = 20;
        int num16 = 456 + 16 * num5 + 16;
        text9 = "Update:";
        spriteBatch.DrawString(FontAssets.MouseText.Value, text9, new Vector2((float)num15, (float)num16), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        text9 = "";
        num15 = 180;
        text9 = $"{upTimer:F2}ms";
        spriteBatch.DrawString(FontAssets.MouseText.Value, text9, new Vector2((float)num15, (float)num16), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        text9 = "";
        num15 = 240;
        text9 = $"{upTimerMax:F2}ms";
        spriteBatch.DrawString(FontAssets.MouseText.Value, text9, new Vector2((float)num15, (float)num16), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
    }
References Terraria.Graphics.Light.Color, Terraria.Main.drawDiag, Terraria.GameInput.PlayerInput.GamepadThumbstickLeft, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.TimeLogger.GetDrawTime(), Terraria.TimeLogger.GetDrawTotal(), Terraria.TimeLogger.GetLightingTime(), Terraria.TimeLogger.GetLightingTotal(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.spriteBatch, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.SetupDrawInterfaceLayers().