TModLoader: Terraria.Main.DrawLoadoutButtons
DrawLoadoutButtons()
static void Terraria.Main.DrawLoadoutButtons (int inventoryTop, bool demonHeartSlotAvailable, bool masterModeSlotAvailable) inline static private
Definition at line 54262 of file Main.cs.
    {
        //IL_0076: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_020d: Unknown result type (might be due to invalid IL or missing references)
        int num = 10;
        Player player = Main.player[myPlayer];
        if (!demonHeartSlotAvailable)
        {
            num--;
        }
        if (!masterModeSlotAvailable)
        {
            num--;
        }
        int x = screenWidth - 58 + 14;
        int num2 = (int)((float)(inventoryTop - 2) + 0f * inventoryScale);
        int num3 = (int)((float)(inventoryTop - 2) + (float)(num * 56) * inventoryScale);
        Texture2D value = TextureAssets.Extra[259].Value;
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(x, num2 + 2, 4, num3 - num2);
        ItemSlot.GetLoadoutColor(player.CurrentLoadoutIndex);
        int num4 = player.Loadouts.Length;
        int num5 = 32;
        int num6 = 4;
        int num7 = -1;
        _ = FontAssets.ItemStack.Value;
        Rectangle rectangle2 = default(Rectangle);
        for (int i = 0; i < num4; i++)
        {
            ((Rectangle)(ref rectangle2))._002Ector(rectangle.X + rectangle.Width, rectangle.Y + (num5 + num6) * i, 32, num5);
            Color loadoutColor = ItemSlot.GetLoadoutColor(i);
            _ = player.Loadouts[i];
            int frameX = ((i == player.CurrentLoadoutIndex) ? 1 : 0);
            bool flag = false;
            if (((Rectangle)(ref rectangle2)).Contains(MouseScreen.ToPoint()))
            {
                flag = true;
                loadoutColor = Color.Lerp(loadoutColor, Color.White, 0.8f);
                player.mouseInterface = true;
                if (!mouseText)
                {
                    instance.MouseText(Language.GetTextValue("UI.Loadout" + (i + 1)), 0, 0);
                    mouseText = true;
                }
                if (mouseLeft && mouseLeftRelease)
                {
                    player.TrySwitchingLoadout(i);
                }
            }
            Rectangle rectangle3 = value.Frame(3, 3, frameX, i);
            spriteBatch.Draw(value, ((Rectangle)(ref rectangle2)).Center.ToVector2(), (Rectangle?)rectangle3, Color.White, 0f, rectangle3.Size() / 2f, 1f, (SpriteEffects)0, 0f);
            if (flag)
            {
                rectangle3 = value.Frame(3, 3, 2, i);
                spriteBatch.Draw(value, ((Rectangle)(ref rectangle2)).Center.ToVector2(), (Rectangle?)rectangle3, OurFavoriteColor, 0f, rectangle3.Size() / 2f, 1f, (SpriteEffects)0, 0f);
            }
            UILinkPointNavigator.SetPosition(312 + i, ((Rectangle)(ref rectangle2)).Center.ToVector2());
        }
        if (_lastHoveredLoadoutIndex != num7)
        {
            _lastHoveredLoadoutIndex = num7;
            SoundEngine.PlaySound(12);
        }
    }
References Terraria.Main._lastHoveredLoadoutIndex, Terraria.Graphics.Light.Color, Terraria.Player.CurrentLoadoutIndex, Terraria.GameContent.TextureAssets.Extra, Terraria.UI.ItemSlot.GetLoadoutColor(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.instance, Terraria.Main.inventoryScale, Terraria.GameContent.FontAssets.ItemStack, Terraria.Player.Loadouts, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.Main.mouseText, Terraria.Main.MouseText(), Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.screenWidth, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, and Terraria.Player.TrySwitchingLoadout().
Referenced by Terraria.Main.DrawInventory().