TModLoader: Terraria.Main.DrawBuilderAccToggles_Inner
DrawBuilderAccToggles_Inner()
void Terraria.Main.DrawBuilderAccToggles_Inner (Vector2 start) inline private
Definition at line 83802 of file Main.cs.
    {
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_021b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02db: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_027b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0287: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0441: Unknown result type (might be due to invalid IL or missing references)
        //IL_0446: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0452: Unknown result type (might be due to invalid IL or missing references)
        //IL_0461: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_033d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0347: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[myPlayer];
        int[] builderAccStatus = player.builderAccStatus;
        List<BuilderToggle> activeToggles = BuilderToggleLoader.ActiveBuilderTogglesList();
        bool shiftHotbarLock = activeToggles.Count / 12 != BuilderToggleLoader.BuilderTogglePage || activeToggles.Count % 12 >= 10;
        Vector2 startPosition = start - new Vector2(0f, (float)(shiftHotbarLock ? 42 : 21));
        string text = "";
        BuilderTogglePageHandler((int)startPosition.Y, activeToggles.Count, out var moveDownForButton, out var startIndex, out var endIndex);
        Rectangle rectangle = default(Rectangle);
        Color textColor = default(Color);
        for (int i = startIndex; i < endIndex; i++)
        {
            BuilderToggle builderToggle = activeToggles[i];
            Texture2D texture = ModContent.Request<Texture2D>(builderToggle.Texture).Value;
            ((Rectangle)(ref rectangle))._002Ector(0, 0, texture.Width, texture.Height);
            Color color = builderToggle.DisplayColorTexture();
            Vector2 position = startPosition + new Vector2(0f, (float)(moveDownForButton ? 24 : 0)) + new Vector2(0f, (float)(i % 12 * 24));
            text = builderToggle.DisplayValue();
            int numberOfStates = builderToggle.NumberOfStates;
            int toggleType = builderToggle.Type;
            Rectangle val = Utils.CenteredRectangle(position, new Vector2(14f));
            bool hover = ((Rectangle)(ref val)).Contains(MouseScreen.ToPoint()) && !PlayerInput.IgnoreMouseInterface;
            bool num = hover && mouseLeft && mouseLeftRelease;
            if (toggleType == BuilderToggle.BlockSwap.Type || toggleType == BuilderToggle.TorchBiome.Type)
            {
                rectangle = ((toggleType != BuilderToggle.BlockSwap.Type) ? texture.Frame(4, 1, (builderToggle.CurrentState == 0) ? 1 : 0) : texture.Frame(3, 1, (builderToggle.CurrentState != 0) ? 1 : 0));
                position += new Vector2(1f, 0f);
            }
            else
            {
                rectangle = (Rectangle)((builderToggle.Type < 10) ? new Rectangle(builderToggle.Type * 16, 16, 14, 14) : rectangle);
            }
            spriteBatch.Draw(texture, position, (Rectangle?)rectangle, color, 0f, rectangle.Size() / 2f, 1f, (SpriteEffects)0, 0f);
            if (hover)
            {
                player.mouseInterface = true;
                mouseText = true;
                if (toggleType != BuilderToggle.BlockSwap.Type && toggleType != BuilderToggle.TorchBiome.Type)
                {
                    Asset<Texture2D> iconHover = ModContent.Request<Texture2D>(builderToggle.HoverTexture);
                    spriteBatch.Draw(iconHover.Value, position, (Rectangle?)null, OurFavoriteColor, 0f, iconHover.Value.Size() / 2f, 1f, (SpriteEffects)0, 0f);
                }
                else if (toggleType == BuilderToggle.BlockSwap.Type)
                {
                    spriteBatch.Draw(texture, position, (Rectangle?)texture.Frame(3, 1, 2), OurFavoriteColor, 0f, rectangle.Size() / 2f, 0.9f, (SpriteEffects)0, 0f);
                }
                else if (toggleType == BuilderToggle.TorchBiome.Type)
                {
                    spriteBatch.Draw(texture, position, (Rectangle?)texture.Frame(4, 1, (builderToggle.CurrentState == 0) ? 3 : 2), OurFavoriteColor, 0f, rectangle.Size() / 2f, 0.9f, (SpriteEffects)0, 0f);
                }
            }
            if (num)
            {
                builderAccStatus[toggleType] = (builderAccStatus[toggleType] + 1) % numberOfStates;
                SoundStyle style = ((toggleType == BuilderToggle.BlockSwap.Type || toggleType == BuilderToggle.TorchBiome.Type) ? SoundID.Unlock : SoundID.MenuTick);
                SoundEngine.PlaySound(in style);
                mouseLeftRelease = false;
            }
            UILinkPointNavigator.SetPosition(6000 + i % 12, position + rectangle.Size() * 0.15f);
            if (mouseText && hover && HoverItem.type <= 0)
            {
                float colorByte = (float)(int)mouseTextColor / 255f;
                ((Color)(ref textColor))._002Ector(colorByte, colorByte, colorByte);
                ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, new Vector2((float)(mouseX + 14), (float)(mouseY + 14)), textColor, 0f, Vector2.Zero, Vector2.One);
                mouseText = false;
            }
        }
        UILinkPointNavigator.Shortcuts.BUILDERACCCOUNT = endIndex - startIndex;
    }
References Terraria.ModLoader.BuilderToggleLoader.ActiveBuilderTogglesList(), Terraria.ModLoader.BuilderToggle.BlockSwap, Terraria.Player.builderAccStatus, Terraria.Main.BuilderTogglePageHandler(), Terraria.Utils.CenteredRectangle(), Terraria.Graphics.Light.Color, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.Main.HoverItem, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.ID.SoundID.MenuTick, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.spriteBatch, Terraria.ModLoader.BuilderToggle.TorchBiome, Terraria.ModLoader.BuilderToggle.Type, Terraria.Item.type, and Terraria.ID.SoundID.Unlock.
Referenced by Terraria.Main.DrawBuilderAccToggles().