TModLoader: Terraria.Main.CancelClothesWindow
CancelClothesWindow()
static void Terraria.Main.CancelClothesWindow (bool quiet = false) inline static
    {
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        if (clothesWindow)
        {
            clothesWindow = false;
            if (!quiet)
            {
                SoundEngine.PlaySound(11);
            }
            player[myPlayer].shirtColor = oldClothesColor[0];
            player[myPlayer].underShirtColor = oldClothesColor[1];
            player[myPlayer].pantsColor = oldClothesColor[2];
            player[myPlayer].shoeColor = oldClothesColor[3];
            player[myPlayer].eyeColor = oldClothesColor[4];
            player[myPlayer].skinColor = oldClothesColor[5];
            dresserInterfaceDummy.skinVariant = oldClothesStyle;
            dresserInterfaceDummy.Male = player[myPlayer].Male;
            player[myPlayer].skinVariant = dresserInterfaceDummy.skinVariant;
        }
    }
References Terraria.Main.clothesWindow, Terraria.Main.dresserInterfaceDummy, Terraria.Player.eyeColor, Terraria.Player.Male, Terraria.Main.myPlayer, Terraria.Main.oldClothesColor, Terraria.Main.oldClothesStyle, Terraria.Player.pantsColor, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.shirtColor, Terraria.Player.shoeColor, Terraria.Player.skinColor, Terraria.Player.skinVariant, and Terraria.Player.underShirtColor.
Referenced by Terraria.Main.DrawClothesWindow(), Terraria.Main.OpenClothesWindow(), Terraria.Player.TileInteractionsUse(), Terraria.Player.ToggleCreativeMenu(), and Terraria.Player.ToggleInv().