TModLoader: Terraria.Main.DrawSuperSpecialProjectiles
DrawSuperSpecialProjectiles()
void Terraria.Main.DrawSuperSpecialProjectiles (List< int > projCache, bool startSpriteBatch = true) inline protected
    {
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0105: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01aa: Unknown result type (might be due to invalid IL or missing references)
        if (startSpriteBatch)
        {
            spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, DefaultSamplerState, DepthStencilState.None, Rasterizer, (Effect)null, Transform);
        }
        for (int i = 0; i < projCache.Count; i++)
        {
            try
            {
                int num = projCache[i];
                Projectile projectile = Main.projectile[num];
                int owner = projectile.owner;
                Player other = Main.player[owner];
                if (playerVisualClone[owner] == null)
                {
                    playerVisualClone[owner] = new Player();
                }
                Player player = playerVisualClone[owner];
                player.CopyVisuals(other);
                player.isFirstFractalAfterImage = true;
                player.firstFractalAfterImageOpacity = projectile.Opacity * 1f;
                player.ResetEffects();
                player.ResetVisibleAccessories();
                player.UpdateDyes();
                player.DisplayDollUpdate();
                player.UpdateSocialShadow();
                player.itemAnimationMax = 60;
                player.itemAnimation = (int)projectile.localAI[0];
                player.itemRotation = projectile.velocity.ToRotation();
                player.heldProj = num;
                player.Center = projectile.Center - projectile.velocity.SafeNormalize(Vector2.Zero) * 42f;
                player.direction = ((projectile.velocity.X > 0f) ? 1 : (-1));
                player.itemRotation = (float)Math.Atan2(projectile.velocity.Y * (float)player.direction, projectile.velocity.X * (float)player.direction);
                player.velocity.Y = 0.01f;
                player.wingFrame = 2;
                player.PlayerFrame();
                player.socialIgnoreLight = true;
                PlayerRenderer.DrawPlayer(Camera, player, player.position, 0f, player.fullRotationOrigin);
            }
            catch (Exception e)
            {
                TimeLogger.DrawException(e);
                Main.projectile[projCache[i]].active = false;
            }
        }
        if (startSpriteBatch)
        {
            spriteBatch.End();
        }
    }
References Terraria.Entity.active, Terraria.Player.CopyVisuals(), Terraria.Main.DefaultSamplerState, Terraria.Entity.direction, Terraria.Player.DisplayDollUpdate(), Terraria.TimeLogger.DrawException(), Terraria.Graphics.Renderers.IPlayerRenderer.DrawPlayer(), Terraria.Player.fullRotationOrigin, Terraria.Projectile.localAI, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Player.PlayerFrame(), Terraria.Main.PlayerRenderer, Terraria.Main.playerVisualClone, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Main.Rasterizer, Terraria.Player.ResetEffects(), Terraria.Player.ResetVisibleAccessories(), Terraria.Main.spriteBatch, Terraria.Main.Transform, Terraria.Player.UpdateDyes(), Terraria.Player.UpdateSocialShadow(), and Terraria.Entity.velocity.
Referenced by Terraria.Main.DoDraw(), and Terraria.Main.DrawCapture().