TModLoader: Terraria.Main.InfoDisplayPageHandler
InfoDisplayPageHandler()
static void Terraria.Main.InfoDisplayPageHandler (int startX, ref string mouseText, out int startingDisplay, out int endingDisplay) inline static
Definition at line 83558 of file Main.cs.
    {
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0177: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0191: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0334: Unknown result type (might be due to invalid IL or missing references)
        //IL_0340: Unknown result type (might be due to invalid IL or missing references)
        //IL_0346: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_036d: Unknown result type (might be due to invalid IL or missing references)
        //IL_036f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_037e: Unknown result type (might be due to invalid IL or missing references)
        //IL_038d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0399: Unknown result type (might be due to invalid IL or missing references)
        //IL_039f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0253: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        startingDisplay = 0;
        endingDisplay = InfoDisplayLoader.InfoDisplayCount;
        if (!playerInventory || InfoDisplayLoader.ActiveDisplays() <= 12)
        {
            return;
        }
        startingDisplay = 12 * InfoDisplayLoader.InfoDisplayPage;
        if (InfoDisplayLoader.ActiveDisplays() - startingDisplay <= 12)
        {
            endingDisplay = InfoDisplayLoader.ActiveDisplays();
        }
        else
        {
            endingDisplay = startingDisplay + 12;
        }
        if (startingDisplay >= 8)
        {
            startingDisplay++;
        }
        endingDisplay++;
        Texture2D buttonTexture = UICommon.InfoDisplayPageArrowTexture.Value;
        bool hovering = false;
        GetInfoAccIconPosition(11, startX, out var X, out var Y);
        Vector2 buttonPosition = default(Vector2);
        ((Vector2)(ref buttonPosition))._002Ector((float)X, (float)(Y + 20));
        if ((float)mouseX >= buttonPosition.X && (float)mouseY >= buttonPosition.Y && (float)mouseX <= buttonPosition.X + (float)buttonTexture.Width && (float)mouseY <= buttonPosition.Y + (float)buttonTexture.Height && !PlayerInput.IgnoreMouseInterface)
        {
            hovering = true;
            player[myPlayer].mouseInterface = true;
            if (mouseLeft && mouseLeftRelease)
            {
                SoundEngine.PlaySound(12);
                mouseLeftRelease = false;
                if (InfoDisplayLoader.ActivePages() != InfoDisplayLoader.InfoDisplayPage + 1)
                {
                    InfoDisplayLoader.InfoDisplayPage++;
                }
                else
                {
                    InfoDisplayLoader.InfoDisplayPage = 0;
                }
            }
            if (!Main.mouseText)
            {
                mouseText = ((InfoDisplayLoader.ActivePages() != InfoDisplayLoader.InfoDisplayPage + 1) ? Language.GetTextValue("tModLoader.NextInfoAccPage") : Language.GetTextValue("tModLoader.FirstInfoAccPage"));
                Main.mouseText = true;
            }
        }
        spriteBatch.Draw(buttonTexture, buttonPosition, (Rectangle?)new Rectangle(0, 0, buttonTexture.Width, buttonTexture.Height), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        if (hovering)
        {
            spriteBatch.Draw(TextureAssets.InfoIcon[13].Value, buttonPosition - Vector2.One * 2f, (Rectangle?)null, OurFavoriteColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        hovering = false;
        GetInfoAccIconPosition(0, startX, out X, out var _);
        ((Vector2)(ref buttonPosition))._002Ector((float)X, (float)(Y + 20));
        if ((float)mouseX >= buttonPosition.X && (float)mouseY >= buttonPosition.Y && (float)mouseX <= buttonPosition.X + (float)buttonTexture.Width && (float)mouseY <= buttonPosition.Y + (float)buttonTexture.Height && !PlayerInput.IgnoreMouseInterface)
        {
            hovering = true;
            player[myPlayer].mouseInterface = true;
            if (mouseLeft && mouseLeftRelease)
            {
                SoundEngine.PlaySound(12);
                mouseLeftRelease = false;
                if (InfoDisplayLoader.InfoDisplayPage != 0)
                {
                    InfoDisplayLoader.InfoDisplayPage--;
                }
                else
                {
                    InfoDisplayLoader.InfoDisplayPage = InfoDisplayLoader.ActivePages() - 1;
                }
            }
            if (!Main.mouseText)
            {
                mouseText = ((InfoDisplayLoader.InfoDisplayPage != 0) ? Language.GetTextValue("tModLoader.PreviousInfoAccPage") : Language.GetTextValue("tModLoader.LastInfoAccPage"));
                Main.mouseText = true;
            }
        }
        spriteBatch.Draw(buttonTexture, buttonPosition, (Rectangle?)new Rectangle(0, 0, buttonTexture.Width, buttonTexture.Height), Color.White, 0f, default(Vector2), 1f, (SpriteEffects)1, 0f);
        if (hovering)
        {
            spriteBatch.Draw(TextureAssets.InfoIcon[13].Value, buttonPosition - Vector2.One * 2f, (Rectangle?)null, OurFavoriteColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
    }
References Terraria.ModLoader.InfoDisplayLoader.ActiveDisplays(), Terraria.ModLoader.InfoDisplayLoader.ActivePages(), Terraria.Main.GetInfoAccIconPosition(), Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.ModLoader.InfoDisplayLoader.InfoDisplayCount, Terraria.ModLoader.InfoDisplayLoader.InfoDisplayPage, Terraria.ModLoader.UI.UICommon.InfoDisplayPageArrowTexture, Terraria.GameContent.TextureAssets.InfoIcon, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawInfoAccs().