TModLoader: Terraria.Main.TryAllowingToCraftRecipe
TryAllowingToCraftRecipe()
static bool Terraria.Main.TryAllowingToCraftRecipe (Recipe currentRecipe, bool tryFittingItemInInventoryToAllowCrafting, out bool movedAnItemToAllowCrafting) inline static private
    {
        movedAnItemToAllowCrafting = false;
        if (mouseItem.IsAir)
        {
            return true;
        }
        if (mouseItem.maxStack > 1 && mouseItem.AllowReforgeForStackableItem && mouseItem.prefix > 0)
        {
            return false;
        }
        if (mouseItem.IsTheSameAs(currentRecipe.createItem) && mouseItem.stack + currentRecipe.createItem.stack <= mouseItem.maxStack)
        {
            return true;
        }
        if (tryFittingItemInInventoryToAllowCrafting && LocalPlayer.ItemSpace(mouseItem).CanTakeItemToPersonalInventory)
        {
            mouseItem = LocalPlayer.GetItem(myPlayer, mouseItem, GetItemSettings.InventoryUIToInventorySettingsShowAsNew);
            if (mouseItem.IsAir)
            {
                movedAnItemToAllowCrafting = true;
                return true;
            }
            if (mouseItem.IsTheSameAs(currentRecipe.createItem) && mouseItem.stack + currentRecipe.createItem.stack <= mouseItem.maxStack)
            {
                movedAnItemToAllowCrafting = true;
                return true;
            }
        }
        return false;
    }
References Terraria.Item.AllowReforgeForStackableItem, Terraria.Player.ItemSpaceStatus.CanTakeItemToPersonalInventory, Terraria.Recipe.createItem, Terraria.Player.GetItem(), Terraria.GetItemSettings.InventoryUIToInventorySettingsShowAsNew, Terraria.Item.IsAir, Terraria.Item.IsTheSameAs(), Terraria.Player.ItemSpace(), Terraria.Main.LocalPlayer, Terraria.Item.maxStack, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Item.prefix, and Terraria.Item.stack.
Referenced by Terraria.Main.HoverOverCraftingItemButton().