TModLoader: Terraria.Main.DrawSmartCursor
DrawSmartCursor()
static void Terraria.Main.DrawSmartCursor () inline static private
    {
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0106: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0154: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0182: Unknown result type (might be due to invalid IL or missing references)
        //IL_0183: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0192: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_024a: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_025a: Unknown result type (might be due to invalid IL or missing references)
        //IL_025f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_030f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0319: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_0329: Unknown result type (might be due to invalid IL or missing references)
        //IL_0331: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_0342: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_0371: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0385: Unknown result type (might be due to invalid IL or missing references)
        //IL_038b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0393: Unknown result type (might be due to invalid IL or missing references)
        //IL_039a: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        if (SmartCursorShowing && !player[myPlayer].dead)
        {
            Vector2 vector = new Vector2((float)SmartCursorX, (float)SmartCursorY) * 16f;
            new Vector2((float)offScreenRange, (float)offScreenRange);
            _ = drawToScreen;
            vector -= screenPosition;
            if (player[myPlayer].gravDir == -1f)
            {
                vector.Y = (float)screenHeight - vector.Y - 16f;
            }
            Color newColor = Lighting.GetColor(SmartCursorX, SmartCursorY) * 1f;
            Rectangle value = default(Rectangle);
            ((Rectangle)(ref value))._002Ector(0, 0, 1, 1);
            float r = 1f;
            float g = 0.9f;
            float b = 0.1f;
            float a = 1f;
            float num = 0.6f;
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector, (Rectangle?)value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, 8f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * 8f, (Rectangle?)value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, 8f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * 8f, (Rectangle?)value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, 8f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.One * 8f, (Rectangle?)value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, 8f, (SpriteEffects)0, 0f);
            b = 0.3f;
            g = 0.95f;
            a = (num = 1f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * -2f, (Rectangle?)value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, new Vector2(2f, 16f), (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitX * 16f, (Rectangle?)value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, new Vector2(2f, 16f), (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * -2f, (Rectangle?)value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, new Vector2(16f, 2f), (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector + Vector2.UnitY * 16f, (Rectangle?)value, buffColor(newColor, r, g, b, a) * num, 0f, Vector2.Zero, new Vector2(16f, 2f), (SpriteEffects)0, 0f);
        }
    }
References Terraria.Main.buffColor(), Terraria.Graphics.Light.Color, Terraria.Main.drawToScreen, Terraria.Lighting.GetColor(), Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.myPlayer, Terraria.Main.offScreenRange, Terraria.Main.player, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.SmartCursorShowing, Terraria.Main.SmartCursorX, Terraria.Main.SmartCursorY, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawInterface_2_SmartCursorTargets().