TModLoader: Terraria.Main.AutoJoin
AutoJoin()
void Terraria.Main.AutoJoin (string IP, string player = null) inline
Definition at line 5027 of file Main.cs.
    {
        defaultIP = IP;
        getIP = IP;
        Netplay.SetRemoteIP(defaultIP);
        Terraria.ModLoader.ModLoader.OnSuccessfulLoad = (Action)Delegate.Combine(Terraria.ModLoader.ModLoader.OnSuccessfulLoad, (Action)delegate
        {
            PlayerFileData playerFileData = null;
            if (player != null)
            {
                if (File.Exists(player))
                {
                    playerFileData = Player.GetFileData(player, cloudSave: false);
                }
                else
                {
                    LoadPlayers();
                    playerFileData = PlayerList.FirstOrDefault((PlayerFileData p) => p.Name == player);
                }
            }
            if (playerFileData != null)
            {
                playerFileData.SetAsActive();
                menuMode = 10;
                Netplay.StartTcpClient();
            }
            else
            {
                OpenPlayerSelect(delegate(PlayerFileData fileData)
                {
                    fileData.SetAsActive();
                    menuMode = 10;
                    Netplay.StartTcpClient();
                });
            }
        });
    }
References Terraria.Main.defaultIP, Terraria.Player.GetFileData(), Terraria.Main.getIP, Terraria.Main.LoadPlayers(), Terraria.Main.menuMode, Terraria.ModLoader.ModLoader.OnSuccessfulLoad, Terraria.Main.OpenPlayerSelect(), Terraria.Main.player, Terraria.Main.PlayerList, Terraria.Netplay.SetRemoteIP(), and Terraria.Netplay.StartTcpClient().