TModLoader: Terraria.Main.DrawHairWindow
DrawHairWindow()
void Terraria.Main.DrawHairWindow () inline protected
Definition at line 56478 of file Main.cs.
    {
        //IL_00be: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_030b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0311: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_046e: Unknown result type (might be due to invalid IL or missing references)
        //IL_047e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0701: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_0974: Unknown result type (might be due to invalid IL or missing references)
        //IL_0979: Unknown result type (might be due to invalid IL or missing references)
        //IL_097b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0982: Unknown result type (might be due to invalid IL or missing references)
        //IL_0987: Unknown result type (might be due to invalid IL or missing references)
        //IL_0994: Unknown result type (might be due to invalid IL or missing references)
        //IL_0999: Unknown result type (might be due to invalid IL or missing references)
        //IL_099b: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0852: Unknown result type (might be due to invalid IL or missing references)
        //IL_085d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0865: Unknown result type (might be due to invalid IL or missing references)
        //IL_086a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0871: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_083a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0833: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aa9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ab6: Unknown result type (might be due to invalid IL or missing references)
        //IL_083c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b9c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c62: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c67: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c03: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c08: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d39: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d3e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d5c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d61: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d84: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d89: Unknown result type (might be due to invalid IL or missing references)
        //IL_0da6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0dab: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e7f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fa8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fca: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_10aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_103a: Unknown result type (might be due to invalid IL or missing references)
        //IL_103f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1178: Unknown result type (might be due to invalid IL or missing references)
        //IL_117d: Unknown result type (might be due to invalid IL or missing references)
        //IL_118d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1192: Unknown result type (might be due to invalid IL or missing references)
        //IL_11da: Unknown result type (might be due to invalid IL or missing references)
        //IL_11e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_129f: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_12d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_12e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_122b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1246: Unknown result type (might be due to invalid IL or missing references)
        //IL_1264: Unknown result type (might be due to invalid IL or missing references)
        //IL_1270: Unknown result type (might be due to invalid IL or missing references)
        //IL_1276: Unknown result type (might be due to invalid IL or missing references)
        //IL_1434: Unknown result type (might be due to invalid IL or missing references)
        //IL_144a: Unknown result type (might be due to invalid IL or missing references)
        //IL_145f: Unknown result type (might be due to invalid IL or missing references)
        //IL_146b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1471: Unknown result type (might be due to invalid IL or missing references)
        //IL_149e: Unknown result type (might be due to invalid IL or missing references)
        //IL_14b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_14d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_14de: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_1511: Unknown result type (might be due to invalid IL or missing references)
        //IL_1527: Unknown result type (might be due to invalid IL or missing references)
        //IL_153c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1548: Unknown result type (might be due to invalid IL or missing references)
        //IL_154e: Unknown result type (might be due to invalid IL or missing references)
        //IL_156e: Unknown result type (might be due to invalid IL or missing references)
        //IL_157e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1583: Unknown result type (might be due to invalid IL or missing references)
        //IL_1588: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_15a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_15bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_15c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_15d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_13a3: Unknown result type (might be due to invalid IL or missing references)
        if (npcChatText != "" || playerInventory || player[myPlayer].chest != -1 || npcShop != 0 || player[myPlayer].talkNPC == -1 || InGuideCraftMenu)
        {
            CancelHairWindow();
            return;
        }
        if (!hairstylesUpdatedForThisInteraction)
        {
            hairstylesUpdatedForThisInteraction = true;
            Hairstyles.UpdateUnlocks();
        }
        int count = Hairstyles.AvailableHairstyles.Count;
        int num = screenHeight / 2 + 60;
        int num12 = screenWidth / 2 - TextureAssets.HairStyleBack.Width() / 2;
        int num23 = num + 42;
        int num28 = num12 + 22;
        int num29 = num12 + 234;
        int num30 = num + 18;
        selColor = player[myPlayer].hairColor;
        spriteBatch.Draw(TextureAssets.HairStyleBack.Value, new Vector2((float)num12, (float)num), (Rectangle?)new Rectangle(0, 0, TextureAssets.HairStyleBack.Width(), TextureAssets.HairStyleBack.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        Rectangle val = new Rectangle(num12, num, TextureAssets.HairStyleBack.Width(), TextureAssets.HairStyleBack.Height());
        if (((Rectangle)(ref val)).Contains(MouseScreen.ToPoint()))
        {
            int num31 = PlayerInput.ScrollWheelDelta / 120;
            num31 = -num31;
            int num32 = Math.Sign(num31);
            while (num31 != 0)
            {
                if (num31 < 0)
                {
                    hairStart -= 5;
                    SoundEngine.PlaySound(12);
                }
                else
                {
                    hairStart += 5;
                    SoundEngine.PlaySound(12);
                }
                num31 -= num32;
            }
        }
        if (mouseX > num12 && mouseX < num12 + TextureAssets.HairStyleBack.Width() && mouseY > num && mouseY < num + TextureAssets.HairStyleBack.Height())
        {
            player[myPlayer].mouseInterface = true;
        }
        int num33 = num29 - 18;
        int num2 = num30 + 74;
        if (hairStart > 1)
        {
            if (mouseX >= num33 && mouseX <= num33 + TextureAssets.CraftUpButton.Width() && mouseY >= num2 && mouseY <= num2 + TextureAssets.CraftUpButton.Height())
            {
                player[myPlayer].mouseInterface = true;
                if (mouseLeftRelease && mouseLeft)
                {
                    hairStart -= 15;
                    SoundEngine.PlaySound(12);
                }
            }
            spriteBatch.Draw(TextureAssets.ScrollLeftButton.Value, new Vector2((float)num33, (float)num2), (Rectangle?)new Rectangle(0, 0, TextureAssets.CraftUpButton.Width(), TextureAssets.CraftUpButton.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        if (hairStart + 15 < count)
        {
            num33 += 296;
            if (mouseX >= num33 && mouseX <= num33 + TextureAssets.CraftUpButton.Width() && mouseY >= num2 && mouseY <= num2 + TextureAssets.CraftUpButton.Height())
            {
                player[myPlayer].mouseInterface = true;
                if (mouseLeftRelease && mouseLeft)
                {
                    hairStart += 15;
                    SoundEngine.PlaySound(12);
                }
            }
            spriteBatch.Draw(TextureAssets.ScrollRightButton.Value, new Vector2((float)num33, (float)num2), (Rectangle?)new Rectangle(0, 0, TextureAssets.CraftUpButton.Width(), TextureAssets.CraftUpButton.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
        }
        if (hairStart + 15 >= count)
        {
            hairStart = count - 15;
        }
        if (hairStart < 0)
        {
            hairStart = 0;
        }
        int num3 = 0;
        if (oldHairStyle != player[myPlayer].hair)
        {
            num3 += 100000;
        }
        if (oldHairColor != player[myPlayer].hairColor)
        {
            num3 += 20000;
        }
        num3 = (int)((double)num3 * player[myPlayer].currentShoppingSettings.PriceAdjustment);
        num3 = (int)Math.Round((float)num3 / 10000f) * 10000;
        string text = "";
        string text2 = "";
        int num4 = 0;
        int num5 = 0;
        int num6 = 0;
        int num7 = 0;
        int num8 = num3;
        if (num8 < 0)
        {
            num8 = 0;
        }
        num3 = num8;
        if (num8 >= 1000000)
        {
            num4 = num8 / 1000000;
            num8 -= num4 * 1000000;
        }
        if (num8 >= 10000)
        {
            num5 = num8 / 10000;
            num8 -= num5 * 10000;
        }
        if (num8 >= 100)
        {
            num6 = num8 / 100;
            num8 -= num6 * 100;
        }
        if (num8 >= 1)
        {
            num7 = num8;
        }
        if (num4 > 0)
        {
            text2 = text2 + num4 + " " + Lang.inter[15].Value + " ";
        }
        if (num5 > 0)
        {
            text2 = text2 + num5 + " " + Lang.inter[16].Value + " ";
        }
        if (num6 > 0)
        {
            text2 = text2 + num6 + " " + Lang.inter[17].Value + " ";
        }
        if (num7 > 0)
        {
            text2 = text2 + num7 + " " + Lang.inter[18].Value + " ";
        }
        text = Language.GetTextValue("GameUI.BuyWithValue", text2);
        if (num3 == 0)
        {
            text = Language.GetTextValue("GameUI.Buy");
        }
        int num9 = (mouseTextColor * 2 + 255) / 3;
        Color color = default(Color);
        ((Color)(ref color))._002Ector(num9, (int)((double)num9 / 1.1), num9 / 2, num9);
        float scale = 0.9f;
        string text3 = text;
        int num10 = num12 + 18;
        int num11 = num + 156;
        bool flag = false;
        if (num3 > 0)
        {
            ItemSlot.DrawSavings(spriteBatch, num10, num11 - 70, horizontal: true);
        }
        if (num3 > 0 && mouseX > num10 && (float)mouseX < (float)num10 + FontAssets.MouseText.Value.MeasureString(text3).X && mouseY > num11 && (float)mouseY < (float)num11 + FontAssets.MouseText.Value.MeasureString(text3).Y)
        {
            flag = true;
            scale = 1.1f;
            if (!npcChatFocus1)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus1 = true;
            player[myPlayer].releaseUseItem = false;
        }
        else
        {
            if (npcChatFocus1)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus1 = false;
        }
        Vector2 vector = FontAssets.MouseText.Value.MeasureString(text3);
        vector *= 0.5f;
        UILinkPointNavigator.SetPosition(2603, new Vector2((float)num10, (float)num11) + vector);
        for (int i = 0; i < 5; i++)
        {
            int num13 = num10;
            int num14 = num11;
            Color color2 = Color.Black;
            if (flag)
            {
                color2 = Color.Brown;
            }
            if (i == 0)
            {
                num13 -= 2;
            }
            if (i == 1)
            {
                num13 += 2;
            }
            if (i == 2)
            {
                num14 -= 2;
            }
            if (i == 3)
            {
                num14 += 2;
            }
            if (i == 4)
            {
                color2 = (Color)((num3 != 0) ? color : new Color(100, 100, 100));
            }
            spriteBatch.DrawString(FontAssets.MouseText.Value, text3, new Vector2((float)num13 + vector.X, (float)num14 + vector.Y), color2, 0f, vector, scale, (SpriteEffects)0, 0f);
        }
        scale = 0.9f;
        string textValue = Language.GetTextValue("GameUI.Cancel");
        num10 += 130;
        flag = false;
        if (mouseX > num10 && (float)mouseX < (float)num10 + FontAssets.MouseText.Value.MeasureString(textValue).X && mouseY > num11 && (float)mouseY < (float)num11 + FontAssets.MouseText.Value.MeasureString(textValue).Y)
        {
            flag = true;
            scale = 1.1f;
            if (!npcChatFocus2)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus2 = true;
            player[myPlayer].releaseUseItem = false;
        }
        else
        {
            if (npcChatFocus2)
            {
                SoundEngine.PlaySound(12);
            }
            npcChatFocus2 = false;
        }
        vector = FontAssets.MouseText.Value.MeasureString(textValue);
        vector *= 0.5f;
        UILinkPointNavigator.SetPosition(2604, new Vector2((float)num10, (float)num11) + vector);
        for (int j = 0; j < 5; j++)
        {
            int num15 = num10;
            int num16 = num11;
            Color color3 = Color.Black;
            if (flag)
            {
                color3 = Color.Brown;
            }
            if (j == 0)
            {
                num15 -= 2;
            }
            if (j == 1)
            {
                num15 += 2;
            }
            if (j == 2)
            {
                num16 -= 2;
            }
            if (j == 3)
            {
                num16 += 2;
            }
            if (j == 4)
            {
                color3 = color;
            }
            spriteBatch.DrawString(FontAssets.MouseText.Value, textValue, new Vector2((float)num15 + vector.X, (float)num16 + vector.Y), color3, 0f, vector, scale, (SpriteEffects)0, 0f);
        }
        if (mouseLeft && mouseLeftRelease)
        {
            if (npcChatFocus1)
            {
                if (player[myPlayer].BuyItem(num3))
                {
                    BuyHairWindow();
                    return;
                }
            }
            else if (npcChatFocus2)
            {
                CancelHairWindow();
                return;
            }
        }
        if (!mouseLeft)
        {
            grabColorSlider = 0;
            blockMouse = false;
        }
        int num17 = 167;
        Vector3 val2 = rgbToHsl(selColor);
        float num18 = val2.X;
        float num19 = val2.Y;
        float z = val2.Z;
        float num20 = (float)(int)((Color)(ref selColor)).A / 255f;
        if (hBar == -1f || sBar == -1f || lBar == -1f || aBar == -1f)
        {
            hBar = num18;
            sBar = num19;
            lBar = z;
            aBar = (float)(int)((Color)(ref selColor)).A / 255f;
        }
        else
        {
            num18 = hBar;
            num19 = sBar;
            z = lBar;
            aBar = num20;
        }
        UILinkPointNavigator.SetPosition(2600, new Vector2((float)num28, (float)num23) + TextureAssets.Hue.Value.Size() / 2f);
        spriteBatch.Draw(TextureAssets.Hue.Value, new Vector2((float)num28, (float)num23), Color.White);
        if ((mouseX > num28 - 4 && mouseX < num28 + TextureAssets.Hue.Width() + 4 && mouseY > num23 - 4 && mouseY < num23 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 1)
        {
            spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num28, (float)num23), OurFavoriteColor);
        }
        spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num28 + (float)(TextureAssets.Hue.Width() - 2) * hBar - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num23 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
        if (((mouseX > num28 - 4 && mouseX < num28 + TextureAssets.Hue.Width() + 4 && mouseY > num23 - 4 && mouseY < num23 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 1) && mouseLeft && !blockMouse)
        {
            grabColorSlider = 1;
            num18 = mouseX - num28;
            num18 /= (float)TextureAssets.Hue.Width();
            if (num18 < 0f)
            {
                num18 = 0f;
            }
            if (num18 > 1f)
            {
                num18 = 1f;
            }
            hBar = num18;
        }
        num23 += 26;
        UILinkPointNavigator.SetPosition(2601, new Vector2((float)num28, (float)num23) + TextureAssets.ColorBar.Value.Size() / 2f);
        spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2((float)num28, (float)num23), Color.White);
        for (int k = 0; k <= num17; k++)
        {
            float saturation = (float)k / (float)num17;
            Color color4 = hslToRgb(num18, saturation, z);
            spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2((float)(num28 + k + 5), (float)(num23 + 4)), color4);
        }
        if ((mouseX > num28 - 4 && mouseX < num28 + TextureAssets.Hue.Width() + 4 && mouseY > num23 - 4 && mouseY < num23 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 2)
        {
            spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num28, (float)num23), OurFavoriteColor);
        }
        spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num28 + (float)(TextureAssets.Hue.Width() - 2) * sBar - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num23 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
        if (((mouseX > num28 - 4 && mouseX < num28 + TextureAssets.Hue.Width() + 4 && mouseY > num23 - 4 && mouseY < num23 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 2) && mouseLeft && !blockMouse)
        {
            grabColorSlider = 2;
            num19 = mouseX - num28;
            num19 /= (float)TextureAssets.Hue.Width();
            if (num19 < 0f)
            {
                num19 = 0f;
            }
            if (num19 > 1f)
            {
                num19 = 1f;
            }
            sBar = num19;
        }
        num23 += 26;
        UILinkPointNavigator.SetPosition(2602, new Vector2((float)num28, (float)num23) + TextureAssets.ColorBar.Value.Size() / 2f);
        spriteBatch.Draw(TextureAssets.ColorBar.Value, new Vector2((float)num28, (float)num23), Color.White);
        float num21 = 0.15f;
        for (int l = 0; l <= num17; l++)
        {
            float luminosity = (float)l / (float)num17;
            Color color5 = hslToRgb(num18, num19, luminosity);
            spriteBatch.Draw(TextureAssets.ColorBlip.Value, new Vector2((float)(num28 + l + 5), (float)(num23 + 4)), color5);
        }
        if ((mouseX > num28 - 4 && mouseX < num28 + TextureAssets.Hue.Width() + 4 && mouseY > num23 - 4 && mouseY < num23 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 3)
        {
            spriteBatch.Draw(TextureAssets.ColorHighlight.Value, new Vector2((float)num28, (float)num23), OurFavoriteColor);
        }
        spriteBatch.Draw(TextureAssets.ColorSlider.Value, new Vector2((float)num28 + (float)(TextureAssets.Hue.Width() - 2) * ((lBar - num21) / (1f - num21)) - (float)(TextureAssets.ColorSlider.Width() / 2), (float)(num23 - TextureAssets.ColorSlider.Height() / 2 + TextureAssets.Hue.Height() / 2)), Color.White);
        if (((mouseX > num28 - 4 && mouseX < num28 + TextureAssets.Hue.Width() + 4 && mouseY > num23 - 4 && mouseY < num23 + TextureAssets.Hue.Height() + 4) || grabColorSlider == 3) && mouseLeft && !blockMouse)
        {
            grabColorSlider = 3;
            z = mouseX - num28;
            z /= (float)TextureAssets.Hue.Width();
            if (z < 0f)
            {
                z = 0f;
            }
            if (z > 1f)
            {
                z = 1f;
            }
            z = z * (1f - num21) + num21;
            lBar = z;
        }
        selColor = hslToRgb(hBar, sBar, lBar);
        player[myPlayer].hairColor = selColor;
        int num22 = num29;
        int num24 = num30;
        _ = hairStart;
        int num25 = 0;
        int num26 = 0;
        for (int m = 0; m < 15; m++)
        {
            int num27 = Hairstyles.AvailableHairstyles[hairStart + m];
            UILinkPointNavigator.SetPosition(2605 + m, new Vector2((float)num22, (float)num24) + TextureAssets.InventoryBack.Value.Size() * 0.75f);
            if (player[myPlayer].hair == num27)
            {
                spriteBatch.Draw(TextureAssets.InventoryBack14.Value, new Vector2((float)num22, (float)num24), (Rectangle?)new Rectangle(0, 0, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            else
            {
                spriteBatch.Draw(TextureAssets.InventoryBack8.Value, new Vector2((float)num22, (float)num24), (Rectangle?)new Rectangle(0, 0, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height()), new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            }
            if (mouseX > num22 && mouseX < num22 + TextureAssets.InventoryBack.Width() && mouseY > num24 && mouseY < num24 + TextureAssets.InventoryBack.Height())
            {
                Asset<Texture2D> asset = Assets.Request<Texture2D>("Images/UI/PanelBorder");
                Utils.DrawSplicedPanel(spriteBatch, asset.Value, num22, num24, TextureAssets.InventoryBack.Width(), TextureAssets.InventoryBack.Height(), asset.Width() / 2 - 1, asset.Width() / 2 - 1, asset.Height() / 2 - 1, asset.Height() / 2 - 1, OurFavoriteColor);
                if (mouseLeft && mouseLeftRelease)
                {
                    mouseLeftRelease = false;
                    player[myPlayer].hair = num27;
                    SoundEngine.PlaySound(12);
                }
            }
            LoadHair(num27);
            float x = num22 + TextureAssets.InventoryBack.Width() / 2 - TextureAssets.PlayerHair[num27].Width() / 2;
            float y = num24 + 4;
            spriteBatch.Draw(TextureAssets.Players[num25, 0].Value, new Vector2(x, y), (Rectangle?)new Rectangle(0, 0, TextureAssets.PlayerHair[num27].Width(), 56), player[myPlayer].skinColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.Players[num25, 1].Value, new Vector2(x, y), (Rectangle?)new Rectangle(0, 0, TextureAssets.PlayerHair[num27].Width(), 56), new Color(255, 255, 255, 255), 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.Players[num25, 2].Value, new Vector2(x, y), (Rectangle?)new Rectangle(0, 0, TextureAssets.PlayerHair[num27].Width(), 56), player[myPlayer].eyeColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            Vector2 vector2 = player[myPlayer].GetHairDrawOffset(num27, hatHair: false) * player[myPlayer].Directions;
            spriteBatch.Draw(TextureAssets.PlayerHair[num27].Value, new Vector2(x, y) + vector2, (Rectangle?)new Rectangle(0, 0, TextureAssets.PlayerHair[num27].Width(), 56), selColor, 0f, default(Vector2), 1f, (SpriteEffects)0, 0f);
            num26++;
            num22 += 56;
            if (num26 >= 5)
            {
                num26 = 0;
                num22 = num29;
                num24 += 56;
            }
        }
    }
References Terraria.Main.aBar, Terraria.Main.blockMouse, Terraria.Main.BuyHairWindow(), Terraria.Main.CancelHairWindow(), Terraria.Main.chest, Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.ColorBar, Terraria.GameContent.TextureAssets.ColorBlip, Terraria.GameContent.TextureAssets.ColorHighlight, Terraria.GameContent.TextureAssets.ColorSlider, Terraria.GameContent.TextureAssets.CraftUpButton, Terraria.UI.ItemSlot.DrawSavings(), Terraria.Utils.DrawSplicedPanel(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.grabColorSlider, Terraria.Main.hairStart, Terraria.GameContent.TextureAssets.HairStyleBack, Terraria.Main.Hairstyles, Terraria.Main.hairstylesUpdatedForThisInteraction, Terraria.Main.hBar, Terraria.Main.hslToRgb(), Terraria.GameContent.TextureAssets.Hue, Terraria.Main.InGuideCraftMenu, Terraria.Lang.inter, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.GameContent.TextureAssets.InventoryBack14, Terraria.GameContent.TextureAssets.InventoryBack8, Terraria.Main.lBar, Terraria.Main.LoadHair(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.npcChatFocus1, Terraria.Main.npcChatFocus2, Terraria.Main.npcChatText, Terraria.Main.npcShop, Terraria.Main.oldHairColor, Terraria.Main.oldHairStyle, Terraria.Main.OurFavoriteColor, Terraria.Main.player, Terraria.GameContent.TextureAssets.PlayerHair, Terraria.Main.playerInventory, Terraria.GameContent.TextureAssets.Players, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rgbToHsl(), Terraria.Main.sBar, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.GameContent.TextureAssets.ScrollLeftButton, Terraria.GameContent.TextureAssets.ScrollRightButton, Terraria.Main.selColor, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawInterface_21_HairWindow().