TModLoader: Terraria.Main.OnSubmitServerPassword
OnSubmitServerPassword() [1/2]
void Terraria.Main.OnSubmitServerPassword () inline private
    {
        string text = "-autoshutdown -password \"" + ConvertToSafeArgument(Netplay.ServerPassword) + "\" -lang " + Language.ActiveCulture.LegacyId;
        if (Platform.IsLinux)
        {
            text = ((IntPtr.Size != 8) ? (text + " -x86") : (text + " -x64"));
        }
        text = ((!ActiveWorldFileData.IsCloudSave) ? (text + SanitizePathArgument("world", worldPathName)) : (text + SanitizePathArgument("cloudworld", worldPathName)));
        text = text + " -worldrollbackstokeep " + WorldRollingBackupsCountToKeep;
        text = text + " -modpath \"" + ModOrganizer.modPath + "\"";
        if (showServerConsole)
        {
            text += " -showserverconsole";
        }
        tServer = new Process();
        tServer.StartInfo.FileName = Environment.ProcessPath;
        tServer.StartInfo.Arguments = "tModLoader.dll -server " + text;
        if (libPath != "")
        {
            ProcessStartInfo startInfo = tServer.StartInfo;
            startInfo.Arguments = startInfo.Arguments + " -loadlib " + libPath;
        }
        tServer.StartInfo.UseShellExecute = true;
        if (!showServerConsole)
        {
            tServer.StartInfo.WindowStyle = ProcessWindowStyle.Hidden;
        }
        if (SocialAPI.Network != null)
        {
            SocialAPI.Network.LaunchLocalServer(tServer, MenuServerMode);
        }
        else
        {
            tServer.Start();
        }
        Netplay.SetRemoteIP("127.0.0.1");
        autoPass = true;
        statusText = Lang.menu[8].Value;
        Netplay.StartTcpClient();
        menuMode = 10;
    }
References Terraria.Localization.Language.ActiveCulture, Terraria.Main.ActiveWorldFileData, Terraria.Main.autoPass, Terraria.Main.ConvertToSafeArgument(), Terraria.ModLoader.Environment, Terraria.Main.libPath, Terraria.Lang.menu, Terraria.Main.menuMode, Terraria.Main.MenuServerMode, Terraria.Social.SocialAPI.Network, Terraria.Enums.Platform, Terraria.Main.SanitizePathArgument(), Terraria.Netplay.ServerPassword, Terraria.Netplay.SetRemoteIP(), Terraria.Main.showServerConsole, Terraria.Netplay.StartTcpClient(), Terraria.Main.statusText, Terraria.Main.tServer, Terraria.Main.worldPathName, and Terraria.Main.WorldRollingBackupsCountToKeep.
Referenced by Terraria.Main.DrawMenu(), and Terraria.Main.OnSubmitServerPassword().