TModLoader: Terraria.Main.DrawInterface_36_Cursor
DrawInterface_36_Cursor()
static void Terraria.Main.DrawInterface_36_Cursor () inline static private
Definition at line 58404 of file Main.cs.
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0089: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0214: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        spriteBatch.End();
        spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, SamplerStateForCursor, DepthStencilState.None, RasterizerState.CullCounterClockwise, (Effect)null, UIScaleMatrix);
        if (cursorOverride != -1)
        {
            Color color = default(Color);
            ((Color)(ref color))._002Ector((int)((float)(int)((Color)(ref cursorColor)).R * 0.2f), (int)((float)(int)((Color)(ref cursorColor)).G * 0.2f), (int)((float)(int)((Color)(ref cursorColor)).B * 0.2f), (int)((float)(int)((Color)(ref cursorColor)).A * 0.5f));
            Color white = cursorColor;
            bool flag = true;
            bool flag2 = true;
            float rotation = 0f;
            Vector2 vector = default(Vector2);
            float num = 1f;
            if (cursorOverride == 2)
            {
                flag = false;
                white = Color.White;
                num = 0.7f;
                ((Vector2)(ref vector))._002Ector(0.1f);
            }
            switch (cursorOverride)
            {
            case 2:
                flag = false;
                white = Color.White;
                num = 0.7f;
                ((Vector2)(ref vector))._002Ector(0.1f);
                break;
            case 3:
            case 6:
            case 7:
            case 8:
            case 9:
            case 10:
                flag = false;
                white = Color.White;
                break;
            }
            if (flag)
            {
                spriteBatch.Draw(TextureAssets.Cursors[cursorOverride].Value, new Vector2((float)(mouseX + 1), (float)(mouseY + 1)), (Rectangle?)null, color, rotation, vector * TextureAssets.Cursors[cursorOverride].Value.Size(), cursorScale * 1.1f * num, (SpriteEffects)0, 0f);
            }
            if (flag2)
            {
                spriteBatch.Draw(TextureAssets.Cursors[cursorOverride].Value, new Vector2((float)mouseX, (float)mouseY), (Rectangle?)null, white, rotation, vector * TextureAssets.Cursors[cursorOverride].Value.Size(), cursorScale * num, (SpriteEffects)0, 0f);
            }
        }
        else if (SmartCursorIsUsed)
        {
            DrawCursor(DrawThickCursor(smart: true), smart: true);
        }
        else
        {
            DrawCursor(DrawThickCursor());
        }
    }
References Terraria.Graphics.Light.Color, Terraria.Main.cursorColor, Terraria.Main.cursorOverride, Terraria.GameContent.TextureAssets.Cursors, Terraria.Main.cursorScale, Terraria.Main.DrawCursor(), Terraria.Main.DrawThickCursor(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.SamplerStateForCursor, Terraria.Main.SmartCursorIsUsed, Terraria.Main.spriteBatch, and Terraria.Main.UIScaleMatrix.
Referenced by Terraria.Main.DrawPendingMouseText(), and Terraria.Main.SetupDrawInterfaceLayers().