TModLoader: Terraria.Main.Main
Main() [1/2]
Terraria.Main.Main () inline
        : base(dedServ)
    {
        //IL_02b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c0: Expected O, but got Unknown
        instance = this;
        UnpausedUpdateSeed = (ulong)Guid.NewGuid().GetHashCode();
        ((Game)this).Exiting += Main_Exiting;
        if (!dedServ)
        {
            Map = new WorldMap(maxTilesX, maxTilesY);
            Configuration.Load();
            graphics = new GraphicsDeviceManager((Game)(object)((this is Game) ? this : null));
            graphics.GraphicsProfile = (GraphicsProfile)1;
            FNALogging.GraphicsInit(graphics);
        }
    }
References Terraria.Main.Configuration, Terraria.Main.dedServ, Terraria.Main.graphics, Terraria.ModLoader.Engine.FNALogging.GraphicsInit(), Terraria.Main.instance, Terraria.IO.Preferences.Load(), Terraria.Main.Main_Exiting(), Terraria.Main.Map, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, and Terraria.Main.UnpausedUpdateSeed.