TModLoader: Terraria.Main.DoDraw_UpdateCameraPosition
DoDraw_UpdateCameraPosition()
static void Terraria.Main.DoDraw_UpdateCameraPosition () inline static private
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_016e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_089c: Unknown result type (might be due to invalid IL or missing references)
        //IL_089e: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0200: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0902: Unknown result type (might be due to invalid IL or missing references)
        //IL_0907: Unknown result type (might be due to invalid IL or missing references)
        //IL_0353: Unknown result type (might be due to invalid IL or missing references)
        //IL_0358: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0256: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_026a: Unknown result type (might be due to invalid IL or missing references)
        //IL_026c: Unknown result type (might be due to invalid IL or missing references)
        //IL_026e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0920: Unknown result type (might be due to invalid IL or missing references)
        //IL_0922: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_029b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b14: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b22: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a12: Unknown result type (might be due to invalid IL or missing references)
        //IL_0931: Unknown result type (might be due to invalid IL or missing references)
        //IL_0933: Unknown result type (might be due to invalid IL or missing references)
        //IL_0938: Unknown result type (might be due to invalid IL or missing references)
        //IL_093d: Unknown result type (might be due to invalid IL or missing references)
        //IL_093f: Unknown result type (might be due to invalid IL or missing references)
        //IL_094b: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0304: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0313: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0324: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a48: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a52: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a57: Unknown result type (might be due to invalid IL or missing references)
        //IL_0986: Unknown result type (might be due to invalid IL or missing references)
        //IL_098b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a79: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bcc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0431: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_044c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_0462: Unknown result type (might be due to invalid IL or missing references)
        //IL_046c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_0476: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0481: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ac6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d7: Unknown result type (might be due to invalid IL or missing references)
        Vector3 vector = default(Vector3);
        ((Vector3)(ref vector))._002Ector(1f, 1f, 1f);
        Vector3 vector2 = Vector3.One / vector;
        if (gameMenu || netMode == 2)
        {
            return;
        }
        int num = 21;
        if (cameraX != 0f && !Main.player[myPlayer].pulley)
        {
            cameraX = 0f;
        }
        if (cameraX > 0f)
        {
            cameraX -= 1f;
            if (cameraX < 0f)
            {
                cameraX = 0f;
            }
        }
        if (cameraX < 0f)
        {
            cameraX += 1f;
            if (cameraX > 0f)
            {
                cameraX = 0f;
            }
        }
        Vector2 value = screenPosition;
        screenPosition.X = Main.player[myPlayer].position.X + (float)Main.player[myPlayer].width * 0.5f - (float)(screenWidth / 2) * vector2.X + cameraX;
        screenPosition.Y = Main.player[myPlayer].position.Y + (float)Main.player[myPlayer].height - (float)num - (float)(screenHeight / 2) * vector2.Y + Main.player[myPlayer].gfxOffY;
        Vector2 vector3 = Vector2.Zero;
        float num10 = 0f;
        float num12 = 0f;
        float num13 = 36f;
        bool flag = false;
        Vector2 vector4 = Vector2.Zero;
        if (!Main.player[myPlayer].dead)
        {
            if (DroneCameraTracker.TryTracking(out var cameraPosition))
            {
                vector3 = cameraPosition - LocalPlayer.Center;
                if (LocalPlayer.gravDir == -1f)
                {
                    vector3.Y *= -1f;
                }
                vector4 = vector3;
                vector3 = CurrentPan * 0.87f + vector3 * 0.13f;
                flag = true;
                _cameraPanHasBlackTransition = true;
            }
            else if (LocalGolfState != null && (LocalGolfState.ShouldCameraTrackBallLastKnownLocation || LocalGolfState.IsTrackingBall))
            {
                if (LocalGolfState.IsTrackingBall)
                {
                    Projectile lastHitBall = LocalGolfState.GetLastHitBall();
                    vector3 = lastHitBall.Center - LocalPlayer.Center;
                    vector4 = vector3;
                    _cameraPanHasBlackTransition = true;
                    if (((Vector2)(ref lastHitBall.velocity)).Length() > 20f)
                    {
                        num13 *= 2f;
                    }
                    vector3 = CurrentPan * 0.87f + vector3 * 0.13f;
                    flag = true;
                }
                else if (LocalGolfState.ShouldCameraTrackBallLastKnownLocation)
                {
                    Vector2? lastBallLocation = LocalGolfState.GetLastBallLocation();
                    if (lastBallLocation.HasValue)
                    {
                        vector3 = lastBallLocation.Value - LocalPlayer.Center;
                        vector4 = vector3;
                        _cameraPanHasBlackTransition = true;
                        vector3 = CurrentPan * 0.87f + vector3 * 0.13f;
                        flag = true;
                    }
                }
            }
            else if ((Main.player[myPlayer].noThrow <= 0 && !Main.player[myPlayer].lastMouseInterface) || !(CurrentPan == Vector2.Zero))
            {
                if (PlayerInput.UsingGamepad)
                {
                    Player player = Main.player[myPlayer];
                    if (((Vector2)(ref PlayerInput.GamepadThumbstickRight)).Length() != 0f || !SmartCursorIsUsed)
                    {
                        float num14 = -1f;
                        if (player.inventory[player.selectedItem].type == 1254 && player.scope)
{
                            num14 = 0.8f;
                        }
                        else if (player.inventory[player.selectedItem].type == 1254)
{
                            num14 = 2f / 3f;
                        }
                        else if (player.inventory[player.selectedItem].type == 1299)
{
                            num14 = 2f / 3f;
                        }
                        else if (player.scope)
{
                            num14 = 0.5f;
                        }
                        PlayerLoader.ModifyZoom(LocalPlayer, ref num14);
                        Vector2 vector5 = (MouseScreen - new Vector2((float)screenWidth, (float)screenHeight) / 2f) / (new Vector2((float)screenWidth, (float)screenHeight) / 2f);
                        num13 = 48f;
                        if (vector5 != Vector2.Zero && num14 != -1f)
{
                            Vector2 vector6 = new Vector2((float)screenWidth, (float)screenHeight) * 0.5f * vector5 * num14;
                            vector3.X = vector6.X;
                            vector3.Y = vector6.Y;
                            flag = true;
                        }
                    }
                }
                else if (Main.player[myPlayer].inventory[Main.player[myPlayer].selectedItem].type == 1254 && Main.player[myPlayer].scope && mouseRight)
                {
                    int num15 = mouseX;
                    int num16 = mouseY;
                    if (num15 > screenWidth)
                    {
                        num15 = screenWidth;
                    }
                    if (num15 < 0)
                    {
                        num15 = 0;
                    }
                    if (num16 > screenHeight)
                    {
                        num16 = screenHeight;
                    }
                    if (num16 < 0)
                    {
                        num16 = 0;
                    }
                    float zoom = 0.8f;
                    PlayerLoader.ModifyZoom(LocalPlayer, ref zoom);
                    vector3.X = (float)(num15 - screenWidth / 2) * zoom;
                    vector3.Y = (float)(num16 - screenHeight / 2) * zoom;
                    flag = true;
                }
                else if (Main.player[myPlayer].inventory[Main.player[myPlayer].selectedItem].type == 1254 && mouseRight)
                {
                    int num17 = mouseX;
                    int num18 = mouseY;
                    if (num17 > screenWidth)
                    {
                        num17 = screenWidth;
                    }
                    if (num17 < 0)
                    {
                        num17 = 0;
                    }
                    if (num18 > screenHeight)
                    {
                        num18 = screenHeight;
                    }
                    if (num18 < 0)
                    {
                        num18 = 0;
                    }
                    float zoom2 = 2f / 3f;
                    PlayerLoader.ModifyZoom(LocalPlayer, ref zoom2);
                    vector3.X = (float)(num17 - screenWidth / 2) * zoom2;
                    vector3.Y = (float)(num18 - screenHeight / 2) * zoom2;
                    flag = true;
                }
                else if (Main.player[myPlayer].inventory[Main.player[myPlayer].selectedItem].type == 1299 && Main.player[myPlayer].selectedItem != 58)
                {
                    int num2 = mouseX;
                    int num3 = mouseY;
                    if (num2 > screenWidth)
                    {
                        num2 = screenWidth;
                    }
                    if (num2 < 0)
                    {
                        num2 = 0;
                    }
                    if (num3 > screenHeight)
                    {
                        num3 = screenHeight;
                    }
                    if (num3 < 0)
                    {
                        num3 = 0;
                    }
                    float zoom3 = 2f / 3f;
                    PlayerLoader.ModifyZoom(LocalPlayer, ref zoom3);
                    vector3.X = (float)(num2 - screenWidth / 2) * zoom3;
                    vector3.Y = (float)(num3 - screenHeight / 2) * zoom3;
                    flag = true;
                }
                else if (Main.player[myPlayer].scope && mouseRight)
                {
                    int num4 = mouseX;
                    int num5 = mouseY;
                    if (num4 > screenWidth)
                    {
                        num4 = screenWidth;
                    }
                    if (num4 < 0)
                    {
                        num4 = 0;
                    }
                    if (num5 > screenHeight)
                    {
                        num5 = screenHeight;
                    }
                    if (num5 < 0)
                    {
                        num5 = 0;
                    }
                    float zoom4 = 0.5f;
                    PlayerLoader.ModifyZoom(Main.player[myPlayer], ref zoom4);
                    vector3.X = (float)(num4 - screenWidth / 2) / 2f;
                    vector3.Y = (float)(num5 - screenHeight / 2) / 2f;
                    flag = true;
                }
                else
                {
                    float zoom5 = -1f;
                    PlayerLoader.ModifyZoom(LocalPlayer, ref zoom5);
                    if (zoom5 != -1f)
                    {
                        int mouseXClamped = Utils.Clamp(mouseX, 0, screenWidth);
                        int mouseYClamped = Utils.Clamp(mouseY, 0, screenHeight);
                        vector3.X = (float)(mouseXClamped - screenWidth / 2) * zoom5;
                        vector3.Y = (float)(mouseYClamped - screenHeight / 2) * zoom5;
                        flag = true;
                    }
                }
            }
        }
        if (float.IsNaN(CurrentPan.X))
        {
            CurrentPan.X = 0f;
        }
        if (float.IsNaN(CurrentPan.Y))
        {
            CurrentPan.Y = 0f;
        }
        Vector2 value2 = vector3 - CurrentPan;
        float num6 = ((Vector2)(ref value2)).Length();
        float amount = 1f;
        if (num12 > num10 + 0.0001f)
        {
            amount = MathHelper.Clamp((num6 - num10) / (num12 - num10), 0f, 1f);
        }
        float value3 = MathHelper.SmoothStep(0f, num6, amount);
        value3 = MathHelper.Clamp(value3, 0f, num13);
        Vector2 val;
        if (CurrentPan == Vector2.Zero && _cameraPanHasBlackTransition && vector4 != Vector2.Zero)
        {
            Vector2 vector7 = vector4 - CurrentPan;
            float num19 = Math.Abs(vector7.X);
            float num7 = Math.Abs(vector7.Y);
            float num8 = ((Vector2)(ref vector7)).Length();
            if (num19 >= (float)(screenWidth / 2) || num7 >= (float)(screenHeight / 2))
            {
                val = new Vector2((float)screenWidth, (float)screenHeight);
                if (num8 >= ((Vector2)(ref val)).Length() / 2f + 100f)
                {
                    renderNow = true;
                    CurrentPan = vector4;
                    _cameraPanHasBlackTransition = false;
                    NPC.ResetNetOffsets();
                    BlackFadeIn = 255;
                    if (mapTime < 5)
                    {
                        mapTime = 5;
                    }
                    maxQ = true;
                    Lighting.Clear();
                    instantBGTransitionCounter = 10;
                    LocalPlayer.ForceUpdateBiomes();
                }
            }
        }
        if (vector3 == Vector2.Zero && !flag)
        {
            float num20 = Math.Abs(value2.X);
            float num9 = Math.Abs(value2.Y);
            float num11 = ((Vector2)(ref value2)).Length();
            if (num20 >= (float)(screenWidth / 2) || num9 >= (float)(screenHeight / 2))
            {
                renderNow = true;
                CurrentPan *= 0.9f;
                if (_cameraPanHasBlackTransition)
                {
                    val = new Vector2((float)screenWidth, (float)screenHeight);
                    if (num11 >= ((Vector2)(ref val)).Length() / 2f + 100f)
                    {
                        _cameraPanHasBlackTransition = false;
                        NPC.ResetNetOffsets();
                        BlackFadeIn = 255;
                        if (mapTime < 5)
{
                            mapTime = 5;
                        }
                        maxQ = true;
                        Lighting.Clear();
                        CurrentPan = Vector2.Zero;
                        instantBGTransitionCounter = 10;
                        LocalPlayer.ForceUpdateBiomes();
                    }
                }
            }
            else if (value3 > 0.0001f)
            {
                CurrentPan += Vector2.Normalize(value2) * value3;
            }
        }
        else if (value3 > 0.0001f)
        {
            CurrentPan += Vector2.Normalize(value2) * value3;
        }
        screenPosition.X += CurrentPan.X;
        screenPosition.Y += CurrentPan.Y * Main.player[myPlayer].gravDir;
        if (cameraLerp > 0f)
        {
            if (Vector2.Distance(value, screenPosition) - ((Vector2)(ref Main.player[myPlayer].velocity)).Length() < 0.25f || (cameraGamePadLerp && !PlayerInput.UsingGamepad))
            {
                cameraLerp = 0f;
                cameraGamePadLerp = false;
            }
            else
            {
                screenPosition = Vector2.Lerp(value, screenPosition, cameraLerp);
            }
        }
        instance.CameraModifiers.ApplyTo(ref screenPosition);
        PlayerLoader.ModifyScreenPosition(LocalPlayer);
        SystemLoader.ModifyScreenPosition();
        screenPosition.X = (int)screenPosition.X;
        screenPosition.Y = (int)screenPosition.Y;
        ClampScreenPositionToWorld();
    }
References Terraria.Main._cameraPanHasBlackTransition, Terraria.Main.BlackFadeIn, Terraria.Main.cameraGamePadLerp, Terraria.Main.cameraLerp, Terraria.Main.cameraX, Terraria.Main.ClampScreenPositionToWorld(), Terraria.Lighting.Clear(), Terraria.Main.CurrentPan, Terraria.Main.gameMenu, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.Main.instance, Terraria.Main.instantBGTransitionCounter, Terraria.Main.LocalGolfState, Terraria.Main.LocalPlayer, Terraria.Main.mapTime, Terraria.Main.maxQ, Terraria.ModLoader.SystemLoader.ModifyScreenPosition(), Terraria.ModLoader.PlayerLoader.ModifyScreenPosition(), Terraria.ModLoader.PlayerLoader.ModifyZoom(), Terraria.Main.mouseRight, Terraria.Main.MouseScreen, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Main.renderNow, Terraria.NPC.ResetNetOffsets(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Main.SmartCursorIsUsed, Terraria.DataStructures.DroneCameraTracker.TryTracking(), and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.DoDraw().