TModLoader: Terraria.Main.rgbToHsl
rgbToHsl()
static Vector3 Terraria.Main.rgbToHsl (Color newColor) inline static
    {
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        float num = (int)((Color)(ref newColor)).R;
        float num2 = (int)((Color)(ref newColor)).G;
        float num3 = (int)((Color)(ref newColor)).B;
        num /= 255f;
        num2 /= 255f;
        num3 /= 255f;
        float val = Math.Max(num, num2);
        val = Math.Max(val, num3);
        float val2 = Math.Min(num, num2);
        val2 = Math.Min(val2, num3);
        float num4 = 0f;
        float num5 = (val + val2) / 2f;
        float y;
        if (val == val2)
        {
            num4 = (y = 0f);
        }
        else
        {
            float num6 = val - val2;
            y = (((double)num5 > 0.5) ? (num6 / (2f - val - val2)) : (num6 / (val + val2)));
            if (val == num)
            {
                num4 = (num2 - num3) / num6 + (float)((num2 < num3) ? 6 : 0);
            }
            if (val == num2)
            {
                num4 = (num3 - num) / num6 + 2f;
            }
            if (val == num3)
            {
                num4 = (num - num2) / num6 + 4f;
            }
            num4 /= 6f;
        }
        return new Vector3(num4, y, num5);
    }
Referenced by Terraria.Main.DrawClothesWindow(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawMenu(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), Terraria.Main.DrawProj_DrawNormalProjs(), Terraria.Projectile.GetLastPrismHue(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.GameContent.UI.States.UICharacterCreation.RgbToScaledHsl(), Terraria.DataStructures.ColorSlidersSet.SetHSL(), Terraria.Player.WingFrame(), and Terraria.Player.Yoraiz0rEye().