TModLoader: Terraria.Main.NewTextMultiline
NewTextMultiline()
static void Terraria.Main.NewTextMultiline (string text, bool force = false, Color c = default(Color), int WidthLimit = -1) inline static
Definition at line 81770 of file Main.cs.
    {
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        chatMonitor.NewTextMultiline(text, force, c, WidthLimit);
        SoundEngine.PlaySound(12);
    }
References Terraria.Main.chatMonitor, Terraria.GameContent.UI.Chat.IChatMonitor.NewTextMultiline(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Chat.ChatHelper.DisplayMessage(), Terraria.MessageBuffer.GetData(), Terraria.Wiring.HitWireSingle(), and Terraria.Chat.ChatHelper.ShowCachedMessages().