TModLoader: Terraria.Main.DrawInvasionProgress
DrawInvasionProgress()
static void Terraria.Main.DrawInvasionProgress () inline static
Definition at line 61499 of file Main.cs.
    {
        //IL_00e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0125: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0164: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_0198: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0612: Unknown result type (might be due to invalid IL or missing references)
        //IL_061f: Unknown result type (might be due to invalid IL or missing references)
        //IL_063a: Unknown result type (might be due to invalid IL or missing references)
        //IL_064a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0654: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0334: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0231: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_0273: Unknown result type (might be due to invalid IL or missing references)
        //IL_0278: Unknown result type (might be due to invalid IL or missing references)
        //IL_093c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0941: Unknown result type (might be due to invalid IL or missing references)
        //IL_094a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0706: Unknown result type (might be due to invalid IL or missing references)
        //IL_0741: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_074b: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0401: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_040b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0415: Unknown result type (might be due to invalid IL or missing references)
        //IL_041a: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0428: Unknown result type (might be due to invalid IL or missing references)
        //IL_042a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0434: Unknown result type (might be due to invalid IL or missing references)
        //IL_0445: Unknown result type (might be due to invalid IL or missing references)
        //IL_0452: Unknown result type (might be due to invalid IL or missing references)
        //IL_045e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_0481: Unknown result type (might be due to invalid IL or missing references)
        //IL_0492: Unknown result type (might be due to invalid IL or missing references)
        //IL_0494: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04df: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0509: Unknown result type (might be due to invalid IL or missing references)
        //IL_0528: Unknown result type (might be due to invalid IL or missing references)
        //IL_052e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0545: Unknown result type (might be due to invalid IL or missing references)
        //IL_054f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0563: Unknown result type (might be due to invalid IL or missing references)
        //IL_056f: Unknown result type (might be due to invalid IL or missing references)
        //IL_058e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0594: Unknown result type (might be due to invalid IL or missing references)
        //IL_059e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_097c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0981: Unknown result type (might be due to invalid IL or missing references)
        //IL_0992: Unknown result type (might be due to invalid IL or missing references)
        //IL_0997: Unknown result type (might be due to invalid IL or missing references)
        //IL_099d: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_09b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_09bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_09be: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a09: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a26: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a47: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a68: Unknown result type (might be due to invalid IL or missing references)
        //IL_095a: Unknown result type (might be due to invalid IL or missing references)
        //IL_077d: Unknown result type (might be due to invalid IL or missing references)
        //IL_077f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0786: Unknown result type (might be due to invalid IL or missing references)
        //IL_078b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0790: Unknown result type (might be due to invalid IL or missing references)
        //IL_079a: Unknown result type (might be due to invalid IL or missing references)
        //IL_079f: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07be: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_07cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_07df: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0800: Unknown result type (might be due to invalid IL or missing references)
        //IL_0805: Unknown result type (might be due to invalid IL or missing references)
        //IL_0816: Unknown result type (might be due to invalid IL or missing references)
        //IL_081c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0832: Unknown result type (might be due to invalid IL or missing references)
        //IL_083c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0850: Unknown result type (might be due to invalid IL or missing references)
        //IL_085c: Unknown result type (might be due to invalid IL or missing references)
        //IL_087b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0881: Unknown result type (might be due to invalid IL or missing references)
        //IL_0898: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_090f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0921: Unknown result type (might be due to invalid IL or missing references)
        //IL_0760: Unknown result type (might be due to invalid IL or missing references)
        if (invasionProgress == -1)
        {
            return;
        }
        if (invasionProgressMode == 2 && invasionProgressNearInvasion && invasionProgressDisplayLeft < 160)
        {
            invasionProgressDisplayLeft = 160;
        }
        if (!gamePaused && invasionProgressDisplayLeft > 0)
        {
            invasionProgressDisplayLeft--;
        }
        if (invasionProgressDisplayLeft > 0)
        {
            invasionProgressAlpha += 0.05f;
        }
        else
        {
            invasionProgressAlpha -= 0.05f;
        }
        if (invasionProgressMode == 0)
        {
            invasionProgressDisplayLeft = 0;
            invasionProgressAlpha = 0f;
        }
        if (invasionProgressAlpha < 0f)
        {
            invasionProgressAlpha = 0f;
        }
        if (invasionProgressAlpha > 1f)
        {
            invasionProgressAlpha = 1f;
        }
        if (invasionProgressAlpha <= 0f)
        {
            return;
        }
        float num = 0.5f + invasionProgressAlpha * 0.5f;
        Texture2D value = TextureAssets.Extra[9].Value;
        string text = "";
        Color c = Color.White;
        if (invasionProgressIcon == 1)
        {
            value = TextureAssets.Extra[8].Value;
            text = Lang.inter[83].Value;
            c = new Color(64, 109, 164) * 0.5f;
        }
        else if (invasionProgressIcon == 2)
        {
            value = TextureAssets.Extra[12].Value;
            text = Lang.inter[84].Value;
            c = new Color(112, 86, 114) * 0.5f;
        }
        else if (invasionProgressIcon == 3)
        {
            value = TextureAssets.Extra[79].Value;
            text = Language.GetTextValue("DungeonDefenders2.InvasionProgressTitle");
            c = new Color(88, 0, 160) * 0.5f;
        }
        else if (invasionProgressIcon == 7)
        {
            value = TextureAssets.Extra[10].Value;
            text = Lang.inter[85].Value;
            c = new Color(165, 160, 155) * 0.5f;
        }
        else if (invasionProgressIcon == 6)
        {
            value = TextureAssets.Extra[11].Value;
            text = Lang.inter[86].Value;
            c = new Color(148, 122, 72) * 0.5f;
        }
        else if (invasionProgressIcon == 5)
        {
            value = TextureAssets.Extra[7].Value;
            text = Lang.inter[87].Value;
            c = new Color(173, 135, 140) * 0.5f;
        }
        else if (invasionProgressIcon == 4)
        {
            value = TextureAssets.Extra[9].Value;
            text = Lang.inter[88].Value;
            c = new Color(94, 72, 131) * 0.5f;
        }
        Rectangle r4 = default(Rectangle);
        if (invasionProgressWave > 0)
        {
            int num6 = (int)(200f * num);
            int num7 = (int)(45f * num);
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector((float)(screenWidth - 120), (float)(screenHeight - 40));
            ((Rectangle)(ref r4))._002Ector((int)vector.X - num6 / 2, (int)vector.Y - num7 / 2, num6, num7);
            Utils.DrawInvBG(spriteBatch, r4, new Color(63, 65, 151, 255) * 0.785f);
            string text2 = "";
            text2 = Language.GetTextValue("Game.WaveMessage", arg1: (invasionProgressMax != 0) ? ((int)((float)invasionProgress * 100f / (float)invasionProgressMax) + "%") : Language.GetTextValue("Game.InvasionPoints", invasionProgress), arg0: invasionProgressWave);
            Texture2D value2 = TextureAssets.ColorBar.Value;
            _ = TextureAssets.ColorBlip.Value;
            float num8 = MathHelper.Clamp((float)invasionProgress / (float)invasionProgressMax, 0f, 1f);
            if (invasionProgressMax == 0)
            {
                num8 = 1f;
            }
            float num9 = 169f * num;
            float num10 = 8f * num;
            Vector2 vector2 = vector + Vector2.UnitY * num10 + Vector2.UnitX * 1f;
            Utils.DrawBorderString(spriteBatch, text2, vector2, Color.White * invasionProgressAlpha, num, 0.5f, 1f);
            spriteBatch.Draw(value2, vector, (Rectangle?)null, Color.White * invasionProgressAlpha, 0f, new Vector2((float)(value2.Width / 2), 0f), num, (SpriteEffects)0, 0f);
            vector2 += Vector2.UnitX * (num8 - 0.5f) * num9;
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector2, (Rectangle?)new Rectangle(0, 0, 1, 1), new Color(255, 241, 51) * invasionProgressAlpha, 0f, new Vector2(1f, 0.5f), new Vector2(num9 * num8, num10), (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector2, (Rectangle?)new Rectangle(0, 0, 1, 1), new Color(255, 165, 0, 127) * invasionProgressAlpha, 0f, new Vector2(1f, 0.5f), new Vector2(2f, num10), (SpriteEffects)0, 0f);
            spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector2, (Rectangle?)new Rectangle(0, 0, 1, 1), Color.Black * invasionProgressAlpha, 0f, new Vector2(0f, 0.5f), new Vector2(num9 * (1f - num8), num10), (SpriteEffects)0, 0f);
        }
        else
        {
            int num11 = (int)(200f * num);
            int num12 = (int)(45f * num);
            Vector2 vector3 = default(Vector2);
            ((Vector2)(ref vector3))._002Ector((float)(screenWidth - 120), (float)(screenHeight - 40));
            ((Rectangle)(ref r4))._002Ector((int)vector3.X - num11 / 2, (int)vector3.Y - num12 / 2, num11, num12);
            Utils.DrawInvBG(spriteBatch, r4, new Color(63, 65, 151, 255) * 0.785f);
            string text3 = "";
            text3 = ((invasionProgressMax != 0) ? ((int)((float)invasionProgress * 100f / (float)invasionProgressMax) + "%") : invasionProgress.ToString());
            text3 = Language.GetTextValue("Game.WaveCleared", text3);
            Texture2D value3 = TextureAssets.ColorBar.Value;
            _ = TextureAssets.ColorBlip.Value;
            if (invasionProgressMax != 0)
            {
                spriteBatch.Draw(value3, vector3, (Rectangle?)null, Color.White * invasionProgressAlpha, 0f, new Vector2((float)(value3.Width / 2), 0f), num, (SpriteEffects)0, 0f);
                float num13 = MathHelper.Clamp((float)invasionProgress / (float)invasionProgressMax, 0f, 1f);
                Vector2 vector4 = FontAssets.MouseText.Value.MeasureString(text3);
                float num2 = num;
                if (vector4.Y > 22f)
                {
                    num2 *= 22f / vector4.Y;
                }
                float num3 = 169f * num;
                float num4 = 8f * num;
                Vector2 vector5 = vector3 + Vector2.UnitY * num4 + Vector2.UnitX * 1f;
                Utils.DrawBorderString(spriteBatch, text3, vector5 + new Vector2(0f, -4f), Color.White * invasionProgressAlpha, num2, 0.5f, 1f);
                vector5 += Vector2.UnitX * (num13 - 0.5f) * num3;
                spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector5, (Rectangle?)new Rectangle(0, 0, 1, 1), new Color(255, 241, 51) * invasionProgressAlpha, 0f, new Vector2(1f, 0.5f), new Vector2(num3 * num13, num4), (SpriteEffects)0, 0f);
                spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector5, (Rectangle?)new Rectangle(0, 0, 1, 1), new Color(255, 165, 0, 127) * invasionProgressAlpha, 0f, new Vector2(1f, 0.5f), new Vector2(2f, num4), (SpriteEffects)0, 0f);
                spriteBatch.Draw(TextureAssets.MagicPixel.Value, vector5, (Rectangle?)new Rectangle(0, 0, 1, 1), Color.Black * invasionProgressAlpha, 0f, new Vector2(0f, 0.5f), new Vector2(num3 * (1f - num13), num4), (SpriteEffects)0, 0f);
            }
        }
        Vector2 vector6 = FontAssets.MouseText.Value.MeasureString(text);
        float num5 = 120f;
        if (vector6.X > 200f)
        {
            num5 += vector6.X - 200f;
        }
        Rectangle r3 = Utils.CenteredRectangle(new Vector2((float)screenWidth - num5, (float)(screenHeight - 80)), (vector6 + new Vector2((float)(value.Width + 12), 6f)) * num);
        Utils.DrawInvBG(spriteBatch, r3, c);
        spriteBatch.Draw(value, r3.Left() + Vector2.UnitX * num * 8f, (Rectangle?)null, Color.White * invasionProgressAlpha, 0f, new Vector2(0f, (float)(value.Height / 2)), num * 0.8f, (SpriteEffects)0, 0f);
        Utils.DrawBorderString(spriteBatch, text, r3.Right() + Vector2.UnitX * num * -22f, Color.White * invasionProgressAlpha, num * 0.9f, 1f, 0.4f);
    }
References Terraria.Utils.CenteredRectangle(), Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.ColorBar, Terraria.GameContent.TextureAssets.ColorBlip, Terraria.Utils.DrawBorderString(), Terraria.Utils.DrawInvBG(), Terraria.GameContent.TextureAssets.Extra, Terraria.Main.gamePaused, Terraria.Localization.Language.GetTextValue(), Terraria.Lang.inter, Terraria.Main.invasionProgress, Terraria.Main.invasionProgressAlpha, Terraria.Main.invasionProgressDisplayLeft, Terraria.Main.invasionProgressIcon, Terraria.Main.invasionProgressMax, Terraria.Main.invasionProgressMode, Terraria.Main.invasionProgressNearInvasion, Terraria.Main.invasionProgressWave, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.screenHeight, Terraria.Main.screenWidth, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawInterface_15_InvasionProgressBars().