TModLoader: Terraria.Main.DrawNetplayStatusText
DrawNetplayStatusText()
static void Terraria.Main.DrawNetplayStatusText () inline static private
Definition at line 80184 of file Main.cs.
    {
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_016c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        if (netMode == 1 && !string.IsNullOrWhiteSpace(Netplay.Connection.StatusText))
        {
            string text = Netplay.Connection.StatusText;
            if (!Netplay.Connection.HideStatusTextPercent)
            {
                text = text + ": " + (int)((float)Netplay.Connection.StatusCount / (float)Netplay.Connection.StatusMax * 100f) + "%";
            }
            if (_netplayStatusTextSnippets == null || _oldNetplayStatusText != text)
            {
                _netplayStatusTextSnippets = ChatManager.ParseMessage(text, Color.White).ToArray();
                _oldNetplayStatusText = text;
            }
            Vector2 position = default(Vector2);
            ((Vector2)(ref position))._002Ector(628f - ChatManager.GetStringSize(FontAssets.MouseText.Value, _netplayStatusTextSnippets, Vector2.One).X * 0.5f + (float)(screenWidth - 800), 84f);
            int hoveredSnippet;
            if (Netplay.Connection.StatusTextHasShadows)
            {
                ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, _netplayStatusTextSnippets, position, 0f, Vector2.Zero, Vector2.One, out hoveredSnippet);
            }
            else
            {
                ChatManager.DrawColorCodedString(spriteBatch, FontAssets.MouseText.Value, _netplayStatusTextSnippets, position, new Color((int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor, (int)mouseTextColor), 0f, Vector2.Zero, Vector2.One, out hoveredSnippet, -1f);
            }
        }
    }
References Terraria.Main._netplayStatusTextSnippets, Terraria.Main._oldNetplayStatusText, Terraria.Graphics.Light.Color, Terraria.Netplay.Connection, Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.RemoteServer.HideStatusTextPercent, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.netMode, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.RemoteServer.StatusMax, Terraria.RemoteServer.StatusText, and Terraria.RemoteServer.StatusTextHasShadows.
Referenced by Terraria.Main.DoDraw().