TModLoader: Terraria.Main.UpdateBGVisibility_BackLayer
UpdateBGVisibility_BackLayer()
void Terraria.Main.UpdateBGVisibility_BackLayer (int? targetBiomeOverride, float? transitionAmountOverride) inline private
Definition at line 81213 of file Main.cs.
    {
        int value = bgStyle;
        if (targetBiomeOverride.HasValue)
        {
            value = targetBiomeOverride.Value;
        }
        _ = backgroundLayerTransitionSpeed;
        if (transitionAmountOverride.HasValue)
        {
            _ = transitionAmountOverride.Value;
        }
        switch (value)
        {
        case 2:
            DrawBG_ModifyBGFarBackLayerAlpha(1, null, transitionAmountOverride);
            break;
        case 3:
            if (WorldGen.jungleBG == 5)
            {
                DrawBG_ModifyBGFarBackLayerAlpha(13, null, transitionAmountOverride);
            }
            else
            {
                DrawBG_ModifyBGFarBackLayerAlpha(0, null, transitionAmountOverride);
            }
            break;
        case 1:
        case 5:
            DrawBG_ModifyBGFarBackLayerAlpha(2, null, transitionAmountOverride);
            break;
        case 6:
            if (WorldGen.hallowBG == 3)
            {
                DrawBG_ModifyBGFarBackLayerAlpha(6, null, transitionAmountOverride);
            }
            else
            {
                DrawBG_ModifyBGFarBackLayerAlpha(2, null, transitionAmountOverride);
            }
            break;
        case 4:
            DrawBG_ModifyBGFarBackLayerAlpha(3, null, transitionAmountOverride);
            break;
        case 7:
            DrawBG_ModifyBGFarBackLayerAlpha(4, null, transitionAmountOverride);
            break;
        case 8:
            DrawBG_ModifyBGFarBackLayerAlpha(5, null, transitionAmountOverride);
            break;
        case 9:
            DrawBG_ModifyBGFarBackLayerAlpha(0, 6, transitionAmountOverride);
            break;
        case 10:
        case 11:
        case 12:
            DrawBG_ModifyBGFarBackLayerAlpha(value, null, transitionAmountOverride);
            break;
        default:
            if (value >= 14)
            {
                DrawBG_ModifyBGFarBackLayerAlpha(value, null, transitionAmountOverride);
            }
            else
            {
                DrawBG_ModifyBGFarBackLayerAlpha(0, null, transitionAmountOverride);
            }
            break;
        }
    }
References Terraria.Main.backgroundLayerTransitionSpeed, Terraria.Main.bgStyle, Terraria.Main.DrawBG_ModifyBGFarBackLayerAlpha(), Terraria.WorldGen.hallowBG, and Terraria.WorldGen.jungleBG.
Referenced by Terraria.Main.DrawBG(), and Terraria.Main.DrawCapture().