TModLoader: Terraria.Main.DrawMapIcons_LastGolfballHit
DrawMapIcons_LastGolfballHit()
void Terraria.Main.DrawMapIcons_LastGolfballHit (SpriteBatch spriteBatch, Vector2 mapTopLeft, Vector2 mapX2Y2AndOff, Rectangle? mapRect, float mapScale, float drawScale, ref string mouseTextString) inline private
Definition at line 72138 of file Main.cs.
    {
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_007e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_0096: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0128: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        //IL_0142: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        Projectile lastHitBall = LocalGolfState.GetLastHitBall();
        if (lastHitBall == null)
        {
            return;
        }
        Vector2 vec = lastHitBall.Center / 16f - mapTopLeft;
        vec *= mapScale;
        vec += mapX2Y2AndOff;
        vec = vec.Floor();
        if (mapRect.HasValue)
        {
            Rectangle value2 = mapRect.Value;
            if (!((Rectangle)(ref value2)).Contains(vec.ToPoint()))
            {
                return;
            }
        }
        Texture2D value = TextureAssets.Extra[176].Value;
        Rectangle rectangle = value.Frame();
        spriteBatch.Draw(value, vec, (Rectangle?)rectangle, Color.White, 0f, rectangle.Size() / 2f, drawScale, (SpriteEffects)0, 0f);
        Rectangle rectangle2 = Utils.CenteredRectangle(vec, rectangle.Size() * drawScale);
        LoadProjectile(lastHitBall.type);
        value = TextureAssets.Projectile[lastHitBall.type].Value;
        rectangle = value.Frame();
        spriteBatch.Draw(value, vec, (Rectangle?)rectangle, Color.White, 0f, rectangle.Size() / 2f, drawScale, (SpriteEffects)0, 0f);
        if (((Rectangle)(ref rectangle2)).Contains(MouseScreen.ToPoint()))
        {
            mouseTextString = lastHitBall.Name;
            _ = MouseScreen + new Vector2(-28f) + new Vector2(4f, 0f);
        }
    }
References Terraria.Utils.CenteredRectangle(), Terraria.Graphics.Light.Color, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Golf.GolfState.GetLastHitBall(), Terraria.Main.LoadProjectile(), Terraria.Main.LocalGolfState, Terraria.Main.MouseScreen, Terraria.GameContent.TextureAssets.Projectile, and Terraria.Main.spriteBatch.
Referenced by Terraria.Main.DrawMiscMapIcons().