TModLoader: Terraria.ModLoader.ItemLoader.NeedsModSaving
NeedsModSaving()
static bool Terraria.ModLoader.ItemLoader.NeedsModSaving (Item item) inline static package
    {
        if (item.type <= 0)
        {
            return false;
        }
        if (item.ModItem != null || item.prefix >= PrefixID.Count)
        {
            return true;
        }
        return false;
    }
References Terraria.ID.PrefixID.Count, Terraria.Item.ModItem, Terraria.Item.prefix, and Terraria.Item.type.
Referenced by Terraria.GameContent.UI.Chat.ItemTagHandler.GenerateTag(), Terraria.ModLoader.IO.TileIO.SaveContainers(), and Terraria.ModLoader.IO.PlayerIO.SaveInventory().