TModLoader: Terraria.ModLoader.ItemLoader.Unload
Unload()
static void Terraria.ModLoader.ItemLoader.Unload () inline static package
    {
        ItemCount = ItemID.Count;
        items.Clear();
        FlexibleTileWand.Reload();
        GlobalList<GlobalItem>.Reset();
        modHooks.Clear();
        UpdateHookLists();
    }
References Terraria.ID.ItemID.Count, Terraria.ModLoader.ItemLoader.ItemCount, Terraria.ModLoader.ItemLoader.items, Terraria.ModLoader.ItemLoader.modHooks, Terraria.GameContent.FlexibleTileWand.Reload(), and Terraria.ModLoader.ItemLoader.UpdateHookLists().
Referenced by Terraria.ModLoader.ModContent.Unload().