TModLoader: Terraria.ModLoader.ItemLoader.ConsumeItem
ConsumeItem()
static bool Terraria.ModLoader.ItemLoader.ConsumeItem (Item item, Player player) inline static
If ModItem.ConsumeItem or any of the GlobalItem.ConsumeItem hooks returns false, sets consume to false.
Definition at line 1409 of file ItemLoader.cs.
    {
        if (item.IsAir)
        {
            return true;
        }
        if (item.ModItem != null && !item.ModItem.ConsumeItem(player))
        {
            return false;
        }
        EntityGlobalsEnumerator<GlobalItem> enumerator = HookConsumeItem.Enumerate(item).GetEnumerator();
        while (enumerator.MoveNext())
        {
            if (!enumerator.Current.ConsumeItem(item, player))
            {
                return false;
            }
        }
        OnConsumeItem(item, player);
        return true;
    }
References Terraria.ModLoader.ItemLoader.HookConsumeItem, Terraria.Item.IsAir, Terraria.Item.ModItem, and Terraria.ModLoader.ItemLoader.OnConsumeItem().
Referenced by Terraria.Player.ApplyPaint(), Terraria.Player.ConsumeItem(), Terraria.Player.ItemCheck_Inner(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_Walls_FillEmptySpace(), Terraria.Player.QuickBuff(), Terraria.Player.QuickHeal(), Terraria.Player.QuickMana(), Terraria.ModLoader.ItemLoader.RightClick(), Terraria.Player.TakeUnityPotion(), Terraria.Player.TileInteractionsUse(), and Terraria.UI.ItemSlot.TryOpenContainer().