TModLoader: Terraria.ModLoader.ItemLoader.CanAccessoryBeEquippedWith
CanAccessoryBeEquippedWith() [1/2]
static bool Terraria.ModLoader.ItemLoader.CanAccessoryBeEquippedWith (Item equippedItem, Item incomingItem) inline static
    {
        Player player = Main.player[Main.myPlayer];
        if (CanAccessoryBeEquippedWith(equippedItem, incomingItem, player))
        {
            return CanAccessoryBeEquippedWith(incomingItem, equippedItem, player);
        }
        return false;
    }
References Terraria.ModLoader.ItemLoader.CanAccessoryBeEquippedWith(), Terraria.Main.myPlayer, and Terraria.Main.player.
Referenced by Terraria.UI.ItemSlot.AccCheck_ForLocalPlayer(), Terraria.UI.ItemSlot.AccessorySwap(), Terraria.ModLoader.ItemLoader.CanAccessoryBeEquippedWith(), and Terraria.UI.ItemSlot.SwapVanityEquip().