TModLoader: Terraria.ModLoader.ItemLoader.TryStackItems
TryStackItems()
static bool Terraria.ModLoader.ItemLoader.TryStackItems (Item destination, Item source, out int numTransferred, bool infiniteSource = false) inline static
Stacks source onto destination if CanStack permits the transfer.
Parameters
destination The item instance that source will attempt to stack onto
source The item instance being stacked onto destination
numTransferred The quantity of source that was transferred to destination
infiniteSource If true, source .stack will not be decreased
Returns
Whether or not the items were allowed to stack
Definition at line 1846 of file ItemLoader.cs.
    {
        numTransferred = 0;
        if (!CanStack(destination, source))
        {
            return false;
        }
        StackItems(destination, source, out numTransferred, infiniteSource);
        return true;
    }
References Terraria.ModLoader.ItemLoader.CanStack(), and Terraria.ModLoader.ItemLoader.StackItems().
Referenced by Terraria.UI.ChestUI.DepositAll(), Terraria.Player.FillAmmo(), Terraria.Player.GetItem_FillIntoOccupiedSlot(), Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag(), Terraria.UI.ItemSlot.LeftClick(), Terraria.Chest.PutItemInNearbyChest(), Terraria.UI.ChestUI.QuickStack(), Terraria.UI.ItemSorting.RefillItemStack(), Terraria.UI.ChestUI.Restock(), and Terraria.UI.ItemSorting.Sort().