TModLoader: Terraria.ModLoader.ItemLoader.GetItem
GetItem()
static ModItem Terraria.ModLoader.ItemLoader.GetItem (int type) inline static
Gets the ModItem template instance corresponding to the specified type (not the clone/new instance which gets added to Items as the game is played). Returns null if no modded item has the given type.
    {
        if (type < ItemID.Count || type >= ItemCount)
        {
            return null;
        }
        return items[type - ItemID.Count];
    }
References Terraria.ID.ItemID.Count, Terraria.ModLoader.ItemLoader.ItemCount, and Terraria.ModLoader.ItemLoader.items.
Referenced by Terraria.ModLoader.MusicLoader.AddMusicBox(), Terraria.ModLoader.ItemLoader.AnglerChat(), Terraria.ModLoader.ItemLoader.ExtractinatorUse(), Terraria.ModLoader.ModContent.GetModItem(), Terraria.ModLoader.Config.UI.ItemDefinitionElement.GetPassedOptionElements(), Terraria.ModLoader.ItemLoader.HoldoutOffset(), Terraria.ModLoader.ItemLoader.IsAnglerQuestAvailable(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.ModLoader.IO.WorldIO.SaveAnglerQuest(), Terraria.ModLoader.IO.TileIO.SaveContainers(), Terraria.ModLoader.IO.PlayerIO.SaveHairDye(), Terraria.ModLoader.IO.PlayerIO.SaveResearch(), and Terraria.ModLoader.ItemLoader.SetDefaults().