TModLoader: Terraria.ModLoader.ItemLoader.ModifyTooltips
ModifyTooltips()
static List< TooltipLine > Terraria.ModLoader.ItemLoader.ModifyTooltips (Item item, ref int numTooltips, string[] names, ref string[] text, ref bool[] modifier, ref bool[] badModifier, ref int oneDropLogo, out Color?[] overrideColor, int prefixlineIndex) inline static
Definition at line 2514 of file ItemLoader.cs.
    {
        List<TooltipLine> tooltips = new List<TooltipLine>();
        for (int j = 0; j < numTooltips; j++)
        {
            TooltipLine tooltip = new TooltipLine(names[j], text[j]);
            tooltip.IsModifier = modifier[j];
            tooltip.IsModifierBad = badModifier[j];
            if (j == oneDropLogo)
            {
                tooltip.OneDropLogo = true;
            }
            tooltips.Add(tooltip);
        }
        if (item.prefix >= PrefixID.Count && prefixlineIndex != -1)
        {
            IEnumerable<TooltipLine> tooltipLines = PrefixLoader.GetPrefix(item.prefix)?.GetTooltipLines(item);
            if (tooltipLines != null)
            {
                foreach (TooltipLine line in tooltipLines)
                {
                    tooltips.Insert(prefixlineIndex, line);
                    prefixlineIndex++;
                }
            }
        }
        item.ModItem?.ModifyTooltips(tooltips);
        if (!item.IsAir)
        {
            EntityGlobalsEnumerator<GlobalItem> enumerator2 = HookModifyTooltips.Enumerate(item).GetEnumerator();
            while (enumerator2.MoveNext())
            {
                enumerator2.Current.ModifyTooltips(item, tooltips);
            }
        }
        tooltips.RemoveAll((TooltipLine x) => !x.Visible);
        numTooltips = tooltips.Count;
        text = new string[numTooltips];
        modifier = new bool[numTooltips];
        badModifier = new bool[numTooltips];
        oneDropLogo = -1;
        overrideColor = new Color?[numTooltips];
        for (int i = 0; i < numTooltips; i++)
        {
            text[i] = tooltips[i].Text;
            modifier[i] = tooltips[i].IsModifier;
            badModifier[i] = tooltips[i].IsModifierBad;
            if (tooltips[i].OneDropLogo)
            {
                oneDropLogo = i;
            }
            overrideColor[i] = tooltips[i].OverrideColor;
        }
        return tooltips;
    }
References Terraria.ID.PrefixID.Count, Terraria.ModLoader.PrefixLoader.GetPrefix(), Terraria.ModLoader.ItemLoader.HookModifyTooltips, Terraria.Item.IsAir, Terraria.Item.ModItem, Terraria.Item.prefix, and Terraria.ModLoader.TooltipLine.Visible.
Referenced by Terraria.GameContent.Creative.ItemFilters.BySearch.FitsFilter(), and Terraria.Main.MouseText_DrawItemTooltip().