TModLoader: Terraria.ModLoader.ItemLoader.StackItems
StackItems()
static void Terraria.ModLoader.ItemLoader.StackItems (Item destination, Item source, out int numTransferred, bool infiniteSource = false, int? numToTransfer = null) inline static
Stacks destination onto source
This method should not be called unless M:Terraria.ModLoader.ItemLoader.CanStack(Terraria.Item,Terraria.Item) returns true. See: M:Terraria.ModLoader.ItemLoader.TryStackItems(Terraria.Item,Terraria.Item,System.Int32@,System.Boolean)
Parameters
destination The item instance that source will attempt to stack onto
source The item instance being stacked onto destination
numTransferred The quantity of source that was transferred to destination
infiniteSource If true, source .stack will not be decreased
numToTransfer An optional argument used to specify the quantity of items to transfer from source to destination .
By default, as many items as possible will be transferred. That is, either source will be empty, or destination will be full (maxStack)
Definition at line 1869 of file ItemLoader.cs.
    {
        numTransferred = numToTransfer ?? Math.Min(source.stack, destination.maxStack - destination.stack);
        OnStack(destination, source, numTransferred);
        bool isSplittingToHand = numTransferred < source.stack && destination == Main.mouseItem;
        if (source.favorited && !isSplittingToHand)
        {
            destination.favorited = true;
            source.favorited = false;
        }
        destination.stack += numTransferred;
        if (!infiniteSource)
        {
            source.stack -= numTransferred;
        }
    }
References Terraria.Item.favorited, Terraria.Main.mouseItem, Terraria.ModLoader.ItemLoader.OnStack(), and Terraria.Item.stack.
Referenced by Terraria.Item.CombineWithNearbyItems(), Terraria.Main.CraftItem(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.UI.ItemSlot.PickupItemIntoMouse(), Terraria.UI.ItemSlot.TryPickupDyeToCursor(), Terraria.UI.ChestUI.TryPlacingInChest(), and Terraria.ModLoader.ItemLoader.TryStackItems().