TModLoader: Terraria.ModLoader.ItemLoader.CanStack
CanStack()
static bool Terraria.ModLoader.ItemLoader.CanStack (Item destination, Item source) inline static
Returns false if item prefixes don't match. Then calls all GlobalItem.CanStack hooks until one returns false then ModItem.CanStack. Returns whether any of the hooks returned false.
Parameters
destination The item instance that source will attempt to stack onto
source The item instance being stacked onto destination
Returns
Whether or not the items are allowed to stack
Definition at line 1802 of file ItemLoader.cs.
    {
        if (destination.prefix != source.prefix)
        {
            return false;
        }
        EntityGlobalsEnumerator<GlobalItem> enumerator = HookCanStack.Enumerate(destination).GetEnumerator();
        while (enumerator.MoveNext())
        {
            if (!enumerator.Current.CanStack(destination, source))
            {
                return false;
            }
        }
        return destination.ModItem?.CanStack(source) ?? true;
    }
References Terraria.ModLoader.ItemLoader.HookCanStack, and Terraria.Item.prefix.
Referenced by Terraria.Player.CanItemSlotAccept(), Terraria.Item.CombineWithNearbyItems(), Terraria.Main.CraftItem(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.Initializers.UILinksInitializer.Load(), Terraria.UI.ItemSlot.RightClick(), Terraria.UI.ItemSlot.TryPickupDyeToCursor(), Terraria.UI.ChestUI.TryPlacingInChest(), and Terraria.ModLoader.ItemLoader.TryStackItems().