TModLoader: Terraria.ModLoader.ItemLoader.SetDefaults
SetDefaults()
static void Terraria.ModLoader.ItemLoader.SetDefaults (Item item, bool createModItem = true) inline static package
Definition at line 490 of file ItemLoader.cs.
    {
        if (IsModItem(item.type) && createModItem)
        {
            item.ModItem = GetItem(item.type).NewInstance(item);
        }
        GlobalLoaderUtils<GlobalItem, Item>.SetDefaults(item, ref item._globals, delegate(Item i)
        {
            i.ModItem?.AutoDefaults();
            i.ModItem?.SetDefaults();
        });
    }
References Terraria.Item._globals, Terraria.ModLoader.ItemLoader.GetItem(), Terraria.ModLoader.ItemLoader.IsModItem(), Terraria.Item.ModItem, and Terraria.Item.type.
Referenced by Terraria.ModLoader.ItemLoader.FinishSetup(), Terraria.Item.SetDefaults(), and Terraria.ModLoader.ModItem.SetupContent().