TModLoader: Terraria.ModLoader.ItemLoader.TransferWithLimit
TransferWithLimit()
static Item Terraria.ModLoader.ItemLoader.TransferWithLimit (Item source, int limit) inline static
Extract up to limit items from source . If some items remain, M:Terraria.ModLoader.ItemLoader.SplitStack(Terraria.Item,Terraria.Item,System.Int32) will be used.
Parameters
source The original item instance
limit How many items should be transferred
Definition at line 1908 of file ItemLoader.cs.
    {
        Item destination = source.Clone();
        if (source.stack <= limit)
        {
            source.TurnToAir();
        }
        else
        {
            SplitStack(destination, source, limit);
        }
        return destination;
    }
References Terraria.Item.Clone(), Terraria.ModLoader.ItemLoader.SplitStack(), Terraria.Item.stack, and Terraria.Item.TurnToAir().
Referenced by Terraria.UI.ItemSlot.LeftClick(), Terraria.UI.ItemSlot.PickupItemIntoMouse(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing(), and Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing().