TModLoader: Terraria.ModLoader.ItemLoader.ResizeArrays
ResizeArrays()
static void Terraria.ModLoader.ItemLoader.ResizeArrays (bool unloading) inline static package
    {
        if (!unloading)
        {
            GlobalList<GlobalItem>.FinishLoading(ItemCount);
        }
        Array.Resize(ref TextureAssets.Item, ItemCount);
        Array.Resize(ref TextureAssets.ItemFlame, ItemCount);
        LoaderUtils.ResetStaticMembers(typeof(ItemID));
        LoaderUtils.ResetStaticMembers(typeof(AmmoID));
        LoaderUtils.ResetStaticMembers(typeof(PrefixLegacy.ItemSets));
        Array.Resize(ref Item.cachedItemSpawnsByType, ItemCount);
        Array.Resize(ref Item.staff, ItemCount);
        Array.Resize(ref Item.claw, ItemCount);
        Array.Resize(ref Lang._itemNameCache, ItemCount);
        Array.Resize(ref Lang._itemTooltipCache, ItemCount);
        Array.Resize(ref RecipeLoader.FirstRecipeForItem, ItemCount);
        for (int i = ItemID.Count; i < ItemCount; i++)
        {
            Lang._itemNameCache[i] = LocalizedText.Empty;
            Lang._itemTooltipCache[i] = ItemTooltip.None;
            Item.cachedItemSpawnsByType[i] = -1;
        }
        lock (Main.itemAnimationsRegistered)
        {
            Array.Resize(ref Main.itemAnimations, ItemCount);
            Main.InitializeItemAnimations();
        }
        if (unloading)
        {
            Array.Resize(ref Main.anglerQuestItemNetIDs, vanillaQuestFishCount);
            return;
        }
        Main.anglerQuestItemNetIDs = Main.anglerQuestItemNetIDs.Concat(from modItem in items
            where modItem.IsQuestFish()
            select modItem.Type).ToArray();
    }
References Terraria.Lang._itemNameCache, Terraria.Lang._itemTooltipCache, Terraria.Main.anglerQuestItemNetIDs, Terraria.Item.cachedItemSpawnsByType, Terraria.Item.claw, Terraria.ID.ItemID.Count, Terraria.Localization.LocalizedText.Empty, Terraria.ModLoader.RecipeLoader.FirstRecipeForItem, Terraria.Main.InitializeItemAnimations(), Terraria.GameContent.TextureAssets.Item, Terraria.Main.itemAnimations, Terraria.Main.itemAnimationsRegistered, Terraria.ModLoader.ItemLoader.ItemCount, Terraria.GameContent.TextureAssets.ItemFlame, Terraria.ModLoader.ItemLoader.items, Terraria.UI.ItemTooltip.None, Terraria.ModLoader.Core.LoaderUtils.ResetStaticMembers(), Terraria.Item.staff, and Terraria.ModLoader.ItemLoader.vanillaQuestFishCount.
Referenced by Terraria.ModLoader.ModContent.ResizeArrays().