TModLoader: Terraria.Net.Sockets.TcpSocket.AsyncSend
AsyncSend()
void ISocket. Terraria.Net.Sockets.TcpSocket.AsyncSend (byte[] data, int offset, int size, SocketSendCallback callback, object state) inline private
Implements Terraria.Net.Sockets.ISocket.
Definition at line 118 of file TcpSocket.cs.
    {
        if (!_connection.Connected)
        {
            ModNet.Warn("TcpSocket, AsyncSend after connection closed.");
            return;
        }
        if (ModNet.DetailedLogging)
        {
            ModNet.Debug(_remoteAddress, $"send {size}");
        }
        state = (state, size);
        if (!Platform.IsWindows)
        {
            byte[] array = LegacyNetBufferPool.RequestBuffer(data, offset, size);
            _connection.GetStream().BeginWrite(array, 0, size, SendCallback, new object[2]
            {
                new Tuple<SocketSendCallback, object>(callback, state),
                array
            });
        }
        else
        {
            _connection.GetStream().BeginWrite(data, 0, size, SendCallback, new Tuple<SocketSendCallback, object>(callback, state));
        }
    }
References Terraria.Net.Sockets.TcpSocket._connection, Terraria.Net.Sockets.TcpSocket._remoteAddress, Terraria.ModLoader.ModNet.Debug(), Terraria.ModLoader.ModNet.DetailedLogging, Terraria.Net.LegacyNetBufferPool.RequestBuffer(), Terraria.Net.Sockets.TcpSocket.SendCallback(), and Terraria.ModLoader.ModNet.Warn().