TModLoader: Terraria.Net.Sockets.TcpSocket.SendCallback
SendCallback()
void Terraria.Net.Sockets.TcpSocket.SendCallback (IAsyncResult result) inline private
    {
        Tuple<SocketSendCallback, object> tuple;
        if (Platform.IsWindows)
        {
            tuple = (Tuple<SocketSendCallback, object>)result.AsyncState;
        }
        else
        {
            object[] obj = (object[])result.AsyncState;
            LegacyNetBufferPool.ReturnBuffer((byte[])obj[1]);
            tuple = (Tuple<SocketSendCallback, object>)obj[0];
        }
        (object, int) obj2 = ((object, int))tuple.Item2;
        object state = obj2.Item1;
        int size = obj2.Item2;
        tuple = Tuple.Create(tuple.Item1, state);
        if (ModNet.DetailedLogging)
        {
            ModNet.Debug(_remoteAddress, $"sent {size}");
        }
        try
        {
            if (_connection.Connected)
            {
                _connection.GetStream().EndWrite(result);
                tuple.Item1(tuple.Item2);
            }
        }
        catch (Exception)
        {
            ((ISocket)this).Close();
        }
    }
References Terraria.Net.Sockets.TcpSocket._connection, Terraria.Net.Sockets.TcpSocket._remoteAddress, Terraria.ModLoader.ModNet.Debug(), Terraria.ModLoader.ModNet.DetailedLogging, and Terraria.Net.LegacyNetBufferPool.ReturnBuffer().
Referenced by Terraria.Net.Sockets.TcpSocket.AsyncSend().