TModLoader: Terraria.GameContent.Biomes.MarbleBiome.Place
Place()
override bool Terraria.GameContent.Biomes.MarbleBiome.Place (Point origin, StructureMap structures) inline
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_037d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0383: Unknown result type (might be due to invalid IL or missing references)
        //IL_038f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0343: Unknown result type (might be due to invalid IL or missing references)
        //IL_034e: Unknown result type (might be due to invalid IL or missing references)
        if (WorldGen.BiomeTileCheck(origin.X, origin.Y))
        {
            return false;
        }
        if (_slabs == null)
        {
            _slabs = new Slab[56, 26];
        }
        int num = GenBase._random.Next(80, 150) / 3;
        int num6 = GenBase._random.Next(40, 60) / 3;
        int num7 = (num6 * 3 - GenBase._random.Next(20, 30)) / 3;
        origin.X -= num * 3 / 2;
        origin.Y -= num6 * 3 / 2;
        for (int i = -1; i < num + 1; i++)
        {
            double num8 = (double)(i - num / 2) / (double)num + 0.5;
            int num9 = (int)((0.5 - Math.Abs(num8 - 0.5)) * 5.0) - 2;
            for (int j = -1; j < num6 + 1; j++)
            {
                bool hasWall = true;
                bool flag = false;
                bool flag2 = IsGroupSolid(i * 3 + origin.X, j * 3 + origin.Y, 3);
                int num10 = Math.Abs(j - num6 / 2) - num7 / 4 + num9;
                if (num10 > 3)
                {
                    flag = flag2;
                    hasWall = false;
                }
                else if (num10 > 0)
                {
                    flag = j - num6 / 2 > 0 || flag2;
                    hasWall = j - num6 / 2 < 0 || num10 <= 2;
                }
                else if (num10 == 0)
                {
                    flag = GenBase._random.Next(2) == 0 && (j - num6 / 2 > 0 || flag2);
                }
                if (Math.Abs(num8 - 0.5) > 0.35 + GenBase._random.NextDouble() * 0.1 && !flag2)
                {
                    hasWall = false;
                    flag = false;
                }
                _slabs[i + 1, j + 1] = Slab.Create(flag ? new SlabState(SlabStates.Solid) : new SlabState(SlabStates.Empty), hasWall);
            }
        }
        for (int k = 0; k < num; k++)
        {
            for (int l = 0; l < num6; l++)
            {
                SmoothSlope(k + 1, l + 1);
            }
        }
        int num11 = num / 2;
        int num12 = num6 / 2;
        int num13 = (num12 + 1) * (num12 + 1);
        double value = GenBase._random.NextDouble() * 2.0 - 1.0;
        double num2 = GenBase._random.NextDouble() * 2.0 - 1.0;
        double value2 = GenBase._random.NextDouble() * 2.0 - 1.0;
        double num3 = 0.0;
        for (int m = 0; m <= num; m++)
        {
            double num4 = (double)num12 / (double)num11 * (double)(m - num11);
            int num5 = Math.Min(num12, (int)Math.Sqrt(Math.Max(0.0, (double)num13 - num4 * num4)));
            num3 = ((m >= num / 2) ? (num3 + Utils.Lerp(num2, value2, (double)m / (double)(num / 2) - 1.0)) : (num3 + Utils.Lerp(value, num2, (double)m / (double)(num / 2))));
            for (int n = num12 - num5; n <= num12 + num5; n++)
            {
                PlaceSlab(_slabs[m + 1, n + 1], m * 3 + origin.X, n * 3 + origin.Y + (int)num3, 3);
            }
        }
        structures.AddStructure(new Rectangle(origin.X, origin.Y, num * 3, num6 * 3), 8);
        return true;
    }
References Terraria.WorldBuilding.GenBase._random, Terraria.GameContent.Biomes.MarbleBiome._slabs, Terraria.WorldBuilding.StructureMap.AddStructure(), Terraria.WorldGen.BiomeTileCheck(), Terraria.GameContent.Biomes.MarbleBiome.Slab.Create(), Terraria.GameContent.Biomes.MarbleBiome.SlabStates.Empty(), Terraria.GameContent.Biomes.MarbleBiome.IsGroupSolid(), Terraria.Utils.Lerp(), Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab(), Terraria.GameContent.Biomes.MarbleBiome.SlabState(), Terraria.GameContent.Biomes.MarbleBiome.SmoothSlope(), and Terraria.GameContent.Biomes.MarbleBiome.SlabStates.Solid().