TModLoader: Terraria.ModLoader.ModPylon.DefaultDrawPylonCrystal
DefaultDrawPylonCrystal() [1/2]
void Terraria.ModLoader.ModPylon.DefaultDrawPylonCrystal (SpriteBatch spriteBatch, int i, int j, Asset< Texture2D > crystalTexture, Asset< Texture2D > crystalHighlightTexture, Vector2 crystalOffset, Color pylonShadowColor, Color dustColor, int dustChanceDenominator, int crystalVerticalFrameCount) inline
Draws the passed in pylon crystal texture the exact way that vanilla draws it. This MUST be called in SpecialDraw in order to function properly.
Parameters
spriteBatch The sprite batch that will draw the crystal.
i The X tile coordinate to start drawing from.
j The Y tile coordinate to start drawing from.
crystalTexture The texture of the crystal that will actually be drawn.
crystalHighlightTexture The texture of the smart cursor highlight for the corresponding crystal texture.
crystalOffset The offset of the actual position of the crystal. Assuming that a pylon tile itself and the crystals are equivalent to vanilla's sizes, this value should be Vector2(0, -12).
pylonShadowColor The color of the "shadow" that is drawn on top of the crystal texture.
dustColor The color of the dust that emanates from the crystal.
dustChanceDenominator Every draw call, this is this the denominator value of a Main.rand.NextBool() (1/denominator chance) check for whether or not a dust particle will spawn. 4 is the value vanilla uses.
crystalVerticalFrameCount How many vertical frames the crystal texture has.
    {
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_006e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_0220: Unknown result type (might be due to invalid IL or missing references)
        //IL_0222: Unknown result type (might be due to invalid IL or missing references)
        //IL_0227: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0233: Unknown result type (might be due to invalid IL or missing references)
        //IL_023a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0280: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0305: Unknown result type (might be due to invalid IL or missing references)
        //IL_0176: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0351: Unknown result type (might be due to invalid IL or missing references)
        //IL_035b: Unknown result type (might be due to invalid IL or missing references)
        //IL_035d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0362: Unknown result type (might be due to invalid IL or missing references)
        //IL_0367: Unknown result type (might be due to invalid IL or missing references)
        //IL_036e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0375: Unknown result type (might be due to invalid IL or missing references)
        Vector2 offscreenVector = default(Vector2);
        ((Vector2)(ref offscreenVector))._002Ector((float)Main.offScreenRange);
        if (Main.drawToScreen)
        {
            offscreenVector = Vector2.Zero;
        }
        Point point = default(Point);
        ((Point)(ref point))._002Ector(i, j);
        Tile tile = Main.tile[point.X, point.Y];
        if (tile == null || !tile.HasTile)
        {
            return;
        }
        TileObjectData tileData = TileObjectData.GetTileData(tile);
        int frameY = Main.tileFrameCounter[597] / crystalVerticalFrameCount;
        Rectangle crystalFrame = crystalTexture.Frame(1, crystalVerticalFrameCount, 0, frameY);
        Rectangle smartCursorGlowFrame = crystalHighlightTexture.Frame(1, crystalVerticalFrameCount, 0, frameY);
        crystalFrame.Height--;
        smartCursorGlowFrame.Height--;
        Vector2 origin = crystalFrame.Size() / 2f;
        Vector2 tileOrigin = default(Vector2);
        ((Vector2)(ref tileOrigin))._002Ector((float)tileData.CoordinateFullWidth / 2f, (float)tileData.CoordinateFullHeight / 2f);
        Vector2 crystalPosition = point.ToWorldCoordinates(tileOrigin.X - 2f, tileOrigin.Y) + crystalOffset;
        float sinusoidalOffset = (float)Math.Sin((double)Main.GlobalTimeWrappedHourly * (Math.PI * 2.0) / 5.0);
        Vector2 drawingPosition = crystalPosition + offscreenVector + new Vector2(0f, sinusoidalOffset * 4f);
        if (!Main.gamePaused && ((Game)Main.instance).IsActive && (!Lighting.UpdateEveryFrame || Main.rand.NextBool(4)) && Main.rand.NextBool(dustChanceDenominator))
        {
            Rectangle dustBox = Utils.CenteredRectangle(crystalPosition, crystalFrame.Size());
            int numForDust = Dust.NewDust(dustBox.TopLeft(), dustBox.Width, dustBox.Height, 43, 0f, 0f, 254, dustColor, 0.5f);
            Dust obj = Main.dust[numForDust];
            obj.velocity *= 0.1f;
            Main.dust[numForDust].velocity.Y -= 0.2f;
        }
        Color color = Lighting.GetColor(point.X, point.Y);
        color = Color.Lerp(color, Color.White, 0.8f);
        spriteBatch.Draw(crystalTexture.Value, drawingPosition - Main.screenPosition, (Rectangle?)crystalFrame, color * 0.7f, 0f, origin, 1f, (SpriteEffects)0, 0f);
        float scale = (float)Math.Sin(Main.GlobalTimeWrappedHourly * ((float)Math.PI * 2f) / 1f) * 0.2f + 0.8f;
        Color shadowColor = pylonShadowColor * scale;
        for (float shadowPos = 0f; shadowPos < 1f; shadowPos += 1f / 6f)
        {
            spriteBatch.Draw(crystalTexture.Value, drawingPosition - Main.screenPosition + ((float)Math.PI * 2f * shadowPos).ToRotationVector2() * (6f + sinusoidalOffset * 2f), (Rectangle?)crystalFrame, shadowColor, 0f, origin, 1f, (SpriteEffects)0, 0f);
        }
        int selectionLevel = 0;
        if (Main.InSmartCursorHighlightArea(point.X, point.Y, out var actuallySelected))
        {
            selectionLevel = 1;
            if (actuallySelected)
            {
                selectionLevel = 2;
            }
        }
        if (selectionLevel != 0)
        {
            int averageBrightness = (((Color)(ref color)).R + ((Color)(ref color)).G + ((Color)(ref color)).B) / 3;
            if (averageBrightness > 10)
            {
                Color selectionGlowColor = Colors.GetSelectionGlowColor(selectionLevel == 2, averageBrightness);
                spriteBatch.Draw(crystalHighlightTexture.Value, drawingPosition - Main.screenPosition, (Rectangle?)smartCursorGlowFrame, selectionGlowColor, 0f, origin, 1f, (SpriteEffects)0, 0f);
            }
        }
    }
References Terraria.Utils.CenteredRectangle(), Terraria.Main.drawToScreen, Terraria.Main.dust, Terraria.Main.gamePaused, Terraria.Lighting.GetColor(), Terraria.ID.Colors.GetSelectionGlowColor(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Tile.HasTile, Terraria.Main.InSmartCursorHighlightArea(), Terraria.Main.instance, Terraria.Dust.NewDust(), Terraria.Main.offScreenRange, Terraria.Main.rand, Terraria.Main.screenPosition, Terraria.Main.tile, Terraria.Main.tileFrameCounter, Terraria.Lighting.UpdateEveryFrame, and Terraria.Dust.velocity.