TModLoader: Terraria.ModLoader.ModPylon.TileFrame
TileFrame()
override bool Terraria.ModLoader.ModPylon.TileFrame (int i, int j, ref bool resetFrame, ref bool noBreak) inline virtual
Called whenever this tile updates due to being placed or being next to a tile that is changed. Return false to stop the game from carrying out its default TileFrame operations. Returns true by default.
Parameters
i The x position in tile coordinates.
j The y position in tile coordinates.
resetFrame
noBreak
Reimplemented from Terraria.ModLoader.ModTile.
    {
        if (WorldGen.destroyObject)
        {
            return false;
        }
        int topLeftX = i;
        int topLeftY = j;
        Tile tileSafely = Framing.GetTileSafely(i, j);
        TileObjectData tileData = TileObjectData.GetTileData(tileSafely);
        bool shouldBreak = false;
        topLeftX -= tileSafely.frameX / tileData.CoordinateWidth % tileData.Width;
        topLeftY -= tileSafely.frameY / 18 % tileData.Height;
        int rightX = topLeftX + tileData.Width;
        int bottomY = topLeftY + tileData.Height;
        for (int x3 = topLeftX; x3 < rightX; x3++)
        {
            for (int y2 = topLeftY; y2 < bottomY; y2++)
            {
                Tile tile2 = Main.tile[x3, y2];
                if (!tile2.HasTile || tile2.type != base.Type)
                {
                    shouldBreak = true;
                    break;
                }
            }
        }
        for (int x2 = topLeftX; x2 < rightX; x2++)
        {
            if (!WorldGen.SolidTileAllowBottomSlope(x2, bottomY))
            {
                shouldBreak = true;
                break;
            }
        }
        if (!shouldBreak)
        {
            noBreak = true;
            return true;
        }
        WorldGen.KillTile_DropItems(i, j, tileSafely, includeLargeObjectDrops: true, includeAllModdedLargeObjectDrops: true);
        KillMultiTile(topLeftX, topLeftY, tileSafely.TileFrameX, tileSafely.TileFrameY);
        WorldGen.destroyObject = true;
        for (int x = topLeftX; x < rightX; x++)
        {
            for (int y = topLeftY; y < bottomY; y++)
            {
                Tile tile = Main.tile[x, y];
                if (tile.HasTile && tile.TileType == base.Type)
                {
                    WorldGen.KillTile(x, y);
                }
            }
        }
        WorldGen.destroyObject = false;
        return true;
    }
References Terraria.WorldGen.destroyObject, Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Framing.GetTileSafely(), Terraria.Tile.HasTile, Terraria.ModLoader.ModTile.KillMultiTile(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_DropItems(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, and Terraria.Tile.TileType.