TModLoader: Terraria.WaterfallManager.Draw
Draw()
void Terraria.WaterfallManager.Draw (SpriteBatch spriteBatch) inline
    {
        for (int i = 0; i < currentMax; i++)
        {
            waterfalls[i].stopAtStep = waterfallDist;
        }
        Main.drewLava = false;
        if (Main.liquidAlpha[0] > 0f)
        {
            DrawWaterfall(0, Main.liquidAlpha[0]);
        }
        if (Main.liquidAlpha[2] > 0f)
        {
            DrawWaterfall(3, Main.liquidAlpha[2]);
        }
        if (Main.liquidAlpha[3] > 0f)
        {
            DrawWaterfall(4, Main.liquidAlpha[3]);
        }
        if (Main.liquidAlpha[4] > 0f)
        {
            DrawWaterfall(5, Main.liquidAlpha[4]);
        }
        if (Main.liquidAlpha[5] > 0f)
        {
            DrawWaterfall(6, Main.liquidAlpha[5]);
        }
        if (Main.liquidAlpha[6] > 0f)
        {
            DrawWaterfall(7, Main.liquidAlpha[6]);
        }
        if (Main.liquidAlpha[7] > 0f)
        {
            DrawWaterfall(8, Main.liquidAlpha[7]);
        }
        if (Main.liquidAlpha[8] > 0f)
        {
            DrawWaterfall(9, Main.liquidAlpha[8]);
        }
        if (Main.liquidAlpha[9] > 0f)
        {
            DrawWaterfall(10, Main.liquidAlpha[9]);
        }
        if (Main.liquidAlpha[10] > 0f)
        {
            DrawWaterfall(13, Main.liquidAlpha[10]);
        }
        if (Main.liquidAlpha[12] > 0f)
        {
            DrawWaterfall(23, Main.liquidAlpha[12]);
        }
        if (Main.liquidAlpha[13] > 0f)
        {
            DrawWaterfall(24, Main.liquidAlpha[13]);
        }
        LoaderManager.Get<WaterStylesLoader>().DrawWaterfall(this);
    }
References Terraria.WaterfallManager.currentMax, Terraria.WaterfallManager.DrawWaterfall(), Terraria.Main.liquidAlpha, Terraria.WaterfallManager.WaterfallData.stopAtStep, Terraria.WaterfallManager.waterfallDist, and Terraria.WaterfallManager.waterfalls.
Referenced by Terraria.Main.DoDraw_Waterfalls(), and Terraria.Main.DrawCapture().