TModLoader: Terraria.ModLoader.Logging.FirstChanceExceptionHandler
FirstChanceExceptionHandler()
static void Terraria.ModLoader.Logging.FirstChanceExceptionHandler (object sender, FirstChanceExceptionEventArgs args) inline static private
Definition at line 380 of file Logging.cs.
    {
        if (quietExceptionCount > 0)
        {
            return;
        }
        using (new QuietExceptionHandle())
        {
            bool oom = args.Exception is OutOfMemoryException;
            if (oom)
            {
                TryFreeingMemory();
            }
            try
            {
                if (!oom && (args.Exception == previousException || args.Exception is ThreadAbortException || ignoreTypes.Contains(args.Exception.GetType().FullName) || ignoreSources.Contains(args.Exception.Source) || ignoreMessages.Any((string str) => args.Exception.Message?.Contains(str) ?? false) || ignoreThrowingMethods.Any((string str) => args.Exception.StackTrace?.Contains(str) ?? false)))
                {
                    return;
                }
                StackTrace stackTrace = new StackTrace(1, fNeedFileInfo: true);
                string traceString = stackTrace.ToString();
                if (!oom && ignoreContents.Any((string s) => MatchContents(traceString, s)))
                {
                    return;
                }
                traceString = stackTrace.ToString();
                string text = traceString;
                int num = traceString.IndexOf('\n');
                traceString = text.Substring(num, text.Length - num);
                string exString = args.Exception.GetType()?.ToString() + ": " + args.Exception.Message + traceString;
                lock (pastExceptions)
                {
                    if (!pastExceptions.Add(exString))
                    {
                        return;
                    }
                }
                tML.Warn((object)(Language.GetTextValue("tModLoader.RuntimeErrorSilentlyCaughtException") + "\n" + exString));
                previousException = args.Exception;
                string msg = args.Exception.Message + " " + Language.GetTextValue("tModLoader.RuntimeErrorSeeLogsForFullTrace", Path.GetFileName(LogPath));
                if (Program.SavePathShared == null || Main.dedServ)
                {
                    Console.ForegroundColor = ConsoleColor.DarkMagenta;
                    Console.WriteLine(msg);
                    Console.ResetColor();
                }
                else if (Program.SavePathShared != null && ModCompile.activelyModding && !Main.gameMenu)
                {
                    AddChatMessage(msg);
                }
                if (oom)
                {
                    ErrorReporting.FatalExit(Language.GetTextValue("tModLoader.OutOfMemory"));
                }
            }
            catch (Exception e)
            {
                tML.Warn((object)"FirstChanceExceptionHandler exception", e);
            }
        }
    }
References Terraria.ModLoader.Core.ModCompile.activelyModding, Terraria.ModLoader.Logging.AddChatMessage(), Terraria.ModLoader.Console, Terraria.Main.dedServ, Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.Main.gameMenu, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Logging.ignoreContents, Terraria.ModLoader.Logging.ignoreMessages, Terraria.ModLoader.Logging.ignoreSources, Terraria.ModLoader.Logging.ignoreThrowingMethods, Terraria.ModLoader.Logging.ignoreTypes, Terraria.ModLoader.Logging.LogPath, Terraria.ModLoader.Logging.MatchContents(), Terraria.ModLoader.Logging.pastExceptions, Terraria.ModLoader.Logging.previousException, Terraria.ModLoader.Logging.quietExceptionCount, Terraria.Program.SavePathShared, Terraria.ModLoader.Logging.tML, and Terraria.ModLoader.Logging.TryFreeingMemory().
Referenced by Terraria.ModLoader.Logging.LogFirstChanceExceptions().