TModLoader: Terraria.ModLoader.Logging.ServerConsoleLine
ServerConsoleLine() [1/2]
static void Terraria.ModLoader.Logging.ServerConsoleLine (string msg) inline static package
Definition at line 319 of file Logging.cs.
    {
        ServerConsoleLine(msg, Level.Info);
    }
References Terraria.ModLoader.Logging.ServerConsoleLine().
Referenced by Terraria.ModLoader.Core.ModOrganizer.CommandLineModPackOverride(), Terraria.Main.DedServ_PostModLoad(), Terraria.NetMessage.EnsureLocalPlayerIsPresent(), Terraria.Netplay.OnConnectionAccepted(), Terraria.ModLoader.Engine.ServerHangWatchdog.Run(), Terraria.NetMessage.SendData(), Terraria.Net.NetManager.SendData(), Terraria.ModLoader.Logging.ServerConsoleLine(), and Terraria.NetMessage.SyncOnePlayer().