TModLoader: Terraria.ModLoader.Logging.LogStartup
LogStartup()
static void Terraria.ModLoader.Logging.LogStartup (bool dedServ) inline static package
Definition at line 118 of file Logging.cs.
    {
        tML.InfoFormat("Starting tModLoader {0} {1} built {2}", (object)(dedServ ? "server" : "client"), (object)BuildInfo.BuildIdentifier, (object)$"{BuildInfo.BuildDate:g}");
        tML.InfoFormat("Log date: {0}", (object)DateTime.Now.ToString("d"));
        tML.InfoFormat("Running on {0} (v{1}) {2} {3} {4}", new object[5]
        {
            Platform.Current.Type,
            Environment.OSVersion.Version,
            RuntimeInformation.ProcessArchitecture,
            FrameworkVersion.Framework,
            FrameworkVersion.Version
        });
        tML.InfoFormat("FrameworkDescription: {0}", (object)RuntimeInformation.FrameworkDescription);
        tML.InfoFormat("Executable: {0}", (object)Assembly.GetEntryAssembly().Location);
        tML.InfoFormat("Working Directory: {0}", (object)Path.GetFullPath(Directory.GetCurrentDirectory()));
        string args2 = string.Join(' ', Environment.GetCommandLineArgs().Skip(1));
        if (!string.IsNullOrEmpty(args2) || Program.LaunchParameters.Any())
        {
            tML.InfoFormat("Launch Parameters: {0}", (object)args2);
            tML.InfoFormat("Parsed Launch Parameters: {0}", (object)string.Join(' ', Program.LaunchParameters.Select((KeyValuePair<string, string> p) => (p.Key + " " + p.Value).Trim())));
        }
        DumpEnvVars();
        string stackLimit = Environment.GetEnvironmentVariable("COMPlus_DefaultStackSize");
        if (!string.IsNullOrEmpty(stackLimit))
        {
            tML.InfoFormat("Override Default Thread Stack Size Limit: {0}", (object)stackLimit);
        }
        foreach (string line in initWarnings)
        {
            tML.Warn((object)line);
        }
        AppDomain.CurrentDomain.UnhandledException += delegate(object s, UnhandledExceptionEventArgs args)
        {
            tML.Error((object)"Unhandled Exception", args.ExceptionObject as Exception);
        };
        LogFirstChanceExceptions();
        AssemblyResolving.Init();
        LoggingHooks.Init();
        LogArchiver.ArchiveLogs();
    }
References Terraria.ModLoader.Engine.LogArchiver.ArchiveLogs(), Terraria.ModLoader.BuildInfo.BuildIdentifier, Terraria.ModLoader.Logging.DumpEnvVars(), Terraria.ModLoader.Environment, Terraria.ModLoader.FrameworkVersion.Framework, Terraria.ModLoader.Core.AssemblyResolving.Init(), Terraria.ModLoader.Engine.LoggingHooks.Init(), Terraria.ModLoader.Logging.initWarnings, Terraria.Program.LaunchParameters, Terraria.ModLoader.Logging.LogFirstChanceExceptions(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.Program.StartupSequenceTml().