TModLoader: Terraria.ModLoader.Logging.GetFreeLogFileName
GetFreeLogFileName()
static string Terraria.ModLoader.Logging.GetFreeLogFileName (List< string > baseLogNames, bool roll) inline static private
    {
        string baseLogName = baseLogNames[0];
        Regex pattern = new Regex("(?:" + string.Join('|', baseLogNames) + ")(\\d*)\\.log$");
        List<string> existingLogs = (from s in Directory.GetFiles(LogDir)
            where pattern.IsMatch(Path.GetFileName(s))
            select s).ToList();
        if (!existingLogs.All(CanOpen))
        {
            int i = existingLogs.Select(delegate(string s)
            {
                string value = pattern.Match(Path.GetFileName(s)).Groups[1].Value;
                return (value.Length == 0) ? 1 : int.Parse(value);
            }).Max();
            return $"{baseLogName}{i + 1}.log";
        }
        if (roll)
        {
            RenameToOld(existingLogs);
        }
        else if (existingLogs.Any())
        {
            IEnumerable<string> logNames = existingLogs.Select((string s) => Path.GetFileName(s));
            initWarnings.Add($"Old log files found which should have already been archived. The {baseLogName}.log will be overwritten. [{string.Join(", ", logNames)}]");
        }
        return baseLogName + ".log";
    }
References Terraria.ModLoader.Logging.CanOpen(), Terraria.ModLoader.Logging.initWarnings, Terraria.ModLoader.Logging.LogDir, and Terraria.ModLoader.Logging.RenameToOld().
Referenced by Terraria.ModLoader.Logging.InitLogPaths().