TModLoader: Terraria.ModLoader.Logging.tML
tML
ILog Terraria.ModLoader.Logging.tML = LogManager.GetLogger("tML") static get package
{ get; } = LogManager.GetLogger("tML");
Referenced by Terraria.ModLoader.Config.DefaultDictionaryKeyValueAttribute.DefaultDictionaryKeyValueAttribute(), Terraria.ModLoader.Config.DefaultListValueAttribute.DefaultListValueAttribute(), UwUPnP.Gateway.Gateway(), Terraria.ModLoader.ModNet.ModNet(), Terraria.ModLoader.Core.ModOrganizer._FindMods(), Terraria.Main.AddSignalTraps(), Terraria.ModLoader.Engine.LogArchiver.Archive(), Terraria.ModLoader.Core.ModOrganizer.AttemptLoadMod(), Terraria.Program.AttemptSupportHighDPI(), Terraria.ModLoader.ModNPC.AutoStaticDefaults(), Terraria.ModLoader.UI.UIUpdateMessage.AutoUpdate(), Terraria.ModLoader.UI.UIBuildMod.BuildMod(), Terraria.ModLoader.Engine.InstallVerifier.CheckGoG(), Terraria.Social.Steam.NetClientSocialModule.CheckParameters(), Terraria.Utilities.FileUtilities.ConvertToRelativePath(), Terraria.Utilities.FileUtilities.CopyFolderEXT(), Terraria.Main.DedServ_PostModLoad(), Terraria.ModLoader.BackupIO.DeleteArchive(), Terraria.ModLoader.UI.UIModPackItem.DeleteButtonClick(), Terraria.ModLoader.Engine.LogArchiver.DeleteOldArchives(), Terraria.ModLoader.Core.ModOrganizer.DeleteTemporaryFiles(), Terraria.ModLoader.Core.ModOrganizer.DetectModChangesForInfoMessage(), Terraria.ModLoader.ModLoader.DisableAllMods(), Terraria.Main.DrawMenu(), Terraria.GameContent.UI.States.UIWorldLoad.DrawSelf(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.DrawTimeText(), Terraria.ModLoader.Logging.DumpEnvVars(), Terraria.ModLoader.MonoModHooks.DumpIL(), Terraria.ModLoader.MonoModHooks.DumpILHooks(), Terraria.ModLoader.MonoModHooks.DumpOnHooks(), Terraria.ModLoader.UI.UIModPackItem.EnabledListOnly(), Terraria.ModLoader.UI.UIModPackItem.EnableList(), Terraria.Social.Steam.WorkshopBrowserModule.EnsureInstallationComplete(), Terraria.GameContent.UI.States.UICharacterSelect.ExecuteAutomaticPlayerMigration(), Terraria.GameContent.UI.States.UICharacterSelect.ExecuteIndividualPlayerMigration(), Terraria.GameContent.UI.States.UIWorldSelect.ExecuteIndividualWorldMigration(), Terraria.ModLoader.UI.UIModPacks.ExportSnapshot(), Terraria.ModLoader.UI.UIExtractMod.Extract(), Terraria.ModLoader.LocalizationLoader.ExtractLocalizationFiles(), Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.ModLoader.Core.MemoryTracking.Finish(), Terraria.ModLoader.PlantLoader.FinishSetup(), Terraria.ModLoader.Logging.FirstChanceExceptionHandler(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.GenerateModDownloadItemFromQuery(), Terraria.WorldGen.GenerateWorld_RunTasksAndFinish(), Terraria.ModLoader.Core.ModOrganizer.GetActiveTmodInRepo(), Terraria.ModLoader.Engine.LogArchiver.GetArchivedLogs(), Terraria.ModLoader.UI.UIModSources.GetCommandToFindPathOfExecutable(), Terraria.ModLoader.Engine.LogArchiver.GetOldLogs(), Terraria.ModLoader.UI.UIModSources.GetPossibleSystemDotnetPaths(), Terraria.ModLoader.Engine.Steam.GetSteamTerrariaInstallDir(), Terraria.ModLoader.UI.UIModSources.GetSystemDotnetPath(), Terraria.Social.Steam.WorkshopHelper.GetWorkshopFolder(), Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.HandleNextDownload(), Terraria.ModLoader.UI.DownloadManager.DownloadFile.HandleResponse(), Terraria.ModLoader.Engine.LoggingHooks.HookProcessStart(), Terraria.ModLoader.Engine.LoggingHooks.HookWebRequests(), Terraria.ModLoader.UI.UIModPackItem.ImportModPackLocal(), Terraria.ModLoader.Core.AssemblyResolving.Init(), Terraria.ModLoader.MonoModHooks.Initialize(), Terraria.Social.Steam.SteamedWraps.Initialize(), Terraria.Social.SocialAPI.Initialize(), Terraria.Main.InitTMLContentManager(), Terraria.ModLoader.ModNet.IsClientCompatible(), Terraria.ModLoader.UI.UIModSources.IsCompatibleDotnetSdkAvailable(), Terraria.ModLoader.UI.UIModSources.IsRunningInSandbox(), Terraria.ModLoader.ModLoader.Load(), Terraria.ModLoader.Config.ConfigManager.Load(), Terraria.ModLoader.IO.TileIO.LoadContainers(), Terraria.ModLoader.Core.ModOrganizer.LoadEnabledMods(), Terraria.Initializers.LaunchInitializer.LoadServerParameters(), Terraria.Main.LoadSettings(), Terraria.Utils.LogAndChatAndConsoleInfoMessage(), Terraria.Utils.LogAndConsoleErrorMessage(), Terraria.Utils.LogAndConsoleInfoMessage(), Terraria.ModLoader.UI.UIBuildMod.LogCompilerLine(), Terraria.ModLoader.Logging.LogStartup(), Terraria.ModLoader.Core.GlobalTypeLookups< TGlobal >.LogStats(), Terraria.ModLoader.UI.Interface.ModLoaderMenus(), Terraria.ModLoader.Engine.LogArchiver.MoveZipsToArchiveDir(), Terraria.ModLoader.ModNet.NetReload(), Terraria.ModLoader.UI.UICreateMod.OKClick(), Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.OnActivate(), Terraria.ModLoader.UI.UIUpdateMessage.OnAutoUpdateDownloadComplete(), Terraria.ModLoader.UI.DownloadManager.UIDownloadProgress.OnDeactivate(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.OnInitialize(), Terraria.ModLoader.UI.UIModItem.OnInitialize(), Terraria.Social.Steam.NetClientSocialModule.OnLobbyJoinRequest(), Terraria.ModLoader.UI.UIModSources.OpenSources(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Program.PortCommonFilesToStagingBranches(), Terraria.Program.PortFilesFromXtoY(), Terraria.Program.PortOldSaveDirectories(), Terraria.ModLoader.Engine.FallbackSyncContext.SyncContext.Post(), Terraria.ModLoader.Engine.Steam.PostInit(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.QueryItemsSynchronously(), Terraria.Social.Steam.SteamedWraps.QueueForceValidateSteamInstall(), Terraria.ModLoader.IO.WorldIO.ReadWorldHeader(), Terraria.ModLoader.NPCLoader.ReceiveExtraAI(), Terraria.ModLoader.ModNet.ReceiveMod(), Terraria.ModLoader.IO.WorldIO.ReceiveModData(), Terraria.ModLoader.IO.ItemIO.ReceiveModData(), Terraria.ModLoader.MonoModHooks.RemoveAll(), Terraria.ModLoader.UI.UIModPackItem.RemoveModPackLocal(), Terraria.MonoLaunch.ResolveNativeLibrary(), Terraria.ModLoader.Engine.ServerHangWatchdog.Run(), Terraria.ModLoader.BackupIO.RunArchiving(), Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods(), Terraria.ModLoader.ModNet.SendServerConfigs(), Terraria.ModLoader.ModLoader.SetModEnabled(), Terraria.ModLoader.UI.UILoadMods.SetProgressText(), Terraria.Program.SetSavePath(), Terraria.ModLoader.UI.UIBuildMod.SetStatus(), Terraria.ModLoader.Engine.LogArchiver.SetupLogDirs(), Terraria.Chest.SetupShop(), Terraria.Utils.ShowFancyErrorMessage(), Terraria.Main.startDedInputCallBack(), Terraria.ModLoader.Engine.InstallVerifier.Startup(), Terraria.Program.StartupSequenceTml(), Terraria.ModLoader.ModNet.SyncClientMods(), Terraria.Audio.SoundEngine.TestAudioSupport(), Terraria.ModLoader.Engine.TMLContentManager.TryFixFileCasings(), Terraria.Social.Steam.WorkshopHelper.TryGetPublishIdByInternalName(), Terraria.Social.Steam.SteamedWraps.TryInitViaGameServer(), Terraria.Social.Steam.WorkshopHelper.QueryHelper.AQueryInstance.TrySearchByInternalName(), Terraria.ModLoader.ModLoader.Unload(), Terraria.ModLoader.Engine.FallbackSyncContext.Update(), Terraria.ModLoader.Engine.FolderShortcutSupport.UpdateFolderShortcuts(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem(), Terraria.ModLoader.UI.UIModPackItem.UpdateModPack(), Terraria.ModLoader.Core.ModCompile.UpdateReferencesFolder(), Terraria.ModLoader.Core.TmodFile.Upgrade(), Terraria.GameContent.AssetSourceController.UseResourcePacks(), Terraria.ModLoader.Core.Cloning.TypeCloningInfo.Warn(), Terraria.ModLoader.ModLoader.WarnModsStillLoaded(), and Terraria.Utilities.FileUtilities.WriteTagCompound().