TModLoader: Terraria.ModLoader.Logging.Init
Init()
static void Terraria.ModLoader.Logging.Init (LogFile logFile) inline static package
    {
        if (Program.LaunchParameters.ContainsKey("-build"))
        {
            return;
        }
        Utils.TryCreatingDirectory(LogDir);
        try
        {
            InitLogPaths(logFile);
            ConfigureAppenders(logFile);
        }
        catch (Exception e)
        {
            ErrorReporting.FatalExit("Failed to init logging", e);
        }
    }
References Terraria.ModLoader.Logging.ConfigureAppenders(), Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.ModLoader.Logging.InitLogPaths(), Terraria.Program.LaunchParameters, Terraria.ModLoader.Logging.LogDir, and Terraria.Utils.TryCreatingDirectory().
Referenced by Terraria.ModLoader.Engine.TerrariaSteamClient.Run(), and Terraria.Program.StartupSequenceTml().