TModLoader: Terraria.ModLoader.Logging.AddChatMessage
AddChatMessage() [1/2]
static void Terraria.ModLoader.Logging.AddChatMessage (string msg) inline static private
Definition at line 291 of file Logging.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        AddChatMessage(msg, Color.OrangeRed);
    }
References Terraria.ModLoader.Logging.AddChatMessage().
Referenced by Terraria.ModLoader.Logging.AddChatMessage(), and Terraria.ModLoader.Logging.FirstChanceExceptionHandler().