TModLoader: Terraria.ModLoader.Config.UI.EnumElement.OnBind
OnBind()
override void Terraria.ModLoader.Config.UI.EnumElement.OnBind () inline virtual
Reimplemented from Terraria.ModLoader.Config.UI.ConfigElement< T >.
    {
        base.OnBind();
        valueStrings = Enum.GetNames(base.MemberInfo.Type);
        for (int i = 0; i < valueStrings.Length; i++)
        {
            FieldInfo enumFieldFieldInfo = base.MemberInfo.Type.GetField(valueStrings[i]);
            if (enumFieldFieldInfo != null)
            {
                string name = ConfigManager.GetLocalizedLabel(new PropertyFieldWrapper(enumFieldFieldInfo));
                valueStrings[i] = name;
            }
        }
        max = valueStrings.Length;
        base.TextDisplayFunction = () => base.MemberInfo.Name + ": " + _getValueString();
        _getValue = () => DefaultGetValue();
        _getValueString = () => DefaultGetStringValue();
        _getIndex = () => DefaultGetIndex();
        _setValue = delegate(int value)
        {
            DefaultSetValue(value);
        };
        if (Label != null)
        {
            base.TextDisplayFunction = () => Label + ": " + _getValueString();
        }
    }
References Terraria.ModLoader.Config.UI.EnumElement._getIndex, Terraria.ModLoader.Config.UI.EnumElement._getValue, Terraria.ModLoader.Config.UI.EnumElement._getValueString, Terraria.ModLoader.Config.UI.EnumElement._setValue, Terraria.ModLoader.Config.UI.EnumElement.DefaultGetIndex(), Terraria.ModLoader.Config.UI.EnumElement.DefaultGetStringValue(), Terraria.ModLoader.Config.UI.EnumElement.DefaultGetValue(), Terraria.ModLoader.Config.UI.EnumElement.DefaultSetValue(), Terraria.ModLoader.Config.ConfigManager.GetLocalizedLabel(), Terraria.ModLoader.Config.UI.ConfigElement< T >.Label, Terraria.ModLoader.Config.UI.ConfigElement< T >.List, Terraria.ModLoader.Config.UI.EnumElement.max, and Terraria.ModLoader.Config.UI.EnumElement.valueStrings.