TModLoader: Terraria.ModLoader.Engine.ErrorReporting.FatalExit
FatalExit() [1/2]
static void Terraria.ModLoader.Engine.ErrorReporting.FatalExit (string message) inline static
Definition at line 36 of file ErrorReporting.cs.
    {
        if (Logging.LogPath == null)
        {
            Console.Error.WriteLine(message);
        }
        else
        {
            Logging.tML.Fatal((object)message);
        }
        TerrariaSteamClient.Shutdown();
        MessageBoxShow(message, fatal: true);
        Environment.Exit(1);
    }
References Terraria.ModLoader.Console, Terraria.ModLoader.Environment, Terraria.ModLoader.Logging.LogPath, Terraria.ModLoader.Engine.ErrorReporting.MessageBoxShow(), Terraria.ModLoader.Engine.TerrariaSteamClient.Shutdown(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.Engine.InstallVerifier.InstallVerifier(), Terraria.ModLoader.Engine.InstallVerifier.CheckGoG(), Terraria.ModLoader.Engine.NativeLibraries.CheckNativeFAudioDependencies(), Terraria.ModLoader.Engine.InstallVerifier.CheckSteam(), Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.ModLoader.Logging.FirstChanceExceptionHandler(), Terraria.ModLoader.Logging.Init(), Terraria.Social.Steam.CoreSocialModule.Initialize(), Terraria.Main.InitTMLContentManager(), Terraria.Program.PortFilesFromXtoY(), Terraria.Program.ProcessLaunchArgs(), Terraria.Program.RunGame(), Terraria.Program.SetSavePath(), and Terraria.Program.StartupSequenceTml().