TModLoader: Terraria.ModLoader.Engine.ErrorReporting.FatalExit
FatalExit() [2/2]
static void Terraria.ModLoader.Engine.ErrorReporting.FatalExit (string message, Exception e) inline static
    {
        try
        {
            string error = SDL.SDL_GetError();
            if (error != null)
            {
                message = message + "\n\nSDL Error: " + error;
            }
        }
        catch
        {
        }
        if (e.HelpLink != null)
        {
            try
            {
                Utils.OpenToURL(e.HelpLink);
            }
            catch
            {
            }
        }
        string tip = null;
        if (e is OutOfMemoryException)
        {
            tip = Language.GetTextValue("tModLoader.OutOfMemoryHint");
        }
        else if (e is InvalidOperationException || e is NullReferenceException || e is IndexOutOfRangeException || e is ArgumentNullException)
        {
            tip = Language.GetTextValue("tModLoader.ModExceptionHint");
        }
        else if (e is IOException && e.Message.Contains("cloud file provider"))
        {
            if (string.IsNullOrEmpty(e.HelpLink))
            {
                e.HelpLink = "https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#save-data-file-issues";
            }
            tip = Language.GetTextValue("tModLoader.OneDriveHint");
            if (Language.ActiveCulture == null)
            {
                tip = "Tip: Try installing/enabling OneDrive. Right click your Documents folder and enable \"Always save on this device\"";
            }
        }
        else if (e is SynchronizationLockException)
        {
            tip = Language.GetTextValue("tModLoader.AntivirusHint");
        }
        else if (e is TypeInitializationException)
        {
            tip = Language.GetTextValue("tModLoader.TypeInitializationHint");
        }
        if (e.HelpLink != null)
        {
            try
            {
                Utils.OpenToURL(e.HelpLink);
            }
            catch
            {
            }
        }
        if (tip != null)
        {
            message = message + "\n\n" + tip;
        }
        message = message + "\n\n" + e;
        FatalExit(message);
    }
References Terraria.Localization.Language.ActiveCulture, Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.Localization.Language.GetTextValue(), and Terraria.Utils.OpenToURL().