TModLoader: Terraria.ModLoader.Config.UI.StringOptionElement.OnBind
OnBind()
override void Terraria.ModLoader.Config.UI.StringOptionElement.OnBind () inline virtual
Reimplemented from Terraria.ModLoader.Config.UI.RangeElement.
    {
        base.OnBind();
        StringList = (IList<string>)base.List;
        OptionStringsAttribute optionsAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<OptionStringsAttribute>(base.MemberInfo, base.Item, StringList);
        options = optionsAttribute.OptionLabels;
        base.TextDisplayFunction = () => base.MemberInfo.Name + ": " + getValue();
        getValue = () => DefaultGetValue();
        getIndex = () => DefaultGetIndex();
        setValue = delegate(int value)
        {
            DefaultSetValue(value);
        };
        if (StringList != null)
        {
            getValue = () => StringList[base.Index];
            setValue = delegate(int value)
            {
                StringList[base.Index] = options[value];
                Interface.modConfig.SetPendingChanges();
            };
            base.TextDisplayFunction = () => base.Index + 1 + ": " + StringList[base.Index];
        }
        if (Label != null)
        {
            base.TextDisplayFunction = () => Label + ": " + getValue();
        }
    }
References Terraria.ModLoader.Config.UI.StringOptionElement.DefaultGetIndex(), Terraria.ModLoader.Config.UI.StringOptionElement.DefaultGetValue(), Terraria.ModLoader.Config.UI.StringOptionElement.DefaultSetValue(), Terraria.ModLoader.Config.UI.StringOptionElement.getIndex, Terraria.ModLoader.Config.UI.StringOptionElement.getValue, Terraria.ModLoader.Config.UI.ConfigElement< T >.Label, Terraria.ModLoader.Config.UI.ConfigElement< T >.List, Terraria.ModLoader.UI.Interface.modConfig, Terraria.ModLoader.Config.UI.StringOptionElement.options, Terraria.ModLoader.Config.UI.StringOptionElement.setValue, and Terraria.ModLoader.Config.UI.StringOptionElement.StringList.