TModLoader: Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw
InternalPrepareDraw()
unsafe void Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw (Rectangle drawArea) inline private
Definition at line 156 of file LiquidRenderer.cs.
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_007b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0249: Unknown result type (might be due to invalid IL or missing references)
        //IL_024f: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_0427: Unknown result type (might be due to invalid IL or missing references)
        //IL_0404: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0591: Unknown result type (might be due to invalid IL or missing references)
        //IL_0919: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b06: Unknown result type (might be due to invalid IL or missing references)
        //IL_0636: Unknown result type (might be due to invalid IL or missing references)
        //IL_064f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ca8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0979: Unknown result type (might be due to invalid IL or missing references)
        //IL_0992: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ed5: Unknown result type (might be due to invalid IL or missing references)
        //IL_075c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0761: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b65: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1217: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c01: Unknown result type (might be due to invalid IL or missing references)
        //IL_122f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d07: Unknown result type (might be due to invalid IL or missing references)
        //IL_0d20: Unknown result type (might be due to invalid IL or missing references)
        //IL_11f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_13cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_13d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_123c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_13b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_14e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c68: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6d: Unknown result type (might be due to invalid IL or missing references)
        //IL_14cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1516: Unknown result type (might be due to invalid IL or missing references)
        //IL_103c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1041: Unknown result type (might be due to invalid IL or missing references)
        //IL_10b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_10bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_1068: Unknown result type (might be due to invalid IL or missing references)
        //IL_128f: Unknown result type (might be due to invalid IL or missing references)
        //IL_12a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_1472: Unknown result type (might be due to invalid IL or missing references)
        //IL_1477: Unknown result type (might be due to invalid IL or missing references)
        //IL_148e: Unknown result type (might be due to invalid IL or missing references)
        //IL_1493: Unknown result type (might be due to invalid IL or missing references)
        //IL_12d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_12ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_1306: Unknown result type (might be due to invalid IL or missing references)
        //IL_1310: Unknown result type (might be due to invalid IL or missing references)
        //IL_1315: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_08dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08de: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_1161: Unknown result type (might be due to invalid IL or missing references)
        //IL_1166: Unknown result type (might be due to invalid IL or missing references)
        Rectangle rectangle = default(Rectangle);
        ((Rectangle)(ref rectangle))._002Ector(drawArea.X - 2, drawArea.Y - 2, drawArea.Width + 4, drawArea.Height + 4);
        _drawArea = drawArea;
        if (_cache.Length < rectangle.Width * rectangle.Height + 1)
        {
            _cache = new LiquidCache[rectangle.Width * rectangle.Height + 1];
        }
        if (_drawCache.Length < drawArea.Width * drawArea.Height + 1)
        {
            _drawCache = new LiquidDrawCache[drawArea.Width * drawArea.Height + 1];
        }
        if (_drawCacheForShimmer.Length < drawArea.Width * drawArea.Height + 1)
        {
            _drawCacheForShimmer = new SpecialLiquidDrawCache[drawArea.Width * drawArea.Height + 1];
        }
        if (_waveMask.Length < drawArea.Width * drawArea.Height)
        {
            _waveMask = (Color[])(object)new Color[drawArea.Width * drawArea.Height];
        }
        Tile tile = default(Tile);
        fixed (LiquidCache* ptr = &_cache[1])
        {
            LiquidCache* ptr3 = ptr;
            int num = rectangle.Height * 2 + 2;
            ptr3 = ptr;
            for (int i = rectangle.X; i < rectangle.X + rectangle.Width; i++)
            {
                for (int j = rectangle.Y; j < rectangle.Y + rectangle.Height; j++)
                {
                    tile = Main.tile[i, j];
                    if (tile == null)
                    {
                        tile = default(Tile);
                    }
                    ptr3->LiquidLevel = (float)(int)tile.liquid / 255f;
                    ptr3->IsHalfBrick = tile.halfBrick() && ptr3[-1].HasLiquid && !TileID.Sets.Platforms[tile.type];
                    ptr3->IsSolid = WorldGen.SolidOrSlopedTile(tile);
                    ptr3->HasLiquid = tile.liquid != 0;
                    ptr3->VisibleLiquidLevel = 0f;
                    ptr3->HasWall = tile.wall != 0;
                    ptr3->Type = tile.liquidType();
                    if (ptr3->IsHalfBrick && !ptr3->HasLiquid)
                    {
                        ptr3->Type = ptr3[-1].Type;
                    }
                    ptr3++;
                }
            }
            ptr3 = ptr;
            float num12 = 0f;
            ptr3 += num;
            for (int k = 2; k < rectangle.Width - 2; k++)
            {
                for (int l = 2; l < rectangle.Height - 2; l++)
                {
                    num12 = 0f;
                    if (ptr3->IsHalfBrick && ptr3[-1].HasLiquid)
                    {
                        num12 = 1f;
                    }
                    else if (!ptr3->HasLiquid)
                    {
                        LiquidCache liquidCache4 = ptr3[-1];
                        LiquidCache liquidCache8 = ptr3[1];
                        LiquidCache liquidCache13 = ptr3[-rectangle.Height];
                        LiquidCache liquidCache18 = ptr3[rectangle.Height];
                        if (liquidCache4.HasLiquid && liquidCache8.HasLiquid && liquidCache4.Type == liquidCache8.Type && !liquidCache4.IsSolid && !liquidCache8.IsSolid)
{
                            num12 = liquidCache4.LiquidLevel + liquidCache8.LiquidLevel;
                            ptr3->Type = liquidCache4.Type;
                        }
                        if (liquidCache13.HasLiquid && liquidCache18.HasLiquid && liquidCache13.Type == liquidCache18.Type && !liquidCache13.IsSolid && !liquidCache18.IsSolid)
{
                            num12 = Math.Max(num12, liquidCache13.LiquidLevel + liquidCache18.LiquidLevel);
                            ptr3->Type = liquidCache13.Type;
                        }
                        num12 *= 0.5f;
                    }
                    else
                    {
                        num12 = ptr3->LiquidLevel;
                    }
                    ptr3->VisibleLiquidLevel = num12;
                    ptr3->HasVisibleLiquid = num12 != 0f;
                    ptr3++;
                }
                ptr3 += 4;
            }
            ptr3 = ptr;
            for (int m = 0; m < rectangle.Width; m++)
            {
                for (int n = 0; n < rectangle.Height - 10; n++)
                {
                    if (ptr3->HasVisibleLiquid && (!ptr3->IsSolid || ptr3->IsHalfBrick))
                    {
                        ptr3->Opacity = 1f;
                        ptr3->VisibleType = ptr3->Type;
                        float num23 = 1f / (float)(WATERFALL_LENGTH[ptr3->Type] + 1);
                        float num24 = 1f;
                        for (int num25 = 1; num25 <= WATERFALL_LENGTH[ptr3->Type]; num25++)
{
                            num24 -= num23;
                            if (ptr3[num25].IsSolid)
{
                                break;
                            }
                            ptr3[num25].VisibleLiquidLevel = Math.Max(ptr3[num25].VisibleLiquidLevel, ptr3->VisibleLiquidLevel * num24);
                            ptr3[num25].Opacity = num24;
                            ptr3[num25].VisibleType = ptr3->Type;
                        }
                    }
                    if (ptr3->IsSolid && !ptr3->IsHalfBrick)
                    {
                        ptr3->VisibleLiquidLevel = 1f;
                        ptr3->HasVisibleLiquid = false;
                    }
                    else
                    {
                        ptr3->HasVisibleLiquid = ptr3->VisibleLiquidLevel != 0f;
                    }
                    ptr3++;
                }
                ptr3 += 10;
            }
            ptr3 = ptr;
            ptr3 += num;
            for (int num26 = 2; num26 < rectangle.Width - 2; num26++)
            {
                for (int num27 = 2; num27 < rectangle.Height - 2; num27++)
                {
                    if (!ptr3->HasVisibleLiquid)
                    {
                        ptr3->HasLeftEdge = false;
                        ptr3->HasTopEdge = false;
                        ptr3->HasRightEdge = false;
                        ptr3->HasBottomEdge = false;
                    }
                    else
                    {
                        LiquidCache liquidCache3 = ptr3[-1];
                        LiquidCache liquidCache7 = ptr3[1];
                        LiquidCache liquidCache12 = ptr3[-rectangle.Height];
                        LiquidCache liquidCache17 = ptr3[rectangle.Height];
                        float num28 = 0f;
                        float num29 = 1f;
                        float num2 = 0f;
                        float num3 = 1f;
                        float visibleLiquidLevel = ptr3->VisibleLiquidLevel;
                        if (!liquidCache3.HasVisibleLiquid)
{
                            num2 += liquidCache7.VisibleLiquidLevel * (1f - visibleLiquidLevel);
                        }
                        if (!liquidCache7.HasVisibleLiquid && !liquidCache7.IsSolid && !liquidCache7.IsHalfBrick)
{
                            num3 -= liquidCache3.VisibleLiquidLevel * (1f - visibleLiquidLevel);
                        }
                        if (!liquidCache12.HasVisibleLiquid && !liquidCache12.IsSolid && !liquidCache12.IsHalfBrick)
{
                            num28 += liquidCache17.VisibleLiquidLevel * (1f - visibleLiquidLevel);
                        }
                        if (!liquidCache17.HasVisibleLiquid && !liquidCache17.IsSolid && !liquidCache17.IsHalfBrick)
{
                            num29 -= liquidCache12.VisibleLiquidLevel * (1f - visibleLiquidLevel);
                        }
                        ptr3->LeftWall = num28;
                        ptr3->RightWall = num29;
                        ptr3->BottomWall = num3;
                        ptr3->TopWall = num2;
                        Point zero = Point.Zero;
                        ptr3->HasTopEdge = (!liquidCache3.HasVisibleLiquid && !liquidCache3.IsSolid) || num2 != 0f;
                        ptr3->HasBottomEdge = (!liquidCache7.HasVisibleLiquid && !liquidCache7.IsSolid) || num3 != 1f;
                        ptr3->HasLeftEdge = (!liquidCache12.HasVisibleLiquid && !liquidCache12.IsSolid) || num28 != 0f;
                        ptr3->HasRightEdge = (!liquidCache17.HasVisibleLiquid && !liquidCache17.IsSolid) || num29 != 1f;
                        if (!ptr3->HasLeftEdge)
{
                            if (ptr3->HasRightEdge)
{
                                zero.X += 32;
                            }
                            else
{
                                zero.X += 16;
                            }
                        }
                        if (ptr3->HasLeftEdge && ptr3->HasRightEdge)
{
                            zero.X = 16;
                            zero.Y += 32;
                            if (ptr3->HasTopEdge)
{
                                zero.Y = 16;
                            }
                        }
                        else if (!ptr3->HasTopEdge)
{
                            if (!ptr3->HasLeftEdge && !ptr3->HasRightEdge)
{
                                zero.Y += 48;
                            }
                            else
{
                                zero.Y += 16;
                            }
                        }
                        if (zero.Y == 16 && (ptr3->HasLeftEdge ^ ptr3->HasRightEdge) && (num27 + rectangle.Y) % 2 == 0)
{
                            zero.Y += 16;
                        }
                        Unsafe.Write(&ptr3->FrameOffset, zero);
                    }
                    ptr3++;
                }
                ptr3 += 4;
            }
            ptr3 = ptr;
            ptr3 += num;
            for (int num4 = 2; num4 < rectangle.Width - 2; num4++)
            {
                for (int num5 = 2; num5 < rectangle.Height - 2; num5++)
                {
                    if (ptr3->HasVisibleLiquid)
                    {
                        LiquidCache liquidCache2 = ptr3[-1];
                        LiquidCache liquidCache6 = ptr3[1];
                        LiquidCache liquidCache11 = ptr3[-rectangle.Height];
                        LiquidCache liquidCache16 = ptr3[rectangle.Height];
                        ptr3->VisibleLeftWall = ptr3->LeftWall;
                        ptr3->VisibleRightWall = ptr3->RightWall;
                        ptr3->VisibleTopWall = ptr3->TopWall;
                        ptr3->VisibleBottomWall = ptr3->BottomWall;
                        if (liquidCache2.HasVisibleLiquid && liquidCache6.HasVisibleLiquid)
{
                            if (ptr3->HasLeftEdge)
{
                                ptr3->VisibleLeftWall = (ptr3->LeftWall * 2f + liquidCache2.LeftWall + liquidCache6.LeftWall) * 0.25f;
                            }
                            if (ptr3->HasRightEdge)
{
                                ptr3->VisibleRightWall = (ptr3->RightWall * 2f + liquidCache2.RightWall + liquidCache6.RightWall) * 0.25f;
                            }
                        }
                        if (liquidCache11.HasVisibleLiquid && liquidCache16.HasVisibleLiquid)
{
                            if (ptr3->HasTopEdge)
{
                                ptr3->VisibleTopWall = (ptr3->TopWall * 2f + liquidCache11.TopWall + liquidCache16.TopWall) * 0.25f;
                            }
                            if (ptr3->HasBottomEdge)
{
                                ptr3->VisibleBottomWall = (ptr3->BottomWall * 2f + liquidCache11.BottomWall + liquidCache16.BottomWall) * 0.25f;
                            }
                        }
                    }
                    ptr3++;
                }
                ptr3 += 4;
            }
            ptr3 = ptr;
            ptr3 += num;
            for (int num6 = 2; num6 < rectangle.Width - 2; num6++)
            {
                for (int num7 = 2; num7 < rectangle.Height - 2; num7++)
                {
                    if (ptr3->HasLiquid)
                    {
                        _ = ptr3[-1];
                        LiquidCache liquidCache5 = ptr3[1];
                        LiquidCache liquidCache10 = ptr3[-rectangle.Height];
                        LiquidCache liquidCache15 = ptr3[rectangle.Height];
                        if (ptr3->HasTopEdge && !ptr3->HasBottomEdge && (ptr3->HasLeftEdge ^ ptr3->HasRightEdge))
{
                            if (ptr3->HasRightEdge)
{
                                ptr3->VisibleRightWall = liquidCache5.VisibleRightWall;
                                ptr3->VisibleTopWall = liquidCache10.VisibleTopWall;
                            }
                            else
{
                                ptr3->VisibleLeftWall = liquidCache5.VisibleLeftWall;
                                ptr3->VisibleTopWall = liquidCache15.VisibleTopWall;
                            }
                        }
                        else if (liquidCache5.FrameOffset.X == 16 && liquidCache5.FrameOffset.Y == 32)
{
                            if (ptr3->VisibleLeftWall > 0.5f)
{
                                ptr3->VisibleLeftWall = 0f;
                                Unsafe.Write(&ptr3->FrameOffset, new Point(0, 0));
                            }
                            else if (ptr3->VisibleRightWall < 0.5f)
{
                                ptr3->VisibleRightWall = 1f;
                                Unsafe.Write(&ptr3->FrameOffset, new Point(32, 0));
                            }
                        }
                    }
                    ptr3++;
                }
                ptr3 += 4;
            }
            ptr3 = ptr;
            ptr3 += num;
            for (int num8 = 2; num8 < rectangle.Width - 2; num8++)
            {
                for (int num9 = 2; num9 < rectangle.Height - 2; num9++)
                {
                    if (ptr3->HasLiquid)
                    {
                        LiquidCache liquidCache = ptr3[-1];
                        _ = ptr3[1];
                        LiquidCache liquidCache9 = ptr3[-rectangle.Height];
                        LiquidCache liquidCache14 = ptr3[rectangle.Height];
                        if (!ptr3->HasBottomEdge && !ptr3->HasLeftEdge && !ptr3->HasTopEdge && !ptr3->HasRightEdge)
{
                            if (liquidCache9.HasTopEdge && liquidCache.HasLeftEdge)
{
                                ((Point)(&ptr3->FrameOffset)).X = Math.Max(4, (int)(16f - liquidCache.VisibleLeftWall * 16f)) - 4;
                                ((Point)(&ptr3->FrameOffset)).Y = 48 + Math.Max(4, (int)(16f - liquidCache9.VisibleTopWall * 16f)) - 4;
                                ptr3->VisibleLeftWall = 0f;
                                ptr3->VisibleTopWall = 0f;
                                ptr3->VisibleRightWall = 1f;
                                ptr3->VisibleBottomWall = 1f;
                            }
                            else if (liquidCache14.HasTopEdge && liquidCache.HasRightEdge)
{
                                ((Point)(&ptr3->FrameOffset)).X = 32 - Math.Min(16, (int)(liquidCache.VisibleRightWall * 16f) - 4);
                                ((Point)(&ptr3->FrameOffset)).Y = 48 + Math.Max(4, (int)(16f - liquidCache14.VisibleTopWall * 16f)) - 4;
                                ptr3->VisibleLeftWall = 0f;
                                ptr3->VisibleTopWall = 0f;
                                ptr3->VisibleRightWall = 1f;
                                ptr3->VisibleBottomWall = 1f;
                            }
                        }
                    }
                    ptr3++;
                }
                ptr3 += 4;
            }
            ptr3 = ptr;
            ptr3 += num;
            fixed (LiquidDrawCache* ptr4 = &_drawCache[0])
            {
                fixed (Color* ptr10 = &_waveMask[0])
                {
                    LiquidDrawCache* ptr5 = ptr4;
                    Color* ptr6 = ptr10;
                    for (int num10 = 2; num10 < rectangle.Width - 2; num10++)
                    {
                        for (int num11 = 2; num11 < rectangle.Height - 2; num11++)
{
                            if (ptr3->HasVisibleLiquid)
{
                                float num13 = Math.Min(0.75f, ptr3->VisibleLeftWall);
                                float num14 = Math.Max(0.25f, ptr3->VisibleRightWall);
                                float num15 = Math.Min(0.75f, ptr3->VisibleTopWall);
                                float num16 = Math.Max(0.25f, ptr3->VisibleBottomWall);
                                if (ptr3->IsHalfBrick && ptr3->IsSolid && num16 > 0.5f)
{
                                    num16 = 0.5f;
                                }
                                ptr5->IsVisible = ptr3->HasWall || !ptr3->IsHalfBrick || !ptr3->HasLiquid || !(ptr3->LiquidLevel < 1f);
                                Unsafe.Write(&ptr5->SourceRectangle, new Rectangle((int)(16f - num14 * 16f) + ((Point)(&ptr3->FrameOffset)).X, (int)(16f - num16 * 16f) + ((Point)(&ptr3->FrameOffset)).Y, (int)Math.Ceiling((num14 - num13) * 16f), (int)Math.Ceiling((num16 - num15) * 16f)));
                                ptr5->IsSurfaceLiquid = ((Point)(&ptr3->FrameOffset)).X == 16 && ((Point)(&ptr3->FrameOffset)).Y == 0 && (double)(num11 + rectangle.Y) > Main.worldSurface - 40.0;
                                ptr5->Opacity = ptr3->Opacity;
                                Unsafe.Write(&ptr5->LiquidOffset, new Vector2((float)Math.Floor(num13 * 16f), (float)Math.Floor(num15 * 16f)));
                                ptr5->Type = ptr3->VisibleType;
                                ptr5->HasWall = ptr3->HasWall;
                                byte b = WAVE_MASK_STRENGTH[ptr3->VisibleType];
                                byte b4 = (((Color)ptr6).R = (byte)(b >> 1));
                                byte g = b4;
                                ((Color)ptr6).G = g;
                                ((Color)ptr6).B = VISCOSITY_MASK[ptr3->VisibleType];
                                ((Color)ptr6).A = b;
                                LiquidCache* ptr7 = ptr3 - 1;
                                if (num11 != 2 && !ptr7->HasVisibleLiquid && !ptr7->IsSolid && !ptr7->IsHalfBrick)
{
                                    Unsafe.Write((byte*)ptr6 - Unsafe.SizeOf<Color>(), *ptr6);
                                }
                            }
                            else
{
                                ptr5->IsVisible = false;
                                int num17 = ((!ptr3->IsSolid && !ptr3->IsHalfBrick) ? 4 : 3);
                                byte b2 = WAVE_MASK_STRENGTH[num17];
                                byte b4 = (((Color)ptr6).R = (byte)(b2 >> 1));
                                byte g2 = b4;
                                ((Color)ptr6).G = g2;
                                ((Color)ptr6).B = VISCOSITY_MASK[num17];
                                ((Color)ptr6).A = b2;
                            }
                            ptr3++;
                            ptr5++;
                            ptr6 = (Color*)((byte*)ptr6 + Unsafe.SizeOf<Color>());
                        }
                        ptr3 += 4;
                    }
                }
            }
            ptr3 = ptr;
            for (int num18 = rectangle.X; num18 < rectangle.X + rectangle.Width; num18++)
            {
                for (int num19 = rectangle.Y; num19 < rectangle.Y + rectangle.Height; num19++)
                {
                    if (ptr3->VisibleType == 1 && ptr3->HasVisibleLiquid && Dust.lavaBubbles < 200)
                    {
                        if (_random.Next(700) == 0)
{
                            Dust.NewDust(new Vector2((float)(num18 * 16), (float)(num19 * 16)), 16, 16, 35, 0f, 0f, 0, Color.White);
                        }
                        if (_random.Next(350) == 0)
{
                            int num20 = Dust.NewDust(new Vector2((float)(num18 * 16), (float)(num19 * 16)), 16, 8, 35, 0f, 0f, 50, Color.White, 1.5f);
                            Dust obj = Main.dust[num20];
                            obj.velocity *= 0.8f;
                            Main.dust[num20].velocity.X *= 2f;
                            Main.dust[num20].velocity.Y -= (float)_random.Next(1, 7) * 0.1f;
                            if (_random.Next(10) == 0)
{
                                Main.dust[num20].velocity.Y *= _random.Next(2, 5);
                            }
                            Main.dust[num20].noGravity = true;
                        }
                    }
                    ptr3++;
                }
            }
            fixed (LiquidDrawCache* ptr8 = &_drawCache[0])
            {
                fixed (SpecialLiquidDrawCache* ptr11 = &_drawCacheForShimmer[0])
                {
                    LiquidDrawCache* ptr9 = ptr8;
                    SpecialLiquidDrawCache* ptr2 = ptr11;
                    for (int num21 = 2; num21 < rectangle.Width - 2; num21++)
                    {
                        for (int num22 = 2; num22 < rectangle.Height - 2; num22++)
{
                            if (ptr9->IsVisible && ptr9->Type == 3)
{
                                ptr2->X = num21;
                                ptr2->Y = num22;
                                ptr2->IsVisible = ptr9->IsVisible;
                                ptr2->HasWall = ptr9->HasWall;
                                ptr2->IsSurfaceLiquid = ptr9->IsSurfaceLiquid;
                                Unsafe.Write(&ptr2->LiquidOffset, ptr9->LiquidOffset);
                                ptr2->Opacity = ptr9->Opacity;
                                Unsafe.Write(&ptr2->SourceRectangle, ptr9->SourceRectangle);
                                ptr2->Type = ptr9->Type;
                                ptr9->IsVisible = false;
                                ptr2++;
                            }
                            ptr9++;
                        }
                    }
                    ptr2->IsVisible = false;
                }
            }
        }
        if (this.WaveFilters != null)
        {
            this.WaveFilters(_waveMask, GetCachedDrawArea());
        }
    }
References Terraria.GameContent.Liquid.LiquidRenderer._cache, Terraria.GameContent.Liquid.LiquidRenderer._drawArea, Terraria.GameContent.Liquid.LiquidRenderer._drawCache, Terraria.GameContent.Liquid.LiquidRenderer._drawCacheForShimmer, Terraria.GameContent.Liquid.LiquidRenderer._random, Terraria.GameContent.Liquid.LiquidRenderer._waveMask, Terraria.Main.dust, Terraria.GameContent.Liquid.LiquidRenderer.GetCachedDrawArea(), Terraria.Tile.halfBrick(), Terraria.Dust.lavaBubbles, Terraria.Tile.liquidType(), Terraria.Dust.NewDust(), Terraria.ID.TileID.Sets.Platforms, Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tile, Terraria.Tile.type, Terraria.GameContent.Liquid.LiquidRenderer.VISCOSITY_MASK, Terraria.GameContent.Liquid.LiquidRenderer.WATERFALL_LENGTH, Terraria.GameContent.Liquid.LiquidRenderer.WAVE_MASK_STRENGTH, and Terraria.GameContent.Liquid.LiquidRenderer.WaveFilters.
Referenced by Terraria.GameContent.Liquid.LiquidRenderer.PrepareDraw().