TModLoader: Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer
DrawShimmer()
unsafe void Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer (SpriteBatch spriteBatch, Vector2 drawOffset, bool isBackgroundDraw) inline
Definition at line 800 of file LiquidRenderer.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0107: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0119: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        Rectangle drawArea = _drawArea;
        Main.tileBatch.Begin();
        fixed (SpecialLiquidDrawCache* ptr3 = &_drawCacheForShimmer[0])
        {
            SpecialLiquidDrawCache* ptr2 = ptr3;
            int num = _drawCacheForShimmer.Length;
            for (int i = 0; i < num; i++)
            {
                if (!ptr2->IsVisible)
                {
                    break;
                }
                Rectangle sourceRectangle = ptr2->SourceRectangle;
                if (ptr2->IsSurfaceLiquid)
                {
                    sourceRectangle.Y = 1280;
                }
                else
                {
                    sourceRectangle.Y += _animationFrame * 80;
                }
                Vector2 liquidOffset = ptr2->LiquidOffset;
                float val = ptr2->Opacity * (isBackgroundDraw ? 1f : 0.75f);
                int num2 = 14;
                val = Math.Min(1f, val);
                int num3 = ptr2->X + drawArea.X - 2;
                int num4 = ptr2->Y + drawArea.Y - 2;
                Lighting.GetCornerColors(num3, num4, out var vertices);
                SetShimmerVertexColors(ref vertices, val, num3, num4);
                Main.DrawTileInWater(drawOffset, num3, num4);
                Main.tileBatch.Draw(_liquidTextures[num2].Value, new Vector2((float)(num3 << 4), (float)(num4 << 4)) + drawOffset + liquidOffset, sourceRectangle, vertices, Vector2.Zero, 1f, (SpriteEffects)0);
                sourceRectangle = ptr2->SourceRectangle;
                bool flag = sourceRectangle.X != 16 || sourceRectangle.Y % 80 != 48;
                if (flag || (num3 + num4) % 2 == 0)
                {
                    sourceRectangle.X += 48;
                    sourceRectangle.Y += 80 * GetShimmerFrame(flag, num3, num4);
                    SetShimmerVertexColors_Sparkle(ref vertices, ptr2->Opacity, num3, num4, flag);
                    Main.tileBatch.Draw(_liquidTextures[num2].Value, new Vector2((float)(num3 << 4), (float)(num4 << 4)) + drawOffset + liquidOffset, sourceRectangle, vertices, Vector2.Zero, 1f, (SpriteEffects)0);
                }
                ptr2++;
            }
        }
        Main.tileBatch.End();
    }
References Terraria.GameContent.Liquid.LiquidRenderer._animationFrame, Terraria.GameContent.Liquid.LiquidRenderer._drawArea, Terraria.GameContent.Liquid.LiquidRenderer._drawCacheForShimmer, Terraria.GameContent.Liquid.LiquidRenderer._liquidTextures, Terraria.Main.DrawTileInWater(), Terraria.Lighting.GetCornerColors(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerFrame(), Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors(), Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors_Sparkle(), and Terraria.Main.tileBatch.