TModLoader: Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors_Sparkle
SetShimmerVertexColors_Sparkle()
static VertexColors Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors_Sparkle (ref VertexColors colors, float opacity, int x, int y, bool top) inline static
Definition at line 875 of file LiquidRenderer.cs.
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000e: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0034: Unknown result type (might be due to invalid IL or missing references)
        //IL_0042: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0053: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_006a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        colors.BottomLeftColor = GetShimmerGlitterColor(top, x, y + 1);
        colors.BottomRightColor = GetShimmerGlitterColor(top, x + 1, y + 1);
        colors.TopLeftColor = GetShimmerGlitterColor(top, x, y);
        colors.TopRightColor = GetShimmerGlitterColor(top, x + 1, y);
        ref Color bottomLeftColor = ref colors.BottomLeftColor;
        bottomLeftColor *= opacity;
        ref Color bottomRightColor = ref colors.BottomRightColor;
        bottomRightColor *= opacity;
        ref Color topLeftColor = ref colors.TopLeftColor;
        topLeftColor *= opacity;
        ref Color topRightColor = ref colors.TopRightColor;
        topRightColor *= opacity;
        return colors;
    }
References Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterColor().
Referenced by Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer(), and Terraria.WaterfallManager.DrawWaterfall().