TModLoader: Terraria.ModLoader.Core.TmodFile.GetStream
GetStream() [1/2]
Stream Terraria.ModLoader.Core.TmodFile.GetStream (FileEntry entry, bool newFileStream = false) inline
    {
        //IL_00c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Expected O, but got Unknown
        Stream stream;
        if (entry.cachedBytes != null)
        {
            stream = entry.cachedBytes.ToMemoryStream();
        }
        else
        {
            if (fileStream == null)
            {
                throw new IOException("File not open: " + path);
            }
            if (newFileStream)
            {
                EntryReadStream ers = new EntryReadStream(this, entry, File.OpenRead(path), leaveOpen: false);
                lock (independentEntryReadStreams)
                {
                    independentEntryReadStreams.Add(ers);
                }
                stream = ers;
            }
            else
            {
                if (sharedEntryReadStream != null)
                {
                    throw new IOException("Previous entry read stream not closed: " + sharedEntryReadStream.Name);
                }
                stream = (sharedEntryReadStream = new EntryReadStream(this, entry, fileStream, leaveOpen: true));
            }
        }
        if (entry.IsCompressed)
        {
            stream = (Stream)new DeflateStream(stream, (CompressionMode)1);
        }
        return stream;
    }
References Terraria.ModLoader.Core.TmodFile.FileEntry.cachedBytes, Terraria.ModLoader.Core.TmodFile.fileStream, Terraria.ModLoader.Core.TmodFile.independentEntryReadStreams, Terraria.ModLoader.Core.TmodFile.FileEntry.IsCompressed, Terraria.ModLoader.Core.EntryReadStream.Name, Terraria.ModLoader.Core.TmodFile.path, and Terraria.ModLoader.Core.TmodFile.sharedEntryReadStream.
Referenced by Terraria.ModLoader.Core.TmodFile.GetBytes(), Terraria.ModLoader.Mod.GetFileStream(), Terraria.ModLoader.Core.TmodFile.GetStream(), Terraria.ModLoader.LocalizationLoader.LoadTranslations(), and Terraria.ModLoader.Core.BuildProperties.ReadModFile().