TModLoader: Terraria.ModLoader.Core.TmodFile.files
files
IDictionary<string, FileEntry> Terraria.ModLoader.Core.TmodFile.files = new Dictionary<string, FileEntry>() private
Definition at line 66 of file TmodFile.cs.
Referenced by Terraria.ModLoader.Core.TmodFile.AddFile(), Terraria.ModLoader.Core.TmodFile.GetBytes(), Terraria.ModLoader.Core.TmodFile.GetFileNames(), Terraria.ModLoader.Core.TmodFile.GetStream(), Terraria.ModLoader.Core.TmodFile.HasFile(), Terraria.ModLoader.Core.TmodFile.Read(), Terraria.ModLoader.Core.TmodFile.RemoveFile(), Terraria.ModLoader.Core.TmodFile.RemoveFromCache(), and Terraria.ModLoader.Core.TmodFile.Save().