TModLoader: Terraria.ModLoader.Core.TmodFile.Read
Read()
void Terraria.ModLoader.Core.TmodFile.Read () inline private
    {
        fileStream = File.OpenRead(path);
        BinaryReader reader = new BinaryReader(fileStream);
        if (Encoding.ASCII.GetString(reader.ReadBytes(4)) != "TMOD")
        {
            throw new Exception("Magic Header != \"TMOD\"");
        }
        TModLoaderVersion = new Version(reader.ReadString());
        Hash = reader.ReadBytes(20);
        Signature = reader.ReadBytes(256);
        reader.ReadInt32();
        long pos = fileStream.Position;
        if (!SHA1.Create().ComputeHash(fileStream).SequenceEqual(Hash))
        {
            throw new Exception(Language.GetTextValue("tModLoader.LoadErrorHashMismatchCorrupted"));
        }
        fileStream.Position = pos;
        if (TModLoaderVersion < new Version(0, 11))
        {
            Upgrade();
            return;
        }
        Name = reader.ReadString();
        Version = new Version(reader.ReadString());
        int offset = 0;
        fileTable = new FileEntry[reader.ReadInt32()];
        for (int i = 0; i < fileTable.Length; i++)
        {
            FileEntry f = new FileEntry(reader.ReadString(), offset, reader.ReadInt32(), reader.ReadInt32());
            fileTable[i] = f;
            files[f.Name] = f;
            offset += f.CompressedLength;
        }
        int fileStartPos = (int)fileStream.Position;
        FileEntry[] array = fileTable;
        for (int j = 0; j < array.Length; j++)
        {
            array[j].Offset += fileStartPos;
        }
    }
References Terraria.ModLoader.Core.TmodFile.files, Terraria.ModLoader.Core.TmodFile.fileStream, Terraria.ModLoader.Core.TmodFile.fileTable, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Core.TmodFile.Hash, Terraria.ModLoader.Core.TmodFile.FileEntry.Length, Terraria.ModLoader.Core.TmodFile.Name, Terraria.ModLoader.Core.TmodFile.FileEntry.Offset, Terraria.ModLoader.Core.TmodFile.path, Terraria.ModLoader.Core.TmodFile.Signature, Terraria.ModLoader.Core.TmodFile.TModLoaderVersion, Terraria.ModLoader.Core.TmodFile.Upgrade(), and Terraria.ModLoader.Core.TmodFile.Version.
Referenced by Terraria.ModLoader.Core.TmodFile.Open().