TModLoader: Terraria.ModLoader.Core.TmodFile.Open
Open()
IDisposable Terraria.ModLoader.Core.TmodFile.Open () inline
Definition at line 317 of file TmodFile.cs.
    {
        if (openCounter++ == 0)
        {
            if (fileStream != null)
            {
                throw new Exception("File already opened? " + path);
            }
            try
            {
                if (Name == null)
                {
                    Read();
                }
                else
                {
                    Reopen();
                }
            }
            catch
            {
                try
                {
                    Close();
                }
                catch
                {
                }
                throw;
            }
        }
        return new DisposeWrapper(Close);
    }
References Terraria.ModLoader.Core.TmodFile.Close(), Terraria.ModLoader.Core.TmodFile.fileStream, Terraria.ModLoader.Core.TmodFile.Name, Terraria.ModLoader.Core.TmodFile.openCounter, Terraria.ModLoader.Core.TmodFile.path, Terraria.ModLoader.Core.TmodFile.Read(), and Terraria.ModLoader.Core.TmodFile.Reopen().
Referenced by Terraria.ModLoader.Core.ModOrganizer.AttemptLoadMod(), Terraria.Social.Steam.WorkshopBrowserModule.EnsureInstallationComplete(), Terraria.ModLoader.Mod.PrepareAssets(), Terraria.ModLoader.UI.UIModSourceItem.PublishModCommandLine(), and Terraria.ModLoader.Core.TmodFile.Upgrade().