TModLoader: Terraria.ModLoader.Core.TmodFile.Upgrade
Upgrade()
void Terraria.ModLoader.Core.TmodFile.Upgrade () inline private
Definition at line 469 of file TmodFile.cs.
    {
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Expected O, but got Unknown
        Interface.loadMods.SubProgressText = "Upgrading: " + Path.GetFileName(this.path);
        Logging.tML.InfoFormat("Upgrading: {0}", (object)Path.GetFileName(this.path));
        DeflateStream deflateStream = new DeflateStream((Stream)fileStream, (CompressionMode)1, true);
        try
        {
            using BinaryReader reader = new BinaryReader((Stream)(object)deflateStream);
            Name = reader.ReadString();
            Version = new Version(reader.ReadString());
            int count = reader.ReadInt32();
            for (int i = 0; i < count; i++)
            {
                AddFile(reader.ReadString(), reader.ReadBytes(reader.ReadInt32()));
            }
        }
        finally
        {
            ((IDisposable)deflateStream)?.Dispose();
        }
        BuildProperties info = BuildProperties.ReadModFile(this);
        info.buildVersion = TModLoaderVersion;
        AddFile("Info", info.ToBytes());
        fileStream.Seek(0L, SeekOrigin.Begin);
        string path = Path.Combine(Path.GetDirectoryName(this.path), "UpgradeBackup");
        Directory.CreateDirectory(path);
        using (FileStream backupStream = File.OpenWrite(Path.Combine(path, Path.GetFileName(this.path))))
        {
            fileStream.CopyTo(backupStream);
        }
        Close();
        Save();
        ResetCache();
        Open();
    }
References Terraria.ModLoader.Core.TmodFile.AddFile(), Terraria.ModLoader.Core.TmodFile.Close(), Terraria.ModLoader.Core.TmodFile.fileStream, Terraria.ModLoader.Core.TmodFile.Name, Terraria.ModLoader.Core.TmodFile.Open(), Terraria.ModLoader.Core.TmodFile.path, Terraria.ModLoader.Core.BuildProperties.ReadModFile(), Terraria.ModLoader.Core.TmodFile.ResetCache(), Terraria.ModLoader.Core.TmodFile.Save(), Terraria.ModLoader.Logging.tML, Terraria.ModLoader.Core.TmodFile.TModLoaderVersion, and Terraria.ModLoader.Core.TmodFile.Version.
Referenced by Terraria.ModLoader.Core.TmodFile.Read().