TModLoader: Terraria.ModLoader.Core.TmodFile.AddFile
AddFile()
void Terraria.ModLoader.Core.TmodFile.AddFile (string fileName, byte[] data) inline package
Adds a (fileName -> content) entry to the compressed payload This method is not threadsafe with reads, but is threadsafe with multiple concurrent AddFile calls.
Parameters
fileName The internal filepath, will be slash sanitised automatically
data The file content to add. WARNING, data is kept as a shallow copy, so modifications to the passed byte array will affect file content
Definition at line 217 of file TmodFile.cs.
    {
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Expected O, but got Unknown
        fileName = Sanitize(fileName);
        int size = data.Length;
        if ((long)size > 1024L && ShouldCompress(fileName))
        {
            using MemoryStream ms = new MemoryStream(data.Length);
            DeflateStream ds = new DeflateStream((Stream)ms, (CompressionMode)0);
            try
            {
                ((Stream)(object)ds).Write(data, 0, data.Length);
            }
            finally
            {
                ((IDisposable)ds)?.Dispose();
            }
            byte[] compressed = ms.ToArray();
            if ((float)compressed.Length < (float)size * 0.9f)
            {
                data = compressed;
            }
        }
        lock (files)
        {
            files[fileName] = new FileEntry(fileName, -1, size, data.Length, data);
        }
        fileTable = null;
    }
References Terraria.ModLoader.Core.TmodFile.files, Terraria.ModLoader.Core.TmodFile.fileTable, Terraria.ModLoader.Core.TmodFile.Sanitize(), and Terraria.ModLoader.Core.TmodFile.ShouldCompress().
Referenced by Terraria.ModLoader.Core.TmodFile.Upgrade().