TModLoader: Terraria.GameContent.ItemDropRules.CommonCode.DropItem
DropItem() [1/3]
static void Terraria.GameContent.ItemDropRules.CommonCode.DropItem (DropAttemptInfo info, int item, int stack, bool scattered = false) inline static
    {
        //IL_001d: Unknown result type (might be due to invalid IL or missing references)
        if (info.npc != null)
        {
            _DropItemFromNPC(info.npc, item, stack, scattered);
        }
        else
        {
            DropItem(info.player.Hitbox, info.player.GetItemSource_OpenItem(info.item), item, stack, scattered);
        }
    }
References Terraria.GameContent.ItemDropRules.CommonCode._DropItemFromNPC(), and Terraria.GameContent.ItemDropRules.CommonCode.DropItem().
Referenced by Terraria.GameContent.ItemDropRules.CommonCode._DropItemFromNPC(), Terraria.GameContent.ItemDropRules.CommonCode.DropItem(), Terraria.GameContent.ItemDropRules.CommonCode.DropItem(), Terraria.GameContent.ItemDropRules.CoinsRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.CommonDrop.TryDroppingItem(), Terraria.GameContent.ItemDropRules.CommonDropNotScalingWithLuck.TryDroppingItem(), Terraria.GameContent.ItemDropRules.CommonDropWithRerolls.TryDroppingItem(), Terraria.GameContent.ItemDropRules.DropOneByOne.TryDroppingItem(), Terraria.GameContent.ItemDropRules.FewFromOptionsDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.FewFromOptionsNotScaledWithLuckDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.HerbBagDropsItemDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.MechBossSpawnersDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.OneFromOptionsDropRule.TryDroppingItem(), Terraria.GameContent.ItemDropRules.OneFromOptionsNotScaledWithLuckDropRule.TryDroppingItem(), and Terraria.GameContent.ItemDropRules.SlimeBodyItemDropRule.TryDroppingItem().