TModLoader: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk
PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk()
SegmentInforReport Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_MerchantAndTravelingMerchantTryingToSellJunk (int startTime, Vector2 sceneAnchorPosition) inline private
Definition at line 1811 of file CreditsRollComposer.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_020a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        //IL_0289: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0294: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_031e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0320: Unknown result type (might be due to invalid IL or missing references)
        //IL_0325: Unknown result type (might be due to invalid IL or missing references)
        //IL_032d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03af: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0444: Unknown result type (might be due to invalid IL or missing references)
        //IL_0446: Unknown result type (might be due to invalid IL or missing references)
        //IL_044b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04db: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_056d: Unknown result type (might be due to invalid IL or missing references)
        //IL_056f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0574: Unknown result type (might be due to invalid IL or missing references)
        //IL_057c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0582: Unknown result type (might be due to invalid IL or missing references)
        //IL_0590: Unknown result type (might be due to invalid IL or missing references)
        //IL_0598: Unknown result type (might be due to invalid IL or missing references)
        //IL_059d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0600: Unknown result type (might be due to invalid IL or missing references)
        //IL_0605: Unknown result type (might be due to invalid IL or missing references)
        //IL_060e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0613: Unknown result type (might be due to invalid IL or missing references)
        //IL_061c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0621: Unknown result type (might be due to invalid IL or missing references)
        //IL_062a: Unknown result type (might be due to invalid IL or missing references)
        //IL_062f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0638: Unknown result type (might be due to invalid IL or missing references)
        //IL_063d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0646: Unknown result type (might be due to invalid IL or missing references)
        //IL_064b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0654: Unknown result type (might be due to invalid IL or missing references)
        //IL_0659: Unknown result type (might be due to invalid IL or missing references)
        //IL_0662: Unknown result type (might be due to invalid IL or missing references)
        //IL_0667: Unknown result type (might be due to invalid IL or missing references)
        sceneAnchorPosition += GetSceneFixVector();
        int num = startTime;
        int num2 = 40;
        sceneAnchorPosition.X += num2;
        int num3 = 62;
        Asset<Texture2D> asset = TextureAssets.Extra[223];
        Rectangle rectangle = asset.Frame();
        DrawData data = new DrawData(asset.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2((float)num2, -42f), 1f, (SpriteEffects)0);
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(asset, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
            .Then(new Actions.Sprites.Wait(60));
        _segments.Add(animationSegmentWithActions);
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 17, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Wait(60));
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 368, sceneAnchorPosition + new Vector2((float)num3, 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Wait(60));
        Asset<Texture2D> asset2 = TextureAssets.Extra[239];
        Rectangle rectangle2 = asset2.Frame(1, 8);
        DrawData data2 = new DrawData(asset2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, (SpriteEffects)1);
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions4 = new Segments.SpriteSegment(asset2, num, data2, sceneAnchorPosition + new Vector2((float)(num2 - 128), 4f)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51));
        num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
        int num4 = 90;
        int num5 = 60;
        animationSegmentWithActions2.Then(new Actions.NPCs.ShowItem(num5, 8));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num5));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
        num += num5;
        Segments.EmoteSegment item = new Segments.EmoteSegment(11, num, num4, sceneAnchorPosition + new Vector2((float)num3, 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
        animationSegmentWithActions3.Then(new Actions.NPCs.ShowItem(num5, 2242));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
        num += num5;
        Segments.EmoteSegment item2 = new Segments.EmoteSegment(11, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        animationSegmentWithActions2.Then(new Actions.NPCs.ShowItem(num5, 88));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num5));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
        num += num5;
        Segments.EmoteSegment item3 = new Segments.EmoteSegment(11, num, num4, sceneAnchorPosition + new Vector2((float)num3, 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
        animationSegmentWithActions3.Then(new Actions.NPCs.ShowItem(num5, 4761));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
        num += num5;
        Segments.EmoteSegment item4 = new Segments.EmoteSegment(11, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        int num6 = num5 + 30;
        animationSegmentWithActions2.Then(new Actions.NPCs.ShowItem(num6, 2));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
        num += num6;
        Segments.EmoteSegment item5 = new Segments.EmoteSegment(10, num, num4, sceneAnchorPosition + new Vector2((float)num3, 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions3.Then(new Actions.NPCs.ShowItem(num6, 52));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
        num += num6;
        Segments.EmoteSegment item6 = new Segments.EmoteSegment(85, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item7 = new Segments.EmoteSegment(85, num, num4, sceneAnchorPosition + new Vector2((float)num3, 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        animationSegmentWithActions4.Then(new Actions.Sprites.SetFrameSequence(num - startTime, (Point[])(object)new Point[8]
        {
            new Point(0, 0),
            new Point(0, 1),
            new Point(0, 2),
            new Point(0, 3),
            new Point(0, 4),
            new Point(0, 5),
            new Point(0, 6),
            new Point(0, 7)
        }, 5, 0, 0));
        animationSegmentWithActions2.Then(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions3.Then(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions4.Then(new Actions.Sprites.Fade(0f, 127));
        animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
        num += 187;
        _segments.Add(animationSegmentWithActions4);
        _segments.Add(animationSegmentWithActions2);
        _segments.Add(animationSegmentWithActions3);
        _segments.Add(item);
        _segments.Add(item2);
        _segments.Add(item3);
        _segments.Add(item4);
        _segments.Add(item5);
        _segments.Add(item6);
        _segments.Add(item7);
        SegmentInforReport result = default(SegmentInforReport);
        result.totalTime = num - startTime;
        return result;
    }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._backgroundOffset, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnLeft, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnRight, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._originAtBottom, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._segments, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.GetSceneFixVector(), Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< T >.Then(), and Terraria.GameContent.Animations.Segments.SpriteSegment.UseShaderEffect().
Referenced by Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments().