TModLoader: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes
PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes()
SegmentInforReport Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_DemolitionistAndArmsDealerArguingThenNurseComes (int startTime, Vector2 sceneAnchorPosition) inline private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0066: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0077: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_0097: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0160: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_020c: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_025b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0266: Unknown result type (might be due to invalid IL or missing references)
        //IL_026b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0284: Unknown result type (might be due to invalid IL or missing references)
        //IL_0298: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_031a: Unknown result type (might be due to invalid IL or missing references)
        //IL_031f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0325: Unknown result type (might be due to invalid IL or missing references)
        //IL_0356: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_03de: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_03eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0402: Unknown result type (might be due to invalid IL or missing references)
        //IL_040e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0413: Unknown result type (might be due to invalid IL or missing references)
        //IL_0419: Unknown result type (might be due to invalid IL or missing references)
        //IL_041e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0426: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04da: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0501: Unknown result type (might be due to invalid IL or missing references)
        //IL_050d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0512: Unknown result type (might be due to invalid IL or missing references)
        //IL_0518: Unknown result type (might be due to invalid IL or missing references)
        //IL_051d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0525: Unknown result type (might be due to invalid IL or missing references)
        //IL_052b: Unknown result type (might be due to invalid IL or missing references)
        //IL_058b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0597: Unknown result type (might be due to invalid IL or missing references)
        //IL_059c: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_05a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_05db: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0614: Unknown result type (might be due to invalid IL or missing references)
        //IL_0636: Unknown result type (might be due to invalid IL or missing references)
        //IL_0668: Unknown result type (might be due to invalid IL or missing references)
        //IL_0693: Unknown result type (might be due to invalid IL or missing references)
        //IL_06be: Unknown result type (might be due to invalid IL or missing references)
        sceneAnchorPosition += GetSceneFixVector();
        int num = startTime;
        int num5 = -30;
        sceneAnchorPosition.X += num5;
        Asset<Texture2D> asset = TextureAssets.Extra[234];
        Rectangle rectangle = asset.Frame();
        DrawData data = new DrawData(asset.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2((float)num5, -42f), 1f, (SpriteEffects)0);
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(asset, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
            .Then(new Actions.Sprites.Wait(120));
        _segments.Add(animationSegmentWithActions);
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 38, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 60))
            .Then(new Actions.NPCs.Wait(60));
        int num6 = 90;
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 19, sceneAnchorPosition + new Vector2((float)(120 + num6), 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60))
            .Then(new Actions.NPCs.Wait(60));
        num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
        int num7 = 360;
        int num8 = 90;
        int num9 = 45;
        int num10 = 135;
        int num11 = 180;
        Segments.EmoteSegment item = new Segments.EmoteSegment(81, num, num8, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item3 = new Segments.EmoteSegment(82, num + num9, num8, sceneAnchorPosition + new Vector2((float)(60 + num6), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        Segments.EmoteSegment item4 = new Segments.EmoteSegment(135, num + num10, num8, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item5 = new Segments.EmoteSegment(135, num + num11, num8, sceneAnchorPosition + new Vector2((float)(60 + num6), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num7));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num7));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num7));
        num += num7;
        int num12 = num6 - 30;
        int num2 = 120;
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions4 = new Segments.NPCSegment(num - num2, 18, sceneAnchorPosition + new Vector2((float)(120 + num12), 0f), _originAtBottom).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51)).Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60))
            .Then(new Actions.NPCs.Wait(20));
        int num3 = (int)animationSegmentWithActions4.DedicatedTimeNeeded - num2;
        num += num3;
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num3));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num3));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num3));
        animationSegmentWithActions4.Then(new Actions.NPCs.LookAt(-1));
        Segments.EmoteSegment item6 = new Segments.EmoteSegment(77, num, num8, sceneAnchorPosition + new Vector2((float)(60 + num12), 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item7 = new Segments.EmoteSegment(15, num + num8, num8, sceneAnchorPosition + new Vector2((float)(60 + num12), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num8));
        num += num8;
        animationSegmentWithActions4.Then(new Actions.NPCs.LookAt(1));
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num8));
        num += num8;
        Segments.EmoteSegment item8 = new Segments.EmoteSegment(10, num, num8, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item9 = new Segments.EmoteSegment(10, num, num8, sceneAnchorPosition + new Vector2((float)(60 + num6), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num8));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num8));
        num += num8;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector(-1f, 0f);
        Segments.EmoteSegment item10 = new Segments.EmoteSegment(77, num, num8, sceneAnchorPosition + new Vector2((float)(60 + num6), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0, vector);
        Segments.EmoteSegment item2 = new Segments.EmoteSegment(77, num + num8 / 2, num8, sceneAnchorPosition + new Vector2(60f, 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0, vector);
        int num4 = num8 + num8 / 2;
        animationSegmentWithActions3.Then(new Actions.NPCs.Move(vector, num4));
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num8 / 2)).Then(new Actions.NPCs.Move(vector, num8));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num8 / 2 + 20)).Then(new Actions.NPCs.Move(vector, num8 - 20));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
        num += 187;
        _segments.Add(animationSegmentWithActions4);
        _segments.Add(animationSegmentWithActions2);
        _segments.Add(animationSegmentWithActions3);
        _segments.Add(item);
        _segments.Add(item3);
        _segments.Add(item4);
        _segments.Add(item5);
        _segments.Add(item6);
        _segments.Add(item7);
        _segments.Add(item8);
        _segments.Add(item9);
        _segments.Add(item2);
        _segments.Add(item10);
        SegmentInforReport result = default(SegmentInforReport);
        result.totalTime = num - startTime;
        return result;
    }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._backgroundOffset, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnLeft, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnRight, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._originAtBottom, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._segments, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.GetSceneFixVector(), Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< T >.Then(), and Terraria.GameContent.Animations.Segments.SpriteSegment.UseShaderEffect().
Referenced by Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments().