TModLoader: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WitchDoctorGoingToHisPeople
PlaySegment_Grox_WitchDoctorGoingToHisPeople()
SegmentInforReport Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WitchDoctorGoingToHisPeople (int startTime, Vector2 sceneAnchorPosition) inline private
Definition at line 1105 of file CreditsRollComposer.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0035: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_005a: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_0174: Unknown result type (might be due to invalid IL or missing references)
        //IL_0179: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0207: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0226: Unknown result type (might be due to invalid IL or missing references)
        //IL_022b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_0250: Unknown result type (might be due to invalid IL or missing references)
        //IL_0255: Unknown result type (might be due to invalid IL or missing references)
        //IL_028a: Unknown result type (might be due to invalid IL or missing references)
        //IL_028f: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_029f: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0309: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0334: Unknown result type (might be due to invalid IL or missing references)
        //IL_0339: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_0399: Unknown result type (might be due to invalid IL or missing references)
        //IL_03db: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_041d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0428: Unknown result type (might be due to invalid IL or missing references)
        //IL_042d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0433: Unknown result type (might be due to invalid IL or missing references)
        //IL_0438: Unknown result type (might be due to invalid IL or missing references)
        //IL_0440: Unknown result type (might be due to invalid IL or missing references)
        //IL_0446: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0508: Unknown result type (might be due to invalid IL or missing references)
        //IL_050d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0513: Unknown result type (might be due to invalid IL or missing references)
        //IL_0518: Unknown result type (might be due to invalid IL or missing references)
        //IL_0520: Unknown result type (might be due to invalid IL or missing references)
        //IL_0526: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0604: Unknown result type (might be due to invalid IL or missing references)
        //IL_060a: Unknown result type (might be due to invalid IL or missing references)
        //IL_060f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0617: Unknown result type (might be due to invalid IL or missing references)
        //IL_061d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0691: Unknown result type (might be due to invalid IL or missing references)
        //IL_069c: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_06a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_0721: Unknown result type (might be due to invalid IL or missing references)
        //IL_072b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0730: Unknown result type (might be due to invalid IL or missing references)
        //IL_0736: Unknown result type (might be due to invalid IL or missing references)
        //IL_073b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0743: Unknown result type (might be due to invalid IL or missing references)
        //IL_0749: Unknown result type (might be due to invalid IL or missing references)
        //IL_075b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0768: Unknown result type (might be due to invalid IL or missing references)
        //IL_076d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0773: Unknown result type (might be due to invalid IL or missing references)
        //IL_0778: Unknown result type (might be due to invalid IL or missing references)
        //IL_0780: Unknown result type (might be due to invalid IL or missing references)
        //IL_0786: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0807: Unknown result type (might be due to invalid IL or missing references)
        //IL_080d: Unknown result type (might be due to invalid IL or missing references)
        //IL_081a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0825: Unknown result type (might be due to invalid IL or missing references)
        //IL_082a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0830: Unknown result type (might be due to invalid IL or missing references)
        //IL_0835: Unknown result type (might be due to invalid IL or missing references)
        //IL_083d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0843: Unknown result type (might be due to invalid IL or missing references)
        //IL_08a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0904: Unknown result type (might be due to invalid IL or missing references)
        //IL_0932: Unknown result type (might be due to invalid IL or missing references)
        sceneAnchorPosition += GetSceneFixVector();
        int num = startTime;
        int num2 = 0;
        sceneAnchorPosition.X += num2;
        int num3 = 60;
        Asset<Texture2D> asset = TextureAssets.Extra[231];
        Rectangle rectangle = asset.Frame();
        DrawData data = new DrawData(asset.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2((float)num2, -42f), 1f, (SpriteEffects)0);
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(asset, startTime, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
            .Then(new Actions.Sprites.Wait(120));
        _segments.Add(animationSegmentWithActions);
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 228, sceneAnchorPosition + new Vector2(-60f, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 120));
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 663, sceneAnchorPosition + new Vector2(-110f, 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 120));
        Point[] frameIndices = (Point[])(object)new Point[5]
        {
            new Point(0, 3),
            new Point(0, 4),
            new Point(0, 5),
            new Point(0, 6),
            new Point(0, 7)
        };
        Point[] frameIndices2 = (Point[])(object)new Point[4]
        {
            new Point(0, 3),
            new Point(0, 2),
            new Point(0, 1),
            new Point(0, 0)
        };
        Main.instance.LoadNPC(199);
        Asset<Texture2D> asset2 = TextureAssets.Npc[199];
        Rectangle rectangle2 = asset2.Frame(1, Main.npcFrameCount[199]);
        DrawData data2 = new DrawData(asset2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, (SpriteEffects)0);
        new DrawData(asset2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, (SpriteEffects)1);
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions4 = new Segments.NPCSegment(startTime, 198, sceneAnchorPosition + new Vector2((float)(num3 * 2), 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Wait(120));
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions5 = new Segments.SpriteSegment(asset2, startTime, data2, sceneAnchorPosition + new Vector2((float)(num3 * 3 - 20 + 120), 4f)).Then(new Actions.Sprites.SetFrame(0, 3, 0, 0)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 25))
            .Then(new Actions.Sprites.SimulateGravity(new Vector2(-1f, 0f), Vector2.Zero, 0f, 120))
            .With(new Actions.Sprites.SetFrameSequence(120, frameIndices, 6, 0, 0));
        num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
        int num4 = 120;
        Segments.EmoteSegment item = new Segments.EmoteSegment(10, num, num4, sceneAnchorPosition + new Vector2(0f, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        int num5 = 6;
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions5.Then(new Actions.Sprites.SetFrameSequence(frameIndices2, num5, 0, 0));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        int durationInFrames = num4 - num5 * 4;
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions6 = new Segments.NPCSegment(num - num4 + num5 * 4, 198, sceneAnchorPosition + new Vector2((float)(num3 * 3 - 20), 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Wait(durationInFrames));
        Segments.EmoteSegment item2 = new Segments.EmoteSegment(92, num, num4, sceneAnchorPosition + new Vector2(-50f, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions2.Then(new Actions.NPCs.LookAt(-1));
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        int num6 = 60;
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), num6));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
        num += num6;
        Segments.EmoteSegment item3 = new Segments.EmoteSegment(87, num, num4, sceneAnchorPosition + new Vector2((float)(num3 * 2), 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4)).Then(new Actions.NPCs.LookAt(-1));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4)).Then(new Actions.NPCs.LookAt(-1));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        Segments.EmoteSegment item4 = new Segments.EmoteSegment(49, num, num4, sceneAnchorPosition + new Vector2(30f, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        int num7 = num4 + num4 / 2;
        Segments.EmoteSegment item5 = new Segments.EmoteSegment(10, num, num4, sceneAnchorPosition + new Vector2((float)(num3 * 2), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        Segments.EmoteSegment item6 = new Segments.EmoteSegment(0, num + num4 / 2, num4, sceneAnchorPosition + new Vector2((float)(num3 * 3 - 20), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num7));
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num7));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num7));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num7));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num7));
        num += num7;
        Segments.EmoteSegment item7 = new Segments.EmoteSegment(17, num, num4, sceneAnchorPosition + new Vector2(-50f, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item8 = new Segments.EmoteSegment(3, num, num4, sceneAnchorPosition + new Vector2(30f, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(-0.4f, 0f), 160)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), 160)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(-0.8f, 0f), 160)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions6.Then(new Actions.NPCs.Move(new Vector2(-0.8f, 0f), 160)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
        num += 187;
        _segments.Add(animationSegmentWithActions4);
        _segments.Add(animationSegmentWithActions6);
        _segments.Add(animationSegmentWithActions5);
        _segments.Add(animationSegmentWithActions2);
        _segments.Add(animationSegmentWithActions3);
        _segments.Add(item);
        _segments.Add(item2);
        _segments.Add(item3);
        _segments.Add(item4);
        _segments.Add(item5);
        _segments.Add(item6);
        _segments.Add(item8);
        _segments.Add(item7);
        SegmentInforReport result = default(SegmentInforReport);
        result.totalTime = num - startTime;
        return result;
    }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._backgroundOffset, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnLeft, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnRight, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._originAtBottom, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._segments, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.GetSceneFixVector(), Terraria.Main.instance, Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npcFrameCount, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< T >.Then(), and Terraria.GameContent.Animations.Segments.SpriteSegment.UseShaderEffect().
Referenced by Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments().