TModLoader: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies
PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies()
SegmentInforReport Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_Grox_WizardPartyGirlDyeTraderAndPainterPartyWithBunnies (int startTime, Vector2 sceneAnchorPosition) inline private
Definition at line 2472 of file CreditsRollComposer.cs.
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0007: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0045: Unknown result type (might be due to invalid IL or missing references)
        //IL_004a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0161: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01be: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_020f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_023d: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0323: Unknown result type (might be due to invalid IL or missing references)
        //IL_0328: Unknown result type (might be due to invalid IL or missing references)
        //IL_0333: Unknown result type (might be due to invalid IL or missing references)
        //IL_0338: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0349: Unknown result type (might be due to invalid IL or missing references)
        //IL_034b: Unknown result type (might be due to invalid IL or missing references)
        //IL_035a: Unknown result type (might be due to invalid IL or missing references)
        //IL_035f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_0389: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_0410: Unknown result type (might be due to invalid IL or missing references)
        //IL_0412: Unknown result type (might be due to invalid IL or missing references)
        //IL_0417: Unknown result type (might be due to invalid IL or missing references)
        //IL_041f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0425: Unknown result type (might be due to invalid IL or missing references)
        //IL_0435: Unknown result type (might be due to invalid IL or missing references)
        //IL_043d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_0448: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0455: Unknown result type (might be due to invalid IL or missing references)
        //IL_045b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0471: Unknown result type (might be due to invalid IL or missing references)
        //IL_047b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0480: Unknown result type (might be due to invalid IL or missing references)
        //IL_0486: Unknown result type (might be due to invalid IL or missing references)
        //IL_048b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0493: Unknown result type (might be due to invalid IL or missing references)
        //IL_0499: Unknown result type (might be due to invalid IL or missing references)
        //IL_04af: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04be: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0545: Unknown result type (might be due to invalid IL or missing references)
        //IL_0570: Unknown result type (might be due to invalid IL or missing references)
        //IL_0590: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_05dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_063b: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_06da: Unknown result type (might be due to invalid IL or missing references)
        //IL_06df: Unknown result type (might be due to invalid IL or missing references)
        //IL_06e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_06ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_0782: Unknown result type (might be due to invalid IL or missing references)
        //IL_0784: Unknown result type (might be due to invalid IL or missing references)
        //IL_0789: Unknown result type (might be due to invalid IL or missing references)
        //IL_0791: Unknown result type (might be due to invalid IL or missing references)
        //IL_0797: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_07bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_07c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_07df: Unknown result type (might be due to invalid IL or missing references)
        //IL_07e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0801: Unknown result type (might be due to invalid IL or missing references)
        //IL_0807: Unknown result type (might be due to invalid IL or missing references)
        //IL_0814: Unknown result type (might be due to invalid IL or missing references)
        //IL_0821: Unknown result type (might be due to invalid IL or missing references)
        //IL_0826: Unknown result type (might be due to invalid IL or missing references)
        //IL_082c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0831: Unknown result type (might be due to invalid IL or missing references)
        //IL_0839: Unknown result type (might be due to invalid IL or missing references)
        //IL_083f: Unknown result type (might be due to invalid IL or missing references)
        //IL_084c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0859: Unknown result type (might be due to invalid IL or missing references)
        //IL_085e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0864: Unknown result type (might be due to invalid IL or missing references)
        //IL_0869: Unknown result type (might be due to invalid IL or missing references)
        //IL_0871: Unknown result type (might be due to invalid IL or missing references)
        //IL_0877: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0902: Unknown result type (might be due to invalid IL or missing references)
        //IL_090b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0910: Unknown result type (might be due to invalid IL or missing references)
        //IL_0919: Unknown result type (might be due to invalid IL or missing references)
        //IL_091e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0927: Unknown result type (might be due to invalid IL or missing references)
        //IL_092c: Unknown result type (might be due to invalid IL or missing references)
        //IL_094f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0954: Unknown result type (might be due to invalid IL or missing references)
        //IL_095d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0962: Unknown result type (might be due to invalid IL or missing references)
        //IL_096b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0970: Unknown result type (might be due to invalid IL or missing references)
        //IL_0979: Unknown result type (might be due to invalid IL or missing references)
        //IL_097e: Unknown result type (might be due to invalid IL or missing references)
        //IL_099e: Unknown result type (might be due to invalid IL or missing references)
        //IL_09c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a4a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a75: Unknown result type (might be due to invalid IL or missing references)
        sceneAnchorPosition += GetSceneFixVector();
        int num = startTime;
        int num2 = -35;
        sceneAnchorPosition.X += num2;
        int num3 = 34;
        Asset<Texture2D> asset = TextureAssets.Extra[221];
        Rectangle rectangle = asset.Frame();
        DrawData data = new DrawData(asset.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2((float)num2, -42f), 1f, (SpriteEffects)0);
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions = new Segments.SpriteSegment(asset, num, data, sceneAnchorPosition + _backgroundOffset).UseShaderEffect(new Segments.SpriteSegment.MaskedFadeEffect()).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 60))
            .Then(new Actions.Sprites.Wait(60));
        _segments.Add(animationSegmentWithActions);
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions2 = new Segments.NPCSegment(startTime, 227, sceneAnchorPosition, _originAtBottom).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Fade(255))
            .With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Wait(60));
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions3 = new Segments.NPCSegment(startTime, 108, sceneAnchorPosition + new Vector2((float)num3, 0f), _originAtBottom).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255))
            .With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Wait(60));
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions4 = new Segments.NPCSegment(startTime, 207, sceneAnchorPosition + new Vector2((float)(num3 * 2 + 60), 0f), _originAtBottom).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255))
            .With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60));
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions5 = new Segments.NPCSegment(startTime, 656, sceneAnchorPosition + new Vector2((float)(num3 * 2), 0f), _originAtBottom).Then(new Actions.NPCs.Variant(1)).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(1))
            .Then(new Actions.NPCs.Fade(255))
            .With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 60));
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions6 = new Segments.NPCSegment(startTime, 540, sceneAnchorPosition + new Vector2((float)(num3 * 4 + 100), 0f), _originAtBottom).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255)).With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60));
        Asset<Texture2D> asset2 = TextureAssets.Extra[238];
        Rectangle rectangle2 = asset2.Frame(1, 4);
        DrawData data2 = new DrawData(asset2.Value, Vector2.Zero, rectangle2, Color.White, 0f, rectangle2.Size() * new Vector2(0.5f, 1f), 1f, (SpriteEffects)1);
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions7 = new Segments.SpriteSegment(asset2, num, data2, sceneAnchorPosition + new Vector2(60f, 2f)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51));
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> animationSegmentWithActions8 = new Segments.SpriteSegment(asset2, num, data2, sceneAnchorPosition + new Vector2(150f, 2f)).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51));
        num += (int)animationSegmentWithActions2.DedicatedTimeNeeded;
        int num4 = 90;
        int num5 = num4 * 4;
        Segments.EmoteSegment item = new Segments.EmoteSegment(127, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item3 = new Segments.EmoteSegment(6, num + num4, num4, sceneAnchorPosition + new Vector2((float)num3, 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        Segments.EmoteSegment item4 = new Segments.EmoteSegment(136, num + num4 * 2, num4, sceneAnchorPosition + new Vector2((float)(num3 * 2), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        Segments.EmoteSegment item5 = new Segments.EmoteSegment(129, num + num4 * 3, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num5));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4 * 2)).Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Wait(num4))
            .Then(new Actions.NPCs.LookAt(-1))
            .Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num5));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num5));
        animationSegmentWithActions6.Then(new Actions.NPCs.Move(new Vector2(-0.5f, 0f), num5 / 3)).Then(new Actions.NPCs.Wait(num5 / 3)).Then(new Actions.NPCs.Move(new Vector2(0.4f, 0f), num5 / 3));
        animationSegmentWithActions5.Then(new Actions.NPCs.Move(new Vector2(-0.6f, 0f), num5 / 3)).Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), num5 / 3)).Then(new Actions.NPCs.Wait(num5 / 3));
        num += num5;
        Segments.AnimationSegmentWithActions<NPC> animationSegmentWithActions9 = new Segments.NPCSegment(num - 60, 208, sceneAnchorPosition + new Vector2((float)(num3 * 5 + 100), 0f), _originAtBottom).Then(new Actions.NPCs.PartyHard()).Then(new Actions.NPCs.LookAt(-1)).Then(new Actions.NPCs.Fade(255))
            .With(new Actions.NPCs.Fade(-5, 51))
            .Then(new Actions.NPCs.Move(new Vector2(-1f, 0f), 60));
        int num6 = (int)animationSegmentWithActions9.DedicatedTimeNeeded - 60;
        num += num6;
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions5.Then(new Actions.NPCs.Wait(num6));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num6));
        Segments.EmoteSegment item6 = new Segments.EmoteSegment(128, num, num4, sceneAnchorPosition + new Vector2((float)(num3 * 5 + 40), 0f) + _emoteBubbleOffsetWhenOnRight, (SpriteEffects)0);
        num += num4;
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions3.Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions4.Then(new Actions.NPCs.LookAt(1)).Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions5.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions9.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        Segments.EmoteSegment item7 = new Segments.EmoteSegment(128, num, num4, sceneAnchorPosition + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item8 = new Segments.EmoteSegment(128, num, num4, sceneAnchorPosition + new Vector2((float)num3, 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item9 = new Segments.EmoteSegment(128, num, num4, sceneAnchorPosition + new Vector2((float)(num3 * 2), 0f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item10 = new Segments.EmoteSegment(3, num, num4, sceneAnchorPosition + new Vector2((float)(num3 * 5 - 10), 24f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        Segments.EmoteSegment item2 = new Segments.EmoteSegment(0, num, num4, sceneAnchorPosition + new Vector2((float)(num3 * 4 - 20), 24f) + _emoteBubbleOffsetWhenOnLeft, (SpriteEffects)1);
        animationSegmentWithActions2.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions3.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions4.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions6.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions5.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions9.Then(new Actions.NPCs.Wait(num4));
        animationSegmentWithActions.Then(new Actions.Sprites.Wait(num4));
        num += num4;
        animationSegmentWithActions7.Then(new Actions.Sprites.SetFrameSequence(num - startTime, (Point[])(object)new Point[4]
        {
            new Point(0, 0),
            new Point(0, 1),
            new Point(0, 2),
            new Point(0, 3)
        }, 10, 0, 0));
        animationSegmentWithActions8.Then(new Actions.Sprites.SetFrameSequence(num - startTime, (Point[])(object)new Point[4]
        {
            new Point(0, 2),
            new Point(0, 3),
            new Point(0, 0),
            new Point(0, 1)
        }, 10, 0, 0));
        animationSegmentWithActions2.Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions3.Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions4.Then(new Actions.NPCs.Move(new Vector2(1f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions6.Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions5.Then(new Actions.NPCs.Move(new Vector2(0.75f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions9.Then(new Actions.NPCs.Move(new Vector2(0.5f, 0f), 120)).With(new Actions.NPCs.Fade(2, 127));
        animationSegmentWithActions7.Then(new Actions.Sprites.Fade(0f, 127));
        animationSegmentWithActions8.Then(new Actions.Sprites.Fade(0f, 127));
        animationSegmentWithActions.Then(new Actions.Sprites.Fade(0f, 127));
        num += 187;
        _segments.Add(animationSegmentWithActions7);
        _segments.Add(animationSegmentWithActions8);
        _segments.Add(animationSegmentWithActions2);
        _segments.Add(animationSegmentWithActions3);
        _segments.Add(animationSegmentWithActions4);
        _segments.Add(animationSegmentWithActions6);
        _segments.Add(animationSegmentWithActions5);
        _segments.Add(animationSegmentWithActions9);
        _segments.Add(item);
        _segments.Add(item3);
        _segments.Add(item4);
        _segments.Add(item5);
        _segments.Add(item6);
        _segments.Add(item7);
        _segments.Add(item8);
        _segments.Add(item9);
        _segments.Add(item10);
        _segments.Add(item2);
        SegmentInforReport result = default(SegmentInforReport);
        result.totalTime = num - startTime;
        return result;
    }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._backgroundOffset, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnLeft, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._emoteBubbleOffsetWhenOnRight, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._originAtBottom, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._segments, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.GetSceneFixVector(), Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< T >.Then(), and Terraria.GameContent.Animations.Segments.SpriteSegment.UseShaderEffect().
Referenced by Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments().