TModLoader: Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_PrincessAndEveryoneThanksPlayer
PlaySegment_PrincessAndEveryoneThanksPlayer()
SegmentInforReport Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.PlaySegment_PrincessAndEveryoneThanksPlayer (int startTime, Vector2 sceneAnchorPosition) inline private
Definition at line 234 of file CreditsRollComposer.cs.
    {
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0196: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0216: Unknown result type (might be due to invalid IL or missing references)
        //IL_0260: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_0270: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_027c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0286: Unknown result type (might be due to invalid IL or missing references)
        //IL_0288: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_029c: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_033e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0398: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0405: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        sceneAnchorPosition.Y += 40f;
        int num = -2;
        int num3 = 2;
        List<int> list = new List<int> { 228, 178, 550, 208, 160, 209 };
        List<int> list2 = new List<int> { 353, 633, 207, 588, 227, 368 };
        List<int> list3 = new List<int> { 22, 19, 18, 17, 38, 54, 108 };
        List<int> list4 = new List<int> { 663, 20, 441, 107, 124, 229, 369 };
        List<SimplifiedNPCInfo> list5 = new List<SimplifiedNPCInfo>();
        for (int i = 0; i < list.Count; i++)
        {
            int npcType = list[i];
            list5.Add(new SimplifiedNPCInfo(npcType, new Vector2((float)(num - i), -1f)));
        }
        for (int j = 0; j < list3.Count; j++)
        {
            int npcType2 = list3[j];
            list5.Add(new SimplifiedNPCInfo(npcType2, new Vector2((float)(num - j) + 0.5f, 0f)));
        }
        for (int k = 0; k < list2.Count; k++)
        {
            int npcType3 = list2[k];
            list5.Add(new SimplifiedNPCInfo(npcType3, new Vector2((float)(num3 + k), -1f)));
        }
        for (int l = 0; l < list4.Count; l++)
        {
            int npcType4 = list4[l];
            list5.Add(new SimplifiedNPCInfo(npcType4, new Vector2((float)(num3 + l) - 0.5f, 0f)));
        }
        int num4 = 240;
        int num5 = 400;
        int num6 = num5 + num4;
        Asset<Texture2D> asset = TextureAssets.Extra[241];
        Rectangle rectangle = asset.Frame();
        DrawData data = new DrawData(asset.Value, Vector2.Zero, rectangle, Color.White, 0f, rectangle.Size() * new Vector2(0.5f, 1f) + new Vector2(0f, -92f), 1f, (SpriteEffects)0);
        Segments.AnimationSegmentWithActions<Segments.LooseSprite> item = new Segments.SpriteSegment(asset, startTime, data, sceneAnchorPosition).Then(new Actions.Sprites.Fade(0f)).With(new Actions.Sprites.Fade(1f, 51)).Then(new Actions.Sprites.Wait(num6))
            .Then(new Actions.Sprites.Fade(0f, 85));
        _segments.Add(item);
        foreach (SimplifiedNPCInfo item3 in list5)
        {
            item3.SpawnNPC(AddWavingNPC, sceneAnchorPosition, startTime, num6);
        }
        float num7 = 3f;
        float num8 = -0.05f;
        int num9 = 60;
        float num10 = num7 * (float)num9 + num8 * ((float)(num9 * num9) * 0.5f);
        int num11 = startTime + num4;
        int num2 = 51;
        Segments.AnimationSegmentWithActions<Player> item2 = new Segments.PlayerSegment(num11 - num9 + num2, sceneAnchorPosition + new Vector2(0f, 0f - num10), _originAtBottom).UseShaderEffect(new Segments.PlayerSegment.ImmediateSpritebatchForPlayerDyesEffect()).Then(new Actions.Players.Fade(0f)).With(new Actions.Players.LookAt(1))
            .With(new Actions.Players.Fade(1f, num9))
            .Then(new Actions.Players.Wait(num5 / 2))
            .With(new Actions.Players.MoveWithAcceleration(new Vector2(0f, num7), new Vector2(0f, num8), num9))
            .Then(new Actions.Players.Wait(num5 / 2 - 60))
            .With(new Actions.Players.LookAt(-1))
            .Then(new Actions.Players.Wait(120))
            .With(new Actions.Players.LookAt(1))
            .Then(new Actions.Players.Fade(0f, 85));
        _segments.Add(item2);
        SegmentInforReport result = default(SegmentInforReport);
        result.totalTime = num6 + 85 + 60;
        return result;
    }
References Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._originAtBottom, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer._segments, Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.AddWavingNPC(), Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.Animations.Segments.AnimationSegmentWithActions< T >.Then(), and Terraria.GameContent.Animations.Segments.PlayerSegment.UseShaderEffect().
Referenced by Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments(), and Terraria.GameContent.Skies.CreditsRoll.CreditsRollComposer.FillSegments_Test().