TModLoader: Terraria.ID.ContentSamples.CreativeHelper.ItemGroupAndOrderInGroup.ItemGroupAndOrderInGroup
ItemGroupAndOrderInGroup()
Terraria.ID.ContentSamples.CreativeHelper.ItemGroupAndOrderInGroup.ItemGroupAndOrderInGroup (Item item) inline
            {
                ItemType = item.type;
                try
                {
                    Group = GetItemGroup(item, out OrderInGroup);
                }
                catch (Exception e)
                {
                    throw new Exception("An exception occured while processing " + (ItemLoader.IsModItem(item.type) ? item.ModItem.FullName : item.Name), e);
                }
                ItemLoader.ModifyResearchSorting(item, ref Group);
            }
References Terraria.ModLoader.ModType< TEntity, TModType >.FullName, Terraria.ID.ContentSamples.CreativeHelper.GetItemGroup(), Terraria.ID.ContentSamples.CreativeHelper.ItemGroupAndOrderInGroup.Group, Terraria.ModLoader.ItemLoader.IsModItem(), Terraria.ID.ContentSamples.CreativeHelper.ItemGroupAndOrderInGroup.ItemType, Terraria.ModLoader.ItemLoader.ModifyResearchSorting(), Terraria.Item.ModItem, Terraria.Item.Name, Terraria.ID.ContentSamples.CreativeHelper.ItemGroupAndOrderInGroup.OrderInGroup, and Terraria.Item.type.