TModLoader: Terraria.ModLoader.ModContent.Load
Load()
static void Terraria.ModLoader.ModContent.Load (CancellationToken token) inline static package
    {
        CacheVanillaState();
        Interface.loadMods.SetLoadStage("tModLoader.MSLoading", ModLoader.Mods.Length);
        LoadModContent(token, delegate(Mod mod)
        {
            if (mod.Code != Assembly.GetExecutingAssembly())
            {
                AssemblyManager.JITMod(mod);
            }
            ContentInstance.Register(mod);
            mod.loading = true;
            mod.AutoloadConfig();
            mod.PrepareAssets();
            mod.Autoload();
            mod.Load();
            SystemLoader.OnModLoad(mod);
            mod.loading = false;
        });
        Interface.loadMods.SetLoadStage("tModLoader.MSResizing");
        ResizeArrays();
        RecipeGroupHelper.CreateRecipeGroupLookups();
        Main.ResourceSetsManager.AddModdedDisplaySets();
        Main.ResourceSetsManager.SetActiveFromOriginalConfigKey();
        Interface.loadMods.SetLoadStage("tModLoader.MSSetupContent", ModLoader.Mods.Length);
        LanguageManager.Instance.ReloadLanguage(resetValuesToKeysFirst: false);
        LoadModContent(token, delegate(Mod mod)
        {
            mod.SetupContent();
        });
        ContentSamples.Initialize();
        TileLoader.PostSetupContent();
        BuffLoader.PostSetupContent();
        Interface.loadMods.SetLoadStage("tModLoader.MSPostSetupContent", ModLoader.Mods.Length);
        LoadModContent(token, delegate(Mod mod)
        {
            mod.PostSetupContent();
            SystemLoader.PostSetupContent(mod);
            mod.TransferAllAssets();
        });
        MemoryTracking.Finish();
        if (Main.dedServ)
        {
            ModNet.AssignNetIDs();
        }
        ModNet.SetModNetDiagnosticsUI(ModLoader.Mods);
        Main.player[255] = new Player();
        BuffLoader.FinishSetup();
        ItemLoader.FinishSetup();
        NPCLoader.FinishSetup();
        PrefixLoader.FinishSetup();
        ProjectileLoader.FinishSetup();
        PylonLoader.FinishSetup();
        TileLoader.FinishSetup();
        WallLoader.FinishSetup();
        EmoteBubbleLoader.FinishSetup();
        MapLoader.FinishSetup();
        PlantLoader.FinishSetup();
        RarityLoader.FinishSetup();
        ConfigManager.FinishSetup();
        SystemLoader.ModifyGameTipVisibility(Main.gameTips.allTips);
        PlayerInput.reinitialize = true;
        SetupBestiary();
        NPCShopDatabase.Initialize();
        SetupRecipes(token);
        NPCShopDatabase.FinishSetup();
        ContentSamples.RebuildItemCreativeSortingIDsAfterRecipesAreSetUp();
        ItemSorting.SetupWhiteLists();
        LocalizationLoader.FinishSetup();
        MenuLoader.GotoSavedModMenu();
        BossBarLoader.GotoSavedStyle();
        ModOrganizer.SaveLastLaunchedMods();
    }
References Terraria.GameContent.UI.GameTipsDisplay.allTips, Terraria.ModLoader.ModNet.AssignNetIDs(), Terraria.ModLoader.Mod.Autoload(), Terraria.ModLoader.Mod.AutoloadConfig(), Terraria.ModLoader.ModContent.CacheVanillaState(), Terraria.ModLoader.Mod.Code, Terraria.ModLoader.Utilities.RecipeGroupHelper.CreateRecipeGroupLookups(), Terraria.Main.dedServ, Terraria.ModLoader.Core.MemoryTracking.Finish(), Terraria.ModLoader.Config.ConfigManager.FinishSetup(), Terraria.ModLoader.BuffLoader.FinishSetup(), Terraria.ModLoader.EmoteBubbleLoader.FinishSetup(), Terraria.ModLoader.ItemLoader.FinishSetup(), Terraria.ModLoader.LocalizationLoader.FinishSetup(), Terraria.ModLoader.MapLoader.FinishSetup(), Terraria.ModLoader.NPCLoader.FinishSetup(), Terraria.ModLoader.NPCShopDatabase.FinishSetup(), Terraria.ModLoader.PlantLoader.FinishSetup(), Terraria.ModLoader.PrefixLoader.FinishSetup(), Terraria.ModLoader.ProjectileLoader.FinishSetup(), Terraria.ModLoader.PylonLoader.FinishSetup(), Terraria.ModLoader.RarityLoader.FinishSetup(), Terraria.ModLoader.TileLoader.FinishSetup(), Terraria.ModLoader.WallLoader.FinishSetup(), Terraria.Main.gameTips, Terraria.ModLoader.MenuLoader.GotoSavedModMenu(), Terraria.ModLoader.BossBarLoader.GotoSavedStyle(), Terraria.ID.ContentSamples.Initialize(), Terraria.ModLoader.NPCShopDatabase.Initialize(), Terraria.Localization.LanguageManager.Instance, Terraria.ModLoader.Mod.Load(), Terraria.ModLoader.ModContent.LoadModContent(), Terraria.ModLoader.UI.Interface.loadMods, Terraria.ModLoader.SystemLoader.ModifyGameTipVisibility(), Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.SystemLoader.OnModLoad(), Terraria.Main.player, Terraria.ModLoader.BuffLoader.PostSetupContent(), Terraria.ModLoader.Mod.PostSetupContent(), Terraria.ModLoader.TileLoader.PostSetupContent(), Terraria.ModLoader.SystemLoader.PostSetupContent(), Terraria.ModLoader.Mod.PrepareAssets(), Terraria.ID.ContentSamples.RebuildItemCreativeSortingIDsAfterRecipesAreSetUp(), Terraria.ModLoader.ContentInstance< T >.Register(), Terraria.Localization.LanguageManager.ReloadLanguage(), Terraria.ModLoader.ModContent.ResizeArrays(), Terraria.Main.ResourceSetsManager, Terraria.ModLoader.Core.ModOrganizer.SaveLastLaunchedMods(), Terraria.ModLoader.UI.UILoadMods.SetLoadStage(), Terraria.ModLoader.ModNet.SetModNetDiagnosticsUI(), Terraria.ModLoader.ModContent.SetupBestiary(), Terraria.ModLoader.Mod.SetupContent(), Terraria.ModLoader.ModContent.SetupRecipes(), Terraria.UI.ItemSorting.SetupWhiteLists(), and Terraria.ModLoader.Mod.TransferAllAssets().
Referenced by Terraria.ModLoader.ModLoader.Load().