TModLoader: Terraria.ModLoader.ModContent.GetInstance< T >
GetInstance< T >()
static T Terraria.ModLoader.ModContent.GetInstance< T > () inline static
Returns the template instance of the provided content type (not the clone/new instance which gets added to Items/Players/NPCs etc. as the game is played).
Type Constraints
T : class
                                             : class
    {
        return ContentInstance<T>.Instance;
    }
Referenced by Terraria.ModLoader.ModContent.BuffType< T >(), Terraria.ModLoader.ModContent.DustType< T >(), Terraria.ModLoader.ModContent.EmoteBubbleType< T >(), Terraria.ModLoader.ModContent.GoreType< T >(), Terraria.ModLoader.ModContent.ItemType< T >(), Terraria.ModLoader.ModContent.MountType< T >(), Terraria.ModLoader.ModContent.NPCType< T >(), Terraria.ModLoader.ModContent.PrefixType< T >(), Terraria.ModLoader.ModContent.ProjectileType< T >(), Terraria.ModLoader.ModContent.PylonType< T >(), Terraria.ModLoader.ModContent.RarityType< T >(), Terraria.ModLoader.ModContent.TileEntityType< T >(), Terraria.ModLoader.ModContent.TileType< T >(), and Terraria.ModLoader.ModContent.WallType< T >().