TModLoader: Terraria.ModLoader.ModContent.OpenRead
OpenRead()
static Stream Terraria.ModLoader.ModContent.OpenRead (string assetName, bool newFileStream = false) inline static
    {
        if (!assetName.StartsWith("tmod:"))
        {
            return File.OpenRead(assetName);
        }
        SplitName(assetName.Substring(5).Replace('\\', '/'), out var modName, out var entryPath);
        return ModLoader.GetMod(modName).GetFileStream(entryPath, newFileStream);
    }
References Terraria.ModLoader.ModLoader.GetMod(), and Terraria.ModLoader.ModContent.SplitName().
Referenced by Terraria.ModLoader.MusicLoader.LoadMusic(), and Terraria.ModLoader.Engine.TMLContentManager.OpenStream().