TModLoader: Terraria.ModLoader.ModContent.SetupBestiary
SetupBestiary()
static void Terraria.ModLoader.ModContent.SetupBestiary () inline static private
    {
        BestiaryDatabase bestiaryDatabase = new BestiaryDatabase();
        new BestiaryDatabaseNPCsPopulator().Populate(bestiaryDatabase);
        Main.BestiaryDB = bestiaryDatabase;
        ContentSamples.RebuildBestiarySortingIDsByBestiaryDatabaseContents(bestiaryDatabase);
        ItemDropDatabase itemDropDatabase = new ItemDropDatabase();
        itemDropDatabase.Populate();
        Main.ItemDropsDB = itemDropDatabase;
        bestiaryDatabase.Merge(Main.ItemDropsDB);
        if (!Main.dedServ)
        {
            Main.BestiaryUI = new UIBestiaryTest(Main.BestiaryDB);
        }
        Main.ItemDropSolver = new ItemDropResolver(itemDropDatabase);
        Main.BestiaryTracker = new BestiaryUnlocksTracker();
    }
References Terraria.Main.BestiaryDB, Terraria.Main.dedServ, Terraria.Main.ItemDropsDB, Terraria.GameContent.ItemDropRules.ItemDropDatabase.Populate(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Populate(), and Terraria.ID.ContentSamples.RebuildBestiarySortingIDsByBestiaryDatabaseContents().
Referenced by Terraria.ModLoader.ModContent.Load(), and Terraria.ModLoader.ModContent.Unload().