TModLoader: Terraria.ModLoader.ModContent.Unload
Unload()
static void Terraria.ModLoader.ModContent.Unload () inline static package
Definition at line 563 of file ModContent.cs.
    {
        MonoModHooks.Clear();
        TypeCaching.Clear();
        ItemLoader.Unload();
        EquipLoader.Unload();
        PrefixLoader.Unload();
        DustLoader.Unload();
        TileLoader.Unload();
        PylonLoader.Unload();
        WallLoader.Unload();
        ProjectileLoader.Unload();
        NPCLoader.Unload();
        NPCHeadLoader.Unload();
        BossBarLoader.Unload();
        PlayerLoader.Unload();
        BuffLoader.Unload();
        MountLoader.Unload();
        RarityLoader.Unload();
        DamageClassLoader.Unload();
        InfoDisplayLoader.Unload();
        BuilderToggleLoader.Unload();
        ExtraJumpLoader.Unload();
        GoreLoader.Unload();
        PlantLoader.UnloadPlants();
        HairLoader.Unload();
        EmoteBubbleLoader.Unload();
        ResourceOverlayLoader.Unload();
        ResourceDisplaySetLoader.Unload();
        LoaderManager.Unload();
        GlobalBackgroundStyleLoader.Unload();
        PlayerDrawLayerLoader.Unload();
        SystemLoader.Unload();
        ResizeArrays(unloading: true);
        for (int i = 0; i < Recipe.maxRecipes; i++)
        {
            Main.recipe[i] = new Recipe();
        }
        Recipe.numRecipes = 0;
        RecipeGroupHelper.ResetRecipeGroups();
        Recipe.SetupRecipes();
        TileEntity.manager.Reset();
        MapLoader.UnloadModMap();
        ItemSorting.SetupWhiteLists();
        RecipeLoader.Unload();
        CommandLoader.Unload();
        TagSerializer.Reload();
        ModNet.Unload();
        ConfigManager.Unload();
        CustomCurrencyManager.Initialize();
        EffectsTracker.RemoveModEffects();
        Main.MapIcons = new MapIconOverlay().AddLayer(new SpawnMapLayer()).AddLayer(new TeleportPylonsMapLayer()).AddLayer(Main.Pings);
        ItemTrader.ChlorophyteExtractinator = ItemTrader.CreateChlorophyteExtractinator();
        Main.gameTips.Reset();
        CreativeItemSacrificesCatalog.Instance.Initialize();
        ContentSamples.Initialize();
        SetupBestiary();
        LocalizationLoader.Unload();
        CleanupModReferences();
    }
References Terraria.Map.MapIconOverlay.AddLayer(), Terraria.ModLoader.ModContent.CleanupModReferences(), Terraria.ModLoader.Core.TypeCaching.Clear(), Terraria.ModLoader.MonoModHooks.Clear(), Terraria.GameContent.ItemTrader.CreateChlorophyteExtractinator(), Terraria.Main.gameTips, Terraria.GameContent.UI.CustomCurrencyManager.Initialize(), Terraria.ID.ContentSamples.Initialize(), Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Instance, Terraria.DataStructures.TileEntity.manager, Terraria.Recipe.maxRecipes, Terraria.Main.Pings, Terraria.Main.recipe, Terraria.ModLoader.IO.TagSerializer< T, S >.Reload(), Terraria.ModLoader.Engine.EffectsTracker.RemoveModEffects(), Terraria.ModLoader.Utilities.RecipeGroupHelper.ResetRecipeGroups(), Terraria.ModLoader.ModContent.ResizeArrays(), Terraria.ModLoader.ModContent.SetupBestiary(), Terraria.Recipe.SetupRecipes(), Terraria.UI.ItemSorting.SetupWhiteLists(), Terraria.ModLoader.Config.ConfigManager.Unload(), Terraria.ModLoader.BossBarLoader.Unload(), Terraria.ModLoader.BuffLoader.Unload(), Terraria.ModLoader.BuilderToggleLoader.Unload(), Terraria.ModLoader.CommandLoader.Unload(), Terraria.ModLoader.DamageClassLoader.Unload(), Terraria.ModLoader.DustLoader.Unload(), Terraria.ModLoader.EmoteBubbleLoader.Unload(), Terraria.ModLoader.EquipLoader.Unload(), Terraria.ModLoader.ExtraJumpLoader.Unload(), Terraria.ModLoader.GlobalBackgroundStyleLoader.Unload(), Terraria.ModLoader.GoreLoader.Unload(), Terraria.ModLoader.HairLoader.Unload(), Terraria.ModLoader.InfoDisplayLoader.Unload(), Terraria.ModLoader.ItemLoader.Unload(), Terraria.ModLoader.LoaderManager.Unload(), Terraria.ModLoader.LocalizationLoader.Unload(), Terraria.ModLoader.ModNet.Unload(), Terraria.ModLoader.MountLoader.Unload(), Terraria.ModLoader.NPCHeadLoader.Unload(), Terraria.ModLoader.NPCLoader.Unload(), Terraria.ModLoader.PlayerDrawLayerLoader.Unload(), Terraria.ModLoader.PlayerLoader.Unload(), Terraria.ModLoader.PrefixLoader.Unload(), Terraria.ModLoader.ProjectileLoader.Unload(), Terraria.ModLoader.PylonLoader.Unload(), Terraria.ModLoader.RarityLoader.Unload(), Terraria.ModLoader.RecipeLoader.Unload(), Terraria.ModLoader.ResourceDisplaySetLoader.Unload(), Terraria.ModLoader.ResourceOverlayLoader.Unload(), Terraria.ModLoader.SystemLoader.Unload(), Terraria.ModLoader.TileLoader.Unload(), Terraria.ModLoader.WallLoader.Unload(), Terraria.ModLoader.MapLoader.UnloadModMap(), and Terraria.ModLoader.PlantLoader.UnloadPlants().
Referenced by Terraria.ModLoader.ModLoader.Mods_Unload().