TModLoader: Terraria.ModLoader.ModContent.ResizeArrays
ResizeArrays()
static void Terraria.ModLoader.ModContent.ResizeArrays (bool unloading = false) inline static private
    {
        DamageClassLoader.ResizeArrays();
        ExtraJumpLoader.ResizeArrays();
        ItemLoader.ResizeArrays(unloading);
        EquipLoader.ResizeAndFillArrays();
        PrefixLoader.ResizeArrays();
        DustLoader.ResizeArrays();
        TileLoader.ResizeArrays(unloading);
        WallLoader.ResizeArrays(unloading);
        ProjectileLoader.ResizeArrays(unloading);
        NPCLoader.ResizeArrays(unloading);
        NPCHeadLoader.ResizeAndFillArrays();
        MountLoader.ResizeArrays();
        BuffLoader.ResizeArrays();
        PlayerLoader.ResizeArrays();
        PlayerDrawLayerLoader.ResizeArrays();
        HairLoader.ResizeArrays();
        EmoteBubbleLoader.ResizeArrays();
        SystemLoader.ResizeArrays();
        if (!Main.dedServ)
        {
            GlobalBackgroundStyleLoader.ResizeAndFillArrays(unloading);
            GoreLoader.ResizeAndFillArrays();
        }
        LoaderManager.ResizeArrays();
        if (!Main.dedServ)
        {
            SkyManager.Instance["CreditsRoll"] = new CreditsRollSky();
        }
    }
References Terraria.Main.dedServ, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.ModLoader.EquipLoader.ResizeAndFillArrays(), Terraria.ModLoader.GoreLoader.ResizeAndFillArrays(), Terraria.ModLoader.NPCHeadLoader.ResizeAndFillArrays(), Terraria.ModLoader.GlobalBackgroundStyleLoader.ResizeAndFillArrays(), Terraria.ModLoader.BuffLoader.ResizeArrays(), Terraria.ModLoader.DamageClassLoader.ResizeArrays(), Terraria.ModLoader.DustLoader.ResizeArrays(), Terraria.ModLoader.EmoteBubbleLoader.ResizeArrays(), Terraria.ModLoader.ExtraJumpLoader.ResizeArrays(), Terraria.ModLoader.HairLoader.ResizeArrays(), Terraria.ModLoader.LoaderManager.ResizeArrays(), Terraria.ModLoader.MountLoader.ResizeArrays(), Terraria.ModLoader.PlayerDrawLayerLoader.ResizeArrays(), Terraria.ModLoader.PlayerLoader.ResizeArrays(), Terraria.ModLoader.PrefixLoader.ResizeArrays(), Terraria.ModLoader.SystemLoader.ResizeArrays(), Terraria.ModLoader.ItemLoader.ResizeArrays(), Terraria.ModLoader.NPCLoader.ResizeArrays(), Terraria.ModLoader.ProjectileLoader.ResizeArrays(), Terraria.ModLoader.TileLoader.ResizeArrays(), and Terraria.ModLoader.WallLoader.ResizeArrays().
Referenced by Terraria.ModLoader.ModContent.Load(), and Terraria.ModLoader.ModContent.Unload().