TModLoader: Terraria.ModLoader.ModContent.UnloadModContent
UnloadModContent()
static void Terraria.ModLoader.ModContent.UnloadModContent () inline static package
Definition at line 542 of file ModContent.cs.
    {
        MenuLoader.Unload();
        int i = 0;
        foreach (Mod mod in ModLoader.Mods.Reverse())
        {
            Interface.loadMods.SetCurrentMod(i++, mod);
            try
            {
                MonoModHooks.RemoveAll(mod);
                mod.Close();
                mod.UnloadContent();
            }
            catch (Exception ex)
            {
                ex.Data["mod"] = mod.Name;
                throw;
            }
        }
    }
References Terraria.ModLoader.Mod.Close(), Terraria.ModLoader.UI.Interface.loadMods, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.Mod.Name, Terraria.ModLoader.MonoModHooks.RemoveAll(), Terraria.ModLoader.UI.UILoadMods.SetCurrentMod(), Terraria.ModLoader.MenuLoader.Unload(), and Terraria.ModLoader.Mod.UnloadContent().
Referenced by Terraria.ModLoader.ModLoader.Mods_Unload().