TModLoader: Terraria.Utils.DrawBorderStringBig
DrawBorderStringBig()
static Vector2 Terraria.Utils.DrawBorderStringBig (SpriteBatch spriteBatch, string text, Vector2 pos, Color color, float scale = 1f, float anchorx = 0f, float anchory = 0f, int maxCharactersDisplayed = -1) inline static
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        //IL_0065: Unknown result type (might be due to invalid IL or missing references)
        //IL_0073: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        if (maxCharactersDisplayed != -1 && text.Length > maxCharactersDisplayed)
        {
            text.Substring(0, maxCharactersDisplayed);
        }
        DynamicSpriteFont value = FontAssets.DeathText.Value;
        TextSnippet[] snippets = ChatManager.ParseMessage(text, color).ToArray();
        ChatManager.ConvertNormalSnippets(snippets);
        Vector2 textSize = ChatManager.GetStringSize(value, snippets, Vector2.One);
        int hoveredSnippet;
        for (int i = -1; i < 2; i++)
        {
            for (int j = -1; j < 2; j++)
            {
                ChatManager.DrawColorCodedString(spriteBatch, value, snippets, pos + new Vector2((float)i, (float)j), Color.Black, 0f, new Vector2(anchorx, anchory) * textSize, new Vector2(scale), out hoveredSnippet, -1f, ignoreColors: true);
            }
        }
        ChatManager.DrawColorCodedString(spriteBatch, value, snippets, pos, color, 0f, new Vector2(anchorx, anchory) * textSize, new Vector2(scale), out hoveredSnippet, -1f);
        return textSize * scale;
    }
References Terraria.UI.Chat.ChatManager.ConvertNormalSnippets(), Terraria.GameContent.FontAssets.DeathText, Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.GetStringSize(), and Terraria.UI.Chat.ChatManager.ParseMessage().
Referenced by Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.IngameOptions.DrawLeftSide(), Terraria.GameContent.UI.Elements.UITextBox.DrawSelf(), Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.DrawSelf(), and Terraria.GameContent.UI.Elements.UITextPanel< T >.DrawText().