TModLoader: Terraria.Utils.DrawPanel
DrawPanel()
static void Terraria.Utils.DrawPanel (Texture2D texture, int edgeWidth, int edgeShove, SpriteBatch spriteBatch, Vector2 position, float width, Color color) inline static
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_000d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        spriteBatch.Draw(texture, position, (Rectangle?)new Rectangle(0, 0, edgeWidth, texture.Height), color);
        spriteBatch.Draw(texture, new Vector2(position.X + (float)edgeWidth, position.Y), (Rectangle?)new Rectangle(edgeWidth + edgeShove, 0, texture.Width - (edgeWidth + edgeShove) * 2, texture.Height), color, 0f, Vector2.Zero, new Vector2((width - (float)(edgeWidth * 2)) / (float)(texture.Width - (edgeWidth + edgeShove) * 2), 1f), (SpriteEffects)0, 0f);
        spriteBatch.Draw(texture, new Vector2(position.X + width - (float)edgeWidth, position.Y), (Rectangle?)new Rectangle(texture.Width - edgeWidth, 0, edgeWidth, texture.Height), color);
    }
Referenced by Terraria.GameContent.UI.Elements.UIHorizontalSeparator.DrawSelf(), Terraria.Utils.DrawSettings2Panel(), and Terraria.Utils.DrawSettingsPanel().