TModLoader: Terraria.Utils.DrawBorderStringFourWay
DrawBorderStringFourWay()
static void Terraria.Utils.DrawBorderStringFourWay (SpriteBatch sb, DynamicSpriteFont font, string text, float x, float y, Color textColor, Color borderColor, Vector2 origin, float scale = 1f) inline static
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0003: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00aa: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        Color color = borderColor;
        Vector2 zero = Vector2.Zero;
        for (int i = 0; i < 5; i++)
        {
            switch (i)
            {
            case 0:
                zero.X = x - 2f;
                zero.Y = y;
                break;
            case 1:
                zero.X = x + 2f;
                zero.Y = y;
                break;
            case 2:
                zero.X = x;
                zero.Y = y - 2f;
                break;
            case 3:
                zero.X = x;
                zero.Y = y + 2f;
                break;
            default:
                zero.X = x;
                zero.Y = y;
                color = textColor;
                break;
            }
            sb.DrawString(font, text, zero, color, 0f, origin, scale, (SpriteEffects)0, 0f);
        }
    }
Referenced by Terraria.GameContent.UI.States.UIAchievementsMenu.Draw(), Terraria.GameContent.UI.States.UICharacterCreation.Draw(), Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawHealthText(), Terraria.Main.DrawInventory(), Terraria.Main.DrawMenu(), Terraria.UI.ItemSlot.DrawMoney(), Terraria.Main.DrawMouseOver(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), and Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney().