TModLoader: Terraria.Utils.WordwrapStringSmart
WordwrapStringSmart()
static List< List< TextSnippet > > Terraria.Utils.WordwrapStringSmart (string text, Color c, DynamicSpriteFont font, int maxWidth, int maxLines) inline static
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        TextSnippet[] array4 = ChatManager.ParseMessage(text, c).ToArray();
        List<List<TextSnippet>> list = new List<List<TextSnippet>>();
        List<TextSnippet> list2 = new List<TextSnippet>();
        TextSnippet[] array5 = array4;
        foreach (TextSnippet textSnippet in array5)
        {
            string[] array2 = textSnippet.Text.Split('\n');
            for (int j = 0; j < array2.Length - 1; j++)
            {
                list2.Add(textSnippet.CopyMorph(array2[j]));
                list.Add(list2);
                list2 = new List<TextSnippet>();
            }
            list2.Add(textSnippet.CopyMorph(array2[^1]));
        }
        list.Add(list2);
        if (maxWidth != -1)
        {
            for (int k = 0; k < list.Count; k++)
            {
                List<TextSnippet> list3 = list[k];
                float num = 0f;
                for (int l = 0; l < list3.Count; l++)
                {
                    float stringLength = list3[l].GetStringLength(font);
                    if (stringLength + num > (float)maxWidth)
                    {
                        int num2 = maxWidth - (int)num;
                        if (num > 0f)
{
                            num2 -= 16;
                        }
                        int num3 = Math.Min(list3[l].Text.Length, num2 / 8);
                        for (int i = 0; i < list3[l].Text.Length; i++)
{
                            if (font.MeasureString(list3[l].Text.Substring(0, i)).X * list3[l].Scale < (float)num2)
{
                                num3 = i;
                            }
                        }
                        if (num3 < 0)
{
                            num3 = 0;
                        }
                        string[] array3 = list3[l].Text.Split(' ');
                        int num4 = num3;
                        if (array3.Length > 1)
{
                            num4 = 0;
                            for (int m = 0; m < array3.Length; m++)
{
                                bool flag = num4 == 0;
                                if (!(num4 + array3[m].Length <= num3 || flag))
{
                                    break;
                                }
                                num4 += array3[m].Length + 1;
                            }
                            if (num4 > num3)
{
                                num4 = num3;
                            }
                        }
                        string newText = list3[l].Text.Substring(0, num4);
                        string newText2 = list3[l].Text.Substring(num4);
                        list2 = new List<TextSnippet> { list3[l].CopyMorph(newText2) };
                        for (int n = l + 1; n < list3.Count; n++)
{
                            list2.Add(list3[n]);
                        }
                        list3[l] = list3[l].CopyMorph(newText);
                        list[k] = list[k].Take(l + 1).ToList();
                        list.Insert(k + 1, list2);
                        break;
                    }
                    num += stringLength;
                }
                num = 0f;
            }
        }
        if (maxLines != -1)
        {
            while (list.Count > maxLines)
            {
                list.RemoveAt(maxLines);
            }
        }
        return list;
    }
References Terraria.UI.Chat.ChatManager.ParseMessage().
Referenced by Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextMultiline(), Terraria.Main.TextDisplayCache.PrepareCache(), and Terraria.UI.Chat.ChatMessageContainer.Refresh().