TModLoader: Terraria.Utils.ShowFancyErrorMessage
ShowFancyErrorMessage()
static void Terraria.Utils.ShowFancyErrorMessage (string message, int returnToMenu, UIState returnToState = null) inline static
Definition at line 3257 of file Utils.cs.
    {
        if (!Main.dedServ)
        {
            Logging.tML.Error((object)message);
            Interface.errorMessage.Show(message, returnToMenu, returnToState);
        }
        else
        {
            LogAndConsoleErrorMessage(message);
        }
    }
References Terraria.Main.dedServ, Terraria.ModLoader.UI.Interface.errorMessage, Terraria.Utils.LogAndConsoleErrorMessage(), Terraria.ModLoader.UI.UIErrorMessage.Show(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.Netplay.ClientLoopSetup(), Terraria.WorldBuilding.WorldGenerator.GenerateWorld(), Terraria.Audio.SoundEngine.Initialize(), Terraria.Social.Steam.SteamedWraps.Initialize(), Terraria.ModLoader.UI.ModBrowser.UIModBrowser.LogModBrowserException(), Terraria.ModLoader.SystemLoader.ModifyWorldGenTasks(), Terraria.ModLoader.UI.UIModSourceItem.PublishMod(), Terraria.ModLoader.UI.UIModSourceItem.PublishServerSideMod(), Terraria.Player.SavePlayer(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ShowGameNeedsRestart(), and Terraria.ModLoader.UI.UIModSources.ShowInfoMessages().