TModLoader: Terraria.Utils.Distance
Distance() [1/2]
static float Terraria.Utils.Distance (this Rectangle r, Vector2 point) inline static
Definition at line 1260 of file Utils.cs.
    {
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0081: Unknown result type (might be due to invalid IL or missing references)
        //IL_0079: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_0139: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_012d: Unknown result type (might be due to invalid IL or missing references)
        //IL_010e: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0101: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c9: Unknown result type (might be due to invalid IL or missing references)
        if (FloatIntersect(((Rectangle)(ref r)).Left, ((Rectangle)(ref r)).Top, r.Width, r.Height, point.X, point.Y, 0f, 0f))
        {
            return 0f;
        }
        if (point.X >= (float)((Rectangle)(ref r)).Left && point.X <= (float)((Rectangle)(ref r)).Right)
        {
            if (point.Y < (float)((Rectangle)(ref r)).Top)
            {
                return (float)((Rectangle)(ref r)).Top - point.Y;
            }
            return point.Y - (float)((Rectangle)(ref r)).Bottom;
        }
        if (point.Y >= (float)((Rectangle)(ref r)).Top && point.Y <= (float)((Rectangle)(ref r)).Bottom)
        {
            if (point.X < (float)((Rectangle)(ref r)).Left)
            {
                return (float)((Rectangle)(ref r)).Left - point.X;
            }
            return point.X - (float)((Rectangle)(ref r)).Right;
        }
        if (point.X < (float)((Rectangle)(ref r)).Left)
        {
            if (point.Y < (float)((Rectangle)(ref r)).Top)
            {
                return Vector2.Distance(point, r.TopLeft());
            }
            return Vector2.Distance(point, r.BottomLeft());
        }
        if (point.Y < (float)((Rectangle)(ref r)).Top)
        {
            return Vector2.Distance(point, r.TopRight());
        }
        return Vector2.Distance(point, r.BottomRight());
    }
References Terraria.Utils.Bottom(), Terraria.Utils.FloatIntersect(), Terraria.Utils.Left(), and Terraria.Utils.Top().