TModLoader: Terraria.Utils.DrawSplicedPanel
DrawSplicedPanel()
static void Terraria.Utils.DrawSplicedPanel (SpriteBatch sb, Texture2D texture, int x, int y, int w, int h, int leftEnd, int rightEnd, int topEnd, int bottomEnd, Color c) inline static
    {
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0055: Unknown result type (might be due to invalid IL or missing references)
        //IL_006b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0075: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0171: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_021f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        if (w < leftEnd + rightEnd)
        {
            w = leftEnd + rightEnd;
        }
        if (h < topEnd + bottomEnd)
        {
            h = topEnd + bottomEnd;
        }
        sb.Draw(texture, new Rectangle(x, y, leftEnd, topEnd), (Rectangle?)new Rectangle(0, 0, leftEnd, topEnd), c);
        sb.Draw(texture, new Rectangle(x + leftEnd, y, w - leftEnd - rightEnd, topEnd), (Rectangle?)new Rectangle(leftEnd, 0, texture.Width - leftEnd - rightEnd, topEnd), c);
        sb.Draw(texture, new Rectangle(x + w - rightEnd, y, topEnd, rightEnd), (Rectangle?)new Rectangle(texture.Width - rightEnd, 0, rightEnd, topEnd), c);
        sb.Draw(texture, new Rectangle(x, y + topEnd, leftEnd, h - topEnd - bottomEnd), (Rectangle?)new Rectangle(0, topEnd, leftEnd, texture.Height - topEnd - bottomEnd), c);
        sb.Draw(texture, new Rectangle(x + leftEnd, y + topEnd, w - leftEnd - rightEnd, h - topEnd - bottomEnd), (Rectangle?)new Rectangle(leftEnd, topEnd, texture.Width - leftEnd - rightEnd, texture.Height - topEnd - bottomEnd), c);
        sb.Draw(texture, new Rectangle(x + w - rightEnd, y + topEnd, rightEnd, h - topEnd - bottomEnd), (Rectangle?)new Rectangle(texture.Width - rightEnd, topEnd, rightEnd, texture.Height - topEnd - bottomEnd), c);
        sb.Draw(texture, new Rectangle(x, y + h - bottomEnd, leftEnd, bottomEnd), (Rectangle?)new Rectangle(0, texture.Height - bottomEnd, leftEnd, bottomEnd), c);
        sb.Draw(texture, new Rectangle(x + leftEnd, y + h - bottomEnd, w - leftEnd - rightEnd, bottomEnd), (Rectangle?)new Rectangle(leftEnd, texture.Height - bottomEnd, texture.Width - leftEnd - rightEnd, bottomEnd), c);
        sb.Draw(texture, new Rectangle(x + w - rightEnd, y + h - bottomEnd, rightEnd, bottomEnd), (Rectangle?)new Rectangle(texture.Width - rightEnd, texture.Height - bottomEnd, rightEnd, bottomEnd), c);
    }
Referenced by Terraria.Main.DrawHairWindow(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawPanel(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterNameButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIClothStyleButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIDifficultyButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIResourcePackInfoButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UISelectableTextPanel< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UISlicedImage.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredSliderSimple.DrawValueBarDynamicWidth(), and Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth().