TModLoader: Terraria.Utils.RotatedBy
RotatedBy() [1/2]
static Vector2 Terraria.Utils.RotatedBy (this Vector2 spinningpoint, double radians, Vector2 center = default(Vector2)) inline static
    {
        //IL_0010: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0017: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_003f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0052: Unknown result type (might be due to invalid IL or missing references)
        float num = (float)Math.Cos(radians);
        float num2 = (float)Math.Sin(radians);
        Vector2 vector = spinningpoint - center;
        Vector2 result = center;
        result.X += vector.X * num - vector.Y * num2;
        result.Y += vector.X * num2 + vector.Y * num;
        return result;
    }
Referenced by Terraria.Projectile.AI_001(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_016(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_123_Deerclops_ShootRubbleUp(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Projectile.AI_142_MonkStaffT2And3(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_156_GetIdlePosition(), Terraria.Projectile.AI_164_GetHomeLocation(), Terraria.Projectile.AI_182_FinalFractal(), Terraria.Projectile.Colliding(), Terraria.GameInput.LockOnHelper.Draw(), Terraria.Main.DrawItem(), Terraria.Main.DrawKite(), Terraria.GameContent.Skies.LanternSky.DrawLantern(), Terraria.Main.DrawMultisegmentPet(), Terraria.Main.DrawNPCDirect_Deerclops(), Terraria.Main.DrawNPCDirect_Inner(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_25_Shield(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_38_EyebrellaCloud(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull(), Terraria.Main.DrawProj_DrawNormalProjs(), Terraria.UI.ItemSlot.DrawRadialCircular(), Terraria.UI.ItemSlot.DrawRadialDpad(), Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.Main.DrawWithOutlines(), Terraria.Utils.GetDayTimeAsDirectionIn24HClock(), Terraria.ModLoader.Default.Developer.Jofairden.JofairdenArmorShaderLayer.GetDrawOffset(), Terraria.Player.GetFrontHandPosition(), Terraria.Mount.GetMinecartMechPoint(), Terraria.Player.ItemCheck_ApplyUseStyle_Inner(), Terraria.Player.ItemCheck_Inner(), Terraria.Player.ItemCheck_Shoot(), Terraria.Projectile.Kill(), Terraria.Projectile.RandomizeInsanityShadowFor(), Terraria.Player.RotatedRelativePoint(), Terraria.DelegateMethods.Minecart.Sparks(), Terraria.DelegateMethods.Minecart.SparksFart(), Terraria.DelegateMethods.Minecart.SparksMech(), Terraria.DelegateMethods.Minecart.SparksMeow(), Terraria.DelegateMethods.Minecart.SparksTerraFart(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_GasTrap(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LoadOutChange(), Terraria.Mount.UpdateEffects(), Terraria.NPC.VanillaAI_Inner(), Terraria.NPC.VanillaFindFrame(), Terraria.NPC.VanillaHitEffect(), Terraria.Player.WingFrame(), and Terraria.Player.Yoraiz0rEye().