TModLoader: Terraria.Utils.DrawCursorSingle
DrawCursorSingle()
static void Terraria.Utils.DrawCursorSingle (SpriteBatch sb, Color color, float rot = float::NaN, float scale = 1f, Vector2 manualPosition = default(Vector2), int cursorSlot = 0, int specialMode = 0) inline static
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000b: Unknown result type (might be due to invalid IL or missing references)
        //IL_001f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0127: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0169: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        bool flag = false;
        bool flag2 = true;
        bool flag3 = true;
        Vector2 origin = Vector2.Zero;
        Vector2 vector = default(Vector2);
        ((Vector2)(ref vector))._002Ector((float)Main.mouseX, (float)Main.mouseY);
        if (manualPosition != Vector2.Zero)
        {
            vector = manualPosition;
        }
        if (float.IsNaN(rot))
        {
            rot = 0f;
        }
        else
        {
            flag = true;
            rot -= (float)Math.PI * 3f / 4f;
        }
        if (cursorSlot == 4 || cursorSlot == 5)
        {
            flag2 = false;
            ((Vector2)(ref origin))._002Ector(8f);
            if (flag && specialMode == 0)
            {
                float num = rot;
                if (num < 0f)
                {
                    num += (float)Math.PI * 2f;
                }
                for (float num2 = 0f; num2 < 4f; num2 += 1f)
                {
                    if (Math.Abs(num - (float)Math.PI / 2f * num2) <= (float)Math.PI / 4f)
                    {
                        rot = (float)Math.PI / 2f * num2;
                        break;
                    }
                }
            }
        }
        Vector2 vector2 = Vector2.One;
        if ((Main.ThickMouse && cursorSlot == 0) || cursorSlot == 1)
        {
            vector2 = Main.DrawThickCursor(cursorSlot == 1);
        }
        if (flag2)
        {
            sb.Draw(TextureAssets.Cursors[cursorSlot].Value, vector + vector2 + Vector2.One, (Rectangle?)null, color.MultiplyRGB(new Color(0.2f, 0.2f, 0.2f, 0.5f)), rot, origin, scale * 1.1f, (SpriteEffects)0, 0f);
        }
        if (flag3)
        {
            sb.Draw(TextureAssets.Cursors[cursorSlot].Value, vector + vector2, (Rectangle?)null, color, rot, origin, scale, (SpriteEffects)0, 0f);
        }
    }
References Terraria.GameContent.TextureAssets.Cursors, Terraria.Main.DrawThickCursor(), Terraria.Main.mouseX, Terraria.Main.mouseY, and Terraria.Main.ThickMouse.
Referenced by Terraria.Graphics.Capture.CaptureInterface.Draw(), and Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawCursors().