TModLoader: Terraria.Utils.GetChaseResults
GetChaseResults()
static ChaseResults Terraria.Utils.GetChaseResults (Vector2 chaserPosition, float chaserSpeed, Vector2 runnerPosition, Vector2 runnerVelocity) inline static
Definition at line 256 of file Utils.cs.
    {
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Unknown result type (might be due to invalid IL or missing references)
        //IL_0024: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0136: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0147: Unknown result type (might be due to invalid IL or missing references)
        //IL_014c: Unknown result type (might be due to invalid IL or missing references)
        //IL_011c: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        ChaseResults result = default(ChaseResults);
        if (chaserPosition == runnerPosition)
        {
            ChaseResults result2 = default(ChaseResults);
            result2.InterceptionHappens = true;
            result2.InterceptionPosition = chaserPosition;
            result2.InterceptionTime = 0f;
            result2.ChaserVelocity = Vector2.Zero;
            return result2;
        }
        if (chaserSpeed <= 0f)
        {
            return default(ChaseResults);
        }
        Vector2 value = chaserPosition - runnerPosition;
        float num = ((Vector2)(ref value)).Length();
        float num2 = ((Vector2)(ref runnerVelocity)).Length();
        if (num2 == 0f)
        {
            result.InterceptionTime = num / chaserSpeed;
            result.InterceptionPosition = runnerPosition;
        }
        else
        {
            float a = chaserSpeed * chaserSpeed - num2 * num2;
            float b = 2f * Vector2.Dot(value, runnerVelocity);
            float c = (0f - num) * num;
            if (!SolveQuadratic(a, b, c, out var result3, out var result4))
            {
                return default(ChaseResults);
            }
            if (result3 < 0f && result4 < 0f)
            {
                return default(ChaseResults);
            }
            if (result3 > 0f && result4 > 0f)
            {
                result.InterceptionTime = Math.Min(result3, result4);
            }
            else
            {
                result.InterceptionTime = Math.Max(result3, result4);
            }
            result.InterceptionPosition = runnerPosition + runnerVelocity * result.InterceptionTime;
        }
        result.ChaserVelocity = (result.InterceptionPosition - chaserPosition) / result.InterceptionTime;
        result.InterceptionHappens = true;
        return result;
    }
References Terraria.Utils.SolveQuadratic().
Referenced by Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_066_TryInterceptingTarget(), and Terraria.Player.OnHit_Inner().