TModLoader: Terraria.Utils.OpenToURL
OpenToURL()
static void Terraria.Utils.OpenToURL (string url) inline static
    {
        if (RuntimeInformation.IsOSPlatform(OSPlatform.Windows))
        {
            Process.Start("explorer.exe", "\"" + url + "\"");
        }
        else if (RuntimeInformation.IsOSPlatform(OSPlatform.OSX))
        {
            Process.Start("open", "\"" + url + "\"");
        }
        else
        {
            Process.Start("xdg-open", "\"" + url + "\"");
        }
    }
Referenced by Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.UIModDownloadItem(), Terraria.ModLoader.UI.UIModSources.AddLink(), Terraria.ModLoader.Engine.InstallVerifier.CheckSteam(), Terraria.Main.DrawVersionNumber(), Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.ModLoader.UI.UIModItem.OnInitialize(), Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.TmlDisclaimerText_OnClick(), Terraria.ModLoader.Engine.FolderShortcutSupport.UpdateFolderShortcuts(), Terraria.ModLoader.UI.ModBrowser.UIModDownloadItem.ViewModInfo(), Terraria.ModLoader.UI.UIModInfo.VisitModHomePage(), Terraria.ModLoader.UI.UIModInfo.VisitModHostPageInner(), and Terraria.ModLoader.UI.UIErrorMessage.VisitRegisterWebpage().