TModLoader: Terraria.ModLoader.UI.UIModPackItem.DrawSelf
DrawSelf()
override void Terraria.ModLoader.UI.UIModPackItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.GameContent.UI.Elements.UIPanel.
    {
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_009b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        CalculatedStyle innerDimensions = GetInnerDimensions();
        Vector2 drawPos = default(Vector2);
        ((Vector2)(ref drawPos))._002Ector(innerDimensions.X + 5f, innerDimensions.Y + 30f);
        spriteBatch.Draw(_dividerTexture.Value, drawPos, (Rectangle?)null, Color.White, 0f, Vector2.Zero, new Vector2((innerDimensions.Width - 10f) / 8f, 1f), (SpriteEffects)0, 0f);
        ((Vector2)(ref drawPos))._002Ector(innerDimensions.X + innerDimensions.Width - 355f, innerDimensions.Y);
        DrawPanel(spriteBatch, drawPos, 350f);
        DrawEnabledText(spriteBatch, drawPos + new Vector2(10f, 5f));
        UIAutoScaleTextTextPanel<string> enableListOnlyButton = _enableListOnlyButton;
        if (enableListOnlyButton != null && enableListOnlyButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.ModPackEnableOnlyThisListDesc");
            return;
        }
        UIAutoScaleTextTextPanel<string> enableListButton = _enableListButton;
        if (enableListButton != null && enableListButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.ModPackEnableThisListDesc");
            return;
        }
        UIAutoScaleTextTextPanel<string> exportPackInstanceButton = _exportPackInstanceButton;
        if (exportPackInstanceButton != null && exportPackInstanceButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.ExportPackInstanceDesc");
            return;
        }
        UIAutoScaleTextTextPanel<string> removePackInstanceButton = _removePackInstanceButton;
        if (removePackInstanceButton != null && removePackInstanceButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.DeletePackInstanceDesc");
            return;
        }
        UIAutoScaleTextTextPanel<string> playInstanceButton = _playInstanceButton;
        if (playInstanceButton != null && playInstanceButton.IsMouseHovering)
        {
            _tooltip = "Play tModLoader using InstallDirectory/<ModPackName>";
            return;
        }
        UIAutoScaleTextTextPanel<string> importFromPackLocalButton = _importFromPackLocalButton;
        if (importFromPackLocalButton != null && importFromPackLocalButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.InstallPackLocalDesc");
            return;
        }
        UIAutoScaleTextTextPanel<string> removePackLocalButton = _removePackLocalButton;
        if (removePackLocalButton != null && removePackLocalButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.RemovePackLocalDesc");
            return;
        }
        UIAutoScaleTextTextPanel<string> viewInModBrowserButton = _viewInModBrowserButton;
        if (viewInModBrowserButton != null && viewInModBrowserButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.ModPackViewModsInModBrowserDesc");
            return;
        }
        UIAutoScaleTextTextPanel<string> updateListWithEnabledButton = _updateListWithEnabledButton;
        if (updateListWithEnabledButton != null && updateListWithEnabledButton.IsMouseHovering)
        {
            _tooltip = Language.GetTextValue("tModLoader.ModPackUpdateListWithEnabledDesc");
        }
    }
References Terraria.ModLoader.UI.UIModPackItem._dividerTexture, Terraria.ModLoader.UI.UIModPackItem._enableListButton, Terraria.ModLoader.UI.UIModPackItem._enableListOnlyButton, Terraria.ModLoader.UI.UIModPackItem._exportPackInstanceButton, Terraria.ModLoader.UI.UIModPackItem._importFromPackLocalButton, Terraria.ModLoader.UI.UIModPackItem._playInstanceButton, Terraria.ModLoader.UI.UIModPackItem._removePackInstanceButton, Terraria.ModLoader.UI.UIModPackItem._removePackLocalButton, Terraria.ModLoader.UI.UIModPackItem._tooltip, Terraria.ModLoader.UI.UIModPackItem._updateListWithEnabledButton, Terraria.ModLoader.UI.UIModPackItem._viewInModBrowserButton, Terraria.ModLoader.UI.UIModPackItem.DrawEnabledText(), Terraria.ModLoader.UI.UIModPackItem.DrawPanel(), Terraria.UI.UIElement.GetInnerDimensions(), and Terraria.Localization.Language.GetTextValue().