TModLoader: Terraria.ModLoader.UI.UIModPackItem.UIModPackItem
UIModPackItem()
Terraria.ModLoader.UI.UIModPackItem.UIModPackItem (string name, string[] mods, bool legacy, IEnumerable< LocalMod > localMods) inline
    {
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_028d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0293: Unknown result type (might be due to invalid IL or missing references)
        //IL_0297: Unknown result type (might be due to invalid IL or missing references)
        //IL_029d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a7: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0366: Unknown result type (might be due to invalid IL or missing references)
        //IL_036c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0370: Unknown result type (might be due to invalid IL or missing references)
        //IL_0376: Unknown result type (might be due to invalid IL or missing references)
        //IL_037a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_0384: Unknown result type (might be due to invalid IL or missing references)
        //IL_038a: Unknown result type (might be due to invalid IL or missing references)
        //IL_043f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0445: Unknown result type (might be due to invalid IL or missing references)
        //IL_0449: Unknown result type (might be due to invalid IL or missing references)
        //IL_044f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_0459: Unknown result type (might be due to invalid IL or missing references)
        //IL_045d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0463: Unknown result type (might be due to invalid IL or missing references)
        //IL_0518: Unknown result type (might be due to invalid IL or missing references)
        //IL_051e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0522: Unknown result type (might be due to invalid IL or missing references)
        //IL_0528: Unknown result type (might be due to invalid IL or missing references)
        //IL_052c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0532: Unknown result type (might be due to invalid IL or missing references)
        //IL_0536: Unknown result type (might be due to invalid IL or missing references)
        //IL_053c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0647: Unknown result type (might be due to invalid IL or missing references)
        //IL_064d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0651: Unknown result type (might be due to invalid IL or missing references)
        //IL_0657: Unknown result type (might be due to invalid IL or missing references)
        //IL_065b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0661: Unknown result type (might be due to invalid IL or missing references)
        //IL_0665: Unknown result type (might be due to invalid IL or missing references)
        //IL_066b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0720: Unknown result type (might be due to invalid IL or missing references)
        //IL_0726: Unknown result type (might be due to invalid IL or missing references)
        //IL_072a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0730: Unknown result type (might be due to invalid IL or missing references)
        //IL_0734: Unknown result type (might be due to invalid IL or missing references)
        //IL_073a: Unknown result type (might be due to invalid IL or missing references)
        //IL_073e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0744: Unknown result type (might be due to invalid IL or missing references)
        //IL_07f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0803: Unknown result type (might be due to invalid IL or missing references)
        //IL_0809: Unknown result type (might be due to invalid IL or missing references)
        //IL_080d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0813: Unknown result type (might be due to invalid IL or missing references)
        //IL_0817: Unknown result type (might be due to invalid IL or missing references)
        //IL_081d: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0900: Unknown result type (might be due to invalid IL or missing references)
        //IL_0906: Unknown result type (might be due to invalid IL or missing references)
        //IL_090a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0910: Unknown result type (might be due to invalid IL or missing references)
        _legacy = legacy;
        _filename = (_legacy ? name : Path.GetFileNameWithoutExtension(name));
        _filepath = name;
        _numModsEnabled = 0;
        _numModsDisabled = 0;
        _mods = mods;
        _numMods = mods.Length;
        foreach (string mod in mods)
        {
            LocalMod localMod = localMods.SingleOrDefault((LocalMod m) => m.Name == mod);
            if (localMod != null)
            {
                if (localMod.Enabled)
                {
                    _numModsEnabled++;
                }
                else
                {
                    _numModsDisabled++;
                }
            }
            else
            {
                _missing.Add(mod);
            }
        }
        BorderColor = new Color(89, 116, 213) * 0.7f;
        _dividerTexture = UICommon.DividerTexture;
        _innerPanelTexture = UICommon.InnerPanelTexture;
        Height.Pixels = (_legacy ? 126 : 210);
        Width.Percent = 1f;
        SetPadding(6f);
        _modName = new UIText(_filename)
        {
            Left =
            {
                Pixels = 10f
            },
            Top =
            {
                Pixels = 5f
            }
        };
        Append(_modName);
        UIAutoScaleTextTextPanel<string> viewListButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModPackViewList"))
        {
            Width =
            {
                Pixels = 100f
            },
            Height =
            {
                Pixels = 36f
            },
            Left =
            {
                Pixels = 407f
            },
            Top =
            {
                Pixels = 40f
            }
        }.WithFadedMouseOver();
        viewListButton.PaddingTop -= 2f;
        viewListButton.PaddingBottom -= 2f;
        viewListButton.OnLeftClick += ViewListInfo;
        Append(viewListButton);
        _enableListButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModPackEnableThisList"))
        {
            Width =
            {
                Pixels = 151f
            },
            Height =
            {
                Pixels = 36f
            },
            Left =
            {
                Pixels = 248f
            },
            Top =
            {
                Pixels = 40f
            }
        }.WithFadedMouseOver();
        _enableListButton.PaddingTop -= 2f;
        _enableListButton.PaddingBottom -= 2f;
        _enableListButton.OnLeftClick += EnableList;
        Append(_enableListButton);
        _enableListOnlyButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModPackEnableOnlyThisList"))
        {
            Width =
            {
                Pixels = 190f
            },
            Height =
            {
                Pixels = 36f
            },
            Left =
            {
                Pixels = 50f
            },
            Top =
            {
                Pixels = 40f
            }
        }.WithFadedMouseOver();
        _enableListOnlyButton.PaddingTop -= 2f;
        _enableListOnlyButton.PaddingBottom -= 2f;
        _enableListOnlyButton.OnLeftClick += EnabledListOnly;
        Append(_enableListOnlyButton);
        _viewInModBrowserButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModPackViewModsInModBrowser"))
        {
            Width =
            {
                Pixels = 246f
            },
            Height =
            {
                Pixels = 36f
            },
            Left =
            {
                Pixels = 50f
            },
            Top =
            {
                Pixels = 80f
            }
        }.WithFadedMouseOver();
        _viewInModBrowserButton.PaddingTop -= 2f;
        _viewInModBrowserButton.PaddingBottom -= 2f;
        _viewInModBrowserButton.OnLeftClick += DownloadMissingMods;
        Append(_viewInModBrowserButton);
        _updateListWithEnabledButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModPackUpdateListWithEnabled"))
        {
            Width =
            {
                Pixels = 225f
            },
            Height =
            {
                Pixels = 36f
            },
            Left =
            {
                Pixels = 304f
            },
            Top =
            {
                Pixels = 80f
            }
        }.WithFadedMouseOver();
        _updateListWithEnabledButton.PaddingTop -= 2f;
        _updateListWithEnabledButton.PaddingBottom -= 2f;
        _updateListWithEnabledButton.OnLeftClick += UpdateModPack;
        Append(_updateListWithEnabledButton);
        _deleteButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/ButtonDelete"))
        {
            Top =
            {
                Pixels = 40f
            }
        };
        _deleteButton.OnLeftClick += DeleteButtonClick;
        Append(_deleteButton);
        if (!_legacy)
        {
            _importFromPackLocalButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.InstallPackLocal"))
            {
                Width =
                {
                    Pixels = 225f
                },
                Height =
                {
                    Pixels = 36f
                },
                Left =
                {
                    Pixels = 50f
                },
                Top =
                {
                    Pixels = 120f
                }
            }.WithFadedMouseOver();
            _importFromPackLocalButton.PaddingTop -= 2f;
            _importFromPackLocalButton.PaddingBottom -= 2f;
            _importFromPackLocalButton.OnLeftClick += ImportModPackLocal;
            Append(_importFromPackLocalButton);
            _removePackLocalButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.RemovePackLocal"))
            {
                Width =
                {
                    Pixels = 225f
                },
                Height =
                {
                    Pixels = 36f
                },
                Left =
                {
                    Pixels = 280f
                },
                Top =
                {
                    Pixels = 120f
                }
            }.WithFadedMouseOver();
            _removePackLocalButton.PaddingTop -= 2f;
            _removePackLocalButton.PaddingBottom -= 2f;
            _removePackLocalButton.OnLeftClick += RemoveModPackLocal;
            Append(_removePackLocalButton);
            _exportPackInstanceButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ExportPackInstance"))
            {
                Width =
                {
                    Pixels = 200f
                },
                Height =
                {
                    Pixels = 36f
                },
                Left =
                {
                    Pixels = 10f
                },
                Top =
                {
                    Pixels = 160f
                }
            }.WithFadedMouseOver();
            _exportPackInstanceButton.PaddingTop -= 2f;
            _exportPackInstanceButton.PaddingBottom -= 2f;
            _exportPackInstanceButton.OnLeftClick += ExportInstance;
            Append(_exportPackInstanceButton);
            if (Directory.Exists(Path.Combine(Directory.GetCurrentDirectory(), _filename)))
            {
                _removePackInstanceButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.DeletePackInstance"))
                {
                    Width =
                    {
                        Pixels = 140f
                    },
                    Height =
                    {
                        Pixels = 36f
                    },
                    Left =
                    {
                        Pixels = 370f
                    },
                    Top =
                    {
                        Pixels = 160f
                    }
                }.WithFadedMouseOver();
                _removePackInstanceButton.PaddingTop -= 2f;
                _removePackInstanceButton.PaddingBottom -= 2f;
                _removePackInstanceButton.OnLeftClick += DeleteInstance;
                Append(_removePackInstanceButton);
            }
        }
    }
References Terraria.ModLoader.UI.UIModPackItem._deleteButton, Terraria.ModLoader.UI.UIModPackItem._dividerTexture, Terraria.ModLoader.UI.UIModPackItem._enableListButton, Terraria.ModLoader.UI.UIModPackItem._enableListOnlyButton, Terraria.ModLoader.UI.UIModPackItem._exportPackInstanceButton, Terraria.ModLoader.UI.UIModPackItem._filename, Terraria.ModLoader.UI.UIModPackItem._filepath, Terraria.ModLoader.UI.UIModPackItem._importFromPackLocalButton, Terraria.ModLoader.UI.UIModPackItem._innerPanelTexture, Terraria.ModLoader.UI.UIModPackItem._legacy, Terraria.ModLoader.UI.UIModPackItem._missing, Terraria.ModLoader.UI.UIModPackItem._modName, Terraria.ModLoader.UI.UIModPackItem._mods, Terraria.ModLoader.UI.UIModPackItem._numMods, Terraria.ModLoader.UI.UIModPackItem._numModsDisabled, Terraria.ModLoader.UI.UIModPackItem._numModsEnabled, Terraria.ModLoader.UI.UIModPackItem._removePackInstanceButton, Terraria.ModLoader.UI.UIModPackItem._removePackLocalButton, Terraria.ModLoader.UI.UIModPackItem._updateListWithEnabledButton, Terraria.ModLoader.UI.UIModPackItem._viewInModBrowserButton, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.ModLoader.UI.UIModPackItem.DeleteButtonClick(), Terraria.ModLoader.UI.UIModPackItem.DeleteInstance(), Terraria.ModLoader.UI.UICommon.DividerTexture, Terraria.ModLoader.UI.UIModPackItem.DownloadMissingMods(), Terraria.ModLoader.UI.UIModPackItem.EnabledListOnly(), Terraria.ModLoader.UI.UIModPackItem.EnableList(), Terraria.ModLoader.UI.UIModPackItem.ExportInstance(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Height, Terraria.ModLoader.UI.UIModPackItem.ImportModPackLocal(), Terraria.ModLoader.UI.UICommon.InnerPanelTexture, Terraria.UI.UIElement.Left, Terraria.ModLoader.UI.UIModPackItem.RemoveModPackLocal(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.Top, Terraria.ModLoader.UI.UIModPackItem.UpdateModPack(), Terraria.ModLoader.UI.UIModPackItem.ViewListInfo(), and Terraria.UI.UIElement.Width.