TModLoader: Terraria.ModLoader.UI.UIModPackItem.ViewListInfo
ViewListInfo()
static void Terraria.ModLoader.UI.UIModPackItem.ViewListInfo (UIMouseEvent evt, UIElement listeningElement) inline static private
    {
        UIModPackItem modListItem = (UIModPackItem)listeningElement.Parent;
        SoundEngine.PlaySound(10);
        string message = "";
        string[] mods = modListItem._mods;
        foreach (string mod in mods)
        {
            message = message + mod + (modListItem._missing.Contains(mod) ? Language.GetTextValue("tModLoader.ModPackMissing") : (ModLoader.IsEnabled(mod) ? "" : Language.GetTextValue("tModLoader.ModPackDisabled"))) + "\n";
        }
        Interface.infoMessage.Show(Language.GetTextValue("tModLoader.ModPackModsContained", message), 10016);
    }
References Terraria.ModLoader.UI.UIModPackItem.UIModPackItem(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.Interface.infoMessage, Terraria.ModLoader.ModLoader.IsEnabled(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.ModLoader.UI.UIModPackItem.UIModPackItem().