TModLoader: Terraria.ModLoader.UI.UIModPackItem.EnableList
EnableList()
static void Terraria.ModLoader.UI.UIModPackItem.EnableList (UIMouseEvent evt, UIElement listeningElement) inline static private
Definition at line 608 of file UIModPackItem.cs.
    {
        UIModPackItem modListItem = (UIModPackItem)listeningElement.Parent;
        LocalMod[] array = ModOrganizer.FindMods();
        foreach (LocalMod mod in array)
        {
            mod.Enabled = mod.Enabled || modListItem._mods.Contains(mod.Name);
        }
        if (modListItem._missing.Count > 0)
        {
            Interface.infoMessage.Show(Language.GetTextValue("tModLoader.ModPackModsMissing", string.Join("\n", modListItem._missing)), 10016);
        }
        Logging.tML.Info((object)("Enabled Collection of mods defined in  Mod Pack " + modListItem._filename));
        ModLoader.OnSuccessfulLoad = (Action)Delegate.Combine(ModLoader.OnSuccessfulLoad, (Action)delegate
        {
            Main.menuMode = 10016;
        });
        ModLoader.Reload();
    }
References Terraria.ModLoader.Core.ModOrganizer.FindMods(), Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.Interface.infoMessage, Terraria.ModLoader.ModLoader.OnSuccessfulLoad, Terraria.ModLoader.ModLoader.Reload(), Terraria.ModLoader.UI.UIInfoMessage.Show(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.UI.UIModPackItem.UIModPackItem(), Terraria.ModLoader.UI.UIModPackItem.EnabledListOnly(), and Terraria.ModLoader.UI.UIModPackItem.UpdateModPack().