TModLoader: Terraria.ModLoader.UI.UIModPackItem.UpdateModPack
UpdateModPack()
static void Terraria.ModLoader.UI.UIModPackItem.UpdateModPack (UIMouseEvent evt, UIElement listeningElement) inline static private
    {
        UIModPackItem modpack = (UIModPackItem)listeningElement.Parent;
        UIModPacks.SaveModPack(modpack._filename);
        if (modpack._filepath == ModOrganizer.ModPackActive)
        {
            ModLoader.DisableAllMods();
            Logging.tML.Info((object)("Cleaning up removed tmods " + modpack._filename));
            ModLoader.OnSuccessfulLoad = (Action)Delegate.Combine(ModLoader.OnSuccessfulLoad, (Action)delegate
            {
                foreach (string current in Directory.EnumerateFiles(UIModPacks.ModPackModsPath(modpack._filename), "*.tmod"))
                {
                    if (!modpack._mods.Contains<string>(Path.GetFileNameWithoutExtension(current)))
                    {
                        File.Delete(current);
                    }
                }
                EnableList(evt, listeningElement);
            });
            ModLoader.Reload();
        }
        else
        {
            foreach (string file in Directory.EnumerateFiles(UIModPacks.ModPackModsPath(modpack._filename), "*.tmod"))
            {
                if (!modpack._mods.Contains<string>(Path.GetFileNameWithoutExtension(file)))
                {
                    File.Delete(file);
                }
            }
        }
        Interface.modPacksMenu.OnDeactivate();
        Interface.modPacksMenu.OnActivate();
    }
References Terraria.ModLoader.UI.UIModPackItem.UIModPackItem(), Terraria.ModLoader.ModLoader.DisableAllMods(), Terraria.ModLoader.UI.UIModPackItem.EnableList(), Terraria.ModLoader.Core.ModOrganizer.ModPackActive, Terraria.ModLoader.UI.UIModPacks.ModPackModsPath(), Terraria.ModLoader.UI.Interface.modPacksMenu, Terraria.ModLoader.ModLoader.OnSuccessfulLoad, Terraria.ModLoader.ModLoader.Reload(), Terraria.ModLoader.UI.UIModPacks.SaveModPack(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.UI.UIModPackItem.UIModPackItem().