TModLoader: Terraria.DataStructures.PlayerDrawSet.CreateCompositeData
CreateCompositeData()
void Terraria.DataStructures.PlayerDrawSet.CreateCompositeData () inline private
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_000c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0011: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0302: Unknown result type (might be due to invalid IL or missing references)
        //IL_0307: Unknown result type (might be due to invalid IL or missing references)
        //IL_030e: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_032f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0334: Unknown result type (might be due to invalid IL or missing references)
        //IL_036b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0379: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_03ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_03f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0401: Unknown result type (might be due to invalid IL or missing references)
        //IL_0408: Unknown result type (might be due to invalid IL or missing references)
        //IL_0409: Unknown result type (might be due to invalid IL or missing references)
        //IL_040e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0415: Unknown result type (might be due to invalid IL or missing references)
        //IL_0417: Unknown result type (might be due to invalid IL or missing references)
        //IL_041c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0423: Unknown result type (might be due to invalid IL or missing references)
        //IL_0424: Unknown result type (might be due to invalid IL or missing references)
        //IL_0429: Unknown result type (might be due to invalid IL or missing references)
        frontShoulderOffset = Vector2.Zero;
        backShoulderOffset = Vector2.Zero;
        usesCompositeTorso = drawPlayer.body > 0 && ArmorIDs.Body.Sets.UsesNewFramingCode[drawPlayer.body];
        usesCompositeFrontHandAcc = drawPlayer.handon > 0 && ArmorIDs.HandOn.Sets.UsesNewFramingCode[drawPlayer.handon];
        usesCompositeBackHandAcc = drawPlayer.handoff > 0 && ArmorIDs.HandOff.Sets.UsesNewFramingCode[drawPlayer.handoff];
        if (drawPlayer.body < 1)
        {
            usesCompositeTorso = true;
        }
        if (!usesCompositeTorso)
        {
            return;
        }
        Point pt = default(Point);
        ((Point)(ref pt))._002Ector(1, 1);
        Point pt2 = default(Point);
        ((Point)(ref pt2))._002Ector(0, 1);
        Point pt3 = default(Point);
        Point frameIndex = default(Point);
        Point frameIndex2 = default(Point);
        int num = drawPlayer.bodyFrame.Y / drawPlayer.bodyFrame.Height;
        compShoulderOverFrontArm = true;
        hideCompositeShoulders = false;
        bool flag = true;
        if (drawPlayer.body > 0)
        {
            flag = ArmorIDs.Body.Sets.showsShouldersWhileJumping[drawPlayer.body];
        }
        bool flag2 = false;
        if (drawPlayer.handon > 0)
        {
            flag2 = ArmorIDs.HandOn.Sets.UsesOldFramingTexturesForWalking[drawPlayer.handon];
        }
        bool flag3 = !flag2;
        switch (num)
        {
        case 0:
            frameIndex2.X = 2;
            flag3 = true;
            break;
        case 1:
            frameIndex2.X = 3;
            compShoulderOverFrontArm = false;
            flag3 = true;
            break;
        case 2:
            frameIndex2.X = 4;
            compShoulderOverFrontArm = false;
            flag3 = true;
            break;
        case 3:
            frameIndex2.X = 5;
            compShoulderOverFrontArm = true;
            flag3 = true;
            break;
        case 4:
            frameIndex2.X = 6;
            compShoulderOverFrontArm = true;
            flag3 = true;
            break;
        case 5:
            frameIndex2.X = 2;
            frameIndex2.Y = 1;
            pt3.X = 1;
            compShoulderOverFrontArm = false;
            flag3 = true;
            if (!flag)
            {
                hideCompositeShoulders = true;
            }
            break;
        case 6:
            frameIndex2.X = 3;
            frameIndex2.Y = 1;
            break;
        case 7:
        case 8:
        case 9:
        case 10:
            frameIndex2.X = 4;
            frameIndex2.Y = 1;
            break;
        case 11:
        case 12:
        case 13:
            frameIndex2.X = 3;
            frameIndex2.Y = 1;
            break;
        case 14:
            frameIndex2.X = 5;
            frameIndex2.Y = 1;
            break;
        case 15:
        case 16:
            frameIndex2.X = 6;
            frameIndex2.Y = 1;
            break;
        case 17:
            frameIndex2.X = 5;
            frameIndex2.Y = 1;
            break;
        case 18:
        case 19:
            frameIndex2.X = 3;
            frameIndex2.Y = 1;
            break;
        }
        CreateCompositeData_DetermineShoulderOffsets(drawPlayer.body, num);
        backShoulderOffset *= new Vector2((float)drawPlayer.direction, drawPlayer.gravDir);
        frontShoulderOffset *= new Vector2((float)drawPlayer.direction, drawPlayer.gravDir);
        if (drawPlayer.body > 0 && ArmorIDs.Body.Sets.shouldersAreAlwaysInTheBack[drawPlayer.body])
        {
            compShoulderOverFrontArm = false;
        }
        usesCompositeFrontHandAcc = flag3;
        frameIndex.X = frameIndex2.X;
        frameIndex.Y = frameIndex2.Y + 2;
        UpdateCompositeArm(drawPlayer.compositeFrontArm, ref compositeFrontArmRotation, ref frameIndex2, 7);
        UpdateCompositeArm(drawPlayer.compositeBackArm, ref compositeBackArmRotation, ref frameIndex, 8);
        if (!drawPlayer.Male)
        {
            pt.Y += 2;
            pt2.Y += 2;
            pt3.Y += 2;
        }
        compBackShoulderFrame = CreateCompositeFrameRect(pt);
        compFrontShoulderFrame = CreateCompositeFrameRect(pt2);
        compBackArmFrame = CreateCompositeFrameRect(frameIndex);
        compFrontArmFrame = CreateCompositeFrameRect(frameIndex2);
        compTorsoFrame = CreateCompositeFrameRect(pt3);
    }
References Terraria.DataStructures.PlayerDrawSet.backShoulderOffset, Terraria.Player.body, Terraria.Player.bodyFrame, Terraria.DataStructures.PlayerDrawSet.compBackArmFrame, Terraria.DataStructures.PlayerDrawSet.compBackShoulderFrame, Terraria.DataStructures.PlayerDrawSet.compFrontArmFrame, Terraria.DataStructures.PlayerDrawSet.compFrontShoulderFrame, Terraria.Player.compositeBackArm, Terraria.DataStructures.PlayerDrawSet.compositeBackArmRotation, Terraria.Player.compositeFrontArm, Terraria.DataStructures.PlayerDrawSet.compositeFrontArmRotation, Terraria.DataStructures.PlayerDrawSet.compShoulderOverFrontArm, Terraria.DataStructures.PlayerDrawSet.compTorsoFrame, Terraria.DataStructures.PlayerDrawSet.CreateCompositeData_DetermineShoulderOffsets(), Terraria.DataStructures.PlayerDrawSet.CreateCompositeFrameRect(), Terraria.Entity.direction, Terraria.DataStructures.PlayerDrawSet.drawPlayer, Terraria.DataStructures.PlayerDrawSet.frontShoulderOffset, Terraria.Player.gravDir, Terraria.Player.handoff, Terraria.Player.handon, Terraria.DataStructures.PlayerDrawSet.hideCompositeShoulders, Terraria.Player.Male, Terraria.ID.ArmorIDs.Body.Sets.shouldersAreAlwaysInTheBack, Terraria.ID.ArmorIDs.Body.Sets.showsShouldersWhileJumping, Terraria.DataStructures.PlayerDrawSet.UpdateCompositeArm(), Terraria.DataStructures.PlayerDrawSet.usesCompositeBackHandAcc, Terraria.DataStructures.PlayerDrawSet.usesCompositeFrontHandAcc, Terraria.DataStructures.PlayerDrawSet.usesCompositeTorso, Terraria.ID.ArmorIDs.Body.Sets.UsesNewFramingCode, Terraria.ID.ArmorIDs.HandOn.Sets.UsesNewFramingCode, Terraria.ID.ArmorIDs.HandOff.Sets.UsesNewFramingCode, and Terraria.ID.ArmorIDs.HandOn.Sets.UsesOldFramingTexturesForWalking.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup_End().