TModLoader: Terraria.DataStructures.PlayerDrawSet.HeadOnlySetup
HeadOnlySetup()
void Terraria.DataStructures.PlayerDrawSet.HeadOnlySetup (Player drawPlayer2, List< DrawData > drawData, List< int > dust, List< int > gore, float X, float Y, float Alpha, float Scale) inline
    {
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_014e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0172: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_017f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019e: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0201: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_0210: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_0295: Unknown result type (might be due to invalid IL or missing references)
        //IL_029a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0411: Unknown result type (might be due to invalid IL or missing references)
        //IL_0416: Unknown result type (might be due to invalid IL or missing references)
        //IL_042e: Unknown result type (might be due to invalid IL or missing references)
        projectileDrawPosition = -1;
        headOnlyRender = true;
        DrawDataCache = drawData;
        DustCache = dust;
        GoreCache = gore;
        drawPlayer = drawPlayer2;
        Position = drawPlayer.position;
        CopyBasicPlayerFields();
        drawUnicornHorn = false;
        drawAngelHalo = false;
        skinVar = drawPlayer.skinVariant;
        hairDyePacked = PlayerDrawHelper.PackShader(drawPlayer.hairDye, PlayerDrawHelper.ShaderConfiguration.HairShader);
        if (drawPlayer.head == 0 && drawPlayer.hairDye == 0)
        {
            hairDyePacked = PlayerDrawHelper.PackShader(1, PlayerDrawHelper.ShaderConfiguration.HairShader);
        }
        skinDyePacked = drawPlayer.skinDyePacked;
        if (drawPlayer.face > 0 && drawPlayer.face < ArmorIDs.Face.Count)
        {
            Main.instance.LoadAccFace(drawPlayer.face);
        }
        drawUnicornHorn = drawPlayer.hasUnicornHorn;
        drawAngelHalo = drawPlayer.hasAngelHalo;
        Main.instance.LoadHair(drawPlayer.hair);
        colorEyeWhites = Main.quickAlpha(Color.White, Alpha);
        colorEyes = Main.quickAlpha(drawPlayer.eyeColor, Alpha);
        colorHair = Main.quickAlpha(drawPlayer.GetHairColor(useLighting: false), Alpha);
        colorHead = Main.quickAlpha(drawPlayer.skinColor, Alpha);
        colorArmorHead = Main.quickAlpha(Color.White, Alpha);
        if (drawPlayer.isDisplayDollOrInanimate)
        {
            colorDisplayDollSkin = Main.quickAlpha(PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, Alpha);
        }
        else
        {
            colorDisplayDollSkin = colorHead;
        }
        playerEffect = (SpriteEffects)0;
        if (drawPlayer.direction < 0)
        {
            playerEffect = (SpriteEffects)1;
        }
        headVect = new Vector2((float)drawPlayer.legFrame.Width * 0.5f, (float)drawPlayer.legFrame.Height * 0.4f);
        Position = new Vector2(X, Y);
        Position.X -= 6f;
        Position.Y -= 4f;
        Position.Y -= drawPlayer.HeightMapOffset;
        SetupHairFrames();
        Position -= Main.OffsetsPlayerHeadgear[drawPlayer.bodyFrame.Y / drawPlayer.bodyFrame.Height];
        if (drawPlayer.head > 0 && drawPlayer.head < ArmorIDs.Head.Count)
        {
            Main.instance.LoadArmorHead(drawPlayer.head);
            int num = ArmorIDs.Head.Sets.FrontToBackID[drawPlayer.head];
            if (num >= 0)
            {
                Main.instance.LoadArmorHead(num);
            }
        }
        if (drawPlayer.face > 0 && drawPlayer.face < ArmorIDs.Face.Count)
        {
            Main.instance.LoadAccFace(drawPlayer.face);
        }
        if (drawPlayer.faceHead > 0 && drawPlayer.faceHead < ArmorIDs.Face.Count)
        {
            Main.instance.LoadAccFace(drawPlayer.faceHead);
        }
        if (drawPlayer.faceFlower > 0 && drawPlayer.faceFlower < ArmorIDs.Face.Count)
        {
            Main.instance.LoadAccFace(drawPlayer.faceFlower);
        }
        if (drawPlayer.beard > 0 && drawPlayer.beard < ArmorIDs.Beard.Count)
        {
            Main.instance.LoadAccBeard(drawPlayer.beard);
        }
        hairOffset = drawPlayer.GetHairDrawOffset(drawPlayer.hair, hatHair);
        hairOffset.Y *= drawPlayer.Directions.Y;
        helmetOffset = drawPlayer.GetHelmetDrawOffset();
        helmetOffset.Y *= drawPlayer.Directions.Y;
        drawPlayer.GetHairSettings(out fullHair, out hatHair, out hideHair, out backHairDraw, out drawsBackHairWithoutHeadgear);
    }
References Terraria.DataStructures.PlayerDrawSet.backHairDraw, Terraria.Player.beard, Terraria.Player.bodyFrame, Terraria.DataStructures.PlayerDrawSet.colorArmorHead, Terraria.DataStructures.PlayerDrawSet.colorDisplayDollSkin, Terraria.DataStructures.PlayerDrawSet.colorEyes, Terraria.DataStructures.PlayerDrawSet.colorEyeWhites, Terraria.DataStructures.PlayerDrawSet.colorHair, Terraria.DataStructures.PlayerDrawSet.colorHead, Terraria.DataStructures.PlayerDrawSet.CopyBasicPlayerFields(), Terraria.ID.ArmorIDs.Head.Count, Terraria.ID.ArmorIDs.Face.Count, Terraria.ID.ArmorIDs.Beard.Count, Terraria.Entity.direction, Terraria.Player.Directions, Terraria.DataStructures.PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, Terraria.DataStructures.PlayerDrawSet.drawAngelHalo, Terraria.DataStructures.PlayerDrawSet.DrawDataCache, Terraria.DataStructures.PlayerDrawSet.drawPlayer, Terraria.DataStructures.PlayerDrawSet.drawsBackHairWithoutHeadgear, Terraria.DataStructures.PlayerDrawSet.drawUnicornHorn, Terraria.DataStructures.PlayerDrawSet.DustCache, Terraria.Player.eyeColor, Terraria.Player.face, Terraria.Player.faceFlower, Terraria.Player.faceHead, Terraria.ID.ArmorIDs.Head.Sets.FrontToBackID, Terraria.DataStructures.PlayerDrawSet.fullHair, Terraria.Player.GetHairColor(), Terraria.Player.GetHairDrawOffset(), Terraria.Player.GetHairSettings(), Terraria.Player.GetHelmetDrawOffset(), Terraria.DataStructures.PlayerDrawSet.GoreCache, Terraria.Player.hair, Terraria.Player.hairDye, Terraria.DataStructures.PlayerDrawSet.hairDyePacked, Terraria.DataStructures.PlayerDrawSet.hairOffset, Terraria.Player.hasAngelHalo, Terraria.Player.hasUnicornHorn, Terraria.DataStructures.PlayerDrawSet.hatHair, Terraria.Player.head, Terraria.DataStructures.PlayerDrawSet.headOnlyRender, Terraria.DataStructures.PlayerDrawSet.headVect, Terraria.Player.HeightMapOffset, Terraria.DataStructures.PlayerDrawSet.helmetOffset, Terraria.DataStructures.PlayerDrawSet.hideHair, Terraria.Main.instance, Terraria.Player.isDisplayDollOrInanimate, Terraria.Player.legFrame, Terraria.Main.OffsetsPlayerHeadgear, Terraria.DataStructures.PlayerDrawHelper.PackShader(), Terraria.DataStructures.PlayerDrawSet.playerEffect, Terraria.DataStructures.PlayerDrawSet.Position, Terraria.Entity.position, Terraria.DataStructures.PlayerDrawSet.projectileDrawPosition, Terraria.Main.quickAlpha(), Terraria.DataStructures.PlayerDrawSet.SetupHairFrames(), Terraria.Player.skinColor, Terraria.DataStructures.PlayerDrawSet.skinDyePacked, Terraria.Player.skinDyePacked, Terraria.DataStructures.PlayerDrawSet.skinVar, and Terraria.Player.skinVariant.