TModLoader: Terraria.DataStructures.PlayerDrawSet.BoringSetup_End
BoringSetup_End()
void Terraria.DataStructures.PlayerDrawSet.BoringSetup_End () inline private
    {
        //IL_0162: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_0173: Unknown result type (might be due to invalid IL or missing references)
        //IL_0178: Unknown result type (might be due to invalid IL or missing references)
        //IL_0184: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        hidesTopSkin = (drawPlayer.body > 0 && ArmorIDs.Body.Sets.HidesTopSkin[drawPlayer.body]) || (drawPlayer.legs > 0 && ArmorIDs.Legs.Sets.HidesTopSkin[drawPlayer.legs]);
        hidesBottomSkin = (drawPlayer.body > 0 && ArmorIDs.Body.Sets.HidesBottomSkin[drawPlayer.body]) || (drawPlayer.legs > 0 && ArmorIDs.Legs.Sets.HidesBottomSkin[drawPlayer.legs]);
        isBottomOverriden = PlayerDrawLayers.IsBottomOverridden(ref this);
        drawFloatingTube = drawPlayer.hasFloatingTube && !hideEntirePlayer;
        drawUnicornHorn = drawPlayer.hasUnicornHorn;
        drawAngelHalo = drawPlayer.hasAngelHalo;
        drawFrontAccInNeckAccLayer = false;
        if (drawPlayer.bodyFrame.Y / drawPlayer.bodyFrame.Height == 5)
        {
            drawFrontAccInNeckAccLayer = drawPlayer.front > 0 && drawPlayer.front < ArmorIDs.Front.Count && ArmorIDs.Front.Sets.DrawsInNeckLayer[drawPlayer.front];
        }
        hairOffset = drawPlayer.GetHairDrawOffset(drawPlayer.hair, hatHair);
        helmetOffset = drawPlayer.GetHelmetDrawOffset();
        legsOffset = drawPlayer.GetLegsDrawOffset();
        CreateCompositeData();
    }
References Terraria.Player.body, Terraria.Player.bodyFrame, Terraria.DataStructures.PlayerDrawSet.CreateCompositeData(), Terraria.DataStructures.PlayerDrawSet.drawAngelHalo, Terraria.DataStructures.PlayerDrawSet.drawFloatingTube, Terraria.DataStructures.PlayerDrawSet.drawFrontAccInNeckAccLayer, Terraria.DataStructures.PlayerDrawSet.drawPlayer, Terraria.ID.ArmorIDs.Front.Sets.DrawsInNeckLayer, Terraria.DataStructures.PlayerDrawSet.drawUnicornHorn, Terraria.Player.front, Terraria.Player.GetHairDrawOffset(), Terraria.Player.GetHelmetDrawOffset(), Terraria.Player.GetLegsDrawOffset(), Terraria.Player.hair, Terraria.DataStructures.PlayerDrawSet.hairOffset, Terraria.Player.hasAngelHalo, Terraria.Player.hasUnicornHorn, Terraria.DataStructures.PlayerDrawSet.hatHair, Terraria.DataStructures.PlayerDrawSet.helmetOffset, Terraria.DataStructures.PlayerDrawSet.hideEntirePlayer, Terraria.DataStructures.PlayerDrawSet.hidesBottomSkin, Terraria.ID.ArmorIDs.Body.Sets.HidesBottomSkin, Terraria.ID.ArmorIDs.Legs.Sets.HidesBottomSkin, Terraria.DataStructures.PlayerDrawSet.hidesTopSkin, Terraria.ID.ArmorIDs.Body.Sets.HidesTopSkin, Terraria.ID.ArmorIDs.Legs.Sets.HidesTopSkin, Terraria.DataStructures.PlayerDrawLayers.IsBottomOverridden(), Terraria.DataStructures.PlayerDrawSet.isBottomOverriden, Terraria.Player.legs, and Terraria.DataStructures.PlayerDrawSet.legsOffset.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup_2().