TModLoader: Terraria.Cinematics.DD2Film.DryadPortalFade
DryadPortalFade()
void Terraria.Cinematics.DD2Film.DryadPortalFade (FrameEventData evt) inline private
    {
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_0078: Unknown result type (might be due to invalid IL or missing references)
        //IL_007d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0082: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0138: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01af: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01df: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ff: Unknown result type (might be due to invalid IL or missing references)
        if (_dryad == null || _portal == null)
        {
            return;
        }
        if (evt.IsFirstFrame)
        {
            SoundEngine.PlaySound(in SoundID.DD2_EtherianPortalDryadTouch, _dryad.Center);
        }
        float val = (float)(evt.Frame - 7) / (float)(evt.Duration - 7);
        val = Math.Max(0f, val);
        _dryad.color = new Color(Vector3.Lerp(Vector3.One, new Vector3(0.5f, 0f, 0.8f), val));
        _dryad.Opacity = 1f - val;
        _dryad.rotation += 0.05f * (val * 4f + 1f);
        _dryad.scale = 1f - val;
        if (_dryad.position.X < _portal.Right.X)
        {
            _dryad.velocity.X *= 0.95f;
            _dryad.velocity.Y *= 0.55f;
        }
        int num = (int)(6f * val);
        Vector2 size = _dryad.Size;
        float num2 = ((Vector2)(ref size)).Length() / 2f;
        num2 /= 20f;
        for (int i = 0; i < num; i++)
        {
            if (Main.rand.Next(5) == 0)
            {
                Dust dust = Dust.NewDustDirect(_dryad.position, _dryad.width, _dryad.height, 27, _dryad.velocity.X * 1f, 0f, 100);
                dust.scale = 0.55f;
                dust.fadeIn = 0.7f;
                dust.velocity *= 0.1f * num2;
                dust.velocity += _dryad.velocity;
            }
        }
    }
References Terraria.Cinematics.DD2Film._dryad, Terraria.Cinematics.DD2Film._portal, Terraria.Entity.Center, Terraria.ID.SoundID.DD2_EtherianPortalDryadTouch, Terraria.Entity.height, Terraria.Dust.NewDustDirect(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Entity.Right, Terraria.Entity.Size, Terraria.Entity.velocity, and Terraria.Entity.width.
Referenced by Terraria.Cinematics.DD2Film.DD2Film().