TModLoader: Terraria.Cinematics.DD2Film.CreateCritters
CreateCritters()
void Terraria.Cinematics.DD2Film.CreateCritters (FrameEventData evt) inline private
Definition at line 126 of file DD2Film.cs.
    {
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_005b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0060: Unknown result type (might be due to invalid IL or missing references)
        for (int i = 0; i < 5; i++)
        {
            float num = (float)i / 5f;
            NPC nPC = PlaceNPCOnGround(Utils.SelectRandom(Main.rand, new short[4] { 46, 46, 299, 538 }), _startPoint + new Vector2((num - 0.25f) * 400f + Main.rand.NextFloat() * 50f - 25f, 0f));
            nPC.ai[0] = 0f;
            nPC.ai[1] = 600f;
            _critters.Add(nPC);
        }
        if (_dryad != null)
        {
            for (int j = 0; j < 10; j++)
            {
                _ = (float)j / 10f;
                int num2 = NPC.NewNPC(new EntitySource_Film(), (int)_dryad.position.X + Main.rand.Next(-1000, 800), (int)_dryad.position.Y - Main.rand.Next(-50, 300), 356);
                NPC nPC2 = Main.npc[num2];
                nPC2.ai[0] = Main.rand.NextFloat() * 4f - 2f;
                nPC2.ai[1] = Main.rand.NextFloat() * 4f - 2f;
                nPC2.velocity.X = Main.rand.NextFloat() * 4f - 2f;
                _critters.Add(nPC2);
            }
        }
    }
References Terraria.Cinematics.DD2Film._critters, Terraria.Cinematics.DD2Film._dryad, Terraria.Cinematics.DD2Film._startPoint, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.Cinematics.DD2Film.PlaceNPCOnGround(), Terraria.Entity.position, and Terraria.Main.rand.
Referenced by Terraria.Cinematics.DD2Film.DD2Film().