TModLoader: Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance
AddTileVariance()
static void Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance (DesertDescription description) inline static private
    {
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e4: Unknown result type (might be due to invalid IL or missing references)
        for (int i = -20; i < description.Hive.Width + 20; i++)
        {
            for (int j = -20; j < description.Hive.Height + 20; j++)
            {
                int num = i + description.Hive.X;
                int num2 = j + description.Hive.Y;
                if (WorldGen.InWorld(num, num2, 1))
                {
                    Tile tile = Main.tile[num, num2];
                    Tile testTile = Main.tile[num, num2 + 1];
                    Tile testTile2 = Main.tile[num, num2 + 2];
                    if (tile.type == 53 && (!WorldGen.SolidTile(testTile) || !WorldGen.SolidTile(testTile2)))
                    {
                        tile.type = 397;
                    }
                }
            }
        }
        for (int k = -20; k < description.Hive.Width + 20; k++)
        {
            for (int l = -20; l < description.Hive.Height + 20; l++)
            {
                int num3 = k + description.Hive.X;
                int num4 = l + description.Hive.Y;
                if (!WorldGen.InWorld(num3, num4, 1))
                {
                    continue;
                }
                Tile tile2 = Main.tile[num3, num4];
                if (!tile2.active() || tile2.type != 396)
                {
                    continue;
                }
                bool flag = true;
                for (int num5 = -1; num5 >= -3; num5--)
                {
                    if (Main.tile[num3, num4 + num5].active())
                    {
                        flag = false;
                        break;
                    }
                }
                bool flag2 = true;
                for (int m = 1; m <= 3; m++)
                {
                    if (Main.tile[num3, num4 + m].active())
                    {
                        flag2 = false;
                        break;
                    }
                }
                if (!WorldGen.remixWorldGen || !((double)num4 > Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2)))
                {
                    if (flag && WorldGen.genRand.Next(20) == 0)
                    {
                        WorldGen.PlaceTile(num3, num4 - 1, 485, mute: true, forced: true, -1, WorldGen.genRand.Next(4));
                    }
                    else if (flag && WorldGen.genRand.Next(5) == 0)
                    {
                        WorldGen.PlaceTile(num3, num4 - 1, 484, mute: true, forced: true);
                    }
                    else if ((flag ^ flag2) && WorldGen.genRand.Next(5) == 0)
                    {
                        WorldGen.PlaceTile(num3, num4 + ((!flag) ? 1 : (-1)), 165, mute: true, forced: true);
                    }
                    else if (flag && WorldGen.genRand.Next(5) == 0)
                    {
                        WorldGen.PlaceTile(num3, num4 - 1, 187, mute: true, forced: true, -1, 29 + WorldGen.genRand.Next(6));
                    }
                }
            }
        }
    }
References Terraria.WorldGen.genRand, Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, Terraria.WorldGen.InWorld(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Biomes.Desert.DesertHive.Place().