TModLoader: Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClusters
PlaceClusters()
static void Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClusters (DesertDescription description, ClusterGroup clusters) inline static private
Definition at line 233 of file DesertHive.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0018: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        Rectangle hive = description.Hive;
        ((Rectangle)(ref hive)).Inflate(20, 20);
        PostPlacementEffect[,] array = new PostPlacementEffect[hive.Width, hive.Height];
        PlaceClustersArea(description, clusters, hive, array, Point.Zero);
        for (int i = ((Rectangle)(ref hive)).Left; i < ((Rectangle)(ref hive)).Right; i++)
        {
            for (int j = ((Rectangle)(ref hive)).Top; j < ((Rectangle)(ref hive)).Bottom; j++)
            {
                PostPlacementEffect postPlacementEffect = array[i - ((Rectangle)(ref hive)).Left, j - ((Rectangle)(ref hive)).Top];
                if (postPlacementEffect.HasFlag(PostPlacementEffect.Smooth))
                {
                    Tile.SmoothSlope(i, j, applyToNeighbors: false);
                }
            }
        }
    }
References Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), and Terraria.Tile.SmoothSlope().
Referenced by Terraria.GameContent.Biomes.Desert.DesertHive.Place().