TModLoader: Terraria.ID.ArmorIDs.Body.Sets.HidesHands
HidesHands
bool [] Terraria.ID.ArmorIDs.Body.Sets.HidesHands = Factory.CreateBoolSet(true, 77, 103, 41, 100, 10, 11, 12, 13, 14, 43, 15, 16, 20, 39, 50, 38, 40, 57, 44, 52, 53, 68, 81, 85, 88, 98, 86, 87, 99, 165, 166, 167, 171, 45, 168, 169, 42, 180, 181, 183, 186, 187, 188, 64, 189, 191, 192, 198, 199, 202, 203, 58, 59, 60, 61, 62, 63, 36, 104, 184, 74, 78, 185, 196, 197, 182, 87, 76, 209, 168, 210, 211, 213) static
If true for a given T:Terraria.ID.ArmorIDs.Body, then that equip will hide the player's hand skins when equipped.
Defaults to true.
Definition at line 791 of file ArmorIDs.cs.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup_2(), Terraria.ModLoader.Default.Patreon.Tantamount_Body.SetStaticDefaults(), and Terraria.ModLoader.Default.Patreon.xAqult_Body.SetStaticDefaults().