TModLoader: Terraria.ModLoader.Utilities.HjsonExtensions.WriteFancyHjsonValue
WriteFancyHjsonValue()
static void Terraria.ModLoader.Utilities.HjsonExtensions.WriteFancyHjsonValue (TextWriter tw, JsonValue value, int level, in HjsonStyle style, bool hasComments = false, bool noIndentation = false, bool isRootObject = false) inline static private
Definition at line 66 of file HjsonExtensions.cs.
    {
        //IL_0001: Unknown result type (might be due to invalid IL or missing references)
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_0008: Unknown result type (might be due to invalid IL or missing references)
        //IL_0023: Expected I4, but got Unknown
        //IL_02fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0308: Unknown result type (might be due to invalid IL or missing references)
        //IL_0327: Unknown result type (might be due to invalid IL or missing references)
        //IL_032b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0330: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_034c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e9: Unknown result type (might be due to invalid IL or missing references)
        JsonType jsonType = value.JsonType;
        switch ((int)jsonType)
        {
        case 2:
        {
            JsonObject jObject = JsonUtil.Qo(value);
            WscJsonObject commentedObject = (WscJsonObject)(object)(style.WriteComments ? ((jObject is WscJsonObject) ? jObject : null) : null);
            bool showBraces = !isRootObject || ((commentedObject != null) ? commentedObject.RootBraces : style.EmitRootBraces);
            if (!noIndentation || showBraces)
            {
                tw.Write(style.Separator);
            }
            if (showBraces)
            {
                tw.Write("{");
            }
            if (commentedObject != null)
            {
                bool skipFirst = !showBraces;
                string kwl = GetComments(commentedObject.Comments, "");
                JsonType? lastJsonType = null;
                foreach (string key in commentedObject.Order.Concat(((JsonObject)commentedObject).Keys).Distinct())
                {
                    if (!((JsonValue)jObject).ContainsKey(key))
                    {
                        continue;
                    }
                    JsonValue val = ((JsonValue)jObject)[key];
                    if (((JsonType?)val.JsonType != lastJsonType && lastJsonType.HasValue) || lastJsonType == (JsonType?)2)
                    {
                        NewLine(tw, 0);
                    }
                    if (!skipFirst)
                    {
                        NewLine(tw, level + (showBraces ? 1 : 0));
                    }
                    else
                    {
                        skipFirst = false;
                    }
                    if (!string.IsNullOrWhiteSpace(kwl))
                    {
                        string indentation = new string('\t', level + (showBraces ? 1 : 0));
                        string[] lines = (from s in kwl.TrimStart().Split(new string[3] { "\r\n", "\r", "\n" }, StringSplitOptions.TrimEntries)
                            select s.Trim()).ToArray();
                        kwl = string.Join("\n" + indentation, lines);
                        tw.Write(kwl);
                        NewLine(tw, level + (showBraces ? 1 : 0));
                    }
                    lastJsonType = val.JsonType;
                    kwl = GetComments(commentedObject.Comments, key);
                    bool num = jObject is LocalizationLoader.CommentedWscJsonObject commented && commented.CommentedOut.Contains(key);
                    bool commentIsMultiline = false;
                    if (num)
                    {
                        commentIsMultiline = val.GetRawString().IndexOf('\n') != -1;
                        if (commentIsMultiline)
{
                            tw.Write("/* ");
                        }
                        else
{
                            tw.Write("// ");
                        }
                    }
                    tw.Write(escapeName(key));
                    tw.Write(':');
                    WriteFancyHjsonValue(tw, val, level + (showBraces ? 1 : 0), in style, TestCommentString(kwl));
                    if (num && commentIsMultiline)
                    {
                        tw.Write(" */");
                    }
                }
                tw.Write(kwl);
                if (showBraces)
                {
                    NewLine(tw, level);
                }
            }
            else
            {
                bool skipFirst2 = !showBraces;
                JsonType? lastJsonType2 = null;
                foreach (KeyValuePair<string, JsonValue> pair in (IEnumerable<KeyValuePair<string, JsonValue>>)jObject)
                {
                    if (((JsonType?)pair.Value.JsonType != lastJsonType2 && lastJsonType2.HasValue) || lastJsonType2 == (JsonType?)2)
                    {
                        NewLine(tw, 0);
                    }
                    lastJsonType2 = pair.Value.JsonType;
                    if (!skipFirst2)
                    {
                        NewLine(tw, level + 1);
                    }
                    else
                    {
                        skipFirst2 = false;
                    }
                    tw.Write(escapeName(pair.Key));
                    tw.Write(':');
                    WriteFancyHjsonValue(tw, pair.Value, level + (showBraces ? 1 : 0), in style, hasComments: false, noIndentation: true);
                }
                if (showBraces && ((JsonValue)jObject).Count > 0)
                {
                    NewLine(tw, level);
                }
            }
            if (showBraces)
            {
                tw.Write('}');
            }
            break;
        }
        case 3:
        {
            int i = 0;
            int j = value.Count;
            if (!style.NoIndentaion)
            {
                if (j > 0)
                {
                    NewLine(tw, level);
                }
                else
                {
                    tw.Write(style.Separator);
                }
            }
            tw.Write('[');
            WscJsonArray whiteL = null;
            string wsl = null;
            if (style.WriteComments)
            {
                whiteL = (WscJsonArray)(object)((value is WscJsonArray) ? value : null);
                if (whiteL != null)
                {
                    wsl = GetComments(whiteL.Comments, 0);
                }
            }
            for (; i < j; i++)
            {
                JsonValue v = value[i];
                if (whiteL != null)
                {
                    tw.Write(wsl);
                    wsl = GetComments(whiteL.Comments, i + 1);
                }
                NewLine(tw, level + 1);
                WriteFancyHjsonValue(tw, v, level + 1, in style, wsl != null && TestCommentString(wsl));
            }
            if (whiteL != null)
            {
                tw.Write(wsl);
            }
            if (j > 0)
            {
                NewLine(tw, level);
            }
            tw.Write(']');
            break;
        }
        case 4:
            tw.Write(style.Separator);
            tw.Write(JsonValue.op_Implicit(value) ? "true" : "false");
            break;
        case 0:
            WriteString(tw, value.GetRawString(), level, hasComments, style.Separator);
            break;
        default:
            tw.Write(style.Separator);
            tw.Write(value.GetRawString());
            break;
        }
    }
References Terraria.ModLoader.Utilities.HjsonExtensions.escapeName, Terraria.ModLoader.Utilities.HjsonExtensions.GetComments(), Terraria.ModLoader.Utilities.HjsonExtensions.NewLine(), Terraria.ModLoader.Utilities.HjsonExtensions.TestCommentString(), Terraria.ModLoader.Utilities.HjsonExtensions.WriteFancyHjsonValue(), and Terraria.ModLoader.Utilities.HjsonExtensions.WriteString().
Referenced by Terraria.ModLoader.Utilities.HjsonExtensions.ToFancyHjsonString(), and Terraria.ModLoader.Utilities.HjsonExtensions.WriteFancyHjsonValue().