TModLoader: Terraria.ModLoader.UI.UIFocusInputTextField.SetText
SetText()
void Terraria.ModLoader.UI.UIFocusInputTextField.SetText (string text) inline
Definition at line 37 of file UIFocusInputTextField.cs.
    {
        if (text == null)
        {
            text = "";
        }
        if (CurrentString != text)
        {
            CurrentString = text;
            this.OnTextChange?.Invoke(this, new EventArgs());
        }
    }
References Terraria.ModLoader.UI.UIFocusInputTextField.CurrentString.
Referenced by Terraria.ModLoader.Config.UI.UIModConfig.OnActivate(), Terraria.ModLoader.UI.UICreateMod.OnActivate(), Terraria.ModLoader.Config.UI.DefinitionElement< T >.OnBind(), Terraria.ModLoader.Config.UI.UIModConfig.OnInitialize(), and Terraria.ModLoader.UI.UICreateMod.OnInitialize().