TModLoader: Terraria.UI.ItemSlot.AccCheck
AccCheck()
static bool Terraria.UI.ItemSlot.AccCheck (Item[] itemCollection, Item item, int slot) inline static
Definition at line 3036 of file ItemSlot.cs.
    {
        if (isEquipLocked(item.type))
        {
            return true;
        }
        if (slot != -1)
        {
            if (itemCollection[slot].IsTheSameAs(item))
            {
                return false;
            }
            if (itemCollection[slot].wingSlot > 0 && item.wingSlot > 0)
            {
                return false;
            }
        }
        for (int i = 0; i < itemCollection.Length; i++)
        {
            if (slot < 10 && i < 10)
            {
                if (item.wingSlot > 0 && itemCollection[i].wingSlot > 0)
                {
                    return true;
                }
                if (slot >= 10 && i >= 10 && item.wingSlot > 0 && itemCollection[i].wingSlot > 0)
                {
                    return true;
                }
            }
            if (item.IsTheSameAs(itemCollection[i]))
            {
                return true;
            }
        }
        return false;
    }
References Terraria.UI.ItemSlot.isEquipLocked(), Terraria.Item.IsTheSameAs(), Terraria.Item.type, and Terraria.Item.wingSlot.
Referenced by Terraria.UI.ItemSlot.PickItemMovementAction(), and Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryFitting().