TModLoader: Terraria.UI.ItemSlot.TryEnteringBuildingMode
TryEnteringBuildingMode()
static bool Terraria.UI.ItemSlot.TryEnteringBuildingMode (Item[] inv, int context, int slot, Player player, ref string s) inline static private
Definition at line 4034 of file ItemSlot.cs.
    {
        int num = 0;
        if (IsABuildingItem(Main.mouseItem))
        {
            num = 1;
        }
        if (num == 0 && Main.mouseItem.stack <= 0 && context == 0 && IsABuildingItem(inv[slot]))
        {
            num = 2;
        }
        if (num > 0)
        {
            Item item = Main.mouseItem;
            if (num == 1)
            {
                item = Main.mouseItem;
            }
            if (num == 2)
            {
                item = inv[slot];
            }
            if (num != 1 || player.ItemSpace(item).CanTakeItemToPersonalInventory)
            {
                if (item.damage > 0 && item.ammo == 0)
                {
                    s += PlayerInput.BuildCommand(Lang.misc[60].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["QuickMount"]);
                }
                else if (item.createTile >= 0 || item.createWall > 0)
                {
                    s += PlayerInput.BuildCommand(Lang.misc[61].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["QuickMount"]);
                }
                else
                {
                    s += PlayerInput.BuildCommand(Lang.misc[63].Value, false, PlayerInput.ProfileGamepadUI.KeyStatus["QuickMount"]);
                }
                if (CanExecuteCommand() && PlayerInput.Triggers.JustPressed.QuickMount)
                {
                    PlayerInput.EnterBuildingMode();
                }
                return true;
            }
        }
        return false;
    }
References Terraria.Item.ammo, Terraria.GameInput.PlayerInput.BuildCommand(), Terraria.UI.ItemSlot.CanExecuteCommand(), Terraria.Player.ItemSpaceStatus.CanTakeItemToPersonalInventory, Terraria.Item.createTile, Terraria.Item.createWall, Terraria.Item.damage, Terraria.GameInput.PlayerInput.EnterBuildingMode(), Terraria.UI.ItemSlot.IsABuildingItem(), Terraria.Player.ItemSpace(), Terraria.GameInput.TriggersPack.JustPressed, Terraria.GameInput.KeyConfiguration.KeyStatus, Terraria.Lang.misc, Terraria.Main.mouseItem, Terraria.GameInput.PlayerInput.ProfileGamepadUI, Terraria.GameInput.TriggersSet.QuickMount, Terraria.Item.stack, Terraria.GameInput.PlayerInput.Triggers, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.UI.ItemSlot.GetGamepadInstructions().