TModLoader: Terraria.UI.ItemSlot.OverrideHover
OverrideHover() [1/2]
static void Terraria.UI.ItemSlot.OverrideHover (Item[] inv, int context = 0, int slot = 0) inline static
Definition at line 363 of file ItemSlot.cs.
    {
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        Item item = inv[slot];
        if (!PlayerInput.UsingGamepad)
        {
            UILinkPointNavigator.SuggestUsage(GetGamepadPointForSlot(inv, context, slot));
        }
        if (PlayerLoader.HoverSlot(Main.player[Main.myPlayer], inv, context, slot))
        {
            return;
        }
        bool shiftForcedOn = ShiftForcedOn;
        if (NotUsingGamepad && Options.DisableLeftShiftTrashCan && !shiftForcedOn)
        {
            if (ControlInUse && !Options.DisableQuickTrash)
            {
                if (item.type > 0 && item.stack > 0 && !inv[slot].favorited)
                {
                    switch (context)
                    {
                    case 0:
                    case 1:
                    case 2:
                        if (Main.npcShop > 0 && !item.favorited)
{
                            Main.cursorOverride = 10;
                        }
                        else
{
                            Main.cursorOverride = 6;
                        }
                        break;
                    case 3:
                    case 4:
                    case 7:
                    case 32:
                        if (Main.player[Main.myPlayer].ItemSpace(item).CanTakeItemToPersonalInventory)
{
                            Main.cursorOverride = 6;
                        }
                        break;
                    }
                }
            }
            else if (ShiftInUse)
            {
                bool flag = false;
                if (Main.LocalPlayer.tileEntityAnchor.IsInValidUseTileEntity())
                {
                    flag = Main.LocalPlayer.tileEntityAnchor.GetTileEntity().OverrideItemSlotHover(inv, context, slot);
                }
                if (item.type > 0 && item.stack > 0 && !inv[slot].favorited && !flag)
                {
                    switch (context)
                    {
                    case 0:
                        if (Main.CreativeMenu.IsShowingResearchMenu())
{
                            Main.cursorOverride = 9;
                            break;
                        }
                        goto case 1;
                    case 1:
                    case 2:
                        if (context == 0 && Main.InReforgeMenu)
{
                            if (item.Prefix(-3))
{
                                Main.cursorOverride = 9;
                            }
                        }
                        else if (context == 0 && Main.InGuideCraftMenu)
{
                            if (item.material)
{
                                Main.cursorOverride = 9;
                            }
                        }
                        else if (Main.player[Main.myPlayer].chest != -1 && ChestUI.TryPlacingInChest(item, justCheck: true, context))
{
                            Main.cursorOverride = 9;
                        }
                        break;
                    case 3:
                    case 4:
                    case 32:
                        if (Main.player[Main.myPlayer].ItemSpace(item).CanTakeItemToPersonalInventory)
{
                            Main.cursorOverride = 8;
                        }
                        break;
                    case 5:
                    case 7:
                    case 8:
                    case 9:
                    case 10:
                    case 11:
                    case 12:
                    case 16:
                    case 17:
                    case 18:
                    case 19:
                    case 20:
                    case 23:
                    case 24:
                    case 25:
                    case 26:
                    case 27:
                    case 29:
                    case 33:
                        if (Main.player[Main.myPlayer].ItemSpace(inv[slot]).CanTakeItemToPersonalInventory)
{
                            Main.cursorOverride = 7;
                        }
                        break;
                    }
                }
            }
        }
        else if (ShiftInUse)
        {
            bool flag2 = false;
            if (Main.LocalPlayer.tileEntityAnchor.IsInValidUseTileEntity())
            {
                flag2 = Main.LocalPlayer.tileEntityAnchor.GetTileEntity().OverrideItemSlotHover(inv, context, slot);
            }
            if (item.type > 0 && item.stack > 0 && !inv[slot].favorited && !flag2)
            {
                switch (context)
                {
                case 0:
                case 1:
                case 2:
                    if (Main.npcShop > 0 && !item.favorited)
                    {
                        if (!Options.DisableQuickTrash)
{
                            Main.cursorOverride = 10;
                        }
                    }
                    else if (context == 0 && Main.CreativeMenu.IsShowingResearchMenu())
                    {
                        Main.cursorOverride = 9;
                    }
                    else if (context == 0 && Main.InReforgeMenu)
                    {
                        if (item.Prefix(-3))
{
                            Main.cursorOverride = 9;
                        }
                    }
                    else if (context == 0 && Main.InGuideCraftMenu)
                    {
                        if (item.material)
{
                            Main.cursorOverride = 9;
                        }
                    }
                    else if (Main.player[Main.myPlayer].chest != -1)
                    {
                        if (ChestUI.TryPlacingInChest(item, justCheck: true, context))
{
                            Main.cursorOverride = 9;
                        }
                    }
                    else if (!Options.DisableQuickTrash)
                    {
                        Main.cursorOverride = 6;
                    }
                    break;
                case 3:
                case 4:
                case 32:
                    if (Main.player[Main.myPlayer].ItemSpace(item).CanTakeItemToPersonalInventory)
                    {
                        Main.cursorOverride = 8;
                    }
                    break;
                case 5:
                case 7:
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                case 16:
                case 17:
                case 18:
                case 19:
                case 20:
                case 23:
                case 24:
                case 25:
                case 26:
                case 27:
                case 29:
                case 33:
                    if (Main.player[Main.myPlayer].ItemSpace(inv[slot]).CanTakeItemToPersonalInventory)
                    {
                        Main.cursorOverride = 7;
                    }
                    break;
                }
            }
        }
        if (((KeyboardState)(ref Main.keyState)).IsKeyDown(Main.FavoriteKey) && (canFavoriteAt[context] || (Main.drawingPlayerChat && canShareAt[context])))
        {
            if (item.type > 0 && item.stack > 0 && Main.drawingPlayerChat)
            {
                Main.cursorOverride = 2;
            }
            else if (item.type > 0 && item.stack > 0)
            {
                Main.cursorOverride = 3;
            }
        }
    }
References Terraria.UI.ItemSlot.canFavoriteAt, Terraria.UI.ItemSlot.canShareAt, Terraria.Player.ItemSpaceStatus.CanTakeItemToPersonalInventory, Terraria.Player.chest, Terraria.UI.ItemSlot.ControlInUse, Terraria.Main.CreativeMenu, Terraria.UI.ItemSlot.Options.DisableLeftShiftTrashCan, Terraria.UI.ItemSlot.Options.DisableQuickTrash, Terraria.Main.drawingPlayerChat, Terraria.Item.favorited, Terraria.Main.FavoriteKey, Terraria.UI.ItemSlot.GetGamepadPointForSlot(), Terraria.DataStructures.PlayerInteractionAnchor.GetTileEntity(), Terraria.ModLoader.PlayerLoader.HoverSlot(), Terraria.Main.InGuideCraftMenu, Terraria.Main.InReforgeMenu, Terraria.DataStructures.PlayerInteractionAnchor.IsInValidUseTileEntity(), Terraria.Player.ItemSpace(), Terraria.Main.keyState, Terraria.Main.LocalPlayer, Terraria.Item.material, Terraria.Main.myPlayer, Terraria.UI.ItemSlot.NotUsingGamepad, Terraria.Main.npcShop, Terraria.DataStructures.TileEntity.OverrideItemSlotHover(), Terraria.Main.player, Terraria.Item.Prefix(), Terraria.UI.ItemSlot.ShiftForcedOn, Terraria.UI.ItemSlot.ShiftInUse, Terraria.Item.stack, Terraria.UI.Gamepad.UILinkPointNavigator.SuggestUsage(), Terraria.Player.tileEntityAnchor, Terraria.UI.ChestUI.TryPlacingInChest(), Terraria.Item.type, and Terraria.GameInput.PlayerInput.UsingGamepad.