TModLoader: Terraria.UI.ItemSlot.SellOrTrash
SellOrTrash()
static void Terraria.UI.ItemSlot.SellOrTrash (Item[] inv, int context, int slot) inline static
Definition at line 1025 of file ItemSlot.cs.
    {
        Player player = Main.player[Main.myPlayer];
        if (inv[slot].type <= 0)
        {
            return;
        }
        if (Main.npcShop > 0 && !inv[slot].favorited)
        {
            Chest chest = Main.instance.shop[Main.npcShop];
            if ((inv[slot].type < 71 || inv[slot].type > 74) && PlayerLoader.CanSellItem(player, player.TalkNPC, chest.item, inv[slot]))
            {
                if (player.SellItem(inv[slot]))
                {
                    AnnounceTransfer(new ItemTransferInfo(inv[slot], context, 15));
                    int soldItemIndex = chest.AddItemToShop(inv[slot]);
                    inv[slot].TurnToAir();
                    SoundEngine.PlaySound(18);
                    Recipe.FindRecipes();
                    PlayerLoader.PostSellItem(player, player.TalkNPC, chest.item, chest.item[soldItemIndex]);
                }
                else if (inv[slot].value == 0)
                {
                    AnnounceTransfer(new ItemTransferInfo(inv[slot], context, 15));
                    int soldItemIndex2 = chest.AddItemToShop(inv[slot]);
                    inv[slot].TurnToAir();
                    SoundEngine.PlaySound(7);
                    Recipe.FindRecipes();
                    PlayerLoader.PostSellItem(player, player.TalkNPC, chest.item, chest.item[soldItemIndex2]);
                }
            }
        }
        else if (!inv[slot].favorited)
        {
            SoundEngine.PlaySound(7);
            player.trashItem = inv[slot].Clone();
            AnnounceTransfer(new ItemTransferInfo(player.trashItem, context, 6));
            inv[slot].TurnToAir();
            if (context == 3 && Main.netMode == 1)
            {
                NetMessage.SendData(32, -1, -1, null, player.chest, slot);
            }
            Recipe.FindRecipes();
        }
    }
References Terraria.Chest.AddItemToShop(), Terraria.UI.ItemSlot.AnnounceTransfer(), Terraria.ModLoader.PlayerLoader.CanSellItem(), Terraria.Player.chest, Terraria.Recipe.FindRecipes(), Terraria.Main.instance, Terraria.Chest.item, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.npcShop, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ModLoader.PlayerLoader.PostSellItem(), Terraria.Player.SellItem(), Terraria.NetMessage.SendData(), Terraria.Main.shop, Terraria.Player.TalkNPC, and Terraria.Player.trashItem.
Referenced by Terraria.UI.ItemSlot.LeftClick_SellOrTrash().