TModLoader: Terraria.UI.ItemSlot.DrawRadialDpad
DrawRadialDpad()
static void Terraria.UI.ItemSlot.DrawRadialDpad (SpriteBatch sb, Vector2 position) inline static
    {
        //IL_0062: Unknown result type (might be due to invalid IL or missing references)
        //IL_0068: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_008e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_0115: Unknown result type (might be due to invalid IL or missing references)
        if (!PlayerInput.UsingGamepad || !PlayerInput.CurrentProfile.UsingDpadHotbar())
        {
            return;
        }
        Player player = Main.player[Main.myPlayer];
        if (player.chest != -1)
        {
            return;
        }
        Texture2D value = TextureAssets.HotbarRadial[0].Value;
        float num = (float)(int)Main.mouseTextColor / 255f;
        float num2 = 1f - (1f - num) * (1f - num);
        num2 *= 0.785f;
        Color color = Color.White * num2;
        sb.Draw(value, position, (Rectangle?)null, color, 0f, value.Size() / 2f, Main.inventoryScale, (SpriteEffects)0, 0f);
        for (int i = 0; i < 4; i++)
        {
            int num3 = player.DpadRadial.Bindings[i];
            if (num3 != -1)
            {
                Draw(sb, player.inventory, 14, num3, position + Utils.RotatedBy(new Vector2((float)(value.Width / 3), 0f), -(float)Math.PI / 2f + (float)Math.PI / 2f * (float)i) + new Vector2(-26f * Main.inventoryScale), Color.White);
            }
        }
    }
References Terraria.Player.SelectionRadial.Bindings, Terraria.Player.chest, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Player.DpadRadial, Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.TextureAssets.HotbarRadial, Terraria.Player.inventory, Terraria.Main.inventoryScale, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Utils.RotatedBy(), Terraria.GameInput.PlayerInputProfile.UsingDpadHotbar(), and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.DrawInventory().