TModLoader: Terraria.UI.ItemSlot.AccessorySwap
AccessorySwap()
static bool Terraria.UI.ItemSlot.AccessorySwap (Player player, Item item, ref Item result) inline static private
Definition at line 4121 of file ItemSlot.cs.
    {
        accSlotToSwapTo = -1;
        AccessorySlotLoader accLoader = LoaderManager.Get<AccessorySlotLoader>();
        Item[] accessories = AccessorySlotLoader.ModSlotPlayer(player).exAccessorySlot;
        for (int j = 3; j < 10; j++)
        {
            if (player.IsItemSlotUnlockedAndUsable(j) && player.armor[j].type == 0 && ItemLoader.CanEquipAccessory(item, j, modded: false))
            {
                accSlotToSwapTo = j - 3;
                break;
            }
        }
        if (accSlotToSwapTo < 0)
        {
            for (int i = 0; i < accessories.Length / 2; i++)
            {
                if (accLoader.ModdedIsItemSlotUnlockedAndUsable(i, player) && accessories[i].type == 0 && accLoader.CanAcceptItem(i, item, -10) && ItemLoader.CanEquipAccessory(item, i, modded: true))
                {
                    accSlotToSwapTo = i + 20;
                    break;
                }
            }
        }
        accLoader.ModifyDefaultSwapSlot(item, ref accSlotToSwapTo);
        for (int l = 0; l < player.armor.Length; l++)
        {
            if (item.IsTheSameAs(player.armor[l]) && ItemLoader.CanEquipAccessory(item, l, modded: false))
            {
                accSlotToSwapTo = l - 3;
            }
            if (l < 10 && ((item.wingSlot > 0 && player.armor[l].wingSlot > 0) || !ItemLoader.CanAccessoryBeEquippedWith(player.armor[l], item)) && ItemLoader.CanEquipAccessory(item, l, modded: false))
            {
                accSlotToSwapTo = l - 3;
            }
        }
        for (int k = 0; k < accessories.Length; k++)
        {
            if (item.IsTheSameAs(accessories[k]) && accLoader.CanAcceptItem(k, item, (k < accessories.Length / 2) ? (-10) : (-11)) && ItemLoader.CanEquipAccessory(item, k, modded: true))
            {
                accSlotToSwapTo = k + 20;
            }
            if (k < accLoader.list.Count && ((item.wingSlot > 0 && accessories[k].wingSlot > 0) || !ItemLoader.CanAccessoryBeEquippedWith(accessories[k], item)) && accLoader.CanAcceptItem(k, item, (k < accessories.Length / 2) ? (-10) : (-11)) && ItemLoader.CanEquipAccessory(item, k, modded: true))
            {
                accSlotToSwapTo = k + 20;
            }
        }
        if (accSlotToSwapTo == -1 && !ItemLoader.CanEquipAccessory(item, 0, modded: false))
        {
            return false;
        }
        accSlotToSwapTo = Math.Max(accSlotToSwapTo, 0);
        if (accSlotToSwapTo >= 20)
        {
            int num3 = accSlotToSwapTo - 20;
            if (isEquipLocked(accessories[num3].type))
            {
                result = item;
                return false;
            }
            result = accessories[num3].Clone();
            accessories[num3] = item.Clone();
        }
        else
        {
            int num4 = 3 + accSlotToSwapTo;
            if (isEquipLocked(player.armor[num4].type))
            {
                result = item;
                return false;
            }
            result = player.armor[num4].Clone();
            player.armor[num4] = item.Clone();
        }
        return true;
    }
References Terraria.UI.ItemSlot.accSlotToSwapTo, Terraria.Player.armor, Terraria.ModLoader.ItemLoader.CanAccessoryBeEquippedWith(), Terraria.ModLoader.ItemLoader.CanEquipAccessory(), Terraria.Item.Clone(), Terraria.ModLoader.Default.ModAccessorySlotPlayer.exAccessorySlot, Terraria.UI.ItemSlot.isEquipLocked(), Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.Item.IsTheSameAs(), Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer(), Terraria.Item.type, and Terraria.Item.wingSlot.
Referenced by Terraria.UI.ItemSlot.ArmorSwap().