TModLoader: Terraria.UI.ItemSlot.DrawRadialCircular
DrawRadialCircular()
static void Terraria.UI.ItemSlot.DrawRadialCircular (SpriteBatch sb, Vector2 position, Player::SelectionRadial radial, Item[] items) inline static
    {
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0116: Unknown result type (might be due to invalid IL or missing references)
        //IL_0132: Unknown result type (might be due to invalid IL or missing references)
        //IL_0133: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_0144: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_018a: Unknown result type (might be due to invalid IL or missing references)
        //IL_018b: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a6: Unknown result type (might be due to invalid IL or missing references)
        CircularRadialOpacity = MathHelper.Clamp(CircularRadialOpacity + ((PlayerInput.UsingGamepad && PlayerInput.Triggers.Current.RadialHotbar) ? 0.25f : (-0.15f)), 0f, 1f);
        if (CircularRadialOpacity == 0f)
        {
            return;
        }
        Texture2D value = TextureAssets.HotbarRadial[2].Value;
        float num = CircularRadialOpacity * 0.9f;
        float num2 = CircularRadialOpacity * 1f;
        float num3 = (float)(int)Main.mouseTextColor / 255f;
        float num4 = 1f - (1f - num3) * (1f - num3);
        num4 *= 0.785f;
        Color color = Color.White * num4 * num;
        value = TextureAssets.HotbarRadial[1].Value;
        float num5 = (float)Math.PI * 2f / (float)radial.RadialCount;
        float num6 = -(float)Math.PI / 2f;
        for (int i = 0; i < radial.RadialCount; i++)
        {
            int num7 = radial.Bindings[i];
            Vector2 vector = Utils.RotatedBy(new Vector2(150f, 0f), num6 + num5 * (float)i) * num2;
            float num8 = 0.85f;
            if (radial.SelectedBinding == i)
            {
                num8 = 1.7f;
            }
            sb.Draw(value, position + vector, (Rectangle?)null, color * num8, 0f, value.Size() / 2f, num2 * num8, (SpriteEffects)0, 0f);
            if (num7 != -1)
            {
                float inventoryScale = Main.inventoryScale;
                Main.inventoryScale = num2 * num8;
                Draw(sb, items, 14, num7, position + vector + new Vector2(-26f * num2 * num8), Color.White);
                Main.inventoryScale = inventoryScale;
            }
        }
    }
References Terraria.UI.ItemSlot.CircularRadialOpacity, Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.TextureAssets.HotbarRadial, Terraria.Main.inventoryScale, Terraria.Utils.RotatedBy(), Terraria.GameInput.PlayerInput.Triggers, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.DrawInterface_32_GamepadRadialHotbars().