TModLoader: Terraria.UI.ItemSlot.DrawMoney
DrawMoney()
static void Terraria.UI.ItemSlot.DrawMoney (SpriteBatch sb, string text, float shopx, float shopy, int[] coinsArray, bool horizontal = false) inline static
Definition at line 3170 of file ItemSlot.cs.
    {
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0072: Unknown result type (might be due to invalid IL or missing references)
        //IL_007c: Unknown result type (might be due to invalid IL or missing references)
        //IL_00af: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_010b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0117: Unknown result type (might be due to invalid IL or missing references)
        //IL_011d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0122: Unknown result type (might be due to invalid IL or missing references)
        //IL_012c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0206: Unknown result type (might be due to invalid IL or missing references)
        //IL_020b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0215: Unknown result type (might be due to invalid IL or missing references)
        Utils.DrawBorderStringFourWay(sb, FontAssets.MouseText.Value, text, shopx, shopy + 40f, Color.White * ((float)(int)Main.mouseTextColor / 255f), Color.Black, Vector2.Zero);
        if (horizontal)
        {
            Vector2 position = default(Vector2);
            for (int i = 0; i < 4; i++)
            {
                Main.instance.LoadItem(74 - i);
                if (i == 0)
                {
                    _ = coinsArray[3 - i];
                }
                ((Vector2)(ref position))._002Ector(shopx + ChatManager.GetStringSize(FontAssets.MouseText.Value, text, Vector2.One).X + (float)(24 * i) + 45f, shopy + 50f);
                sb.Draw(TextureAssets.Item[74 - i].Value, position, (Rectangle?)null, Color.White, 0f, TextureAssets.Item[74 - i].Value.Size() / 2f, 1f, (SpriteEffects)0, 0f);
                Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, coinsArray[3 - i].ToString(), position.X - 11f, position.Y, Color.White, Color.Black, new Vector2(0.3f), 0.75f);
            }
        }
        else
        {
            for (int j = 0; j < 4; j++)
            {
                Main.instance.LoadItem(74 - j);
                int num = ((j == 0 && coinsArray[3 - j] > 99) ? (-6) : 0);
                sb.Draw(TextureAssets.Item[74 - j].Value, new Vector2(shopx + 11f + (float)(24 * j), shopy + 75f), (Rectangle?)null, Color.White, 0f, TextureAssets.Item[74 - j].Value.Size() / 2f, 1f, (SpriteEffects)0, 0f);
                Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, coinsArray[3 - j].ToString(), shopx + (float)(24 * j) + (float)num, shopy + 75f, Color.White, Color.Black, new Vector2(0.3f), 0.75f);
            }
        }
    }
References Terraria.Utils.DrawBorderStringFourWay(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.GameContent.FontAssets.ItemStack, Terraria.GameContent.FontAssets.MouseText, and Terraria.Main.mouseTextColor.
Referenced by Terraria.UI.ItemSlot.DrawSavings(), Terraria.Main.GUIChatDrawInner(), and Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.UseMouseOver().