TModLoader: Terraria.UI.ItemSlot.DrawSavings
DrawSavings()
static void Terraria.UI.ItemSlot.DrawSavings (SpriteBatch sb, float shopx, float shopy, bool horizontal = false) inline static
Definition at line 3222 of file ItemSlot.cs.
    {
        //IL_00fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0102: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_0120: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_0146: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_0166: Unknown result type (might be due to invalid IL or missing references)
        //IL_0186: Unknown result type (might be due to invalid IL or missing references)
        //IL_018d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0197: Unknown result type (might be due to invalid IL or missing references)
        //IL_019c: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[Main.myPlayer];
        if (_customCurrencyForSavings != -1)
        {
            CustomCurrencyManager.DrawSavings(sb, _customCurrencyForSavings, shopx, shopy, horizontal);
            return;
        }
        bool overFlowing;
        long num = Utils.CoinsCount(out overFlowing, player.bank.item);
        long num2 = Utils.CoinsCount(out overFlowing, player.bank2.item);
        long num3 = Utils.CoinsCount(out overFlowing, player.bank3.item);
        long num4 = Utils.CoinsCount(out overFlowing, player.bank4.item);
        long num5 = Utils.CoinsCombineStacks(out overFlowing, num, num2, num3, num4);
        if (num5 > 0)
        {
            Main.GetItemDrawFrame(4076, out var itemTexture, out var itemFrame);
            Main.GetItemDrawFrame(3813, out var itemTexture2, out var itemFrame2);
            Main.GetItemDrawFrame(346, out var itemTexture3, out var itemFrame3);
            Main.GetItemDrawFrame(87, out var itemTexture4, out itemFrame3);
            if (num4 > 0)
            {
                sb.Draw(itemTexture, Utils.CenteredRectangle(new Vector2(shopx + 92f, shopy + 45f), itemFrame.Size() * 0.65f), (Rectangle?)null, Color.White);
            }
            if (num3 > 0)
            {
                sb.Draw(itemTexture2, Utils.CenteredRectangle(new Vector2(shopx + 92f, shopy + 45f), itemFrame2.Size() * 0.65f), (Rectangle?)null, Color.White);
            }
            if (num2 > 0)
            {
                sb.Draw(itemTexture3, Utils.CenteredRectangle(new Vector2(shopx + 80f, shopy + 50f), itemTexture3.Size() * 0.65f), (Rectangle?)null, Color.White);
            }
            if (num > 0)
            {
                sb.Draw(itemTexture4, Utils.CenteredRectangle(new Vector2(shopx + 70f, shopy + 60f), itemTexture4.Size() * 0.65f), (Rectangle?)null, Color.White);
            }
            DrawMoney(sb, Lang.inter[66].Value, shopx, shopy, Utils.CoinsSplit(num5), horizontal);
        }
    }
References Terraria.UI.ItemSlot._customCurrencyForSavings, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Utils.CenteredRectangle(), Terraria.Utils.CoinsCombineStacks(), Terraria.Utils.CoinsCount(), Terraria.Utils.CoinsSplit(), Terraria.UI.ItemSlot.DrawMoney(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), Terraria.Main.GetItemDrawFrame(), Terraria.Lang.inter, Terraria.Chest.item, Terraria.Main.myPlayer, and Terraria.Main.player.
Referenced by Terraria.Main.DrawHairWindow(), and Terraria.Main.DrawInventory().