TModLoader: Terraria.UI.ItemSlot.DrawRadialQuicks
DrawRadialQuicks()
static void Terraria.UI.ItemSlot.DrawRadialQuicks (SpriteBatch sb, Vector2 position) inline static
    {
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01da: Unknown result type (might be due to invalid IL or missing references)
        //IL_01db: Unknown result type (might be due to invalid IL or missing references)
        //IL_01dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0205: Unknown result type (might be due to invalid IL or missing references)
        //IL_0234: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_0237: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_024c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0251: Unknown result type (might be due to invalid IL or missing references)
        //IL_0262: Unknown result type (might be due to invalid IL or missing references)
        //IL_0263: Unknown result type (might be due to invalid IL or missing references)
        //IL_0265: Unknown result type (might be due to invalid IL or missing references)
        //IL_0274: Unknown result type (might be due to invalid IL or missing references)
        //IL_027e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0285: Unknown result type (might be due to invalid IL or missing references)
        //IL_028c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0291: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_02af: Unknown result type (might be due to invalid IL or missing references)
        //IL_02b9: Unknown result type (might be due to invalid IL or missing references)
        QuicksRadialOpacity = MathHelper.Clamp(QuicksRadialOpacity + ((PlayerInput.UsingGamepad && PlayerInput.Triggers.Current.RadialQuickbar) ? 0.25f : (-0.15f)), 0f, 1f);
        if (QuicksRadialOpacity == 0f)
        {
            return;
        }
        Player player = Main.player[Main.myPlayer];
        Texture2D value = TextureAssets.HotbarRadial[2].Value;
        Texture2D value2 = TextureAssets.QuicksIcon.Value;
        float num = QuicksRadialOpacity * 0.9f;
        float num2 = QuicksRadialOpacity * 1f;
        float num3 = (float)(int)Main.mouseTextColor / 255f;
        float num4 = 1f - (1f - num3) * (1f - num3);
        num4 *= 0.785f;
        Color color = Color.White * num4 * num;
        float num5 = (float)Math.PI * 2f / (float)player.QuicksRadial.RadialCount;
        float num6 = -(float)Math.PI / 2f;
        Item item = player.QuickHeal_GetItemToUse();
        Item item2 = player.QuickMana_GetItemToUse();
        Item item3 = null;
        Item item4 = null;
        if (item == null)
        {
            item = new Item();
            item.SetDefaults(28);
        }
        if (item2 == null)
        {
            item2 = new Item();
            item2.SetDefaults(110);
        }
        if (item3 == null)
        {
            item3 = new Item();
            item3.SetDefaults(292);
        }
        if (item4 == null)
        {
            item4 = new Item();
            item4.SetDefaults(2428);
        }
        for (int i = 0; i < player.QuicksRadial.RadialCount; i++)
        {
            Item inv = item4;
            if (i == 1)
            {
                inv = item;
            }
            if (i == 2)
            {
                inv = item3;
            }
            if (i == 3)
            {
                inv = item2;
            }
            _ = player.QuicksRadial.Bindings[i];
            Vector2 vector = Utils.RotatedBy(new Vector2(120f, 0f), num6 + num5 * (float)i) * num2;
            float num7 = 0.85f;
            if (player.QuicksRadial.SelectedBinding == i)
            {
                num7 = 1.7f;
            }
            sb.Draw(value, position + vector, (Rectangle?)null, color * num7, 0f, value.Size() / 2f, num2 * num7 * 1.3f, (SpriteEffects)0, 0f);
            float inventoryScale = Main.inventoryScale;
            Main.inventoryScale = num2 * num7;
            Draw(sb, ref inv, 14, position + vector + new Vector2(-26f * num2 * num7), Color.White);
            Main.inventoryScale = inventoryScale;
            sb.Draw(value2, position + vector + new Vector2(34f, 20f) * 0.85f * num2 * num7, (Rectangle?)null, color * num7, 0f, value.Size() / 2f, num2 * num7 * 1.3f, (SpriteEffects)0, 0f);
        }
    }
References Terraria.Player.SelectionRadial.Bindings, Terraria.GameInput.TriggersPack.Current, Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.TextureAssets.HotbarRadial, Terraria.Main.inventoryScale, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Player.QuickHeal_GetItemToUse(), Terraria.Player.QuickMana_GetItemToUse(), Terraria.GameContent.TextureAssets.QuicksIcon, Terraria.Player.QuicksRadial, Terraria.UI.ItemSlot.QuicksRadialOpacity, Terraria.Player.SelectionRadial.RadialCount, Terraria.GameInput.TriggersSet.RadialQuickbar, Terraria.Utils.RotatedBy(), Terraria.Player.SelectionRadial.SelectedBinding, Terraria.Item.SetDefaults(), Terraria.GameInput.PlayerInput.Triggers, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.Main.DrawInterface_32_GamepadRadialHotbars().