TModLoader: Terraria.UI.ItemSlot.RightClick
RightClick() [1/2]
static void Terraria.UI.ItemSlot.RightClick (Item[] inv, int context = 0, int slot = 0) inline static
Definition at line 1332 of file ItemSlot.cs.
    {
        Player player = Main.player[Main.myPlayer];
        inv[slot].newAndShiny = false;
        if (player.itemAnimation > 0)
        {
            return;
        }
        if (context == 15)
        {
            HandleShopSlot(inv, slot, rightClickIsValid: true, leftClickIsValid: false);
        }
        else
        {
            if (!Main.mouseRight)
            {
                return;
            }
            if (context == 0 && Main.mouseRightRelease)
            {
                TryItemSwap(inv[slot]);
            }
            if (context == 0 && ItemLoader.CanRightClick(inv[slot]))
            {
                if (Main.mouseRightRelease)
                {
                    if (Main.ItemDropsDB.GetRulesForItemID(inv[slot].type).Any())
                    {
                        TryOpenContainer(inv[slot], player);
                    }
                    else
                    {
                        ItemLoader.RightClick(inv[slot], player);
                    }
                }
                return;
            }
            switch (Math.Abs(context))
            {
            case 9:
            case 11:
                if (Main.mouseRightRelease)
                {
                    SwapVanityEquip(inv, context, slot, player);
                }
                break;
            case 12:
            case 25:
            case 27:
            case 33:
                if (Main.mouseRightRelease)
                {
                    TryPickupDyeToCursor(context, inv, slot, player);
                }
                break;
            case 0:
            case 3:
            case 4:
            case 32:
                if (inv[slot].maxStack == 1)
                {
                    if (Main.mouseRightRelease)
                    {
                        SwapEquip(inv, context, slot);
                    }
                    break;
                }
                goto default;
            default:
            {
                if (Main.stackSplit > 1)
                {
                    break;
                }
                bool flag = true;
                bool flag2 = inv[slot].maxStack <= 1 && inv[slot].stack <= 1;
                if (context == 0 && flag2)
                {
                    flag = false;
                }
                if (context == 3 && flag2)
                {
                    flag = false;
                }
                if (context == 4 && flag2)
                {
                    flag = false;
                }
                if (context == 32 && flag2)
                {
                    flag = false;
                }
                if (!flag)
                {
                    break;
                }
                int num = Main.superFastStack + 1;
                for (int i = 0; i < num; i++)
                {
                    if (((Main.mouseItem.IsTheSameAs(inv[slot]) && ItemLoader.CanStack(Main.mouseItem, inv[slot])) || Main.mouseItem.type == 0) && (Main.mouseItem.stack < Main.mouseItem.maxStack || Main.mouseItem.type == 0))
                    {
                        PickupItemIntoMouse(inv, context, slot, player);
                        SoundEngine.PlaySound(12);
                        RefreshStackSplitCooldown();
                    }
                }
                break;
            }
            }
        }
    }
References Terraria.ModLoader.ItemLoader.CanRightClick(), Terraria.ModLoader.ItemLoader.CanStack(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.Player.itemAnimation, Terraria.Main.ItemDropsDB, Terraria.Main.mouseItem, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.myPlayer, Terraria.UI.ItemSlot.PickupItemIntoMouse(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.ItemSlot.RefreshStackSplitCooldown(), Terraria.ModLoader.ItemLoader.RightClick(), Terraria.Main.stackSplit, Terraria.UI.ItemSlot.SwapEquip(), Terraria.UI.ItemSlot.SwapVanityEquip(), Terraria.UI.ItemSlot.TryItemSwap(), Terraria.UI.ItemSlot.TryOpenContainer(), and Terraria.UI.ItemSlot.TryPickupDyeToCursor().