TModLoader: Terraria.UI.ItemSlot.DrawItemIcon
DrawItemIcon()
static float Terraria.UI.ItemSlot.DrawItemIcon (Item item, int context, SpriteBatch spriteBatch, Vector2 screenPositionForItemCenter, float scale, float sizeLimit, Color environmentColor) inline static
Definition at line 2597 of file ItemSlot.cs.
    {
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0046: Unknown result type (might be due to invalid IL or missing references)
        //IL_0059: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0070: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0083: Unknown result type (might be due to invalid IL or missing references)
        //IL_0084: Unknown result type (might be due to invalid IL or missing references)
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_0087: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0094: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0143: Unknown result type (might be due to invalid IL or missing references)
        //IL_0148: Unknown result type (might be due to invalid IL or missing references)
        //IL_0149: Unknown result type (might be due to invalid IL or missing references)
        //IL_014f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0156: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0104: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_019a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a5: Unknown result type (might be due to invalid IL or missing references)
        int num = item.type;
        if ((uint)(num - 5358) <= 3u && context == 31)
        {
            num = 5437;
        }
        Main.instance.LoadItem(num);
        Texture2D value = TextureAssets.Item[num].Value;
        Rectangle frame = ((Main.itemAnimations[num] == null) ? value.Frame() : Main.itemAnimations[num].GetFrame(value));
        DrawItem_GetColorAndScale(item, scale, ref environmentColor, sizeLimit, ref frame, out var itemLight, out var finalDrawScale);
        SpriteEffects effects = (SpriteEffects)0;
        Vector2 origin = frame.Size() / 2f;
        if (ItemLoader.PreDrawInInventory(item, spriteBatch, screenPositionForItemCenter, frame, item.GetAlpha(itemLight), item.GetColor(environmentColor), origin, finalDrawScale))
        {
            spriteBatch.Draw(value, screenPositionForItemCenter, (Rectangle?)frame, item.GetAlpha(itemLight), 0f, origin, finalDrawScale, effects, 0f);
            if (item.color != Color.Transparent)
            {
                Color newColor = environmentColor;
                if (context == 13)
                {
                    ((Color)(ref newColor)).A = byte.MaxValue;
                }
                spriteBatch.Draw(value, screenPositionForItemCenter, (Rectangle?)frame, item.GetColor(newColor), 0f, origin, finalDrawScale, effects, 0f);
            }
            switch (num)
            {
            case 5140:
            case 5141:
            case 5142:
            case 5143:
            case 5144:
            case 5145:
            {
                Texture2D value3 = TextureAssets.GlowMask[item.glowMask].Value;
                Color white = Color.White;
                spriteBatch.Draw(value3, screenPositionForItemCenter, (Rectangle?)frame, white, 0f, origin, finalDrawScale, effects, 0f);
                break;
            }
            case 5146:
            {
                Texture2D value2 = TextureAssets.GlowMask[324].Value;
                Color val = default(Color);
                ((Color)(ref val))._002Ector(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                spriteBatch.Draw(value2, screenPositionForItemCenter, (Rectangle?)frame, val, 0f, origin, finalDrawScale, effects, 0f);
                break;
            }
            }
        }
        ItemLoader.PostDrawInInventory(item, spriteBatch, screenPositionForItemCenter, frame, item.GetAlpha(itemLight), item.GetColor(environmentColor), origin, finalDrawScale);
        return finalDrawScale;
    }
References Terraria.Item.color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.UI.ItemSlot.DrawItem_GetColorAndScale(), Terraria.Item.GetAlpha(), Terraria.Item.GetColor(), Terraria.DataStructures.DrawAnimation.GetFrame(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.Item.glowMask, Terraria.Main.instance, Terraria.GameContent.TextureAssets.Item, Terraria.Main.itemAnimations, Terraria.Main.LoadItem(), Terraria.ModLoader.ItemLoader.PostDrawInInventory(), Terraria.ModLoader.ItemLoader.PreDrawInInventory(), and Terraria.Item.type.
Referenced by Terraria.Graphics.Renderers.ItemTransferParticle.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.UI.Elements.UIItemIcon.DrawSelf(), and Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy().