TModLoader: Terraria.UI.ItemSlot.Draw
Draw() [1/2]
static void Terraria.UI.ItemSlot.Draw (SpriteBatch spriteBatch, Item[] inv, int context, int slot, Vector2 position, Color lightColor = default(Color)) inline static
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_001c: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_002a: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_008a: Unknown result type (might be due to invalid IL or missing references)
        //IL_008f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0325: Unknown result type (might be due to invalid IL or missing references)
        //IL_032a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0350: Unknown result type (might be due to invalid IL or missing references)
        //IL_0355: Unknown result type (might be due to invalid IL or missing references)
        //IL_037b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0380: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0511: Unknown result type (might be due to invalid IL or missing references)
        //IL_0518: Unknown result type (might be due to invalid IL or missing references)
        //IL_0533: Unknown result type (might be due to invalid IL or missing references)
        //IL_053a: Unknown result type (might be due to invalid IL or missing references)
        //IL_053f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0558: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_0567: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0155: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015f: Unknown result type (might be due to invalid IL or missing references)
        //IL_065c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0661: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0203: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_01de: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_067c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0681: Unknown result type (might be due to invalid IL or missing references)
        //IL_0683: Unknown result type (might be due to invalid IL or missing references)
        //IL_0687: Unknown result type (might be due to invalid IL or missing references)
        //IL_068d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0692: Unknown result type (might be due to invalid IL or missing references)
        //IL_05c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ce: Unknown result type (might be due to invalid IL or missing references)
        //IL_05d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0208: Unknown result type (might be due to invalid IL or missing references)
        //IL_06c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_06db: Unknown result type (might be due to invalid IL or missing references)
        //IL_0608: Unknown result type (might be due to invalid IL or missing references)
        //IL_060f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0614: Unknown result type (might be due to invalid IL or missing references)
        //IL_062d: Unknown result type (might be due to invalid IL or missing references)
        //IL_062f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0639: Unknown result type (might be due to invalid IL or missing references)
        //IL_063e: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_05eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_05f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_06b7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0904: Unknown result type (might be due to invalid IL or missing references)
        //IL_090a: Unknown result type (might be due to invalid IL or missing references)
        //IL_090f: Unknown result type (might be due to invalid IL or missing references)
        //IL_081f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0824: Unknown result type (might be due to invalid IL or missing references)
        //IL_0854: Unknown result type (might be due to invalid IL or missing references)
        //IL_0858: Unknown result type (might be due to invalid IL or missing references)
        //IL_0862: Unknown result type (might be due to invalid IL or missing references)
        //IL_0868: Unknown result type (might be due to invalid IL or missing references)
        //IL_086d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0872: Unknown result type (might be due to invalid IL or missing references)
        //IL_0874: Unknown result type (might be due to invalid IL or missing references)
        //IL_087e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0888: Unknown result type (might be due to invalid IL or missing references)
        //IL_088a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0894: Unknown result type (might be due to invalid IL or missing references)
        //IL_1043: Unknown result type (might be due to invalid IL or missing references)
        //IL_1047: Unknown result type (might be due to invalid IL or missing references)
        //IL_104d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1057: Unknown result type (might be due to invalid IL or missing references)
        //IL_105c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1063: Unknown result type (might be due to invalid IL or missing references)
        //IL_1069: Unknown result type (might be due to invalid IL or missing references)
        //IL_1073: Unknown result type (might be due to invalid IL or missing references)
        //IL_1078: Unknown result type (might be due to invalid IL or missing references)
        //IL_107d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1082: Unknown result type (might be due to invalid IL or missing references)
        //IL_1096: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a2: Unknown result type (might be due to invalid IL or missing references)
        //IL_10a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_092c: Unknown result type (might be due to invalid IL or missing references)
        //IL_092e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0935: Unknown result type (might be due to invalid IL or missing references)
        //IL_093a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0945: Unknown result type (might be due to invalid IL or missing references)
        //IL_0966: Unknown result type (might be due to invalid IL or missing references)
        //IL_0972: Unknown result type (might be due to invalid IL or missing references)
        //IL_0978: Unknown result type (might be due to invalid IL or missing references)
        //IL_097d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0987: Unknown result type (might be due to invalid IL or missing references)
        //IL_0991: Unknown result type (might be due to invalid IL or missing references)
        //IL_099c: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ac: Unknown result type (might be due to invalid IL or missing references)
        //IL_08b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08db: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_08e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08f1: Unknown result type (might be due to invalid IL or missing references)
        //IL_1179: Unknown result type (might be due to invalid IL or missing references)
        //IL_117b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1182: Unknown result type (might be due to invalid IL or missing references)
        //IL_1187: Unknown result type (might be due to invalid IL or missing references)
        //IL_09cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_09d7: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_09f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_09fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_09ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a01: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a16: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a1b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a20: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a2f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a39: Unknown result type (might be due to invalid IL or missing references)
        //IL_10eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_10f0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a82: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a88: Unknown result type (might be due to invalid IL or missing references)
        //IL_0a8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_1138: Unknown result type (might be due to invalid IL or missing references)
        //IL_1144: Unknown result type (might be due to invalid IL or missing references)
        //IL_114a: Unknown result type (might be due to invalid IL or missing references)
        //IL_114f: Unknown result type (might be due to invalid IL or missing references)
        //IL_1154: Unknown result type (might be due to invalid IL or missing references)
        //IL_115b: Unknown result type (might be due to invalid IL or missing references)
        //IL_1161: Unknown result type (might be due to invalid IL or missing references)
        //IL_116c: Unknown result type (might be due to invalid IL or missing references)
        //IL_1108: Unknown result type (might be due to invalid IL or missing references)
        //IL_110d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ad7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0adc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ae5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0af4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0afa: Unknown result type (might be due to invalid IL or missing references)
        //IL_0aff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b0b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b11: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b13: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b1d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b51: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b56: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b5f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b6e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b74: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b79: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b7e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b85: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b8d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0b97: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c42: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c54: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c59: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c5e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c64: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c6a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c75: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bc8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bcd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd4: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0be5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0beb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bf5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0bfc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c02: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c04: Unknown result type (might be due to invalid IL or missing references)
        //IL_0c0e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e21: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e2d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e33: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e38: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e3d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e43: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e4f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0e96: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ea8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ead: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ebe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ec9: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ee6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0eec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ef6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0efb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f0a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f10: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f1f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f24: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f27: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f28: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f3c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f41: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f4e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f5a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f63: Unknown result type (might be due to invalid IL or missing references)
        //IL_0f69: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fae: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fb8: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fc7: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fd6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fdc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0fe6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0feb: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff0: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0ff7: Unknown result type (might be due to invalid IL or missing references)
        //IL_1004: Unknown result type (might be due to invalid IL or missing references)
        //IL_1010: Unknown result type (might be due to invalid IL or missing references)
        //IL_1019: Unknown result type (might be due to invalid IL or missing references)
        //IL_101f: Unknown result type (might be due to invalid IL or missing references)
        Player player = Main.player[Main.myPlayer];
        Item item = inv[slot];
        float inventoryScale = Main.inventoryScale;
        Color color = Color.White;
        if (lightColor != Color.Transparent)
        {
            color = lightColor;
        }
        bool flag = false;
        int num = 0;
        int gamepadPointForSlot = GetGamepadPointForSlot(inv, context, slot);
        if (PlayerInput.UsingGamepadUI)
        {
            flag = UILinkPointNavigator.CurrentPoint == gamepadPointForSlot;
            if (PlayerInput.SettingsForUI.PreventHighlightsForGamepad)
            {
                flag = false;
            }
            if (context == 0)
            {
                num = player.DpadRadial.GetDrawMode(slot);
                if (num > 0 && !PlayerInput.CurrentProfile.UsingDpadHotbar())
                {
                    num = 0;
                }
            }
        }
        Texture2D value = TextureAssets.InventoryBack.Value;
        Color color2 = Main.inventoryBack;
        bool flag2 = false;
        bool highlightThingsForMouse = PlayerInput.SettingsForUI.HighlightThingsForMouse;
        if (item.type > 0 && item.stack > 0 && item.favorited && context != 13 && context != 21 && context != 22 && context != 14)
        {
            value = TextureAssets.InventoryBack10.Value;
            if (context == 32)
            {
                value = TextureAssets.InventoryBack19.Value;
            }
        }
        else if (item.type > 0 && item.stack > 0 && Options.HighlightNewItems && item.newAndShiny && context != 13 && context != 21 && context != 14 && context != 22)
        {
            value = TextureAssets.InventoryBack15.Value;
            float num5 = (float)(int)Main.mouseTextColor / 255f;
            num5 = num5 * 0.2f + 0.8f;
            color2 = color2.MultiplyRGBA(new Color(num5, num5, num5));
        }
        else if (!highlightThingsForMouse && item.type > 0 && item.stack > 0 && num != 0 && context != 13 && context != 21 && context != 22)
        {
            value = TextureAssets.InventoryBack15.Value;
            float num6 = (float)(int)Main.mouseTextColor / 255f;
            num6 = num6 * 0.2f + 0.8f;
            color2 = ((num != 1) ? color2.MultiplyRGBA(new Color(num6 / 2f, num6, num6 / 2f)) : color2.MultiplyRGBA(new Color(num6, num6 / 2f, num6 / 2f)));
        }
        else if (context == 0 && slot < 10)
        {
            value = TextureAssets.InventoryBack9.Value;
        }
        else
        {
            switch (context)
            {
            case 28:
                value = TextureAssets.InventoryBack7.Value;
                color2 = Color.White;
                break;
            case 16:
            case 17:
            case 18:
            case 19:
            case 20:
                value = TextureAssets.InventoryBack3.Value;
                break;
            case 8:
            case 10:
                value = TextureAssets.InventoryBack13.Value;
                color2 = GetColorByLoadout(slot, context);
                break;
            case 23:
            case 24:
            case 26:
                value = TextureAssets.InventoryBack8.Value;
                break;
            case 9:
            case 11:
                value = TextureAssets.InventoryBack13.Value;
                color2 = GetColorByLoadout(slot, context);
                break;
            case 25:
            case 27:
            case 33:
                value = TextureAssets.InventoryBack12.Value;
                break;
            case 12:
                value = TextureAssets.InventoryBack13.Value;
                color2 = GetColorByLoadout(slot, context);
                break;
            case -12:
            case -11:
            case -10:
                value = LoaderManager.Get<AccessorySlotLoader>().GetBackgroundTexture(slot, context);
                break;
            case 3:
                value = TextureAssets.InventoryBack5.Value;
                break;
            case 4:
            case 32:
                value = TextureAssets.InventoryBack2.Value;
                break;
            case 5:
            case 7:
                value = TextureAssets.InventoryBack4.Value;
                break;
            case 6:
                value = TextureAssets.InventoryBack7.Value;
                break;
            case 13:
            {
                byte b = 200;
                if (slot == Main.player[Main.myPlayer].selectedItem)
                {
                    value = TextureAssets.InventoryBack14.Value;
                    b = byte.MaxValue;
                }
                ((Color)(ref color2))._002Ector((int)b, (int)b, (int)b, (int)b);
                break;
            }
            case 14:
            case 21:
                flag2 = true;
                break;
            case 15:
                value = TextureAssets.InventoryBack6.Value;
                break;
            case 29:
                ((Color)(ref color2))._002Ector(53, 69, 127, 255);
                value = TextureAssets.InventoryBack18.Value;
                break;
            case 30:
                flag2 = !flag;
                break;
            case 22:
                value = TextureAssets.InventoryBack4.Value;
                if (DrawGoldBGForCraftingMaterial)
                {
                    DrawGoldBGForCraftingMaterial = false;
                    value = TextureAssets.InventoryBack14.Value;
                    float num7 = (float)(int)((Color)(ref color2)).A / 255f;
                    num7 = ((!(num7 < 0.7f)) ? 1f : Utils.GetLerpValue(0f, 0.7f, num7, clamped: true));
                    color2 = Color.White * num7;
                }
                break;
            }
        }
        if ((context == 0 || context == 2) && inventoryGlowTime[slot] > 0 && !inv[slot].favorited && !inv[slot].IsAir)
        {
            float num8 = Main.invAlpha / 255f;
            Color val = new Color(63, 65, 151, 255) * num8;
            Color value4 = Main.hslToRgb(inventoryGlowHue[slot], 1f, 0.5f) * num8;
            float num9 = (float)inventoryGlowTime[slot] / 300f;
            num9 *= num9;
            color2 = Color.Lerp(val, value4, num9 / 2f);
            value = TextureAssets.InventoryBack13.Value;
        }
        if ((context == 4 || context == 32 || context == 3) && inventoryGlowTimeChest[slot] > 0 && !inv[slot].favorited && !inv[slot].IsAir)
        {
            float num10 = Main.invAlpha / 255f;
            Color value5 = new Color(130, 62, 102, 255) * num10;
            if (context == 3)
            {
                value5 = new Color(104, 52, 52, 255) * num10;
            }
            Color value6 = Main.hslToRgb(inventoryGlowHueChest[slot], 1f, 0.5f) * num10;
            float num11 = (float)inventoryGlowTimeChest[slot] / 300f;
            num11 *= num11;
            color2 = Color.Lerp(value5, value6, num11 / 2f);
            value = TextureAssets.InventoryBack13.Value;
        }
        if (flag)
        {
            value = TextureAssets.InventoryBack14.Value;
            color2 = Color.White;
            if (item.favorited)
            {
                value = TextureAssets.InventoryBack17.Value;
            }
        }
        if (context == 28 && Main.MouseScreen.Between(position, position + value.Size() * inventoryScale) && !player.mouseInterface)
        {
            value = TextureAssets.InventoryBack14.Value;
            color2 = Color.White;
        }
        if (!flag2)
        {
            spriteBatch.Draw(value, position, (Rectangle?)null, color2, 0f, default(Vector2), inventoryScale, (SpriteEffects)0, 0f);
        }
        int num12 = -1;
        switch (context)
        {
        case 8:
        case 23:
            if (slot == 0)
            {
                num12 = 0;
            }
            if (slot == 1)
            {
                num12 = 6;
            }
            if (slot == 2)
            {
                num12 = 12;
            }
            break;
        case 26:
            num12 = 0;
            break;
        case 9:
            if (slot == 10)
            {
                num12 = 3;
            }
            if (slot == 11)
            {
                num12 = 9;
            }
            if (slot == 12)
            {
                num12 = 15;
            }
            break;
        case 10:
        case 24:
            num12 = 11;
            break;
        case 11:
            num12 = 2;
            break;
        case 12:
        case 25:
        case 27:
        case 33:
            num12 = 1;
            break;
        case -10:
            num12 = 11;
            break;
        case -11:
            num12 = 2;
            break;
        case -12:
            num12 = 1;
            break;
        case 16:
            num12 = 4;
            break;
        case 17:
            num12 = 13;
            break;
        case 19:
            num12 = 10;
            break;
        case 18:
            num12 = 7;
            break;
        case 20:
            num12 = 17;
            break;
        }
        if ((item.type <= 0 || item.stack <= 0) && num12 != -1)
        {
            Texture2D value7 = TextureAssets.Extra[54].Value;
            Rectangle rectangle = value7.Frame(3, 6, num12 % 3, num12 / 3);
            rectangle.Width -= 2;
            rectangle.Height -= 2;
            if (context == -10 || context == -11 || context == -12)
            {
                LoaderManager.Get<AccessorySlotLoader>().DrawSlotTexture(value7, position + value.Size() / 2f * inventoryScale, rectangle, Color.White * 0.35f, 0f, rectangle.Size() / 2f, inventoryScale, (SpriteEffects)0, 0f, slot, context);
            }
            else
            {
                spriteBatch.Draw(value7, position + value.Size() / 2f * inventoryScale, (Rectangle?)rectangle, Color.White * 0.35f, 0f, rectangle.Size() / 2f, inventoryScale, (SpriteEffects)0, 0f);
            }
        }
        Vector2 vector = value.Size() * inventoryScale;
        if (item.type > 0 && item.stack > 0)
        {
            float scale = DrawItemIcon(item, context, spriteBatch, position + vector / 2f, inventoryScale, 32f, color);
            if (ItemID.Sets.TrapSigned[item.type])
            {
                spriteBatch.Draw(TextureAssets.Wire.Value, position + new Vector2(40f, 40f) * inventoryScale, (Rectangle?)new Rectangle(4, 58, 8, 8), color, 0f, new Vector2(4f), 1f, (SpriteEffects)0, 0f);
            }
            if (ItemID.Sets.DrawUnsafeIndicator[item.type])
            {
                Vector2 vector2 = new Vector2(-4f, -4f) * inventoryScale;
                Texture2D value8 = TextureAssets.Extra[258].Value;
                Rectangle rectangle2 = value8.Frame();
                spriteBatch.Draw(value8, position + vector2 + new Vector2(40f, 40f) * inventoryScale, (Rectangle?)rectangle2, color, 0f, rectangle2.Size() / 2f, 1f, (SpriteEffects)0, 0f);
            }
            if (item.type == 5324 || item.type == 5329 || item.type == 5330)
            {
                Vector2 vector3 = new Vector2(2f, -6f) * inventoryScale;
                switch (item.type)
                {
                case 5324:
                {
                    Texture2D value2 = TextureAssets.Extra[257].Value;
                    Rectangle rectangle5 = value2.Frame(3, 1, 2);
                    spriteBatch.Draw(value2, position + vector3 + new Vector2(40f, 40f) * inventoryScale, (Rectangle?)rectangle5, color, 0f, rectangle5.Size() / 2f, 1f, (SpriteEffects)0, 0f);
                    break;
                }
                case 5329:
                {
                    Texture2D value10 = TextureAssets.Extra[257].Value;
                    Rectangle rectangle4 = value10.Frame(3, 1, 1);
                    spriteBatch.Draw(value10, position + vector3 + new Vector2(40f, 40f) * inventoryScale, (Rectangle?)rectangle4, color, 0f, rectangle4.Size() / 2f, 1f, (SpriteEffects)0, 0f);
                    break;
                }
                case 5330:
                {
                    Texture2D value9 = TextureAssets.Extra[257].Value;
                    Rectangle rectangle3 = value9.Frame(3);
                    spriteBatch.Draw(value9, position + vector3 + new Vector2(40f, 40f) * inventoryScale, (Rectangle?)rectangle3, color, 0f, rectangle3.Size() / 2f, 1f, (SpriteEffects)0, 0f);
                    break;
                }
                }
            }
            if (item.stack > 1)
            {
                ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, item.stack.ToString(), position + new Vector2(10f, 26f) * inventoryScale, color, 0f, Vector2.Zero, new Vector2(inventoryScale), -1f, inventoryScale);
            }
            int num2 = -1;
            if (context == 13)
            {
                if (item.DD2Summon)
                {
                    for (int i = 0; i < 58; i++)
                    {
                        if (inv[i].type == 3822)
{
                            num2 += inv[i].stack;
                        }
                    }
                    if (num2 >= 0)
                    {
                        num2++;
                    }
                }
                if (item.useAmmo > 0)
                {
                    _ = item.useAmmo;
                    num2 = 0;
                    for (int j = 0; j < 58; j++)
                    {
                        if (inv[j].stack > 0 && ItemLoader.CanChooseAmmo(item, inv[j], player))
{
                            num2 += inv[j].stack;
                        }
                    }
                }
                if (item.fishingPole > 0)
                {
                    num2 = 0;
                    for (int k = 0; k < 58; k++)
                    {
                        if (inv[k].bait > 0)
{
                            num2 += inv[k].stack;
                        }
                    }
                }
                if (item.tileWand > 0)
                {
                    int tileWand = item.tileWand;
                    num2 = 0;
                    for (int l = 0; l < 58; l++)
                    {
                        if (inv[l].type == tileWand)
{
                            num2 += inv[l].stack;
                        }
                    }
                }
                if (item.type == 509 || item.type == 851 || item.type == 850 || item.type == 3612 || item.type == 3625 || item.type == 3611)
                {
                    num2 = 0;
                    for (int m = 0; m < 58; m++)
                    {
                        if (inv[m].type == 530)
{
                            num2 += inv[m].stack;
                        }
                    }
                }
            }
            if (num2 != -1)
            {
                ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, num2.ToString(), position + new Vector2(8f, 30f) * inventoryScale, color, 0f, Vector2.Zero, new Vector2(inventoryScale * 0.8f), -1f, inventoryScale);
            }
            if (context == 13)
            {
                string text = string.Concat(slot + 1);
                if (text == "10")
                {
                    text = "0";
                }
                ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text, position + new Vector2(8f, 4f) * inventoryScale, color, 0f, Vector2.Zero, new Vector2(inventoryScale), -1f, inventoryScale);
            }
            if (context == 13 && item.potion)
            {
                Vector2 position2 = position + value.Size() * inventoryScale / 2f - TextureAssets.Cd.Value.Size() * inventoryScale / 2f;
                Color color3 = item.GetAlpha(color) * ((float)player.potionDelay / (float)player.potionDelayTime);
                spriteBatch.Draw(TextureAssets.Cd.Value, position2, (Rectangle?)null, color3, 0f, default(Vector2), scale, (SpriteEffects)0, 0f);
            }
            if ((Math.Abs(context) == 10 || context == 18) && ((item.expertOnly && !Main.expertMode) || (item.masterOnly && !Main.masterMode)))
            {
                Vector2 position3 = position + value.Size() * inventoryScale / 2f - TextureAssets.Cd.Value.Size() * inventoryScale / 2f;
                Color white = Color.White;
                spriteBatch.Draw(TextureAssets.Cd.Value, position3, (Rectangle?)null, white, 0f, default(Vector2), scale, (SpriteEffects)0, 0f);
            }
        }
        else if (context == 6)
        {
            Texture2D value3 = TextureAssets.Trash.Value;
            Vector2 position4 = position + value.Size() * inventoryScale / 2f - value3.Size() * inventoryScale / 2f;
            spriteBatch.Draw(value3, position4, (Rectangle?)null, new Color(100, 100, 100, 100), 0f, default(Vector2), inventoryScale, (SpriteEffects)0, 0f);
        }
        if (context == 0 && slot < 10)
        {
            float num3 = inventoryScale;
            string text2 = string.Concat(slot + 1);
            if (text2 == "10")
            {
                text2 = "0";
            }
            Color baseColor = Main.inventoryBack;
            int num4 = 0;
            if (Main.player[Main.myPlayer].selectedItem == slot)
            {
                baseColor = Color.White;
                ((Color)(ref baseColor)).A = 200;
                num4 -= 2;
                num3 *= 1.4f;
            }
            ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.ItemStack.Value, text2, position + new Vector2(6f, (float)(4 + num4)) * inventoryScale, baseColor, 0f, Vector2.Zero, new Vector2(inventoryScale), -1f, inventoryScale);
        }
        if (gamepadPointForSlot != -1)
        {
            UILinkPointNavigator.SetPosition(gamepadPointForSlot, position + vector * 0.75f);
        }
    }
References Terraria.ModLoader.ItemLoader.CanChooseAmmo(), Terraria.GameContent.TextureAssets.Cd, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Item.DD2Summon, Terraria.Player.DpadRadial, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.ItemSlot.DrawGoldBGForCraftingMaterial, Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.ID.ItemID.Sets.DrawUnsafeIndicator, Terraria.Main.expertMode, Terraria.Item.expertOnly, Terraria.GameContent.TextureAssets.Extra, Terraria.Item.favorited, Terraria.Item.fishingPole, Terraria.Item.GetAlpha(), Terraria.UI.ItemSlot.GetColorByLoadout(), Terraria.Player.SelectionRadial.GetDrawMode(), Terraria.UI.ItemSlot.GetGamepadPointForSlot(), Terraria.Utils.GetLerpValue(), Terraria.UI.ItemSlot.Options.HighlightNewItems, Terraria.GameInput.PlayerInput.SettingsForUI.HighlightThingsForMouse, Terraria.Main.hslToRgb(), Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryBack, Terraria.GameContent.TextureAssets.InventoryBack10, Terraria.GameContent.TextureAssets.InventoryBack12, Terraria.GameContent.TextureAssets.InventoryBack13, Terraria.GameContent.TextureAssets.InventoryBack14, Terraria.GameContent.TextureAssets.InventoryBack15, Terraria.GameContent.TextureAssets.InventoryBack17, Terraria.GameContent.TextureAssets.InventoryBack18, Terraria.GameContent.TextureAssets.InventoryBack19, Terraria.GameContent.TextureAssets.InventoryBack2, Terraria.GameContent.TextureAssets.InventoryBack3, Terraria.GameContent.TextureAssets.InventoryBack4, Terraria.GameContent.TextureAssets.InventoryBack5, Terraria.GameContent.TextureAssets.InventoryBack6, Terraria.GameContent.TextureAssets.InventoryBack7, Terraria.GameContent.TextureAssets.InventoryBack8, Terraria.GameContent.TextureAssets.InventoryBack9, Terraria.UI.ItemSlot.inventoryGlowHue, Terraria.UI.ItemSlot.inventoryGlowHueChest, Terraria.UI.ItemSlot.inventoryGlowTime, Terraria.UI.ItemSlot.inventoryGlowTimeChest, Terraria.Main.inventoryScale, Terraria.GameContent.FontAssets.ItemStack, Terraria.Main.masterMode, Terraria.Player.mouseInterface, Terraria.Main.MouseScreen, Terraria.Main.myPlayer, Terraria.Item.newAndShiny, Terraria.Main.player, Terraria.Item.potion, Terraria.Player.potionDelay, Terraria.Player.potionDelayTime, Terraria.GameInput.PlayerInput.SettingsForUI.PreventHighlightsForGamepad, Terraria.Player.selectedItem, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Item.stack, Terraria.Item.tileWand, Terraria.ID.ItemID.Sets.TrapSigned, Terraria.GameContent.TextureAssets.Trash, Terraria.Item.type, Terraria.Item.useAmmo, Terraria.GameInput.PlayerInputProfile.UsingDpadHotbar(), Terraria.GameInput.PlayerInput.UsingGamepadUI, and Terraria.GameContent.TextureAssets.Wire.