TModLoader: Terraria.UI.ItemSlot.DyeSwap
DyeSwap()
static Item Terraria.UI.ItemSlot.DyeSwap (Item item, out bool success) inline static private
Definition at line 3074 of file ItemSlot.cs.
    {
        success = false;
        if (item.dye <= 0)
        {
            return item;
        }
        Player player = Main.player[Main.myPlayer];
        Item item2 = item;
        for (int i = 0; i < 10; i++)
        {
            if (player.dye[i].type == 0)
            {
                dyeSlotCount = i;
                break;
            }
        }
        if (dyeSlotCount >= 10)
        {
            item2 = ModSlotDyeSwap(item, out success);
            if (success)
            {
                return item2;
            }
            dyeSlotCount = 0;
        }
        if (dyeSlotCount < 0)
        {
            dyeSlotCount = 9;
        }
        item2 = player.dye[dyeSlotCount].Clone();
        player.dye[dyeSlotCount] = item.Clone();
        dyeSlotCount++;
        if (dyeSlotCount >= 10)
        {
            accSlotToSwapTo = 0;
        }
        SoundEngine.PlaySound(7);
        Recipe.FindRecipes();
        success = true;
        return item2;
    }
References Terraria.UI.ItemSlot.accSlotToSwapTo, Terraria.Item.Clone(), Terraria.Item.dye, Terraria.Player.dye, Terraria.UI.ItemSlot.dyeSlotCount, Terraria.Recipe.FindRecipes(), Terraria.UI.ItemSlot.ModSlotDyeSwap(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Item.type.
Referenced by Terraria.UI.ItemSlot.SwapEquip().