TModLoader: Terraria.UI.ItemSlot.AccCheck_ForLocalPlayer
AccCheck_ForLocalPlayer()
static bool Terraria.UI.ItemSlot.AccCheck_ForLocalPlayer (Item[] itemCollection, Item item, int slot) inline static package
Definition at line 4230 of file ItemSlot.cs.
    {
        if (isEquipLocked(item.type))
        {
            return true;
        }
        if (slot != -1)
        {
            if (itemCollection[slot].IsTheSameAs(item))
            {
                return false;
            }
            if ((itemCollection[slot].wingSlot > 0 && item.wingSlot > 0) || !ItemLoader.CanAccessoryBeEquippedWith(itemCollection[slot], item))
            {
                return !ItemLoader.CanEquipAccessory(item, slot % 20, slot >= 20);
            }
        }
        int modCount = AccessorySlotLoader.ModSlotPlayer(Main.LocalPlayer).SlotCount;
        bool targetVanity = (slot >= 20 && slot >= modCount + 20) || (slot < 20 && slot >= 10);
        for (int k = (targetVanity ? 13 : 3); k < (targetVanity ? 20 : 10); k++)
        {
            if ((!targetVanity && item.wingSlot > 0 && itemCollection[k].wingSlot > 0) || !ItemLoader.CanAccessoryBeEquippedWith(itemCollection[k], item))
            {
                return true;
            }
        }
        for (int j = (targetVanity ? modCount : 0) + 20; j < (targetVanity ? (modCount * 2) : modCount) + 20; j++)
        {
            if ((!targetVanity && item.wingSlot > 0 && itemCollection[j].wingSlot > 0) || !ItemLoader.CanAccessoryBeEquippedWith(itemCollection[j], item))
            {
                return true;
            }
        }
        for (int i = 0; i < itemCollection.Length; i++)
        {
            if (item.IsTheSameAs(itemCollection[i]))
            {
                return true;
            }
        }
        return !ItemLoader.CanEquipAccessory(item, slot % 20, slot >= 20);
    }
References Terraria.ModLoader.ItemLoader.CanAccessoryBeEquippedWith(), Terraria.ModLoader.ItemLoader.CanEquipAccessory(), Terraria.UI.ItemSlot.isEquipLocked(), Terraria.Item.IsTheSameAs(), Terraria.Main.LocalPlayer, Terraria.ModLoader.AccessorySlotLoader.ModSlotPlayer(), Terraria.Item.type, and Terraria.Item.wingSlot.
Referenced by Terraria.ModLoader.AccessorySlotLoader.ModSlotCheck(), and Terraria.UI.ItemSlot.PickItemMovementAction().