TModLoader: Terraria.GameContent.UI.States.UICharacterSelect.LoadMigratablePlayers
LoadMigratablePlayers()
void Terraria.GameContent.UI.States.UICharacterSelect.LoadMigratablePlayers () inline private
Definition at line 378 of file UICharacterSelect.cs.
    {
        _migrationPanel = new UIExpandablePanel();
        UIText playerMigrationPanelTitle = new UIText(Language.GetTextValue("tModLoader.MigrateIndividualPlayersHeader"));
        playerMigrationPanelTitle.Top.Set(4f, 0f);
        _migrationPanel.Append(playerMigrationPanelTitle);
        NestedUIList migratePlayerList = new NestedUIList();
        migratePlayerList.Width.Set(-22f, 1f);
        migratePlayerList.Left.Set(0f, 0f);
        migratePlayerList.Top.Set(30f, 0f);
        migratePlayerList.MinHeight.Set(300f, 0f);
        migratePlayerList.ListPadding = 5f;
        _migrationPanel.VisibleWhenExpanded.Add(migratePlayerList);
        UIScrollbar scrollbar = new UIScrollbar();
        scrollbar.SetView(100f, 1000f);
        scrollbar.Height.Set(-42f, 1f);
        scrollbar.Top.Set(36f, 0f);
        scrollbar.Left.Pixels -= 0f;
        scrollbar.HAlign = 1f;
        migratePlayerList.SetScrollbar(scrollbar);
        _migrationPanel.VisibleWhenExpanded.Add(scrollbar);
        (string, string, int)[] otherPaths = FileUtilities.GetAlternateSavePathFiles("Players");
        int currentStabilityLevel = BuildInfo.Purpose switch
        {
            BuildInfo.BuildPurpose.Stable => 1,
            BuildInfo.BuildPurpose.Preview => 2,
            _ => 3,
        };
        (string, string, int)[] array = otherPaths;
        for (int j = 0; j < array.Length; j++)
        {
            var (otherSaveFolderPath, message, stabilityLevel) = array[j];
            if (stabilityLevel == currentStabilityLevel || !Directory.Exists(otherSaveFolderPath))
            {
                continue;
            }
            string[] files = Directory.GetFiles(otherSaveFolderPath, "*.plr");
            int num2 = Math.Min(1000, files.Length);
            for (int i = 0; i < num2; i++)
            {
                string playerInThisPlayersPath = Path.Combine(Main.PlayerPath, Path.GetFileName(files[i]));
                if (File.Exists(playerInThisPlayersPath) && File.GetLastWriteTime(playerInThisPlayersPath) == File.GetLastWriteTime(files[i]))
                {
                    continue;
                }
                PlayerFileData fileData = Player.GetFileData(files[i], cloudSave: false);
                if (fileData == null)
                {
                    continue;
                }
                UIPanel migrateIndividualPlayerPanel = new UIPanel();
                migrateIndividualPlayerPanel.Width.Set(0f, 1f);
                migrateIndividualPlayerPanel.Height.Set(50f, 0f);
                float left = 0f;
                if (stabilityLevel > currentStabilityLevel)
                {
                    UIHoverImage warningImage2 = new UIHoverImage(UICommon.ButtonErrorTexture, Language.GetTextValue("tModLoader.PlayerFromNewerTModMightNotWork"))
                    {
                        Left =
{
                            Pixels = left
                        },
                        Top =
{
                            Pixels = 3f
                        }
                    };
                    migrateIndividualPlayerPanel.Append(warningImage2);
                    left += warningImage2.Width.Pixels + 6f;
                }
                PlayerFileData playerWithSameName = Main.PlayerList.FirstOrDefault((PlayerFileData x) => x.Name == fileData.Name);
                if (playerWithSameName != null)
                {
                    UIHoverImage warningImage = new UIHoverImage(UICommon.ButtonExclamationTexture, Language.GetTextValue("tModLoader.PlayerWithThisNameExistsWillBeOverwritten"))
                    {
                        Left =
{
                            Pixels = left
                        },
                        Top =
{
                            Pixels = 3f
                        }
                    };
                    migrateIndividualPlayerPanel.Append(warningImage);
                    left += warningImage.Width.Pixels + 6f;
                    if (File.GetLastWriteTime(playerWithSameName.Path) > File.GetLastWriteTime(files[i]))
                    {
                        warningImage = new UIHoverImage(UICommon.ButtonExclamationTexture, Language.GetTextValue("tModLoader.ExistingPlayerPlayedMoreRecently"))
{
                            Left =
{
                                Pixels = left
                            },
                            Top =
{
                                Pixels = 3f
                            }
                        };
                        migrateIndividualPlayerPanel.Append(warningImage);
                        left += warningImage.Width.Pixels + 6f;
                    }
                }
                UIText migrateIndividualPlayerText = new UIText(string.Format(message, fileData.Name));
                migrateIndividualPlayerText.Width.Set(0f - left, 1f);
                migrateIndividualPlayerText.Left.Set(left, 0f);
                migrateIndividualPlayerText.Height.Set(0f, 1f);
                migrateIndividualPlayerText.OnLeftClick += delegate
                {
                    if (!_currentlyMigratingFiles)
                    {
                        _currentlyMigratingFiles = true;
                        migrateIndividualPlayerText.SetText(Language.GetText("tModLoader.MigratingWorldsText"));
                        Task.Factory.StartNew(delegate
{
                            ExecuteIndividualPlayerMigration(fileData, otherSaveFolderPath);
                        }, TaskCreationOptions.PreferFairness);
                    }
                };
                migrateIndividualPlayerPanel.Append(migrateIndividualPlayerText);
                migratePlayerList.Add(migrateIndividualPlayerPanel);
            }
        }
    }
References Terraria.GameContent.UI.States.UICharacterSelect._currentlyMigratingFiles, Terraria.GameContent.UI.States.UICharacterSelect._migrationPanel, Terraria.ModLoader.UI.UICommon.ButtonErrorTexture, Terraria.ModLoader.UI.UICommon.ButtonExclamationTexture, Terraria.GameContent.UI.States.UICharacterSelect.ExecuteIndividualPlayerMigration(), Terraria.Utilities.FileUtilities.GetAlternateSavePathFiles(), Terraria.Player.GetFileData(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Left, Terraria.IO.FileData.Name, Terraria.Main.PlayerList, Terraria.Main.PlayerPath, and Terraria.UI.UIElement.Top.
Referenced by Terraria.GameContent.UI.States.UICharacterSelect.OnActivate().