TModLoader: Terraria.GameContent.UI.States.UICharacterSelect.ExecuteIndividualPlayerMigration
ExecuteIndividualPlayerMigration()
static void Terraria.GameContent.UI.States.UICharacterSelect.ExecuteIndividualPlayerMigration (PlayerFileData fileData, string otherSaveFolderPath) inline static private
Definition at line 503 of file UICharacterSelect.cs.
    {
        try
        {
            string playerFileName = Path.GetFileNameWithoutExtension(fileData.Path);
            foreach (string item in from s in Directory.GetFiles(Main.PlayerPath, playerFileName + ".*")
                where s.EndsWith(".plr") || s.EndsWith(".tplr") || s.EndsWith(".bak")
                select s)
            {
                File.Delete(item);
            }
            string existingPlayerMapPath = Path.Combine(Main.PlayerPath, Path.GetFileNameWithoutExtension(fileData.Path));
            if (Directory.Exists(existingPlayerMapPath))
            {
                Directory.Delete(existingPlayerMapPath, recursive: true);
            }
            foreach (string otherPlayerFile in from s in Directory.GetFiles(otherSaveFolderPath, playerFileName + ".*")
                where s.EndsWith(".plr") || s.EndsWith(".tplr") || s.EndsWith(".bak")
                select s)
            {
                File.Copy(otherPlayerFile, Path.Combine(Main.PlayerPath, Path.GetFileName(otherPlayerFile)), overwrite: true);
            }
            string playerMapPath = Path.Combine(otherSaveFolderPath, Path.GetFileNameWithoutExtension(fileData.Path));
            if (Directory.Exists(playerMapPath))
            {
                FileUtilities.CopyFolder(playerMapPath, existingPlayerMapPath);
            }
        }
        catch (Exception e)
        {
            Logging.tML.Error((object)Language.GetText("tModLoader.MigratePlayersException"), e);
        }
        _currentlyMigratingFiles = false;
        Main.menuMode = 1;
    }
References Terraria.GameContent.UI.States.UICharacterSelect._currentlyMigratingFiles, Terraria.Utilities.FileUtilities.CopyFolder(), Terraria.Localization.Language.GetText(), Terraria.Main.PlayerPath, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.GameContent.UI.States.UICharacterSelect.LoadMigratablePlayers().