TModLoader: Terraria.GameContent.UI.States.UICharacterSelect.AddAutomaticPlayerMigrationButtons
AddAutomaticPlayerMigrationButtons()
void Terraria.GameContent.UI.States.UICharacterSelect.AddAutomaticPlayerMigrationButtons () inline private
    {
        string vanillaPlayersPath = Path.Combine(Platform.Get<IPathService>().GetStoragePath("Terraria"), "Players");
        if (!Directory.Exists(vanillaPlayersPath) || !Directory.GetFiles(vanillaPlayersPath, "*.plr").Any())
        {
            return;
        }
        UIPanel autoMigrateButton = new UIPanel();
        autoMigrateButton.Width.Set(0f, 1f);
        autoMigrateButton.Height.Set(50f, 0f);
        UIText migrateText = new UIText((!_currentlyMigratingFiles) ? Language.GetText("tModLoader.MigratePlayersText") : Language.GetText("tModLoader.MigratingWorldsText"));
        autoMigrateButton.OnLeftClick += delegate
        {
            if (!_currentlyMigratingFiles)
            {
                _currentlyMigratingFiles = true;
                migrateText.SetText(Language.GetText("tModLoader.MigratingWorldsText"));
                Task.Factory.StartNew(delegate
                {
                    ExecuteAutomaticPlayerMigration(vanillaPlayersPath);
                }, TaskCreationOptions.PreferFairness);
            }
        };
        autoMigrateButton.Append(migrateText);
        _playerList.Add(autoMigrateButton);
        UIText noPlayersMessage = new UIText(Language.GetTextValue("tModLoader.MigratePlayersMessage", Program.SaveFolderName));
        noPlayersMessage.Width.Set(0f, 1f);
        noPlayersMessage.Height.Set(300f, 0f);
        noPlayersMessage.MarginTop = 20f;
        noPlayersMessage.OnLeftClick += delegate
        {
            Utils.OpenFolder(Main.PlayerPath);
            Utils.OpenFolder(vanillaPlayersPath);
        };
        _playerList.Add(noPlayersMessage);
    }
References Terraria.GameContent.UI.States.UICharacterSelect._currentlyMigratingFiles, Terraria.GameContent.UI.States.UICharacterSelect._playerList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.States.UICharacterSelect.ExecuteAutomaticPlayerMigration(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.Utils.OpenFolder(), Terraria.Main.PlayerPath, and Terraria.Program.SaveFolderName.
Referenced by Terraria.GameContent.UI.States.UICharacterSelect.UpdatePlayersList().