TModLoader: Terraria.Social.Steam.NetServerSocialModule.OnPacketRead
OnPacketRead()
bool Terraria.Social.Steam.NetServerSocialModule.OnPacketRead (byte[] data, int length, CSteamID userId) inline private
    {
        //IL_0006: Unknown result type (might be due to invalid IL or missing references)
        //IL_001e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0039: Unknown result type (might be due to invalid IL or missing references)
        //IL_0014: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_009d: Unknown result type (might be due to invalid IL or missing references)
        //IL_009e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c2: Expected I4, but got Unknown
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e3: Unknown result type (might be due to invalid IL or missing references)
        if (!_connectionStateMap.ContainsKey(userId) || _connectionStateMap[userId] == ConnectionState.Inactive)
        {
            P2PSessionRequest_t result = default(P2PSessionRequest_t);
            result.m_steamIDRemote = userId;
            OnP2PSessionRequest(result);
            if (!_connectionStateMap.ContainsKey(userId) || _connectionStateMap[userId] == ConnectionState.Inactive)
            {
                return false;
            }
        }
        ConnectionState connectionState = _connectionStateMap[userId];
        if (connectionState == ConnectionState.Authenticating)
        {
            if (length < 3)
            {
                return false;
            }
            if (((data[1] << 8) | data[0]) != length)
            {
                return false;
            }
            if (data[2] != 93)
            {
                return false;
            }
            byte[] array = new byte[data.Length - 3];
            Array.Copy(data, 3, array, 0, array.Length);
            EBeginAuthSessionResult val = SteamUser.BeginAuthSession(array, array.Length, userId);
            switch ((int)val)
            {
            case 0:
                _connectionStateMap[userId] = ConnectionState.Connected;
                BroadcastConnectedUsers();
                break;
            case 2:
                Close(userId);
                break;
            case 5:
                Close(userId);
                break;
            case 4:
                Close(userId);
                break;
            case 1:
                Close(userId);
                break;
            case 3:
                Close(userId);
                break;
            }
            return false;
        }
        return connectionState == ConnectionState.Connected;
    }
References Terraria.Social.Steam.NetSocialModule._connectionStateMap, Terraria.Social.Steam.NetServerSocialModule.BroadcastConnectedUsers(), Terraria.Social.Steam.NetServerSocialModule.Close(), and Terraria.Social.Steam.NetServerSocialModule.OnP2PSessionRequest().
Referenced by Terraria.Social.Steam.NetServerSocialModule.Initialize().