TModLoader: Terraria.Graphics.TileBatch.InternalDraw
InternalDraw()
void Terraria.Graphics.TileBatch.InternalDraw (Texture2D texture, Vector4 destinationRectangle, Rectangle? sourceRectangle, VertexColors colors, float rotation, Vector2 origin, SpriteEffects effect, float depth) inline package
Definition at line 227 of file TileBatch.cs.
    {
        //IL_0002: Unknown result type (might be due to invalid IL or missing references)
        //IL_0015: Unknown result type (might be due to invalid IL or missing references)
        //IL_0029: Unknown result type (might be due to invalid IL or missing references)
        //IL_003d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0051: Unknown result type (might be due to invalid IL or missing references)
        //IL_0099: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_012e: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_015a: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_015c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0131: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        Vector4 sourceRectangle2 = default(Vector4);
        if (sourceRectangle.HasValue)
        {
            sourceRectangle2.X = sourceRectangle.Value.X;
            sourceRectangle2.Y = sourceRectangle.Value.Y;
            sourceRectangle2.Z = sourceRectangle.Value.Width;
            sourceRectangle2.W = sourceRectangle.Value.Height;
        }
        else
        {
            sourceRectangle2.X = 0f;
            sourceRectangle2.Y = 0f;
            sourceRectangle2.Z = texture.Width;
            sourceRectangle2.W = texture.Height;
        }
        Vector2 texCoordTL = default(Vector2);
        texCoordTL.X = sourceRectangle2.X / (float)texture.Width;
        texCoordTL.Y = sourceRectangle2.Y / (float)texture.Height;
        Vector2 texCoordBR = default(Vector2);
        texCoordBR.X = (sourceRectangle2.X + sourceRectangle2.Z) / (float)texture.Width;
        texCoordBR.Y = (sourceRectangle2.Y + sourceRectangle2.W) / (float)texture.Height;
        if ((effect & 2) != 0)
        {
            float y = texCoordBR.Y;
            texCoordBR.Y = texCoordTL.Y;
            texCoordTL.Y = y;
        }
        if ((effect & 1) != 0)
        {
            float x = texCoordBR.X;
            texCoordBR.X = texCoordTL.X;
            texCoordTL.X = x;
        }
        QueueSprite(destinationRectangle, -origin, colors, sourceRectangle2, texCoordTL, texCoordBR, texture, depth, rotation);
    }
References Terraria.Graphics.TileBatch.QueueSprite().
Referenced by Terraria.Graphics.TileBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), Terraria.Graphics.TileBatch.Draw(), and Terraria.Graphics.TileBatch.Draw().