TModLoader: Terraria.Graphics.TileBatch.SortedDrawBatch
SortedDrawBatch()
void Terraria.Graphics.TileBatch.SortedDrawBatch () inline private
Definition at line 340 of file TileBatch.cs.
    {
        if (_lastBatchDrawGroupIndex == 0 && _batchDrawGroups[_lastBatchDrawGroupIndex].SpriteCount == 0)
        {
            return;
        }
        FlushRemainingBatch();
        VertexBuffer vertexBuffer = ((VertexBufferBinding)(ref _graphicsDevice.GetVertexBuffers()[0])).VertexBuffer;
        _graphicsDevice.Indices = (IndexBuffer)(object)_sortedIndexBuffer;
        for (int i = 0; i <= _lastBatchDrawGroupIndex; i++)
        {
            BatchDrawGroup batchDrawGroup = _batchDrawGroups[i];
            int vertexCount = batchDrawGroup.VertexCount;
            vertexBuffer.SetData<VertexPositionColorTexture>(_batchDrawGroups[i].VertexArray, 0, vertexCount, (SetDataOptions)0);
            SortAndApplyIndexData(batchDrawGroup);
            int num = 0;
            for (int j = 0; j < batchDrawGroup.BatchDrawCount; j++)
            {
                BatchDrawInfo batchDrawInfo = batchDrawGroup.BatchDraws[j];
                _graphicsDevice.Textures[0] = (Texture)(object)batchDrawInfo.Texture;
                int num2 = batchDrawInfo.Count;
                for (; j + 1 < batchDrawGroup.BatchDrawCount && batchDrawInfo.Texture == batchDrawGroup.BatchDraws[j + 1].Texture; j++)
                {
                    num2 += batchDrawGroup.BatchDraws[j + 1].Count;
                }
                _graphicsDevice.DrawIndexedPrimitives((PrimitiveType)0, 0, 0, num2 * 4, num, num2 * 2);
                num += num2 * 6;
            }
            batchDrawGroup.Reset();
        }
        _currentBatchDrawInfo = BatchDrawInfo.Empty;
        _lastBatchDrawGroupIndex = 0;
    }
References Terraria.Graphics.TileBatch._batchDrawGroups, Terraria.Graphics.TileBatch._currentBatchDrawInfo, Terraria.Graphics.TileBatch._graphicsDevice, Terraria.Graphics.TileBatch._lastBatchDrawGroupIndex, Terraria.Graphics.TileBatch._sortedIndexBuffer, Terraria.Graphics.TileBatch.BatchDrawInfo.Empty, Terraria.Graphics.TileBatch.FlushRemainingBatch(), and Terraria.Graphics.TileBatch.SortAndApplyIndexData().
Referenced by Terraria.Graphics.TileBatch.End().