TModLoader: Terraria.Graphics.Capture.CaptureCamera.DrawTick
DrawTick()
void Terraria.Graphics.Capture.CaptureCamera.DrawTick () inline
Definition at line 201 of file CaptureCamera.cs.
    {
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0063: Unknown result type (might be due to invalid IL or missing references)
        //IL_006c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0071: Unknown result type (might be due to invalid IL or missing references)
        //IL_007a: Unknown result type (might be due to invalid IL or missing references)
        //IL_007f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_016b: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_022f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f3: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ff: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        Monitor.Enter(_captureLock);
        if (_activeSettings == null)
        {
            return;
        }
        bool notRetro = Lighting.NotRetro;
        if (_renderQueue.Count > 0)
        {
            CaptureChunk captureChunk = _renderQueue.Dequeue();
            _graphics.SetRenderTarget((RenderTarget2D)null);
            _graphics.Clear(Color.Transparent);
            TileDrawing tilesRenderer = Main.instance.TilesRenderer;
            Rectangle area = captureChunk.Area;
            int left = ((Rectangle)(ref area)).Left;
            area = captureChunk.Area;
            int right = ((Rectangle)(ref area)).Right;
            area = captureChunk.Area;
            int top = ((Rectangle)(ref area)).Top;
            area = captureChunk.Area;
            tilesRenderer.PrepareForAreaDrawing(left, right, top, ((Rectangle)(ref area)).Bottom, prepareLazily: false);
            Main.instance.TilePaintSystem.PrepareAllRequests();
            _graphics.SetRenderTarget(_frameBuffer);
            _graphics.Clear(Color.Transparent);
            if (notRetro)
            {
                Color clearColor = (_activeSettings.CaptureBackground ? Color.Black : Color.Transparent);
                Filters.Scene.BeginCapture(_filterFrameBuffer1, clearColor);
                Main.instance.DrawCapture(captureChunk.Area, _activeSettings);
                Filters.Scene.EndCapture(_frameBuffer, _filterFrameBuffer1, _filterFrameBuffer2, clearColor);
            }
            else
            {
                Main.instance.DrawCapture(captureChunk.Area, _activeSettings);
            }
            if (_activeSettings.UseScaling)
            {
                _graphics.SetRenderTarget(_scaledFrameBuffer);
                _graphics.Clear(Color.Transparent);
                _spriteBatch.Begin((SpriteSortMode)0, BlendState.AlphaBlend, _downscaleSampleState, DepthStencilState.Default, RasterizerState.CullNone);
                _spriteBatch.Draw((Texture2D)(object)_frameBuffer, new Rectangle(0, 0, ((Texture2D)_scaledFrameBuffer).Width, ((Texture2D)_scaledFrameBuffer).Height), Color.White);
                _spriteBatch.End();
                _graphics.SetRenderTarget((RenderTarget2D)null);
                ((Texture2D)_scaledFrameBuffer).GetData<byte>(_scaledFrameData, 0, ((Texture2D)_scaledFrameBuffer).Width * ((Texture2D)_scaledFrameBuffer).Height * 4);
                DrawBytesToBuffer(_scaledFrameData, _outputData, ((Texture2D)_scaledFrameBuffer).Width, _outputImageSize.Width, captureChunk.ScaledArea);
            }
            else
            {
                _graphics.SetRenderTarget((RenderTarget2D)null);
                SaveImage((Texture2D)(object)_frameBuffer, captureChunk.ScaledArea.Width, captureChunk.ScaledArea.Height, ImageFormat.Png, _activeSettings.OutputName, captureChunk.Area.X + "-" + captureChunk.Area.Y + ".png");
            }
            _tilesProcessed += captureChunk.Area.Width * captureChunk.Area.Height;
        }
        if (_renderQueue.Count == 0)
        {
            FinishCapture();
        }
        Monitor.Exit(_captureLock);
    }
References Terraria.Graphics.Capture.CaptureCamera._activeSettings, Terraria.Graphics.Capture.CaptureCamera._captureLock, Terraria.Graphics.Capture.CaptureCamera._downscaleSampleState, Terraria.Graphics.Capture.CaptureCamera._filterFrameBuffer1, Terraria.Graphics.Capture.CaptureCamera._filterFrameBuffer2, Terraria.Graphics.Capture.CaptureCamera._frameBuffer, Terraria.Graphics.Capture.CaptureCamera._graphics, Terraria.Graphics.Capture.CaptureCamera._outputData, Terraria.Graphics.Capture.CaptureCamera._outputImageSize, Terraria.Graphics.Capture.CaptureCamera._renderQueue, Terraria.Graphics.Capture.CaptureCamera._scaledFrameBuffer, Terraria.Graphics.Capture.CaptureCamera._scaledFrameData, Terraria.Graphics.Capture.CaptureCamera._spriteBatch, Terraria.Graphics.Capture.CaptureCamera._tilesProcessed, Terraria.Graphics.Capture.CaptureCamera.DrawBytesToBuffer(), Terraria.Graphics.Capture.CaptureCamera.FinishCapture(), Terraria.Main.instance, Terraria.Lighting.NotRetro, Terraria.Graphics.Capture.CaptureSettings.OutputName, Terraria.Graphics.Capture.CaptureCamera.SaveImage(), Terraria.Graphics.Effects.Filters.Scene, and Terraria.Graphics.Capture.CaptureSettings.UseScaling.
Referenced by Terraria.Graphics.Capture.CaptureManager.DrawTick().