TModLoader: Terraria.IO.WorldFile.InternalSaveWorld
InternalSaveWorld()
static void Terraria.IO.WorldFile.InternalSaveWorld (bool useCloudSaving, bool resetTime) inline static private
Definition at line 829 of file WorldFile.cs.
    {
        Utils.TryCreatingDirectory(Main.WorldPath);
        if (Main.skipMenu)
        {
            return;
        }
        if (_hasCache)
        {
            SetTempToCache();
        }
        else
        {
            SetTempToOngoing();
        }
        if (resetTime)
        {
            ResetTempsToDayTime();
        }
        if (Main.worldPathName == null)
        {
            return;
        }
        if (!BackupIO.archiveLock)
        {
            BackupIO.World.ArchiveWorld(Main.worldPathName, useCloudSaving);
        }
        new Stopwatch().Start();
        int num;
        byte[] array;
        using (MemoryStream memoryStream = new MemoryStream(7000000))
        {
            using (BinaryWriter writer = new BinaryWriter(memoryStream))
            {
                SaveWorld_Version2(writer);
            }
            array = memoryStream.ToArray();
            num = array.Length;
        }
        byte[] array2 = null;
        if (FileUtilities.Exists(Main.worldPathName, useCloudSaving))
        {
            array2 = FileUtilities.ReadAllBytes(Main.worldPathName, useCloudSaving);
        }
        FileUtilities.Write(Main.worldPathName, array, num, useCloudSaving);
        array = FileUtilities.ReadAllBytes(Main.worldPathName, useCloudSaving);
        string text = null;
        bool validated = true;
        using (MemoryStream input = new MemoryStream(array, 0, num, writable: false))
        {
            using BinaryReader fileIO = new BinaryReader(input);
            if (!Main.validateSaves || ValidateWorld(fileIO))
            {
                if (array2 != null)
                {
                    text = Main.worldPathName + ".bak";
                    Main.statusText = Lang.gen[50].Value;
                }
                DoRollingBackups(text);
            }
            else
            {
                Logging.Terraria.Error((object)"ValidateWorld failed. A bug in WorldFile.Save has produced an invalid file. Step through with a debugger to find out where ValidateWorld returns false.");
                validated = false;
                text = Main.worldPathName;
            }
        }
        if (text != null && array2 != null)
        {
            FileUtilities.WriteAllBytes(text, array2, useCloudSaving);
        }
        if (validated)
        {
            WorldIO.Save(Main.worldPathName, useCloudSaving);
        }
    }
References Terraria.IO.WorldFile._hasCache, Terraria.ModLoader.BackupIO.archiveLock, Terraria.ModLoader.BackupIO.World.ArchiveWorld(), Terraria.IO.WorldFile.DoRollingBackups(), Terraria.Utilities.FileUtilities.Exists(), Terraria.Lang.gen, Terraria.Utilities.FileUtilities.ReadAllBytes(), Terraria.IO.WorldFile.ResetTempsToDayTime(), Terraria.ModLoader.IO.WorldIO.Save(), Terraria.IO.WorldFile.SaveWorld_Version2(), Terraria.IO.WorldFile.SetTempToCache(), Terraria.IO.WorldFile.SetTempToOngoing(), Terraria.Main.skipMenu, Terraria.ModLoader.Logging.Terraria, Terraria.Utils.TryCreatingDirectory(), Terraria.Main.validateSaves, Terraria.IO.WorldFile.ValidateWorld(), Terraria.Localization.LocalizedText.Value, Terraria.Main.WorldPath, Terraria.Main.worldPathName, Terraria.Utilities.FileUtilities.Write(), and Terraria.Utilities.FileUtilities.WriteAllBytes().
Referenced by Terraria.IO.WorldFile.SaveWorld().