TModLoader: Terraria.IO.WorldFile.LoadWorld
LoadWorld()
static void Terraria.IO.WorldFile.LoadWorld (bool loadFromCloud) inline static
Definition at line 579 of file WorldFile.cs.
    {
        Main.lockMenuBGChange = true;
        _isWorldOnCloud = loadFromCloud;
        Main.checkXMas();
        Main.checkHalloween();
        bool flag = loadFromCloud && SocialAPI.Cloud != null;
        if (!FileUtilities.Exists(Main.worldPathName, flag) && Main.autoGen)
        {
            if (!flag)
            {
                for (int num = Main.worldPathName.Length - 1; num >= 0; num--)
                {
                    if (Main.worldPathName.Substring(num, 1) == (Path.DirectorySeparatorChar.ToString() ?? ""))
                    {
                        Utils.TryCreatingDirectory(Main.worldPathName.Substring(0, num));
                        break;
                    }
                }
            }
            WorldGen.clearWorld();
            Main.ActiveWorldFileData = CreateMetadata((Main.worldName == "") ? "World" : Main.worldName, flag, Main.GameMode);
            string text = (Main.AutogenSeedName ?? "").Trim();
            if (text.Length == 0)
            {
                Main.ActiveWorldFileData.SetSeedToRandom();
            }
            else
            {
                Main.ActiveWorldFileData.SetSeed(text);
            }
            UIWorldCreation.ProcessSpecialWorldSeeds(text);
            WorldGen.GenerateWorld(Main.ActiveWorldFileData.Seed, Main.AutogenProgress);
            SaveWorld();
        }
        try
        {
            using MemoryStream memoryStream = new MemoryStream(FileUtilities.ReadAllBytes(Main.worldPathName, flag));
            using BinaryReader binaryReader = new BinaryReader(memoryStream);
            try
            {
                WorldGen.loadFailed = false;
                WorldGen.loadSuccess = false;
                int num2 = (_versionNumber = binaryReader.ReadInt32());
                if (_versionNumber <= 0 || _versionNumber > 279)
                {
                    WorldGen.loadFailed = true;
                    return;
                }
                int num3 = ((num2 > 87) ? LoadWorld_Version2(binaryReader) : LoadWorld_Version1_Old_BeforeRelease88(binaryReader));
                if (num2 < 141)
                {
                    if (!loadFromCloud)
                    {
                        Main.ActiveWorldFileData.CreationTime = File.GetCreationTime(Main.worldPathName);
                    }
                    else
                    {
                        Main.ActiveWorldFileData.CreationTime = DateTime.Now;
                    }
                }
                CheckSavedOreTiers();
                binaryReader.Close();
                memoryStream.Close();
                SystemLoader.OnWorldLoad();
                WorldIO.Load(Main.worldPathName, flag);
                if (num3 != 0)
                {
                    WorldGen.loadFailed = true;
                }
                else
                {
                    WorldGen.loadSuccess = true;
                }
                if (WorldGen.loadFailed || !WorldGen.loadSuccess)
                {
                    return;
                }
                ConvertOldTileEntities();
                ClearTempTiles();
                WorldGen.gen = true;
                GenVars.waterLine = Main.maxTilesY;
                Liquid.QuickWater(2);
                WorldGen.WaterCheck();
                int num4 = 0;
                Liquid.quickSettle = true;
                int num5 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                float num6 = 0f;
                while (Liquid.numLiquid > 0 && num4 < 100000)
                {
                    num4++;
                    float num7 = (float)(num5 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (float)num5;
                    if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num5)
                    {
                        num5 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                    }
                    if (num7 > num6)
                    {
                        num6 = num7;
                    }
                    else
                    {
                        num7 = num6;
                    }
                    Main.statusText = Lang.gen[27].Value + " " + (int)(num7 * 100f / 2f + 50f) + "%";
                    Liquid.UpdateLiquid();
                }
                Liquid.quickSettle = false;
                Main.weatherCounter = WorldGen.genRand.Next(3600, 18000);
                Cloud.resetClouds();
                WorldGen.WaterCheck();
                WorldGen.gen = false;
                NPC.setFireFlyChance();
                if (Main.slimeRainTime > 0.0)
                {
                    Main.StartSlimeRain(announce: false);
                }
                NPC.SetWorldSpecificMonstersByWorldID();
            }
            catch (Exception lastThrownLoadException)
            {
                LastThrownLoadException = lastThrownLoadException;
                WorldGen.loadFailed = true;
                WorldGen.loadSuccess = false;
                try
                {
                    binaryReader.Close();
                    memoryStream.Close();
                    return;
                }
                catch
                {
                    return;
                }
            }
        }
        catch (Exception lastThrownLoadException2)
        {
            LastThrownLoadException = lastThrownLoadException2;
            WorldGen.loadFailed = true;
            WorldGen.loadSuccess = false;
            return;
        }
        if (WorldFile.OnWorldLoad != null)
        {
            WorldFile.OnWorldLoad();
        }
    }
References Terraria.IO.WorldFile._isWorldOnCloud, Terraria.IO.WorldFile._versionNumber, Terraria.Main.ActiveWorldFileData, Terraria.Main.autoGen, Terraria.Main.AutogenProgress, Terraria.Main.checkHalloween(), Terraria.IO.WorldFile.CheckSavedOreTiers(), Terraria.Main.checkXMas(), Terraria.IO.WorldFile.ClearTempTiles(), Terraria.WorldGen.clearWorld(), Terraria.IO.WorldFile.ConvertOldTileEntities(), Terraria.IO.WorldFile.CreateMetadata(), Terraria.Utilities.FileUtilities.Exists(), Terraria.Main.GameMode, Terraria.Lang.gen, Terraria.WorldGen.GenerateWorld(), Terraria.WorldGen.genRand, Terraria.IO.WorldFile.LastThrownLoadException, Terraria.ModLoader.IO.WorldIO.Load(), Terraria.WorldGen.loadFailed, Terraria.WorldGen.loadSuccess, Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorld_Version2(), Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Liquid.numLiquid, Terraria.LiquidBuffer.numLiquidBuffer, Terraria.IO.WorldFile.OnWorldLoad, Terraria.ModLoader.SystemLoader.OnWorldLoad(), Terraria.GameContent.UI.States.UIWorldCreation.ProcessSpecialWorldSeeds(), Terraria.Liquid.QuickWater(), Terraria.Utilities.FileUtilities.ReadAllBytes(), Terraria.Cloud.resetClouds(), Terraria.IO.WorldFile.SaveWorld(), Terraria.NPC.setFireFlyChance(), Terraria.NPC.SetWorldSpecificMonstersByWorldID(), Terraria.Main.slimeRainTime, Terraria.Main.StartSlimeRain(), Terraria.Utils.TryCreatingDirectory(), Terraria.Liquid.UpdateLiquid(), Terraria.Localization.LocalizedText.Value, Terraria.WorldGen.WaterCheck(), Terraria.Main.worldName, and Terraria.Main.worldPathName.
Referenced by Terraria.WorldGen.playWorldCallBack(), Terraria.WorldGen.RenameWorldCallBack(), and Terraria.WorldGen.serverLoadWorldCallBack().