TModLoader: Terraria.Initializers.LaunchInitializer.LoadClientParameters
LoadClientParameters()
static void Terraria.Initializers.LaunchInitializer.LoadClientParameters (Main game) inline static private
    {
        string iP;
        if ((iP = TryParameter("-j", "-join")) != null)
        {
            game.AutoJoin(iP, TryParameter("-plr", "-player"));
        }
        string arg;
        if ((arg = TryParameter("-pass", "-password")) != null)
        {
            Netplay.ServerPassword = Main.ConvertFromSafeArgument(arg);
            game.AutoPass();
        }
        if (HasParameter("-host"))
        {
            game.AutoHost();
        }
        if (!HasParameter("-skipselect"))
        {
            return;
        }
        string playerName = null;
        string worldName = null;
        string skipSelectArgs = TryParameter("-skipselect");
        if (skipSelectArgs != null)
        {
            Match i = new Regex("(?<name>.*?):(?<val>.*)").Match(skipSelectArgs);
            if (i.Success)
            {
                playerName = i.Groups["name"].Value;
                worldName = i.Groups["val"].Value;
            }
        }
        Terraria.ModLoader.ModLoader.OnSuccessfulLoad = (Action)Delegate.Combine(Terraria.ModLoader.ModLoader.OnSuccessfulLoad, (Action)delegate
        {
            WorldGen.clearWorld();
            Main.LoadPlayers();
            (Main.PlayerList.FirstOrDefault((PlayerFileData x) => x.Name == playerName) ?? Main.PlayerList[0]).SetAsActive();
            Main.LoadWorlds();
            (Main.WorldList.FirstOrDefault((WorldFileData x) => x.Name == worldName) ?? Main.WorldList[0]).SetAsActive();
            if (!UIWorldSelect.CanWorldBePlayed(Main.ActiveWorldFileData))
            {
                throw new Exception($"The selected character {playerName} can not be used with the selected world {worldName}.\n" + "This could be due to mismatched Journey Mode or other mod specific changes.Check in Game Menus for more information.");
            }
            WorldGen.playWorld();
        });
    }
References Terraria.Main.ActiveWorldFileData, Terraria.GameContent.UI.States.UIWorldSelect.CanWorldBePlayed(), Terraria.WorldGen.clearWorld(), Terraria.Main.ConvertFromSafeArgument(), Terraria.Initializers.LaunchInitializer.HasParameter(), Terraria.Main.LoadPlayers(), Terraria.Main.LoadWorlds(), Terraria.IO.FileData.Name, Terraria.ModLoader.ModLoader.OnSuccessfulLoad, Terraria.Main.PlayerList, Terraria.WorldGen.playWorld(), Terraria.Initializers.LaunchInitializer.TryParameter(), and Terraria.Main.WorldList.
Referenced by Terraria.Initializers.LaunchInitializer.LoadParameters().