TModLoader: Terraria.ModLoader.PrefixLoader.Roll
Roll()
static bool Terraria.ModLoader.PrefixLoader.Roll (Item item, UnifiedRandom unifiedRandom, out int prefix, bool justCheck) inline static
Definition at line 140 of file PrefixLoader.cs.
    {
        int forcedPrefix = ItemLoader.ChoosePrefix(item, unifiedRandom);
        if (forcedPrefix > 0 && CanRoll(item, forcedPrefix))
        {
            prefix = forcedPrefix;
            return true;
        }
        prefix = 0;
        WeightedRandom<int> wr = new WeightedRandom<int>(unifiedRandom);
        PrefixCategory? prefixCategory = item.GetPrefixCategory();
        if (prefixCategory.HasValue)
        {
            PrefixCategory category2 = prefixCategory.GetValueOrDefault();
            if (justCheck)
            {
                return true;
            }
            int[] vanillaPrefixes = Item.GetVanillaPrefixes(category2);
            foreach (int pre in vanillaPrefixes)
            {
                wr.Add(pre);
            }
            if (PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2[item.type])
            {
                wr.Add(84);
            }
            AddCategory(category2);
            if (IsWeaponSubCategory(category2))
            {
                AddCategory(PrefixCategory.AnyWeapon);
            }
            for (int i = 0; i < 50; i++)
            {
                prefix = wr.Get();
                if (ItemLoader.AllowPrefix(item, prefix))
                {
                    return true;
                }
            }
            return false;
        }
        return false;
        void AddCategory(PrefixCategory category)
        {
            foreach (ModPrefix modPrefix in categoryPrefixes[category].Where((ModPrefix x) => x.CanRoll(item)))
            {
                wr.Add(modPrefix.Type, modPrefix.RollChance(item));
            }
        }
    }
References Terraria.ModLoader.ItemLoader.AllowPrefix(), Terraria.ModLoader.ModPrefix.CanRoll(), Terraria.ModLoader.PrefixLoader.CanRoll(), Terraria.ModLoader.PrefixLoader.categoryPrefixes, Terraria.ModLoader.ItemLoader.ChoosePrefix(), Terraria.Item.GetPrefixCategory(), Terraria.Item.GetVanillaPrefixes(), Terraria.ModLoader.PrefixLoader.IsWeaponSubCategory(), Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2, and Terraria.Item.type.
Referenced by Terraria.Item.Prefix(), and Terraria.Item.RollAPrefix().