TModLoader: Terraria.ModLoader.PrefixLoader.CanRoll
CanRoll()
static bool Terraria.ModLoader.PrefixLoader.CanRoll (Item item, int prefix) inline static
Definition at line 90 of file PrefixLoader.cs.
    {
        if (!ItemLoader.AllowPrefix(item, prefix))
        {
            return false;
        }
        ModPrefix modPrefix = GetPrefix(prefix);
        PrefixCategory? prefixCategory;
        if (modPrefix != null)
        {
            if (!modPrefix.CanRoll(item))
            {
                return false;
            }
            if (modPrefix.Category == PrefixCategory.Custom)
            {
                return true;
            }
            prefixCategory = item.GetPrefixCategory();
            if (prefixCategory.HasValue)
            {
                PrefixCategory itemCategory = prefixCategory.GetValueOrDefault();
                if (modPrefix.Category != itemCategory)
                {
                    if (modPrefix.Category == PrefixCategory.AnyWeapon)
                    {
                        return IsWeaponSubCategory(itemCategory);
                    }
                    return false;
                }
                return true;
            }
            return false;
        }
        prefixCategory = item.GetPrefixCategory();
        if (prefixCategory.HasValue)
        {
            PrefixCategory category = prefixCategory.GetValueOrDefault();
            if (Item.GetVanillaPrefixes(category).Contains(prefix))
            {
                return true;
            }
        }
        if (PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2[item.type] && prefix == 84)
        {
            return true;
        }
        return false;
    }
References Terraria.ModLoader.ItemLoader.AllowPrefix(), Terraria.ModLoader.PrefixLoader.GetPrefix(), Terraria.Item.GetPrefixCategory(), Terraria.Item.GetVanillaPrefixes(), Terraria.ModLoader.PrefixLoader.IsWeaponSubCategory(), Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2, and Terraria.Item.type.
Referenced by Terraria.Item.CanRollPrefix(), and Terraria.ModLoader.PrefixLoader.Roll().