TModLoader: Terraria.ModLoader.PrefixLoader.GetPrefix
GetPrefix()
static ModPrefix Terraria.ModLoader.PrefixLoader.GetPrefix (int type) inline static
Returns the ModPrefix associated with specified type If not a ModPrefix, returns null.
    {
        if (type < PrefixID.Count || type >= PrefixCount)
        {
            return null;
        }
        return prefixes[type - PrefixID.Count];
    }
References Terraria.ID.PrefixID.Count, Terraria.ModLoader.PrefixLoader.PrefixCount, and Terraria.ModLoader.PrefixLoader.prefixes.
Referenced by Terraria.ModLoader.PrefixLoader.ApplyAccessoryEffects(), Terraria.ModLoader.PrefixLoader.CanRoll(), Terraria.ModLoader.Config.UI.PrefixDefinitionElement.GetPassedOptionElements(), Terraria.ModLoader.ItemLoader.ModifyTooltips(), Terraria.Item.Prefix(), Terraria.ModLoader.IO.ItemIO.Save(), and Terraria.Item.TryGetPrefixStatMultipliersForItem().