TModLoader: Terraria.GameContent.PlayerSittingHelper.GetSittingTargetInfo
GetSittingTargetInfo()
static bool Terraria.GameContent.PlayerSittingHelper.GetSittingTargetInfo (Player player, int x, int y, out int targetDirection, out Vector2 playerSittingPosition, out Vector2 seatDownOffset, out ExtraSeatInfo extraInfo) inline static
Definition at line 184 of file PlayerSittingHelper.cs.
    {
        //IL_002e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0033: Unknown result type (might be due to invalid IL or missing references)
        //IL_003a: Unknown result type (might be due to invalid IL or missing references)
        //IL_004b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        //IL_0057: Unknown result type (might be due to invalid IL or missing references)
        //IL_005c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0224: Unknown result type (might be due to invalid IL or missing references)
        //IL_0229: Unknown result type (might be due to invalid IL or missing references)
        //IL_0489: Unknown result type (might be due to invalid IL or missing references)
        //IL_0490: Unknown result type (might be due to invalid IL or missing references)
        //IL_0498: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_04f7: Unknown result type (might be due to invalid IL or missing references)
        //IL_050b: Unknown result type (might be due to invalid IL or missing references)
        //IL_051a: Unknown result type (might be due to invalid IL or missing references)
        //IL_051f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0538: Unknown result type (might be due to invalid IL or missing references)
        //IL_053d: Unknown result type (might be due to invalid IL or missing references)
        //IL_053f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0544: Unknown result type (might be due to invalid IL or missing references)
        //IL_042c: Unknown result type (might be due to invalid IL or missing references)
        //IL_042e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0473: Unknown result type (might be due to invalid IL or missing references)
        //IL_0478: Unknown result type (might be due to invalid IL or missing references)
        //IL_047a: Unknown result type (might be due to invalid IL or missing references)
        //IL_047f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0468: Unknown result type (might be due to invalid IL or missing references)
        //IL_046a: Unknown result type (might be due to invalid IL or missing references)
        //IL_045d: Unknown result type (might be due to invalid IL or missing references)
        //IL_045f: Unknown result type (might be due to invalid IL or missing references)
        extraInfo = default(ExtraSeatInfo);
        Tile tileSafely = Framing.GetTileSafely(x, y);
        if (!TileID.Sets.CanBeSatOnForPlayers[tileSafely.type] || !tileSafely.active())
        {
            targetDirection = 1;
            seatDownOffset = Vector2.Zero;
            playerSittingPosition = default(Vector2);
            return false;
        }
        int num = x;
        int num2 = y;
        targetDirection = 1;
        seatDownOffset = Vector2.Zero;
        int num3 = 6;
        Vector2 zero = Vector2.Zero;
        switch (tileSafely.type)
        {
        case 15:
        case 497:
        {
            bool num7 = tileSafely.type == 15 && (tileSafely.frameY / 40 == 1 || tileSafely.frameY / 40 == 20);
            bool value = tileSafely.type == 15 && tileSafely.frameY / 40 == 27;
            seatDownOffset.Y = value.ToInt() * 4;
            if (tileSafely.frameY % 40 != 0)
            {
                num2--;
            }
            targetDirection = -1;
            if (tileSafely.frameX != 0)
            {
                targetDirection = 1;
            }
            if (num7 || tileSafely.type == 497)
            {
                extraInfo.IsAToilet = true;
            }
            break;
        }
        case 102:
        {
            int num5 = tileSafely.frameX / 18;
            if (num5 == 0)
            {
                num++;
            }
            if (num5 == 2)
            {
                num--;
            }
            int num6 = tileSafely.frameY / 18;
            if (num6 == 0)
            {
                num2 += 2;
            }
            if (num6 == 1)
            {
                num2++;
            }
            if (num6 == 3)
            {
                num2--;
            }
            targetDirection = player.direction;
            num3 = 0;
            break;
        }
        case 487:
        {
            int num4 = tileSafely.frameX % 72 / 18;
            if (num4 == 1)
            {
                num--;
            }
            if (num4 == 2)
            {
                num++;
            }
            if (tileSafely.frameY / 18 != 0)
            {
                num2--;
            }
            targetDirection = (num4 <= 1).ToDirectionInt();
            num3 = 0;
            seatDownOffset.Y -= 1f;
            break;
        }
        case 89:
        {
            targetDirection = player.direction;
            num3 = 0;
            Vector2 vector = default(Vector2);
            ((Vector2)(ref vector))._002Ector(-4f, 2f);
            Vector2 vector2 = default(Vector2);
            ((Vector2)(ref vector2))._002Ector(4f, 2f);
            Vector2 vector3 = default(Vector2);
            ((Vector2)(ref vector3))._002Ector(0f, 2f);
            Vector2 zero2 = Vector2.Zero;
            zero2.X = 1f;
            zero.X = -1f;
            switch (tileSafely.frameX / 54)
            {
            case 0:
                vector3.Y = (vector.Y = (vector2.Y = 1f));
                break;
            case 1:
                vector3.Y = 1f;
                break;
            case 2:
            case 14:
            case 15:
            case 17:
            case 20:
            case 21:
            case 22:
            case 23:
            case 25:
            case 26:
            case 27:
            case 28:
            case 35:
            case 37:
            case 38:
            case 39:
            case 40:
            case 41:
            case 42:
                vector3.Y = (vector.Y = (vector2.Y = 1f));
                break;
            case 3:
            case 4:
            case 5:
            case 7:
            case 8:
            case 9:
            case 10:
            case 11:
            case 12:
            case 13:
            case 16:
            case 18:
            case 19:
            case 36:
                vector3.Y = (vector.Y = (vector2.Y = 0f));
                break;
            case 6:
                vector3.Y = (vector.Y = (vector2.Y = -1f));
                break;
            case 24:
                vector3.Y = 0f;
                vector.Y = -4f;
                vector.X = 0f;
                vector2.X = 0f;
                vector2.Y = -4f;
                break;
            }
            if (tileSafely.frameY % 40 != 0)
            {
                num2--;
            }
            if ((tileSafely.frameX % 54 == 0 && targetDirection == -1) || (tileSafely.frameX % 54 == 36 && targetDirection == 1))
            {
                seatDownOffset = vector;
            }
            else if ((tileSafely.frameX % 54 == 0 && targetDirection == 1) || (tileSafely.frameX % 54 == 36 && targetDirection == -1))
            {
                seatDownOffset = vector2;
            }
            else
            {
                seatDownOffset = vector3;
            }
            seatDownOffset += zero2;
            break;
        }
        }
        TileRestingInfo info = new TileRestingInfo(player, new Point(num, num2), seatDownOffset, targetDirection, num3, zero, extraInfo);
        TileLoader.ModifySittingTargetInfo(x, y, tileSafely.type, ref info);
        num = info.AnchorTilePosition.X;
        num2 = info.AnchorTilePosition.Y;
        num3 = info.DirectionOffset;
        targetDirection = info.TargetDirection;
        seatDownOffset = info.VisualOffset;
        zero = info.FinalOffset;
        extraInfo = info.ExtraInfo;
        playerSittingPosition = Utils.ToWorldCoordinates(new Point(num, num2), 8f, 16f);
        playerSittingPosition.X += targetDirection * num3;
        playerSittingPosition += zero;
        return true;
    }
References Terraria.ID.TileID.Sets.CanBeSatOnForPlayers, Terraria.Entity.direction, Terraria.Framing.GetTileSafely(), Terraria.ModLoader.TileLoader.ModifySittingTargetInfo(), and Terraria.Utils.ToWorldCoordinates().
Referenced by Terraria.GameContent.PlayerSittingHelper.SitDown(), Terraria.GameContent.PlayerSittingHelper.TryGetSittingBlock(), and Terraria.GameContent.PlayerSittingHelper.UpdateSitting().