TModLoader: Terraria.GameContent.PlayerSittingHelper.TryGetSittingBlock
TryGetSittingBlock()
bool Terraria.GameContent.PlayerSittingHelper.TryGetSittingBlock (Player player, out Tile tile) inline
Definition at line 46 of file PlayerSittingHelper.cs.
    {
        //IL_0012: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_002b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0030: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_0038: Unknown result type (might be due to invalid IL or missing references)
        //IL_0050: Unknown result type (might be due to invalid IL or missing references)
        tile = default(Tile);
        if (!isSitting)
        {
            return false;
        }
        Point pt = (player.Bottom + new Vector2(0f, -2f)).ToTileCoordinates();
        if (!GetSittingTargetInfo(player, pt.X, pt.Y, out var _, out var _, out var _, out var _))
        {
            return false;
        }
        tile = Framing.GetTileSafely(pt);
        return true;
    }
References Terraria.GameContent.PlayerSittingHelper.GetSittingTargetInfo(), Terraria.Framing.GetTileSafely(), and Terraria.GameContent.PlayerSittingHelper.isSitting.
Referenced by Terraria.Player.GetFishingConditions().