TModLoader: Terraria.GameContent.UI.Elements.UIText.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIText.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 146 of file UIText.cs.
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0113: Unknown result type (might be due to invalid IL or missing references)
        //IL_0118: Unknown result type (might be due to invalid IL or missing references)
        //IL_0124: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_012b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0130: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_015e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0165: Unknown result type (might be due to invalid IL or missing references)
        //IL_0167: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_017d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0187: Unknown result type (might be due to invalid IL or missing references)
        //IL_0189: Unknown result type (might be due to invalid IL or missing references)
        //IL_0193: Unknown result type (might be due to invalid IL or missing references)
        base.DrawSelf(spriteBatch);
        VerifyTextState();
        CalculatedStyle innerDimensions = GetInnerDimensions();
        Vector2 position = innerDimensions.Position();
        if (_isLarge)
        {
            position.Y -= 10f * _textScale;
        }
        else
        {
            position.Y -= 2f * _textScale;
        }
        position.X += (innerDimensions.Width - _textSize.X) * TextOriginX;
        position.Y += (innerDimensions.Height - _textSize.Y) * TextOriginY;
        float num = _textScale;
        if (DynamicallyScaleDownToWidth && _textSize.X > innerDimensions.Width)
        {
            num *= innerDimensions.Width / _textSize.X;
        }
        DynamicSpriteFont value = (_isLarge ? FontAssets.DeathText : FontAssets.MouseText).Value;
        Vector2 vector = value.MeasureString(_visibleText);
        Color baseColor = _shadowColor * ((float)(int)((Color)(ref _color)).A / 255f);
        Vector2 origin = new Vector2(0f, 0f) * vector;
        Vector2 baseScale = default(Vector2);
        ((Vector2)(ref baseScale))._002Ector(num);
        TextSnippet[] snippets = ChatManager.ParseMessage(_visibleText, _color).ToArray();
        ChatManager.ConvertNormalSnippets(snippets);
        ChatManager.DrawColorCodedStringShadow(spriteBatch, value, snippets, position, baseColor, 0f, origin, baseScale, -1f, 1.5f);
        ChatManager.DrawColorCodedString(spriteBatch, value, snippets, position, Color.White, 0f, origin, baseScale, out var _, -1f);
    }
References Terraria.GameContent.UI.Elements.UIText._color, Terraria.GameContent.UI.Elements.UIText._isLarge, Terraria.GameContent.UI.Elements.UIText._shadowColor, Terraria.GameContent.UI.Elements.UIText._textScale, Terraria.GameContent.UI.Elements.UIText._textSize, Terraria.GameContent.UI.Elements.UIText._visibleText, Terraria.UI.Chat.ChatManager.ConvertNormalSnippets(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.GameContent.UI.Elements.UIText.DynamicallyScaleDownToWidth, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.GameContent.FontAssets.MouseText, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.GameContent.UI.Elements.UIText.TextOriginX, Terraria.GameContent.UI.Elements.UIText.TextOriginY, and Terraria.GameContent.UI.Elements.UIText.VerifyTextState().