TModLoader: Terraria.GameContent.UI.Elements.UIText.InternalSetText
InternalSetText()
void Terraria.GameContent.UI.Elements.UIText.InternalSetText (object text, float textScale, bool large) inline private
    {
        //IL_0086: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_0095: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b2: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00df: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00da: Unknown result type (might be due to invalid IL or missing references)
        //IL_011a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f6: Unknown result type (might be due to invalid IL or missing references)
        DynamicSpriteFont dynamicSpriteFont = (large ? FontAssets.DeathText.Value : FontAssets.MouseText.Value);
        _text = text;
        _isLarge = large;
        _textScale = textScale;
        _lastTextReference = _text.ToString();
        if (IsWrapped)
        {
            _visibleText = dynamicSpriteFont.CreateWrappedText(_lastTextReference, GetInnerDimensions().Width / _textScale);
        }
        else
        {
            _visibleText = _lastTextReference;
        }
        Vector2 vector = ChatManager.GetStringSize(dynamicSpriteFont, _visibleText, new Vector2(1f));
        Vector2 vector2 = (_textSize = ((!IsWrapped) ? (new Vector2(vector.X, large ? 32f : 16f) * textScale) : (new Vector2(vector.X, vector.Y + WrappedTextBottomPadding) * textScale)));
        if (!IsWrapped)
        {
            MinWidth.Set(vector2.X + PaddingLeft + PaddingRight, 0f);
        }
        MinHeight.Set(vector2.Y + PaddingTop + PaddingBottom, 0f);
        if (this.OnInternalTextChange != null)
        {
            this.OnInternalTextChange();
        }
    }
References Terraria.GameContent.UI.Elements.UIText._isLarge, Terraria.GameContent.UI.Elements.UIText._lastTextReference, Terraria.GameContent.UI.Elements.UIText._text, Terraria.GameContent.UI.Elements.UIText._textScale, Terraria.GameContent.UI.Elements.UIText._textSize, Terraria.GameContent.UI.Elements.UIText._visibleText, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.UI.Elements.UIText.IsWrapped, Terraria.UI.UIElement.MinHeight, Terraria.UI.UIElement.MinWidth, Terraria.GameContent.FontAssets.MouseText, Terraria.GameContent.UI.Elements.UIText.OnInternalTextChange, Terraria.UI.UIElement.PaddingBottom, Terraria.UI.UIElement.PaddingLeft, Terraria.UI.UIElement.PaddingRight, Terraria.UI.UIElement.PaddingTop, Terraria.UI.StyleDimension.Set(), Terraria.UI.CalculatedStyle.Width, and Terraria.GameContent.UI.Elements.UIText.WrappedTextBottomPadding.
Referenced by Terraria.GameContent.UI.Elements.UIText.UIText(), Terraria.GameContent.UI.Elements.UIText.UIText(), Terraria.GameContent.UI.Elements.UIText.Recalculate(), Terraria.GameContent.UI.Elements.UIText.SetText(), Terraria.GameContent.UI.Elements.UIText.SetText(), Terraria.GameContent.UI.Elements.UIText.SetText(), Terraria.GameContent.UI.Elements.UIText.SetText(), and Terraria.GameContent.UI.Elements.UIText.VerifyTextState().