TModLoader: Terraria.Program.PortFilesFromXtoY
PortFilesFromXtoY()
static void Terraria.Program.PortFilesFromXtoY (string superSavePath, string source, string destination, string maxVersionOfSource, bool isCloud, bool isAtomicLockable) inline static private
Super Save Path is the parent directory containing both folders. Usually Program.SavePath or Steam Cloud Source is of variety StableFolder, PreviewFolder... etc Destination is of variety StableFolder, PreviewFolder... etc maxVersionOfSource is used to determine if we even should port the files. Example: 1.4.3-Legacy has maxVersion of 2022.9 isAtomicLockable could be expressed as CopyToNewlyCreatedDestinationFolderViaTempFolder if that makes more sense to the reader.
Definition at line 377 of file Program.cs.
    {
        string newFolderPath = Path.Combine(superSavePath, destination);
        string newFolderPathTemp = Path.Combine(superSavePath, destination + "-temp");
        string oldFolderPath = Path.Combine(superSavePath, source);
        string cloudName = (isCloud ? "Steam Cloud" : "Local Files");
        if (!Directory.Exists(oldFolderPath))
        {
            return;
        }
        string portFilePath = Path.Combine(superSavePath, destination, (maxVersionOfSource == "2022.9") ? ("143ported_" + cloudName + ".txt") : $"{maxVersionOfSource}{destination}ported_{cloudName}.txt");
        if ((isAtomicLockable && Directory.Exists(newFolderPath)) || (!isAtomicLockable && File.Exists(portFilePath)))
        {
            return;
        }
        if (newFolderPath.Contains("OneDrive"))
        {
            Logging.tML.Info((object)"Ensuring OneDrive is running before starting to Migrate Files");
            try
            {
                string oneDrivePath1 = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Microsoft\\OneDrive\\OneDrive.exe");
                string oneDrivePath2 = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ProgramFiles), "Microsoft OneDrive\\OneDrive.exe");
                if (File.Exists(oneDrivePath1))
                {
                    Process.Start(oneDrivePath1);
                }
                else if (File.Exists(oneDrivePath2))
                {
                    Process.Start(oneDrivePath2);
                }
                Thread.Sleep(3000);
            }
            catch
            {
            }
        }
        string sourceFolderConfig = Path.Combine(LaunchParameters.ContainsKey("-savedirectory") ? LaunchParameters["-savedirectory"] : Platform.Get<IPathService>().GetStoragePath("Terraria"), source, "config.json");
        if (!File.Exists(sourceFolderConfig))
        {
            Logging.tML.Info((object)("No config.json found at " + sourceFolderConfig + "\nAssuming nothing to port"));
            return;
        }
        string lastLaunchedTml = null;
        try
        {
            if (JsonConvert.DeserializeObject<Dictionary<string, object>>(File.ReadAllText(sourceFolderConfig)).TryGetValue("LastLaunchedTModLoaderVersion", out var lastLaunchedTmlObject))
            {
                lastLaunchedTml = (string)lastLaunchedTmlObject;
            }
        }
        catch (Exception e2)
        {
            e2.HelpLink = "https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#configjson-corrupted";
            ErrorReporting.FatalExit($"Attempt to Port from \"{oldFolderPath}\" to \"{newFolderPath}\" aborted, the \"{sourceFolderConfig}\" file is corrupted.", e2);
        }
        if (string.IsNullOrEmpty(lastLaunchedTml))
        {
            ErrorReporting.FatalExit($"Attempt to Port from \"{oldFolderPath}\" to \"{newFolderPath}\" aborted, the \"{sourceFolderConfig}\" file is missing the \"LastLaunchedTModLoaderVersion\" entry. If porting is desired, follow the instructions at \"https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#manually-port\"");
            return;
        }
        if (new Version(lastLaunchedTml).MajorMinor() > new Version(maxVersionOfSource))
        {
            Logging.tML.Info((object)$"Attempt to Port from \"{oldFolderPath}\" to \"{newFolderPath}\" aborted, \"{lastLaunchedTml}\" is a newer version.");
            return;
        }
        Logging.tML.Info((object)($"Cloning current {source} files to {destination} save folder. Porting {cloudName}." + "\nThis may take a few minutes for a large amount of files."));
        try
        {
            FileUtilities.CopyFolderEXT(oldFolderPath, isAtomicLockable ? newFolderPathTemp : newFolderPath, isCloud, new Regex("(Workshop|ModSources)($|/|\\\\)"), overwriteAlways: false, overwriteOld: true);
        }
        catch (Exception e)
        {
            e.HelpLink = "https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#migration-failed";
            ErrorReporting.FatalExit("Migration Failed, please consult the instructions in the \"Migration Failed\" section at \"" + e.HelpLink + "\" for more information.", e);
        }
        if (isAtomicLockable)
        {
            Directory.Move(newFolderPathTemp, newFolderPath);
        }
        else if (isCloud)
        {
            if (SocialAPI.Cloud != null)
            {
                SocialAPI.Cloud.Write(FileUtilities.ConvertToRelativePath(superSavePath, portFilePath), new byte[0]);
            }
        }
        else
        {
            File.Create(portFilePath);
        }
        Logging.tML.Info((object)("Porting " + cloudName + " finished"));
    }
References Terraria.Social.SocialAPI.Cloud, Terraria.Utilities.FileUtilities.ConvertToRelativePath(), Terraria.Utilities.FileUtilities.CopyFolderEXT(), Terraria.ModLoader.Environment, Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.Program.LaunchParameters, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.Program.PortFilesMaster().