TModLoader: Terraria.Program.LaunchParameters
LaunchParameters
Dictionary<string, string> Terraria.Program.LaunchParameters = new Dictionary<string, string>() static
Referenced by Terraria.ModLoader.ModNet.ModNet(), Terraria.ModLoader.Core.ModCompile.BuildMod(), Terraria.Social.Steam.NetClientSocialModule.CheckParameters(), Terraria.ModLoader.Core.ModCompile.CompileMod(), Terraria.ModLoader.Engine.FNAFixes.ConfigureDrivers(), Terraria.ModLoader.Engine.InstallVerifier.DetectPlatform(), Terraria.ModLoader.Core.ModCompile.DllRefPath(), Terraria.Main.FindAnnouncementBoxStatus(), Terraria.Social.Steam.WorkshopHelper.GetWorkshopFolder(), Terraria.Initializers.LaunchInitializer.HasParameter(), Terraria.ModLoader.Logging.Init(), Terraria.Social.Steam.NetClientSocialModule.Initialize(), Terraria.Social.Steam.NetServerSocialModule.Initialize(), Terraria.Social.WeGame.NetServerSocialModule.Initialize(), Terraria.Social.SocialAPI.Initialize(), Terraria.Program.InitializeConsoleOutput(), Terraria.Net.SteamAddress.IsLocalHost(), Terraria.Net.WeGameAddress.IsLocalHost(), Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssembly(), Terraria.Main.LoadDedConfig(), Terraria.ModLoader.Logging.LogStartup(), Terraria.Program.PortFilesFromXtoY(), Terraria.Program.ProcessLaunchArgs(), Terraria.ModLoader.Engine.TerrariaSteamClient.Run(), Terraria.Program.SetSavePath(), Terraria.Program.SetupLogging(), Terraria.Net.Sockets.TcpSocket.StartListening(), Terraria.Social.Steam.WorkshopSocialModule.SteamCMDPublishPreparer(), and Terraria.Initializers.LaunchInitializer.TryParameter().