TModLoader: Terraria.Program.ProcessLaunchArgs
ProcessLaunchArgs()
static void Terraria.Program.ProcessLaunchArgs (string[] args, bool monoArgs, out bool isServer) inline static private
    {
        isServer = false;
        try
        {
            if (monoArgs)
            {
                args = Utils.ConvertMonoArgsToDotNet(args);
            }
            LaunchParameters = Utils.ParseArguements(args);
            if (LaunchParameters.ContainsKey("-terrariasteamclient"))
            {
                TerrariaSteamClient.Run();
                Environment.Exit(1);
            }
            SavePath = (LaunchParameters.ContainsKey("-savedirectory") ? LaunchParameters["-savedirectory"] : Platform.Get<IPathService>().GetStoragePath("Terraria"));
            isServer = LaunchParameters.ContainsKey("-server");
        }
        catch (Exception e)
        {
            ErrorReporting.FatalExit("Unhandled Issue with Launch Arguments. Please verify sources such as Steam Launch Options, cli-ArgsConfig, and VS profiles", e);
        }
    }
References Terraria.Utils.ConvertMonoArgsToDotNet(), Terraria.ModLoader.Environment, Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.Program.LaunchParameters, Terraria.Utils.ParseArguements(), Terraria.ModLoader.Engine.TerrariaSteamClient.Run(), and Terraria.Program.SavePath.
Referenced by Terraria.Program.LaunchGame().