TModLoader: Terraria.Program.RunGame
RunGame()
static void Terraria.Program.RunGame () inline static
    {
        LanguageManager.Instance.SetLanguage(GameCulture.DefaultCulture);
        if (Platform.IsOSX)
        {
            Main.OnEngineLoad += delegate
            {
                ((Game)Main.instance).IsMouseVisible = false;
            };
        }
        InstallVerifier.Startup();
        try
        {
            Terraria.ModLoader.ModLoader.EngineInit();
            Main main = new Main();
            try
            {
                Lang.InitializeLegacyLocalization();
                SocialAPI.Initialize();
                LaunchInitializer.LoadParameters(main);
                Main.OnEnginePreload += StartForceLoad;
                if (Main.dedServ)
                {
                    main.DedServ();
                }
                else
                {
                    ((Game)main).Run();
                }
            }
            finally
            {
                ((IDisposable)main)?.Dispose();
            }
        }
        catch (Exception e)
        {
            ErrorReporting.FatalExit("Main engine crash", e);
        }
    }
References Terraria.Main.dedServ, Terraria.Localization.GameCulture.DefaultCulture, Terraria.ModLoader.ModLoader.EngineInit(), Terraria.ModLoader.Engine.ErrorReporting.FatalExit(), Terraria.Social.SocialAPI.Initialize(), Terraria.Lang.InitializeLegacyLocalization(), Terraria.Localization.LanguageManager.Instance, Terraria.Main.instance, Terraria.Initializers.LaunchInitializer.LoadParameters(), Terraria.Localization.LanguageManager.SetLanguage(), Terraria.Program.StartForceLoad(), and Terraria.ModLoader.Engine.InstallVerifier.Startup().
Referenced by Terraria.Program.LaunchGame_().