TModLoader: Terraria.ModLoader.Engine.TerrariaSteamClient.Run
Run()
static void Terraria.ModLoader.Engine.TerrariaSteamClient.Run () inline static package
    {
        //IL_0044: Unknown result type (might be due to invalid IL or missing references)
        //IL_0049: Unknown result type (might be due to invalid IL or missing references)
        //IL_0061: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        Logging.Init(Logging.LogFile.TerrariaSteamClient);
        Logger.InfoFormat("Working Directory: {0}", (object)Path.GetFullPath(Directory.GetCurrentDirectory()));
        Logger.InfoFormat("Args: {0}", (object)string.Join(' ', Environment.GetCommandLineArgs()));
        ILog logger = Logger;
        AppId_t terrariaAppId_t = Steam.TerrariaAppId_t;
        logger.Info((object)("Setting steam app id to " + ((object)(AppId_t)(ref terrariaAppId_t)).ToString()));
        Steam.SetAppId(Steam.TerrariaAppId_t);
        bool steamInit = false;
        try
        {
            using AnonymousPipeClientStream clientPipe = new AnonymousPipeClientStream(PipeDirection.In, Program.LaunchParameters["-terrariasteamclient"]);
            StreamReader sr = new StreamReader(clientPipe, null, detectEncodingFromByteOrderMarks: true, -1, leaveOpen: true);
            try
            {
                Func<string> Recv = delegate
                {
                    string text = sr.ReadLine()?.Trim();
                    if (text == null)
                    {
                        throw new EndOfStreamException();
                    }
                    Logger.Debug((object)("Recv: " + text));
                    return text;
                };
                Action<string> Send = delegate(string s)
                {
                    Logger.Debug((object)("Send: " + s));
                    Console.WriteLine(s);
                };
                Logger.Info((object)"SteamAPI.Init()");
                steamInit = SteamAPI.Init();
                if (!steamInit)
                {
                    Logger.Fatal((object)"SteamAPI.Init() failed");
                    Send(MsgInitFailed);
                    return;
                }
                if (!SteamApps.BIsAppInstalled(Steam.TerrariaAppId_t))
                {
                    Logger.Fatal((object)$"SteamApps.BIsAppInstalled({Steam.TerrariaAppId_t}): false");
                    Send(MsgNotInstalled);
                    SteamShutdown();
                    return;
                }
                int TerrariaBuildID = SteamApps.GetAppBuildId();
                Logger.Info((object)("Terraria BuildID: " + TerrariaBuildID));
                if (TerrariaBuildID < 9653812)
                {
                    Logger.Fatal((object)"Terraria is out of date, you need to update Terraria in Steam.");
                    Send(MsgInstallOutOfDate);
                    SteamShutdown();
                    return;
                }
                if (SteamApps.BIsSubscribedFromFamilySharing())
                {
                    Logger.Info((object)"Terraria is installed via Family Share. Re-pathing tModLoader required");
                    Send(MsgFamilyShared);
                }
                Send(MsgInitSuccess);
                while (Recv() != MsgAck)
                {
                }
                bool pbAchieved = default(bool);
                while (true)
                {
                    Thread.Sleep(250);
                    string nextCMD = Recv();
                    if (nextCMD == MsgShutdown)
                    {
                        break;
                    }
                    if (nextCMD.StartsWith(MsgGrant))
                    {
                        string achievement = nextCMD.Substring(MsgGrant.Length);
                        SteamUserStats.GetAchievement(achievement, ref pbAchieved);
                        if (!pbAchieved)
{
                            SteamUserStats.SetAchievement(achievement);
                        }
                    }
                    if (nextCMD == MsgInvalidateTerrariaInstall)
                    {
                        SteamApps.MarkContentCorrupt(false);
                    }
                }
            }
            finally
            {
                if (sr != null)
                {
                    ((IDisposable)sr).Dispose();
                }
            }
        }
        catch (EndOfStreamException)
        {
            Logger.Info((object)"The connection to tML was closed unexpectedly. Look in client.log or server.log for details");
        }
        catch (Exception ex)
        {
            Logger.Fatal((object)"Unhandled error", ex);
        }
        if (steamInit)
        {
            SteamShutdown();
        }
    }
References Terraria.ModLoader.Console, Terraria.ModLoader.Environment, Terraria.ModLoader.Logging.Init(), Terraria.Program.LaunchParameters, Terraria.ModLoader.Engine.TerrariaSteamClient.Logger, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgAck, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgFamilyShared, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgGrant, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgInitFailed, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgInitSuccess, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgInstallOutOfDate, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgInvalidateTerrariaInstall, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgNotInstalled, Terraria.ModLoader.Engine.TerrariaSteamClient.MsgShutdown, Terraria.ModLoader.Engine.Steam.SetAppId(), Terraria.ModLoader.Engine.TerrariaSteamClient.SteamShutdown(), and Terraria.ModLoader.Engine.Steam.TerrariaAppId_t.
Referenced by Terraria.Program.ProcessLaunchArgs().