TModLoader: Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion
EmitGolfballExplosion()
static void Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion (Vector2 Center) inline static
        {
            //IL_0005: Unknown result type (might be due to invalid IL or missing references)
            //IL_001d: Unknown result type (might be due to invalid IL or missing references)
            //IL_002a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0039: Unknown result type (might be due to invalid IL or missing references)
            //IL_003e: Unknown result type (might be due to invalid IL or missing references)
            //IL_004b: Unknown result type (might be due to invalid IL or missing references)
            //IL_0051: Unknown result type (might be due to invalid IL or missing references)
            //IL_00d8: Unknown result type (might be due to invalid IL or missing references)
            //IL_00dd: Unknown result type (might be due to invalid IL or missing references)
            //IL_0143: Unknown result type (might be due to invalid IL or missing references)
            //IL_0152: Unknown result type (might be due to invalid IL or missing references)
            //IL_0157: Unknown result type (might be due to invalid IL or missing references)
            //IL_0172: Unknown result type (might be due to invalid IL or missing references)
            //IL_0177: Unknown result type (might be due to invalid IL or missing references)
            //IL_0195: Unknown result type (might be due to invalid IL or missing references)
            //IL_019a: Unknown result type (might be due to invalid IL or missing references)
            //IL_01ad: Unknown result type (might be due to invalid IL or missing references)
            //IL_01be: Unknown result type (might be due to invalid IL or missing references)
            //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
            //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d7: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e1: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e7: Unknown result type (might be due to invalid IL or missing references)
            //IL_0226: Unknown result type (might be due to invalid IL or missing references)
            //IL_022e: Unknown result type (might be due to invalid IL or missing references)
            //IL_0233: Unknown result type (might be due to invalid IL or missing references)
            //IL_0256: Unknown result type (might be due to invalid IL or missing references)
            //IL_026a: Unknown result type (might be due to invalid IL or missing references)
            //IL_026f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0274: Unknown result type (might be due to invalid IL or missing references)
            //IL_0279: Unknown result type (might be due to invalid IL or missing references)
            //IL_027b: Unknown result type (might be due to invalid IL or missing references)
            //IL_02aa: Unknown result type (might be due to invalid IL or missing references)
            //IL_02b8: Unknown result type (might be due to invalid IL or missing references)
            //IL_02c7: Unknown result type (might be due to invalid IL or missing references)
            //IL_02cc: Unknown result type (might be due to invalid IL or missing references)
            //IL_02d9: Unknown result type (might be due to invalid IL or missing references)
            //IL_02df: Unknown result type (might be due to invalid IL or missing references)
            //IL_0366: Unknown result type (might be due to invalid IL or missing references)
            //IL_036b: Unknown result type (might be due to invalid IL or missing references)
            //IL_039d: Unknown result type (might be due to invalid IL or missing references)
            //IL_03ad: Unknown result type (might be due to invalid IL or missing references)
            //IL_03b7: Unknown result type (might be due to invalid IL or missing references)
            //IL_03c4: Unknown result type (might be due to invalid IL or missing references)
            //IL_03ca: Unknown result type (might be due to invalid IL or missing references)
            //IL_03e7: Unknown result type (might be due to invalid IL or missing references)
            //IL_03fa: Unknown result type (might be due to invalid IL or missing references)
            //IL_03ff: Unknown result type (might be due to invalid IL or missing references)
            //IL_0471: Unknown result type (might be due to invalid IL or missing references)
            //IL_0478: Unknown result type (might be due to invalid IL or missing references)
            //IL_0482: Unknown result type (might be due to invalid IL or missing references)
            //IL_0487: Unknown result type (might be due to invalid IL or missing references)
            //IL_048c: Unknown result type (might be due to invalid IL or missing references)
            //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
            //IL_04c2: Unknown result type (might be due to invalid IL or missing references)
            SoundEngine.PlaySound(in SoundID.Item129, Center);
            for (float num = 0f; num < 1f; num += 0.085f)
            {
                Dust dust5 = Dust.NewDustPerfect(Center, 278, (num * ((float)Math.PI * 2f)).ToRotationVector2() * new Vector2(2f, 0.5f));
                dust5.fadeIn = 1.2f;
                dust5.noGravity = true;
                dust5.velocity.X *= 0.7f;
                dust5.velocity.Y -= 1.5f;
                dust5.position.Y += 8f;
                dust5.velocity.X *= 2f;
                dust5.color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.5f);
            }
            float num2 = Main.rand.NextFloat();
            float num3 = Main.rand.Next(5, 10);
            for (int i = 0; (float)i < num3; i++)
            {
                int num4 = Main.rand.Next(5, 22);
                Vector2 value = (((float)i - num3 / 2f) * ((float)Math.PI * 2f) / 256f - (float)Math.PI / 2f).ToRotationVector2() * new Vector2(5f, 1f) * (0.25f + Main.rand.NextFloat() * 0.05f);
                Color color = Main.hslToRgb((num2 + (float)i / num3) % 1f, 0.7f, 0.7f);
                ((Color)(ref color)).A = 127;
                for (int j = 0; j < num4; j++)
                {
                    Dust dust6 = Dust.NewDustPerfect(Center + new Vector2((float)i - num3 / 2f, 0f) * 2f, 278, value);
                    dust6.fadeIn = 0.7f;
                    dust6.scale = 0.7f;
                    dust6.noGravity = true;
                    dust6.position.Y += -1f;
                    dust6.velocity *= (float)j;
                    dust6.scale += 0.2f - (float)j * 0.03f;
                    dust6.velocity += Main.rand.NextVector2Circular(0.05f, 0.05f);
                    dust6.color = color;
                }
            }
            for (float num5 = 0f; num5 < 1f; num5 += 0.2f)
            {
                Dust dust7 = Dust.NewDustPerfect(Center, 278, (num5 * ((float)Math.PI * 2f)).ToRotationVector2() * new Vector2(1f, 0.5f));
                dust7.fadeIn = 1.2f;
                dust7.noGravity = true;
                dust7.velocity.X *= 0.7f;
                dust7.velocity.Y -= 0.5f;
                dust7.position.Y += 8f;
                dust7.velocity.X *= 2f;
                dust7.color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.3f);
            }
            float num6 = Main.rand.NextFloatDirection();
            for (float num7 = 0f; num7 < 1f; num7 += 0.15f)
            {
                Dust dust4 = Dust.NewDustPerfect(Center, 278, (num6 + num7 * ((float)Math.PI * 2f)).ToRotationVector2() * 4f);
                dust4.fadeIn = 1.5f;
                dust4.velocity *= 0.5f + num7 * 0.8f;
                dust4.noGravity = true;
                dust4.velocity.X *= 0.35f;
                dust4.velocity.Y *= 2f;
                dust4.velocity.Y -= 1f;
                dust4.velocity.Y = 0f - Math.Abs(dust4.velocity.Y);
                dust4.position += dust4.velocity * 3f;
                dust4.color = Main.hslToRgb(Main.rand.NextFloat(), 1f, 0.6f + Main.rand.NextFloat() * 0.2f);
            }
        }
References Terraria.Main.hslToRgb(), Terraria.ID.SoundID.Item129, Terraria.Dust.NewDustPerfect(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.rand.
Referenced by Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion_Old(), and Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup_TextAndEffects().