TModLoader: Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup
PutBallInCup()
void Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup (Projectile proj, BallCollisionEvent collision) inline
Definition at line 136 of file GolfHelper.cs.
        {
            //IL_0020: Unknown result type (might be due to invalid IL or missing references)
            //IL_0026: Unknown result type (might be due to invalid IL or missing references)
            //IL_0030: Unknown result type (might be due to invalid IL or missing references)
            //IL_0035: Unknown result type (might be due to invalid IL or missing references)
            //IL_003a: Unknown result type (might be due to invalid IL or missing references)
            //IL_003f: Unknown result type (might be due to invalid IL or missing references)
            //IL_009b: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ae: Unknown result type (might be due to invalid IL or missing references)
            //IL_00b4: Unknown result type (might be due to invalid IL or missing references)
            //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
            //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
            //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
            //IL_0103: Unknown result type (might be due to invalid IL or missing references)
            if (proj.owner == Main.myPlayer && Main.LocalGolfState.ShouldScoreHole)
            {
                Point hitLocation = (collision.ImpactPoint - collision.Normal * 0.5f).ToTileCoordinates();
                int owner = proj.owner;
                int num = (int)proj.ai[1];
                int type = proj.type;
                if (num > 1)
                {
                    Main.LocalGolfState.SetScoreTime();
                }
                Main.LocalGolfState.RecordBallInfo(proj);
                Main.LocalGolfState.LandBall(proj);
                int golfBallScore = Main.LocalGolfState.GetGolfBallScore(proj);
                if (num > 0)
                {
                    Main.player[owner].AccumulateGolfingScore(golfBallScore);
                }
                PutBallInCup_TextAndEffects(hitLocation, owner, num, type);
                Main.LocalGolfState.ResetScoreTime();
                Wiring.HitSwitch(hitLocation.X, hitLocation.Y);
                NetMessage.SendData(59, -1, -1, null, hitLocation.X, hitLocation.Y);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(128, -1, -1, null, owner, num, type, 0f, hitLocation.X, hitLocation.Y);
                }
            }
            proj.Kill();
        }
References Terraria.Wiring.HitSwitch(), Terraria.Main.LocalGolfState, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), and Terraria.NetMessage.SendData().
Referenced by Terraria.GameContent.Golf.GolfHelper.ContactListener.OnCollision().