TModLoader: Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup_TextAndEffects
PutBallInCup_TextAndEffects()
static void Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup_TextAndEffects (Point hitLocation, int plr, int numberOfHits, int projid) inline static
Definition at line 180 of file GolfHelper.cs.
        {
            //IL_0006: Unknown result type (might be due to invalid IL or missing references)
            //IL_0011: Unknown result type (might be due to invalid IL or missing references)
            //IL_00da: Unknown result type (might be due to invalid IL or missing references)
            if (numberOfHits != 0)
            {
                EmitGolfballExplosion(hitLocation.ToWorldCoordinates(8f, 0f));
                string key = "Game.BallBounceResultGolf_Single";
                NetworkText networkText;
                if (numberOfHits != 1)
                {
                    key = "Game.BallBounceResultGolf_Plural";
                    networkText = NetworkText.FromKey(key, Main.player[plr].name, NetworkText.FromKey(Lang.GetProjectileName(projid).Key), numberOfHits);
                }
                else
                {
                    networkText = NetworkText.FromKey(key, Main.player[plr].name, NetworkText.FromKey(Lang.GetProjectileName(projid).Key));
                }
                if (Main.netMode == 0 || Main.netMode == 1)
                {
                    Main.NewText(networkText.ToString(), byte.MaxValue, 240, 20);
                }
                else if (Main.netMode == 2)
                {
                    ChatHelper.BroadcastChatMessage(networkText, new Color(255, 240, 20));
                }
            }
        }
References Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion(), Terraria.Localization.NetworkText.FromKey(), Terraria.Lang.GetProjectileName(), Terraria.Main.netMode, Terraria.Main.NewText(), and Terraria.Main.player.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup().