TModLoader: Terraria.GameContent.Golf.GolfHelper.ContactListener.OnCollision
OnCollision()
void Terraria.GameContent.Golf.GolfHelper.ContactListener.OnCollision (PhysicsProperties properties, ref Vector2 position, ref Vector2 velocity, ref BallCollisionEvent collision) inline
Implements Terraria.Physics.IBallContactListener.
        {
            //IL_0014: Unknown result type (might be due to invalid IL or missing references)
            //IL_0024: Unknown result type (might be due to invalid IL or missing references)
            //IL_0029: Unknown result type (might be due to invalid IL or missing references)
            //IL_002c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0032: Unknown result type (might be due to invalid IL or missing references)
            //IL_0039: Unknown result type (might be due to invalid IL or missing references)
            //IL_0043: Unknown result type (might be due to invalid IL or missing references)
            //IL_005f: Unknown result type (might be due to invalid IL or missing references)
            //IL_0064: Unknown result type (might be due to invalid IL or missing references)
            //IL_0066: Unknown result type (might be due to invalid IL or missing references)
            //IL_0067: Unknown result type (might be due to invalid IL or missing references)
            //IL_0068: Unknown result type (might be due to invalid IL or missing references)
            //IL_006d: Unknown result type (might be due to invalid IL or missing references)
            //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
            //IL_0101: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f2: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
            //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
            //IL_0115: Unknown result type (might be due to invalid IL or missing references)
            //IL_011a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0133: Unknown result type (might be due to invalid IL or missing references)
            //IL_0138: Unknown result type (might be due to invalid IL or missing references)
            //IL_013d: Unknown result type (might be due to invalid IL or missing references)
            //IL_0172: Unknown result type (might be due to invalid IL or missing references)
            //IL_017c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0181: Unknown result type (might be due to invalid IL or missing references)
            //IL_01d9: Unknown result type (might be due to invalid IL or missing references)
            //IL_01e2: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f0: Unknown result type (might be due to invalid IL or missing references)
            //IL_01f6: Unknown result type (might be due to invalid IL or missing references)
            //IL_0219: Unknown result type (might be due to invalid IL or missing references)
            //IL_0223: Unknown result type (might be due to invalid IL or missing references)
            //IL_0237: Unknown result type (might be due to invalid IL or missing references)
            //IL_023c: Unknown result type (might be due to invalid IL or missing references)
            //IL_0241: Unknown result type (might be due to invalid IL or missing references)
            TileMaterial byTileId = TileMaterials.GetByTileId(collision.Tile.type);
            Vector2 vector = velocity * byTileId.GolfPhysics.SideImpactDampening;
            Vector2 vector2 = collision.Normal * Vector2.Dot(velocity, collision.Normal) * (byTileId.GolfPhysics.DirectImpactDampening - byTileId.GolfPhysics.SideImpactDampening);
            velocity = vector + vector2;
            Projectile projectile = collision.Entity as Projectile;
            switch (collision.Tile.type)
            {
            case 421:
            case 422:
            {
                float num2 = 2.5f * collision.TimeScale;
                Vector2 vector3 = default(Vector2);
                ((Vector2)(ref vector3))._002Ector(0f - collision.Normal.Y, collision.Normal.X);
                if (collision.Tile.type == 422)
                {
                    vector3 = -vector3;
                }
                float num3 = Vector2.Dot(velocity, vector3);
                if (num3 < num2)
                {
                    velocity += vector3 * MathHelper.Clamp(num2 - num3, 0f, num2 * 0.5f);
                }
                break;
            }
            case 476:
            {
                float num = ((Vector2)(ref velocity)).Length() / collision.TimeScale;
                if (!(collision.Normal.Y > -0.01f) && !(num > 100f))
                {
                    velocity *= 0f;
                    if (projectile != null && projectile.active)
                    {
                        PutBallInCup(projectile, collision);
                    }
                }
                break;
            }
            }
            if (projectile != null && velocity.Y < -0.3f && velocity.Y > -2f && ((Vector2)(ref velocity)).Length() > 1f)
            {
                Dust dust = Dust.NewDustPerfect(collision.Entity.Center, 31, collision.Normal, 127);
                dust.scale = 0.7f;
                dust.fadeIn = 1f;
                dust.velocity = dust.velocity * 0.5f + Main.rand.NextVector2CircularEdge(0.5f, 0.4f);
            }
        }
References Terraria.Entity.active, Terraria.GameContent.Metadata.TileMaterials.GetByTileId(), Terraria.Dust.NewDustPerfect(), Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup(), and Terraria.Main.rand.