TModLoader: Terraria.Player.HurtModifiers.ToHurtInfo
ToHurtInfo()
HurtInfo Terraria.Player.HurtModifiers.ToHurtInfo (int damage, int defense, float defenseEffectiveness, float knockback, bool knockbackImmune) inline
        {
            HurtInfo hurtInfo2 = new HurtInfo();
            hurtInfo2.DamageSource = DamageSource;
            hurtInfo2.PvP = PvP;
            hurtInfo2.CooldownCounter = CooldownCounter;
            hurtInfo2.Dodgeable = Dodgeable;
            hurtInfo2.HitDirection = HitDirectionOverride ?? HitDirection;
            hurtInfo2.SourceDamage = (int)SourceDamage.ApplyTo(damage);
            hurtInfo2.Damage = (int)GetDamage(damage, defense, defenseEffectiveness);
            hurtInfo2.Knockback = GetKnockback(knockback, knockbackImmune);
            hurtInfo2.DustDisabled = _dustDisabled;
            hurtInfo2.SoundDisabled = _soundDisabled;
            HurtInfo hurtInfo = hurtInfo2;
            this.ModifyHurtInfo?.Invoke(ref hurtInfo);
            this.ModifyHurtInfo = null;
            return hurtInfo;
        }
References Terraria.Player.HurtModifiers._dustDisabled, Terraria.Player.HurtModifiers._soundDisabled, Terraria.ModLoader.StatModifier.ApplyTo(), Terraria.Player.HurtModifiers.CooldownCounter, Terraria.Player.HurtModifiers.DamageSource, Terraria.Player.HurtModifiers.Dodgeable, Terraria.Player.HurtModifiers.GetDamage(), Terraria.Player.HurtModifiers.GetKnockback(), Terraria.Player.HurtModifiers.HitDirection, Terraria.Player.HurtModifiers.HitDirectionOverride, Terraria.Player.HurtModifiers.PvP, and Terraria.Player.HurtModifiers.SourceDamage.