TModLoader: Terraria.ModLoader.Engine.Steam.SetAppId
SetAppId()
static void Terraria.ModLoader.Engine.Steam.SetAppId (AppId_t appId) inline static package
    {
        string steam_appid_path = "steam_appid.txt";
        if (Environment.GetEnvironmentVariable("SteamClientLaunch") != "1" || SteamedWraps.FamilyShared || InstallVerifier.DistributionPlatform == DistributionPlatform.GoG)
        {
            File.WriteAllText(steam_appid_path, ((object)(AppId_t)(ref appId)).ToString());
            return;
        }
        try
        {
            File.Delete(steam_appid_path);
        }
        catch (IOException)
        {
        }
        if (!(Environment.GetEnvironmentVariable("SteamAppId") != ((object)(AppId_t)(ref appId)).ToString()))
        {
            return;
        }
        throw new Exception("Cannot overwrite steam env. SteamAppId=" + Environment.GetEnvironmentVariable("SteamAppId"));
    }
References Terraria.ModLoader.Engine.InstallVerifier.DistributionPlatform, Terraria.ModLoader.Environment, and Terraria.Social.Steam.SteamedWraps.FamilyShared.
Referenced by Terraria.Social.Steam.CoreSocialModule.Initialize(), Terraria.ModLoader.Engine.TerrariaSteamClient.Run(), and Terraria.Social.Steam.SteamedWraps.TryInitViaGameServer().