TModLoader: Terraria.ModLoader.Engine.Steam.PostInit
PostInit()
static void Terraria.ModLoader.Engine.Steam.PostInit () inline static package
Definition at line 41 of file Steam.cs.
    {
        RecalculateAvailableSteamCloudStorage();
        Logging.Terraria.Info((object)("Steam Cloud Quota: " + UIMemoryBar.SizeSuffix((long)lastAvailableSteamCloudStorage) + " available"));
        string branchName = default(string);
        bool OnBetaBranch = SteamApps.GetCurrentBetaName(ref branchName, 1000);
        Logging.tML.Info((object)("Steam beta branch: " + (OnBetaBranch ? branchName : "None")));
    }
References Terraria.ModLoader.Engine.Steam.lastAvailableSteamCloudStorage, Terraria.ModLoader.Engine.Steam.RecalculateAvailableSteamCloudStorage(), Terraria.ModLoader.UI.UIMemoryBar.SizeSuffix(), Terraria.ModLoader.Logging.Terraria, and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.Social.SocialAPI.LoadSteam().