TModLoader: Terraria.GameContent.Bestiary.BestiaryDatabase.Register
Register() [1/3]
BestiaryEntry Terraria.GameContent.Bestiary.BestiaryDatabase.Register (BestiaryEntry entry) inline
Definition at line 33 of file BestiaryDatabase.cs.
    {
        _entries.Add(entry);
        for (int i = 0; i < entry.Info.Count; i++)
        {
            if (entry.Info[i] is NPCNetIdBestiaryInfoElement nPCNetIdBestiaryInfoElement)
            {
                _byNpcId[nPCNetIdBestiaryInfoElement.NetId] = entry;
            }
        }
        Mod mod = ContentSamples.NpcsByNetId[((NPCNetIdBestiaryInfoElement)entry.Info[0]).NetId].ModNPC?.Mod;
        if (mod == null)
        {
            _vanillaEntries.Add(entry);
        }
        else if (_byMod.ContainsKey(mod))
        {
            _byMod[mod].Add(entry);
        }
        else
        {
            _byMod.Add(mod, new List<BestiaryEntry> { entry });
        }
        return entry;
    }
References Terraria.GameContent.Bestiary.BestiaryDatabase._byMod, Terraria.GameContent.Bestiary.BestiaryDatabase._byNpcId, Terraria.GameContent.Bestiary.BestiaryDatabase._entries, Terraria.GameContent.Bestiary.BestiaryDatabase._vanillaEntries, Terraria.GameContent.Bestiary.BestiaryEntry.Info, and Terraria.ID.ContentSamples.NpcsByNetId.
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Register(), Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.Register(), and Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.RegisterSortSteps().