TModLoader: Terraria.ModLoader.Config.UI.CollectionElement.Update
Update()
override void Terraria.ModLoader.Config.UI.CollectionElement.Update (GameTime gameTime) inline virtual inherited
Reimplemented from Terraria.UI.UIElement.
Definition at line 196 of file CollectionElement.cs.
    {
        base.Update(gameTime);
        if (!pendingChanges)
        {
            return;
        }
        pendingChanges = false;
        if (CanAdd)
        {
            RemoveChild(initializeButton);
            RemoveChild(addButton);
            RemoveChild(deleteButton);
        }
        RemoveChild(expandButton);
        RemoveChild(upDownButton);
        RemoveChild(DataListElement);
        if (Data == null)
        {
            Append(initializeButton);
            return;
        }
        if (CanAdd)
        {
            Append(addButton);
            Append(deleteButton);
        }
        Append(expandButton);
        if (expanded)
        {
            Append(upDownButton);
            Append(DataListElement);
            expandButton.HoverText = Language.GetTextValue("tModLoader.ModConfigCollapse");
            expandButton.SetImage(base.ExpandedTexture);
        }
        else
        {
            expandButton.HoverText = Language.GetTextValue("tModLoader.ModConfigExpand");
            expandButton.SetImage(base.CollapsedTexture);
        }
    }
References Terraria.ModLoader.Config.UI.CollectionElement.addButton, Terraria.UI.UIElement.Append(), Terraria.ModLoader.Config.UI.CollectionElement.CanAdd, Terraria.ModLoader.Config.UI.CollectionElement.Data, Terraria.ModLoader.Config.UI.CollectionElement.DataListElement, Terraria.ModLoader.Config.UI.CollectionElement.deleteButton, Terraria.ModLoader.Config.UI.CollectionElement.expandButton, Terraria.ModLoader.Config.UI.CollectionElement.expanded, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.Config.UI.CollectionElement.initializeButton, Terraria.ModLoader.Config.UI.ConfigElement< T >.List, Terraria.ModLoader.Config.UI.CollectionElement.pendingChanges, Terraria.UI.UIElement.RemoveChild(), Terraria.GameContent.UI.Elements.UIImage.SetImage(), and Terraria.ModLoader.Config.UI.CollectionElement.upDownButton.