TModLoader: Terraria.ModLoader.Config.UI.CollectionElement.OnBind
OnBind()
override void Terraria.ModLoader.Config.UI.CollectionElement.OnBind () inline virtual inherited
Reimplemented from Terraria.ModLoader.Config.UI.ConfigElement< T >.
Definition at line 45 of file CollectionElement.cs.
    {
        base.OnBind();
        ExpandAttribute expandAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<ExpandAttribute>(base.MemberInfo, base.Item, base.List);
        if (expandAttribute != null)
        {
            expanded = expandAttribute.Expand;
        }
        Data = base.MemberInfo.GetValue(base.Item);
        DefaultListValueAttribute = ConfigManager.GetCustomAttributeFromMemberThenMemberType<DefaultListValueAttribute>(base.MemberInfo, null, null);
        MaxHeight.Set(300f, 0f);
        DataListElement = new UIElement();
        DataListElement.Width.Set(-10f, 1f);
        DataListElement.Left.Set(10f, 0f);
        DataListElement.Height.Set(-30f, 1f);
        DataListElement.Top.Set(30f, 0f);
        if (Data != null && expanded)
        {
            Append(DataListElement);
        }
        DataListElement.OverflowHidden = true;
        DataList = new NestedUIList();
        DataList.Width.Set(-20f, 1f);
        DataList.Left.Set(0f, 0f);
        DataList.Height.Set(0f, 1f);
        DataList.ListPadding = 5f;
        DataListElement.Append(DataList);
        UIScrollbar scrollbar = new UIScrollbar();
        scrollbar.SetView(100f, 1000f);
        scrollbar.Height.Set(-16f, 1f);
        scrollbar.Top.Set(6f, 0f);
        scrollbar.Left.Pixels -= 3f;
        scrollbar.HAlign = 1f;
        DataList.SetScrollbar(scrollbar);
        DataListElement.Append(scrollbar);
        PrepareTypes();
        SetupList();
        if (CanAdd)
        {
            initializeButton = new UIModConfigHoverImage(base.PlayTexture, Language.GetTextValue("tModLoader.ModConfigInitialize"));
            initializeButton.Top.Pixels += 4f;
            initializeButton.Left.Pixels -= 3f;
            initializeButton.HAlign = 1f;
            initializeButton.OnLeftClick += delegate
            {
                SoundEngine.PlaySound(in SoundID.Tink);
                InitializeCollection();
                SetupList();
                Interface.modConfig.RecalculateChildren();
                Interface.modConfig.SetPendingChanges();
                expanded = true;
                pendingChanges = true;
            };
            addButton = new UIModConfigHoverImage(base.PlusTexture, Language.GetTextValue("tModLoader.ModConfigAdd"));
            addButton.Top.Set(4f, 0f);
            addButton.Left.Set(-52f, 1f);
            addButton.OnLeftClick += delegate
            {
                SoundEngine.PlaySound(in SoundID.Tink);
                AddItem();
                SetupList();
                Interface.modConfig.RecalculateChildren();
                Interface.modConfig.SetPendingChanges();
                expanded = true;
                pendingChanges = true;
            };
            deleteButton = new UIModConfigHoverImage(base.DeleteTexture, Language.GetTextValue("tModLoader.ModConfigClear"));
            deleteButton.Top.Set(4f, 0f);
            deleteButton.Left.Set(-25f, 1f);
            deleteButton.OnLeftClick += delegate
            {
                SoundEngine.PlaySound(in SoundID.Tink);
                if (base.NullAllowed)
                {
                    NullCollection();
                }
                else
                {
                    ClearCollection();
                }
                SetupList();
                Interface.modConfig.RecalculateChildren();
                Interface.modConfig.SetPendingChanges();
                pendingChanges = true;
            };
        }
        expandButton = new UIModConfigHoverImage(expanded ? base.ExpandedTexture : base.CollapsedTexture, expanded ? Language.GetTextValue("tModLoader.ModConfigCollapse") : Language.GetTextValue("tModLoader.ModConfigExpand"));
        expandButton.Top.Set(4f, 0f);
        expandButton.Left.Set(-79f, 1f);
        expandButton.OnLeftClick += delegate
        {
            expanded = !expanded;
            pendingChanges = true;
        };
        upDownButton = new UIModConfigHoverImageSplit(base.UpDownTexture, Language.GetTextValue("tModLoader.ModConfigScaleUp"), Language.GetTextValue("tModLoader.ModConfigScaleDown"));
        upDownButton.Top.Set(4f, 0f);
        upDownButton.Left.Set(-106f, 1f);
        upDownButton.OnLeftClick += delegate(UIMouseEvent a, UIElement b)
        {
            //IL_0009: Unknown result type (might be due to invalid IL or missing references)
            //IL_000e: Unknown result type (might be due to invalid IL or missing references)
            //IL_001a: Unknown result type (might be due to invalid IL or missing references)
            //IL_0020: Unknown result type (might be due to invalid IL or missing references)
            Rectangle val = b.GetDimensions().ToRectangle();
            if (a.MousePosition.Y < (float)(val.Y + val.Height / 2))
            {
                Scale = Math.Min(2f, Scale + 0.5f);
            }
            else
            {
                Scale = Math.Max(1f, Scale - 0.5f);
            }
        };
        pendingChanges = true;
        Recalculate();
    }
References Terraria.UI.UIElement.UIElement(), Terraria.ModLoader.Config.UI.CollectionElement.addButton, Terraria.ModLoader.Config.UI.CollectionElement.AddItem(), Terraria.UI.UIElement.Append(), Terraria.ModLoader.Config.UI.CollectionElement.CanAdd, Terraria.ModLoader.Config.UI.CollectionElement.ClearCollection(), Terraria.ModLoader.Config.UI.CollectionElement.Data, Terraria.ModLoader.Config.UI.CollectionElement.DataList, Terraria.ModLoader.Config.UI.CollectionElement.DataListElement, Terraria.ModLoader.Config.UI.CollectionElement.deleteButton, Terraria.ModLoader.Config.UI.CollectionElement.expandButton, Terraria.ModLoader.Config.UI.CollectionElement.expanded, Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.Height, Terraria.ModLoader.Config.UI.CollectionElement.initializeButton, Terraria.ModLoader.Config.UI.CollectionElement.InitializeCollection(), Terraria.UI.UIElement.Left, Terraria.ModLoader.Config.UI.ConfigElement< T >.List, Terraria.UI.UIElement.MaxHeight, Terraria.ModLoader.UI.Interface.modConfig, Terraria.ModLoader.Config.UI.CollectionElement.NullCollection(), Terraria.ModLoader.Config.UI.CollectionElement.pendingChanges, Terraria.Audio.SoundEngine.PlaySound(), Terraria.ModLoader.Config.UI.CollectionElement.PrepareTypes(), Terraria.ModLoader.Config.UI.CollectionElement.Recalculate(), Terraria.ModLoader.Config.UI.CollectionElement.Scale, Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.ModLoader.Config.UI.CollectionElement.SetupList(), Terraria.ID.SoundID.Tink, Terraria.UI.UIElement.Top, Terraria.ModLoader.Config.UI.CollectionElement.upDownButton, and Terraria.UI.UIElement.Width.