TModLoader: Terraria.ModLoader.Config.UI.CollectionElement.Recalculate
Recalculate()
override void Terraria.ModLoader.Config.UI.CollectionElement.Recalculate () inline virtual inherited
Reimplemented from Terraria.UI.UIElement.
Definition at line 238 of file CollectionElement.cs.
    {
        base.Recalculate();
        float defaultHeight = 30f;
        float h = ((DataListElement.Parent != null) ? (DataList.GetTotalHeight() + defaultHeight) : defaultHeight);
        h = Utils.Clamp(h, 30f, 300f * Scale);
        MaxHeight.Set(300f * Scale, 0f);
        Height.Set(h, 0f);
        if (base.Parent != null && base.Parent is UISortableElement)
        {
            base.Parent.Height.Set(h, 0f);
        }
    }
References Terraria.ModLoader.Config.UI.CollectionElement.DataList, Terraria.GameContent.UI.Elements.UIList.GetTotalHeight(), Terraria.UI.UIElement.Height, Terraria.ModLoader.Config.UI.ConfigElement< T >.List, Terraria.UI.UIElement.MaxHeight, Terraria.ModLoader.Config.UI.CollectionElement.Scale, and Terraria.UI.StyleDimension.Set().
Referenced by Terraria.ModLoader.Config.UI.CollectionElement.OnBind().