TModLoader: Terraria.ModLoader.Config.UI.CollectionElement.CreateCollectionElementInstance
CreateCollectionElementInstance()
object Terraria.ModLoader.Config.UI.CollectionElement.CreateCollectionElementInstance (Type type) inline protected inherited
Definition at line 162 of file CollectionElement.cs.
    {
        object toAdd;
        if (DefaultListValueAttribute != null)
        {
            toAdd = DefaultListValueAttribute.Value;
        }
        else
        {
            toAdd = ConfigManager.AlternateCreateInstance(type);
            if (!type.IsValueType && type != typeof(string))
            {
                JsonConvert.PopulateObject(JsonDefaultListValueAttribute?.Json ?? "{}", toAdd, ConfigManager.serializerSettings);
            }
        }
        return toAdd;
    }
References Terraria.ModLoader.Config.ConfigManager.AlternateCreateInstance(), Terraria.ModLoader.Config.UI.ConfigElement< T >.List, Terraria.ModLoader.Config.ConfigManager.serializerSettings, and Terraria.ModLoader.Config.DefaultListValueAttribute.Value.
Referenced by Terraria.ModLoader.Config.UI.DictionaryElement.AddItem(), and Terraria.ModLoader.Config.UI.ListElement.AddItem().