TModLoader: Terraria.GameContent.Shaders.WaterShaderData.DrawWaves
DrawWaves()
void Terraria.GameContent.Shaders.WaterShaderData.DrawWaves () inline private
    {
        //IL_0000: Unknown result type (might be due to invalid IL or missing references)
        //IL_0005: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0019: Unknown result type (might be due to invalid IL or missing references)
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_002c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0036: Unknown result type (might be due to invalid IL or missing references)
        //IL_003b: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_08bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c2: Unknown result type (might be due to invalid IL or missing references)
        //IL_08c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_08d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_08db: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ea: Unknown result type (might be due to invalid IL or missing references)
        //IL_08ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_0901: Unknown result type (might be due to invalid IL or missing references)
        //IL_0908: Unknown result type (might be due to invalid IL or missing references)
        //IL_090f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0916: Unknown result type (might be due to invalid IL or missing references)
        //IL_091d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0927: Unknown result type (might be due to invalid IL or missing references)
        //IL_092c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0940: Unknown result type (might be due to invalid IL or missing references)
        //IL_094a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0954: Unknown result type (might be due to invalid IL or missing references)
        //IL_095e: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0100: Unknown result type (might be due to invalid IL or missing references)
        //IL_010d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0112: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_0441: Unknown result type (might be due to invalid IL or missing references)
        //IL_0442: Unknown result type (might be due to invalid IL or missing references)
        //IL_044c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0451: Unknown result type (might be due to invalid IL or missing references)
        //IL_0453: Unknown result type (might be due to invalid IL or missing references)
        //IL_0460: Unknown result type (might be due to invalid IL or missing references)
        //IL_0465: Unknown result type (might be due to invalid IL or missing references)
        //IL_0467: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0135: Unknown result type (might be due to invalid IL or missing references)
        //IL_013a: Unknown result type (might be due to invalid IL or missing references)
        //IL_013e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0153: Unknown result type (might be due to invalid IL or missing references)
        //IL_0159: Unknown result type (might be due to invalid IL or missing references)
        //IL_015b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0170: Unknown result type (might be due to invalid IL or missing references)
        //IL_0175: Unknown result type (might be due to invalid IL or missing references)
        //IL_017a: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c1: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c8: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f2: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0209: Unknown result type (might be due to invalid IL or missing references)
        //IL_020e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0482: Unknown result type (might be due to invalid IL or missing references)
        //IL_0487: Unknown result type (might be due to invalid IL or missing references)
        //IL_0488: Unknown result type (might be due to invalid IL or missing references)
        //IL_048d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_04be: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d1: Unknown result type (might be due to invalid IL or missing references)
        //IL_024b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0252: Unknown result type (might be due to invalid IL or missing references)
        //IL_0275: Unknown result type (might be due to invalid IL or missing references)
        //IL_027f: Unknown result type (might be due to invalid IL or missing references)
        //IL_028e: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_02bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_050e: Unknown result type (might be due to invalid IL or missing references)
        //IL_052a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0562: Unknown result type (might be due to invalid IL or missing references)
        //IL_056c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0571: Unknown result type (might be due to invalid IL or missing references)
        //IL_0584: Unknown result type (might be due to invalid IL or missing references)
        //IL_059f: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_06f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_06fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0702: Unknown result type (might be due to invalid IL or missing references)
        //IL_0704: Unknown result type (might be due to invalid IL or missing references)
        //IL_070b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0710: Unknown result type (might be due to invalid IL or missing references)
        //IL_0712: Unknown result type (might be due to invalid IL or missing references)
        //IL_033f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0344: Unknown result type (might be due to invalid IL or missing references)
        //IL_0348: Unknown result type (might be due to invalid IL or missing references)
        //IL_034d: Unknown result type (might be due to invalid IL or missing references)
        //IL_05de: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_05e7: Unknown result type (might be due to invalid IL or missing references)
        //IL_05ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_0774: Unknown result type (might be due to invalid IL or missing references)
        //IL_0779: Unknown result type (might be due to invalid IL or missing references)
        //IL_077a: Unknown result type (might be due to invalid IL or missing references)
        //IL_077f: Unknown result type (might be due to invalid IL or missing references)
        //IL_07a8: Unknown result type (might be due to invalid IL or missing references)
        //IL_07ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_072c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0746: Unknown result type (might be due to invalid IL or missing references)
        //IL_0382: Unknown result type (might be due to invalid IL or missing references)
        //IL_038c: Unknown result type (might be due to invalid IL or missing references)
        //IL_03b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_080e: Unknown result type (might be due to invalid IL or missing references)
        //IL_081e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0832: Unknown result type (might be due to invalid IL or missing references)
        //IL_083c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0841: Unknown result type (might be due to invalid IL or missing references)
        //IL_0854: Unknown result type (might be due to invalid IL or missing references)
        //IL_086f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0625: Unknown result type (might be due to invalid IL or missing references)
        //IL_0641: Unknown result type (might be due to invalid IL or missing references)
        Vector2 screenPosition = Main.screenPosition;
        Vector2 vector = (Vector2)(Main.drawToScreen ? Vector2.Zero : new Vector2((float)Main.offScreenRange, (float)Main.offScreenRange));
        Vector2 vector2 = -_lastDistortionDrawOffset / 0.25f + vector;
        TileBatch tileBatch = Main.tileBatch;
        _ = ((Game)Main.instance).GraphicsDevice;
        Vector2 dimensions = default(Vector2);
        ((Vector2)(ref dimensions))._002Ector((float)Main.screenWidth, (float)Main.screenHeight);
        Vector2 vector3 = default(Vector2);
        ((Vector2)(ref vector3))._002Ector(16f, 16f);
        tileBatch.Begin();
        GameShaders.Misc["WaterDistortionObject"].Apply();
        if (_useNPCWaves)
        {
            for (int i = 0; i < 200; i++)
            {
                if (Main.npc[i] == null || !Main.npc[i].active || (!Main.npc[i].wet && Main.npc[i].wetCount == 0) || !Collision.CheckAABBvAABBCollision(screenPosition, dimensions, Main.npc[i].position - vector3, Main.npc[i].Size + vector3))
                {
                    continue;
                }
                NPC nPC = Main.npc[i];
                Vector2 vector4 = nPC.Center - vector2;
                Vector2 velocity4 = nPC.velocity;
                double radians = 0f - nPC.rotation;
                Vector2 center = default(Vector2);
                Vector2 vector5 = velocity4.RotatedBy(radians, center) / new Vector2((float)nPC.height, (float)nPC.width);
                float num = ((Vector2)(ref vector5)).LengthSquared();
                num = num * 0.3f + 0.7f * num * (1024f / (float)(nPC.height * nPC.width));
                num = Math.Min(num, 0.08f);
                float num8 = num;
                center = nPC.velocity - nPC.oldVelocity;
                num = num8 + ((Vector2)(ref center)).Length() * 0.5f;
                ((Vector2)(ref vector5)).Normalize();
                Vector2 velocity = nPC.velocity;
                ((Vector2)(ref velocity)).Normalize();
                vector4 -= velocity * 10f;
                if (!_useViscosityFilter && (nPC.honeyWet || nPC.lavaWet))
                {
                    num *= 0.3f;
                }
                if (nPC.wet)
                {
                    tileBatch.Draw(TextureAssets.MagicPixel.Value, new Vector4(vector4.X, vector4.Y, (float)nPC.width * 2f, (float)nPC.height * 2f) * 0.25f, null, new VertexColors(new Color(vector5.X * 0.5f + 0.5f, vector5.Y * 0.5f + 0.5f, 0.5f * num)), new Vector2((float)TextureAssets.MagicPixel.Width() / 2f, (float)TextureAssets.MagicPixel.Height() / 2f), (SpriteEffects)0, nPC.rotation);
                }
                if (nPC.wetCount != 0)
                {
                    num = ((Vector2)(ref nPC.velocity)).Length();
                    num = 0.195f * (float)Math.Sqrt(num);
                    float num2 = 5f;
                    if (!nPC.wet)
                    {
                        num2 = -20f;
                    }
                    QueueRipple(nPC.Center + velocity * num2, new Color(0.5f, (nPC.wet ? num : (0f - num)) * 0.5f + 0.5f, 0f, 1f) * 0.5f, new Vector2((float)nPC.width, (float)nPC.height * ((float)(int)nPC.wetCount / 9f)) * MathHelper.Clamp(num * 10f, 0f, 1f), RippleShape.Circle);
                }
            }
        }
        if (_usePlayerWaves)
        {
            for (int j = 0; j < 255; j++)
            {
                if (Main.player[j] == null || !Main.player[j].active || (!Main.player[j].wet && Main.player[j].wetCount == 0) || !Collision.CheckAABBvAABBCollision(screenPosition, dimensions, Main.player[j].position - vector3, Main.player[j].Size + vector3))
                {
                    continue;
                }
                Player player = Main.player[j];
                Vector2 vector6 = player.Center - vector2;
                float num3 = ((Vector2)(ref player.velocity)).Length();
                num3 = 0.05f * (float)Math.Sqrt(num3);
                Vector2 velocity2 = player.velocity;
                ((Vector2)(ref velocity2)).Normalize();
                vector6 -= velocity2 * 10f;
                if (!_useViscosityFilter && (player.honeyWet || player.lavaWet))
                {
                    num3 *= 0.3f;
                }
                if (player.wet)
                {
                    tileBatch.Draw(TextureAssets.MagicPixel.Value, new Vector4(vector6.X - (float)player.width * 2f * 0.5f, vector6.Y - (float)player.height * 2f * 0.5f, (float)player.width * 2f, (float)player.height * 2f) * 0.25f, new VertexColors(new Color(velocity2.X * 0.5f + 0.5f, velocity2.Y * 0.5f + 0.5f, 0.5f * num3)));
                }
                if (player.wetCount != 0)
                {
                    float num4 = 5f;
                    if (!player.wet)
                    {
                        num4 = -20f;
                    }
                    num3 *= 3f;
                    QueueRipple(player.Center + velocity2 * num4, player.wet ? num3 : (0f - num3), new Vector2((float)player.width, (float)player.height * ((float)(int)player.wetCount / 9f)) * MathHelper.Clamp(num3 * 10f, 0f, 1f), RippleShape.Circle);
                }
            }
        }
        if (_useProjectileWaves)
        {
            for (int k = 0; k < 1000; k++)
            {
                Projectile projectile = Main.projectile[k];
                if (projectile.wet && !projectile.lavaWet)
                {
                    _ = projectile.honeyWet;
                }
                bool flag = projectile.lavaWet;
                bool flag2 = projectile.honeyWet;
                bool flag3 = projectile.wet;
                if (projectile.ignoreWater)
                {
                    flag3 = true;
                }
                if (!(projectile != null && projectile.active && ProjectileID.Sets.CanDistortWater[projectile.type] && flag3) || ProjectileID.Sets.NoLiquidDistortion[projectile.type] || !Collision.CheckAABBvAABBCollision(screenPosition, dimensions, projectile.position - vector3, projectile.Size + vector3))
                {
                    continue;
                }
                if (projectile.ignoreWater)
                {
                    bool num9 = Collision.LavaCollision(projectile.position, projectile.width, projectile.height);
                    flag = Collision.WetCollision(projectile.position, projectile.width, projectile.height);
                    flag2 = Collision.honey;
                    if (!(num9 || flag || flag2))
                    {
                        continue;
                    }
                }
                Vector2 vector7 = projectile.Center - vector2;
                float num5 = ((Vector2)(ref projectile.velocity)).Length();
                num5 = 2f * (float)Math.Sqrt(0.05f * num5);
                Vector2 velocity3 = projectile.velocity;
                ((Vector2)(ref velocity3)).Normalize();
                if (!_useViscosityFilter && (flag2 || flag))
                {
                    num5 *= 0.3f;
                }
                float num6 = Math.Max(12f, (float)projectile.width * 0.75f);
                float num7 = Math.Max(12f, (float)projectile.height * 0.75f);
                tileBatch.Draw(TextureAssets.MagicPixel.Value, new Vector4(vector7.X - num6 * 0.5f, vector7.Y - num7 * 0.5f, num6, num7) * 0.25f, new VertexColors(new Color(velocity3.X * 0.5f + 0.5f, velocity3.Y * 0.5f + 0.5f, num5 * 0.5f)));
            }
        }
        tileBatch.End();
        if (_useRippleWaves)
        {
            tileBatch.Begin();
            for (int l = 0; l < _rippleQueueCount; l++)
            {
                Vector2 vector8 = _rippleQueue[l].Position - vector2;
                Vector2 size = _rippleQueue[l].Size;
                Rectangle sourceRectangle = _rippleQueue[l].SourceRectangle;
                Texture2D value = _rippleShapeTexture.Value;
                tileBatch.Draw(value, new Vector4(vector8.X, vector8.Y, size.X, size.Y) * 0.25f, sourceRectangle, new VertexColors(_rippleQueue[l].WaveData), new Vector2((float)(sourceRectangle.Width / 2), (float)(sourceRectangle.Height / 2)), (SpriteEffects)0, _rippleQueue[l].Rotation);
            }
            tileBatch.End();
        }
        _rippleQueueCount = 0;
        if (_useCustomWaves && this.OnWaveDraw != null)
        {
            tileBatch.Begin();
            this.OnWaveDraw(tileBatch);
            tileBatch.End();
        }
    }
References Terraria.GameContent.Shaders.WaterShaderData._lastDistortionDrawOffset, Terraria.GameContent.Shaders.WaterShaderData._rippleQueue, Terraria.GameContent.Shaders.WaterShaderData._rippleQueueCount, Terraria.GameContent.Shaders.WaterShaderData._rippleShapeTexture, Terraria.GameContent.Shaders.WaterShaderData._useCustomWaves, Terraria.GameContent.Shaders.WaterShaderData._useNPCWaves, Terraria.GameContent.Shaders.WaterShaderData._usePlayerWaves, Terraria.GameContent.Shaders.WaterShaderData._useProjectileWaves, Terraria.GameContent.Shaders.WaterShaderData._useRippleWaves, Terraria.GameContent.Shaders.WaterShaderData._useViscosityFilter, Terraria.Entity.active, Terraria.Graphics.TileBatch.Begin(), Terraria.ID.ProjectileID.Sets.CanDistortWater, Terraria.Entity.Center, Terraria.Collision.CheckAABBvAABBCollision(), Terraria.Graphics.Light.Color, Terraria.Graphics.TileBatch.Draw(), Terraria.Main.drawToScreen, Terraria.Graphics.TileBatch.End(), Terraria.Entity.height, Terraria.Collision.honey, Terraria.Entity.honeyWet, Terraria.Projectile.ignoreWater, Terraria.Main.instance, Terraria.Collision.LavaCollision(), Terraria.Entity.lavaWet, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.ID.ProjectileID.Sets.NoLiquidDistortion, Terraria.Main.npc, Terraria.Main.offScreenRange, Terraria.GameContent.Shaders.WaterShaderData.OnWaveDraw, Terraria.Main.player, Terraria.GameContent.Shaders.WaterShaderData.Ripple.Position, Terraria.Entity.position, Terraria.Main.projectile, Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.GameContent.Shaders.WaterShaderData.Ripple.Size, Terraria.Entity.Size, Terraria.GameContent.Shaders.WaterShaderData.Ripple.SourceRectangle, Terraria.Main.tileBatch, Terraria.Projectile.type, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Collision.WetCollision(), Terraria.Entity.wetCount, and Terraria.Entity.width.
Referenced by Terraria.GameContent.Shaders.WaterShaderData.StepLiquids().