TModLoader: Terraria.GameContent.Shaders.WaterShaderData.StepLiquids
StepLiquids()
void Terraria.GameContent.Shaders.WaterShaderData.StepLiquids () inline private
Definition at line 135 of file WaterShaderData.cs.
    {
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_001a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0026: Unknown result type (might be due to invalid IL or missing references)
        //IL_0027: Unknown result type (might be due to invalid IL or missing references)
        //IL_0028: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0032: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00bf: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c7: Unknown result type (might be due to invalid IL or missing references)
        //IL_00db: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ed: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_00f9: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0109: Unknown result type (might be due to invalid IL or missing references)
        //IL_0110: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0134: Unknown result type (might be due to invalid IL or missing references)
        //IL_0158: Unknown result type (might be due to invalid IL or missing references)
        //IL_015d: Unknown result type (might be due to invalid IL or missing references)
        //IL_006d: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_01d6: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01eb: Unknown result type (might be due to invalid IL or missing references)
        //IL_01f4: Unknown result type (might be due to invalid IL or missing references)
        //IL_01fc: Unknown result type (might be due to invalid IL or missing references)
        //IL_0204: Unknown result type (might be due to invalid IL or missing references)
        //IL_0211: Unknown result type (might be due to invalid IL or missing references)
        //IL_0218: Unknown result type (might be due to invalid IL or missing references)
        //IL_021d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0228: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        //IL_0241: Unknown result type (might be due to invalid IL or missing references)
        //IL_0248: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0258: Unknown result type (might be due to invalid IL or missing references)
        //IL_0269: Unknown result type (might be due to invalid IL or missing references)
        //IL_0290: Unknown result type (might be due to invalid IL or missing references)
        //IL_0292: Unknown result type (might be due to invalid IL or missing references)
        //IL_0299: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02a5: Unknown result type (might be due to invalid IL or missing references)
        _isWaveBufferDirty = true;
        Vector2 vector = (Vector2)(Main.drawToScreen ? Vector2.Zero : new Vector2((float)Main.offScreenRange, (float)Main.offScreenRange));
        Vector2 vector2 = vector - Main.screenPosition;
        TileBatch tileBatch = Main.tileBatch;
        GraphicsDevice graphicsDevice = ((Game)Main.instance).GraphicsDevice;
        graphicsDevice.SetRenderTarget(_distortionTarget);
        if (_clearNextFrame)
        {
            graphicsDevice.Clear(new Color(0.5f, 0.5f, 0f, 1f));
            _clearNextFrame = false;
        }
        DrawWaves();
        graphicsDevice.SetRenderTarget(_distortionTargetSwap);
        graphicsDevice.Clear(new Color(0.5f, 0.5f, 0.5f, 1f));
        Main.tileBatch.Begin();
        vector2 *= 0.25f;
        vector2.X = (float)Math.Floor(vector2.X);
        vector2.Y = (float)Math.Floor(vector2.Y);
        Vector2 vector3 = vector2 - _lastDistortionDrawOffset;
        _lastDistortionDrawOffset = vector2;
        tileBatch.Draw((Texture2D)(object)_distortionTarget, new Vector4(vector3.X, vector3.Y, (float)((Texture2D)_distortionTarget).Width, (float)((Texture2D)_distortionTarget).Height), new VertexColors(Color.White));
        GameShaders.Misc["WaterProcessor"].Apply(new DrawData((Texture2D)(object)_distortionTarget, Vector2.Zero, Color.White));
        tileBatch.End();
        RenderTarget2D distortionTarget = _distortionTarget;
        _distortionTarget = _distortionTargetSwap;
        _distortionTargetSwap = distortionTarget;
        if (_useViscosityFilter)
        {
            LiquidRenderer.Instance.SetWaveMaskData(ref _viscosityMaskChain[_activeViscosityMask]);
            tileBatch.Begin();
            Rectangle cachedDrawArea = LiquidRenderer.Instance.GetCachedDrawArea();
            Rectangle rectangle = default(Rectangle);
            ((Rectangle)(ref rectangle))._002Ector(0, 0, cachedDrawArea.Height, cachedDrawArea.Width);
            Vector4 destination = default(Vector4);
            ((Vector4)(ref destination))._002Ector((float)(cachedDrawArea.X + cachedDrawArea.Width), (float)cachedDrawArea.Y, (float)cachedDrawArea.Height, (float)cachedDrawArea.Width);
            destination *= 16f;
            destination.X -= vector.X;
            destination.Y -= vector.Y;
            destination *= 0.25f;
            destination.X += vector2.X;
            destination.Y += vector2.Y;
            graphicsDevice.SamplerStates[0] = SamplerState.PointClamp;
            tileBatch.Draw(_viscosityMaskChain[_activeViscosityMask], destination, rectangle, new VertexColors(Color.White), rectangle.Size(), (SpriteEffects)1, -(float)Math.PI / 2f);
            tileBatch.End();
            _activeViscosityMask++;
            _activeViscosityMask %= _viscosityMaskChain.Length;
        }
        graphicsDevice.SetRenderTarget((RenderTarget2D)null);
    }
References Terraria.GameContent.Shaders.WaterShaderData._activeViscosityMask, Terraria.GameContent.Shaders.WaterShaderData._clearNextFrame, Terraria.GameContent.Shaders.WaterShaderData._distortionTarget, Terraria.GameContent.Shaders.WaterShaderData._distortionTargetSwap, Terraria.GameContent.Shaders.WaterShaderData._isWaveBufferDirty, Terraria.GameContent.Shaders.WaterShaderData._lastDistortionDrawOffset, Terraria.GameContent.Shaders.WaterShaderData._useViscosityFilter, Terraria.GameContent.Shaders.WaterShaderData._viscosityMaskChain, Terraria.Graphics.TileBatch.Begin(), Terraria.Graphics.Light.Color, Terraria.Graphics.TileBatch.Draw(), Terraria.Main.drawToScreen, Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.Graphics.TileBatch.End(), Terraria.GameContent.Liquid.LiquidRenderer.Instance, Terraria.Main.instance, Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.Main.offScreenRange, Terraria.Main.screenPosition, and Terraria.Main.tileBatch.
Referenced by Terraria.GameContent.Shaders.WaterShaderData.PreDraw().