TModLoader: Terraria.GameContent.Generation.TrackGenerator.CreateTunnel
CreateTunnel()
TrackPlacementState Terraria.GameContent.Generation.TrackGenerator.CreateTunnel () inline private
    {
        TrackSlope trackSlope = TrackSlope.Straight;
        int num = 10;
        TrackPlacementState trackPlacementState = TrackPlacementState.Invalid;
        int x = _history[_length - 1].X;
        int y = _history[_length - 1].Y;
        for (TrackSlope trackSlope2 = TrackSlope.Up; trackSlope2 <= TrackSlope.Down; trackSlope2++)
        {
            TrackPlacementState trackPlacementState2 = TrackPlacementState.Invalid;
            for (int i = 1; i < num; i++)
            {
                trackPlacementState2 = CalculateStateForLocation(x + i * _xDirection, y + i * (int)trackSlope2);
                switch (trackPlacementState2)
                {
                default:
                    trackSlope = trackSlope2;
                    num = i;
                    trackPlacementState = trackPlacementState2;
                    break;
                case TrackPlacementState.Obstructed:
                    continue;
                case TrackPlacementState.Invalid:
                    break;
                }
                break;
            }
            if (trackPlacementState != 0 && trackPlacementState2 == TrackPlacementState.Obstructed && (trackPlacementState != TrackPlacementState.Obstructed || trackSlope != 0))
            {
                trackSlope = trackSlope2;
                num = 10;
                trackPlacementState = trackPlacementState2;
            }
        }
        if (_length == 0 || !CanSlopesTouch(_history[_length - 1].Slope, trackSlope))
        {
            RewriteSlopeDirection(_length - 1, TrackSlope.Straight);
        }
        _history[_length - 1].Mode = TrackMode.Tunnel;
        for (int j = 1; j < num; j++)
        {
            AppendToHistory(trackSlope, TrackMode.Tunnel);
        }
        return trackPlacementState;
    }
References Terraria.GameContent.Generation.TrackGenerator._history, Terraria.GameContent.Generation.TrackGenerator._length, Terraria.GameContent.Generation.TrackGenerator._xDirection, Terraria.GameContent.Generation.TrackGenerator.AppendToHistory(), Terraria.GameContent.Generation.TrackGenerator.CalculateStateForLocation(), Terraria.GameContent.Generation.TrackGenerator.CanSlopesTouch(), and Terraria.GameContent.Generation.TrackGenerator.RewriteSlopeDirection().
Referenced by Terraria.GameContent.Generation.TrackGenerator.FindPath().