TModLoader: Terraria.GameContent.UI.States.UIAchievementsMenu.Draw
Draw()
override void Terraria.GameContent.UI.States.UIAchievementsMenu.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 112 of file UIAchievementsMenu.cs.
    {
        //IL_009f: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c0: Unknown result type (might be due to invalid IL or missing references)
        //IL_00c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ca: Unknown result type (might be due to invalid IL or missing references)
        //IL_00cb: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0121: Unknown result type (might be due to invalid IL or missing references)
        //IL_013b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0145: Unknown result type (might be due to invalid IL or missing references)
        base.Draw(spriteBatch);
        for (int i = 0; i < _categoryButtons.Count; i++)
        {
            if (_categoryButtons[i].IsMouseHovering)
            {
                string text = "";
                text = i switch
                {
                    3 => Language.GetTextValue("Achievements.ChallengerCategory"),
                    1 => Language.GetTextValue("Achievements.CollectorCategory"),
                    2 => Language.GetTextValue("Achievements.ExplorerCategory"),
                    0 => Language.GetTextValue("Achievements.SlayerCategory"),
                    -1 => Language.GetTextValue("Achievements.NoCategory"),
                    _ => Language.GetTextValue("Achievements.NoCategory"),
                };
                float x = FontAssets.MouseText.Value.MeasureString(text).X;
                Vector2 vector = new Vector2((float)Main.mouseX, (float)Main.mouseY) + new Vector2(16f);
                if (vector.Y > (float)(Main.screenHeight - 30))
                {
                    vector.Y = Main.screenHeight - 30;
                }
                if (vector.X > (float)Main.screenWidth - x)
                {
                    vector.X = Main.screenWidth - 460;
                }
                Utils.DrawBorderStringFourWay(spriteBatch, FontAssets.MouseText.Value, text, vector.X, vector.Y, new Color((int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor, (int)Main.mouseTextColor), Color.Black, Vector2.Zero);
                break;
            }
        }
        SetupGamepadPoints(spriteBatch);
    }
References Terraria.GameContent.UI.States.UIAchievementsMenu._categoryButtons, Terraria.Utils.DrawBorderStringFourWay(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.IsMouseHovering, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.screenHeight, Terraria.Main.screenWidth, and Terraria.GameContent.UI.States.UIAchievementsMenu.SetupGamepadPoints().