TModLoader: Terraria.ModLoader.Core.GlobalTypeLookups.BuildPerTypeGlobalLists
BuildPerTypeGlobalLists()
static TGlobal[][] Terraria.ModLoader.Core.GlobalTypeLookups< TGlobal >.BuildPerTypeGlobalLists (TGlobal[] arr) inline static
Definition at line 212 of file GlobalTypeLookups.cs.
    {
        Dictionary<TGlobal[], TGlobal[]> dict = new Dictionary<TGlobal[], TGlobal[]>();
        TGlobal[][] lookup = new TGlobal[EntityTypeCount][];
        int type;
        for (type = 0; type < lookup.Length; type++)
        {
            if (!dict.TryGetValue(GetGlobalsForType(type), out var v))
            {
                v = CachedFilter(arr, (TGlobal g) => AppliesToType(g, type));
            }
            lookup[type] = v;
        }
        return lookup;
    }
References Terraria.ModLoader.Core.GlobalTypeLookups< TGlobal >.AppliesToType(), Terraria.ModLoader.Core.GlobalTypeLookups< TGlobal >.CachedFilter(), Terraria.ModLoader.Core.GlobalTypeLookups< TGlobal >.EntityTypeCount, and Terraria.ModLoader.Core.GlobalTypeLookups< TGlobal >.GetGlobalsForType().