TModLoader: Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition
UpdatePlayerPosition()
static void Terraria.GameContent.PressurePlateHelper.UpdatePlayerPosition (Player player) inline static
    {
        //IL_0009: Unknown result type (might be due to invalid IL or missing references)
        //IL_000a: Unknown result type (might be due to invalid IL or missing references)
        //IL_000f: Unknown result type (might be due to invalid IL or missing references)
        //IL_001b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0020: Unknown result type (might be due to invalid IL or missing references)
        //IL_0021: Unknown result type (might be due to invalid IL or missing references)
        //IL_0031: Unknown result type (might be due to invalid IL or missing references)
        //IL_0037: Unknown result type (might be due to invalid IL or missing references)
        //IL_003c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0041: Unknown result type (might be due to invalid IL or missing references)
        //IL_0047: Unknown result type (might be due to invalid IL or missing references)
        //IL_004c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0058: Unknown result type (might be due to invalid IL or missing references)
        //IL_005d: Unknown result type (might be due to invalid IL or missing references)
        //IL_005e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0064: Unknown result type (might be due to invalid IL or missing references)
        //IL_0069: Unknown result type (might be due to invalid IL or missing references)
        //IL_006f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0074: Unknown result type (might be due to invalid IL or missing references)
        //IL_0080: Unknown result type (might be due to invalid IL or missing references)
        //IL_0085: Unknown result type (might be due to invalid IL or missing references)
        //IL_0088: Unknown result type (might be due to invalid IL or missing references)
        //IL_008d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0091: Unknown result type (might be due to invalid IL or missing references)
        //IL_0098: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ad: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_010a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0111: Unknown result type (might be due to invalid IL or missing references)
        //IL_013c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0150: Unknown result type (might be due to invalid IL or missing references)
        //IL_016f: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b0: Unknown result type (might be due to invalid IL or missing references)
        //IL_01b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_01bc: Unknown result type (might be due to invalid IL or missing references)
        //IL_01c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_0271: Unknown result type (might be due to invalid IL or missing references)
        //IL_0276: Unknown result type (might be due to invalid IL or missing references)
        //IL_017c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0185: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0202: Unknown result type (might be due to invalid IL or missing references)
        //IL_0221: Unknown result type (might be due to invalid IL or missing references)
        //IL_022e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0245: Unknown result type (might be due to invalid IL or missing references)
        //IL_0239: Unknown result type (might be due to invalid IL or missing references)
        Point p = default(Point);
        ((Point)(ref p))._002Ector(1, 1);
        Vector2 vector = p.ToVector2();
        List<Point> tilesIn = Collision.GetTilesIn(PlayerLastPosition[player.whoAmI] + vector, PlayerLastPosition[player.whoAmI] + player.Size - vector * 2f);
        List<Point> tilesIn2 = Collision.GetTilesIn(player.TopLeft + vector, player.BottomRight - vector * 2f);
        Rectangle hitbox = player.Hitbox;
        Rectangle hitbox2 = player.Hitbox;
        ((Rectangle)(ref hitbox)).Inflate(-p.X, -p.Y);
        ((Rectangle)(ref hitbox2)).Inflate(-p.X, -p.Y);
        hitbox2.X = (int)PlayerLastPosition[player.whoAmI].X;
        hitbox2.Y = (int)PlayerLastPosition[player.whoAmI].Y;
        for (int i = 0; i < tilesIn.Count; i++)
        {
            Point point = tilesIn[i];
            Tile tile = Main.tile[point.X, point.Y];
            if (tile.active() && tile.type == 428)
            {
                pressurePlateBounds.X = point.X * 16;
                pressurePlateBounds.Y = point.Y * 16 + 16 - pressurePlateBounds.Height;
                if (!((Rectangle)(ref hitbox)).Intersects(pressurePlateBounds) && !tilesIn2.Contains(point))
                {
                    MoveAwayFrom(point, player.whoAmI);
                }
            }
        }
        for (int j = 0; j < tilesIn2.Count; j++)
        {
            Point point2 = tilesIn2[j];
            Tile tile2 = Main.tile[point2.X, point2.Y];
            if (tile2.active() && tile2.type == 428)
            {
                pressurePlateBounds.X = point2.X * 16;
                pressurePlateBounds.Y = point2.Y * 16 + 16 - pressurePlateBounds.Height;
                if (((Rectangle)(ref hitbox)).Intersects(pressurePlateBounds) && (!tilesIn.Contains(point2) || !((Rectangle)(ref hitbox2)).Intersects(pressurePlateBounds)))
                {
                    MoveInto(point2, player.whoAmI);
                }
            }
        }
        PlayerLastPosition[player.whoAmI] = player.position;
    }
References Terraria.Tile.active(), Terraria.Entity.BottomRight, Terraria.Collision.GetTilesIn(), Terraria.Entity.Hitbox, Terraria.GameContent.PressurePlateHelper.MoveAwayFrom(), Terraria.GameContent.PressurePlateHelper.MoveInto(), Terraria.GameContent.PressurePlateHelper.PlayerLastPosition, Terraria.Entity.position, Terraria.GameContent.PressurePlateHelper.pressurePlateBounds, Terraria.Entity.Size, Terraria.Main.tile, Terraria.Entity.TopLeft, Terraria.Tile.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Teleport(), and Terraria.Player.Update().