TModLoader: Terraria.ID.ProjectileSourceID.ToContextString
ToContextString()
static ? string Terraria.ID.ProjectileSourceID.ToContextString (int itemSourceId) inline static
    {
        return itemSourceId switch
        {
            1 => "SetBonus_SolarExplosion_WhenTakingDamage",
            2 => "SetBonus_SolarExplosion_WhenDashing",
            3 => "SetBonus_ForbiddenStorm",
            4 => "SetBonus_Titanium",
            5 => "SetBonus_Orichalcum",
            6 => "SetBonus_Chlorophyte",
            7 => "SetBonus_Stardust",
            8 => "WeaponEnchantment_Confetti",
            9 => "PlayerDeath_TombStone",
            11 => "FallingStar",
            12 => "PlayerHurt_DropFootball",
            13 => "StormTigerTierSwap",
            14 => "AbigailTierSwap",
            15 => "SetBonus_GhostHeal",
            16 => "SetBonus_GhostHurt",
            18 => "VampireKnives",
            10 => "TorchGod",
            _ => null,
        };
    }
Referenced by Terraria.Player.GetProjectileSource_Misc(), Terraria.Player.GetProjectileSource_OnHit(), Terraria.Projectile.GetProjectileSource_OnHit(), Terraria.Player.GetProjectileSource_OnHurt(), and Terraria.Player.GetProjectileSource_SetBonus().