TModLoader: Terraria.Graphics.Shaders.ArmorShaderData.Apply
Apply() [2/2]
virtual void Terraria.Graphics.Shaders.ArmorShaderData.Apply (Entity entity, DrawData? drawData = null) inline virtual
Reimplemented in Terraria.GameContent.Dyes.ReflectiveArmorShaderData, Terraria.GameContent.Dyes.TeamArmorShaderData, and Terraria.GameContent.Dyes.TwilightDyeShaderData.
    {
        //IL_0016: Unknown result type (might be due to invalid IL or missing references)
        //IL_0056: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ee: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e8: Unknown result type (might be due to invalid IL or missing references)
        //IL_00fa: Unknown result type (might be due to invalid IL or missing references)
        //IL_010c: Unknown result type (might be due to invalid IL or missing references)
        //IL_011e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0129: Unknown result type (might be due to invalid IL or missing references)
        //IL_0368: Unknown result type (might be due to invalid IL or missing references)
        //IL_0157: Unknown result type (might be due to invalid IL or missing references)
        //IL_016d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0188: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a3: Unknown result type (might be due to invalid IL or missing references)
        //IL_01a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_01ae: Unknown result type (might be due to invalid IL or missing references)
        //IL_01e5: Unknown result type (might be due to invalid IL or missing references)
        //IL_021c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0242: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03c5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03cd: Unknown result type (might be due to invalid IL or missing references)
        //IL_03d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_03dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_0406: Unknown result type (might be due to invalid IL or missing references)
        //IL_0281: Unknown result type (might be due to invalid IL or missing references)
        base.Shader.Parameters["uColor"].SetValue(_uColor);
        base.Shader.Parameters["uSaturation"].SetValue(_uSaturation);
        base.Shader.Parameters["uSecondaryColor"].SetValue(_uSecondaryColor);
        base.Shader.Parameters["uTime"].SetValue(Main.GlobalTimeWrappedHourly);
        base.Shader.Parameters["uOpacity"].SetValue(_uOpacity);
        base.Shader.Parameters["uTargetPosition"].SetValue(_uTargetPosition);
        if (drawData.HasValue)
        {
            DrawData value = drawData.Value;
            Vector4 value2 = ((!value.sourceRect.HasValue) ? new Vector4(0f, 0f, (float)value.texture.Width, (float)value.texture.Height) : new Vector4((float)value.sourceRect.Value.X, (float)value.sourceRect.Value.Y, (float)value.sourceRect.Value.Width, (float)value.sourceRect.Value.Height));
            base.Shader.Parameters["uSourceRect"].SetValue(value2);
            base.Shader.Parameters["uLegacyArmorSourceRect"].SetValue(value2);
            base.Shader.Parameters["uWorldPosition"].SetValue(Main.screenPosition + value.position);
            base.Shader.Parameters["uImageSize0"].SetValue(new Vector2((float)value.texture.Width, (float)value.texture.Height));
            base.Shader.Parameters["uLegacyArmorSheetSize"].SetValue(new Vector2((float)value.texture.Width, (float)value.texture.Height));
            base.Shader.Parameters["uRotation"].SetValue(value.rotation * (((Enum)value.effect).HasFlag((Enum)(object)(SpriteEffects)1) ? (-1f) : 1f));
            base.Shader.Parameters["uDirection"].SetValue((!((Enum)value.effect).HasFlag((Enum)(object)(SpriteEffects)1)) ? 1 : (-1));
        }
        else
        {
            Vector4 value3 = default(Vector4);
            ((Vector4)(ref value3))._002Ector(0f, 0f, 4f, 4f);
            base.Shader.Parameters["uSourceRect"].SetValue(value3);
            base.Shader.Parameters["uLegacyArmorSourceRect"].SetValue(value3);
            base.Shader.Parameters["uRotation"].SetValue(0f);
        }
        if (_uImage != null)
        {
            Main.graphics.GraphicsDevice.Textures[1] = (Texture)(object)_uImage.Value;
            base.Shader.Parameters["uImageSize1"].SetValue(new Vector2((float)_uImage.Width(), (float)_uImage.Height()));
        }
        if (entity != null)
        {
            base.Shader.Parameters["uDirection"].SetValue((float)entity.direction);
        }
        if (entity is Player { bodyFrame: var bodyFrame })
        {
            base.Shader.Parameters["uLegacyArmorSourceRect"].SetValue(new Vector4((float)bodyFrame.X, (float)bodyFrame.Y, (float)bodyFrame.Width, (float)bodyFrame.Height));
            base.Shader.Parameters["uLegacyArmorSheetSize"].SetValue(new Vector2(40f, 1120f));
        }
        Apply();
    }
References Terraria.Graphics.Shaders.ArmorShaderData._uColor, Terraria.Graphics.Shaders.ArmorShaderData._uImage, Terraria.Graphics.Shaders.ArmorShaderData._uOpacity, Terraria.Graphics.Shaders.ArmorShaderData._uSaturation, Terraria.Graphics.Shaders.ArmorShaderData._uSecondaryColor, Terraria.Graphics.Shaders.ArmorShaderData._uTargetPosition, Terraria.Graphics.Shaders.ShaderData.Apply(), Terraria.Entity.direction, Terraria.DataStructures.DrawData.effect, Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.graphics, Terraria.DataStructures.DrawData.position, Terraria.DataStructures.DrawData.rotation, Terraria.Main.screenPosition, Terraria.DataStructures.DrawData.sourceRect, and Terraria.DataStructures.DrawData.texture.
Referenced by Terraria.GameContent.Dyes.TeamArmorShaderData.Apply(), and Terraria.Main.DrawDust().