TModLoader: Terraria.GameContent.PlayerSleepingHelper.GetSleepingTargetInfo
GetSleepingTargetInfo()
static bool Terraria.GameContent.PlayerSleepingHelper.GetSleepingTargetInfo (int x, int y, out int targetDirection, out Vector2 anchorPosition, out Vector2 visualoffset) inline static
    {
        //IL_0025: Unknown result type (might be due to invalid IL or missing references)
        //IL_002d: Unknown result type (might be due to invalid IL or missing references)
        //IL_008b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0090: Unknown result type (might be due to invalid IL or missing references)
        //IL_009a: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00ab: Unknown result type (might be due to invalid IL or missing references)
        //IL_00b1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_00e2: Unknown result type (might be due to invalid IL or missing references)
        //IL_0103: Unknown result type (might be due to invalid IL or missing references)
        //IL_0108: Unknown result type (might be due to invalid IL or missing references)
        //IL_010f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0114: Unknown result type (might be due to invalid IL or missing references)
        //IL_011b: Unknown result type (might be due to invalid IL or missing references)
        //IL_012a: Unknown result type (might be due to invalid IL or missing references)
        //IL_012f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0146: Unknown result type (might be due to invalid IL or missing references)
        //IL_014b: Unknown result type (might be due to invalid IL or missing references)
        //IL_014d: Unknown result type (might be due to invalid IL or missing references)
        //IL_0152: Unknown result type (might be due to invalid IL or missing references)
        Tile tileSafely = Framing.GetTileSafely(x, y);
        if (!TileID.Sets.CanBeSleptIn[tileSafely.type] || !tileSafely.active())
        {
            targetDirection = 1;
            anchorPosition = default(Vector2);
            visualoffset = default(Vector2);
            return false;
        }
        int num = y;
        int num4 = x - tileSafely.frameX % 72 / 18;
        if (tileSafely.frameY % 36 != 0)
        {
            num--;
        }
        targetDirection = 1;
        int num2 = tileSafely.frameX / 72;
        int num3 = num4;
        switch (num2)
        {
        case 0:
            targetDirection = -1;
            num3++;
            break;
        case 1:
            num3 += 2;
            break;
        }
        visualoffset = SetOffsetbyBed(tileSafely.frameY / 36);
        TileRestingInfo info = new TileRestingInfo(null, new Point(num3, num), visualoffset, targetDirection);
        TileLoader.ModifySleepingTargetInfo(x, y, tileSafely.type, ref info);
        num3 = info.AnchorTilePosition.X;
        num = info.AnchorTilePosition.Y;
        int directionOffset = info.DirectionOffset;
        targetDirection = info.TargetDirection;
        visualoffset = info.VisualOffset;
        Vector2 finalOffset = info.FinalOffset;
        anchorPosition = Utils.ToWorldCoordinates(new Point(num3, num + 1), 8f, 16f);
        anchorPosition.X += targetDirection * directionOffset;
        anchorPosition += finalOffset;
        return true;
    }
References Terraria.ID.TileID.Sets.CanBeSleptIn, Terraria.Framing.GetTileSafely(), Terraria.ModLoader.TileLoader.ModifySleepingTargetInfo(), Terraria.GameContent.PlayerSleepingHelper.SetOffsetbyBed(), and Terraria.Utils.ToWorldCoordinates().
Referenced by Terraria.GameContent.PlayerSleepingHelper.StartSleeping(), and Terraria.GameContent.PlayerSleepingHelper.UpdateState().