TModLoader: Terraria.GameContent.PlayerSleepingHelper.UpdateState
UpdateState()
void Terraria.GameContent.PlayerSleepingHelper.UpdateState (Player player) inline
Definition at line 92 of file PlayerSleepingHelper.cs.
    {
        //IL_002f: Unknown result type (might be due to invalid IL or missing references)
        //IL_003e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0043: Unknown result type (might be due to invalid IL or missing references)
        //IL_0048: Unknown result type (might be due to invalid IL or missing references)
        //IL_004d: Unknown result type (might be due to invalid IL or missing references)
        //IL_004e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0054: Unknown result type (might be due to invalid IL or missing references)
        //IL_0126: Unknown result type (might be due to invalid IL or missing references)
        //IL_0140: Unknown result type (might be due to invalid IL or missing references)
        //IL_0141: Unknown result type (might be due to invalid IL or missing references)
        //IL_0151: Unknown result type (might be due to invalid IL or missing references)
        if (!isSleeping)
        {
            timeSleeping = 0;
            return;
        }
        timeSleeping++;
        if (DoesPlayerHaveReasonToActUpInBed(player))
        {
            timeSleeping = 0;
        }
        Point coords = (player.Bottom + new Vector2(0f, -2f)).ToTileCoordinates();
        if (!GetSleepingTargetInfo(coords.X, coords.Y, out var targetDirection, out var _, out var visualoffset))
        {
            StopSleeping(player);
            return;
        }
        if (player.controlLeft || player.controlRight || player.controlUp || player.controlDown || player.controlJump || player.pulley || player.mount.Active || targetDirection != player.direction)
        {
            StopSleeping(player);
        }
        bool flag = false;
        if (player.itemAnimation > 0)
        {
            Item heldItem = player.HeldItem;
            if (heldItem.damage > 0 && !heldItem.noMelee)
            {
                flag = true;
            }
            if (heldItem.fishingPole > 0)
            {
                flag = true;
            }
            bool? flag2 = ItemID.Sets.ForcesBreaksSleeping[heldItem.type];
            if (flag2.HasValue)
            {
                flag = flag2.Value;
            }
        }
        if (flag)
        {
            StopSleeping(player);
        }
        if (Main.sleepingManager.GetNextPlayerStackIndexInCoords(coords) >= 2)
        {
            StopSleeping(player);
        }
        if (isSleeping)
        {
            visualOffsetOfBedBase = visualoffset;
            Main.sleepingManager.AddPlayerAndGetItsStackedIndexInCoords(player.whoAmI, coords, out sleepingIndex);
        }
    }
References Terraria.Mount.Active, Terraria.DataStructures.AnchoredEntitiesCollection.AddPlayerAndGetItsStackedIndexInCoords(), Terraria.Player.controlDown, Terraria.Player.controlJump, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.controlUp, Terraria.Item.damage, Terraria.Entity.direction, Terraria.GameContent.PlayerSleepingHelper.DoesPlayerHaveReasonToActUpInBed(), Terraria.Item.fishingPole, Terraria.ID.ItemID.Sets.ForcesBreaksSleeping, Terraria.DataStructures.AnchoredEntitiesCollection.GetNextPlayerStackIndexInCoords(), Terraria.GameContent.PlayerSleepingHelper.GetSleepingTargetInfo(), Terraria.Player.HeldItem, Terraria.GameContent.PlayerSleepingHelper.isSleeping, Terraria.Player.itemAnimation, Terraria.Player.mount, Terraria.Item.noMelee, Terraria.Player.pulley, Terraria.GameContent.PlayerSleepingHelper.sleepingIndex, Terraria.Main.sleepingManager, Terraria.GameContent.PlayerSleepingHelper.StopSleeping(), Terraria.GameContent.PlayerSleepingHelper.timeSleeping, Terraria.Item.type, Terraria.GameContent.PlayerSleepingHelper.visualOffsetOfBedBase, and Terraria.Entity.whoAmI.
Referenced by Terraria.Player.Update().