TModLoader: Terraria.ModLoader.UI.UIModInfo.DeleteMod
DeleteMod()
void Terraria.ModLoader.UI.UIModInfo.DeleteMod (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 407 of file UIModInfo.cs.
    {
        SoundEngine.PlaySound(in SoundID.MenuClose);
        ModOrganizer.DeleteMod(_localMod);
        Main.menuMode = _gotoMenu;
    }
References Terraria.ModLoader.UI.UIModInfo._gotoMenu, Terraria.ModLoader.UI.UIModInfo._localMod, Terraria.ModLoader.Core.ModOrganizer.DeleteMod(), Terraria.ID.SoundID.MenuClose, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.ModLoader.UI.UIModInfo.OnInitialize().