TModLoader: Terraria.ModLoader.UI.UIModInfo.OnActivate
OnActivate()
override void Terraria.ModLoader.UI.UIModInfo.OnActivate () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 450 of file UIModInfo.cs.
    {
        _modInfo.SetText(_info);
        _uITextPanel.SetText(Language.GetTextValue("tModLoader.ModInfoHeader") + _modDisplayName, 0.8f, large: true);
        _loading = false;
        _ready = true;
    }
References Terraria.ModLoader.UI.UIModInfo._info, Terraria.ModLoader.UI.UIModInfo._loading, Terraria.ModLoader.UI.UIModInfo._modDisplayName, Terraria.ModLoader.UI.UIModInfo._modInfo, Terraria.ModLoader.UI.UIModInfo._ready, Terraria.ModLoader.UI.UIModInfo._uITextPanel, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.UIMessageBox.SetText(), and Terraria.GameContent.UI.Elements.UITextPanel< T >.SetText().