TModLoader: Terraria.ModLoader.UI.UIModInfo.Update
Update()
override void Terraria.ModLoader.UI.UIModInfo.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 458 of file UIModInfo.cs.
    {
        if (!_loading && _ready)
        {
            _modInfo.SetText(_info);
            if (!string.IsNullOrEmpty(_url))
            {
                _uIElement.Append(_modHomepageButton);
            }
            if (!string.IsNullOrEmpty(_publishedFileId.m_ModPubId))
            {
                _uIElement.Append(_modSteamButton);
            }
            if (_localMod != null)
            {
                bool realDeleteButton = ModLoader.Mods.All((Mod x) => x.Name != _localMod.Name);
                _uIElement.AddOrRemoveChild(_deleteButton, realDeleteButton);
                _uIElement.AddOrRemoveChild(_fakeDeleteButton, !realDeleteButton);
                _uIElement.AddOrRemoveChild(extractLocalizationButton, !realDeleteButton);
                _uIElement.AddOrRemoveChild(fakeExtractLocalizationButton, realDeleteButton);
                extractLocalizationButton.SetText(Language.GetTextValue("tModLoader.ModInfoExtractLocalization"));
                _uIElement.Append(_extractButton);
            }
            Recalculate();
            _modInfo.RemoveChild(_loaderElement);
            _ready = false;
        }
        base.Update(gameTime);
    }
References Terraria.ModLoader.UI.UIModInfo._deleteButton, Terraria.ModLoader.UI.UIModInfo._extractButton, Terraria.ModLoader.UI.UIModInfo._fakeDeleteButton, Terraria.ModLoader.UI.UIModInfo._info, Terraria.ModLoader.UI.UIModInfo._loaderElement, Terraria.ModLoader.UI.UIModInfo._loading, Terraria.ModLoader.UI.UIModInfo._localMod, Terraria.ModLoader.UI.UIModInfo._modHomepageButton, Terraria.ModLoader.UI.UIModInfo._modInfo, Terraria.ModLoader.UI.UIModInfo._modSteamButton, Terraria.ModLoader.UI.UIModInfo._publishedFileId, Terraria.ModLoader.UI.UIModInfo._ready, Terraria.ModLoader.UI.UIModInfo._uIElement, Terraria.ModLoader.UI.UIModInfo._url, Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UIModInfo.extractLocalizationButton, Terraria.ModLoader.UI.UIModInfo.fakeExtractLocalizationButton, Terraria.Localization.Language.GetTextValue(), Terraria.Social.Base.ModPubId_t.m_ModPubId, Terraria.ModLoader.ModLoader.Mods, Terraria.ModLoader.Core.LocalMod.Name, Terraria.ModLoader.Mod.Name, Terraria.UI.UIElement.Recalculate(), Terraria.UI.UIElement.RemoveChild(), Terraria.ModLoader.UI.UIMessageBox.SetText(), and Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.SetText().