TModLoader: Terraria.ModLoader.UI.UIModInfo.OnInitialize
OnInitialize()
override void Terraria.ModLoader.UI.UIModInfo.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
    {
        //IL_00a1: Unknown result type (might be due to invalid IL or missing references)
        //IL_00a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_0194: Unknown result type (might be due to invalid IL or missing references)
        //IL_0199: Unknown result type (might be due to invalid IL or missing references)
        //IL_022c: Unknown result type (might be due to invalid IL or missing references)
        //IL_0232: Unknown result type (might be due to invalid IL or missing references)
        //IL_0235: Unknown result type (might be due to invalid IL or missing references)
        //IL_023b: Unknown result type (might be due to invalid IL or missing references)
        //IL_023e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0244: Unknown result type (might be due to invalid IL or missing references)
        //IL_0247: Unknown result type (might be due to invalid IL or missing references)
        //IL_024d: Unknown result type (might be due to invalid IL or missing references)
        //IL_02dd: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e3: Unknown result type (might be due to invalid IL or missing references)
        //IL_02e6: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ec: Unknown result type (might be due to invalid IL or missing references)
        //IL_02ef: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f5: Unknown result type (might be due to invalid IL or missing references)
        //IL_02f8: Unknown result type (might be due to invalid IL or missing references)
        //IL_02fe: Unknown result type (might be due to invalid IL or missing references)
        //IL_038e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0394: Unknown result type (might be due to invalid IL or missing references)
        //IL_0397: Unknown result type (might be due to invalid IL or missing references)
        //IL_039d: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a0: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a6: Unknown result type (might be due to invalid IL or missing references)
        //IL_03a9: Unknown result type (might be due to invalid IL or missing references)
        //IL_03af: Unknown result type (might be due to invalid IL or missing references)
        //IL_0448: Unknown result type (might be due to invalid IL or missing references)
        //IL_044d: Unknown result type (might be due to invalid IL or missing references)
        //IL_04b4: Unknown result type (might be due to invalid IL or missing references)
        //IL_04ba: Unknown result type (might be due to invalid IL or missing references)
        //IL_04bd: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c3: Unknown result type (might be due to invalid IL or missing references)
        //IL_04c6: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cc: Unknown result type (might be due to invalid IL or missing references)
        //IL_04cf: Unknown result type (might be due to invalid IL or missing references)
        //IL_04d5: Unknown result type (might be due to invalid IL or missing references)
        //IL_0568: Unknown result type (might be due to invalid IL or missing references)
        //IL_056e: Unknown result type (might be due to invalid IL or missing references)
        //IL_0571: Unknown result type (might be due to invalid IL or missing references)
        //IL_0577: Unknown result type (might be due to invalid IL or missing references)
        //IL_057a: Unknown result type (might be due to invalid IL or missing references)
        //IL_0580: Unknown result type (might be due to invalid IL or missing references)
        //IL_0583: Unknown result type (might be due to invalid IL or missing references)
        //IL_0589: Unknown result type (might be due to invalid IL or missing references)
        //IL_0619: Unknown result type (might be due to invalid IL or missing references)
        //IL_061f: Unknown result type (might be due to invalid IL or missing references)
        //IL_0622: Unknown result type (might be due to invalid IL or missing references)
        //IL_0628: Unknown result type (might be due to invalid IL or missing references)
        //IL_062b: Unknown result type (might be due to invalid IL or missing references)
        //IL_0631: Unknown result type (might be due to invalid IL or missing references)
        //IL_0634: Unknown result type (might be due to invalid IL or missing references)
        //IL_063a: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d3: Unknown result type (might be due to invalid IL or missing references)
        //IL_06d8: Unknown result type (might be due to invalid IL or missing references)
        _uIElement = new UIElement
        {
            Width =
            {
                Percent = 0.8f
            },
            MaxWidth = new StyleDimension(800f, 0f),
            Top =
            {
                Pixels = 220f
            },
            Height =
            {
                Pixels = -220f,
                Percent = 1f
            },
            HAlign = 0.5f
        };
        UIPanel uIPanel = new UIPanel
        {
            Width =
            {
                Percent = 1f
            },
            Height =
            {
                Pixels = -110f,
                Percent = 1f
            },
            BackgroundColor = UICommon.MainPanelBackground
        };
        _uIElement.Append(uIPanel);
        _modInfo = new UIMessageBox(string.Empty)
        {
            Width =
            {
                Pixels = -25f,
                Percent = 1f
            },
            Height =
            {
                Percent = 1f
            }
        };
        uIPanel.Append(_modInfo);
        UIScrollbar uIScrollbar = new UIScrollbar
        {
            Height =
            {
                Pixels = -12f,
                Percent = 1f
            },
            VAlign = 0.5f,
            HAlign = 1f
        }.WithView(100f, 1000f);
        uIPanel.Append(uIScrollbar);
        _modInfo.SetScrollbar(uIScrollbar);
        _uITextPanel = new UITextPanel<string>(Language.GetTextValue("tModLoader.ModInfoHeader"), 0.8f, large: true)
        {
            HAlign = 0.5f,
            Top =
            {
                Pixels = -35f
            },
            BackgroundColor = UICommon.DefaultUIBlue
        }.WithPadding(15f);
        _uIElement.Append(_uITextPanel);
        _modHomepageButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModInfoVisitHomepage"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.333f
            },
            Height =
            {
                Pixels = 40f
            },
            HAlign = 0.5f,
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            }
        }.WithFadedMouseOver();
        _modHomepageButton.OnLeftClick += VisitModHomePage;
        _modSteamButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModInfoVisitSteampage"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.333f
            },
            Height =
            {
                Pixels = 40f
            },
            HAlign = 0f,
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            }
        }.WithFadedMouseOver();
        _modSteamButton.OnLeftClick += VisitModHostPage;
        extractLocalizationButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModInfoExtractLocalization"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.333f
            },
            Height =
            {
                Pixels = 40f
            },
            HAlign = 1f,
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            }
        }.WithFadedMouseOver();
        extractLocalizationButton.OnLeftClick += ExtractLocalization;
        fakeExtractLocalizationButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModInfoExtractLocalization"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.333f
            },
            Height =
            {
                Pixels = 40f
            },
            HAlign = 1f,
            VAlign = 1f,
            Top =
            {
                Pixels = -65f
            }
        };
        fakeExtractLocalizationButton.BackgroundColor = Color.Gray;
        UIAutoScaleTextTextPanel<string> backButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("UI.Back"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.333f
            },
            Height =
            {
                Pixels = 40f
            },
            VAlign = 1f,
            Top =
            {
                Pixels = -20f
            }
        }.WithFadedMouseOver();
        backButton.OnLeftClick += BackClick;
        _uIElement.Append(backButton);
        _extractButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("tModLoader.ModInfoExtract"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.333f
            },
            Height =
            {
                Pixels = 40f
            },
            VAlign = 1f,
            HAlign = 0.5f,
            Top =
            {
                Pixels = -20f
            }
        }.WithFadedMouseOver();
        _extractButton.OnLeftClick += ExtractMod;
        _deleteButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("UI.Delete"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.333f
            },
            Height =
            {
                Pixels = 40f
            },
            VAlign = 1f,
            HAlign = 1f,
            Top =
            {
                Pixels = -20f
            }
        }.WithFadedMouseOver();
        _deleteButton.OnLeftClick += DeleteMod;
        _fakeDeleteButton = new UIAutoScaleTextTextPanel<string>(Language.GetTextValue("UI.Delete"))
        {
            Width =
            {
                Pixels = -10f,
                Percent = 0.333f
            },
            Height =
            {
                Pixels = 40f
            },
            VAlign = 1f,
            HAlign = 1f,
            Top =
            {
                Pixels = -20f
            }
        };
        _fakeDeleteButton.BackgroundColor = Color.Gray;
        Append(_uIElement);
    }
References Terraria.ModLoader.UI.UIModInfo._deleteButton, Terraria.ModLoader.UI.UIModInfo._extractButton, Terraria.ModLoader.UI.UIModInfo._fakeDeleteButton, Terraria.ModLoader.UI.UIModInfo._modHomepageButton, Terraria.ModLoader.UI.UIModInfo._modInfo, Terraria.ModLoader.UI.UIModInfo._modSteamButton, Terraria.ModLoader.UI.UIModInfo._uIElement, Terraria.ModLoader.UI.UIModInfo._uITextPanel, Terraria.UI.UIElement.Append(), Terraria.ModLoader.UI.UIModInfo.BackClick(), Terraria.ModLoader.UI.UIModInfo.DeleteMod(), Terraria.ModLoader.UI.UIModInfo.ExtractLocalization(), Terraria.ModLoader.UI.UIModInfo.extractLocalizationButton, Terraria.ModLoader.UI.UIModInfo.ExtractMod(), Terraria.ModLoader.UI.UIModInfo.fakeExtractLocalizationButton, Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.MaxWidth, Terraria.ModLoader.UI.UIMessageBox.SetScrollbar(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, Terraria.ModLoader.UI.UIModInfo.VisitModHomePage(), Terraria.ModLoader.UI.UIModInfo.VisitModHostPage(), and Terraria.UI.UIElement.Width.