TModLoader: Terraria.ModLoader.UI.UIModInfo.ExtractLocalization
ExtractLocalization()
void Terraria.ModLoader.UI.UIModInfo.ExtractLocalization (UIMouseEvent evt, UIElement listeningElement) inline private
    {
        SoundEngine.PlaySound(in SoundID.MenuOpen);
        if (LocalizationLoader.ExtractLocalizationFiles(_modName))
        {
            extractLocalizationButton.SetText(Language.GetTextValue("tModLoader.ModInfoExtracted"));
        }
    }
References Terraria.ModLoader.UI.UIModInfo._modName, Terraria.ModLoader.UI.UIModInfo.extractLocalizationButton, Terraria.ModLoader.LocalizationLoader.ExtractLocalizationFiles(), Terraria.Localization.Language.GetTextValue(), Terraria.ID.SoundID.MenuOpen, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.ModLoader.UI.UIAutoScaleTextTextPanel< T >.SetText().
Referenced by Terraria.ModLoader.UI.UIModInfo.OnInitialize().