TModLoader: Terraria.ModLoader.UI.UIBuildMod.BuildMod
BuildMod()
Task Terraria.ModLoader.UI.UIBuildMod.BuildMod (Action< ModCompile > buildAction, bool reload) inline private
Definition at line 82 of file UIBuildMod.cs.
    {
        while (_progressBar == null || _cts == null)
        {
            Task.Delay(1);
        }
        try
        {
            buildAction(new ModCompile(this));
            Main.menuMode = (reload ? 10006 : 10001);
        }
        catch (OperationCanceledException)
        {
            Logging.tML.Info((object)"Mod building was cancelled.");
            return Task.FromResult(result: false);
        }
        catch (Exception e)
        {
            Logging.tML.Error((object)e.Message, e);
            object mod = (e.Data.Contains("mod") ? e.Data["mod"] : null);
            string msg = Language.GetTextValue("tModLoader.BuildError", mod ?? "");
            Action retry = null;
            if (e is BuildException)
            {
                msg = msg + "\n" + e.Message + "\n\n" + e.InnerException;
                retry = delegate
                {
                    Interface.buildMod.Build(buildAction, reload);
                };
            }
            else
            {
                msg += $"\n\n{e}";
            }
            Interface.errorMessage.Show(msg, 10001, null, e.HelpLink, continueIsRetry: false, showSkip: false, retry);
            return Task.FromResult(result: false);
        }
        return Task.FromResult(result: true);
    }
References Terraria.ModLoader.UI.UIBuildMod._cts, Terraria.ModLoader.UI.UIProgress._progressBar, Terraria.ModLoader.UI.UIBuildMod.Build(), Terraria.ModLoader.UI.Interface.buildMod, Terraria.ModLoader.UI.Interface.errorMessage, Terraria.Localization.Language.GetTextValue(), Terraria.ModLoader.UI.UIErrorMessage.Show(), and Terraria.ModLoader.Logging.tML.
Referenced by Terraria.ModLoader.UI.UIBuildMod.Build().