TModLoader: Terraria.ModLoader.UI.UIBuildMod.Build
Build() [2/2]
void Terraria.ModLoader.UI.UIBuildMod.Build (string mod, bool reload) inline package
Definition at line 37 of file UIBuildMod.cs.
    {
        Build(delegate(ModCompile mc)
        {
            mc.Build(mod);
        }, reload);
    }
References Terraria.ModLoader.UI.UIBuildMod.Build().
Referenced by Terraria.ModLoader.UI.UIBuildMod.Build(), Terraria.ModLoader.UI.UIBuildMod.BuildAll(), Terraria.ModLoader.UI.UIModSourceItem.BuildAndReload(), Terraria.ModLoader.UI.UIBuildMod.BuildMod(), and Terraria.ModLoader.UI.UIModSourceItem.BuildMod().